USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_MA_HULL_VENDOR_ITEM_XML]    Script Date: 2015-10-26 오후 7:56:46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




ALTER PROCEDURE [NEOE].[SP_CZ_MA_HULL_VENDOR_ITEM_XML] 
(
	@P_XML			XML, 
	@P_ID_USER		NVARCHAR(10), 
    @DOC				INT = NULL
) 
AS 

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

EXEC SP_XML_PREPAREDOCUMENT @DOC OUTPUT, @P_XML 

-- ================================================== DELETE
DELETE A 
FROM CZ_MA_HULL_VENDOR_ITEM A 
JOIN OPENXML (@DOC, '/XML/D', 2) 
        WITH (NO_IMO		NVARCHAR(10),
		      CD_VENDOR		NVARCHAR(20),
			  NO_TYPE 		INT,
			  NO_ITEM 		INT) B 
ON A.NO_IMO = B.NO_IMO
AND A.CD_VENDOR = B.CD_VENDOR
AND A.NO_TYPE = B.NO_TYPE
AND A.NO_ITEM = B.NO_ITEM
-- ================================================== INSERT
INSERT INTO CZ_MA_HULL_VENDOR_ITEM 
(
	NO_IMO,
	CD_VENDOR,
	NO_TYPE,
	NO_ITEM,
	CD_ITEM,
	QT_ITEM,
	NO_PART,
	NM_PART,
	DC_MODEL,
	NO_POS,
	UCODE,
	UCODE2,
	NO_DRAWING,
	NO_DRAWING2,
	UNIT,
	DC_RMK,
	DC_RMK1,
	DC_RMK2,
	DC_RMK3,
	DC_RMK4,
	DC_RMK5,
	DC_RMK6,
	DC_RMK7,
	DC_RMK8,
	DC_RMK9,
	DC_RMK10,
	DXDESC,
	ID_INSERT,
	DTS_INSERT
)
SELECT NO_IMO,
	   CD_VENDOR,
	   NO_TYPE,
	   NO_ITEM,
	   CD_ITEM,
	   QT_ITEM,
	   NO_PART,
	   NM_PART,
	   DC_MODEL,
	   NO_POS,
	   UCODE,
	   UCODE2,
	   NO_DRAWING,
	   NO_DRAWING2,
	   UNIT,
	   REPLACE(DC_RMK, CHAR(10), CHAR(13) + CHAR(10)),
	   REPLACE(DC_RMK1, CHAR(10), CHAR(13) + CHAR(10)),
	   REPLACE(DC_RMK2, CHAR(10), CHAR(13) + CHAR(10)),
	   REPLACE(DC_RMK3, CHAR(10), CHAR(13) + CHAR(10)),
	   REPLACE(DC_RMK4, CHAR(10), CHAR(13) + CHAR(10)),
	   REPLACE(DC_RMK5, CHAR(10), CHAR(13) + CHAR(10)),
	   REPLACE(DC_RMK6, CHAR(10), CHAR(13) + CHAR(10)),
	   REPLACE(DC_RMK7, CHAR(10), CHAR(13) + CHAR(10)),
	   REPLACE(DC_RMK8, CHAR(10), CHAR(13) + CHAR(10)),
	   REPLACE(DC_RMK9, CHAR(10), CHAR(13) + CHAR(10)),
	   REPLACE(DC_RMK10, CHAR(10), CHAR(13) + CHAR(10)),
	   '   ' + REPLACE(NEOE.FN_CZ_SINGLE_SPACE(CONCAT(NO_PART, ' ' + NM_PART, ' ' + DC_MODEL, ' ' + NO_POS, ' ' + UCODE, ' ' + UCODE2, ' ' + NO_DRAWING, ' ' + NO_DRAWING2, ' ' + DC_RMK1, ' ' + DC_RMK2, ' ' + DC_RMK3, ' ' + DC_RMK4, ' ' + DC_RMK5, ' ' + DC_RMK6, ' ' + DC_RMK7, ' ' + DC_RMK8, ' ' + DC_RMK9, ' ' + DC_RMK10 + ' ' + DC_RMK)), ' ', '   ') + '   ' AS DXDESC,
       @P_ID_USER, 
       NEOE.SF_SYSDATE(GETDATE()) 
  FROM OPENXML (@DOC, '/XML/I', 2) 
          WITH (NO_IMO			NVARCHAR(10),
				CD_VENDOR		NVARCHAR(20),
				NO_TYPE			INT,
				NO_ITEM			INT,
				CD_ITEM			NVARCHAR(20),
				QT_ITEM			NUMERIC(11, 0),
				NO_PART			NVARCHAR(100),
				NM_PART			NVARCHAR(500),
				DC_MODEL		    NVARCHAR(100),
				NO_POS				NVARCHAR(100),
				UCODE				NVARCHAR(100),
				UCODE2			NVARCHAR(100),
				NO_DRAWING		NVARCHAR(100),
				NO_DRAWING2	NVARCHAR(100),
				UNIT					NVARCHAR(4),
				DC_RMK				NVARCHAR(500),
				DC_RMK1			NVARCHAR(500),
				DC_RMK2			NVARCHAR(500),
				DC_RMK3			NVARCHAR(500),
				DC_RMK4			NVARCHAR(500),
				DC_RMK5			NVARCHAR(500),
				DC_RMK6			NVARCHAR(500),
				DC_RMK7			NVARCHAR(500),
				DC_RMK8			NVARCHAR(500),
				DC_RMK9			NVARCHAR(500),
				DC_RMK10			NVARCHAR(500)) 
-- ================================================== UPDATE    
UPDATE A 
   SET A.CD_ITEM = B.CD_ITEM,
	   A.QT_ITEM = B.QT_ITEM,
	   A.NO_PART = (CASE WHEN ISNULL(A.CD_ITEM, '') = '' OR A.CD_VENDOR = '02428' THEN B.NO_PART ELSE A.NO_PART END),
	   A.NM_PART = (CASE WHEN ISNULL(A.CD_ITEM, '') = '' THEN B.NM_PART ELSE A.NM_PART END),
	   A.DC_MODEL = (CASE WHEN ISNULL(A.CD_ITEM, '') = '' OR A.CD_VENDOR = '02428' THEN B.DC_MODEL ELSE A.DC_MODEL END),
	   A.NO_POS = (CASE WHEN ISNULL(A.CD_ITEM, '') = '' OR A.CD_VENDOR = '02428' THEN B.NO_POS ELSE A.NO_POS END),
	   A.UCODE = (CASE WHEN ISNULL(A.CD_ITEM, '') = '' OR A.CD_VENDOR = '02428' THEN B.UCODE ELSE A.UCODE END),
	   A.UCODE2 = (CASE WHEN ISNULL(A.CD_ITEM, '') = '' OR A.CD_VENDOR = '02428' THEN B.UCODE2 ELSE A.UCODE2 END),
	   A.NO_DRAWING = (CASE WHEN ISNULL(A.CD_ITEM, '') = '' OR A.CD_VENDOR = '02428' THEN B.NO_DRAWING ELSE A.NO_DRAWING END),
	   A.NO_DRAWING2 = (CASE WHEN ISNULL(A.CD_ITEM, '') = '' OR A.CD_VENDOR = '02428' THEN B.NO_DRAWING2 ELSE A.NO_DRAWING2 END),
	   A.UNIT = (CASE WHEN ISNULL(A.CD_ITEM, '') = '' OR A.CD_VENDOR = '02428' THEN B.UNIT ELSE A.UNIT END),
	   A.DC_RMK = REPLACE(B.DC_RMK, CHAR(10), CHAR(13) + CHAR(10)),
	   A.DC_RMK1 = REPLACE(B.DC_RMK1, CHAR(10), CHAR(13) + CHAR(10)),
	   A.DC_RMK2 = REPLACE(B.DC_RMK2, CHAR(10), CHAR(13) + CHAR(10)),
	   A.DC_RMK3 = REPLACE(B.DC_RMK3, CHAR(10), CHAR(13) + CHAR(10)),
	   A.DC_RMK4 = REPLACE(B.DC_RMK4, CHAR(10), CHAR(13) + CHAR(10)),
	   A.DC_RMK5 = REPLACE(B.DC_RMK5, CHAR(10), CHAR(13) + CHAR(10)),
	   A.DC_RMK6 = REPLACE(B.DC_RMK6, CHAR(10), CHAR(13) + CHAR(10)),
	   A.DC_RMK7 = REPLACE(B.DC_RMK7, CHAR(10), CHAR(13) + CHAR(10)),
	   A.DC_RMK8 = REPLACE(B.DC_RMK8, CHAR(10), CHAR(13) + CHAR(10)),
	   A.DC_RMK9 = REPLACE(B.DC_RMK9, CHAR(10), CHAR(13) + CHAR(10)),
	   A.DC_RMK10 = REPLACE(B.DC_RMK10, CHAR(10), CHAR(13) + CHAR(10)),
	   A.DXDESC = '   ' + REPLACE(NEOE.FN_CZ_SINGLE_SPACE(CONCAT(B.NO_PART, ' ' + B.NM_PART, ' ' + B.DC_MODEL, ' ' + B.NO_POS, ' ' + B.UCODE, ' ' + B.UCODE2, ' ' + B.NO_DRAWING, ' ' + B.NO_DRAWING2, ' ' + B.DC_RMK1, ' ' + B.DC_RMK2, ' ' + B.DC_RMK3, ' ' + B.DC_RMK4, ' ' + B.DC_RMK5, ' ' + B.DC_RMK6)), ' ', '   ') + '   ',
	   A.ID_UPDATE = @P_ID_USER, 
	   A.DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE())
  FROM CZ_MA_HULL_VENDOR_ITEM A 
  JOIN OPENXML (@DOC, '/XML/U', 2) 
          WITH (NO_IMO				NVARCHAR(10),
				   CD_VENDOR		NVARCHAR(20),
				   NO_TYPE				INT,
				   NO_ITEM				INT,
				   CD_ITEM				NVARCHAR(20),
				   QT_ITEM				NUMERIC(11, 0),
				   NO_PART			NVARCHAR(100),
				   NM_PART			NVARCHAR(500),
				   DC_MODEL		    NVARCHAR(100),
				   NO_POS				NVARCHAR(100),
				   UCODE				NVARCHAR(100),
				   UCODE2				NVARCHAR(100),
				   NO_DRAWING		NVARCHAR(100),
				   NO_DRAWING2	NVARCHAR(100),
				   UNIT					NVARCHAR(4),
				   DC_RMK				NVARCHAR(500),
				   DC_RMK1			NVARCHAR(500),
				   DC_RMK2			NVARCHAR(500),
				   DC_RMK3			NVARCHAR(500),
				   DC_RMK4			NVARCHAR(500),
				   DC_RMK5			NVARCHAR(500),
				   DC_RMK6			NVARCHAR(500),
				   DC_RMK7			NVARCHAR(500),
				   DC_RMK8			NVARCHAR(500),
				   DC_RMK9			NVARCHAR(500),
				   DC_RMK10			NVARCHAR(500)) B 
  ON A.NO_IMO = B.NO_IMO 
  AND A.CD_VENDOR = B.CD_VENDOR
  AND A.NO_TYPE = B.NO_TYPE
  AND A.NO_ITEM = B.NO_ITEM

EXEC SP_XML_REMOVEDOCUMENT @DOC 

GO

