USE [NeoBizboxS2]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_CUST_REL_MNGH_S]    Script Date: 2017-05-23 오전 9:44:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER PROCEDURE [BX].[SP_CZ_SA_CRM_EMP_TODOLIST_XML]
(
	@P_XML			XML, 
	@P_NO_EMP		NVARCHAR(10), 
    @DOC			INT = NULL
) 
AS
 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

EXEC SP_XML_PREPAREDOCUMENT @DOC OUTPUT, @P_XML

DECLARE @V_ID_USER INT
DECLARE @V_TODO_ID INT

DECLARE @V_CATEGORY_ID INT,
	    @V_TITLE NVARCHAR(500),
	    @V_CONTENTS NVARCHAR(MAX),
		@V_PROC_CONTENTS NVARCHAR(MAX),
		@V_PROC_RATE NUMERIC(3, 0),
		@V_START_DT NVARCHAR(8),
		@V_END_DT NVARCHAR(8),
		@V_ORDERBY NVARCHAR(10),
		@V_END_YN NVARCHAR(1)

SELECT @V_ID_USER = USER_ID
FROM BX.TCMG_USER
WHERE LOGON_CD = @P_NO_EMP

-- ================================================== DELETE
UPDATE A
SET A.DEL_YN = '1',
	A.MODIFY_BY = @V_ID_USER,
	A.MODIFY_DT = GETDATE()
FROM BX.TSOG_TODOLIST A 
JOIN OPENXML (@DOC, '/XML/ROW', 2) 
        WITH (TODO_ID INT,
			  XML_FLAG NVARCHAR(1)) B 
ON A.TODO_ID = B.TODO_ID
AND B.XML_FLAG = 'D'
-- ================================================== INSERT
DECLARE CUR_CZ_SA_CRM_EMP_SCHEDULE CURSOR FOR
SELECT CATEGORY_ID,
	   TITLE,
	   CONTENTS,
	   PROC_CONTENTS,
	   PROC_RATE,
	   START_DT,
	   END_DT,
	   ORDERBY,
	   END_YN
FROM OPENXML (@DOC, '/XML/ROW', 2) 
        WITH (CATEGORY_ID INT,
	          TITLE NVARCHAR(500),
	          CONTENTS NVARCHAR(MAX),
		      PROC_CONTENTS NVARCHAR(MAX),
		      PROC_RATE NUMERIC(3, 0),
		      START_DT NVARCHAR(8),
		      END_DT NVARCHAR(8),
		      ORDERBY NVARCHAR(10),
			  END_YN NVARCHAR(1),
			  XML_FLAG NVARCHAR(1))
WHERE XML_FLAG = 'I'

OPEN CUR_CZ_SA_CRM_EMP_SCHEDULE
FETCH NEXT FROM CUR_CZ_SA_CRM_EMP_SCHEDULE INTO @V_CATEGORY_ID,
												@V_TITLE,
												@V_CONTENTS,
												@V_PROC_CONTENTS,
												@V_PROC_RATE,
												@V_START_DT,
												@V_END_DT,
												@V_ORDERBY,
												@V_END_YN

WHILE @@FETCH_STATUS = 0                                                      
BEGIN

SELECT @V_TODO_ID = (MAX(TODO_ID) + 1)
FROM BX.TSOG_TODOLIST

INSERT INTO BX.TSOG_TODOLIST
(
	TODO_ID,
	CATEGORY_ID,
	TITLE,
	CONTENTS,
	PROC_CONTENTS,
	ALERT_TIME,
	MAIL_YN,
	PAPER_YN,
	ALERT_YN,
	SMS_YN,
	PROC_RATE,
	END_YN,
	DEL_YN,
	CREATED_BY,
	CREATED_DT,
	START_DT,
	END_DT,
	ORDERBY
)
VALUES
(
	@V_TODO_ID,
	@V_CATEGORY_ID,
	@V_TITLE,
	@V_CONTENTS,
	@V_PROC_CONTENTS,
	NULL, -- ALERT_TIME
	'0', -- MAIL_YN
	'0', -- PAPER_YN
	'0', -- ALERT_YN
	'0', -- SMS_YN
	@V_PROC_RATE,
	@V_END_YN, -- END_YN,
	'0', -- DEL_YN
	@V_ID_USER, -- CREATED_BY
	GETDATE(), -- CREATED_DT
	@V_START_DT,
	@V_END_DT,
	@V_ORDERBY
)
	   	
FETCH NEXT FROM CUR_CZ_SA_CRM_EMP_SCHEDULE INTO @V_CATEGORY_ID,
												@V_TITLE,
												@V_CONTENTS,
												@V_PROC_CONTENTS,
												@V_PROC_RATE,
												@V_START_DT,
												@V_END_DT,
												@V_ORDERBY,
												@V_END_YN

END

CLOSE CUR_CZ_SA_CRM_EMP_SCHEDULE                                                      
DEALLOCATE CUR_CZ_SA_CRM_EMP_SCHEDULE  

-- ================================================== UPDATE    
UPDATE A
SET A.CATEGORY_ID = B.CATEGORY_ID,
	A.TITLE = B.TITLE,
	A.CONTENTS = B.CONTENTS,
	A.PROC_CONTENTS = B.PROC_CONTENTS,
	A.PROC_RATE = B.PROC_RATE,
	A.START_DT = B.START_DT,
	A.END_DT = B.END_DT,
	A.ORDERBY = B.ORDERBY,
	A.END_YN = B.END_YN,
	A.MODIFY_BY = @V_ID_USER,
	A.MODIFY_DT = GETDATE()
FROM BX.TSOG_TODOLIST A 
JOIN OPENXML (@DOC, '/XML/ROW', 2) 
        WITH (TODO_ID INT,
			  CATEGORY_ID INT,
	          TITLE NVARCHAR(500),
	          CONTENTS NVARCHAR(MAX),
		      PROC_CONTENTS NVARCHAR(MAX),
		      PROC_RATE NUMERIC(3, 0),
		      START_DT NVARCHAR(8),
		      END_DT NVARCHAR(8),
		      ORDERBY NVARCHAR(10),
			  END_YN NVARCHAR(1),
			  XML_FLAG NVARCHAR(1)) B 
ON A.TODO_ID = B.TODO_ID
AND B.XML_FLAG = 'U'

EXEC SP_XML_REMOVEDOCUMENT @DOC 

GO

