USE [NEOE]
GO
/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_CUST_REL_MNG_TIME_LINE_S]    Script Date: 2017-05-25 오후 1:06:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_SA_CRM_EMP_CLAIM_S]
(
	@P_CD_COMPANY		NVARCHAR(7),
	@P_NO_EMP			NVARCHAR(10),
	@P_DT_STRAT			NVARCHAR(8),
	@P_DT_END			NVARCHAR(8)
) 
AS
 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT MC3.NM_SYSDEF AS NM_STATUS,
	   MC4.NM_SYSDEF AS NM_GW_STATUS,
	   CH.NO_CLAIM,
	   CH.NO_SO,
	   SH.DT_SO,
	   CH.DT_INPUT,
	   CH.DT_CLOSING,
	   MC.NM_SYSDEF AS NM_TP_CLAIM,
	   MC1.NM_SYSDEF AS NM_TP_CAUSE,
	   MC2.NM_SYSDEF AS NM_TP_ITEM,
	   MH.NM_VESSEL,
	   CH.CD_PARTNER,
	   MP.LN_PARTNER AS NM_PARTNER,
	   (CASE WHEN CH.NO_CLAIM IS NOT NULL THEN 1 ELSE 0 END) AS QT_CLAIM,
	   CL.AM_CLAIM,
	   DATEDIFF(DAY, SH.DT_SO, CH.DT_INPUT) AS DT_SO_DIFF,
	   DATEDIFF(DAY, CH.DT_INPUT, CH.DT_CLOSING) AS DT_CLOSING_DIFF,
	   CH.DC_RECEIVE
FROM CZ_SA_CLAIMH CH
LEFT JOIN SA_SOH SH ON SH.CD_COMPANY = CH.CD_COMPANY AND SH.NO_SO = CH.NO_SO
JOIN (SELECT CL.CD_COMPANY, CL.NO_CLAIM,
	  		 SUM(CL.AM_CLAIM) AS AM_CLAIM 
	  FROM CZ_SA_CLAIML CL
	  GROUP BY CL.CD_COMPANY, CL.NO_CLAIM) CL
ON CL.CD_COMPANY = CH.CD_COMPANY AND CL.NO_CLAIM = CH.NO_CLAIM
LEFT JOIN CZ_MA_HULL MH ON MH.NO_IMO = CH.NO_IMO
LEFT JOIN MA_PARTNER MP ON MP.CD_COMPANY = CH.CD_COMPANY AND MP.CD_PARTNER = CH.CD_PARTNER
LEFT JOIN FI_GWDOCU GW ON GW.CD_COMPANY = 'K100' AND GW.CD_PC = '010000' AND GW.NO_DOCU = CH.CD_COMPANY + '-' + CH.NO_CLAIM + '-' + CH.CD_STATUS
LEFT JOIN MA_CODEDTL MC ON MC.CD_COMPANY = CH.CD_COMPANY AND MC.CD_FIELD = 'CZ_SA00001' AND MC.CD_SYSDEF = CH.TP_CLAIM
LEFT JOIN MA_CODEDTL MC1 ON MC1.CD_COMPANY = CH.CD_COMPANY AND MC1.CD_FIELD = 'CZ_SA00002' AND MC1.CD_SYSDEF = CH.TP_CAUSE
LEFT JOIN MA_CODEDTL MC2 ON MC2.CD_COMPANY = CH.CD_COMPANY AND MC2.CD_FIELD = 'CZ_SA00003' AND MC2.CD_SYSDEF = CH.TP_ITEM
LEFT JOIN MA_CODEDTL MC3 ON MC3.CD_COMPANY = CH.CD_COMPANY AND MC3.CD_FIELD = 'CZ_SA00004' AND MC3.CD_SYSDEF = CH.CD_STATUS
LEFT JOIN MA_CODEDTL MC4 ON MC4.CD_COMPANY = GW.CD_COMPANY AND MC4.CD_FIELD = 'PU_C000065' AND MC4.CD_SYSDEF = GW.ST_STAT
WHERE CH.CD_COMPANY = @P_CD_COMPANY
AND CH.NO_EMP = @P_NO_EMP
AND CH.DT_INPUT BETWEEN @P_DT_STRAT AND @P_DT_END
ORDER BY CH.DT_INPUT DESC

GO