USE [NeoBizboxS2]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_CUST_REL_MNGH_S]    Script Date: 2017-05-23 오전 9:44:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER PROCEDURE [BX].[SP_CZ_SA_CRM_EMP_SCHEDULE_S]
(
	@P_NO_EMP			NVARCHAR(20)
) 
AS
 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT DATEDIFF(DAY, SD.START_DT, GETDATE()) AS DT_DDAY,
	   SD.SCHD_ID,
	   SM.SCHM_ID,
	   SD.SCH_STS,
	   SD.SCH_NM,
	   SD.SCH_PLACE,
	   SD.CONTENTS,
	   SD.WORK_CONTENTS,
	   CD.NM_KR AS TP_REPEAT, 
	   CONVERT(CHAR(8), SD.START_DT, 112) AS DT_START,
	   CONVERT(CHAR(8), SD.END_DT, 112) AS DT_END,
	   RIGHT('00' + CONVERT(NVARCHAR, DATEPART(HOUR, SD.START_TIME)), 2) AS DT_HOUR_START,
	   RIGHT('00' + CONVERT(NVARCHAR, DATEPART(MINUTE, SD.START_TIME)), 2) AS DT_MINUTE_START,
	   RIGHT('00' + CONVERT(NVARCHAR, DATEPART(HOUR, SD.END_TIME)), 2) AS DT_HOUR_END,
	   RIGHT('00' + CONVERT(NVARCHAR, DATEPART(MINUTE, SD.END_TIME)), 2) AS DT_MINUTE_END,
	   SD.ALL_DAY_YN,
	   SD.CREATED_DT,
	   US.LOGON_CD AS ID_INSERT,
	   SD.MENU_ID,
	   SD.SCHMEMO_DIV
FROM BX.TSOG_SCH_D SD
LEFT JOIN BX.TSOG_SCH_M SM ON SM.SCHM_ID = SD.SCHM_ID
JOIN BX.TCMG_USER US ON US.USER_ID = SD.CREATED_BY
LEFT JOIN BX.TCMG_CDD CD ON CD.CM_CD = 'so0001' AND CD.CD = SD.REPEAT_TP AND CD.CO_ID = 0 
WHERE SD.DEL_YN = '0'
AND US.LOGON_CD = @P_NO_EMP
AND ISNULL(SD.SCHMEMO_DIV, 'S') != 'M'
ORDER BY SD.CREATED_DT DESC

GO

