USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_ORDER_TRACKINGH_U]    Script Date: 2016-06-15 오전 10:09:13 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_SA_READY_STATUSH_U]  
(  
    @P_CD_COMPANY		NVARCHAR(7),
	@P_NO_SO			NVARCHAR(20),
	@P_YN_ONTIME		NVARCHAR(1),
	@P_DC_RMK			NVARCHAR(MAX),
	@P_ID_UPDATE		NVARCHAR(15)
)
AS

UPDATE SA_SOH
SET YN_ONTIME = @P_YN_ONTIME,
	DC_RMK_READY = @P_DC_RMK,
	ID_UPDATE = @P_ID_UPDATE,
	DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE())
WHERE CD_COMPANY = @P_CD_COMPANY 
AND NO_SO = @P_NO_SO

GO

