USE [NEOE]
GO
/****** Object:  StoredProcedure [NEOE].[SP_CZ_PR_OPOUT_PO_REG_INSP_U]    Script Date: 2022-11-17 오후 2:13:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_PR_OPOUT_PO_REG_INSP_U]
(
	@P_CD_COMPANY		NVARCHAR(7),
	@P_YN_CHK			NVARCHAR(1),
	@P_NO_WO			NVARCHAR(20),
	@P_NO_WO_LINE		NUMERIC(5, 0),
	@P_SEQ_WO			NUMERIC(5, 0),
	@P_NO_PO			NVARCHAR(20),
	@P_NO_OPOUT_PO		NVARCHAR(20),
	@P_NO_OPOUT_PR		NVARCHAR(20),
	@P_NO_PR_LINE		NUMERIC(5, 0),
	@P_NO_INSERT		NVARCHAR(15)
) 
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

IF @P_YN_CHK = 'Y'
BEGIN
UPDATE CZ_PR_WO_INSP
SET NO_OPOUT_PO = @P_NO_PO
,	ID_UPDATE = @P_NO_INSERT
,	DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE())
WHERE CD_COMPANY = @P_CD_COMPANY
AND NO_WO = @P_NO_WO
AND NO_LINE = @P_NO_WO_LINE
AND SEQ_WO = @P_SEQ_WO
AND NO_OPOUT_PR = @P_NO_OPOUT_PR
AND NO_PR_LINE = @P_NO_PR_LINE
END


ELSE
BEGIN
UPDATE CZ_PR_WO_INSP
SET NO_OPOUT_PO = NULL
,	ID_UPDATE = @P_NO_INSERT
,	DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE())
WHERE CD_COMPANY = @P_CD_COMPANY
AND NO_WO = @P_NO_WO
AND NO_LINE = @P_NO_WO_LINE
AND SEQ_WO = @P_SEQ_WO
AND NO_OPOUT_PO = @P_NO_OPOUT_PO
AND NO_OPOUT_PR = @P_NO_OPOUT_PR
AND NO_PR_LINE = @P_NO_PR_LINE
END

