USE [NEOE]
GO
/****** Object:  StoredProcedure [NEOE].[SP_CZ_PR_OPOUT_PO_REG_S]    Script Date: 2023-01-31 오후 1:49:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_PR_OPOUT_PO_REG_S]  
(  
    @P_CD_COMPANY   NVARCHAR(7),   
    @P_CD_PLANT     NVARCHAR(7),   
    @P_NO_PO        NVARCHAR(20),
    @P_FG_LANG      NVARCHAR(4) = NULL
)  
AS  

-- MultiLang Call
EXEC UP_MA_LOCAL_LANGUAGE @P_FG_LANG

SET ANSI_WARNINGS OFF
SET ARITHIGNORE ON
SET ARITHABORT OFF

BEGIN

SELECT H.CD_PLANT,
       H.NO_PO,
       H.CD_PARTNER,
       H.NO_EMP,
       H.DT_PO,
       H.CD_EXCH,
       H.RT_EXCH,
       H.FG_TAX,   
       H.VAT_RATE,
       H.AM_EX,
       H.AM,
       H.AM_VAT,
       H.DC_RMK,
       H.AM + H.AM_VAT AS AM_PUR,
       A.LN_PARTNER,
       B.NM_KOR,
       C.NM_DEPT, 
       H.COND_PAYMENT,
       H.COND_PRICE,
       B.NO_TEL,
       B.NO_EMAIL,
       A.NO_TEL AS PARTNER_NO_TEL,
       A.NO_FAX AS PARTNER_NO_FAX,
       A.CD_EMP_PARTNER,
       A.NO_HPEMP_PARTNER,
       A.E_MAIL AS PARTNER_E_MAIL,
       M.NM_CEO,
       M.NO_FAX,
       H.DC_RMK_TEXT1
FROM PR_OPOUT_POH H  
LEFT JOIN MA_PARTNER A ON A.CD_COMPANY = H.CD_COMPANY AND A.CD_PARTNER = H.CD_PARTNER  
LEFT JOIN MA_EMP B ON B.CD_COMPANY = H.CD_COMPANY AND B.NO_EMP = H.NO_EMP  
LEFT JOIN MA_DEPT C ON C.CD_COMPANY = B.CD_COMPANY AND C.CD_DEPT = B.CD_DEPT  
LEFT JOIN MA_COMPANY M ON M.CD_COMPANY = H.CD_COMPANY  
WHERE H.CD_COMPANY = @P_CD_COMPANY  
AND H.CD_PLANT = @P_CD_PLANT  
AND H.NO_PO = @P_NO_PO  
  
SELECT L.CD_PLANT,
       L.NO_LINE,
       L.NO_WO,
       L.CD_OP,
       L.CD_WC,
       L.CD_WCOP,
       L.CD_ITEM,
       L.DT_DUE,   
       L.QT_PO,
       L.QT_RCV,
       L.QT_CLS,
       L.UM_EX,
       L.AM_EX,
       L.UM,
       L.AM,
       L.AM_VAT,
       L.DC_RMK,   
       (R.QT_START - R.QT_OUTPO + L.QT_PO) AS QT_PO_ORIGIN,   
       P.NM_ITEM,
       P.STND_ITEM,
       P.UNIT_IM,
       C.NM_WC,
       D.NM_OP,  
       W.TP_ROUT,
       TP.NM_TP_WO,
       L.UM_MATL,
       L.UM_SOUL,
       H.CD_PARTNER,
       NEOE.FN_MA_GET_CODEDTL_NM_SYSDEF(@P_CD_COMPANY, 'MA_B000015', P.FG_SERNO) AS NM_FG_SERNO,
       G.NM_ITEMGRP AS NM_GRP_ITEM,
       (ISNULL(L.AM,0)+ ISNULL(L.AM_VAT,0)) AS AM_SUM,
       H.DT_PO,
       L.OLD_QT_PO,
	   L.UNIT_CH,
	   L.QT_CHCOEF,
	   L.NO_WORK,
	   A.LN_PARTNER,  
	   W.NO_PJT,  
	   J.NM_PROJECT AS NM_PJT,  
	   J.AM_CONTRACT,
	   J.CD_PARTNER AS CD_PARTNER_PJT,
	   B.LN_PARTNER AS LN_PARTNER_PJT,
	   W.NO_LOT,
	   P.EN_ITEM,
	   P.STND_DETAIL_ITEM,
	   P.MAT_ITEM,
	   P.NM_MAKER,
	   P.BARCODE,
	   P.NO_MODEL,
	   W.TXT_USERDEF1 AS TXT_USERDEF1_WO,
       P.NO_DESIGN,
	   R.NO_LINE AS NO_WO_LINE,
	   (CONVERT(decimal,L.AM_EX) / (L.UM_EX * L.QT_PO)) AS WEIGHT,
	   Z.NO_PR,
	   Z.NO_LINE AS PR_LINE,
	   L.QT_PO * (CONVERT(decimal,L.AM_EX) / (L.UM_EX * L.QT_PO)) AS T_WEIGHT
FROM PR_OPOUT_POL L  
JOIN PR_OPOUT_POH H ON H.CD_COMPANY = L.CD_COMPANY AND H.CD_PLANT = L.CD_PLANT AND H.NO_PO = L.NO_PO
JOIN PR_WO_ROUT R ON R.CD_COMPANY = @P_CD_COMPANY AND R.CD_PLANT = @P_CD_PLANT AND R.NO_WO = L.NO_WO AND R.CD_OP = L.CD_OP    
JOIN PR_WO W ON W.CD_COMPANY = L.CD_COMPANY AND W.CD_PLANT = L.CD_PLANT AND W.NO_WO = L.NO_WO  
LEFT JOIN MA_PITEM P ON P.CD_COMPANY = L.CD_COMPANY AND P.CD_PLANT = L.CD_PLANT AND P.CD_ITEM = L.CD_ITEM  
LEFT JOIN MA_WC C ON C.CD_COMPANY = L.CD_COMPANY AND C.CD_PLANT = L.CD_PLANT AND C.CD_WC = L.CD_WC  
LEFT JOIN PR_WCOP D ON D.CD_COMPANY = L.CD_COMPANY AND D.CD_PLANT = L.CD_PLANT AND D.CD_WC = L.CD_WC AND D.CD_WCOP = L.CD_WCOP  
LEFT JOIN PR_TPWO TP ON W.CD_COMPANY = TP.CD_COMPANY AND W.TP_ROUT = TP.TP_WO
LEFT JOIN MA_ITEMGRP G ON G.CD_COMPANY = P.CD_COMPANY AND G.CD_ITEMGRP = P.GRP_ITEM
LEFT JOIN MA_PARTNER A ON A.CD_COMPANY = H.CD_COMPANY AND A.CD_PARTNER = H.CD_PARTNER    
LEFT JOIN SA_PROJECTH J ON J.CD_COMPANY = W.CD_COMPANY AND J.NO_PROJECT = W.NO_PJT  
LEFT JOIN MA_PARTNER B ON B.CD_COMPANY = J.CD_COMPANY AND B.CD_PARTNER = J.CD_PARTNER   
LEFT JOIN CZ_PR_OPOUT_PR Z ON Z.CD_COMPANY = L.CD_COMPANY AND Z.CD_PLANT = L.CD_PLANT AND Z.NO_PR = L.NO_PR AND Z.NO_WO = L.NO_WO AND Z.CD_OP = L.CD_OP
WHERE L.CD_COMPANY = @P_CD_COMPANY  
AND L.CD_PLANT = @P_CD_PLANT  
AND L.NO_PO = @P_NO_PO  

END