USE [NEOE]
GO

/****** Object:  UserDefinedFunction [NEOE].[FN_CZ_GET_STOCK_QTY]    Script Date: 2015-07-30 오후 2:24:14 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER FUNCTION [NEOE].[FN_CZ_GET_STOCK_QTY] 
(
	@P_CD_COMPANY	NVARCHAR(7),
	@P_DT_INQ		NVARCHAR(8),
	@P_CD_PLANT		NVARCHAR(7),
	@P_CD_ITEM		NVARCHAR(20)
)
RETURNS NUMERIC(17, 4)
AS
BEGIN
	DECLARE	@V_RESULT NUMERIC(17, 4)

	--SELECT @V_RESULT = SUM(A.QT_INV)
	--FROM (SELECT MO.CD_COMPANY, MO.CD_PLANT, MO.CD_ITEM, MO.QT_GOOD_INV AS QT_INV 
	--	  FROM MM_OPENQTL MO
	--	  JOIN MA_PITEM MI ON MI.CD_COMPANY = MO.CD_COMPANY AND MI.CD_PLANT = MO.CD_PLANT AND MI.CD_ITEM = MO.CD_ITEM AND MI.CLS_ITEM IN ('005', '009', '013')
	--	  WHERE MO.CD_COMPANY = @P_CD_COMPANY
	--	  AND MO.YM_STANDARD = LEFT(@P_DT_INQ, 4) + '00'
	--	  AND MO.CD_PLANT = @P_CD_PLANT
	--	  AND MO.CD_ITEM = @P_CD_ITEM
	--	  UNION ALL
	--	  SELECT MM.CD_COMPANY, MM.CD_PLANT, MM.CD_ITEM, (SUM(MM.QT_GOOD_GR + MM.QT_REJECT_GR + MM.QT_INSP_GR + MM.QT_TRANS_GR) 
	--													  - SUM(MM.QT_GOOD_GI + MM.QT_REJECT_GI + MM.QT_INSP_GI + MM.QT_TRANS_GI)) AS QT_INV 
	--	  FROM MM_OHSLINVM MM
	--	  JOIN MA_PITEM MI ON MI.CD_COMPANY = MM.CD_COMPANY AND MI.CD_PLANT = MM.CD_PLANT AND MI.CD_ITEM = MM.CD_ITEM AND MI.CLS_ITEM IN ('005', '009', '013')
	--	  WHERE MM.CD_COMPANY = @P_CD_COMPANY
	--	  AND MM.YM_IO >= LEFT(@P_DT_INQ, 4) + '00'
	--	  AND MM.YM_IO <= LEFT(@P_DT_INQ, 6) - 1
	--	  AND MM.CD_PLANT = @P_CD_PLANT
	--	  AND MM.CD_ITEM = @P_CD_ITEM      
	--	  GROUP BY MM.CD_COMPANY, MM.CD_PLANT, MM.CD_ITEM
	--	  UNION ALL
	--	  SELECT MD.CD_COMPANY, MD.CD_PLANT, MD.CD_ITEM, (MD.QT_GOOD_GR - MD.QT_GOOD_GI + MD.QT_REJECT_GR - MD.QT_REJECT_GI + MD.QT_TRANS_GR - MD.QT_TRANS_GI + MD.QT_INSP_GR - MD.QT_INSP_GI) AS QT_INV 
	--	  FROM MM_OHSLINVD MD
	--	  JOIN MA_PITEM MI ON MI.CD_COMPANY = MD.CD_COMPANY AND MI.CD_PLANT = MD.CD_PLANT AND MI.CD_ITEM = MD.CD_ITEM AND MI.CLS_ITEM IN ('005', '009', '013')
	--	  WHERE MD.CD_COMPANY = @P_CD_COMPANY 
	--	  AND MD.DT_IO <= @P_DT_INQ
	--	  AND MD.DT_IO > LEFT(@P_DT_INQ, 6) + '00'
	--	  AND MD.CD_PLANT = @P_CD_PLANT
	--	  AND MD.CD_ITEM = @P_CD_ITEM) A
	--GROUP BY A.CD_COMPANY, A.CD_PLANT, A.CD_ITEM

	--SELECT @V_RESULT = SUM(A.QT_INV)
	--FROM (SELECT MO.CD_COMPANY, MO.CD_PLANT, MO.CD_ITEM, MO.QT_GOOD_INV AS QT_INV 
	--	  FROM MM_OPENQTL MO
	--	  JOIN MA_PITEM MI ON MI.CD_COMPANY = MO.CD_COMPANY AND MI.CD_PLANT = MO.CD_PLANT AND MI.CD_ITEM = MO.CD_ITEM
	--	  WHERE MO.CD_COMPANY = @P_CD_COMPANY
	--	  AND MO.YM_STANDARD = LEFT(@P_DT_INQ, 4) + '00'
	--	  AND MO.CD_PLANT = @P_CD_PLANT
	--	  AND MO.CD_ITEM = @P_CD_ITEM
	--	  AND (MI.CLS_ITEM = '005' OR MI.CLS_ITEM = '009' OR MI.CLS_ITEM = '013')
	--	  UNION ALL
	--	  SELECT MY.CD_COMPANY, MY.CD_PLANT, MY.CD_ITEM, (SUM(MY.QT_GOOD_GR + MY.QT_REJECT_GR + MY.QT_INSP_GR + MY.QT_TRANS_GR) 
	--													  - SUM(MY.QT_GOOD_GI + MY.QT_REJECT_GI + MY.QT_INSP_GI + MY.QT_TRANS_GI)) AS QT_INV 
	--	  FROM MM_PINVN MY
	--	  JOIN MA_PITEM MI ON MI.CD_COMPANY = MY.CD_COMPANY AND MI.CD_PLANT = MY.CD_PLANT AND MI.CD_ITEM = MY.CD_ITEM
	--	  WHERE MY.CD_COMPANY = @P_CD_COMPANY
	--	  AND MY.P_YR = LEFT(@P_DT_INQ, 4)		  
	--	  AND MY.CD_PLANT = @P_CD_PLANT
	--	  AND MY.CD_ITEM = @P_CD_ITEM
	--	  AND (MI.CLS_ITEM = '005' OR MI.CLS_ITEM = '009' OR MI.CLS_ITEM = '013')      
	--	  GROUP BY MY.CD_COMPANY, MY.CD_PLANT, MY.CD_ITEM) A
	--GROUP BY A.CD_COMPANY, A.CD_PLANT, A.CD_ITEM

	SELECT @V_RESULT = (SUM(MY.QT_GOOD_OPEN + MY.QT_REJECT_OPEN + MY.QT_INSP_OPEN + MY.QT_TRANS_OPEN) 
						+ SUM(MY.QT_GOOD_GR + MY.QT_REJECT_GR + MY.QT_INSP_GR + MY.QT_TRANS_GR) 
						- SUM(MY.QT_GOOD_GI + MY.QT_REJECT_GI + MY.QT_INSP_GI + MY.QT_TRANS_GI))
    FROM MM_PINVN MY
    JOIN MA_PITEM MI ON MI.CD_COMPANY = MY.CD_COMPANY AND MI.CD_PLANT = MY.CD_PLANT AND MI.CD_ITEM = MY.CD_ITEM
    WHERE MY.CD_COMPANY = @P_CD_COMPANY
    AND MY.P_YR = LEFT(@P_DT_INQ, 4)		  
    AND MY.CD_PLANT = @P_CD_PLANT
	AND MY.CD_SL = 'SL02'
    AND MY.CD_ITEM = @P_CD_ITEM     

	RETURN ISNULL(@V_RESULT, 0)
END

GO

