USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_LEAD_TIME_RPT_S]    Script Date: 2016-02-12 오후 1:40:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




ALTER PROCEDURE [NEOE].[SP_CZ_SA_LEAD_TIME_RPT_S]  
(
    @P_CD_COMPANY	NVARCHAR(7),
	@P_DT_FROM		NVARCHAR(8),
	@P_DT_TO		NVARCHAR(8),
	@P_NO_FILE		NVARCHAR(20),
	@P_ID_SALES	    NVARCHAR(10),
	@P_CD_PARTNER	NVARCHAR(20),
	@P_CD_SALEGRP	NVARCHAR(12),
	@P_CD_SUPPLIER	NVARCHAR(20)
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT WH.NO_KEY,
	   QH.CD_PARTNER,
	   MP.LN_PARTNER,
	   QL1.CD_PARTNER AS CD_SUPPLIER,
	   MP1.LN_PARTNER AS NM_SUPPLIER,
	   QH.CD_SALEGRP,
	   SG.NM_SALEGRP,
       QH.NO_EMP AS ID_SALES,
	   MU.NM_USER AS NM_SALES,
	   WH.ID_TYPIST,
	   MU1.NM_USER AS NM_TYPIST,
	   WH.DTS_INSERT AS [01],
	   WH1.DTS_INSERT AS [02],
	   WH1.DTS_DONE AS [03],
	   WH2.DTS_DONE AS [04],
	   WH3.DTS_DONE AS [05],
	   WH4.DTS_DONE AS [06],
	   (CASE WHEN ISNULL(QH.YN_CLOSE, 'N') = 'Y' THEN QH.DT_CLOSE ELSE NULL END) AS [07],
	   (CASE WHEN ISNULL(QH.YN_CLOSE, 'N') = 'Y' THEN QH.TP_CLOSE ELSE NULL END) AS TP_CLOSE,
	   QH.CD_EXCH,
	   CD.NM_SYSDEF AS NM_EXCH,
	   QL.NM_ITEMGRP,
	   QL.QT_ITEM,
	   QL.AM_EX_Q,
	   QL.AM_KR_Q
FROM CZ_MA_WORKFLOWH WH
LEFT JOIN CZ_SA_QTNH QH ON QH.CD_COMPANY = WH.CD_COMPANY AND QH.NO_FILE = WH.NO_KEY
LEFT JOIN (SELECT QL.CD_COMPANY, QL.NO_FILE, 
				  MAX(IG.NM_ITEMGRP) AS NM_ITEMGRP,
				  COUNT(1) AS QT_ITEM,
				  SUM(QL.AM_EX_S) AS AM_EX_Q,
				  SUM(QL.AM_KR_S) AS AM_KR_Q 
		   FROM CZ_SA_QTNL QL
		   LEFT JOIN MA_ITEMGRP IG ON IG.CD_COMPANY = QL.CD_COMPANY AND IG.USE_YN = 'Y' AND IG.CD_ITEMGRP = QL.GRP_ITEM
		   GROUP BY QL.CD_COMPANY, QL.NO_FILE) QL
ON QL.CD_COMPANY = QH.CD_COMPANY AND QL.NO_FILE = QH.NO_FILE
LEFT JOIN (SELECT QL.CD_COMPANY,
		   	      QL.NO_FILE,
		   	      QL.CD_PARTNER 
		   FROM (SELECT QL.CD_COMPANY, 
		   			    QL.NO_FILE, 
		   			    QL.CD_PARTNER,
		   			    ROW_NUMBER() OVER (PARTITION BY QL.CD_COMPANY, QL.NO_FILE ORDER BY COUNT(1) DESC) AS IDX
		   	     FROM CZ_PU_QTNL QL
		   	     GROUP BY QL.CD_COMPANY, QL.NO_FILE, QL.CD_PARTNER) QL
		   WHERE QL.IDX = 1) QL1
ON QL1.CD_COMPANY = QH.CD_COMPANY AND QL1.NO_FILE = QH.NO_FILE
LEFT JOIN MA_USER MU ON MU.CD_COMPANY = QH.CD_COMPANY AND MU.ID_USER = QH.NO_EMP
LEFT JOIN MA_USER MU1 ON MU1.CD_COMPANY = WH.CD_COMPANY AND MU1.ID_USER = WH.ID_TYPIST
LEFT JOIN MA_PARTNER MP ON MP.CD_COMPANY = QH.CD_COMPANY AND MP.CD_PARTNER = QH.CD_PARTNER
LEFT JOIN MA_PARTNER MP1 ON MP1.CD_COMPANY = QL1.CD_COMPANY AND MP1.CD_PARTNER = QL1.CD_PARTNER
LEFT JOIN MA_SALEGRP SG ON SG.CD_COMPANY = QH.CD_COMPANY AND SG.CD_SALEGRP = QH.CD_SALEGRP
LEFT JOIN MA_CODEDTL CD ON CD.CD_COMPANY = QH.CD_COMPANY AND CD.CD_FIELD = 'MA_B000005' AND CD.CD_SYSDEF = QH.CD_EXCH
LEFT JOIN CZ_MA_WORKFLOWH WH1 ON WH1.CD_COMPANY = WH.CD_COMPANY AND WH1.NO_KEY = WH.NO_KEY AND WH1.TP_STEP = '03'
LEFT JOIN CZ_MA_WORKFLOWH WH2 ON WH2.CD_COMPANY = WH.CD_COMPANY AND WH2.NO_KEY = WH.NO_KEY AND WH2.TP_STEP = '04'
LEFT JOIN CZ_MA_WORKFLOWH WH3 ON WH3.CD_COMPANY = WH.CD_COMPANY AND WH3.NO_KEY = WH.NO_KEY AND WH3.TP_STEP = '05'
LEFT JOIN CZ_MA_WORKFLOWH WH4 ON WH4.CD_COMPANY = WH.CD_COMPANY AND WH4.NO_KEY = WH.NO_KEY AND WH4.TP_STEP = '06'
WHERE WH.CD_COMPANY = @P_CD_COMPANY
AND SUBSTRING(WH.DTS_INSERT, 1, 8) BETWEEN @P_DT_FROM AND @P_DT_TO
AND WH.TP_STEP = '01' 
AND (ISNULL(@P_NO_FILE, '') = '' OR WH.NO_KEY = @P_NO_FILE)
AND (ISNULL(@P_ID_SALES, '') = '' OR QH.NO_EMP = @P_ID_SALES)
AND (ISNULL(@P_CD_PARTNER, '') = '' OR QH.CD_PARTNER = @P_CD_PARTNER)
AND (ISNULL(@P_CD_SUPPLIER, '') = '' OR QL1.CD_PARTNER = @P_CD_SUPPLIER)
AND (ISNULL(@P_CD_SALEGRP, '') = '' OR QH.CD_SALEGRP = @P_CD_SALEGRP)

GO