USE [NEOE]
GO
/****** Object:  StoredProcedure [NEOE].[SP_CZ_FI_ETAX_DIFF_RPTL_S]    Script Date: 2018-02-09 오전 9:32:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_FI_ETAX_DIFF_RPTL_S]
(
	@P_CD_COMPANY		NVARCHAR(7),
    @P_DT_START         NVARCHAR(8),
	@P_NO_COMPANY		NVARCHAR(200),
	@P_TP_ETAX			NVARCHAR(3)
) 
AS
 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

IF @P_TP_ETAX = '001'
BEGIN
	SELECT EX.NO_ETAX,
		   EX.DT_WRITE,
		   EX.DT_START,
		   EX.DT_SEND,
		   EX.NO_COMPANY1,
		   EX.NM_COMPANY1,
		   EX.NM_CEO1,
		   EX.AM_TAXSTD,
		   EX.AM_ADDTAX,
		   EX.AM_SUM,
		   EX.TP_TAX,
		   EX.NM_TAX,
		   EX.TP_BAL,
		   EX.NM_BIGO,
		   EX.SELL_DAM_EMAIL,
		   EX.BUY_DAM_EMAIL,
		   EX.BUY_DAM_EMAIL2,
		   EX.NM_ST_TAX,
		   EX.NM_ITEM,
		   EX.DC_ADDRESS_SELL,
		   EX.DC_ADDRESS_BUY,
		   (CASE WHEN EXISTS (SELECT 1 
	                          FROM CZ_PU_ETAXH TX
	                          WHERE TX.CD_COMPANY = @P_CD_COMPANY
	                          AND TX.NO_ETAX = EX.NO_ETAX) THEN 'Y' ELSE 'N' END) AS YN_AUTO
	FROM FI_ETAX EX
	WHERE EX.CD_COMPANY = @P_CD_COMPANY
	AND EX.TP_GUBUN = '2'
	AND EX.DT_START = @P_DT_START
	AND EX.NO_COMPANY1 = @P_NO_COMPANY
END
ELSE
BEGIN
	SELECT EX.NO_ETAX,
		   EX.DT_WRITE,
		   EX.DT_START,
		   EX.DT_SEND,
		   EX.NO_COMPANY1,
		   EX.NM_COMPANY1,
		   EX.NM_CEO1,
		   EX.AM_TAXSTD,
		   EX.AM_ADDTAX,
		   EX.AM_SUM,
		   EX.TP_TAX,
		   EX.NM_TAX,
		   EX.TP_BAL,
		   EX.NM_BIGO,
		   EX.SELL_DAM_EMAIL,
		   EX.BUY_DAM_EMAIL,
		   EX.BUY_DAM_EMAIL2,
		   EX.NM_ST_TAX,
		   EX.NM_ITEM,
		   EX.DC_ADDRESS_SELL,
		   EX.DC_ADDRESS_BUY,
		   (CASE WHEN EXISTS (SELECT 1 
	                          FROM CZ_PU_ETAXH TX
	                          WHERE TX.CD_COMPANY = @P_CD_COMPANY
	                          AND TX.NO_ETAX = EX.NO_ETAX) THEN 'Y' ELSE 'N' END) AS YN_AUTO
	FROM FI_ETAX2 EX
	WHERE EX.CD_COMPANY = @P_CD_COMPANY
	AND EX.TP_GUBUN = '2'
	AND EX.DT_START = @P_DT_START
	AND EX.NO_COMPANY1 = @P_NO_COMPANY
END



