USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_EALRY_WARNING_SYSTEM_OPTION_S]    Script Date: 2019-05-29 오후 7:42:12 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER PROCEDURE [NEOE].[SP_CZ_SA_EALRY_WARNING_SYSTEM_SUB_S]
(
	@P_CD_COMPANY	 NVARCHAR(7),
	@P_YN_SIMULATION NVARCHAR(1)
) 
AS
 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT EC.CD_COMPANY,
	   EC.YN_SIMULATION,
	   EC.TP_GUBUN,
	   EC.CD_EWS,
	   EC.DC_EWS,
	   EC.DC_EWS1,
	   EC.DC_EWS2,
	   EC.DC_EWS3,
	   EC.YN_USE,
	   EC.ID_INSERT,
	   EC.DTS_INSERT,
	   EC.ID_UPDATE,
	   EC.DTS_UPDATE 
FROM CZ_SA_EWS_CONDITION EC
WHERE EC.CD_COMPANY = @P_CD_COMPANY
AND EC.YN_SIMULATION = @P_YN_SIMULATION
AND EC.TP_GUBUN = 'M'

SELECT EC.CD_COMPANY,
	   EC.YN_SIMULATION,
	   EC.TP_GUBUN,
	   EC.CD_EWS,
	   EC.DC_EWS,
	   EC.DC_EWS1,
	   EC.DC_EWS2,
	   EC.DC_EWS3,
	   EC.YN_USE,
	   EC.ID_INSERT,
	   EC.DTS_INSERT,
	   EC.ID_UPDATE,
	   EC.DTS_UPDATE
FROM CZ_SA_EWS_CONDITION EC
WHERE EC.CD_COMPANY = @P_CD_COMPANY
AND EC.YN_SIMULATION = @P_YN_SIMULATION
AND EC.TP_GUBUN = 'C'

SELECT WD.DT_RCP_PREARRANGED,
	   WD.DT_FIRST_WARNING,
	   WD.DT_SECOND_WARNING,
	   WD.DT_FINAL_WARNING,
	   WD.DC_RMK,
	   WD.ID_INSERT,
	   WD.DTS_INSERT,
	   WD.ID_UPDATE,
	   WD.DTS_UPDATE
FROM CZ_SA_EWS_WARNING_DATE WD
WHERE WD.CD_COMPANY = @P_CD_COMPANY

SELECT EP.CD_COMPANY,
	   EP.IDX_HST,
	   EP.CD_PARTNER,
	   MP.LN_PARTNER,
	   EP.DT_EXPIRE,
	   MP.USE_YN,
	   MP1.YN_USE_GIR,
	   EP.AM_LIMIT,
	   EP.YN_PAY,
	   EP.DC_RMK,
	   EP.ID_INSERT,
	   EP.DTS_INSERT,
	   EP.ID_UPDATE,
	   EP.DTS_UPDATE
FROM CZ_SA_EWS_EXCEPT_PARTNER EP
LEFT JOIN MA_PARTNER MP ON MP.CD_COMPANY = EP.CD_COMPANY AND MP.CD_PARTNER = EP.CD_PARTNER
LEFT JOIN CZ_MA_PARTNER MP1 ON MP1.CD_COMPANY = EP.CD_COMPANY AND MP1.CD_PARTNER = EP.CD_PARTNER
WHERE EP.CD_COMPANY = @P_CD_COMPANY
ORDER BY EP.DT_EXPIRE

GO

