USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_EWS_WARNING_DATE_XML]    Script Date: 2019-05-29 오후 7:54:41 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_SA_EWS_WARNING_DATE_XML] 
(
	@P_XML			XML, 
	@P_ID_USER		NVARCHAR(10), 
    @DOC			INT = NULL
) 
AS 

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

EXEC SP_XML_PREPAREDOCUMENT @DOC OUTPUT, @P_XML 

-- ================================================== DELETE
DELETE A 
FROM CZ_SA_EWS_WARNING_DATE A 
JOIN OPENXML (@DOC, '/XML/D', 2) 
        WITH (CD_COMPANY			NVARCHAR(7),
			  DT_RCP_PREARRANGED	NUMERIC(3, 0)) B 
ON A.CD_COMPANY = B.CD_COMPANY
AND A.DT_RCP_PREARRANGED = B.DT_RCP_PREARRANGED
-- ================================================== INSERT
INSERT INTO CZ_SA_EWS_WARNING_DATE
(
	CD_COMPANY,
	DT_RCP_PREARRANGED,
	DT_FIRST_WARNING,
	DT_SECOND_WARNING,
	DT_FINAL_WARNING,
	DC_RMK,
	ID_INSERT,
	DTS_INSERT
)
SELECT CD_COMPANY,
	   DT_RCP_PREARRANGED,
	   DT_FIRST_WARNING,
	   DT_SECOND_WARNING,
	   DT_FINAL_WARNING,
	   DC_RMK,
       @P_ID_USER, 
       NEOE.SF_SYSDATE(GETDATE()) 
  FROM OPENXML (@DOC, '/XML/I', 2) 
          WITH (CD_COMPANY			NVARCHAR(7),
				DT_RCP_PREARRANGED	NUMERIC(3, 0),
			    DT_FIRST_WARNING	NUMERIC(3, 0),
			    DT_SECOND_WARNING	NUMERIC(3, 0),
				DT_FINAL_WARNING	NUMERIC(3, 0),
				DC_RMK				NVARCHAR(200)) 
-- ================================================== UPDATE
UPDATE A 
   SET A.DT_FIRST_WARNING = B.DT_FIRST_WARNING,
	   A.DT_SECOND_WARNING = B.DT_SECOND_WARNING,
	   A.DT_FINAL_WARNING = B.DT_FINAL_WARNING,
	   A.DC_RMK = B.DC_RMK,
	   A.ID_UPDATE = @P_ID_USER,
	   A.DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE())
  FROM CZ_SA_EWS_WARNING_DATE A 
  JOIN OPENXML (@DOC, '/XML/U', 2) 
          WITH (CD_COMPANY			NVARCHAR(7),
				DT_RCP_PREARRANGED	NUMERIC(3, 0),
			    DT_FIRST_WARNING	NUMERIC(3, 0),
			    DT_SECOND_WARNING	NUMERIC(3, 0),
				DT_FINAL_WARNING	NUMERIC(3, 0),
				DC_RMK				NVARCHAR(200)) B 
  ON A.CD_COMPANY = B.CD_COMPANY
  AND A.DT_RCP_PREARRANGED = B.DT_RCP_PREARRANGED

EXEC SP_XML_REMOVEDOCUMENT @DOC 



GO