USE [NEOE]
GO
/****** Object:  StoredProcedure [NEOE].[SP_CZ_PR_OPOUT_PR_REG_SUB_S]    Script Date: 2022-10-26 오후 3:10:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_PR_OPOUT_PR_REG_SUB_S]
(          
    @P_CD_COMPANY			NVARCHAR(7),           
    @P_CD_PLANT				NVARCHAR(7),            
	@P_NO_WO				NVARCHAR(20)	= '',       
    @P_DT_START				NVARCHAR(8),           
    @P_DT_END				NVARCHAR(8),                  
	@P_EXCEPT_LIST			VARCHAR(8000)
)
AS

BEGIN

SET NOCOUNT ON
DECLARE @DT_REL NVARCHAR(8)
DECLARE @DT_DUE NVARCHAR(8)
SET @DT_REL = @P_DT_START
SET @DT_DUE = @P_DT_END

SELECT	'N' AS S
,	A.CD_COMPANY
,	A.CD_PLANT
,	A.NO_WO
,	A.NO_LINE AS NO_WO_LINE
,	A.CD_OP
,	A.CD_WC
,	D.NM_WC
,	A.CD_WCOP
,	E.NM_OP
,	W.CD_ITEM
,	P.NM_ITEM
,	P.NO_DESIGN
,	P.STND_ITEM
,	P.UNIT_IM
,	A.QT_WO
,	A.QT_START
,	A.QT_START - SUM(ISNULL(B.QT_WORK,0)) AS QT_OUTPR
,	ISNULL(Z.QT_PR,0) AS QT_OPOUT_PR
,	A.QT_START - SUM(ISNULL(B.QT_WORK,0)) - ISNULL(Z.QT_PR,0) AS QT_APPLY_YET
,	A.QT_START - SUM(ISNULL(B.QT_WORK,0)) - ISNULL(Z.QT_PR,0) AS QT_APPLY
,	W.DT_REL
,	W.DT_DUE
,	(A.NO_WO + '&' + A.CD_OP) AS NO_WO_CD_OP
,	T.NM_TP_WO
FROM PR_WO_ROUT A
JOIN PR_WO W ON W.CD_COMPANY = A.CD_COMPANY AND W.CD_PLANT = A.CD_PLANT  AND W.NO_WO = A.NO_WO AND W.DT_REL >= @DT_REL AND W.DT_DUE <= @DT_DUE         
LEFT JOIN MA_WC D ON D.CD_COMPANY = A.CD_COMPANY AND D.CD_PLANT = A.CD_PLANT AND D.CD_WC = A.CD_WC    
LEFT JOIN PR_WCOP E ON E.CD_COMPANY = A.CD_COMPANY AND E.CD_PLANT = A.CD_PLANT AND E.CD_WC = A.CD_WC AND E.CD_WCOP = A.CD_WCOP 
LEFT JOIN MA_PITEM P ON P.CD_COMPANY = W.CD_COMPANY AND P.CD_PLANT = W.CD_PLANT AND P.CD_ITEM = W.CD_ITEM       
LEFT JOIN PR_TPWO T ON T.CD_COMPANY = W.CD_COMPANY AND T.TP_WO = W.TP_ROUT
LEFT JOIN PR_WORK B ON B.CD_COMPANY = A.CD_COMPANY AND B.NO_WO = A.NO_WO AND B.CD_OP = A.CD_OP AND ISNULL(B.NO_OPOUT_PO, '') = ''
LEFT JOIN (SELECT CD_COMPANY, NO_WO, CD_OP, SUM(ISNULL(QT_PR, 0)) AS QT_PR FROM CZ_PR_OPOUT_PR GROUP BY CD_COMPANY, NO_WO, CD_OP) Z
ON Z.CD_COMPANY = A.CD_COMPANY AND Z.NO_WO = A.NO_WO AND Z.CD_OP = A.CD_OP
WHERE A.CD_COMPANY = @P_CD_COMPANY
AND A.CD_PLANT = @P_CD_PLANT
AND A.ST_OP NOT IN ('C')
AND (A.NO_WO + '&' + A.CD_OP NOT IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_EXCEPT_LIST)) OR ISNULL(@P_EXCEPT_LIST, '') = '')
AND A.CD_WC != 'W500'
AND (A.NO_WO LIKE '%' + ISNULL(@P_NO_WO,'') + '%')
AND EXISTS (SELECT 1 
			FROM CZ_PR_WO_REQ_D WD
			WHERE WD.CD_COMPANY = A.CD_COMPANY
			AND WD.NO_WO = A.NO_WO)
GROUP BY A.CD_COMPANY, A.CD_PLANT, A.NO_WO, A.CD_OP, A.CD_WC, D.NM_WC, A.CD_WCOP, E.NM_OP, W.CD_ITEM, A.NO_LINE
	   , P.NM_ITEM, P.STND_ITEM, P.UNIT_IM, A.QT_WO, A.QT_START, T.NM_TP_WO, W.DT_REL, W.DT_DUE, P.NO_DESIGN, Z.QT_PR
HAVING A.QT_START - SUM(ISNULL(B.QT_WORK,0)) - ISNULL(Z.QT_PR,0) > 0
ORDER BY A.NO_WO, A.NO_LINE

END