USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_FI_PARTNERPTR_XML]    Script Date: 2017-06-09 오후 1:32:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO





ALTER PROCEDURE [NEOE].[SP_CZ_FI_PARTNERPTR_XML] 
(
	@P_XML			XML, 
	@P_ID_USER		NVARCHAR(10), 
    @DOC			INT = NULL
) 
AS 

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

EXEC SP_XML_PREPAREDOCUMENT @DOC OUTPUT, @P_XML 

-- ================================================== DELETE
DELETE A 
FROM FI_PARTNERPTR A 
JOIN OPENXML (@DOC, '/XML/D', 2) 
        WITH (CD_COMPANY NVARCHAR(7),
			  CD_PARTNER NVARCHAR(20),
			  SEQ NUMERIC(5)) B 
ON A.CD_COMPANY = B.CD_COMPANY
AND A.CD_PARTNER = B.CD_PARTNER
AND A.SEQ = B.SEQ
-- ================================================== INSERT
IF EXISTS (SELECT 1 
		   FROM OPENXML (@DOC, '/XML/I', 2) 
				   WITH (USE_YN NVARCHAR(1))
		   WHERE USE_YN = 'Y')
BEGIN
	UPDATE A
	SET A.USE_YN = 'N'
	FROM FI_PARTNERPTR A 
	JOIN OPENXML (@DOC, '/XML/I', 2) 
			WITH (CD_COMPANY NVARCHAR(7),
				  CD_PARTNER NVARCHAR(20)) B
	ON A.CD_COMPANY = B.CD_COMPANY
	AND A.CD_PARTNER = B.CD_PARTNER 
END

INSERT INTO FI_PARTNERPTR 
(
	CD_COMPANY,
	CD_PARTNER,
	SEQ,
	USE_YN,
	TP_PTR,
	YN_TYPE,
	YN_OUTSTANDING_INV,
	NM_PTR,
	EN_PTR,
	NM_DEPT,
	NM_DUTY_RESP,
	EN_DUTY_RESP,
	NM_EMAIL,
	NO_HP,
	NO_TEL,
	NO_FAX,
	CLIENT_NOTE,
	DC_PHOTO,
	YN_LIMIT,
	NO_MOBILE,
	ID_INSERT,
	DTS_INSERT
)
SELECT CD_COMPANY,
	   CD_PARTNER,
	   SEQ,
	   USE_YN,
	   TP_PTR,
	   YN_TYPE,
	   YN_OUTSTANDING_INV,
	   UPPER(NM_PTR),
	   EN_PTR,
	   NM_DEPT,
	   NM_DUTY_RESP,
	   EN_DUTY_RESP,
	   NM_EMAIL,
	   NO_HP,
	   NO_TEL,
	   NO_FAX,
	   CLIENT_NOTE,
	   DC_PHOTO,
	   YN_LIMIT,
	   NO_MOBILE,
       @P_ID_USER, 
       NEOE.SF_SYSDATE(GETDATE()) 
  FROM OPENXML (@DOC, '/XML/I', 2) 
          WITH (CD_COMPANY			NVARCHAR(7),
			    CD_PARTNER			NVARCHAR(20),
				SEQ					NUMERIC(5),
				USE_YN				NVARCHAR(1),
				TP_PTR				NVARCHAR(3),
				YN_TYPE				NVARCHAR(1),
				YN_OUTSTANDING_INV	NVARCHAR(1),
				NM_PTR				NVARCHAR(30),
				EN_PTR				NVARCHAR(100),
				NM_DEPT				NVARCHAR(100),
			    NM_DUTY_RESP		NVARCHAR(100),
				EN_DUTY_RESP		NVARCHAR(100),
				NM_EMAIL			NVARCHAR(80),
				NO_HP				NVARCHAR(15),
				NO_TEL				NVARCHAR(20),
				NO_FAX				NVARCHAR(20),
				CLIENT_NOTE			NVARCHAR(100),
				DC_PHOTO			NVARCHAR(50),
				YN_LIMIT			NVARCHAR(1),
				NO_MOBILE			NVARCHAR(100)) 
-- ================================================== UPDATE
IF EXISTS (SELECT 1 
		   FROM OPENXML (@DOC, '/XML/U', 2) 
				   WITH (USE_YN NVARCHAR(1))
		   WHERE USE_YN = 'Y')
BEGIN
	UPDATE A
	SET A.USE_YN = 'N'
	FROM FI_PARTNERPTR A 
	JOIN OPENXML (@DOC, '/XML/U', 2) 
			WITH (CD_COMPANY NVARCHAR(7),
				  CD_PARTNER NVARCHAR(20)) B
	ON A.CD_COMPANY = B.CD_COMPANY
	AND A.CD_PARTNER = B.CD_PARTNER 
END

UPDATE A 
   SET A.USE_YN = B.USE_YN,
	   A.TP_PTR = B.TP_PTR,	
	   A.YN_TYPE = B.YN_TYPE,
	   A.YN_OUTSTANDING_INV = B.YN_OUTSTANDING_INV,
	   A.NM_PTR = UPPER(B.NM_PTR),
	   A.EN_PTR = B.EN_PTR,
	   A.NM_DEPT = B.NM_DEPT,
	   A.NM_DUTY_RESP = B.NM_DUTY_RESP,
	   A.EN_DUTY_RESP = B.EN_DUTY_RESP,
	   A.NM_EMAIL = B.NM_EMAIL,
	   A.NO_HP = B.NO_HP,
	   A.NO_TEL = B.NO_TEL,
	   A.NO_FAX = B.NO_FAX,
	   A.CLIENT_NOTE = B.CLIENT_NOTE,
	   A.DC_PHOTO = B.DC_PHOTO,
	   A.YN_LIMIT = B.YN_LIMIT,
	   A.NO_MOBILE = B.NO_MOBILE,
	   A.ID_UPDATE = @P_ID_USER,
	   A.DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE())
  FROM FI_PARTNERPTR A 
  JOIN OPENXML (@DOC, '/XML/U', 2) 
          WITH (CD_COMPANY			NVARCHAR(7),
			    CD_PARTNER			NVARCHAR(20),
				SEQ					NUMERIC(5),
				USE_YN				NVARCHAR(1),
				TP_PTR				NVARCHAR(3),
				YN_TYPE				NVARCHAR(1),
				YN_OUTSTANDING_INV	NVARCHAR(1),
				NM_PTR				NVARCHAR(30),
				EN_PTR				NVARCHAR(100),
				NM_DEPT				NVARCHAR(100),
			    NM_DUTY_RESP		NVARCHAR(100),
				EN_DUTY_RESP		NVARCHAR(100),
				NM_EMAIL			NVARCHAR(80),
				NO_HP				NVARCHAR(15),
				NO_TEL				NVARCHAR(20),
				NO_FAX				NVARCHAR(20),
				CLIENT_NOTE			NVARCHAR(100),
				DC_PHOTO			NVARCHAR(50),
				YN_LIMIT			NVARCHAR(1),
				NO_MOBILE			NVARCHAR(100)) B 
  ON A.CD_COMPANY = B.CD_COMPANY
  AND A.CD_PARTNER = B.CD_PARTNER
  AND A.SEQ = B.SEQ 

EXEC SP_XML_REMOVEDOCUMENT @DOC 



GO

