USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_GIR_DAILY_PLAN_S2]    Script Date: 12/2/2015 10:10:47 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER PROCEDURE [NEOE].[SP_CZ_SA_GIR_DAILY_PLAN_S2]  
(  
	@P_NO_GIR		NVARCHAR(20)
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT GH.CD_COMPANY,
       MC.NM_COMPANY,
	   GH.STA_GIR,
	   GH.NO_GIR,
	   MH.NM_VESSEL,
	   ME.NM_KOR,
	   CD.NM_SYSDEF AS NM_MAIN_CATEGORY,
	   CD1.NM_SYSDEF AS NM_SUB_CATEGORY,
	   MP.LN_PARTNER,
	   (ISNULL(MP.DC_ADDRESS, '') + ' ' + ISNULL(MP.DC_ADDRESS1, '')) AS DC_ADS,
	   GL.QT_ITEM,
	   STUFF((SELECT '+' + MC.CD_FLAG2 + CONVERT(VARCHAR, CONVERT(INT, PH.QT_WIDTH))
			  FROM CZ_SA_PACKH PH
			  JOIN MA_CODEDTL MC ON MC.CD_COMPANY = PH.CD_COMPANY AND MC.CD_FIELD = 'CZ_SA00026' AND MC.CD_SYSDEF = PH.CD_TYPE
			  WHERE PH.CD_COMPANY = GH.CD_COMPANY
			  AND PH.NO_GIR = GH.NO_GIR
			  FOR XML PATH('')), 1,1, '')AS DC_RESULT_PACK,
	   STUFF((SELECT DISTINCT ',' + LEFT(GL.NO_SO, 2)
			  FROM SA_GIRL GL
			  WHERE GL.CD_COMPANY = GH.CD_COMPANY
			  AND GL.NO_GIR = GH.NO_GIR
			  FOR XML PATH('')), 1,1, '')AS NO_SO_PRE,
	   WD.DT_COMPLETE,
	   DATENAME(DW, WD.DT_COMPLETE) AS DT_NAME,
	   WD.DC_RMK AS DC_RMK_GIR,
	   WD.DC_RMK1,
	   WD.DC_RMK3,
	   '002' AS TP_PLAN,
	   ISNULL(GP.SEQ_PLAN, 0) AS SEQ_PLAN,
	   GP.DT_PLAN,
	   GP.NO_EMP,
	   ME1.NM_KOR AS NM_EMP,
	   GP.DC_RMK
FROM SA_GIRH GH
JOIN CZ_SA_GIRH_WORK_DETAIL WD ON WD.CD_COMPANY = GH.CD_COMPANY AND WD.NO_GIR = GH.NO_GIR
JOIN (SELECT GL.CD_COMPANY, GL.NO_GIR,
			 COUNT(1) AS QT_ITEM 
	  FROM SA_GIRL GL
	  GROUP BY GL.CD_COMPANY, GL.NO_GIR) GL
ON GL.CD_COMPANY = GH.CD_COMPANY AND GL.NO_GIR = GH.NO_GIR
LEFT JOIN CZ_SA_GIR_PLAN GP ON GP.CD_COMPANY = GH.CD_COMPANY AND GP.NO_GIR = GH.NO_GIR AND GP.TP_PLAN = '002'
LEFT JOIN MA_COMPANY MC ON MC.CD_COMPANY = GH.CD_COMPANY
LEFT JOIN CZ_MA_HULL MH ON MH.NO_IMO = WD.NO_IMO
LEFT JOIN MA_EMP ME ON ME.CD_COMPANY = GH.CD_COMPANY AND ME.NO_EMP = GH.NO_EMP
LEFT JOIN MA_EMP ME1 ON ME1.CD_COMPANY = GP.CD_COMPANY AND ME1.NO_EMP = GP.NO_EMP
LEFT JOIN CZ_MA_DELIVERY MP ON MP.CD_COMPANY = WD.CD_COMPANY AND MP.CD_PARTNER = WD.CD_DELIVERY_TO
LEFT JOIN MA_CODEDTL CD ON CD.CD_COMPANY = WD.CD_COMPANY AND CD.CD_FIELD = 'CZ_SA00006' AND CD.CD_SYSDEF = WD.CD_MAIN_CATEGORY
LEFT JOIN MA_CODEDTL CD1 ON CD1.CD_COMPANY = WD.CD_COMPANY AND CD1.CD_FIELD = CD.CD_FLAG1 AND CD1.CD_SYSDEF = WD.CD_SUB_CATEGORY
WHERE GH.CD_COMPANY IN ('K100', 'K200') 
AND (GH.STA_GIR IN ('O', 'R') OR ISNULL(GP.DT_PLAN, '') <> '')
AND GH.YN_RETURN = 'N'
AND WD.CD_MAIN_CATEGORY = '002'
AND WD.CD_SUB_CATEGORY = 'DIR'
AND (ISNULL(@P_NO_GIR, '') = '' OR GP.NO_GIR = @P_NO_GIR)
UNION ALL
SELECT GH.CD_COMPANY,
	   MC.NM_COMPANY,
	   GH.STA_GIR,
	   GH.NO_GIR,
	   MH.NM_VESSEL,
	   ME.NM_KOR,
	   CD.NM_SYSDEF AS NM_MAIN_CATEGORY,
	   CD1.NM_SYSDEF AS NM_SUB_CATEGORY,
	   MP.LN_PARTNER,
	   (ISNULL(MP.DC_ADDRESS, '') + ' ' + ISNULL(MP.DC_ADDRESS1, '')) AS DC_ADS,
	   GL.QT_ITEM,
	   STUFF((SELECT '+' + MC.CD_FLAG2 + CONVERT(VARCHAR, CONVERT(INT, PH.QT_WIDTH))
			  FROM CZ_SA_PACKH PH
			  JOIN MA_CODEDTL MC ON MC.CD_COMPANY = PH.CD_COMPANY AND MC.CD_FIELD = 'CZ_SA00026' AND MC.CD_SYSDEF = PH.CD_TYPE
			  WHERE PH.CD_COMPANY = GH.CD_COMPANY
			  AND PH.NO_GIR = GH.NO_GIR
			  FOR XML PATH('')), 1,1, '')AS DC_RESULT_PACK,
	   STUFF((SELECT DISTINCT ',' + LEFT(GL.NO_SO, 2)
			  FROM CZ_SA_GIRL_PACK GL
			  WHERE GL.CD_COMPANY = GH.CD_COMPANY
			  AND GL.NO_GIR = GH.NO_GIR
			  FOR XML PATH('')), 1,1, '')AS NO_SO_PRE,
	   WD.DT_COMPLETE,
	   DATENAME(DW, WD.DT_COMPLETE) AS DT_NAME, 
	   WD.DC_RMK AS DC_RMK_GIR,
	   WD.DC_RMK1,
	   WD.DC_RMK3,
	   '002' AS TP_PLAN,
	   ISNULL(GP.SEQ_PLAN, 0) AS SEQ_PLAN,
	   GP.DT_PLAN,
	   GP.NO_EMP,
	   ME1.NM_KOR AS NM_EMP,
	   GP.DC_RMK
FROM CZ_SA_GIRH_PACK GH
JOIN CZ_SA_GIRH_PACK_DETAIL WD ON WD.CD_COMPANY = GH.CD_COMPANY AND WD.NO_GIR = GH.NO_GIR
JOIN (SELECT GL.CD_COMPANY, GL.NO_GIR,
			 COUNT(1) AS QT_ITEM 
	  FROM CZ_SA_GIRL_PACK GL
	  GROUP BY GL.CD_COMPANY, GL.NO_GIR) GL
ON GL.CD_COMPANY = GH.CD_COMPANY AND GL.NO_GIR = GH.NO_GIR
LEFT JOIN CZ_SA_GIR_PLAN GP ON GP.CD_COMPANY = GH.CD_COMPANY AND GP.NO_GIR = GH.NO_GIR AND GP.TP_PLAN = '2'
LEFT JOIN MA_COMPANY MC ON MC.CD_COMPANY = GH.CD_COMPANY
LEFT JOIN CZ_MA_HULL MH ON MH.NO_IMO = WD.NO_IMO
LEFT JOIN MA_EMP ME ON ME.CD_COMPANY = GH.CD_COMPANY AND ME.NO_EMP = GH.NO_EMP
LEFT JOIN MA_EMP ME1 ON ME1.CD_COMPANY = GP.CD_COMPANY AND ME1.NO_EMP = GP.NO_EMP
LEFT JOIN CZ_MA_DELIVERY MP ON MP.CD_COMPANY = WD.CD_COMPANY AND MP.CD_PARTNER = WD.CD_COLLECT_FROM
LEFT JOIN MA_CODEDTL CD ON CD.CD_COMPANY = WD.CD_COMPANY AND CD.CD_FIELD = 'CZ_SA00020' AND CD.CD_SYSDEF = WD.CD_PACK_CATEGORY
LEFT JOIN MA_CODEDTL CD1 ON CD1.CD_COMPANY = WD.CD_COMPANY AND CD1.CD_FIELD = CD.CD_FLAG1 AND CD1.CD_SYSDEF = WD.CD_SUB_CATEGORY
WHERE GH.CD_COMPANY IN ('K100', 'K200') 
AND (GH.STA_GIR IN ('O', 'R') OR ISNULL(GP.DT_PLAN, '') <> '')
AND GH.YN_RETURN = 'N'
AND WD.CD_PACK_CATEGORY = '002'
AND (ISNULL(@P_NO_GIR, '') = '' OR GP.NO_GIR = @P_NO_GIR)

GO

