USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_GIR_DAILY_PLAN_S4]    Script Date: 12/2/2015 10:10:47 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER PROCEDURE [NEOE].[SP_CZ_SA_GIR_DAILY_PLAN_S4]  
(  
    @P_CLSGN   NVARCHAR(10)
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT VH.CLSGN,
       VH.NM_VSSL,
       VH.NM_PRTAG,
       VH.DTS_ETRYPT,
       VH.DTS_TKOFF,
       ISNULL(VL.NM_SATMN_ENTRPS, VL1.NM_SATMN_ENTRPS) AS NM_SATMN_ENTRPS,
       ISNULL(VL.NM_IBOBPRT, VL1.NM_IBOBPRT) AS NM_IBOBPRT,
       ISNULL(VL.NM_LAIDUPFCLTY, VL1.NM_LAIDUPFCLTY) AS NM_LAIDUPFCLTY
FROM (SELECT VH.CLSGN,
             VH.NM_VSSL,
             VH.CD_PRTAG,
             VH.DT_ETRYPT_YEAR,
             VH.CNT_ETRYPT,
             VH.NM_PRTAG,
             VH.DTS_ETRYPT,
             VH.DTS_TKOFF
      FROM CZ_SA_VSSL_ETRYNDH VH
      WHERE VH.CLSGN = @P_CLSGN) VH
LEFT JOIN CZ_SA_VSSL_ETRYNDL VL ON VL.CD_PRTAG = VH.CD_PRTAG AND VL.DT_ETRYPT_YEAR = VH.DT_ETRYPT_YEAR AND VL.CNT_ETRYPT = VH.CNT_ETRYPT AND VL.CLSGN = VH.CLSGN AND VL.NM_VSSL = VH.NM_VSSL AND VL.NM_ETRYND = '입항'
LEFT JOIN CZ_SA_VSSL_ETRYNDL VL1 ON VL1.CD_PRTAG = VH.CD_PRTAG AND VL1.DT_ETRYPT_YEAR = VH.DT_ETRYPT_YEAR AND VL1.CNT_ETRYPT = VH.CNT_ETRYPT AND VL1.CLSGN = VH.CLSGN AND VL1.NM_VSSL = VH.NM_VSSL AND VL1.NM_ETRYND = '출항'
ORDER BY VH.DTS_ETRYPT DESC

GO

