USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_GIR_DAILY_PLAN_S3]    Script Date: 12/2/2015 10:10:47 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER PROCEDURE [NEOE].[SP_CZ_SA_GIR_DAILY_PLAN_S3]  
(  
    @P_DT_TODAY		NVARCHAR(8)
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT ME.NO_EMP,
	   ME.NM_KOR,
	   CONVERT(CHAR(10), CONVERT(DATE, ME.DT_BIRTH), 23) AS DT_BIRTH,
	   CONVERT(CHAR(10), CONVERT(DATE, ME.DT_ENTER), 23) AS DT_ENTER,
	   (ISNULL(ME.DC_ADDRESS_RES1, '') + ' ' + ISNULL(ME.DC_ADDRESS_RES2, '')) AS DC_ADDRESS_RES,
	   (ISNULL(ME.DC_ADDRESS_CUR1, '') + ' ' + ISNULL(ME.DC_ADDRESS_CUR2, '')) AS DC_ADDRESS_CUR,
	   CC.NM_CC,
	   MC.NM_SYSDEF AS NM_DUTY_RANK,
	   ME.NO_TEL,
	   ME.NO_TEL_EMER,
	   WC.NM_WCODE 
FROM MA_EMP ME
LEFT JOIN MA_CC CC ON CC.CD_COMPANY = ME.CD_COMPANY AND CC.CD_CC = ME.CD_CC
LEFT JOIN HR_WTMCALC WT ON WT.CD_COMPANY = ME.CD_COMPANY AND WT.NO_EMP = ME.NO_EMP AND WT.DT_WORK = (CASE WHEN ISNULL(@P_DT_TODAY, '') = '' THEN CONVERT(CHAR(8), GETDATE(), 112) 
																																			ELSE @P_DT_TODAY END)
LEFT JOIN HR_WCODE WC ON WC.CD_COMPANY = WT.CD_COMPANY AND WC.CD_WCODE = WT.CD_WCODE
LEFT JOIN MA_CODEDTL MC ON MC.CD_COMPANY = ME.CD_COMPANY AND MC.CD_FIELD = 'HR_H000002' AND MC.CD_SYSDEF = ME.CD_DUTY_RANK
WHERE ME.CD_COMPANY = 'K100'
AND ISNULL(ME.DT_RETIRE, '00000000') = '00000000'
AND ME.CD_DEPT = '010500'

GO

