USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_GIR_DAILY_PLAN_S]    Script Date: 12/2/2015 10:10:47 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER PROCEDURE [NEOE].[SP_CZ_SA_GIR_DAILY_PLAN_S]  
(  
    @P_DT_TODAY     NVARCHAR(8),
    @P_NO_GIR       NVARCHAR(20)
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT GP.SEQ_PLAN,
       GP.NO_EMP,
       ME.NM_KOR AS NM_EMP,
       CC.NM_CC,
       GP.DT_PLAN,
       GP.TP_PLAN,
       GP.NO_GIR,
       GP.DC_RMK
FROM CZ_SA_GIR_PLAN GP
LEFT JOIN MA_EMP ME ON ME.CD_COMPANY = 'K100' AND ME.NO_EMP = GP.NO_EMP
LEFT JOIN MA_CC CC ON CC.CD_COMPANY = ME.CD_COMPANY AND CC.CD_CC = ME.CD_CC
WHERE GP.DT_PLAN = @P_DT_TODAY
AND (ISNULL(@P_NO_GIR, '') = '' OR GP.NO_GIR = @P_NO_GIR)

GO

