USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_EXPENSE_MNG_U]    Script Date: 2016-04-07 오전 10:19:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER PROCEDURE [NEOE].[SP_CZ_SA_EXPENSE_MNG_U] 
(
	@P_CD_COMPANY		NVARCHAR(7),
	@P_TP_IO			NVARCHAR(3),
	@P_NO_IV			NVARCHAR(20),
	@P_NO_LINE			NUMERIC(5, 0),
	@P_TXT_USERDEF1		NVARCHAR(200),
	@P_ID_UPDATE		NVARCHAR(15)
) 
AS

IF @P_TP_IO = '001'
BEGIN
	UPDATE PU_IVL
	SET TXT_USERDEF1 = @P_TXT_USERDEF1
	WHERE CD_COMPANY = @P_CD_COMPANY
	AND NO_IV = @P_NO_IV
	AND NO_LINE = @P_NO_LINE
END
ELSE
BEGIN
	UPDATE SA_IVL
	SET TXT_USERDEF1 = @P_TXT_USERDEF1,
	    ID_UPDATE = @P_ID_UPDATE,
		DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE())
	WHERE CD_COMPANY = @P_CD_COMPANY
	AND NO_IV = @P_NO_IV
	AND NO_LINE = @P_NO_LINE
END


GO

