USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_PU_IV_REGH_SUB_S]    Script Date: 2015-06-23 오후 4:38:34 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_FI_IMP_PMT_REGH_S]      
(      
	@P_CD_COMPANY		NVARCHAR(7),      
	@P_DT_FROM			NVARCHAR(8),  
	@P_DT_TO			NVARCHAR(8),           
	@P_CD_PARTNER		NVARCHAR(20),      
	@P_NO_PO			NVARCHAR(20),
	@P_ID_USER			NVARCHAR(20)
)
AS  

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT 'N' AS S,
	   PH.DT_PO,
	   ISNULL(PL.AM_EX, 0) AS AM_EX,
	   ISNULL(PL.AM, 0) AS AM,
	   PH.NO_PO,
	   PH.CD_PJT,
	   PH.CD_PARTNER,
	   MP.LN_PARTNER AS NM_SUPPLIER,
	   0 AS AM_TAX,
	   PH.NO_EMP AS NO_EMP_PO,
	   ME.NM_KOR AS NM_KOR_PO 
FROM PU_POH PH
JOIN (SELECT PL.CD_COMPANY,
			 PL.NO_PO,
			 SUM(PL.AM_EX) AS AM_EX,
	         SUM(PL.AM) AS AM  
	  FROM PU_POL PL
	  WHERE NOT EXISTS (SELECT 1 
						FROM CZ_FI_IMP_PMTL IL
						WHERE IL.CD_COMPANY = PL.CD_COMPANY 
						AND IL.NO_PO = PL.NO_PO
						AND IL.NO_POLINE = PL.NO_LINE)
	  GROUP BY PL.CD_COMPANY, PL.NO_PO) PL 
ON PL.CD_COMPANY = PH.CD_COMPANY AND PL.NO_PO = PH.NO_PO
LEFT JOIN MA_PARTNER MP ON MP.CD_COMPANY = PH.CD_COMPANY AND MP.CD_PARTNER = PH.CD_PARTNER
LEFT JOIN MA_EMP ME ON ME.CD_COMPANY = PH.CD_COMPANY AND ME.NO_EMP = PH.NO_EMP
WHERE PH.CD_COMPANY = @P_CD_COMPANY
AND PH.DT_PO BETWEEN @P_DT_FROM AND @P_DT_TO
AND (ISNULL(@P_CD_PARTNER, '') = '' OR PH.CD_PARTNER = @P_CD_PARTNER)
AND (ISNULL(@P_NO_PO, '') = '' OR PH.NO_PO LIKE @P_NO_PO + '%')

GO

