USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_GIRL_SCH_SUB_S]    Script Date: 2015-06-02 오후 7:43:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_SA_GIRL_SCH_SUB_S]  
(    
    @P_CD_COMPANY           NVARCHAR(7),    
    @P_NO_GIR               NVARCHAR(20),
	@P_YN_PACK				NVARCHAR(1)
)    
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

DECLARE @QUERY			NVARCHAR(MAX)
DECLARE @HEADER			NVARCHAR(MAX)
DECLARE @LINE			NVARCHAR(MAX)

IF @P_YN_PACK = 'Y'
BEGIN
	SET @HEADER = 'CZ_SA_GIRH_PACK'
	SET @LINE = 'CZ_SA_GIRL_PACK'
END
ELSE
BEGIN
	SET @HEADER = 'SA_GIRH'
	SET @LINE = 'SA_GIRL'
END

SET @QUERY = 'SELECT GL.NO_GIR,       --의뢰번호  
					 GL.SEQ_GIR,      --의뢰항번  
					 GL.CD_ITEM,      --품목코드  
					 MI.NM_ITEM,       --품목명  
					 MI.STND_ITEM,	  --규격			(2011-10-27, 최승애 추가)
					 GL.QT_GIR,       --의뢰수량  
					 GL.UNIT,         --재고단위  
					 GL.UM,           --단가  
					 GL.AM_GIR,       --금액  
					 GL.AM_GIRAMT,    --원화금액  
					 GL.AM_VAT,       --부가세  
					 GL.QT_GIR_IM,    --관리수량  
					 GL.QT_GI,        --출고수량  
					 ISNULL(QL.CD_ITEM_PARTNER, '''') CD_ITEM_PARTNER,   
					 ISNULL(QL.NM_ITEM_PARTNER, '''') NM_ITEM_PARTNER,
					 GL.DT_REQGI,    --출고예정일
					 GL.DT_DUEDATE,	 --납기일
					 (SL.QT_SO - PL.QT_GIR) AS REQ_QT_GIR, --의뢰적용수량
					 SL.NO_SO,			--수주번호
					 GL.NO_PROJECT,
					 SP.NM_PROJECT
			FROM ' + @LINE + ' GL  
            JOIN ' + @HEADER + ' GH ON GL.CD_COMPANY = GH.CD_COMPANY AND GL.NO_GIR = GH.NO_GIR  
            LEFT JOIN MA_PITEM MI ON GL.CD_COMPANY = MI.CD_COMPANY AND GH.CD_PLANT = MI.CD_PLANT AND GL.CD_ITEM = MI.CD_ITEM   
            LEFT JOIN SA_SOL SL ON GL.CD_COMPANY = SL.CD_COMPANY AND GH.CD_PLANT = SL.CD_PLANT AND GL.NO_SO = SL.NO_SO AND GL.SEQ_SO = SL.SEQ_SO
			LEFT JOIN CZ_SA_QTNL QL ON QL.CD_COMPANY = GL.CD_COMPANY AND QL.NO_FILE = GL.NO_SO AND QL.NO_LINE = GL.SEQ_SO 
			LEFT JOIN (SELECT CD_COMPANY, NO_SO, SEQ_SO, SUM(QT_GIR) AS QT_GIR 
					   FROM ' + @LINE + ' 
					   GROUP BY CD_COMPANY, NO_SO, SEQ_SO) PL 
		    ON PL.CD_COMPANY = SL.CD_COMPANY AND PL.NO_SO = SL.NO_SO AND PL.SEQ_SO = SL.SEQ_SO 
            LEFT JOIN SA_PROJECTH SP ON GL.CD_COMPANY = SP.CD_COMPANY AND GL.NO_PROJECT = SP.NO_PROJECT
			WHERE GL.CD_COMPANY = ''' + @P_CD_COMPANY + '''  
			AND GL.NO_GIR = ''' + @P_NO_GIR + ''''  

EXEC SP_EXECUTESQL @QUERY
PRINT @QUERY  

GO