USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_SO_PR_WO_RPTD_S]    Script Date: 2019-11-14 오후 3:11:38 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER PROCEDURE [NEOE].[SP_CZ_SA_SO_PR_WO_RPTD_S]        
(  
    @P_CD_COMPANY   NVARCHAR(7),
	@P_NO_WO		NVARCHAR(20)
)        
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT WR.CD_OP,
	   WC.NM_WC,
	   OP.NM_OP,
	   CD.NM_SYSDEF AS NM_ST_OP,
	   WR.QT_WO,
	   WR.QT_START,
	   WR.QT_WORK,
	   WR.QT_REJECT,
	   WR.QT_REWORK,
	   WR.QT_MOVE,
	   WR.QT_WIP,
	   (CASE WHEN ISNULL(WR.QT_WO, 0) = 0 THEN 0.0 ELSE ROUND(ISNULL(WR.QT_WORK, 0) / ISNULL(WR.QT_WO, 0) * 100, 2) END) AS RT_WORK,
	   EQ.NM_EQUIP,
	   WR.YN_FINAL
FROM PR_WO_ROUT WR
LEFT JOIN MA_WC WC ON WC.CD_COMPANY = WR.CD_COMPANY AND WC.CD_PLANT = WR.CD_PLANT AND WC.CD_WC = WR.CD_WC
LEFT JOIN PR_WCOP OP ON OP.CD_COMPANY = WR.CD_COMPANY AND OP.CD_PLANT = WR.CD_PLANT AND OP.CD_WC = WR.CD_WC AND OP.CD_WCOP = WR.CD_WCOP
LEFT JOIN PR_EQUIP EQ ON EQ.CD_COMPANY = WR.CD_COMPANY AND EQ.CD_PLANT = WR.CD_PLANT AND EQ.CD_EQUIP = WR.CD_EQUIP
LEFT JOIN MA_CODEDTL CD ON CD.CD_COMPANY = WR.CD_COMPANY AND CD.CD_FIELD = 'PR_0000009' AND CD.CD_SYSDEF = WR.ST_OP
WHERE WR.CD_COMPANY = @P_CD_COMPANY
AND WR.NO_WO = @P_NO_WO
ORDER BY WR.CD_OP

GO