//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:2.0.50727.5485
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pur {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 내역표시_Text {
            get {
                return ((string)(this["내역표시_Text"]));
            }
            set {
                this["내역표시_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("모두")]
        public string 내역표시 {
            get {
                return ((string)(this["내역표시"]));
            }
            set {
                this["내역표시"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string 내용표시_QTY {
            get {
                return ((string)(this["내용표시_QTY"]));
            }
            set {
                this["내용표시_QTY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string 내용표시_UM {
            get {
                return ((string)(this["내용표시_UM"]));
            }
            set {
                this["내용표시_UM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 품목표시 {
            get {
                return ((string)(this["품목표시"]));
            }
            set {
                this["품목표시"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Tx_내역표시구분 {
            get {
                return ((string)(this["Tx_내역표시구분"]));
            }
            set {
                this["Tx_내역표시구분"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Tx_내역표시_Text {
            get {
                return ((string)(this["Tx_내역표시_Text"]));
            }
            set {
                this["Tx_내역표시_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Tx_품목표시구분 {
            get {
                return ((string)(this["Tx_품목표시구분"]));
            }
            set {
                this["Tx_품목표시구분"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://165.244.237.222:5530/ws/FI.CNPPurchaseRequest.providers.CNPPurchaseRequest" +
            "_Provider/FI_CNPPurchaseRequest_providers_CNPPurchaseRequest_Provider_Port")]
        public string P_PU_IV_MNG_WebServiceCNP_LIVE_FI_CNPPurchaseRequest_providers_CNPPurchaseRequest_Provider {
            get {
                return ((string)(this["P_PU_IV_MNG_WebServiceCNP_LIVE_FI_CNPPurchaseRequest_providers_CNPPurchaseRequest" +
                    "_Provider"]));
            }
        }
    }
}
