USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_FI_TAX_EXPORTD_I]    Script Date: 2015-08-11 오전 9:59:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_FI_TAX_EXPORTD_I] 
(
	@P_CD_COMPANY			NVARCHAR(7),
	@P_NO_TAX				NVARCHAR(20),
	@P_NO_IO				NVARCHAR(20),
	@P_ID_INSERT			NVARCHAR(15)
) 
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

IF NOT EXISTS (SELECT 1 
			   FROM CZ_FI_TAX_EXPORT_D ED
			   WHERE ED.CD_COMPANY = @P_CD_COMPANY
			   AND ED.NO_TAX = @P_NO_TAX
			   AND ED.NO_IO = @P_NO_IO)
BEGIN
	INSERT INTO CZ_FI_TAX_EXPORT_D
	(
		CD_COMPANY,
		NO_TAX,
		NO_IO,
		ID_INSERT,
		DTS_INSERT
	)
	VALUES
	(
		@P_CD_COMPANY,
		@P_NO_TAX,
		@P_NO_IO,
		@P_ID_INSERT,
		NEOE.SF_SYSDATE(GETDATE())
	)
END



GO