USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_FI_TAX_EXPORTD_S]    Script Date: 2015-08-11 오전 9:59:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_FI_TAX_EXPORTD_S] 
(
	@P_CD_COMPANY			NVARCHAR(7),
	@P_NO_TAX				NVARCHAR(20)
) 
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT 'N' AS S,
	   ED.NO_TAX AS NO_TO,
	   ED.NO_IO,
	   '조회' AS DC_RMK
FROM CZ_FI_TAX_EXPORT_D ED
WHERE ED.CD_COMPANY = @P_CD_COMPANY
AND ED.NO_TAX = @P_NO_TAX

GO