USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_FI_TAX_EXPORTH_U]    Script Date: 2015-08-11 오전 11:18:27 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_FI_TAX_EXPORTH_U] 
(
	@P_CD_COMPANY		NVARCHAR(7),
	@P_NO_TAX			NVARCHAR(20),
	@P_YN_CHECK			NVARCHAR(1),
	@P_DC_IMPORT		NVARCHAR(100),
	@P_DC_RMK			NVARCHAR(500),
	@P_ID_UPDATE		NVARCHAR(15)
) 
AS

UPDATE TE
SET TE.YN_CHECK = @P_YN_CHECK,
	TE.DC_IMPORT = @P_DC_IMPORT,
	TE.DC_RMK = @P_DC_RMK,
	TE.ID_UPDATE = @P_ID_UPDATE,
    TE.DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE())
FROM CZ_FI_TAX_EXPORT TE
WHERE TE.CD_COMPANY = @P_CD_COMPANY
AND TE.NO_TAX = @P_NO_TAX

GO