USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_FI_TAX_EXPORT_PARSING]    Script Date: 2016-06-28 오후 1:28:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_FI_TAX_EXPORT_PARSING] 
(
	@P_CD_COMPANY	NVARCHAR(7),
	@P_XML			XML, 
	@P_ID_USER		NVARCHAR(10)
) 
AS 

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

-- ================================================== 데이터 업데이트
DECLARE @V_DOC INT

EXEC SP_XML_PREPAREDOCUMENT @V_DOC OUTPUT, @P_XML 

SELECT * INTO #XML
FROM OPENXML (@V_DOC, '/XML/ROW', 2) WITH 
(
	NO_TAX				NVARCHAR(20),
	NO_IMPORT			NVARCHAR(100),
	DC_TAX				NVARCHAR(1000)
)

EXEC SP_XML_REMOVEDOCUMENT @V_DOC 

UPDATE A
SET A.NO_IMPORT = B.NO_IMPORT,
	A.DC_TAX = B.DC_TAX,
	A.ID_UPDATE = @P_ID_USER, 
	A.DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE())
FROM CZ_FI_TAX_EXPORT A
JOIN #XML B ON REPLACE(B.NO_TAX, '-', '') = A.NO_TAX
WHERE A.CD_COMPANY = @P_CD_COMPANY

GO