USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_MA_FORWARD_EXCHANGE_S]    Script Date: 2016-05-03 오후 5:11:29 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER PROCEDURE [NEOE].[SP_CZ_MA_FORWARD_EXCHANGE_REG_S]
(
	@P_CD_COMPANY			   NVARCHAR(7),
	@P_DT_EXCH_FROM			   NVARCHAR(8),
	@P_DT_EXCH_TO			   NVARCHAR(8),
	@P_DT_CONTRACT_FROM		   NVARCHAR(8),
	@P_DT_CONTRACT_TO		   NVARCHAR(8),
	@P_DT_MONTH				   NVARCHAR(6),
	@P_CD_BANK				   NVARCHAR(3),
	@P_YN_AFTER				   NVARCHAR(1)
) 
AS 

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT FE.CD_BANK,
	   MC.NM_SYSDEF AS NM_BANK,
	   FE.DT_EXCH,
	   SUBSTRING(FE.DT_EXCH, 0, 7) AS DT_MONTH,
	   FE.DT_CONTRACT,
	   FE.RT_EXCH,
	   FE.AM_EX,
	   FE.AM,
	   FE.SWAP,
	   FE.COMMISSION,
	   ISNULL(ME.RATE_BASE, ME1.RATE_BASE) AS RT_EVALUATION,
	   (FE.AM - (FE.AM_EX * ISNULL(ME.RATE_BASE, ME1.RATE_BASE))) AS AM_PL
FROM CZ_MA_FORWARD_EXCHANGE FE
LEFT JOIN MA_CODEDTL MC ON MC.CD_COMPANY = FE.CD_COMPANY AND MC.CD_FIELD = 'CZ_MA00008' AND MC.CD_SYSDEF = FE.CD_BANK
LEFT JOIN MA_EXCHANGE ME ON ME.CD_COMPANY = FE.CD_COMPANY AND ME.CURR_SOUR = '001' AND ME.CURR_DEST = '000' AND ME.YYMMDD = FE.DT_EXCH AND ME.NO_SEQ = '1'
LEFT JOIN MA_EXCHANGE ME1 ON ME1.CD_COMPANY = FE.CD_COMPANY AND ME1.CURR_SOUR = '001' AND ME1.CURR_DEST = '000' AND ME1.YYMMDD = CONVERT(CHAR(8), GETDATE(), 112) AND ME1.NO_SEQ = '2'
WHERE FE.CD_COMPANY = @P_CD_COMPANY
AND FE.DT_EXCH BETWEEN @P_DT_EXCH_FROM AND @P_DT_EXCH_TO
AND FE.DT_CONTRACT BETWEEN @P_DT_CONTRACT_FROM AND @P_DT_CONTRACT_TO
AND ((@P_YN_AFTER = 'Y' AND FE.DT_EXCH > CONVERT(CHAR(8), GETDATE(), 112)) OR (@P_YN_AFTER = 'N'))
AND (ISNULL(@P_DT_MONTH, '') = '' OR SUBSTRING(FE.DT_EXCH, 0, 7) = @P_DT_MONTH)
AND (ISNULL(@P_CD_BANK, '') = '' OR FE.CD_BANK = @P_CD_BANK)
ORDER BY DT_CONTRACT

GO

