USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_MA_DOCUMENT_MNG_WINTEC_S]    Script Date: 2017-01-05 오후 5:48:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_MA_DOCUMENT_MNG_WINTEC_S1]          
(
	@P_CD_COMPANY	NVARCHAR(7),
	@P_CD_PLANT		NVARCHAR(7),
	@P_CD_ITEM		NVARCHAR(20),
	@P_NO_DRAWING	NVARCHAR(20)
)  
AS
   
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT CT.SEQ,
	   CT.NO_DOC,
	   CT.CD_SUPPLIER,
	   MP.LN_PARTNER AS NM_SUPPLIER,
	   CT.DC_TYPE,
	   CT.CD_ITEM,
	   MI.NM_ITEM,
	   CT.NO_DRAWING,
	   CT.DC_MAT,
	   CT.DC_SIZE,
	   CT.TP_UNIT,
	   CT.QT_IN,
	   CT.NO_HEAT,
	   CT.NO_LOT,
	   CT.NM_FILE,
	   CT.DC_RMK
FROM CZ_MA_CERT_WINTEC CT
LEFT JOIN MA_PITEM MI ON MI.CD_COMPANY = CT.CD_COMPANY AND MI.CD_PLANT = CT.CD_PLANT AND MI.CD_ITEM = CT.CD_ITEM
LEFT JOIN MA_PARTNER MP ON MP.CD_COMPANY = CT.CD_COMPANY AND MP.CD_PARTNER = CT.CD_SUPPLIER
WHERE CT.CD_COMPANY = @P_CD_COMPANY
AND CT.CD_PLANT = @P_CD_PLANT
AND (ISNULL(@P_CD_ITEM, '') = '' OR CT.CD_ITEM = @P_CD_ITEM)
AND (ISNULL(@P_NO_DRAWING, '') = '' OR CT.NO_DRAWING LIKE @P_NO_DRAWING + '%')
ORDER BY CT.SEQ

GO

