USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_MA_DOCUMENT_MNG_WINTEC_XML]    Script Date: 2016-11-30 오후 5:22:08 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER PROCEDURE [NEOE].[SP_CZ_MA_DOCUMENT_MNG_WINTEC_XML1] 
(
	@P_CD_COMPANY	NVARCHAR(7),
	@P_CD_PLANT		NVARCHAR(20),
	@P_XML			XML, 
	@P_ID_USER		NVARCHAR(10), 
    @DOC			INT = NULL
) 
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

EXEC SP_XML_PREPAREDOCUMENT @DOC OUTPUT, @P_XML 

-- ================================================== DELETE
DELETE A 
FROM CZ_MA_CERT_WINTEC A 
JOIN OPENXML (@DOC, '/XML/D', 2) 
        WITH (SEQ		  NUMERIC(5, 0)) B 
ON A.CD_COMPANY = @P_CD_COMPANY
AND A.CD_PLANT = @P_CD_PLANT
AND A.SEQ = B.SEQ

-- ================================================== INSERT
INSERT INTO CZ_MA_CERT_WINTEC 
(
	CD_COMPANY,
    CD_PLANT,
	SEQ,
	NO_DOC,
	CD_SUPPLIER,
	DC_TYPE,
	CD_ITEM,
	NO_DRAWING,
	DC_MAT,
	DC_SIZE,
	TP_UNIT,
	QT_IN,
	NO_HEAT,
	NO_LOT,
	DC_RMK,
    ID_INSERT,
    DTS_INSERT
)
SELECT @P_CD_COMPANY,
	   @P_CD_PLANT,
	   SEQ,
	   NO_DOC,
	   CD_SUPPLIER,
	   DC_TYPE,
	   CD_ITEM,
	   NO_DRAWING,
	   DC_MAT,
	   DC_SIZE,
	   TP_UNIT,
	   QT_IN,
	   NO_HEAT,
	   NO_LOT,
	   DC_RMK,
       @P_ID_USER, 
       NEOE.SF_SYSDATE(GETDATE()) 
FROM OPENXML (@DOC, '/XML/I', 2) 
        WITH (SEQ		    NUMERIC(5, 0),
			  NO_DOC		NVARCHAR(50),
			  CD_SUPPLIER	NVARCHAR(20),
			  DC_TYPE		NVARCHAR(50),
			  CD_ITEM		NVARCHAR(20),
			  NO_DRAWING	NVARCHAR(100),
			  DC_MAT		NVARCHAR(50),
			  DC_SIZE		NVARCHAR(50),
			  TP_UNIT		NVARCHAR(4),
			  QT_IN			NUMERIC(10, 0),
			  NO_HEAT		NVARCHAR(50),
			  NO_LOT		NVARCHAR(50),
			  DC_RMK		NVARCHAR(MAX))
-- ================================================== UPDATE    
UPDATE A 
   SET A.NO_DOC = B.NO_DOC,
	   A.CD_SUPPLIER = B.CD_SUPPLIER,
	   A.DC_TYPE = B.DC_TYPE,
	   A.CD_ITEM = B.CD_ITEM,
	   A.NO_DRAWING = B.NO_DRAWING,
	   A.DC_MAT = B.DC_MAT,
	   A.DC_SIZE = B.DC_SIZE,
	   A.TP_UNIT = B.TP_UNIT,
	   A.QT_IN = B.QT_IN,
	   A.NO_HEAT = B.NO_HEAT,
	   A.NO_LOT = B.NO_LOT,
	   A.DC_RMK = B.DC_RMK,
	   A.ID_UPDATE = @P_ID_USER, 
	   A.DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE())
  FROM CZ_MA_CERT_WINTEC A 
  JOIN OPENXML (@DOC, '/XML/U', 2) 
          WITH (SEQ		    NUMERIC(5, 0),
				NO_DOC		NVARCHAR(50),
				CD_SUPPLIER	NVARCHAR(20),
				DC_TYPE		NVARCHAR(50),
				CD_ITEM		NVARCHAR(20),
				NO_DRAWING	NVARCHAR(100),
				DC_MAT		NVARCHAR(50),
				DC_SIZE		NVARCHAR(50),
				TP_UNIT		NVARCHAR(4),
				QT_IN	    NUMERIC(10, 0),
				NO_HEAT		NVARCHAR(50),
				NO_LOT		NVARCHAR(50),
			    DC_RMK		NVARCHAR(MAX)) B 
  ON A.CD_COMPANY = @P_CD_COMPANY
  AND A.CD_PLANT = @P_CD_PLANT
  AND A.SEQ = B.SEQ

EXEC SP_XML_REMOVEDOCUMENT @DOC 

GO

