USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[UP_CZ_PU_PO_REG_PRINT]    Script Date: 2022-03-24 오전 10:56:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
                       

                                                             
ALTER PROC [NEOE].[UP_CZ_PU_PO_REG_PRINT]    
(                                       
 @CD_COMPANY	NVARCHAR(7),                                        
 @NO_PO			NVARCHAR(20),    
 @P_USER_ID		NVARCHAR(15) = '',
 @P_FG_LANG     NVARCHAR(4) = NULL	--언어
)   

AS
-- MultiLang Call
EXEC UP_MA_LOCAL_LANGUAGE @P_FG_LANG
                                         
SELECT      
 H.NO_PO,    
 H.NO_PO AS 발주번호,     
 H.CD_PLANT,    
 H.CD_PLANT AS 공장명,    
 H.CD_PARTNER,                                       
 H.CD_PARTNER AS 거래처명,     
 H.DT_PO,     
 CASE WHEN SUBSTRING(H.DT_PO,5,2) = '01' THEN 'Jan'      
 WHEN SUBSTRING(H.DT_PO,5,2) = '02' THEN 'Feb'      
 WHEN SUBSTRING(H.DT_PO,5,2) = '03' THEN 'Mar'      
 WHEN SUBSTRING(H.DT_PO,5,2) = '04' THEN 'Apr'      
 WHEN SUBSTRING(H.DT_PO,5,2) = '05' THEN 'May'      
 WHEN SUBSTRING(H.DT_PO,5,2) = '06' THEN 'Jun'      
 WHEN SUBSTRING(H.DT_PO,5,2) = '07' THEN 'Jul'      
 WHEN SUBSTRING(H.DT_PO,5,2) = '08' THEN 'Aug'      
 WHEN SUBSTRING(H.DT_PO,5,2) = '09' THEN 'Sep'      
 WHEN SUBSTRING(H.DT_PO,5,2) = '10' THEN 'Oct'      
 WHEN SUBSTRING(H.DT_PO,5,2) = '11' THEN 'Nov'      
 WHEN SUBSTRING(H.DT_PO,5,2) = '12' THEN 'Dec'      
 END      
  + '.' + SUBSTRING(H.DT_PO,7,2)       
  + '.' + SUBSTRING(H.DT_PO,1,4) AS DT_PO_CON, 
 H.CD_PURGRP,                               
 H.NO_EMP, H.CD_TPPO, H.FG_UM, H.FG_PAYMENT,  
  (SELECT NM_ENG FROM DZSN_MA_EMP      
 WHERE CD_COMPANY=H.CD_COMPANY AND NO_EMP = (      
 SELECT TOP 1 NM_SYSDEF FROM DZSN_MA_CODEDTL      
 WHERE CD_COMPANY=H.CD_COMPANY AND CD_FIELD='PU_C000080' AND USE_YN = 'Y')) AS NM_ENG_SIGN,             
 (SELECT TOP 1 CD_FLAG1 FROM DZSN_MA_CODEDTL      
WHERE CD_COMPANY=H.CD_COMPANY AND CD_FIELD='HR_H000052'      
AND CD_SYSDEF IN (SELECT CD_DUTY_RESP FROM DZSN_MA_EMP      
WHERE CD_COMPANY=H.CD_COMPANY AND NO_EMP IN (      
SELECT NM_SYSDEF FROM DZSN_MA_CODEDTL      
WHERE CD_COMPANY=H.CD_COMPANY AND CD_FIELD='PU_C000080' AND USE_YN = 'Y')) ) AS CD_FLAG1,                             
 (SELECT TOP 1 CD_FLAG2 FROM DZSN_MA_CODEDTL      
WHERE CD_COMPANY=H.CD_COMPANY AND CD_FIELD='HR_H000052'      
AND CD_SYSDEF IN (SELECT CD_DUTY_RESP FROM DZSN_MA_EMP      
WHERE CD_COMPANY=H.CD_COMPANY AND NO_EMP IN (      
SELECT NM_SYSDEF FROM DZSN_MA_CODEDTL      
WHERE CD_COMPANY=H.CD_COMPANY AND CD_FIELD='PU_C000080' AND USE_YN = 'Y')) ) AS CD_FLAG2,                                     
 H.FG_TAX, H.NO_ORDER,                                                     
 H.TP_UM_TAX, H.CD_PJT AS CD_PJT_H, H.CD_EXCH , H.RT_EXCH,   
(SELECT NM_SYSDEF FROM DZSN_MA_CODEDTL WHERE CD_COMPANY = H.CD_COMPANY AND CD_FIELD = 'MA_B000005' AND CD_SYSDEF = (SELECT CD_EXCH FROM PU_POH WHERE CD_COMPANY = H.CD_COMPANY AND NO_PO = H.NO_PO)) AS NM_EXCH,                        
 H.AM_EX AS AM_EX_H,                         
 H.AM AS AM_H ,     
 H.VAT AS H_VAT,    
 H.VAT AS VAT,  
(H.AM + H.VAT) AS TOT,       
 H.DC50_PO,                                       
 H.TP_PROCESS, H.FG_TAXP, H.YN_AM, H.FG_TRANS,    
 H.FG_TRACK,                                            
 G.NM_PURGRP,                          
 G.EN_PURGRP,                          
 B.USE_YN,                               
 B.PO_PRICE, B.PO_UNIT,B.TP_PURPRICE,L.DC1,                                                      
 (SELECT P.LN_PARTNER FROM DZSN_MA_PARTNER P WHERE P.CD_COMPANY = H.CD_COMPANY AND P.CD_PARTNER= H.CD_PARTNER) AS NM_PARTNER,      
 P.LN_PARTNER AS NM_PARTNER, 
 P.NM_PTR,      
 P.NO_TEL,      
 P.NO_FAX,      
 E.NM_KOR AS NM_KOR,    
 E.NM_ENG AS NM_ENG,                                       
 E.CD_DEPT,                                                     
 (SELECT A.NM_DEPT FROM DZSN_MA_DEPT A WHERE A.CD_DEPT = E.CD_DEPT AND A.CD_COMPANY = E.CD_COMPANY) AS NM_DEPT,
 (SELECT NM_KOR FROM DZSN_MA_EMP WHERE CD_COMPANY = H.CD_COMPANY AND NO_EMP = MD11.NO_EMPMNG) AS NM_EMPMNG, -- 현대위아IHI터보 부서장
 E.NM_KOR + '/' + (SELECT A.NM_DEPT FROM DZSN_MA_DEPT A WHERE A.CD_DEPT = E.CD_DEPT AND A.CD_COMPANY = E.CD_COMPANY) AS REQ_EMP_DEPT,
 MC7.NM_SYSDEF_E AS EN_DUTY_RANK,  -- 현대위아IHI터보 부서장 직위명 영문                                                  
 (SELECT D.NM_SYSDEF FROM DZSN_MA_CODEDTL D WHERE D.CD_COMPANY = H.CD_COMPANY AND D.CD_SYSDEF = H.FG_TRANS AND D.CD_FIELD = 'PU_C000016' ) AS  NM_TRANS,                                        
 M05.RT_VAT_STR AS VAT_RATE,
 CASE WHEN LEN(H.CD_PJT) > 0 THEN ( SELECT TOP 1 PJ.NM_PROJECT FROM DZSN_SA_PROJECTH PJ WHERE PJ.CD_COMPANY = H.CD_COMPANY AND PJ.NO_PROJECT = H.CD_PJT ORDER BY NO_SEQ DESC ) ELSE '' END AS NM_PJT,                                                  
 T.CD_TPPO,T.NM_TPPO, T.YN_ORDER, T.YN_RCV, T.FG_TPRCV, T.YN_AUTORCV, T.FG_TPPURCHASE,       
 T.YN_IMPORT,T.FG_TPIMPORT, T.YN_RETURN, T.YN_SUBCON,T.FG_TRANS, T.YN_AM,                                      
 T.YN_USE,        
 T.YN_REQ,        
 H.DTS_INSERT,                                
 H.ID_INSERT ,                                               
 C.NO_COMPANY,                                    
 C.NM_CEO,                                       
 C.ADS_NO,                                       
 C.ADS_H,                      
 C.ADS_D,                                                                            
 P.LN_PARTNER,                                       
 P.NM_CEO NM_CEO1,                                       
 P.NO_POST1,                                       
 P.DC_ADS1_H,                           
 P.DC_ADS1_D,                                       
 P.NO_TEL1,                                       
 P.NO_FAX1,                        
 P.NO_FAX,                                       
 P.NM_PTR,                                              
 G.NO_TEL PURGRP_NO_TEL,                                       
 G.NO_FAX PURGRP_NO_FAX,                     
 G.E_MAIL AS PURGRP_E_MAIL,       --구매그룹 E_MAIL    
 H.CD_AGENCY,                                   
 H.DC_RMK2,                                          
 H.TP_TRANSPORT,                                   
 H.COND_PAY,                                    
 H.COND_PAY_DLV,                                    
 H.COND_PRICE,                                    
 H.ARRIVER,                                
 H.LOADING,                    
 ISNULL(L.RT_PO,1) * L.UM AS UM_P,                                           
 M.NM_ITEM,                                    
 M.STND_ITEM, 
 M.STND_DETAIL_ITEM,                                    
 M.STND_ITEM AS STND_MA_ITEM,                                  
 M.UNIT_IM,                                     
 ISNULL(M.UNIT_PO,1) UNIT_PO,                                              
 L.NO_PO,                                      
 L.NO_LINE, 
 CONVERT(VARCHAR,(SELECT COUNT(NO_LINE) FROM PU_POL WHERE CD_COMPANY = L.CD_COMPANY AND NO_PO = L.NO_PO)) + '건' AS ROWCNT,                                        
 L.CD_PLANT,                           
 L.NO_CONTRACT,                                      
 L.NO_CTLINE,                                                        
 L.NO_PR,                                      
 L.NO_PRLINE,                                      
 L.FG_TRANS,                                      
 L.CD_ITEM,                             
 L.CD_UNIT_MM,                                      
 L.FG_RCV,                                      
 L.FG_PURCHASE,                                                      
 L.DT_LIMIT,                                      
 L.QT_PO_MM,                                      
 L.QT_PO,                                       
 L.QT_REQ,                                      
 L.QT_RCV,                                      
 L.FG_TAX,                                      
 L.UM_EX_PO,                                      
 L.UM_EX,                                                    
 L.AM_EX,                                      
 L.UM,                                      
 L.AM,                                      
 L.VAT AS L_VAT,                                      
 L.CD_SL,                                        
 L.FG_POST,                                      
 L.YN_AUTORCV,                                      
 L.YN_RCV,                                                     
 L.YN_RETURN,                                      
 L.YN_ORDER,                                      
 L.YN_SUBCON,                                        
 L.YN_IMPORT,                                      
 L.RT_PO,                                      
 L.YN_REQ,                                      
 L.CD_PJT ,                                                     
 L.QT_REQ_MM,      
 L.QT_TR_MM,                                      
 L.QT_TR,                                      
 L.AM_EXTR,                                      
 L.AM_TR,                                      
 L.AM_EXREQ,                                      
 L.AM_REQ,          
 L.NO_APP,        
 L.NO_APPLINE,     
 L.QT_RCV_MM,                        
 CASE WHEN L.QT_REQ = 0 AND L.YN_ORDER ='Y' THEN  '001' ELSE L.FG_POCON  END AS FG_POCON,                                                   
 CASE WHEN LEN(L.CD_PJT) > 0 THEN ( SELECT TOP 1 PJ.NM_PROJECT FROM DZSN_SA_PROJECTH PJ WHERE PJ.CD_COMPANY = H.CD_COMPANY AND PJ.NO_PROJECT = L.CD_PJT ORDER BY NO_SEQ DESC )              ELSE '' END AS NM_PJT,                                                 
 CASE WHEN LEN(L.CD_PJT) > 0 THEN ( SELECT TOP 1 PJ.NM_PROJECT FROM DZSN_SA_PROJECTH PJ WHERE PJ.CD_COMPANY = H.CD_COMPANY AND PJ.NO_PROJECT = L.CD_PJT ORDER BY NO_SEQ DESC )              ELSE '' END AS NM_PJT_LIST,   
  
 SL.NM_SL,
 (SELECT Z.NM_SYSDEF FROM DZSN_MA_CODEDTL Z WHERE Z.CD_COMPANY = L.CD_COMPANY AND Z.CD_SYSDEF = L.FG_POST AND Z.CD_FIELD = 'PU_C000009' ) AS NM_SYSDEF,                                                    
 (SELECT P.NM_PLANT FROM DZSN_MA_PLANT P WHERE P.CD_COMPANY = L.CD_COMPANY AND P.CD_PLANT = L.CD_PLANT) AS NM_PLANT,              '' AS NO_RCV, 0.0 AS NO_RCVLINE,                                      
 '' AS YN_PURCHASE ,                                    
 '' AS  FG_TPPURCHASE,                                        
 0.0 AS QT_POC,                                      
 0.0 AS QT_REQC,                                    
 0.0 AS QT_INVC,                                    
 0.0 AS QT_ATPC,                                     
 L.DC1,                                     
 L.DC2,          
 L.DC3,
 L.DC4,                                 
 M.DT_VALID,                                     
 M.GRP_ITEM,                                     
 M.MAT_ITEM,               
 B1.NM_ITEMGRP,                                     
 ISNULL(C1.AM_ITEM_PU, 0) AM_ITEM_PU,                                           
 L.UMVAT_PO,                                     
 L.AMVAT_PO,                                     
 L.SEQ_PROJECT,                              
 PRH.CD_DEPT AS CD_DEPT_PR,                              
 (SELECT PA.NM_DEPT FROM DZSN_MA_DEPT PA WHERE PA.CD_DEPT = PRH.CD_DEPT AND PA.CD_COMPANY = PRH.CD_COMPANY) AS NM_DEPT_PR,                  
 ISNULL(MB.ADS_H,'') AS ADS_H_BIZ,                   
 ISNULL(MB.ADS_D,'') AS ADS_D_BIZ,                  
 MB.TP_JOB AS TP_JOB_BIZ,                  
 MB.CLS_JOB AS CLS_JOB_BIZ,                  
 P.TP_JOB AS TP_JOB_PT,                  
 P.CLS_JOB  AS CLS_JOB_PT,              
 G.EN_PURGRP,              
 M.MAT_ITEM,              
 PRL.CD_PURGRP AS CD_PURGRP_PR,               
 PRH_G.EN_PURGRP AS EN_PURGRP_PR ,              
 PRH_G.NM_PURGRP AS NM_PURGRP_PR,          
 M.NO_DESIGN,          
 M.URL_ITEM,          
 PRH_G.NO_TEL AS NO_TEL_PR,          
 PRH_G.NO_FAX AS NO_FAX_PR,      
  
 P.NO_COMPANY AS NO_COMPANY_PR,    
 C.NO_TEL,                                       
 C.NO_FAX,    
 L.GI_PARTNER,    
 P1.LN_PARTNER,    
  
 MB.NM_BIZAREA AS 사업장명,    
 SUBSTRING(MB.NO_BIZAREA,1,3) + '-' +  SUBSTRING(MB.NO_BIZAREA,4,2) + '-' + SUBSTRING(MB.NO_BIZAREA,6,5) AS 사업자등록번호,     
 MB.NM_MASTER AS 대표자,    
 MB.TP_JOB AS TP_JOB_BIZ,                  
 MB.CLS_JOB AS CLS_JOB_BIZ,                  
 MB.NO_TEL AS 전화,    
 MB.NO_FAX AS 팩스,    
 E.NM_KOR AS 담당자,    
 E.NM_ENG AS 담당자_영문,    
 ISNULL(MB.ADS_H,'') AS 주소,    
 ISNULL(MB.ADS_D,'') AS 상세주소,    
  
 P.LN_PARTNER AS 거래처명,    
 SUBSTRING(P.NO_COMPANY,1,3) + '-' +  SUBSTRING(P.NO_COMPANY,4,2) + '-' + SUBSTRING(P.NO_COMPANY,6,5) AS 사업자등록번호1,    
 P.NM_CEO AS 대표자1,    
 P.TP_JOB AS TP_JOB_PT,                  
 P.CLS_JOB  AS CLS_JOB_PT,     
 P.NO_TEL AS 전화1,    
 P.NO_FAX AS 팩스1,    
 P.NM_PTR AS 담당자1,    
 P.DC_ADS1_H AS 주소1,    
 P.DC_ADS1_D AS 상세주소1,    
 P.CD_EMP_PARTNER,    --거래처담당자    
  
 -- (20120925) 곽영진 추가  
 C.NO_FAX AS NO_FAX_CP, -- 회사FAX번호  
 P.NM_CURE_AGENCY,  -- 거래처 담당자  
 P.NO_TEL3,    -- 거래처 담당자 전화번호  
 P.NO_CUER_AGENCY,  -- 거래처 담당자 이메일  
   
 SSD.NM_CUST_DLV,    
 SSD.ADDR1 AS ADDR1_DLV,    
 SSD.NO_TEL_D2 AS NO_TEL_D2_DLV,    
 H.COND_PRICE_DLV,    
 H.CD_ARRIVER,    
 MC1.NM_SYSDEF AS NM_ARRIVER,    
 H.CD_LOADING,    
 MC2.NM_SYSDEF AS NM_LOADING,    
 MP1.CD_BIZAREA AS 공장귀속사업장코드,    
 MBP.NM_BIZAREA AS  공장귀속사업장명,    
 L.NO_PO + '-' +CONVERT(NVARCHAR, L.NO_LINE) AS 발주번호항번,    
 P.NO_HPEMP_PARTNER AS 거래처담당자핸드폰번호,    
  
 P.NM_PTR AS PARTNER_NM_PTR, -- 거래처 담당자    
 P.NO_TEL AS PARTNER_NO_TEL, --담당자 전화번호    
 P.NO_FAX AS PARTNER_NO_FAX, --거래처 FAX 번호    
 P.NO_HPEMP_PARTNER AS PARTNER_NO_HP, --거래처 담당자 H.P    
 P.E_MAIL AS PARTNER_E_MAIL, --거래처 담당자 E-mail    
 M.TP_ITEM AS PITEM_TP_ITEM, --품목타입    
 MC3.NM_SYSDEF AS PITEM_NM_TP_ITEM, --품목타입    
  
 MBP.NM_BIZAREA AS 사업장명1,    
 SUBSTRING(MBP.NO_BIZAREA,1,3) + '-' +  SUBSTRING(MBP.NO_BIZAREA,4,2) + '-' + SUBSTRING(MBP.NO_BIZAREA,6,5) AS 사업자등록번호1,     
 MBP.NO_TEL AS 전화1,    
 MBP.NO_FAX AS 팩스1,    
 MBP.ADS_H AS 주소1,    
 MBP.ADS_D AS 상세주소1,    
 MBP.NM_MASTER AS 대표자1,    
 MBP.NM_BIZ_RPT AS 사업장명D,    
 MBP.TP_JOB AS TP_JOB_BIZ1,                  
 MBP.CLS_JOB AS CLS_JOB_BIZ1,    
  
 --사원등록정보의 TEL    
 E.NO_TEL AS NO_TEL_EMP,    
 ME.NM_KOR AS NM_KOR_PJT,    
  
 P.DC_ADS1_H  +  P.DC_ADS1_D AS ADS1HD  ,    
 M.NO_MODEL  ,    
 H.DC_RMK_TEXT,    
 MC4.NM_SYSDEF AS NM_FG_PAYMENT, --지급조건한글		
 MC4.NM_SYSDEF_E AS NM_FG_PAYMENT_ENG, -- 지급조건영문		
 PRH.NO_EMP AS PRH_NO_EMP,  
 (SELECT NM_KOR FROM DZSN_MA_EMP WHERE NO_EMP = PRH.NO_EMP AND CD_COMPANY = PRH.CD_COMPANY) AS PRH_NM_EMP ,  
 PRL.CD_PJT PRL_PJT,  
 (SELECT NM_PROJECT FROM DZSN_SA_PROJECTH WHERE CD_COMPANY = PRL.CD_COMPANY AND NO_PROJECT= PRL.CD_PJT ) AS PRL_NM_PROJECT ,  
  
 E.CD_DUTY_STEP,  
 MC5.NM_SYSDEF AS NM_DUTY_STEP,  
 E.NO_TEL_EMER,  
 E.NO_EMAIL,  
 H.COND_DAYS,  
 M.NM_MAKER,       --2011.06.22 이장원  
 H.COND_PAY_DLV,  
 H.COND_PRICE_DLV,  
 C3.NM_SYSDEF AS TP_TRANSPORT ,-- 별칭 운송조건  
 C4.NM_SYSDEF AS COND_PAY,     -- 별칭 지불조건명  
 C5.NM_SYSDEF AS COND_PRICE,   -- 별칭 가격조건명  
 L.DT_PLAN,  
 E.NO_TEL     AS EMP_NO_TEL,   --담당자전화번호  
 G.NO_TEL	  AS PURGRP_NO_TEL, --구매그룹전화번호  
 G.NO_FAX	  AS PURGRP_NO_FAX,  --구매그룹팩스번호  
  
 P.NO_DEPOSIT, --계좌번호  
 P.CD_BANK,  
 C7.NM_SYSDEF AS NM_CD_BANK, --은행명  
 P.NM_DEPOSIT, --예금주명  
 C6.NM_SYSDEF AS NM_CLS_ITEM, -- 계정구분  
 L.AM + L.VAT AS HAP_L,  
 C.NM_ENG,  
 C.NM_CEO,  
 MB.DC_ADS_ENG,  
 M.STND_DETAIL_ITEM,    
 MU.NO_TEL AS EMP_NO_TEL1,  
 MU.EMAIL AS EMAIL_USER,  
 PRH.FG_PR_TP,  
 C8.NM_SYSDEF AS NM_FG_PR_TP,  
 M.NO_HS,  
 H.NM_PACKING,  
 SUP.DC_ADS1_H AS SUPP_ADS1_H,  
 SUP.DC_ADS1_D AS SUPP_ADS1_D,  
 M.EN_ITEM AS M_EN_ITEM,  
 M.NM_USERDEF1 AS M_NM_USERDEF1,  
 M.NM_USERDEF3 AS M_NM_USERDEF3,  
 M.NM_USERDEF4 AS M_NM_USERDEF4,  
 M.NM_USERDEF5 AS M_NM_USERDEF5,  
 M.NUM_USERDEF8 AS M_NUM_USERDEF8,  
   
 ---부가정보적용 ---  
 PS.DT_USERDEF1 AS   SUB_DT_USERDEF1,  
 PS.DT_USERDEF2 AS   SUB_DT_USERDEF2,  
 PS.DT_USERDEF3 AS   SUB_DT_USERDEF3,  
 PS.DT_USERDEF4 AS   SUB_DT_USERDEF4,  
   
 PS.CD_USERDEF1 AS   SUB_CD_USERDEF1,  
 PS.CD_USERDEF2 AS   SUB_CD_USERDEF2,  
 PS.CD_USERDEF3 AS   SUB_CD_USERDEF3,  
 PS.CD_USERDEF4 AS   SUB_CD_USERDEF4,  
 PS.CD_USERDEF5 AS   SUB_CD_USERDEF5,  
 PS.CD_USERDEF6 AS   SUB_CD_USERDEF6,  
 PS.CD_USERDEF7 AS   SUB_CD_USERDEF7,  
 PS.CD_USERDEF8 AS   SUB_CD_USERDEF8,  
 PS.CD_USERDEF9 AS   SUB_CD_USERDEF9,  
 PS.CD_USERDEF10 AS  SUB_CD_USERDEF10,  
   
 SM1.NM_SYSDEF  AS   SUB_NM_COM_USERDEF1,  
 SM2.NM_SYSDEF AS   SUB_NM_COM_USERDEF2,  
 SM3.NM_SYSDEF AS   SUB_NM_COM_USERDEF3,  
 SM4.NM_SYSDEF AS   SUB_NM_COM_USERDEF4,  
 SM5.NM_SYSDEF AS   SUB_NM_COM_USERDEF5,  
 SM6.NM_SYSDEF AS   SUB_NM_COM_USERDEF6,  
 SM7.NM_SYSDEF AS   SUB_NM_COM_USERDEF7,  
 SM8.NM_SYSDEF AS   SUB_NM_COM_USERDEF8,  
 SM9.NM_SYSDEF AS   SUB_NM_COM_USERDEF9,  
 SM10.NM_SYSDEF AS   SUB_NM_COM_USERDEF10,  
   
   
 PS.NUM_USERDEF1 AS  SUB_NUM_USERDEF1,  
 PS.NUM_USERDEF2 AS  SUB_NUM_USERDEF2,  
 PS.NUM_USERDEF3 AS  SUB_NUM_USERDEF3,  
 PS.NUM_USERDEF4 AS  SUB_NUM_USERDEF4,  
 PS.NUM_USERDEF5 AS  SUB_NUM_USERDEF5,  
 PS.NUM_USERDEF6 AS  SUB_NUM_USERDEF6,  
 PS.NM_USERDEF1 AS   SUB_NM_USERDEF1,  
 PS.NM_USERDEF2 AS   SUB_NM_USERDEF2,  
 PS.NM_USERDEF3 AS   SUB_NM_USERDEF3,  
 PS.NM_USERDEF4 AS   SUB_NM_USERDEF4,  
 PS.NM_USERDEF5 AS   SUB_NM_USERDEF5,  
 PS.NM_USERDEF6 AS   SUB_NM_USERDEF6,  
 PS.NM_USERDEF7 AS SUB_NM_USERDEF7,
 PS.NM_USERDEF8 AS SUB_NM_USERDEF8,
 PS.NM_USERDEF9 AS SUB_NM_USERDEF9,
 PS.NM_USERDEF10 AS SUB_NM_USERDEF10,
 PS.NM_USERDEF11 AS SUB_NM_USERDEF11,
 PS.NM_USERDEF12 AS SUB_NM_USERDEF12,
 PS.NM_USERDEF13 AS SUB_NM_USERDEF13,
 PS.NM_USERDEF14 AS SUB_NM_USERDEF14,
 PS.NM_USERDEF15 AS SUB_NM_USERDEF15,
 PS.NM_USERDEF16 AS SUB_NM_USERDEF16,
  
 ---부가정보적용 ---  
 L.CD_ITEM_ORIGIN,  
 ORIGIN.NM_ITEM AS NM_ITEM_ORIGIN,  
 ME10.NM_KOR + ' / ' + MD10.NM_DEPT AS PR_NM_EMP,     -- 발주서출력에서 구매요청등록의 요청자와 부서를 출력하기 위해 추가 : 2013.02.04    
 WW.DT_LIMIT                        AS PR_DT_LIMIT,   -- 발주서출력에서 발주일자 여러 건이 있는 경우 한건만 출력하기 위해 추가 : 2013.02.04   
   (SELECT MAX(NO_TEL) FROM DZSN_MA_USER WHERE CD_COMPANY = @CD_COMPANY AND NO_EMP = H.NO_EMP) AS NO_TEL_USER,  
   (SELECT MAX(EMAIL) FROM DZSN_MA_USER WHERE CD_COMPANY = @CD_COMPANY AND NO_EMP = H.NO_EMP) AS E_MAIL_USER,  
   P.DC_ADS2_D,  
   P.NO_TEL2,  
   P.NO_FAX2,  
   M.FG_MODEL,  
   APPL.UM_PRE,  
   (ISNULL(L.QT_PO_MM,0) * ISNULL(APPL.UM_PRE,0)) AS AM_PRE,  
  CASE WHEN LEN(L.CD_PJT) > 0 THEN ( SELECT TOP 1 PJ.NM_PROJECT FROM DZSN_SA_PROJECTH PJ WHERE PJ.CD_COMPANY = H.CD_COMPANY AND PJ.NO_PROJECT = L.CD_PJT ORDER BY NO_SEQ DESC )  ELSE '' END AS NM_PJT_LINE,    
  B.NO_TEL AS NO_TEL_ORG,  --  구매조직 전화번호  
  B.NO_FAX AS NO_FAX_ORG,  --  구매조직 FAX  
  B.E_MAIL AS E_MAIL_ORG,  -- 구매조직 E-MAIL  
  CASE WHEN C6.CD_FLAG1 = 'Y' THEN L.QT_PO ELSE 0 END AS QT_PO_RP, -- 수불수량  
  M.NM_MAKER,  
  PAR.NM_EMAIL AS PARF_NM_EMAIL, PAR.NM_PTR AS PARF_NM_PTR, PAR.NO_FAX AS PARF_NO_FAX, PAR.NO_HP AS PARF_NO_HP, PAR.NO_TEL AS PARF_NO_TEL, ---거래처담당자테이블에있는내용  
  MB.EN_BIZAREA,  
  L.AM_REBATE,  
  L.AM_REBATE_EX,  
  M.CD_USERDEF1 AS CD_USERDEF1_ITEM,  
  SM11.NM_SYSDEF AS NM_USERDEF1_ITEM,   
  CASE WHEN LEN(L.CD_PJT) > 0 THEN ( SELECT TOP 1 RIGHT(PJ.NM_PROJECT,4) FROM DZSN_SA_PROJECTH PJ WHERE PJ.CD_COMPANY = H.CD_COMPANY AND PJ.NO_PROJECT = L.CD_PJT ORDER BY NO_SEQ DESC )  ELSE '' END AS NM_PJT_ICD ,  
  SPL.CD_ITEM AS CD_PJT_ITEM, --프로젝트 품목코드  
  I2.NM_ITEM AS NM_PJT_ITEM, --프로젝트 품목명  
  I2.STND_ITEM AS PJT_ITEM_STND, --프로젝트 품목 규격   
  P.NO_TEL3,  
  P.NO_FAX3,  
  P.NM_CURE_AGENCY,  
  P.NO_CUER_AGENCY,  
  L.NM_USERDEF1,  
  L.NM_USERDEF2,
  M.DC_RMK,                        -- 2013.07.22 품목 마스터 비고정보 추가(윤성우)
  H.TP_PACKING,                        --2013.07.23 포장형태명 컬럼 추가(윤나라)
  MC6.NM_SYSDEF AS NM_TP_PACKING,    --2013.07.23 포장형태명 컬럼 추가(윤나라)
  (SELECT NM_SYSDEF FROM DZSN_MA_CODEDTL MC7 WHERE MC7.CD_COMPANY = L.CD_COMPANY AND MC7.CD_FIELD ='PU_C000076' AND MC7.CD_SYSDEF = L.FG_PACKING) AS NM_FG_PACKING,
  P.EN_PARTNER,
  L.TOT_WEIGHT,
  -- 오라클을 추후에 필요할때 추가하겠음..
  H.DELIVERY_TERMS,
  H.DELIVERY_TIME,
  H.VALIDITY,
  H.INSPECTION,
  H.DOCUMENT_REQUIRED,
  M.EN_ITEM,
  G.CD_CC,
  CC.NM_CC,
  PJD.NM_COST, --인터벡스전용
  PRH.DT_PR,    --현대위아IHI터보 요청일자
  '*'+H.NO_PO+'*' AS NO_PO_BARCODE, -- 바코드 (오라클은 필요할때 컨버전하겠음)
  L.CD_USERDEF1 AS CD_USERDEF1_PO,
  L.CD_USERDEF2	AS CD_USERDEF2_PO,
  L.NM_USERDEF1	AS NM_USERDEF1_PO,
  L.NM_USERDEF2	AS NM_USERDEF2_PO,
  L.DATE_USERDEF1	AS DATE_USERDEF1_PO,L.DATE_USERDEF2	AS DATE_USERDEF2_PO,
  M.BARCODE AS ITEM_BARCODE,
  --산성앨엔에스 (오라클은 필요할때 컨버전하겠음) 
  (SELECT MS.NM_SYSDEF FROM DZSN_MA_CODEDTL MS WHERE MS.CD_COMPANY = E.CD_COMPANY AND MS.CD_FIELD='HR_H000002' AND MS.CD_SYSDEF = E.CD_DUTY_RANK ) AS NM_DUTY_RANK,
  L.CD_CC AS CD_CC_LINE, CC_LINE.NM_CC AS NM_CC_LINE,
  L.CD_USERDEF3 AS CD_USERDEF3_PO, L.NUM_USERDEF1 AS NUM_USERDEF1_PO,
  M.CD_USERDEF3 AS CD_USERDEF3_ITEM, --다이킨코리아(주) 포장단위
  M.NUM_USERDEF1 AS NUM_USERDEF1_ITEM, --다이킨코리아(주) 내용량
  AG.LN_PARTNER AS LN_PARTNER_AGENCY, --다이킨코리아(주) 배송처
  AG.DC_ADS1_H AS DC_ADS1_H_AGENCY, --다이킨코리아(주) 배송처주소
  AG.DC_ADS1_D AS DC_ADS1_D_AGENCY, --다이킨코리아(주) 배송처주소(상세)
  AG.EN_PARTNER,
  AG.DC_ADS2_H,
  AG.DC_ADS2_D,
  CASE WHEN ISNULL(M.NUM_USERDEF1,0) = 0 THEN 0 ELSE ROUND(L.QT_PO_MM / M.NUM_USERDEF1,4,4) END PCS, --다이킨코리아(주) PCS
  PRL.CD_USERDEF2	AS CD_USERDEF2_PR,
  --대명ENG 전용
  DMENG.NM_BIZAREA AS NM_BIZAREA_DM,
  DMENG.NO_BIZAREA AS NO_BIZAREA_DM,
  DMENG.NO_TEL AS NO_TEL_DM,
  DMENG.NO_MOBILE AS NO_MOBILE_DM,
  DMENG.ADS_NO AS ADS_NO_DM,
  DMENG.ADS_H AS ADS_H_DM,
  DMENG.ADS_D AS ADS_D_DM,
  DMENG.NO_FAX AS NO_FAX_DM,
  DMENG.TP_JOB AS TP_JOB_DM,
  DMENG.CLS_JOB AS CLS_JOB_DM,
  -- 호식이전용
  CASE WHEN PTR.NM_PTR IS NULL THEN P1.NM_CEO  ELSE PTR.NM_PTR END GI_NM_PTR,
  CASE WHEN PTR.NM_PTR IS NULL THEN P1.NO_TEL1 ELSE PTR.NO_TEL END GI_NO_TEL,
  ISNULL(P1.DC_ADS1_H,'') +' '+ ISNULL(P1.DC_ADS1_D,'') GI_DC_ADS1,
  L.TXT_USERDEF1,
  L.TXT_USERDEF2,
  -- 삼원산업요청 2016.06.01 김동우
  SM12.NM_SYSDEF AS NM_USERDEF2_ITEM, 
  SM13.NM_SYSDEF AS NM_USERDEF3_ITEM, 
  SM14.NM_SYSDEF AS NM_USERDEF4_ITEM, 
  SM15.NM_SYSDEF AS NM_USERDEF5_ITEM, 
  SM16.NM_SYSDEF AS NM_USERDEF6_ITEM, 
  SM17.NM_SYSDEF AS NM_USERDEF7_ITEM, 
  SM18.NM_SYSDEF AS NM_USERDEF8_ITEM, 
  SM19.NM_SYSDEF AS NM_USERDEF9_ITEM, 
  SM20.NM_SYSDEF AS NM_USERDEF10_ITEM,
  E.DC_RMK AS EMP_DC_RMK,
  CLS_L.NM_SYSDEF AS CLS_L, CLS_M.NM_SYSDEF AS CLS_M, CLS_S.NM_SYSDEF AS CLS_S ,
  ITEMGRP.NM_SYSDEF AS NM_GRP_MFG, ITMEPT.LN_PARTNER AS ITEM_PARTNER,
  (SELECT TOP 1 CD_ITEM_PARTNER 
   FROM DZSN_PU_CUSTITEM WHERE CD_COMPANY = L.CD_COMPANY AND CD_ITEM = L.CD_ITEM AND CD_PLANT = L.CD_PLANT AND CD_PARTNER = H.CD_PARTNER) CD_ITEM_PARTNER,
  (SELECT TOP 1 NM_ITEM_PARTNER 
   FROM DZSN_PU_CUSTITEM WHERE CD_COMPANY = L.CD_COMPANY AND CD_ITEM = L.CD_ITEM AND CD_PLANT = L.CD_PLANT AND CD_PARTNER = H.CD_PARTNER) NM_ITEM_PARTNER,
  (SELECT TOP 1 STND_ITEM 
   FROM DZSN_PU_CUSTITEM WHERE CD_COMPANY = L.CD_COMPANY AND CD_ITEM = L.CD_ITEM AND CD_PLANT = L.CD_PLANT AND CD_PARTNER = H.CD_PARTNER) STND_ITEM_PARTNER,
  GW.APP_DT_END,
  ISNULL(P1.DC_ADS2_H,'') + ISNULL(P1.DC_ADS2_D, '') AS ADS2_GI_PARTNER,
  P1.NO_POST2 AS NO_POST2_GI_PARTNER,
  -- 우양냉동 전용
  (SELECT TOP 1 UNIT_IM_PARTNER 
   FROM DZSN_PU_CUSTITEM WHERE CD_COMPANY = L.CD_COMPANY AND CD_ITEM = L.CD_ITEM AND CD_PLANT = L.CD_PLANT AND CD_PARTNER = H.CD_PARTNER) UNIT_IM_PARTNER,
     -- 재원푸드
  P1.NM_PTR AS PTR_GI_PARTNER,
  P1.NO_TEL2 AS TEL_GI_PARTNER,
  SP.CD_PARTNER AS CD_PJT_PARTNER,
  (SELECT LN_PARTNER FROM DZSN_MA_PARTNER WHERE CD_COMPANY = SP.CD_COMPANY AND CD_PARTNER = SP.CD_PARTNER) AS LN_PJT_PARTNER,
  SOL.NO_PO_PARTNER,
  L.NO_SO, L.DC50_PO DC50_PO_POL, L.NM_USERDEF3 NM_USERDEF3_PO, L.NM_USERDEF4 NM_USERDEF4_PO, L.NM_USERDEF5 NM_USERDEF5_PO, 
  P1.LN_PARTNER_L1 AS LN_PARTNER_L1_GI, 
  SOHP.LN_PARTNER AS LN_PARTNER_SO,
  SOHP.LN_PARTNER_L1 AS  LN_PARTNER_L1_SO,
  CASE WHEN H.CD_EXCH = '000' THEN 0 ELSE L.AM_EX END AM_EX_DMT,
  SM21.NM_SYSDEF AS NM_USERDEF11_ITEM,
  MU.DC_RMK1 AS USER_DC_RMK1, MU.DC_RMK2 AS USER_DC_RMK2, MU.DC_RMK3 AS USER_DC_RMK3, MU.DC_RMK4 AS USER_DC_RMK4, MU.DC_RMK5 AS USER_DC_RMK5,
  H.DC_RMK_TEXT2,
  PJTD.TXT_USERDEF1 AS TXT_USERDEF1_PJTL,
  PJTD.TXT_USERDEF2 AS TXT_USERDEF2_PJTL,
  APPL.UM_EX_PO AS UM_EX_PO_APP,
  APPL.RT_CUT,
  PRL.CD_REASON,
  REASON.NM_SYSDEF AS NM_REASON,
  CASE WHEN M.UNIT_PO = 'G' THEN ISNULL(L.QT_PO_MM, 0) * 0.001 ELSE L.QT_PO_MM END AS QT_PO_CHG,
  MC8.NM_SYSDEF AS NM_UNIT_IM,
  L.NO_CBS,
  PJC.DL_CSTR,
  PJC.NM_CSTR,
  M.WEIGHT,
  ISNULL(H.NO_HST, 0) AS NO_HST,
  --에이비엘바이오 전용
  APPL.TXT_USERDEF1 AS TXT_USERDEF1_APP,
  APPL.TXT_USERDEF2 AS TXT_USERDEF2_APP,
  EMPA.NM_KOR AS NM_KOR_APP,
  EMPA.NO_EMAIL AS NO_EMAIL_APP,
  (SELECT NM_ITEM FROM DZSN_MA_ITEM ITEM WHERE L.CD_ITEM = ITEM.CD_ITEM AND L.CD_COMPANY = ITEM.CD_COMPANY ) NM_ITEM_COM,
  M05.NM_SYSDEF AS NM_TAX,
  SL.DC_100,
  (SELECT NO_TEL_EMER FROM DZSN_MA_EMP EMP WHERE EMP.CD_COMPANY = PRH.CD_COMPANY AND PRH.NO_EMP = EMP.NO_EMP ) AS PRH_NO_TEL_EMER,
  SL_PT.LN_PARTNER AS LN_PARTNER_SL,
  SL_PT.DC_ADS1_H AS DC_ADS1_H_SL,
  SL_PT.DC_ADS1_D AS DC_ADS1_D_SL,
  SL_PT.NO_TEL1 AS NO_TEL1_SL,
  SL_PT.NO_FAX1 AS NO_FAX1_SL,
  SL_PT.CD_EMP_PARTNER AS CD_EMP_PARTNER_SL,
  SL_PT.NO_HPEMP_PARTNER AS NO_HPEMP_PARTNER_SL,
  MP1.ADS_H AS ADS_H_PLANT, MP1.ADS_D AS ADS_D_PLANT,
  C5.NM_SYSDEF_E AS COND_PRICE_EN

FROM PU_POH H INNER JOIN  PU_POL L ON    H.NO_PO = L.NO_PO AND   H.CD_COMPANY = L.CD_COMPANY                 
 LEFT OUTER JOIN  DZSN_MA_PURGRP G  ON   H.CD_COMPANY = G.CD_COMPANY  AND H.CD_PURGRP = G.CD_PURGRP                                                      
 LEFT OUTER JOIN  DZSN_MA_PURORG B  ON    G.CD_COMPANY = B.CD_COMPANY  AND   G.CD_PURORG = B.CD_PURORG         
 INNER JOIN  DZSN_PU_TPPO T  ON    H.CD_COMPANY = T.CD_COMPANY  AND   H.CD_TPPO = T.CD_TPPO                                                       
 LEFT OUTER JOIN DZSN_MA_EMP E ON E.CD_COMPANY = H.CD_COMPANY AND   E.NO_EMP = H.NO_EMP                       
 INNER JOIN DZSN_MA_COMPANY C ON H.CD_COMPANY =   C.CD_COMPANY                                              
 INNER JOIN DZSN_MA_PARTNER P ON H.CD_PARTNER = P.CD_PARTNER AND   H.CD_COMPANY = P.CD_COMPANY                                                 
 LEFT OUTER JOIN DZSN_MA_BIZAREA MB ON E.CD_BIZAREA = MB.CD_BIZAREA AND E.CD_COMPANY = MB.CD_COMPANY                                        
 LEFT OUTER JOIN DZSN_MA_PITEM M ON    L.CD_COMPANY = M.CD_COMPANY AND   L.CD_ITEM = M.CD_ITEM AND   L.CD_PLANT = M.CD_PLANT                                                
 LEFT OUTER JOIN DZSN_MA_ITEMGRP B1 ON B1.CD_COMPANY = H.CD_COMPANY AND B1.CD_ITEMGRP = M.GRP_ITEM                                   
 LEFT OUTER JOIN MA_GRPITEM_UM_HDS C1 ON C1.CD_COMPANY = H.CD_COMPANY AND C1.CD_PLANT = L.CD_PLANT AND C1.GRP_ITEM = M.GRP_ITEM AND C1.FG_UM = H.FG_UM                                        
 LEFT OUTER JOIN PU_PRH PRH ON L.NO_PR = PRH.NO_PR AND L.CD_PLANT = PRH.CD_PLANT AND L.CD_COMPANY = PRH.CD_COMPANY                              
 LEFT OUTER JOIN PU_PRL PRL ON L.NO_PR = PRL.NO_PR  AND L.NO_PRLINE = PRL.NO_PRLINE AND L.CD_COMPANY = PRL.CD_COMPANY                              
 LEFT OUTER JOIN PU_APPL APPL ON APPL.NO_APP = L.NO_APP AND APPL.NO_APPLINE = L.NO_APPLINE AND APPL.CD_COMPANY = L.CD_COMPANY  
 LEFT OUTER JOIN PU_APPH APPH ON APPH.NO_APP = APPL.NO_APP AND APPH.CD_COMPANY = APPL.CD_COMPANY
 LEFT OUTER JOIN DZSN_MA_EMP EMPA ON EMPA.NO_EMP = APPH.EMP_WRITE AND EMPA.CD_COMPANY = APPH.CD_COMPANY
 LEFT OUTER JOIN DZSN_MA_PURGRP PRH_G  ON PRL.CD_COMPANY = PRH_G.CD_COMPANY  AND   PRL.CD_PURGRP = PRH_G.CD_PURGRP                                                                        
 LEFT OUTER JOIN DZSN_MA_PARTNER P1 ON P1.CD_COMPANY = L.CD_COMPANY AND P1.CD_PARTNER = L.GI_PARTNER    
 LEFT OUTER JOIN DZSN_SA_SOL_DLV SSD ON L.CD_COMPANY = SSD.CD_COMPANY AND L.CD_PJT = SSD.NO_SO AND L.SEQ_PROJECT = SSD.SEQ_SO AND SSD.FG_TRACK = 'SO'   
 LEFT OUTER JOIN DZSN_MA_CODEDTL MC1 ON MC1.CD_COMPANY = H.CD_COMPANY AND MC1.CD_SYSDEF = H.CD_ARRIVER AND MC1.CD_FIELD = 'PU_C000046'    
 LEFT OUTER JOIN DZSN_MA_CODEDTL MC2 ON MC2.CD_COMPANY = H.CD_COMPANY AND MC2.CD_SYSDEF = H.CD_LOADING AND MC2.CD_FIELD = 'PU_C000047'              
 LEFT OUTER JOIN DZSN_MA_PLANT MP1 ON MP1.CD_COMPANY = H.CD_COMPANY AND MP1.CD_PLANT = H.CD_PLANT    
 LEFT OUTER JOIN DZSN_MA_BIZAREA MBP ON MP1.CD_BIZAREA = MBP.CD_BIZAREA AND MP1.CD_COMPANY = MBP.CD_COMPANY     
 LEFT OUTER JOIN DZSN_MA_CODEDTL MC3 ON MC3.CD_COMPANY = M.CD_COMPANY AND MC3.CD_SYSDEF = M.TP_ITEM AND MC3.CD_FIELD = 'MA_B000011'               
 LEFT OUTER JOIN DZSN_SA_PROJECTH SP ON L.CD_COMPANY = SP.CD_COMPANY AND L.CD_PJT = SP.NO_PROJECT    
 LEFT OUTER JOIN DZSN_MA_EMP ME ON SP.CD_COMPANY = ME.CD_COMPANY AND SP.NO_EMP = ME.NO_EMP    
 LEFT OUTER JOIN DZSN_MA_CODEDTL MC4 ON MC4.CD_COMPANY = H.CD_COMPANY AND MC4.CD_SYSDEF = H.FG_PAYMENT AND MC4.CD_FIELD = 'PU_C000014'
 LEFT OUTER JOIN DZSN_MA_CODEDTL MC5 ON MC5.CD_COMPANY = H.CD_COMPANY AND MC5.CD_SYSDEF = H.FG_PAYMENT AND MC5.CD_FIELD = 'HR_H000003'
                                 --2011.06.22 이장원   
 LEFT OUTER JOIN DZSN_MA_CODEDTL C3 ON C3.CD_COMPANY =  H.CD_COMPANY AND C3.CD_SYSDEF = H.TP_TRANSPORT AND C3.CD_FIELD = 'TR_IM00008'   
 LEFT OUTER JOIN DZSN_MA_CODEDTL C4 ON C4.CD_COMPANY =  H.CD_COMPANY AND C4.CD_SYSDEF = H.COND_PAY  AND C4.CD_FIELD = 'TR_IM00004'  
 LEFT OUTER JOIN DZSN_MA_CODEDTL C5 ON C5.CD_COMPANY =  H.CD_COMPANY AND C5.CD_SYSDEF = H.COND_PRICE AND C5.CD_FIELD = 'TR_IM00002'  
 LEFT OUTER JOIN DZSN_MA_CODEDTL C6 ON C6.CD_COMPANY =  H.CD_COMPANY AND C6.CD_SYSDEF = M.CLS_ITEM AND C6.CD_FIELD = 'MA_B000010'  
 LEFT OUTER JOIN DZSN_MA_CODEDTL C7 ON C7.CD_COMPANY =  H.CD_COMPANY AND C7.CD_SYSDEF = P.CD_BANK AND C7.CD_FIELD = 'MA_B000043'  
 LEFT OUTER JOIN DZSN_MA_USER MU ON MU.NO_EMP = H.NO_EMP  AND MU.ID_USER= @P_USER_ID AND MU.CD_COMPANY = H.CD_COMPANY     
 LEFT OUTER JOIN DZSN_MA_CODEDTL C8 ON C8.CD_COMPANY = PRH.CD_COMPANY AND C8.CD_SYSDEF = PRH.FG_PR_TP AND C8.CD_FIELD = 'PU_C000007'  
 LEFT OUTER JOIN DZSN_MA_PARTNER MAN ON MAN.CD_PARTNER = H.MANUFACTURER AND MAN.CD_COMPANY = H.CD_COMPANY  
 LEFT OUTER JOIN DZSN_MA_PARTNER SUP ON SUP.CD_PARTNER = H.SUPPLIER AND SUP.CD_COMPANY = H.CD_COMPANY  
 LEFT OUTER JOIN PU_SUBINFO PS ON PS.CD_COMPANY = H.CD_COMPANY AND PS.NO_PK = H.NO_PO AND CD_MENU = '102' -- 102: PU_POH  
   
 LEFT OUTER JOIN DZSN_MA_CODEDTL SM1 ON SM1.CD_COMPANY = PS.CD_COMPANY AND SM1.CD_SYSDEF = PS.CD_USERDEF1 AND SM1.CD_FIELD = 'PU_C000052'  
 LEFT OUTER JOIN DZSN_MA_CODEDTL SM2 ON SM2.CD_COMPANY = PS.CD_COMPANY AND SM2.CD_SYSDEF = PS.CD_USERDEF2 AND SM2.CD_FIELD = 'PU_C000053'  
 LEFT OUTER JOIN DZSN_MA_CODEDTL SM3 ON SM3.CD_COMPANY = PS.CD_COMPANY AND SM3.CD_SYSDEF = PS.CD_USERDEF3 AND SM3.CD_FIELD = 'PU_C000054'  
 LEFT OUTER JOIN DZSN_MA_CODEDTL SM4 ON SM4.CD_COMPANY = PS.CD_COMPANY AND SM4.CD_SYSDEF = PS.CD_USERDEF4 AND SM4.CD_FIELD = 'PU_C000055'  
 LEFT OUTER JOIN DZSN_MA_CODEDTL SM5 ON SM5.CD_COMPANY = PS.CD_COMPANY AND SM5.CD_SYSDEF = PS.CD_USERDEF5 AND SM5.CD_FIELD = 'PU_C000056'  
 LEFT OUTER JOIN DZSN_MA_CODEDTL SM6 ON SM6.CD_COMPANY = PS.CD_COMPANY AND SM6.CD_SYSDEF = PS.CD_USERDEF6 AND SM6.CD_FIELD = 'PU_C000057'  
 LEFT OUTER JOIN DZSN_MA_CODEDTL SM7 ON SM7.CD_COMPANY = PS.CD_COMPANY AND SM7.CD_SYSDEF = PS.CD_USERDEF7 AND SM7.CD_FIELD = 'PU_C000071'  
 LEFT OUTER JOIN DZSN_MA_CODEDTL SM8 ON SM8.CD_COMPANY = PS.CD_COMPANY AND SM8.CD_SYSDEF = PS.CD_USERDEF8 AND SM8.CD_FIELD = 'PU_C000072'  
 LEFT OUTER JOIN DZSN_MA_CODEDTL SM9 ON SM9.CD_COMPANY = PS.CD_COMPANY AND SM9.CD_SYSDEF = PS.CD_USERDEF9 AND SM9.CD_FIELD = 'PU_C000073'  
 LEFT OUTER JOIN DZSN_MA_CODEDTL SM10 ON SM10.CD_COMPANY = PS.CD_COMPANY AND SM10.CD_SYSDEF = PS.CD_USERDEF10 AND SM10.CD_FIELD = 'PU_C000074'  
 LEFT OUTER JOIN DZSN_MA_PITEM ORIGIN ON ORIGIN.CD_ITEM = L.CD_ITEM_ORIGIN AND ORIGIN.CD_PLANT = L.CD_PLANT AND ORIGIN.CD_COMPANY = L.CD_COMPANY  
 LEFT OUTER JOIN   
    (  
     SELECT TOP 1 P.CD_PARTNER, P.NM_EMAIL, P.NM_PTR, P.NO_FAX, P.NO_HP, P.NO_TEL, P.CD_COMPANY  
       FROM PU_POH H  
       INNER JOIN FI_PARTNERPTR P ON P.CD_PARTNER = H.CD_PARTNER AND P.CD_COMPANY = H.CD_COMPANY  
       WHERE H.CD_COMPANY = @CD_COMPANY  
         AND H.NO_PO = @NO_PO  
         AND P.CLIENT_NOTE LIKE '%구매%'  
    )PAR ON PAR.CD_PARTNER = H.CD_PARTNER AND PAR.CD_COMPANY = H.CD_COMPANY   
 LEFT OUTER JOIN DZSN_MA_CODEDTL SM11 ON SM11.CD_FIELD ='MA_B000081' AND SM11.CD_SYSDEF = M.CD_USERDEF1 AND SM11.CD_COMPANY = M.CD_COMPANY  
 LEFT OUTER JOIN SA_PROJECTL SPL ON L.CD_COMPANY = SPL.CD_COMPANY AND L.CD_PJT = SPL.NO_PROJECT AND L.SEQ_PROJECT = SPL.SEQ_PROJECT  
 LEFT OUTER JOIN DZSN_MA_PITEM I2 ON SPL.CD_COMPANY = I2.CD_COMPANY AND SPL.CD_PLANT = I2.CD_PLANT AND SPL.CD_ITEM = I2.CD_ITEM 
 LEFT OUTER JOIN ( SELECT Z.NO_EMP    
                        , Z.CD_DEPT    
                        , Y.NO_PR    
                        , Y.CD_COMPANY    
                        , Y.NO_PO   
                        , Y.DT_LIMIT   
                     FROM PU_PRH Z    
                     INNER JOIN ( SELECT A.NO_PO    
                                       , MIN(B.NO_PR) AS NO_PR    
                                       , A.CD_COMPANY    
                                       , MIN(B.DT_LIMIT) AS DT_LIMIT
                                    FROM PU_POH A    
                                    INNER JOIN PU_POL B ON A.CD_COMPANY = B.CD_COMPANY AND A.NO_PO = B.NO_PO    
                                   WHERE A.CD_COMPANY = @CD_COMPANY    
                                     AND A.NO_PO = @NO_PO    
                                GROUP BY A.NO_PO    
                                       , A.CD_COMPANY  ) Y ON Y.CD_COMPANY = Z.CD_COMPANY AND Y.NO_PR = Z.NO_PR ) WW 
   ON WW.CD_COMPANY = H.CD_COMPANY AND WW.NO_PO = H.NO_PO           
 LEFT OUTER JOIN DZSN_MA_EMP ME10 ON WW.NO_EMP = ME10.NO_EMP AND WW.CD_COMPANY = ME10.CD_COMPANY    
 LEFT OUTER JOIN DZSN_MA_DEPT MD10 ON WW.CD_DEPT = MD10.CD_DEPT AND WW.CD_COMPANY = MD10.CD_COMPANY
 LEFT OUTER JOIN DZSN_MA_CODEDTL MC6 ON MC6.CD_FIELD = 'TR_IM00011' AND MC6.CD_SYSDEF = H.TP_PACKING AND MC6.CD_COMPANY = H.CD_COMPANY    --2013.07.23    포장형태명 컬럼 추가(윤나라)   
 LEFT OUTER JOIN DZSN_MA_CC CC ON CC.CD_CC = G.CD_CC AND CC.CD_COMPANY = G.CD_COMPANY
 LEFT OUTER JOIN DZSN_MA_CC CC_LINE ON L.CD_CC = CC_LINE.CD_CC AND L.CD_COMPANY = CC_LINE.CD_COMPANY
 LEFT OUTER JOIN PJ_CBS PJC ON L.CD_COMPANY = PJC.CD_COMPANY AND L.CD_PJT = PJC.NO_PROJECT AND L.NO_CBS = PJC.NO_CBS
 LEFT OUTER JOIN PJ_CBSCODE PJD ON L.CD_COMPANY = PJD.CD_COMPANY AND PJC.CD_COST = PJD.CD_COST
 LEFT OUTER JOIN DZSN_MA_DEPT MD11 ON MD11.CD_COMPANY = E.CD_COMPANY AND MD11.CD_DEPT = E.CD_DEPT
 LEFT OUTER JOIN DZSN_MA_EMP ME11 ON ME11.CD_COMPANY = MD11.CD_COMPANY AND ME11.NO_EMP = MD11.NO_EMPMNG
 LEFT OUTER JOIN MA_CODEDTL MC7 ON MC7.CD_COMPANY = ME11.CD_COMPANY AND MC7.CD_SYSDEF = ME11.CD_DUTY_RANK AND MC7.CD_FIELD='HR_H000002' 
 LEFT OUTER JOIN DZSN_MA_PARTNER AG ON AG.CD_PARTNER = H.CD_AGENCY AND AG.CD_COMPANY = H.CD_COMPANY
 LEFT OUTER JOIN DZSN_MA_BIZAREA DMENG ON DMENG.CD_BIZAREA = H.SUPPLIER AND DMENG.CD_COMPANY = L.CD_COMPANY
 LEFT OUTER JOIN FI_PARTNERPTR PTR ON PTR.CD_COMPANY = P1.CD_COMPANY AND PTR.CD_PARTNER = P1.CD_PARTNER AND PTR.SEQ = 1
 LEFT OUTER JOIN DZSN_MA_CODEDTL SM12 ON SM12.CD_FIELD ='MA_B000082' AND SM12.CD_SYSDEF = M.CD_USERDEF2 AND SM12.CD_COMPANY = M.CD_COMPANY
 LEFT OUTER JOIN DZSN_MA_CODEDTL SM13 ON SM13.CD_FIELD ='MA_B000083' AND SM13.CD_SYSDEF = M.CD_USERDEF3 AND SM13.CD_COMPANY = M.CD_COMPANY
 LEFT OUTER JOIN DZSN_MA_CODEDTL SM14 ON SM14.CD_FIELD ='MA_B000084' AND SM14.CD_SYSDEF = M.CD_USERDEF4 AND SM14.CD_COMPANY = M.CD_COMPANY 
 LEFT OUTER JOIN DZSN_MA_CODEDTL SM15 ON SM15.CD_FIELD ='MA_B000085' AND SM15.CD_SYSDEF = M.CD_USERDEF5 AND SM15.CD_COMPANY = M.CD_COMPANY 
 LEFT OUTER JOIN DZSN_MA_CODEDTL SM16 ON SM16.CD_FIELD ='MA_B000086' AND SM16.CD_SYSDEF = M.CD_USERDEF6 AND SM16.CD_COMPANY = M.CD_COMPANY 
 LEFT OUTER JOIN DZSN_MA_CODEDTL SM17 ON SM17.CD_FIELD ='MA_B000087' AND SM17.CD_SYSDEF = M.CD_USERDEF7 AND SM17.CD_COMPANY = M.CD_COMPANY 
 LEFT OUTER JOIN DZSN_MA_CODEDTL SM18 ON SM18.CD_FIELD ='MA_B000088' AND SM18.CD_SYSDEF = M.CD_USERDEF8 AND SM18.CD_COMPANY = M.CD_COMPANY  
 LEFT OUTER JOIN DZSN_MA_CODEDTL SM19 ON SM19.CD_FIELD ='MA_B000089' AND SM19.CD_SYSDEF = M.CD_USERDEF9 AND SM19.CD_COMPANY = M.CD_COMPANY  
 LEFT OUTER JOIN DZSN_MA_CODEDTL SM20 ON SM20.CD_FIELD ='MA_B000090' AND SM20.CD_SYSDEF = M.CD_USERDEF10 AND SM20.CD_COMPANY = M.CD_COMPANY  
 LEFT OUTER JOIN DZSN_MA_CODEDTL CLS_L ON CLS_L.CD_FIELD ='MA_B000030' AND CLS_L.CD_SYSDEF = M.CLS_L AND CLS_L.CD_COMPANY = M.CD_COMPANY  
 LEFT OUTER JOIN DZSN_MA_CODEDTL CLS_M ON CLS_M.CD_FIELD ='MA_B000031' AND CLS_M.CD_SYSDEF = M.CLS_M AND CLS_M.CD_COMPANY = M.CD_COMPANY  
 LEFT OUTER JOIN DZSN_MA_CODEDTL CLS_S ON CLS_S.CD_FIELD ='MA_B000032' AND CLS_S.CD_SYSDEF = M.CLS_S AND CLS_S.CD_COMPANY = M.CD_COMPANY  
 LEFT OUTER JOIN DZSN_MA_CODEDTL ITEMGRP ON ITEMGRP.CD_FIELD ='MA_B000066' AND ITEMGRP.CD_SYSDEF = M.GRP_MFG AND ITEMGRP.CD_COMPANY = M.CD_COMPANY  
 LEFT OUTER JOIN DZSN_MA_PARTNER ITMEPT ON ITMEPT.CD_PARTNER = M.PARTNER AND ITMEPT.CD_COMPANY = M.CD_COMPANY
 LEFT OUTER JOIN FI_GWDOCU GW ON GW.CD_COMPANY = H.CD_COMPANY AND GW.NO_DOCU = H.NO_PO
 LEFT OUTER JOIN SA_SOL SOL ON SOL.CD_COMPANY = L.CD_COMPANY AND SOL.NO_SO = L.NO_SO AND SOL.SEQ_SO = L.NO_SOLINE
 LEFT OUTER JOIN SA_SOH SOH ON SOH.CD_COMPANY = SOL.CD_COMPANY AND SOH.NO_SO = SOL.NO_SO
 LEFT OUTER JOIN DZSN_MA_PARTNER SOHP ON SOHP.CD_PARTNER = SOH.CD_PARTNER AND SOHP.CD_COMPANY = SOH.CD_COMPANY
 LEFT OUTER JOIN DZSN_MA_CODEDTL SM21 ON SM21.CD_FIELD ='MA_B000120' AND SM21.CD_SYSDEF = M.CD_USERDEF11 AND SM21.CD_COMPANY = M.CD_COMPANY  
 LEFT OUTER JOIN SA_PROJECTL_D PJTD ON PJTD.CD_COMPANY = L.CD_COMPANY AND PJTD.NO_PROJECT = L.CD_PJT AND PJTD.SEQ_PROJECT = L.SEQ_PROJECT AND PJTD.NO_LINE = L.NO_LINE_PJTBOM
 LEFT OUTER JOIN DZSN_MA_CODEDTL REASON ON REASON.CD_FIELD ='PU_C000075' AND REASON.CD_SYSDEF = PRL.CD_REASON AND REASON.CD_COMPANY = PRL.CD_COMPANY  
 LEFT OUTER JOIN DZSN_MA_CODEDTL MC8 ON MC8.CD_FIELD ='MA_B000004' AND MC8.CD_SYSDEF = M.UNIT_IM AND MC8.CD_COMPANY = M.CD_COMPANY  
 LEFT OUTER JOIN DZSN_MA_SL SL ON SL.CD_SL = L.CD_SL AND SL.CD_PLANT = L.CD_PLANT AND SL.CD_COMPANY = L.CD_COMPANY
 LEFT JOIN V_PU_MA_B000046 M05 ON M05.CD_COMPANY = L.CD_COMPANY AND M05.CD_FIELD = 'MA_B000046' AND M05.CD_SYSDEF = L.FG_TAX     									   
 LEFT OUTER JOIN DZSN_MA_PARTNER SL_PT ON SL.CD_COMPANY = SL_PT.CD_COMPANY AND SL.CD_PARTNER = SL_PT.CD_PARTNER
WHERE H.CD_COMPANY = @CD_COMPANY                                      
  AND H.NO_PO = @NO_PO                                     
ORDER BY L.NO_LINE     
     
      
-- SUM 데이터  
 SELECT   
  SUM(ISNULL(L.AM,0)) AS AM_H,  
  SUM(ISNULL(L.VAT,0)) AS VAT_H,  
  SUM(ISNULL(L.AM,0)) + SUM(ISNULL(L.VAT,0)) AS HAP_H,  
  SUM(ISNULL(L.QT_PO,0)) AS QT_PO_H,  
  SUM(ISNULL(L.QT_PO_MM,0)) AS QT_PO_MM_H,  
  --SUM(ISNULL(L.AM_EX,0)) AS AM_EX_H,  
  L.NO_PO  
 FROM PU_POL L  
   
 WHERE L.CD_COMPANY =@CD_COMPANY                                      
   AND  L.NO_PO =@NO_PO    
 GROUP BY L.NO_PO--, L.AM, L.VAT
GO


