USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[UP_PU_PO_REG_SELECT]    Script Date: 2022-03-24 오후 3:03:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO 
              
ALTER PROC [NEOE].[UP_PU_PO_REG_SELECT]  
(                           
	 @CD_COMPANY	NVARCHAR(7),                            
	 @NO_PO			NVARCHAR(20),
	 @P_FG_LANG     NVARCHAR(4) = NULL,	--언어
	 @P_NO_LINE		NVARCHAR(4000) = NULL
)          
AS
-- MultiLang Call
EXEC UP_MA_LOCAL_LANGUAGE @P_FG_LANG
                             
DECLARE  @YY_INV   AS NCHAR(4) ,        
         @CD_PLANT AS NVARCHAR(7),        
		 @V_SERVER_KEY NVARCHAR(25)        
		 
SELECT @V_SERVER_KEY = MAX(SERVER_KEY)
  FROM CM_SERVER_CONFIG
 WHERE YN_UPGRADE = 'Y'           
        
SELECT  H.NO_PO, H.CD_PLANT,                           
  H.CD_PARTNER, H.DT_PO, H.CD_PURGRP, H.NO_EMP, H.CD_TPPO, H.FG_UM, H.FG_PAYMENT,                           
  H.FG_TAX,                                         
  H.TP_UM_TAX, H.CD_PJT, H.CD_EXCH , H.RT_EXCH, H.AM_EX, H.AM, H.VAT, H.DC50_PO,                           
  H.TP_PROCESS, H.FG_TAXP, H.YN_AM, H.FG_TRANS,               H.FG_TRACK,                                
  G.NM_PURGRP,B.USE_YN, B.PO_PRICE, B.PO_UNIT,B.TP_PURPRICE,                                         
  (SELECT P.LN_PARTNER FROM DZSN_MA_PARTNER P WHERE P.CD_COMPANY = H.CD_COMPANY AND P.CD_PARTNER= H.CD_PARTNER) AS NM_PARTNER,                                         
  E.NM_KOR AS NM_KOR,                           
  E.CD_DEPT,                                         
  (SELECT A.NM_DEPT FROM DZSN_MA_DEPT A WHERE A.CD_DEPT = E.CD_DEPT AND A.CD_COMPANY = E.CD_COMPANY) AS NM_DEPT,                                         
  (SELECT D.NM_SYSDEF FROM DZSN_MA_CODEDTL D WHERE D.CD_COMPANY = H.CD_COMPANY AND D.CD_SYSDEF = H.FG_TRANS AND D.CD_FIELD = 'PU_C000016' ) AS  NM_TRANS,                 
  (SELECT  (CASE WHEN ISNULL(CD_FLAG1,'') = '' THEN 0 ELSE CONVERT(NUMERIC(20,8),CD_FLAG1) END) AS CD_FLAG1 FROM DZSN_MA_CODEDTL WHERE CD_COMPANY = @CD_COMPANY AND CD_FIELD = 'MA_B000046' AND CD_SYSDEF = H.FG_TAX )   AS  VAT_RATE,                                              
  CASE WHEN LEN(H.CD_PJT) > 0 THEN ( SELECT TOP 1 PJ.NM_PROJECT FROM DZSN_SA_PROJECTH PJ WHERE PJ.CD_COMPANY = H.CD_COMPANY AND PJ.NO_PROJECT = H.CD_PJT ORDER BY NO_SEQ DESC ) ELSE '' END AS NM_PJT,                                      
  T.CD_TPPO,T.NM_TPPO, T.YN_ORDER, T.YN_RCV, T.FG_TPRCV, T.YN_AUTORCV, T.FG_TPPURCHASE,                                     
  T.YN_IMPORT,T.FG_TPIMPORT, T.YN_RETURN, T.YN_SUBCON,T.FG_TRANS, T.YN_AM,                          
  T.YN_USE,                           
  T.YN_REQ,                           
  H.DTS_INSERT,                           
  H.ID_INSERT ,                                   
  C.NO_COMPANY,                           
  C.NM_CEO,                           
  C.ADS_NO,                           
  C.ADS_H,                           
  C.ADS_D,                           
  C.NO_TEL,                           
  C.NO_FAX,                                 
  P.LN_PARTNER,                           
  P.NM_CEO NM_CEO1,                           
  P.NO_POST1,                           
  P.DC_ADS1_H,                           
  P.DC_ADS1_D,                           
  P.NO_TEL1,                           
  P.NO_FAX1,                           
  P.NO_FAX,                           
  P.NM_PTR,                                  
  G.NO_TEL PURGRP_NO_TEL,    
  G.NO_FAX PURGRP_NO_FAX,                           
  G.E_MAIL                           
  PURGRP_E_MAIL,                           
  MB.NO_BIZAREA,                          
  H.DC_RMK2,                              
  H.TP_TRANSPORT,     
  H.COND_PAY,    
  H.COND_PAY_DLV,                    
  H.COND_PRICE,                        
  H.ARRIVER,          
  H.LOADING,                  
  G.CD_CC AS CD_CC_PURGRP,                
  MC_GRP.NM_CC AS NM_CC_PURGRP,                
  T.CD_CC AS CD_CC_TPPO,                
  MC_TP.NM_CC AS NM_CC_TPPO,          
  H.YN_BUDGET,          
  H.BUDGET_PASS,  
  H.COND_PRICE_DLV,  
  H.CD_ARRIVER,  
  MC1.NM_SYSDEF AS NM_ARRIVER,  
  H.CD_LOADING,  
  MC2.NM_SYSDEF AS NM_LOADING,  
  H.NO_HST,  
  H.DC_RMK_TEXT,  
  H.CD_AGENCY,   -- 2011.04.07 추가(대행사)  
  (SELECT P.LN_PARTNER FROM DZSN_MA_PARTNER P WHERE P.CD_COMPANY = H.CD_COMPANY AND P.CD_PARTNER= H.CD_AGENCY) AS NM_AGENCY,  -- 2011.04.07 추가(대행사)  
  ISNULL(H.AM_NEGO,0) AS AM_NEGO,
  H.COND_SHIPMENT,
  H.FREIGHT_CHARGE,
  H.DC_RMK_TEXT2,
  H.CD_STND_PAY AS STND_PAY, --지급기준
  MC3.NM_SYSDEF AS NM_STND_PAY,
  
  ISNULL(H.COND_DAYS,0) AS COND_DAYS,
  H.CD_ORGIN,
  H.DELIVERY_TERMS,
  H.DELIVERY_TIME,
  H.VALIDITY,
  H.TP_PACKING,
  ISNULL(H.DELIVERY_COST,0) AS DELIVERY_COST,
  H.INSPECTION,
  H.DOCUMENT_REQUIRED,
  H.SUPPLIER,
  CASE WHEN @V_SERVER_KEY = 'DMENG' THEN MB2.NM_BIZAREA ELSE SUP.LN_PARTNER END AS NM_SUPPLIER,
  H.MANUFACTURER,
  MAN.LN_PARTNER AS NM_MANUFACTURER,
  H.NO_ORDER,
  H.NM_PACKING,
  SUP.DC_ADS1_H AS SUPP_ADS1_H,
  SUP.DC_ADS1_D AS SUPP_ADS1_D,
  T.TP_GR,
  H.SHIP_DATE,
  H.DACU_NO,
  SUB.DT_PROCESS_IV,
  SUB.DT_PAY_PRE_IV,
  SUB.DT_DUE_IV,
  SUB.FG_PAYBILL_IV,
  SUB.CD_DOCU_IV,
  SUB.AM_K_IV,
  SUB.VAT_TAX_IV,
  SUB.AM_EX_IV,
  ------------ 20140320 추가
  C.NM_COMPANY,
  E.NM_KOR	AS PU_NM_KOR,
  E.NO_TEL AS PU_NO_TEL,
  E.NO_TEL_EMER AS PU_NO_TEL_EMER,
  P.CD_EMP_PARTNER,
  P.NO_TEL	AS P_NO_TEL,
  P.NO_FAX  AS P_NO_FAX,
  C.ADS_H + ' '+C.ADS_D AS COM_ADS,
  E.NO_TEL + '/' + E.NO_TEL_EMER AS E_NO_TEL,
  H.TXT_USERDEF4,
  SUB.DC_RMK_IV,
  H.CD_USERDEF1,
  H.CD_USERDEF2,
  H.CD_USERDEF3,
  H.CD_USERDEF4,
  SUB.CD_BIZAREA_TAX,
  IV.NM_BIZAREA AS NM_BIZAREA_TAX,
  H.TXT_USERDEF3
  
FROM PU_POH H                                       
 LEFT OUTER JOIN  DZSN_MA_PURGRP G  ON    H.CD_COMPANY = G.CD_COMPANY  AND   H.CD_PURGRP = G.CD_PURGRP                                          
 LEFT OUTER JOIN  DZSN_MA_PURORG B  ON    G.CD_COMPANY = B.CD_COMPANY  AND   G.CD_PURORG = B.CD_PURORG                                           
 INNER JOIN  DZSN_PU_TPPO T  ON    H.CD_COMPANY = T.CD_COMPANY  AND   H.CD_TPPO = T.CD_TPPO                                          
 LEFT OUTER JOIN DZSN_MA_EMP E ON E.CD_COMPANY = H.CD_COMPANY AND   E.NO_EMP = H.NO_EMP                                   
 INNER JOIN DZSN_MA_COMPANY C ON H.CD_COMPANY =   C.CD_COMPANY                                  
 INNER JOIN DZSN_MA_PARTNER P ON H.CD_PARTNER = P.CD_PARTNER AND   H.CD_COMPANY = P.CD_COMPANY                                     
 LEFT OUTER JOIN DZSN_MA_BIZAREA MB ON E.CD_BIZAREA = MB.CD_BIZAREA AND E.CD_COMPANY = MB.CD_COMPANY                            
 LEFT OUTER JOIN DZSN_MA_CC MC_GRP ON G.CD_CC = MC_GRP.CD_CC AND G.CD_COMPANY = MC_GRP.CD_COMPANY                
 LEFT OUTER JOIN DZSN_MA_CC MC_TP ON T.CD_CC = MC_TP.CD_CC AND T.CD_COMPANY = MC_TP.CD_COMPANY                
 LEFT OUTER JOIN DZSN_MA_CODEDTL MC1 ON MC1.CD_COMPANY = H.CD_COMPANY AND MC1.CD_SYSDEF = H.CD_ARRIVER AND MC1.CD_FIELD = 'PU_C000046'  
 LEFT OUTER JOIN DZSN_MA_CODEDTL MC2 ON MC2.CD_COMPANY = H.CD_COMPANY AND MC2.CD_SYSDEF = H.CD_LOADING AND MC2.CD_FIELD = 'PU_C000047'   
 LEFT OUTER JOIN DZSN_MA_CODEDTL MC3 ON MC3.CD_COMPANY = H.CD_COMPANY AND MC3.CD_SYSDEF = H.CD_STND_PAY AND MC3.CD_FIELD = 'PU_C000067'   
 LEFT OUTER JOIN DZSN_MA_PARTNER MAN ON MAN.CD_PARTNER = H.MANUFACTURER AND MAN.CD_COMPANY = H.CD_COMPANY
 LEFT OUTER JOIN DZSN_MA_PARTNER SUP ON SUP.CD_PARTNER = H.SUPPLIER AND SUP.CD_COMPANY = H.CD_COMPANY
 LEFT OUTER JOIN PU_POH_SUB SUB ON SUB.NO_PO = H.NO_PO AND SUB.CD_COMPANY = H.CD_COMPANY
 --대명이엔지 전용--
 LEFT OUTER JOIN DZSN_MA_BIZAREA MB2 ON H.SUPPLIER = MB2.CD_BIZAREA AND H.CD_COMPANY = MB2.CD_COMPANY 
 LEFT OUTER JOIN DZSN_MA_BIZAREA IV ON IV.CD_BIZAREA = SUB.CD_BIZAREA_TAX AND IV.CD_COMPANY = SUB.CD_COMPANY 
WHERE H.CD_COMPANY =@CD_COMPANY                          
  AND   H.NO_PO =@NO_PO                                                        
                          
 SELECT @YY_INV = LEFT(DT_PO,4), @CD_PLANT = CD_PLANT FROM PU_POH WHERE CD_COMPANY = @CD_COMPANY AND NO_PO =@NO_PO                
        
 SELECT   
 'N' AS S,  
 ISNULL(L.RT_PO,1) * L.UM AS UM_P,                               
  M.NM_ITEM,                        
  M.STND_ITEM,                         
  M.STND_ITEM AS STND_MA_ITEM,                           
  M.UNIT_IM,                         
  ISNULL(M.UNIT_PO,1) UNIT_PO,                                  
  L.NO_PO,                          
  L.NO_LINE,                          
  L.CD_PLANT,                          
  L.NO_CONTRACT,                          
  L.NO_CTLINE,                                            
  L.NO_PR,                          
  L.NO_PRLINE,                          
  L.FG_TRANS,                          
  L.CD_ITEM,                            
  L.CD_UNIT_MM,                          
  L.FG_RCV,                          
  L.FG_PURCHASE,                                          
  L.DT_LIMIT,                          
  L.QT_PO_MM,                          
  L.QT_PO,                           
  L.QT_REQ,                          
  L.QT_RCV,                          
  LTRIM(RTRIM(L.FG_TAX)) AS FG_TAX,                          
  L.UM_EX_PO,                          
  L.UM_EX,                                        
  L.AM_EX,                          
  L.UM,                          
  L.AM,                          
  L.VAT,                          
  L.CD_SL,                            
  L.FG_POST,                          
  L.YN_AUTORCV,                          
  L.YN_RCV,                                         
  L.YN_RETURN,                          
  L.YN_ORDER,                          
  L.YN_SUBCON,                            
  L.YN_IMPORT,                      
  L.RT_PO,                          
  L.YN_REQ,                          
  L.CD_PJT,                                         
  L.QT_REQ_MM                          
  ,  L.QT_TR_MM,                          
  L.QT_TR,        
 L.AM_EXTR,    
  L.AM_TR,                          
  L.AM_EXREQ,                          
  L.AM_REQ,                          
  L.NO_APP,                                           
  L.NO_APPLINE,                         
  L.QT_RCV_MM,                               
  CASE WHEN L.QT_REQ = 0 AND L.YN_ORDER ='Y' THEN  '001' ELSE L.FG_POCON  END AS FG_POCON,    
  --CASE WHEN LEN(L.CD_PJT) > 0 THEN ( SELECT TOP 1 PJ.NM_PROJECT FROM DZSN_SA_PROJECTH PJ WHERE PJ.CD_COMPANY = H.CD_COMPANY AND PJ.NO_PROJECT = L.CD_PJT ORDER BY NO_SEQ DESC )  
  --         ELSE '' END AS NM_PJT,        
  PJ.NM_PROJECT AS NM_PJT,                                
  (SELECT S.NM_SL FROM DZSN_MA_SL S WHERE S.CD_COMPANY = L.CD_COMPANY AND S.CD_PLANT = L.CD_PLANT AND S.CD_SL = L.CD_SL ) AS NM_SL ,                                        
  (SELECT Z.NM_SYSDEF FROM DZSN_MA_CODEDTL Z WHERE Z.CD_COMPANY = L.CD_COMPANY AND Z.CD_SYSDEF = L.FG_POST AND Z.CD_FIELD = 'PU_C000009' ) AS NM_SYSDEF,                                        
  (SELECT P.NM_PLANT FROM DZSN_MA_PLANT P WHERE P.CD_COMPANY = L.CD_COMPANY AND P.CD_PLANT = L.CD_PLANT) AS NM_PLANT,              '' AS NO_RCV, 0.0 AS NO_RCVLINE,                          
  '' AS YN_PURCHASE ,                        
  '' AS  FG_TPPURCHASE,                           
  H.CD_EXCH,              
  A.NM_SYSDEF NM_EXCH,                              
  0.0 AS QT_POC,                          
  0.0 AS QT_REQC,                        
  --0.0 AS QT_INVC,                        
  0.0 AS QT_ATPC,                         
  L.DC1,                         
  L.DC2,  
  L.DC3,  --2010/12/30 조형우 DC3(비고3) 컬럼 추가                             
  M.DT_VALID,                         
                         
  M.MAT_ITEM,                
  M.FG_TAX_PU,               
  ISNULL(M05.RT_VAT_STR,0) AS RATE_VAT,            
  B.NM_ITEMGRP,                         
  ISNULL(C.AM_ITEM_PU, 0) AM_ITEM_PU,                               
  L.UMVAT_PO,                       
  L.AMVAT_PO,                         
  L.SEQ_PROJECT,                  
  L.CD_CC,                  
  MC.NM_CC,              
  SSD.NM_CUST_DLV,               
  SSD.ADDR1 AS ADDR1_DLV,               
  SSD.NO_TEL_D2 AS NO_TEL_D2_DLV,      
  --(D20110405061) : 김영민(2011-04-08) 현재고 조건 수정--------------------------------------  
  --내용: 비수불계정 ('006', '007', '008', '010') 에 대해 현재고 미표시(0) 적용---------------  
  --   수불계정 ('001', '002', '003', '004', '005', '009')에 현재고 표시    ---------------      
  CASE WHEN M.CLS_ITEM IN ('001', '002', '003', '004', '005', '009') THEN ISNULL(INV.QT_INVC, 0)   
       ELSE 0     END QT_INVC,          
  --------------------------------------------------------------------------------------------  
 L.CD_BUDGET, --예산단위          
 (SELECT FC.NM_BUDGET FROM DZSN_FI_BGCODE FC WHERE FC.CD_COMPANY = L.CD_COMPANY AND FC.CD_BUDGET = L.CD_BUDGET ) AS NM_BUDGET,          
 L.CD_BGACCT,  --예산계정           
 (SELECT FA.NM_BGACCT FROM DZSN_FI_BGACCT FA WHERE FA.CD_COMPANY = L.CD_COMPANY AND FA.CD_BGACCT = L.CD_BGACCT ) AS NM_BGACCT,    
 M.WEIGHT,    
 M.WEIGHT * L.QT_PO_MM AS QT_WEIGHT,  
 L.NO_SO,  
 ISNULL(L.NO_SOLINE,0) AS NO_SOLINE,  
 L.AM + L.VAT AS AM_TOTAL, -- 총금액  
 L.GI_PARTNER, --납품처  
 MP.LN_PARTNER, --납품처명  
  
 L.DT_PLAN,  
 L.DC4,  
 H.CD_AGENCY,  -- 2011.04.07 추가 (대행사)
 (SELECT NM_SYSDEF FROM DZSN_MA_CODEDTL MC WHERE MC.CD_COMPANY = @CD_COMPANY AND MC.CD_FIELD = 'MA_B000010' AND MC.CD_SYSDEF = M.CLS_ITEM) AS NM_CLS_ITEM ,  
 M.CLS_ITEM,
 M.QT_LENGTH,
 M.QT_WIDTH,
 0.0 AS QT_AREA,
 0.0 AS TOTAL_AREA,
 L.UM_EX_AR,
 M.CD_TP,
 
 M.GRP_ITEM,
 MG.NM_ITEMGRP,
 M.STND_DETAIL_ITEM, 
  
 SL.CD_ITEM AS CD_PJT_ITEM, --프로젝트 품목코드  
 I2.NM_ITEM AS NM_PJT_ITEM, --프로젝트 품목명  
 I2.NO_DESIGN AS NO_PJT_DESIGN, --UNIT 도면번호,프로젝트 도면번호
 I2.STND_ITEM AS PJT_ITEM_STND, --프로젝트 품목 규격  
 L.NO_WBS,  
 L.NO_CBS,  
 ACTIVITY.CD_ACTIVITY,  
 ACTIVITY.NM_ACTIVITY,  
 PC.CD_COST,  
 CBS.NM_COST,
 
 M.NO_MODEL,
 M.CD_USERDEF14,
 M.NUM_USERDEF4,
 M.NUM_USERDEF5,
 M.NUM_USERDEF6,
 
 L.CD_USERDEF1,
 L.CD_USERDEF2,
 L.NM_USERDEF1,
 L.NM_USERDEF2,
 L.TP_UM_TAX,
 L.DT_EXDATE,
 L.CD_ITEM_ORIGIN,
 L.AM_EX_TRANS,
 L.AM_TRANS,
 L.NO_LINE_PJTBOM,
 L.MEMO_CD,
 L.CHECK_PEN,
 L.FG_PACKING,
 PRL.FG_SU,
 PRL.CD_REASON,
 PRL.CD_ITEM_MO,
 MOI.NM_ITEM AS NM_ITEM_MO,
 
 M.GRP_MFG,
 MC8.NM_SYSDEF AS NM_GRPMFG,
 M.NM_MAKER,
 L.NUM_USERDEF1,
 APP.UM_PRE,
 ISNULL(APP.UM_PRE,0.0) * ISNULL(L.QT_PO,0.0) AS AM_PRE,
 ISNULL(L.AM_REBATE_EX,0.0) AS AM_REBATE_EX,  -- 리베이트 외화금액추가 2012.09.26 SMR
 ISNULL(L.AM_REBATE,0.0) AS AM_REBATE,
 (SELECT Z.NM_SYSDEF FROM DZSN_MA_CODEDTL Z WHERE Z.CD_COMPANY = M.CD_COMPANY AND Z.CD_SYSDEF = M.FG_IQCL AND Z.CD_FIELD = 'MA_B000131' ) AS FG_IQCL,      -- 수입레벨추가 2012.11.17 SMR
 ISNULL(L.UM_REBATE,0.0) AS UM_REBATE,
 L.DATE_USERDEF1,
 L.DATE_USERDEF2,
 L.TXT_USERDEF1,
 L.TXT_USERDEF2,
 L.CDSL_USERDEF1,
 SL_USER.NM_SL AS NMSL_USERDEF1,
 L.NUM_USERDEF2,
 M.PARTNER AS PI_PARTNER,
 MP2.LN_PARTNER AS PI_LN_PARTNER,
 L.CD_STND_ITEM_1, 
 L.CD_STND_ITEM_2,
 L.CD_STND_ITEM_3,
 L.CD_STND_ITEM_4,
 L.CD_STND_ITEM_5,
 L.NUM_STND_ITEM_1, 
 L.NUM_STND_ITEM_2,
 L.NUM_STND_ITEM_3,
 L.NUM_STND_ITEM_4,
 L.NUM_STND_ITEM_5,
 M.GRP_ITEM CD_ITEMGRP,
 L.UM_WEIGHT,
 M.WEIGHT,
 L.TOT_WEIGHT,
 CP.CD_1 SG_TYPE,
 CP.UM_RT_ETC_1 QT_SG,
 M.CLS_L,
 M.CLS_M,
 M.CLS_S,
 MC1.NM_SYSDEF AS NM_CLS_L,  
 MC2.NM_SYSDEF AS NM_CLS_M,  
 MC3.NM_SYSDEF AS NM_CLS_S,
 M.NO_DESIGN 
 ,M.EN_ITEM,
 L.NO_RELATION,
 L.SEQ_RELATION
 --유니포인트전용
 ,PJ.CD_PARTNER AS CD_PARTNER_PJT
 ,MPJT.LN_PARTNER AS LN_PARTNER_PJT
 ,PJ.NO_EMP AS NO_EMP_PJT
 ,EPJT.NM_KOR AS NM_KOR_PJT
 ,PJ.END_USER AS END_USER,
 -- PMS고도화
 PC.CD_CSTR,
 PC.DL_CSTR,
 PC.NM_CSTR,
 PC.SIZE_CSTR,
 PC.UNIT_CSTR,
 PC.QTY_ACT,
 PC.UNT_ACT,
 PC.AMT_ACT,
 L.ID_MEMO,
 L.CD_WBS,
 L.NO_SHARE,
 L.NO_ISSUE,
 L.NUM_USERDEF3 AS NUM_USERDEF3_PO,
 L.NUM_USERDEF4 AS NUM_USERDEF4_PO,
 L.NUM_USERDEF5 AS NUM_USERDEF5_PO,
 CASE WHEN L.TP_UM_TAX = '001' THEN ISNULL(L.NUM_USERDEF4,0) - ( L.AM + L.VAT)
      ELSE ISNULL(L.NUM_USERDEF4,0) - L.AM END AS AM_DISCONUNT, -- 쿠켄테크전용
 'N' AS S, -- 쿠켄테크전용
 L.NO_QUO,
 L.NO_QUOLINE,
 -- 동양피엔에프(주)전용 컬럼 
 L.AM AS AM_OLD,
 L.CD_BIZPLAN, BIZPLAN.NM_BIZPLAN,
 L.CD_USERDEF3 AS CD_USERDEF3_PO , L.CD_USERDEF4 AS CD_USERDEF4_PO, 
 L.NM_USERDEF3 AS NM_USERDEF3_PO, L.NM_USERDEF4  AS NM_USERDEF4_PO,
 PRL.YN_BUDGET YN_BUDGET_PR, APP.YN_BUDGET YN_BUDGET_APP, L.YN_BUDGET YN_BUDGET, L.BUDGET_PASS, L.AM AS AM_ORG,
 M.FG_SERNO,
 M.TP_PART,
 L.CD_ACCT,
 CODE.NM_ACCT,
 L.NM_USERDEF5,
(SELECT TOP 1 CD_ITEM_PARTNER 
 FROM   DZSN_PU_CUSTITEM  WHERE CD_COMPANY = L.CD_COMPANY AND CD_ITEM = L.CD_ITEM AND CD_PLANT = L.CD_PLANT AND CD_PARTNER = H.CD_PARTNER) CD_ITEM_PARTNER,
(SELECT TOP 1 NM_ITEM_PARTNER 
 FROM   DZSN_PU_CUSTITEM WHERE  CD_COMPANY = L.CD_COMPANY AND CD_ITEM = L.CD_ITEM AND CD_PLANT = L.CD_PLANT AND CD_PARTNER = H.CD_PARTNER) NM_ITEM_PARTNER,
(SELECT TOP 1 STND_ITEM 
 FROM   DZSN_PU_CUSTITEM WHERE  CD_COMPANY = L.CD_COMPANY AND CD_ITEM = L.CD_ITEM AND CD_PLANT = L.CD_PLANT AND CD_PARTNER = H.CD_PARTNER) STND_ITEM_PARTNER,
 SOH.CD_PARTNER AS CD_PARTNER_SO,
 (SELECT LN_PARTNER FROM DZSN_MA_PARTNER WHERE CD_COMPANY = SOH.CD_COMPANY AND CD_PARTNER = SOH.CD_PARTNER) AS LN_PARTNER_SO,
 L.DC50_PO,
 M.LOTSIZE,
 M.LT_ITEM,
 M.TP_ITEM,
 (SELECT OMP.NM_ITEM FROM MA_PITEM OMP WHERE OMP.CD_COMPANY = L.CD_COMPANY AND OMP.CD_PLANT = L.CD_PLANT AND OMP.CD_ITEM = L.CD_ITEM_ORIGIN) AS NM_ITEM_ORIGIN,
 UEMP.NM_KOR AS NM_POST,
 L.DTS_POST
 
FROM PU_POH H                                         
 INNER JOIN  PU_POL L ON    H.NO_PO = L.NO_PO AND   H.CD_COMPANY = L.CD_COMPANY                                         
 LEFT OUTER JOIN DZSN_MA_PITEM M ON    L.CD_COMPANY = M.CD_COMPANY AND   L.CD_ITEM = M.CD_ITEM AND   L.CD_PLANT = M.CD_PLANT                                    
 LEFT OUTER JOIN DZSN_MA_CODEDTL A ON A.CD_COMPANY = H.CD_COMPANY AND A.CD_FIELD = 'MA_B000005' AND A.CD_SYSDEF = H.CD_EXCH                              
 LEFT OUTER JOIN DZSN_MA_ITEMGRP B ON B.CD_COMPANY = H.CD_COMPANY AND B.CD_ITEMGRP = M.GRP_ITEM                             
 LEFT OUTER JOIN MA_GRPITEM_UM_HDS C ON C.CD_COMPANY = H.CD_COMPANY AND C.CD_PLANT = L.CD_PLANT AND C.GRP_ITEM = M.GRP_ITEM AND C.FG_UM = H.FG_UM                            
 LEFT OUTER JOIN DZSN_MA_CC MC ON MC.CD_COMPANY = L.CD_COMPANY AND MC.CD_CC = L.CD_CC                  
 LEFT OUTER JOIN DZSN_SA_SOL_DLV SSD ON L.CD_COMPANY = SSD.CD_COMPANY AND L.CD_PJT = SSD.NO_SO AND L.SEQ_PROJECT = SSD.SEQ_SO AND SSD.FG_TRACK = 'SO'             
 LEFT  JOIN V_PU_MA_B000046 M05 ON M05.CD_COMPANY = L.CD_COMPANY AND M05.CD_FIELD = 'MA_B000046' AND M05.CD_SYSDEF = L.FG_TAX            
LEFT OUTER JOIN          
(         
 SELECT CD_COMPANY,CD_ITEM, CD_PLANT,CD_SL, SUM(QT_GOOD_OPEN + QT_GOOD_GR - QT_GOOD_GI) AS QT_INVC      
   FROM MM_PINVN     
   WHERE P_YR = @YY_INV      
    AND CD_COMPANY = @CD_COMPANY      
 AND CD_PLANT = @CD_PLANT 
   GROUP BY CD_COMPANY,CD_ITEM, CD_PLANT,CD_SL     
) INV ON L.CD_COMPANY = INV.CD_COMPANY AND L.CD_PLANT = INV.CD_PLANT AND L.CD_ITEM = INV.CD_ITEM AND L.CD_SL = INV.CD_SL      
LEFT OUTER JOIN DZSN_MA_PARTNER MP ON MP.CD_COMPANY = L.CD_COMPANY AND MP.CD_PARTNER = L.GI_PARTNER -- 납품처  
LEFT OUTER JOIN DZSN_MA_PARTNER MP2 ON M.CD_COMPANY = MP2.CD_COMPANY AND M.PARTNER = MP2.CD_PARTNER -- 납품처  
LEFT OUTER JOIN DZSN_MA_ITEMGRP MG ON MG.CD_ITEMGRP = M.GRP_ITEM AND MG.CD_COMPANY = M.CD_COMPANY 
LEFT OUTER JOIN SA_PROJECTL SL ON L.CD_COMPANY = SL.CD_COMPANY AND L.CD_PJT = SL.NO_PROJECT AND L.SEQ_PROJECT = SL.SEQ_PROJECT
LEFT OUTER JOIN PJ_WBS W ON L.CD_COMPANY = W.CD_COMPANY AND L.CD_PJT = W.NO_PROJECT AND L.NO_WBS = W.NO_WBS  
LEFT OUTER JOIN PJ_CBS PC ON L.CD_COMPANY = PC.CD_COMPANY AND L.CD_PJT = PC.NO_PROJECT AND PC.NO_CBS = L.NO_CBS   
LEFT OUTER JOIN PJ_ACTIVITY ACTIVITY ON W.CD_COMPANY = ACTIVITY.CD_COMPANY AND W.CD_ACTIVITY = ACTIVITY.CD_ACTIVITY    
LEFT OUTER JOIN PJ_CBSCODE CBS ON PC.CD_COMPANY = CBS.CD_COMPANY AND PC.CD_COST = CBS.CD_COST    
LEFT JOIN DZSN_MA_PITEM I2 ON SL.CD_COMPANY = I2.CD_COMPANY AND SL.CD_PLANT = I2.CD_PLANT AND SL.CD_ITEM = I2.CD_ITEM               
LEFT OUTER JOIN PU_PRL PRL ON PRL.NO_PR = L.NO_PR AND PRL.NO_PRLINE = L.NO_PRLINE AND PRL.CD_COMPANY = L.CD_COMPANY 
LEFT OUTER JOIN DZSN_MA_PITEM MOI ON MOI.CD_ITEM = PRL.CD_ITEM_MO AND MOI.CD_PLANT = PRL.CD_PLANT AND MOI.CD_COMPANY = PRL.CD_COMPANY		  
LEFT OUTER JOIN DZSN_MA_CODEDTL MC8 ON MC8.CD_FIELD ='MA_B000066' AND MC8.CD_SYSDEF = M.GRP_MFG AND MC8.CD_COMPANY = M.CD_COMPANY
LEFT OUTER JOIN PU_APPL APP ON APP.NO_APP = L.NO_APP AND APP.NO_APPLINE = L.NO_APPLINE AND APP.CD_COMPANY = L.CD_COMPANY
LEFT OUTER JOIN DZSN_MA_SL SL_USER ON SL_USER.CD_SL = L.CDSL_USERDEF1 AND SL_USER.CD_COMPANY = L.CD_COMPANY AND SL_USER.CD_PLANT = L.CD_PLANT
LEFT OUTER JOIN PU_CUST_PUBLIC CP ON L.CD_COMPANY = CP.CD_NO_PK_1 AND M.GRP_ITEM = CP.CD_NO_PK_2 AND CP.CD_CUST_SERVER_KEY = @V_SERVER_KEY
                                     AND NM_BUSINESS = 'P_PU_Z_SINJINSM_ITEMGRP_SG' AND SQ_BUSINESS = '1' 
LEFT OUTER JOIN DZSN_MA_CODEDTL MC1 ON MC1.CD_FIELD ='MA_B000030' AND MC1.CD_SYSDEF = M.CLS_L AND MC1.CD_COMPANY = M.CD_COMPANY  
LEFT OUTER JOIN DZSN_MA_CODEDTL MC2 ON MC2.CD_FIELD ='MA_B000031' AND MC2.CD_SYSDEF = M.CLS_M AND MC2.CD_COMPANY = M.CD_COMPANY  
LEFT OUTER JOIN DZSN_MA_CODEDTL MC3 ON MC3.CD_FIELD ='MA_B000032' AND MC3.CD_SYSDEF = M.CLS_S AND MC3.CD_COMPANY = M.CD_COMPANY  
LEFT JOIN DZSN_SA_PROJECTH PJ ON PJ.NO_PROJECT = L.CD_PJT AND PJ.CD_COMPANY = L.CD_COMPANY
LEFT JOIN DZSN_MA_PARTNER MPJT ON MPJT.CD_PARTNER =  PJ.CD_PARTNER AND MPJT.CD_COMPANY = PJ.CD_COMPANY
LEFT JOIN DZSN_MA_EMP EPJT ON EPJT.NO_EMP = PJ.NO_EMP AND EPJT.CD_COMPANY = PJ.CD_COMPANY
LEFT OUTER JOIN DZSN_FI_BIZPLAN BIZPLAN ON L.CD_BIZPLAN =  BIZPLAN.CD_BIZPLAN AND L.CD_COMPANY = BIZPLAN.CD_COMPANY         
LEFT OUTER JOIN DZSN_FI_ACCTCODE CODE ON CODE.CD_ACCT = L.CD_ACCT AND CODE.CD_COMPANY = L.CD_COMPANY
LEFT OUTER JOIN SA_SOH SOH ON SOH.CD_COMPANY = L.CD_COMPANY AND SOH.NO_SO = L.NO_SO
LEFT OUTER JOIN MA_USER UER ON UER.ID_USER = L.ID_POST AND UER.CD_COMPANY = L.CD_COMPANY
LEFT OUTER JOIN MA_EMP UEMP ON UEMP.NO_EMP = UER.NO_EMP AND UEMP.CD_COMPANY = UER.CD_COMPANY

WHERE H.CD_COMPANY =@CD_COMPANY                            
  AND H.NO_PO =@NO_PO   
  AND (L.NO_LINE IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_NO_LINE)) OR @P_NO_LINE = '' OR @P_NO_LINE IS NULL)
ORDER BY L.NO_LINE   



----------- 발행정보(기성매입)------------

SELECT	H.NO_PO,
		H.NO_SEQ,
		H.FG_IV,
		H.DT_PUR_PLAN,
		H.RT_IV,
		H.AM,
		H.AM_K,
		H.AM_VAT,
		H.AM_SUM,
		H.AM_PUL,
		H.CD_PJT,
		H.SEQ_PROJECT,
		H.NM_TEXT,
		H.NM_TEXT2,
		H.AM_EX_PUL,
		H.NO_POLINE
							
FROM PU_PBL H
LEFT OUTER JOIN DZSN_MA_CODEDTL MC ON MC.CD_COMPANY = H.CD_COMPANY AND MC.CD_SYSDEF = H.FG_IV AND MC.CD_FIELD = 'PM_1000013'
WHERE	H.CD_COMPANY = @CD_COMPANY
AND		H.NO_PO		 = @NO_PO
GO


