USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[UP_PU_POLL_UPDATE]    Script Date: 2022-03-24 오후 6:01:07 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

--발주등록사급자재UPDATE
ALTER PROCEDURE [NEOE].[UP_PU_POLL_UPDATE]
(
	@P_CD_COMPANY       NVARCHAR(7),
	@P_CD_PLANT         NVARCHAR(7),     
	@P_NO_PO            NVARCHAR(20), 
	@P_NO_POLINE		NUMERIC(5, 0),     
	@P_NO_LINE          NUMERIC(5, 0),   
	@P_CD_MATL			NVARCHAR(20), 
	@P_QT_NEED			NUMERIC(17, 4), 
	@P_QT_NEED_UNIT		NUMERIC(17, 4), 
	@P_ID_UPDATE        NVARCHAR(15),
	@P_NO_RELATION		NVARCHAR(20),
	@P_SEQ_RELATION		NUMERIC(5,0),
	@P_TXT_USERDEF1		NVARCHAR(100),
	@P_NUM_USERDEF1		NUMERIC(19,6),
	@P_TXT_USERDEF2		NVARCHAR(100) ,
	@P_TXT_USERDEF3		NVARCHAR(100) ,
	@P_TXT_USERDEF4		NVARCHAR(100) ,
	@P_TXT_USERDEF5		NVARCHAR(100) ,
	@P_NUM_USERDEF2		NUMERIC(19,6) 
)
AS
DECLARE	@ERRNO                  INT, 
		@ERRMSG					NVARCHAR(255), 
		@CD_MATL_COMPARE        NVARCHAR(20), 
		@QT_NEED_COMPARE        NUMERIC(17, 4), 
		@QT_NEED_UNIT   
        NUMERIC(17, 4), 
		@QT_REQ                 NUMERIC(17, 4), 
		@QT_PR                  NUMERIC(17, 4), 
		@NO_PR                  NVARCHAR(20), 
		@P_DTS_UPDATE           VARCHAR(14)

SET @P_DTS_UPDATE = REPLACE(REPLACE(REPLACE(CONVERT(VARCHAR(20),
 GETDATE(), 120), '-',''), ' ', ''),':','')

IF (	EXISTS	(	SELECT 1 FROM PU_POL
				WHERE CD_COMPANY = @P_CD_COMPANY
					AND CD_PLANT = @P_CD_PLANT
					AND NO_PO = @P_NO_PO
					AND NO_LINE = @P_NO_POLINE
					AND FG_POST IN ('R', 'S', 'C')        )        )
BEGIN
	SELECT @ERRNO  = 100000, @ERRMSG = '[UP_PU_POLL_UPDATE]확정이후의건입니다. 수정할수없습니다.' GOTO ERROR
END

SELECT @CD_MATL_COMPARE = CD_MATL, @QT_NEED_COMPARE = QT_NEED, @QT_REQ = QT_REQ, @QT_NEED_UNIT = QT_NEED_UNIT
FROM PU_POLL A
WHERE CD_COMPANY = @P_CD_COMPANY
AND CD_PLANT = @P_CD_PLANT
AND NO_PO = @P_NO_PO
AND NO_POLINE = @P_NO_POLINE
AND NO_LINE = @P_NO_LINE

SELECT @NO_PR = ISNULL(A.NO_PR, ''), @QT_PR = ISNULL(B.QT_PR, 0)
FROM PU_POL A
INNER JOIN PU_POH H ON H.CD_COMPANY = @P_CD_COMPANY
	                                AND H.NO_PO = A.NO_PO
	                                AND H.CD_PLANT = A.CD_PLANT
LEFT OUTER JOIN PU_PRL B ON B.CD_COMPANY = @P_CD_COMPANY
	                                AND B.CD_PLANT = H.CD_PLANT
	                                AND B.NO_PR = A.NO_PR
	                                AND B.NO_PRLINE = A.NO_PRLINE
WHERE A.CD_COMPANY = @P_CD_COMPANY
AND A.CD_PLANT = @P_CD_PLANT
AND A.NO_PO = @P_NO_PO
AND A.NO_LINE = @P_NO_POLINE

IF (@CD_MATL_COMPARE != @P_CD_MATL AND @QT_REQ > 0)
BEGIN
SELECT @ERRNO  = 100000, @ERRMSG = '변경하려는자재('+@P_CD_MATL+' --> '+@CD_MATL_COMPARE+')의의뢰수량(QT_REQ)이존재합니다. 수정할수없습니다.' GOTO ERROR
END

IF (@QT_REQ > 0)

BEGIN
SELECT @ERRNO  = 100000, @ERRMSG = '의뢰수량이존재합니다. 수정할수없습니다.' GOTO ERROR
END

IF (@P_QT_NEED < @QT_REQ)
BEGIN
SELECT @ERRNO  = 100000, @ERRMSG = '변경하려는소요량(QT_NEED)이의뢰수량(QT_REQ)보다작습니다. 수정할수없습니다.' GOTO ERROR
END

IF (@P_QT_NEED > (@QT_PR * @QT_NEED_UNIT
) AND @NO_PR <> '')
BEGIN
SELECT @ERRNO  = 100000, @ERRMSG = '변경하려는소요량(QT_NEED = '+LTRIM(STR(@P_QT_NEED))+')이요청수량(QT_PR = '+LTRIM(STR(@QT_PR))+') * 단위소요량(QT_NEED_UNIT = '+@QT_NEED_UNIT+') 보다큽니다. 요청번호는('+@NO_PR+')입니다. 수정할수없습니다.' GOTO ERROR
END

UPDATE PU_POLL
SET CD_MATL = @P_CD_MATL, 
QT_NEED = @P_QT_NEED, 
QT_NEED_UNIT = @P_QT_NEED_UNIT, 
ID_UPDATE = @P_ID_UPDATE, 
DTS_UPDATE = @P_DTS_UPDATE,
NO_RELATION = @P_NO_RELATION,
SEQ_RELATION = @P_SEQ_RELATION,
TXT_USERDEF1 = @P_TXT_USERDEF1,
NUM_USERDEF1 = @P_NUM_USERDEF1,
TXT_USERDEF2 = @P_TXT_USERDEF2,
TXT_USERDEF3 = @P_TXT_USERDEF3,
TXT_USERDEF4 = @P_TXT_USERDEF4,
TXT_USERDEF5 = @P_TXT_USERDEF5,
NUM_USERDEF2 = @P_NUM_USERDEF2

WHERE CD_COMPANY = @P_CD_COMPANY
AND CD_PLANT = @P_CD_PLANT
AND NO_PO = @P_NO_PO
AND NO_POLINE = @P_NO_POLINE
AND NO_LINE = @P_NO_LINE

IF (
@@ERROR <> 0 ) BEGIN SELECT @ERRNO  = 100000, @ERRMSG = '작업을정상적으로처리하지못했습니다.' GOTO ERROR END

RETURN
ERROR: RAISERROR (@ERRMSG, 18 ,1)
GO


