USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_GIR_CUTOFF_S]    Script Date: 2015-06-02 오후 7:34:10 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
            
ALTER PROCEDURE [NEOE].[SP_CZ_SA_GIR_CUTOFF_S]
(
    @P_CD_COMPANY    NVARCHAR(7),
    @P_NO_GIR        NVARCHAR(20),
    @P_YN_CUTOFF     NVARCHAR(1)
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT PH.CD_COMPANY,
       PH.NO_PO,
       PL.NO_DSP,
       @P_NO_GIR AS NO_GIR,
       MP.LN_PARTNER AS NM_SUPPLIER,
       PH.CD_DLV,
       MC.NM_SYSDEF AS NM_DLV,
       PH.DT_DLV,
       PH.TM_DLV,
       MC1.NM_SYSDEF AS NM_TM_DLV,
       PH.DC_DLV,
       (CASE WHEN (ISNULL(PH.CD_DLV, '') = '' OR ISNULL(PH.DT_DLV, '') = '' OR ISNULL(PH.TM_DLV, '') = '') AND 
                  ISNULL(PL.QT_ITEM, 0) > 0 AND 
                  ISNULL(PL.QT_PO, 0) > ISNULL(PL.QT_RCV, 0) THEN 'Y' ELSE 'N' END) AS YN_CHECK,
       (SELECT DTS_CUTOFF 
        FROM CZ_SA_GIRH_WORK_DETAIL WD
        WHERE WD.CD_COMPANY = @P_CD_COMPANY
        AND WD.NO_GIR = @P_NO_GIR) AS DTS_CUTOFF
FROM PU_POH PH
LEFT JOIN MA_PARTNER MP ON MP.CD_COMPANY = PH.CD_COMPANY AND MP.CD_PARTNER = PH.CD_PARTNER
LEFT JOIN CZ_MA_CODEDTL MC ON MC.CD_COMPANY = PH.CD_COMPANY AND MC.CD_FIELD = 'CZ_PU00012' AND MC.CD_SYSDEF = PH.CD_DLV
LEFT JOIN CZ_MA_CODEDTL MC1 ON MC1.CD_COMPANY = PH.CD_COMPANY AND MC1.CD_FIELD = 'CZ_PU00013' AND MC1.CD_SYSDEF = PH.TM_DLV
LEFT JOIN SA_SOH SH ON SH.CD_COMPANY = PH.CD_COMPANY AND SH.NO_SO = PH.CD_PJT
JOIN (SELECT PL.CD_COMPANY, PL.NO_PO,
             SUM(PL.QT_PO) AS QT_PO,
             SUM(PL.QT_RCV) AS QT_RCV,
             SUM(CASE WHEN QL.GRP_ITEM NOT IN ('PV', 'BD') THEN 1 ELSE 0 END) AS QT_ITEM,
             STRING_AGG(QL.NO_DSP, ',') AS NO_DSP
      FROM PU_POL PL
      LEFT JOIN CZ_SA_QTNL QL ON QL.CD_COMPANY = PL.CD_COMPANY AND QL.NO_FILE = PL.NO_SO AND QL.NO_LINE = PL.NO_SOLINE
      WHERE EXISTS (SELECT 1 
                    FROM SA_GIRL GL
                    LEFT JOIN CZ_SA_GIRH_WORK_DETAIL WD ON WD.CD_COMPANY = GL.CD_COMPANY AND WD.NO_GIR = GL.NO_GIR
                    WHERE GL.CD_COMPANY = @P_CD_COMPANY
                    AND GL.NO_GIR = @P_NO_GIR
                    AND GL.CD_COMPANY = QL.CD_COMPANY 
                    AND GL.NO_SO = QL.NO_FILE
                    AND GL.SEQ_SO = QL.NO_LINE
                    AND GL.QT_GIR > ISNULL(GL.QT_GIR_STOCK, 0)
                    AND (ISNULL(@P_YN_CUTOFF, 'N') = 'N' OR ISNULL(WD.DTS_CUTOFF, '') <> ''))
      GROUP BY PL.CD_COMPANY, PL.NO_PO) PL
ON PL.CD_COMPANY = PH.CD_COMPANY AND PL.NO_PO = PH.NO_PO
ORDER BY PH.NO_PO ASC

GO