USE [NEOE]
GO
/****** Object:  Trigger [NEOE].[TU_MA_ITEM_UMPARTNER]    Script Date: 2021-02-24 오후 5:31:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER TRIGGER [NEOE].[TU_MA_ITEM_UMPARTNER] ON [NEOE].[MA_ITEM_UMPARTNER] FOR UPDATE AS
BEGIN

DECLARE 
	@ERRMSG				NVARCHAR(255),
	@NUMROWS			INT,
	@V_SERVER_KEY		NVARCHAR(50)

SELECT @NUMROWS = @@ROWCOUNT 
IF @NUMROWS = 0 RETURN 

SELECT @V_SERVER_KEY = MAX(SERVER_KEY) FROM CM_SERVER_CONFIG WHERE YN_UPGRADE = 'Y'

IF (@V_SERVER_KEY LIKE 'BCWP%' OR @V_SERVER_KEY LIKE 'OHSUNG%' OR @V_SERVER_KEY = 'HOSIGI' OR @V_SERVER_KEY = 'DINTEC')
BEGIN
	-- M20200214185, M20200214189 황대경 : 전용메뉴에서 시작일을 동일하게 입력함
	UPDATE MI
	SET MI.YN_MGMT = 'Y'
	FROM MA_PITEM MI
	JOIN INSERTED I ON I.CD_COMPANY = MI.CD_COMPANY AND I.CD_PLANT = MI.CD_PLANT AND I.CD_ITEM = MI.CD_ITEM
	WHERE I.FG_UM = '003'

	RETURN
END
ELSE
BEGIN
	IF( SELECT COUNT(*)
		FROM MA_ITEM_UMPARTNER MIU, INSERTED I 
		WHERE MIU.CD_COMPANY = I.CD_COMPANY AND
		MIU.CD_ITEM = I.CD_ITEM AND
		MIU.CD_PARTNER = I.CD_PARTNER AND 
		MIU.FG_UM = I.FG_UM AND
		MIU.CD_EXCH = I.CD_EXCH AND 
		--MIU.NO_LINE = I.NO_LINE AND
		MIU.FG_UM = I.FG_UM AND 
		MIU.TP_UMMODULE = I.TP_UMMODULE AND
		MIU.CD_PLANT = I.CD_PLANT AND
		((CONVERT(NUMERIC(8,0),I.SDT_UM) = CONVERT(NUMERIC(8,0),MIU.SDT_UM)))
	) > 1
	BEGIN
		SELECT @ERRMSG = '시작 날짜가 중복되었습니다. 다시 입력하세요.' 
		GOTO ERROR
	END
END

--BEGIN
--	IF( SELECT COUNT(*)
--		FROM MA_ITEM_UMPARTNER MIU, INSERTED I 
--		WHERE MIU.CD_COMPANY = I.CD_COMPANY AND
--		MIU.CD_ITEM = I.CD_ITEM AND
--		MIU.CD_PARTNER = I.CD_PARTNER AND 
--		MIU.FG_UM = I.FG_UM AND
--		MIU.CD_EXCH = I.CD_EXCH AND 
--		--MIU.NO_LINE = I.NO_LINE AND
--		MIU.FG_UM = I.FG_UM AND 
--		MIU.TP_UMMODULE = I.TP_UMMODULE AND
--		MIU.CD_PLANT = I.CD_PLANT AND
--		(((CONVERT(NUMERIC(8,0),I.SDT_UM) >= CONVERT(NUMERIC(8,0),MIU.SDT_UM)) AND (CONVERT(NUMERIC(8,0),I.SDT_UM) <= CONVERT(NUMERIC(8,0),MIU.EDT_UM))) OR
--		((CONVERT(NUMERIC(8,0),I.EDT_UM) >= CONVERT(NUMERIC(8,0),MIU.SDT_UM)) AND (CONVERT(NUMERIC(8,0),I.EDT_UM) <= CONVERT(NUMERIC(8,0),MIU.EDT_UM))) OR
--		((CONVERT(NUMERIC(8,0),I.SDT_UM) >= CONVERT(NUMERIC(8,0),MIU.SDT_UM)) AND (CONVERT(NUMERIC(8,0),I.EDT_UM) <= CONVERT(NUMERIC(8,0),MIU.EDT_UM))) OR
--		((CONVERT(NUMERIC(8,0),I.SDT_UM) <= CONVERT(NUMERIC(8,0),MIU.SDT_UM)) AND (CONVERT(NUMERIC(8,0),I.EDT_UM) >= CONVERT(NUMERIC(8,0),MIU.EDT_UM)))) 
--	) > 1
--	BEGIN
--		SELECT @ERRMSG = '날짜가 중복되었습니다. 다시 입력하세요.' 
--		GOTO ERROR
--	END
--END

END

RETURN
ERROR: 
RAISERROR (@ERRMSG, 18, 1)
RETURN