USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_PU_PO_TP_VAT_U]    Script Date: 2017-02-13 오후 3:22:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



-- EXEC SP_CZ_PU_PO_TP_VAT_U 'K100', 'ST16000364', '38'
ALTER PROCEDURE [NEOE].[SP_CZ_PU_PO_TP_VAT_U]
(
    @P_CD_COMPANY   NVARCHAR(7),
    @P_NO_PO        NVARCHAR(20),
	@P_TP_VAT		NVARCHAR(4)
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

DECLARE @V_ERRMSG   VARCHAR(255),   -- ERROR 메시지
		@V_NO_KEY	NVARCHAR(20)   

BEGIN TRAN SP_CZ_PU_PO_TP_VAT_U
BEGIN TRY

IF EXISTS (SELECT 1 
		   FROM PU_IVL 
		   WHERE CD_COMPANY = @P_CD_COMPANY 
		   AND NO_PO = @P_NO_PO
		   AND YN_RETURN = 'N')
BEGIN
	SELECT @V_ERRMSG = '매입 등록된 발주건 입니다. 매입 취소후 변경 하시기 바랍니다.'                      
	GOTO ERROR
END

PRINT '-- 발주'

UPDATE PL
SET PL.FG_TAX = MC.CD_SYSDEF,
	PL.VAT = (PL.AM * ROUND(CONVERT(NUMERIC(17, 4), CASE WHEN ISNULL(CD_FLAG1, '') = '' THEN '0' ELSE CD_FLAG1 END) / 100, 2))
FROM PU_POL PL
LEFT JOIN MA_CODEDTL MC ON MC.CD_COMPANY = PL.CD_COMPANY AND MC.CD_FIELD = 'MA_B000046' AND MC.CD_SYSDEF = @P_TP_VAT
WHERE PL.CD_COMPANY = @P_CD_COMPANY
AND PL.NO_PO = @P_NO_PO

UPDATE PH
SET PH.FG_TAX = MC.CD_SYSDEF,
	PH.VAT = PL.VAT
FROM PU_POH PH
LEFT JOIN (SELECT CD_COMPANY, NO_PO,
				  SUM(VAT) AS VAT
		   FROM PU_POL
		   GROUP BY CD_COMPANY, NO_PO) PL
ON PL.CD_COMPANY = PH.CD_COMPANY AND PL.NO_PO = PH.NO_PO
LEFT JOIN MA_CODEDTL MC ON MC.CD_COMPANY = PH.CD_COMPANY AND MC.CD_FIELD = 'MA_B000046' AND MC.CD_SYSDEF = @P_TP_VAT
WHERE PH.CD_COMPANY = @P_CD_COMPANY
AND PH.NO_PO = @P_NO_PO

PRINT '-- 입고의뢰'

UPDATE RL
SET RL.FG_TAX = MC.CD_SYSDEF,
	RL.VAT = (RL.AM * ROUND(CONVERT(NUMERIC(17, 4), CASE WHEN ISNULL(CD_FLAG1, '') = '' THEN '0' ELSE CD_FLAG1 END) / 100, 2)),
	RL.VAT_CLS = (RL.AM * ROUND(CONVERT(NUMERIC(17, 4), CASE WHEN ISNULL(CD_FLAG1, '') = '' THEN '0' ELSE CD_FLAG1 END) / 100, 2))
FROM PU_RCVL RL
LEFT JOIN MA_CODEDTL MC ON MC.CD_COMPANY = RL.CD_COMPANY AND MC.CD_FIELD = 'MA_B000046' AND MC.CD_SYSDEF = @P_TP_VAT
WHERE RL.CD_COMPANY = @P_CD_COMPANY
AND RL.NO_PO = @P_NO_PO

PRINT '-- 입고'

UPDATE OL
SET OL.FG_TAX = MC.CD_SYSDEF,
	OL.VAT = (OL.AM * ROUND(CONVERT(NUMERIC(17, 4), CASE WHEN ISNULL(CD_FLAG1, '') = '' THEN '0' ELSE CD_FLAG1 END) / 100, 2)),
	OL.VAT_CLS = (OL.AM_CLS * ROUND(CONVERT(NUMERIC(17, 4), CASE WHEN ISNULL(CD_FLAG1, '') = '' THEN '0' ELSE CD_FLAG1 END) / 100, 2))
FROM MM_QTIO OL
LEFT JOIN MA_CODEDTL MC ON MC.CD_COMPANY = OL.CD_COMPANY AND MC.CD_FIELD = 'MA_B000046' AND MC.CD_SYSDEF = @P_TP_VAT
WHERE OL.CD_COMPANY = @P_CD_COMPANY
AND OL.NO_PSO_MGMT = @P_NO_PO

COMMIT TRAN SP_CZ_PU_PO_TP_VAT_U

END TRY
BEGIN CATCH
	ROLLBACK TRAN SP_CZ_PU_PO_TP_VAT_U
	SELECT @V_ERRMSG = ERROR_MESSAGE()
	GOTO ERROR
END CATCH

RETURN
ERROR: 
RAISERROR(@V_ERRMSG, 16, 1)
ROLLBACK TRAN SP_CZ_PU_PO_TP_VAT_U



GO

