USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_PR_ASSEMBLING_SA_SOL_SUB_JSON]    Script Date: 2017-01-05 오후 5:48:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_PR_ASSEMBLING_SA_SOL_SUB_JSON]          
(
	@P_JSON			NVARCHAR(MAX),
	@P_ID_USER		NVARCHAR(10)	
)  
AS
   
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

DELETE SL
FROM CZ_PR_ASSEMBLING_SA_SOL SL
WHERE EXISTS (SELECT 1 
			  FROM OPENJSON(@P_JSON)
			  WITH
			  (
					CD_COMPANY		NVARCHAR(7),
					CD_PLANT		NVARCHAR(7),
			  		NO_SO			NVARCHAR(20),
					SEQ_SO			NUMERIC(5, 0),
					NO_WO			NVARCHAR(20),
					SEQ_WO			NUMERIC(5, 0),
					NO_ID			NVARCHAR(10),
			  		JSON_FLAG		NVARCHAR(1)
			  ) JS
			  WHERE JS.JSON_FLAG = 'D'
			  AND JS.CD_COMPANY = SL.CD_COMPANY
			  AND JS.CD_PLANT = SL.CD_PLANT
			  AND JS.NO_SO = SL.NO_SO
			  AND JS.SEQ_SO = SL.SEQ_SO
			  AND JS.NO_WO = SL.NO_WO
			  AND JS.SEQ_WO = SL.SEQ_WO
			  AND JS.NO_ID = SL.NO_ID)

INSERT INTO CZ_PR_ASSEMBLING_SA_SOL
(
	CD_COMPANY,
	CD_PLANT,
	NO_SO,
	SEQ_SO,
	NO_WO,
	SEQ_WO,
	CD_ITEM,
	NO_ID,
	ID_INSERT,
	DTS_INSERT
)
SELECT JS.CD_COMPANY,
	   JS.CD_PLANT,
	   JS.NO_SO,
	   JS.SEQ_SO,
	   JS.NO_WO,
	   JS.SEQ_WO,
	   JS.CD_ITEM,
	   JS.NO_ID,
	   @P_ID_USER,
	   NEOE.SF_SYSDATE(GETDATE())
FROM OPENJSON(@P_JSON)
WITH
(
	CD_COMPANY		NVARCHAR(7),
	CD_PLANT		NVARCHAR(7),
	NO_SO			NVARCHAR(20),
	SEQ_SO			NUMERIC(5, 0),
	NO_WO			NVARCHAR(20),
	SEQ_WO			NUMERIC(5, 0),
	CD_ITEM			NVARCHAR(20),
	NO_ID			NVARCHAR(10),
	JSON_FLAG		NVARCHAR(1)
) JS
WHERE JS.JSON_FLAG = 'I'

GO