USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_FORWARD_OUT_MNGL_S]    Script Date: 2016-06-27 오후 5:01:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_SA_FORWARD_OUT_MNGL_S]          
(  
	@P_CD_COMPANY		NVARCHAR(7),
	@P_CD_PARTNER		NVARCHAR(20),
	@P_DT_FORWARD		NVARCHAR(8)
)  
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT FO.CD_COMPANY,
	   FO.CD_PARTNER,
	   FO.DT_FORWARD,
	   FO.NO_GIR,
	   FO.NO_PACK
FROM CZ_SA_FORWARD_OUT FO
WHERE FO.CD_COMPANY = @P_CD_COMPANY
AND FO.CD_PARTNER = @P_CD_PARTNER
AND FO.DT_FORWARD = @P_DT_FORWARD

GO