USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_GIRSCH_D]    Script Date: 2015-10-20 오후 3:40:42 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER PROCEDURE [NEOE].[SP_CZ_SA_GIRSCH_D]  
(  
    @P_CD_COMPANY   NVARCHAR(7),        --회사
    @P_NO_GIR       NVARCHAR(20),       --의뢰번호
	@P_CD_TYPE      NVARCHAR(3),		--유형
	@P_ID_USER		NVARCHAR(15)
)
AS

DECLARE @V_ERRMSG		NVARCHAR(255)
DECLARE	@V_NO_INV		NVARCHAR(20)

BEGIN TRAN SP_CZ_SA_GIRSCH_D
BEGIN TRY

IF @P_CD_TYPE = '001'
BEGIN
	IF EXISTS (SELECT * 
			   FROM CZ_SA_GIRH_WORK_DETAIL
			   WHERE CD_COMPANY = @P_CD_COMPANY
			   AND NO_GIR = @P_NO_GIR
			   AND ISNULL(DC_RMK1, '') = '')
	BEGIN
		SELECT @V_ERRMSG = '수정/취소 사유가 없을 경우 삭제할 수 없습니다. (협조전 번호 : ' + @P_NO_GIR + ')'                     
		GOTO ERROR	
	END

	EXEC SP_CZ_SA_GIR_LOG @P_CD_COMPANY, @P_CD_TYPE, @P_NO_GIR, @P_ID_USER

	IF EXISTS (SELECT 1 
			   FROM SA_GIRL
			   WHERE CD_COMPANY = @P_CD_COMPANY
			   AND NO_GIR = @P_NO_GIR
			   AND ISNULL(QT_GIR_STOCK, 0) > 0
			   AND ISNULL(YN_GI_STOCK, 'N') <> 'P')
	BEGIN
		DECLARE @V_NO_GIREQ NVARCHAR(20)
		DECLARE @V_YYYYMM	NVARCHAR(6)

		SET @V_YYYYMM = SUBSTRING(CONVERT(CHAR(8), GETDATE(), 112), 1, 6)
		EXEC CP_GETNO @P_CD_COMPANY, 'PU', '08', @V_YYYYMM, @V_NO_GIREQ OUTPUT

		EXEC SP_CZ_SA_STOCK_GI_REQ_I @P_CD_COMPANY, @P_NO_GIR, @V_NO_GIREQ, @P_CD_TYPE, 'SL01', 'SL02', @P_ID_USER, 'N'
		EXEC SP_CZ_PU_STS_BATCH_REG_GI @P_CD_COMPANY, '', @V_NO_GIREQ, '', '', @P_ID_USER
		
		EXEC CP_GETNO @P_CD_COMPANY, 'PU', '08', @V_YYYYMM, @V_NO_GIREQ OUTPUT

		EXEC SP_CZ_SA_STOCK_GI_REQ_I @P_CD_COMPANY, @P_NO_GIR, @V_NO_GIREQ, @P_CD_TYPE, 'SL02', 'SL03', @P_ID_USER, 'N'
		EXEC SP_CZ_PU_STS_BATCH_REG_GI @P_CD_COMPANY, '', @V_NO_GIREQ, '', '', @P_ID_USER		
	END

	SELECT @V_NO_INV = MAX(NO_INV) 
	FROM SA_GIRL
	WHERE CD_COMPANY = @P_CD_COMPANY
	AND NO_GIR = @P_NO_GIR

	EXEC SP_CZ_SA_GIR_D @P_CD_COMPANY, @P_NO_GIR, @P_ID_USER
END
ELSE
BEGIN
	IF EXISTS (SELECT * 
			   FROM CZ_SA_GIRH_PACK_DETAIL
			   WHERE CD_COMPANY = @P_CD_COMPANY
			   AND NO_GIR = @P_NO_GIR
			   AND ISNULL(DC_RMK1, '') = '')
	BEGIN
		SELECT @V_ERRMSG = '수정/취소 사유가 없을 경우 삭제할 수 없습니다. (협조전 번호 : ' + @P_NO_GIR + ')'                     
		GOTO ERROR	
	END

	EXEC SP_CZ_SA_GIR_LOG @P_CD_COMPANY, @P_CD_TYPE, @P_NO_GIR, @P_ID_USER

	SELECT @V_NO_INV = MAX(NO_INV) 
	FROM CZ_SA_GIRL_PACK
	WHERE CD_COMPANY = @P_CD_COMPANY
	AND NO_GIR = @P_NO_GIR

	EXEC SP_CZ_SA_GIR_PACK_D @P_CD_COMPANY, @P_NO_GIR
END

IF ISNULL(@V_NO_INV, '') <> ''
	EXEC SP_CZ_TR_EXINV_D @P_CD_COMPANY, @V_NO_INV

COMMIT TRAN SP_CZ_SA_GIRSCH_D

END TRY
BEGIN CATCH
	ROLLBACK TRAN SP_CZ_SA_GIRSCH_D
	SELECT @V_ERRMSG = ERROR_MESSAGE()
	GOTO ERROR
END CATCH

RETURN
ERROR: 
RAISERROR(@V_ERRMSG, 16, 1)
ROLLBACK TRAN SP_CZ_SA_GIRSCH_D

GO

