USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_GIRSCH_CONFIRM]    Script Date: 2023-05-22 오전 9:42:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




  
ALTER PROCEDURE [NEOE].[SP_CZ_SA_GIRSCH_CONFIRM]    
(    
    @P_CD_COMPANY       NVARCHAR(7),
    @P_NO_GIR           NVARCHAR(20),
	@P_CD_TYPE			NVARCHAR(3),
	@P_STA_GIR			NVARCHAR(1),
	@P_YN_CONFIRM		NVARCHAR(1),
	@P_ID_UPDATE        NVARCHAR(15)
)    
AS    

DECLARE @V_STA_GIR_OLD NVARCHAR(1)
DECLARE @V_ERRMSG	   VARCHAR(255) -- ERROR 메시지

BEGIN TRAN SP_CZ_SA_GIRSCH_CONFIRM
BEGIN TRY

IF @P_CD_TYPE = '001'
BEGIN
	SELECT @V_STA_GIR_OLD = STA_GIR
	FROM SA_GIRH
	WHERE CD_COMPANY = @P_CD_COMPANY
	AND NO_GIR = @P_NO_GIR

	IF (@P_STA_GIR = 'R' AND @V_STA_GIR_OLD <> 'O') OR 
	   (@P_STA_GIR = '' AND @V_STA_GIR_OLD <> 'R') OR
	   (@P_STA_GIR = 'O' AND @V_STA_GIR_OLD <> 'R')
	BEGIN
		SELECT @V_ERRMSG = '상태를 변경 할 수 없습니다. (협조전 번호 : ' + @P_NO_GIR + ', 이전상태 : ' + @V_STA_GIR_OLD + ', 변경상태 : ' + @P_STA_GIR + ')'                     
		GOTO ERROR
	END

	IF (@P_STA_GIR = 'R' AND @V_STA_GIR_OLD = 'O')
	BEGIN
		EXEC SP_CZ_SA_STOCK_GI_REQ_I @P_CD_COMPANY, @P_NO_GIR, '', @P_CD_TYPE, 'SL02', 'SL03', @P_ID_UPDATE, 'N'
	END

	IF (@V_STA_GIR_OLD = 'R' AND (@P_STA_GIR = '' OR @P_STA_GIR = 'O'))
	BEGIN
		IF EXISTS (SELECT * 
				   FROM CZ_SA_GIRH_WORK_DETAIL
				   WHERE CD_COMPANY = @P_CD_COMPANY
				   AND NO_GIR = @P_NO_GIR
				   AND ISNULL(DC_RMK1, '') = '')
		BEGIN
			SELECT @V_ERRMSG = '수정/취소 사유가 없을 경우 확정 취소할 수 없습니다. (협조전 번호 : ' + @P_NO_GIR + ')'                     
			GOTO ERROR	
		END
		
		EXEC SP_CZ_SA_GIR_LOG @P_CD_COMPANY, @P_CD_TYPE, @P_NO_GIR, @P_ID_UPDATE

		IF EXISTS (SELECT 1 
				   FROM SA_GIRL
				   WHERE CD_COMPANY = @P_CD_COMPANY
				   AND NO_GIR =  @P_NO_GIR
				   AND ISNULL(QT_GIR_STOCK, 0) > 0
				   AND ISNULL(YN_GI_STOCK, 'N') <> 'P')
		BEGIN
			DECLARE @V_NO_GIREQ NVARCHAR(20)
			DECLARE @V_YYYYMM	NVARCHAR(6)

			SET @V_YYYYMM = SUBSTRING(CONVERT(CHAR(8), GETDATE(), 112), 1, 6)
			EXEC CP_GETNO @P_CD_COMPANY, 'PU', '08', @V_YYYYMM, @V_NO_GIREQ OUTPUT

			EXEC SP_CZ_SA_STOCK_GI_REQ_I @P_CD_COMPANY, @P_NO_GIR, @V_NO_GIREQ, @P_CD_TYPE, 'SL01', 'SL02', @P_ID_UPDATE, 'N'
			EXEC SP_CZ_PU_STS_BATCH_REG_GI @P_CD_COMPANY, '', @V_NO_GIREQ, '', '', @P_ID_UPDATE

			SET @V_YYYYMM = SUBSTRING(CONVERT(CHAR(8), GETDATE(), 112), 1, 6)
			EXEC CP_GETNO @P_CD_COMPANY, 'PU', '08', @V_YYYYMM, @V_NO_GIREQ OUTPUT

			EXEC SP_CZ_SA_STOCK_GI_REQ_I @P_CD_COMPANY, @P_NO_GIR, @V_NO_GIREQ, @P_CD_TYPE, 'SL02', 'SL03', @P_ID_UPDATE, 'N'
			EXEC SP_CZ_PU_STS_BATCH_REG_GI @P_CD_COMPANY, '', @V_NO_GIREQ, '', '', @P_ID_UPDATE
		END
	END 

	UPDATE SA_GIRH
	SET STA_GIR = @P_STA_GIR
	WHERE CD_COMPANY = @P_CD_COMPANY
	AND NO_GIR = @P_NO_GIR

	IF (@P_YN_CONFIRM = 'Y' OR @P_YN_CONFIRM = 'A')
	BEGIN
		UPDATE CZ_SA_GIRH_WORK_DETAIL
		SET ID_CONFIRM = @P_ID_UPDATE,
            DTS_CONFIRM = NEOE.SF_SYSDATE(GETDATE())
		WHERE CD_COMPANY = @P_CD_COMPANY
		AND NO_GIR = @P_NO_GIR

		IF @P_YN_CONFIRM = 'A'
		BEGIN
			UPDATE GH
			SET CD_USERDEF3 = 'A'
			FROM SA_GIRH GH
			WHERE GH.CD_COMPANY = @P_CD_COMPANY
			AND GH.NO_GIR = @P_NO_GIR

			UPDATE WD
			SET WD.DT_COMPLETE = (SELECT TOP 1 CL.DT_CAL 
								  FROM MA_CALENDAR CL
							      WHERE CL.CD_COMPANY = WD.CD_COMPANY
							      AND CL.FG1_HOLIDAY = 'W'
							      AND CL.DT_CAL >= CONVERT(CHAR(8), DATEADD(DAY, 1, GETDATE()), 112))
		    FROM CZ_SA_GIRH_WORK_DETAIL WD
			WHERE WD.CD_COMPANY = @P_CD_COMPANY
			AND WD.NO_GIR = @P_NO_GIR
		END
	END
END	   
ELSE
BEGIN
	SELECT @V_STA_GIR_OLD = STA_GIR
	FROM CZ_SA_GIRH_PACK
	WHERE CD_COMPANY = @P_CD_COMPANY
	AND NO_GIR = @P_NO_GIR

	IF (@P_STA_GIR = 'C' AND @V_STA_GIR_OLD <> 'R') OR
	   (@P_STA_GIR = 'R' AND @V_STA_GIR_OLD <> 'C' AND @V_STA_GIR_OLD <> 'O') OR
	   (@P_STA_GIR = '' AND @V_STA_GIR_OLD <> 'R') OR
	   (@P_STA_GIR = 'O' AND @V_STA_GIR_OLD <> 'R')
	BEGIN
		SELECT @V_ERRMSG = '상태를 변경 할 수 없습니다. (협조전 번호 : ' + @P_NO_GIR + ', 이전상태 : ' + @V_STA_GIR_OLD + ', 변경상태 : ' + @P_STA_GIR + ')'                     
		GOTO ERROR
	END

	SELECT @V_NO_GIREQ = NO_GIREQ
	FROM CZ_SA_GIRH_PACK_DETAIL
	WHERE CD_COMPANY = @P_CD_COMPANY
	AND NO_GIR = @P_NO_GIR

	IF (@P_STA_GIR = 'R' AND @V_STA_GIR_OLD = 'O')
	BEGIN
		EXEC SP_CZ_SA_STOCK_GI_REQ_I @P_CD_COMPANY, @P_NO_GIR, '', @P_CD_TYPE, 'SL02', 'SL03', @P_ID_UPDATE, 'N'
	END

	IF (@V_STA_GIR_OLD = 'R' AND (@P_STA_GIR = '' OR @P_STA_GIR = 'O'))
	BEGIN
		IF EXISTS (SELECT * 
				   FROM CZ_SA_GIRH_PACK_DETAIL
				   WHERE CD_COMPANY = @P_CD_COMPANY
				   AND NO_GIR = @P_NO_GIR
				   AND ISNULL(DC_RMK1, '') = '')
		BEGIN
			SELECT @V_ERRMSG = '수정/취소 사유가 없을 경우 확정 취소할 수 없습니다. (협조전 번호 : ' + @P_NO_GIR + ')'                     
			GOTO ERROR	
		END

		EXEC SP_CZ_SA_GIR_LOG @P_CD_COMPANY, @P_CD_TYPE, @P_NO_GIR, @P_ID_UPDATE
	END

	IF @P_STA_GIR = 'R' AND (SELECT ISNULL(STA_GIR, '') FROM CZ_SA_GIRH_PACK WHERE CD_COMPANY = @P_CD_COMPANY AND NO_GIR = @P_NO_GIR) = 'C'
	BEGIN
		IF EXISTS (SELECT * 
				   FROM CZ_SA_GIRH_PACK_DETAIL
				   WHERE CD_COMPANY = @P_CD_COMPANY
				   AND NO_GIR = @P_NO_GIR
				   AND ISNULL(DC_RMK1, '') = '')
		BEGIN
			SELECT @V_ERRMSG = '수정/취소 사유가 없을 경우 포장 종결 취소할 수 없습니다. (협조전 번호 : ' + @P_NO_GIR + ')'                     
			GOTO ERROR	
		END

		EXEC SP_CZ_SA_GIR_LOG @P_CD_COMPANY, @P_CD_TYPE, @P_NO_GIR, @P_ID_UPDATE
	END
	
	UPDATE CZ_SA_GIRH_PACK
	SET STA_GIR = @P_STA_GIR
	WHERE CD_COMPANY = @P_CD_COMPANY
	AND NO_GIR = @P_NO_GIR

	IF (@P_YN_CONFIRM = 'Y' OR @P_YN_CONFIRM = 'A')
	BEGIN
		UPDATE CZ_SA_GIRH_PACK_DETAIL
		SET ID_CONFIRM = @P_ID_UPDATE,
            DTS_CONFIRM = NEOE.SF_SYSDATE(GETDATE())
		WHERE CD_COMPANY = @P_CD_COMPANY
		AND NO_GIR = @P_NO_GIR
		
		IF @P_YN_CONFIRM = 'A'
		BEGIN
			UPDATE GH
			SET GH.CD_USERDEF3 = 'A'
			FROM CZ_SA_GIRH_PACK GH
			WHERE GH.CD_COMPANY = @P_CD_COMPANY
			AND GH.NO_GIR = @P_NO_GIR

			UPDATE PD
			SET PD.DT_COMPLETE = (SELECT TOP 1 CL.DT_CAL 
								  FROM MA_CALENDAR CL
							      WHERE CL.CD_COMPANY = PD.CD_COMPANY
							      AND CL.FG1_HOLIDAY = 'W'
							      AND CL.DT_CAL >= CONVERT(CHAR(8), DATEADD(DAY, 1, GETDATE()), 112))
		    FROM CZ_SA_GIRH_PACK_DETAIL PD
			WHERE PD.CD_COMPANY = @P_CD_COMPANY
			AND PD.NO_GIR = @P_NO_GIR
	    END
	END
END

COMMIT TRAN SP_CZ_SA_GIRSCH_CONFIRM

END TRY
BEGIN CATCH
	ROLLBACK TRAN SP_CZ_SA_GIRSCH_CONFIRM
	SELECT @V_ERRMSG = ERROR_MESSAGE()
	GOTO ERROR
END CATCH

RETURN
ERROR: 
RAISERROR(@V_ERRMSG, 16, 1)
ROLLBACK TRAN SP_CZ_SA_GIRSCH_CONFIRM

GO


