USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_PR_MARKING_REG_SUB_XML]    Script Date: 2016-10-28 오후 7:27:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_PR_MARKING_REG_SUB_XML] 
(
	@P_XML			XML, 
	@P_ID_USER		NVARCHAR(10), 
    @DOC			INT = NULL
) 
AS 

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

EXEC SP_XML_PREPAREDOCUMENT @DOC OUTPUT, @P_XML 

-- ================================================== DELETE
DELETE A 
FROM CZ_PR_MARKING_SETTING A 
JOIN OPENXML (@DOC, '/XML/D', 2) 
        WITH (CD_COMPANY	NVARCHAR(7),
			  CD_ITEM 		NVARCHAR(20),
			  CD_PARTNER 	NVARCHAR(20)) B 
ON A.CD_COMPANY = B.CD_COMPANY 
AND A.CD_ITEM = B.CD_ITEM
AND A.CD_PARTNER = B.CD_PARTNER
-- ================================================== INSERT
INSERT INTO CZ_PR_MARKING_SETTING 
(
	CD_COMPANY,
	CD_ITEM,
	CD_PARTNER,
	YN_CERT,
	ID_INSERT,
	DTS_INSERT
)
SELECT CD_COMPANY,
	   CD_ITEM,
	   CD_PARTNER,
	   YN_CERT,
       @P_ID_USER, 
       NEOE.SF_SYSDATE(GETDATE()) 
  FROM OPENXML (@DOC, '/XML/I', 2) 
          WITH (CD_COMPANY		NVARCHAR(7),
				CD_ITEM         NVARCHAR(20),
				CD_PARTNER      NVARCHAR(20),
				YN_CERT			NVARCHAR(1))
-- ================================================== UPDATE    
UPDATE A 
   SET A.YN_CERT = B.YN_CERT,
	   A.ID_UPDATE = @P_ID_USER, 
	   A.DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE())
  FROM CZ_PR_MARKING_SETTING A 
  JOIN OPENXML (@DOC, '/XML/U', 2) 
          WITH (CD_COMPANY		NVARCHAR(7),
				CD_ITEM         NVARCHAR(20),
				CD_PARTNER      NVARCHAR(20),
				YN_CERT			NVARCHAR(1)) B 
ON A.CD_COMPANY = B.CD_COMPANY 
AND A.CD_ITEM = B.CD_ITEM
AND A.CD_PARTNER = B.CD_PARTNER

EXEC SP_XML_REMOVEDOCUMENT @DOC 

GO

