USE [NEOE]
GO

/****** Object:  Table [NEOE].[CZ_SA_CONTRACT_RPTH]    Script Date: 2017-09-08 오전 9:02:47 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [NEOE].[CZ_SA_CONTRACT_RPTH](
	[CD_COMPANY] [nvarchar](7) NOT NULL,
	[NO_SO] [nvarchar](20) NOT NULL,
	[ID_FIRST_APPROVAL] [nvarchar](15) NULL,
	[DTS_FIRST_APPROVAL] [nvarchar](14) NULL,
	[ID_SECOND_APPROVAL] [nvarchar](15) NULL,
	[DTS_SECOND_APPROVAL] [nvarchar](14) NULL,
	[YN_RE_APPROVAL] [nvarchar](1) NULL,
	[DTS_RE_APPROVAL] [nvarchar](14) NULL,
	[YN_BEFORE_STATUS] [nvarchar](1) NULL,
	[DC_COMMENT_FIRST] [nvarchar](500) NULL,
	[DC_COMMENT_SECOND] [nvarchar](500) NULL,
	[ID_INSERT] [nvarchar](15) NULL,
	[DTS_INSERT] [nvarchar](14) NULL,
	[ID_UPDATE] [nvarchar](15) NULL,
	[DTS_UPDATE] [nvarchar](14) NULL,
 CONSTRAINT [PK_CZ_SA_CONTRACT_RPT_H] PRIMARY KEY CLUSTERED 
(
	[CD_COMPANY] ASC,
	[NO_SO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [NEOE].[CZ_SA_CONTRACT_RPTH] ADD  CONSTRAINT [DF_CZ_SA_CONTRACT_RPT_H_DTS_INSERT]  DEFAULT (replace(replace(replace(CONVERT([varchar](20),getdate(),(120)),'-',''),' ',''),':','')) FOR [DTS_INSERT]
GO


