USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[UP_CZ_PR_OPOUT_REG_DELETE]    Script Date: 2022-08-25 오후 3:42:17 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER PROC [NEOE].[UP_CZ_PR_OPOUT_REG_DELETE]
(
    @P_CD_COMPANY   NVARCHAR(7),
    @P_CD_PLANT     NVARCHAR(7),
    @P_NO_WO        NVARCHAR(20),
    @P_CD_OP		NVARCHAR(4)
)
AS

DECLARE @ERRMSG     NVARCHAR(255),
		@V_SERVER_KEY NVARCHAR(50)
		
SELECT @V_SERVER_KEY = MAX(SERVER_KEY) FROM CM_SERVER_CONFIG WHERE YN_UPGRADE = 'Y'

IF EXISTS (	SELECT 1
			FROM CZ_PR_WO_INSP A
			LEFT JOIN PR_WO_ROUT B ON B.CD_COMPANY = A.CD_COMPANY AND B.NO_WO = A.NO_WO AND B.NO_LINE = A.NO_LINE
			WHERE A.CD_COMPANY = @P_CD_COMPANY
			AND A.NO_WO = @P_NO_WO
			AND B.CD_OP = @P_CD_OP
			AND A.NO_OPOUT_PO IS NOT NULL)
BEGIN
	SELECT @ERRMSG = '[UP_CZ_PR_OPOUT_REG_DELETE]ID번호 중 발주상태인 ID번호가 있습니다.' 
	GOTO ERROR
END

DELETE FROM CZ_PR_OPOUT_PR
WHERE CD_COMPANY = @P_CD_COMPANY
    AND CD_PLANT = @P_CD_PLANT
    AND NO_WO = @P_NO_WO
    AND CD_OP = @P_CD_OP

DELETE CZ_PR_WO_INSP FROM CZ_PR_WO_INSP A
LEFT JOIN PR_WO_ROUT B ON B.CD_COMPANY = A.CD_COMPANY AND B.NO_WO = A.NO_WO AND B.NO_LINE = A.NO_LINE
WHERE A.CD_COMPANY = @P_CD_COMPANY
AND A.NO_WO = @P_NO_WO
AND B.CD_OP = @P_CD_OP
AND A.NO_INSP = '994'
AND A.NO_OPOUT_PO = NULL

IF (@@ERROR <> 0 ) BEGIN SELECT @ERRMSG = '[UP_CZ_PR_OPOUT_REG_DELETE]작업을정상적으로처리하지못했습니다.' GOTO ERROR END

RETURN
ERROR: RAISERROR (@ERRMSG, 18, 1)
RETURN
GO


