USE [NEOE]
GO

/****** Object:  Table [NEOE].[CZ_CRM_PARTNER_PIC_LOG]    Script Date: 2020-03-20 오후 1:26:47 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [NEOE].[CZ_CRM_PARTNER_PIC_LOG](
	[CD_COMPANY] [nvarchar](7) NOT NULL,
	[CD_PARTNER] [nvarchar](20) NOT NULL,
	[SEQ] [numeric](5, 0) NOT NULL,
	[NO_INDEX] [int] NOT NULL,
	[DT_LOG] [nvarchar](8) NULL,
	[DC_CONTENTS] [nvarchar](500) NULL,
	[QT_RATE] [numeric](4, 0) NULL,
	[DC_RMK] [nvarchar](1000) NULL,
	[ID_INSERT] [nvarchar](15) NULL,
	[DTS_INSERT] [nvarchar](14) NULL,
	[ID_UPDATE] [nvarchar](15) NULL,
	[DTS_UPDATE] [nvarchar](14) NULL,
 CONSTRAINT [PK_CZ_CRM_PARTNER_PIC_LOG] PRIMARY KEY CLUSTERED 
(
	[CD_COMPANY] ASC,
	[CD_PARTNER] ASC,
	[SEQ] ASC,
	[NO_INDEX] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


