USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_VSSL_ETRYNDL2]    Script Date: 2018-11-26 오후 7:26:51 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




ALTER PROCEDURE [NEOE].[SP_CZ_SA_VSSL_ETRYNDL2]
(
    @P_CLSGN	    NVARCHAR(10),
    @P_NM_VSSL	    NVARCHAR(20),
	@P_CD_PRTAG		NVARCHAR(500),
	@P_DT_START		NVARCHAR(8),
	@P_DT_END		NVARCHAR(8)
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT VH.CLSGN,
	   VH.NM_VSSL,
	   VH.NM_PRTAG,
	   VH.DT_ETRYPT_YEAR,
	   VH.CNT_ETRYPT,
	   VH.NM_ETRYPT_PURPS,
	   VH.NM_FRST_DPMPRT_PRT,
	   VH.NM_PRVS_DPMPRT_PRT,
	   VH.NM_NX_INPT_PRT,
	   VH.NM_DSTN_PRT,
	   VH.DTS_ETRYPT,
	   VH.DTS_TKOFF
FROM CZ_SA_VSSL_ETRYNDH VH
WHERE VH.CLSGN = @P_CLSGN
AND VH.NM_VSSL = @P_NM_VSSL
AND (DTS_ETRYPT BETWEEN @P_DT_START + '000000' AND @P_DT_END + '999999')
AND (ISNULL(@P_CD_PRTAG, '') = '' OR CD_PRTAG IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_PRTAG)))
ORDER BY VH.DTS_ETRYPT DESC


GO

