USE [NEOE]
GO

/****** Object:  Table [NEOE].[CZ_MA_WORKFLOWL]    Script Date: 2019-10-23 오전 11:39:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [NEOE].[CZ_MA_WORKFLOWL](
	[CD_COMPANY] [nvarchar](7) NOT NULL,
	[NO_KEY] [nvarchar](20) NOT NULL,
	[TP_STEP] [nvarchar](3) NOT NULL,
	[NO_LINE] [int] NOT NULL,
	[NO_KEY_REF] [nvarchar](20) NULL,
	[CD_SUPPLIER] [nvarchar](20) NULL,
	[NO_HST] [numeric](3, 0) NULL,
	[NM_FILE] [nvarchar](max) NULL,
	[NM_FILE_REAL] [nvarchar](max) NULL,
	[YN_DONE] [nvarchar](1) NULL,
	[DTS_DONE] [nvarchar](14) NULL,
	[YN_PARSING] [nvarchar](1) NULL,
	[ID_INSERT] [nvarchar](15) NULL,
	[DTS_INSERT] [nvarchar](14) NULL,
	[ID_UPDATE] [nvarchar](15) NULL,
	[DTS_UPDATE] [nvarchar](14) NULL,
	[YN_INCLUDED] [nvarchar](1) NULL,
 CONSTRAINT [PK_CZ_MA_WORKFLOW] PRIMARY KEY CLUSTERED 
(
	[CD_COMPANY] ASC,
	[NO_KEY] ASC,
	[TP_STEP] ASC,
	[NO_LINE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [NEOE].[CZ_MA_WORKFLOWL] ADD  CONSTRAINT [DF_CZ_MA_WORKFLOWL_YN_PARSING]  DEFAULT ('N') FOR [YN_PARSING]
GO


