USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_PU_ADPAYMENT_BILL_DD]    Script Date: 2015-08-06 오후 2:35:42 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER PROCEDURE [NEOE].[SP_CZ_PU_ADPAYMENT_BILL_DD]
(
	@P_CD_COMPANY       NVARCHAR(7), 
	@P_NO_BILLS         NVARCHAR(20), 
	@P_NO_IV            NVARCHAR(20), 
	@P_GUBUN            NVARCHAR(40), 
	@P_CD_PARTNER       NVARCHAR(20),
	@P_NO_ADPAY         NVARCHAR(20)
) 
AS 
BEGIN
    DECLARE
	@ERRNO                 INT,
    @ERRMSG                VARCHAR(255)

	DELETE CZ_PU_ADPAYMENT_BILL_D
	WHERE CD_COMPANY = @P_CD_COMPANY
	AND NO_BILLS = @P_NO_BILLS
	AND NO_IV = @P_NO_IV
	AND NO_ADPAY = @P_NO_ADPAY

IF (@@ERROR <> 0 )
BEGIN  
      SELECT @ERRNO  = 100000,  
             @ERRMSG = 'CZ_PU_ADPAYMENT_BILL_D DELETE ERROR'  
      GOTO ERROR  
END

RETURN
ERROR:  
    ROLLBACK TRAN
    RAISERROR (@ERRMSG, 18 , 1)  
END
GO

