USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_PU_ADPAYMENT_BILL_DI]    Script Date: 2015-08-06 오후 2:35:21 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER PROCEDURE [NEOE].[SP_CZ_PU_ADPAYMENT_BILL_DI]
(
	@P_CD_COMPANY		NVARCHAR(7), 
	@P_NO_BILLS			NVARCHAR(20), 
	@P_NO_IV			NVARCHAR(20), 
	@P_DT_IV			NVARCHAR(8), 
	@P_AM_TARGET		NUMERIC(17,4), 
	@P_AM_RCPS			NUMERIC(17,4), 
	@P_GUBUN			NVARCHAR(40), 
	@P_CD_PARTNER		NVARCHAR(20),
	@P_CD_EXCH_IV		NVARCHAR(3),
	@P_RT_EXCH_IV		NUMERIC(17,4), 
	@P_AM_TARGET_EX		NUMERIC(17,4), 
	@P_AM_RCPS_EX		NUMERIC(17,4), 
	@P_AM_PL			NUMERIC(17,4), 
	@P_NO_ADPAY			NVARCHAR(20),
	@P_NO_DOCU_ADPAY	NVARCHAR(20),
	@P_NO_DOLINE_ADPAY	NUMERIC(5,0),
	@P_NO_DOCU_IV		NVARCHAR(20),
	@P_NO_DOLINE_IV		NUMERIC(5,0),
	@P_ID_INSERT		NVARCHAR(15)
) 
AS 
BEGIN
    DECLARE
	@ERRNO                    INT,
    @ERRMSG                   VARCHAR(255)

INSERT INTO CZ_PU_ADPAYMENT_BILL_D
(
	CD_COMPANY,
	NO_BILLS,
	NO_IV,
	DT_IV,
	AM_TARGET,
	AM_RCPS,
	GUBUN,
    CD_EXCH_IV,
	RT_EXCH_IV,
	AM_TARGET_EX,
	AM_RCPS_EX,
	AM_PL,
	NO_ADPAY,
	NO_DOCU_ADPAY,
	NO_DOLINE_ADPAY,
	NO_DOCU_IV,
	NO_DOLINE_IV,
	ID_INSERT,
	DTS_INSERT
)
VALUES
(
	@P_CD_COMPANY,
	@P_NO_BILLS,
	@P_NO_IV,
	@P_DT_IV,
	@P_AM_TARGET,
	@P_AM_RCPS,
	@P_GUBUN,
	@P_CD_EXCH_IV,
	@P_RT_EXCH_IV,
	@P_AM_TARGET_EX,
	@P_AM_RCPS_EX,
	@P_AM_PL,
	@P_NO_ADPAY,
	@P_NO_DOCU_ADPAY,
	@P_NO_DOLINE_ADPAY,
	@P_NO_DOCU_IV,
	@P_NO_DOLINE_IV,
	@P_ID_INSERT,
	NEOE.SF_SYSDATE(GETDATE())
)

IF (@@ERROR <> 0 )
BEGIN  
      SELECT @ERRNO  = 100000,  
                   @ERRMSG = 'CZ_PU_ADPAYMENT_BILL_D INSERT ERROR '  
      GOTO ERROR  
END

RETURN
ERROR: 
    ROLLBACK TRAN 
    RAISERROR (@ERRMSG, 18 , 1)  
END
GO

