USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_PU_ADPAYMENT_BILL_LU]    Script Date: 2015-08-06 오후 2:26:21 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER PROCEDURE [NEOE].[SP_CZ_PU_ADPAYMENT_BILL_LU]
(
	@P_CD_COMPANY		NVARCHAR(7), 
	@P_NO_BILLS			NVARCHAR(20), 
	@P_NO_LINE			NUMERIC(3,0),
	@P_AM_TARGET		NUMERIC(17,4), 
	@P_AM_BILLS			NUMERIC(17,4), 
	@P_NO_ADPAY			NVARCHAR(20),
	@P_CD_EXCH			NVARCHAR(3),
	@P_RT_EXCH			NUMERIC(17,4), 
	@P_AM_TARGET_EX		NUMERIC(17,4), 
	@P_AM_BILLS_EX		NUMERIC(17,4),
	@P_NO_MGMT			NVARCHAR(40),
	@P_CD_PJT			NVARCHAR(20),
	@P_NO_DOCU			NVARCHAR(20),
	@P_NO_DOLINE		NUMERIC(5,0),
	@P_ID_UPDATE		NVARCHAR(15)
) 
AS 
BEGIN
DECLARE	@ERRNO			INT,
		@ERRMSG			VARCHAR(255), 
		@AM_ORIGINAL	NUMERIC(17,4), 
		@AM_INPUT		NUMERIC(17,4)

	UPDATE	CZ_PU_ADPAYMENT_BILL_L
	SET	CD_COMPANY = @P_CD_COMPANY,
		NO_BILLS = @P_NO_BILLS,
		NO_LINE	= @P_NO_LINE,
		AM_TARGET = @P_AM_TARGET,
		AM_BILLS = @P_AM_BILLS,
		NO_ADPAY = @P_NO_ADPAY,
		CD_EXCH	= @P_CD_EXCH,
		RT_EXCH	= @P_RT_EXCH,
		AM_TARGET_EX = @P_AM_TARGET_EX,
		AM_BILLS_EX	= @P_AM_BILLS_EX,
		NO_MGMT	= @P_NO_MGMT,
		CD_PJT = @P_CD_PJT,
		NO_DOCU = @P_NO_DOCU,
		NO_DOLINE = @P_NO_DOLINE,
		ID_UPDATE = @P_ID_UPDATE,
		DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE())
	WHERE CD_COMPANY = @P_CD_COMPANY
	AND NO_BILLS = @P_NO_BILLS
	AND NO_LINE	= @P_NO_LINE

IF (@@ERROR <> 0 )
BEGIN  
SELECT	@ERRNO  = 100000,  
		@ERRMSG = 'CZ_PU_ADPAYMENT_BILL_L UPDATE ERROR '  
GOTO	ERROR  
END

RETURN
ERROR:  
    ROLLBACK TRAN
    RAISERROR (@ERRMSG, 18 , 1)  
END
GO

