USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_PU_ADPAYMENT_BILL_DU]    Script Date: 2015-08-06 오후 2:35:32 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER PROCEDURE [NEOE].[SP_CZ_PU_ADPAYMENT_BILL_DU]
(
	@P_CD_COMPANY		NVARCHAR(7), 
	@P_NO_BILLS			NVARCHAR(20), 
	@P_NO_IV			NVARCHAR(20), 
	@P_DT_IV			NVARCHAR(8), 
	@P_AM_TARGET		NUMERIC(17,4), 
	@P_AM_RCPS			NUMERIC(17,4), 
	@P_GUBUN			NVARCHAR(40), 
	@P_CD_PARTNER		NVARCHAR(20),
	@P_CD_EXCH_IV		NVARCHAR(3),
	@P_RT_EXCH_IV		NUMERIC(17,4), 
	@P_AM_TARGET_EX		NUMERIC(17,4), 
	@P_AM_RCPS_EX		NUMERIC(17,4), 
	@P_AM_PL			NUMERIC(17,4), 
	@P_NO_ADPAY			NVARCHAR(20),
	@P_NO_DOCU_ADPAY	NVARCHAR(20),
	@P_NO_DOLINE_ADPAY	NUMERIC(5,0),
	@P_NO_DOCU_IV		NVARCHAR(20),
	@P_NO_DOLINE_IV		NUMERIC(5,0),
	@P_ID_UPDATE		NVARCHAR(15)
) 
AS 
BEGIN
    DECLARE
	@ERRNO                    INT,
    @ERRMSG                   VARCHAR(255)

	UPDATE CZ_PU_ADPAYMENT_BILL_D
	SET CD_COMPANY = @P_CD_COMPANY,
		NO_BILLS = @P_NO_BILLS,
		NO_IV = @P_NO_IV,
		DT_IV = @P_DT_IV,
		AM_TARGET = @P_AM_TARGET,
		AM_RCPS = @P_AM_RCPS,
		CD_EXCH_IV = @P_CD_EXCH_IV,
		RT_EXCH_IV = @P_RT_EXCH_IV,
		AM_TARGET_EX = @P_AM_TARGET_EX,
		AM_RCPS_EX = @P_AM_RCPS_EX,
		AM_PL = @P_AM_PL,
		NO_DOCU_ADPAY = @P_NO_DOCU_ADPAY,
		NO_DOLINE_ADPAY = @P_NO_DOLINE_ADPAY,
		NO_DOCU_IV = @P_NO_DOCU_IV,
		NO_DOLINE_IV = @P_NO_DOLINE_IV,
		ID_UPDATE = @P_ID_UPDATE,
		DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE())
	WHERE CD_COMPANY = @P_CD_COMPANY
	AND NO_BILLS = @P_NO_BILLS
	AND NO_IV = @P_NO_IV
	AND NO_ADPAY = @P_NO_ADPAY

IF (@@ERROR <> 0 )
BEGIN  
      SELECT @ERRNO  = 100000,  
                   @ERRMSG = 'CZ_PU_ADPAYMENT_BILL_D UPDATE ERROR '  
      GOTO ERROR  
END

RETURN
ERROR:  
    ROLLBACK TRAN
    RAISERROR (@ERRMSG, 18 , 1)  
END
GO

