USE [NEOE]
GO
/****** Object:  StoredProcedure [NEOE].[SP_CZ_PR_ROUT_EQUIP_S]    Script Date: 2023-06-27 오후 4:19:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_PR_ROUT_EQUIP_S]
(  
    @P_CD_COMPANY       NVARCHAR(7),
    @P_CD_PLANT         NVARCHAR(7),
	@P_CD_ITEM			NVARCHAR(20),
	@P_NO_OPPATH		NVARCHAR(3),
	@P_CD_OP			NVARCHAR(4),
	@P_CD_WCOP			NVARCHAR(7)
)  
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT
	RE.CD_COMPANY
,	RE.CD_PLANT
,	RE.CD_ITEM
,	RE.NO_OPPATH
,	RE.CD_OP
,	RE.CD_WC
,	RE.CD_WCOP
,	RE.CD_EQUIP
,	EQ.NM_EQUIP
,	EQ.CD_EQIP_GRP
,	RE.QT_LABOR_PLAN
,	RE.ID_INSERT
,	MU.NM_USER AS NM_INSERT
,	RE.DTS_INSERT
FROM CZ_PR_ROUT_EQUIP RE
LEFT JOIN PR_EQUIP EQ ON RE.CD_COMPANY = EQ.CD_COMPANY AND RE.CD_EQUIP = EQ.CD_EQUIP
LEFT JOIN MA_USER MU ON MU.CD_COMPANY = RE.CD_COMPANY AND MU.ID_USER = RE.ID_INSERT
WHERE RE.CD_COMPANY = @P_CD_COMPANY
AND RE.CD_PLANT = @P_CD_PLANT
AND RE.CD_ITEM = @P_CD_ITEM
AND RE.NO_OPPATH = @P_NO_OPPATH
AND RE.CD_OP = @P_CD_OP
AND RE.CD_WCOP = @P_CD_WCOP