SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_PR_ROUT_REG_L_D]  
(  
	@P_CD_OP          NVARCHAR(4),  
	@P_CD_ITEM        NVARCHAR(20),  
	@P_NO_OPPATH      NVARCHAR(3),  
	@P_CD_PLANT       NVARCHAR(7),  
	@P_CD_COMPANY     NVARCHAR(7),   
	@P_TP_OPPATH      NVARCHAR(3)  
)  
AS

DECLARE @V_ERRMSG NVARCHAR(255)   -- ERROR 메시지

BEGIN TRAN SP_CZ_PR_ROUT_REG_L_D
BEGIN TRY

IF EXISTS (SELECT 1
		   FROM PR_WO WO
		   JOIN PR_WO_ROUT WR ON WR.CD_COMPANY = WO.CD_COMPANY AND WR.NO_WO = WO.NO_WO
		   WHERE WO.CD_COMPANY = @P_CD_COMPANY
		   AND WO.CD_PLANT = @P_CD_PLANT
		   AND WO.PATN_ROUT = @P_NO_OPPATH
		   AND WO.CD_ITEM = @P_CD_ITEM
		   AND WR.CD_OP = @P_CD_OP)
BEGIN
	SELECT @V_ERRMSG = '작업 진행 중인 공정은 삭제 할 수 없습니다.'                     
	GOTO ERROR	
END

DELETE 
FROM PR_ROUT_L  
WHERE CD_COMPANY = @P_CD_COMPANY  
AND CD_PLANT = @P_CD_PLANT  
AND CD_ITEM = @P_CD_ITEM  
AND NO_OPPATH = @P_NO_OPPATH  
AND TP_OPPATH = @P_TP_OPPATH  
AND CD_OP = @P_CD_OP  

DELETE 
FROM PR_ROUT_ASN
WHERE CD_COMPANY = @P_CD_COMPANY 
AND CD_PLANT = @P_CD_PLANT 
AND CD_ITEM = @P_CD_ITEM
AND NO_OPPATH = @P_NO_OPPATH
AND TP_OPPATH = @P_TP_OPPATH
AND CD_OP = @P_CD_OP

COMMIT TRAN SP_CZ_PR_ROUT_REG_L_D

END TRY
BEGIN CATCH
	ROLLBACK TRAN SP_CZ_PR_ROUT_REG_L_D
	SELECT @V_ERRMSG = ERROR_MESSAGE()
	GOTO ERROR
END CATCH

RETURN
ERROR: 
RAISERROR(@V_ERRMSG, 16, 1)
ROLLBACK TRAN SP_CZ_PR_ROUT_REG_L_D

GO