USE [NEOE]
GO
/****** Object:  StoredProcedure [NEOE].[SP_CZ_PR_ROUT_REG_L_I]    Script Date: 2021-02-18 오후 1:12:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

--UP_PR_ROUT_L_INSERT
ALTER PROCEDURE [NEOE].[SP_CZ_PR_ROUT_REG_L_I]
(
	@P_CD_WCOP			NVARCHAR(7),
	@P_CD_OP			NVARCHAR(4),
	@P_CD_WC			NVARCHAR(7),
	@P_CD_ITEM			NVARCHAR(50),
	@P_NO_OPPATH		NVARCHAR(3),
	@P_CD_PLANT			NVARCHAR(7),
	@P_CD_COMPANY		NVARCHAR(7),
	@P_TM_SETUP			NVARCHAR(6),
	@P_TM				NVARCHAR(6),
	@P_TM_MOVE			NVARCHAR(6),
	@P_CD_RSRC			NVARCHAR(7),
	@P_TP_RSRC			NVARCHAR(3),
	@P_YN_RECEIPT		NVARCHAR(1),
	@P_YN_BF			NVARCHAR(1),
	@P_QT_OVERLAP		NUMERIC(17,4),
	@P_N_OPSPLIT		NUMERIC(3,0),
	@P_YN_PAR			NVARCHAR(1),
	@P_DY_SBCNT			NUMERIC(3,0),
	@P_CD_TOOL			NVARCHAR(7),
	@P_ID_INSERT		NVARCHAR(15),
	@P_YN_QC			NVARCHAR(1),
	@P_YN_FINAL			NVARCHAR(1),
	@P_TP_OPPATH		NVARCHAR(3)   = NULL,
	@P_CD_EQUIP			NVARCHAR(30)  = NULL,
	@P_RT_YIELD			NUMERIC(17,4) = NULL,
	@P_QT_LABOR_PLAN	NUMERIC(17,4) = NULL,
	@P_SET_REASON		NVARCHAR(3)	  = NULL,
	@P_DC_RMK			NVARCHAR(100) = NULL,
	@P_SET_METHOD		NVARCHAR(3)	  = NULL,
	@P_DY_PLAN			NUMERIC(5, 0) = 0,
	@P_NO_SFT			NVARCHAR(3)   = NULL,
	@P_YN_ROUT_SU_IV	NVARCHAR(1)	  = NULL,
	@P_YN_INSP			NVARCHAR(1)	  = NULL,
	@P_DC_OP			NVARCHAR(MAX),
	@P_YN_USE			NVARCHAR(1),
	@P_NUM_USERDEF1		NUMERIC(17,4) = NULL,
	@P_NUM_USERDEF2		NUMERIC(17,4) = NULL,
	@P_NUM_USERDEF3		NUMERIC(17,4) = NULL,
	@P_TXT_USERDEF1		NVARCHAR(4000) = NULL,
	@P_TXT_USERDEF2		NVARCHAR(200) = NULL,
	@P_TXT_USERDEF3		NVARCHAR(200) = NULL,
	@P_CD_USERDEF1		NVARCHAR(3) = NULL,
	@P_CD_USERDEF2		NVARCHAR(3) = NULL,
	@P_CD_USERDEF3		NVARCHAR(3) = NULL,
	@P_NUM_USERDEF4		NUMERIC(17, 4) = NULL,
	@P_NUM_USERDEF5		NUMERIC(17, 4) = NULL,
	@P_NUM_USERDEF6		NUMERIC(17, 4) = NULL,
	@P_NUM_USERDEF7		NUMERIC(17, 4) = NULL,
	@P_NUM_USERDEF8		NUMERIC(17, 4) = NULL,
	@P_NUM_USERDEF9		NUMERIC(17, 4) = NULL,
	@P_TXT_USERDEF4		NVARCHAR(200) = NULL,
	@P_TXT_USERDEF5		NVARCHAR(200) = NULL,
	@P_TXT_USERDEF6		NVARCHAR(200) = NULL,
	@P_TXT_USERDEF7		NVARCHAR(200) = NULL,
	@P_TXT_USERDEF8		NVARCHAR(200) = NULL,
	@P_TXT_USERDEF9		NVARCHAR(200) = NULL
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

DECLARE	@P_DTS_INSERT	VARCHAR(14),
		@ERRMSG			VARCHAR(255),
		@V_CD_EXC		NVARCHAR(3)

SET @P_DTS_INSERT = NEOE.SF_SYSDATE(GETDATE())

INSERT PR_ROUT_L
(
	CD_WCOP,
	CD_OP,
	CD_WC,
	CD_ITEM,
	NO_OPPATH,
	CD_PLANT,
	CD_COMPANY,
	TM_SETUP,
	TM,
	TM_MOVE,
	CD_RSRC,
	TP_RSRC,
	YN_RECEIPT,
	YN_BF,
	QT_OVERLAP,
	N_OPSPLIT,
	YN_PAR,
	DY_SBCNT,
	CD_TOOL,
	ID_INSERT,
	DTS_INSERT,
	YN_QC,
	YN_FINAL,
	TP_OPPATH,
	CD_EQUIP,
	RT_YIELD,
	QT_LABOR_PLAN,
	SET_REASON,
	DC_RMK,
	SET_METHOD,
	DY_PLAN,
	NO_SFT,
	YN_ROUT_SU_IV,
	YN_INSP,
	DC_OP,
	YN_USE,
	NUM_USERDEF1,
	NUM_USERDEF2,
	NUM_USERDEF3,
	TXT_USERDEF1,
	TXT_USERDEF2,
	TXT_USERDEF3,
	CD_USERDEF1,
	CD_USERDEF2,
	CD_USERDEF3,
	NUM_USERDEF4,
	NUM_USERDEF5,
	NUM_USERDEF6,
	NUM_USERDEF7,
	NUM_USERDEF8,
	NUM_USERDEF9,
	TXT_USERDEF4,
	TXT_USERDEF5,
	TXT_USERDEF6,
	TXT_USERDEF7,
	TXT_USERDEF8,
	TXT_USERDEF9
)
VALUES
(
	@P_CD_WCOP,
	@P_CD_OP,
	@P_CD_WC,
	@P_CD_ITEM,
	@P_NO_OPPATH,
	@P_CD_PLANT,
	@P_CD_COMPANY,
	@P_TM_SETUP,
	@P_TM,
	@P_TM_MOVE,
	@P_CD_RSRC,
	@P_TP_RSRC,
	@P_YN_RECEIPT,
	@P_YN_BF,
	@P_QT_OVERLAP,
	@P_N_OPSPLIT,
	@P_YN_PAR,
	@P_DY_SBCNT,
	@P_CD_TOOL,
	@P_ID_INSERT,
	@P_DTS_INSERT,
	@P_YN_QC,
	@P_YN_FINAL,
	@P_TP_OPPATH,
	@P_CD_EQUIP,
	@P_RT_YIELD,
	@P_QT_LABOR_PLAN,
	@P_SET_REASON,
	@P_DC_RMK,
	@P_SET_METHOD,
	@P_DY_PLAN,
	@P_NO_SFT,
	@P_YN_ROUT_SU_IV,
	@P_YN_INSP,
	@P_DC_OP,
	@P_YN_USE,
	@P_NUM_USERDEF1,
	@P_NUM_USERDEF2,
	@P_NUM_USERDEF3,
	@P_TXT_USERDEF1,
	@P_TXT_USERDEF2,
	@P_TXT_USERDEF3,
	@P_CD_USERDEF1,
	@P_CD_USERDEF2,
	@P_CD_USERDEF3,
	@P_NUM_USERDEF4,
	@P_NUM_USERDEF5,
	@P_NUM_USERDEF6,
	@P_NUM_USERDEF7,
	@P_NUM_USERDEF8,
	@P_NUM_USERDEF9,
	@P_TXT_USERDEF4,
	@P_TXT_USERDEF5,
	@P_TXT_USERDEF6,
	@P_TXT_USERDEF7,
	@P_TXT_USERDEF8,
	@P_TXT_USERDEF9
)

IF (@@ERROR <> 0) BEGIN SELECT @ERRMSG = '[UP_PR_ROUT_L_INSERT]INSERT PR_ROUT_L 입력구문에서 오류가 발생했습니다.' GOTO ERROR END

SELECT @V_CD_EXC = ISNULL(CD_EXC, '000')
FROM MA_EXC
WHERE CD_COMPANY = @P_CD_COMPANY
AND EXC_TITLE = '공정경로등록-등록시BOM적용'

SELECT	@V_CD_EXC = ISNULL(@V_CD_EXC, '000')

IF (@V_CD_EXC = '000')
BEGIN
	EXEC UP_PR_ROUT_ASN_STND_INSERT @P_CD_COMPANY = @P_CD_COMPANY, @P_CD_PLANT = @P_CD_PLANT, @P_CD_ITEM = @P_CD_ITEM, @P_NO_OPPATH = @P_NO_OPPATH, @P_TP_OPPATH = @P_TP_OPPATH

	IF (@@ERROR <> 0 ) BEGIN SELECT @ERRMSG = '[UP_PR_ROUT_L_INSERT]UP_PR_ROUT_ASN_STND_INSERT 에서 오류가 발생했습니다.' GOTO ERROR END
END

ELSE IF(@V_CD_EXC = '100'AND @P_TP_OPPATH <> 'S')
BEGIN
	EXEC UP_PR_ROUT_ASN_STND_PM_MBOM_I @P_CD_COMPANY = @P_CD_COMPANY, @P_CD_PLANT = @P_CD_PLANT, @P_CD_ITEM = @P_CD_ITEM, @P_NO_OPPATH = @P_NO_OPPATH, @P_TP_OPPATH = @P_TP_OPPATH

	IF (@@ERROR <> 0 ) BEGIN SELECT @ERRMSG = '[UP_PR_ROUT_ASN_STND_PM_MBOM_I]UP_PR_ROUT_ASN_STND_INSERT 에서 오류가 발생했습니다.' GOTO ERROR END
END

IF (@@ERROR <> 0 ) BEGIN SELECT @ERRMSG = '[UP_PR_ROUT_L_INSERT]UP_PR_ROUT_ASN_STND_INSERT 에서 오류가 발생했습니다.' GOTO ERROR END

RETURN
ERROR: RAISERROR (@ERRMSG, 18, 1)