USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_PR_ROUT_INSP_COPY]    Script Date: 2021-02-18 오후 1:26:05 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_PR_ROUT_INSP_COPY]
(
	@P_CD_COMPANY		NVARCHAR(7),
	@P_CD_PLANT			NVARCHAR(7),
	@P_CD_ITEM_FROM		NVARCHAR(20),
	@P_NO_OPPATH_FROM	NVARCHAR(3),
	@P_CD_OP_FROM		NVARCHAR(4),
	@P_CD_WCOP_FROM		NVARCHAR(7),
	@P_CD_ITEM_TO		NVARCHAR(20),
	@P_NO_OPPATH_TO		NVARCHAR(3),
	@P_CD_OP_TO			NVARCHAR(4),
	@P_CD_WCOP_TO		NVARCHAR(7),
	@P_ID_USER			NVARCHAR(10)
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

INSERT INTO CZ_PR_ROUT_INSP 
(
	CD_COMPANY,
	CD_PLANT,
	CD_ITEM,
	NO_OPPATH,
	CD_OP,
	CD_WCOP,
	NO_INSP,
	DC_ITEM,
	CD_MEASURE,
	DC_MEASURE,
	DC_LOCATION,
	DC_SPEC,
	QT_MIN,
	QT_MAX,
	TP_DATA,
	CNT_INSP,
	YN_CERT,
	YN_USE,
	YN_SAMPLING,
	YN_ASSY,
	CD_CLEAR_GRP,
	DC_RMK,
	ID_INSERT,
	DTS_INSERT
)
SELECT CD_COMPANY,
	   CD_PLANT,
	   @P_CD_ITEM_TO AS CD_ITEM,
	   @P_NO_OPPATH_TO AS NO_OPPATH,
	   @P_CD_OP_TO AS CD_OP,
	   @P_CD_WCOP_TO AS CD_WCOP,
	   NO_INSP,
	   DC_ITEM,
	   CD_MEASURE,
	   DC_MEASURE,
	   DC_LOCATION,
	   DC_SPEC,
	   QT_MIN,
	   QT_MAX,
	   TP_DATA,
	   CNT_INSP,
	   YN_CERT,
	   YN_USE,
	   YN_SAMPLING,
	   YN_ASSY,
	   CD_CLEAR_GRP,
	   DC_RMK,
       @P_ID_USER, 
       NEOE.SF_SYSDATE(GETDATE()) 
FROM CZ_PR_ROUT_INSP RI
WHERE RI.CD_COMPANY = @P_CD_COMPANY
AND RI.CD_PLANT = @P_CD_PLANT
AND RI.CD_ITEM = @P_CD_ITEM_FROM
AND RI.NO_OPPATH = @P_NO_OPPATH_FROM
AND RI.CD_OP = @P_CD_OP_FROM
AND RI.CD_WCOP = @P_CD_WCOP_FROM

GO

