USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_ITEM_UPDATE_XML]    Script Date: 2018-03-21 오전 8:53:51 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER PROCEDURE [NEOE].[SP_CZ_SA_ITEM_UPDATE_XML] 
(
	@P_XML			XML, 
	@P_ID_USER		NVARCHAR(10), 
    @DOC			INT = NULL
) 
AS 

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

EXEC SP_XML_PREPAREDOCUMENT @DOC OUTPUT, @P_XML 

-- ================================================== UPDATE    
UPDATE A 
SET A.CD_ITEM = B.CD_ITEM_AFTER,
	A.CD_ITEM_SUB = B.CD_ITEM_SUB_AFTER,
    A.ID_UPDATE = @P_ID_USER, 
    A.DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE())
FROM CZ_SA_QTNL A 
JOIN OPENXML (@DOC, '/XML/U', 2) 
        WITH (CD_COMPANY			NVARCHAR(7),
			  NO_FILE				NVARCHAR(20),
			  NO_LINE				INT,
			  CD_ITEM_AFTER		    NVARCHAR(20),
			  CD_ITEM_SUB_AFTER		NVARCHAR(20)) B 
ON A.CD_COMPANY = B.CD_COMPANY
AND A.NO_FILE = B.NO_FILE
AND A.NO_LINE = B.NO_LINE 

EXEC SP_XML_REMOVEDOCUMENT @DOC 

GO

