USE [NEOE]
GO

/****** Object:  Table [NEOE].[CZ_SA_FORWARD_CHARGE_H]    Script Date: 2020-12-07 오후 2:04:46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [NEOE].[CZ_SA_FORWARD_CHARGE_H](
	[CD_COMPANY] [nvarchar](7) NOT NULL,
	[CD_PARTNER] [nvarchar](20) NOT NULL,
	[TP_DELIVERY] [nvarchar](4) NOT NULL,
	[DT_MONTH] [nvarchar](6) NOT NULL,
	[NO_MDOCU] [nvarchar](20) NULL,
	[NO_MDOCU_TAX] [nvarchar](20) NULL,
	[DC_RMK] [nvarchar](200) NULL,
	[ID_INSERT] [nvarchar](15) NULL,
	[DTS_INSERT] [nvarchar](14) NULL,
	[ID_UPDATE] [nvarchar](15) NULL,
	[DTS_UPDATE] [nvarchar](14) NULL,
 CONSTRAINT [PK_CZ_SA_FORWARD_CHARGE_H_1] PRIMARY KEY CLUSTERED 
(
	[CD_COMPANY] ASC,
	[CD_PARTNER] ASC,
	[TP_DELIVERY] ASC,
	[DT_MONTH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


