USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_FORWARD_CHARGE_H_XML]    Script Date: 2016-06-28 오후 1:28:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_SA_FORWARD_CHARGE_H_XML] 
(
	@P_XML			XML, 
	@P_ID_USER		NVARCHAR(10), 
    @DOC			INT = NULL
) 
AS 

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

EXEC SP_XML_PREPAREDOCUMENT @DOC OUTPUT, @P_XML 

IF EXISTS (SELECT * 
		   FROM CZ_SA_FORWARD_CHARGE_H A 
		   JOIN OPENXML (@DOC, '/XML/D', 2) 
		           WITH (CD_COMPANY		NVARCHAR(7),
		   			     CD_PARTNER		NVARCHAR(20),
		   			     TP_DELIVERY	NVARCHAR(4),
		   			     DT_MONTH		NVARCHAR(6)) B 
		   ON A.CD_COMPANY = B.CD_COMPANY 
		   AND A.CD_PARTNER = B.CD_PARTNER
		   AND A.TP_DELIVERY = B.TP_DELIVERY
		   AND A.DT_MONTH = B.DT_MONTH
		   AND EXISTS (SELECT 1 
					   FROM FI_DOCU FD
					   WHERE FD.CD_COMPANY = A.CD_COMPANY
					   AND (FD.NO_MDOCU = A.NO_MDOCU OR FD.NO_MDOCU = A.NO_MDOCU_TAX)))
BEGIN
	EXEC SP_XML_REMOVEDOCUMENT @DOC 
	RAISERROR('전표처리된 건은 삭제 할수 없습니다.', 16, 1)
	RETURN
END

-- ================================================== DELETE
DELETE A 
FROM CZ_SA_FORWARD_CHARGE_H A 
JOIN OPENXML (@DOC, '/XML/D', 2) 
        WITH (CD_COMPANY	NVARCHAR(7),
			  CD_PARTNER	NVARCHAR(20),
			  TP_DELIVERY	NVARCHAR(4),
			  DT_MONTH		NVARCHAR(6)) B 
ON A.CD_COMPANY = B.CD_COMPANY 
AND A.CD_PARTNER = B.CD_PARTNER
AND A.TP_DELIVERY = B.TP_DELIVERY
AND A.DT_MONTH = B.DT_MONTH
-- ================================================== INSERT
INSERT INTO CZ_SA_FORWARD_CHARGE_H 
(
	CD_COMPANY,
	CD_PARTNER,
	TP_DELIVERY,
	DT_MONTH,
	DC_RMK,
	ID_INSERT,
	DTS_INSERT
)
SELECT CD_COMPANY,
	   CD_PARTNER,
	   TP_DELIVERY,
	   DT_MONTH,
	   DC_RMK,
       @P_ID_USER, 
       NEOE.SF_SYSDATE(GETDATE()) 
  FROM OPENXML (@DOC, '/XML/I', 2) 
          WITH (CD_COMPANY		NVARCHAR(7), 
			    CD_PARTNER		NVARCHAR(20),
				TP_DELIVERY		NVARCHAR(4),
				DT_MONTH		NVARCHAR(6),
				DC_RMK		    NVARCHAR(200))
-- ================================================== UPDATE
UPDATE A
SET A.DC_RMK = B.DC_RMK,
	A.ID_UPDATE = @P_ID_USER,
	A.DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE())
FROM CZ_SA_FORWARD_CHARGE_H A
JOIN OPENXML (@DOC, '/XML/U', 2) 
        WITH (CD_COMPANY		NVARCHAR(7), 
			  CD_PARTNER		NVARCHAR(20),
			  TP_DELIVERY		NVARCHAR(4),
			  DT_MONTH			NVARCHAR(6),
			  DC_RMK		    NVARCHAR(200)) B
ON B.CD_COMPANY = A.CD_COMPANY 
AND B.CD_PARTNER = A.CD_PARTNER
AND B.TP_DELIVERY = A.TP_DELIVERY
AND B.DT_MONTH = A.DT_MONTH

EXEC SP_XML_REMOVEDOCUMENT @DOC 

GO