USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_FORWARD_CHARGE_L_XML]    Script Date: 2016-06-28 오후 1:28:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_SA_FORWARD_CHARGE_L_XML] 
(
	@P_XML			XML, 
	@P_ID_USER		NVARCHAR(10), 
    @DOC			INT = NULL
) 
AS 

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

EXEC SP_XML_PREPAREDOCUMENT @DOC OUTPUT, @P_XML 

IF EXISTS (SELECT * 
		   FROM CZ_SA_FORWARD_CHARGE_L A 
		   JOIN OPENXML (@DOC, '/XML/D', 2) 
		           WITH (CD_COMPANY		NVARCHAR(7),
		   			     CD_PARTNER		NVARCHAR(20),
		   			     TP_DELIVERY	NVARCHAR(4),
		   			     DT_MONTH		NVARCHAR(6),
		   			     SEQ			INT) B 
		   ON A.CD_COMPANY = B.CD_COMPANY 
		   AND A.CD_PARTNER = B.CD_PARTNER
		   AND A.TP_DELIVERY = B.TP_DELIVERY
		   AND A.DT_MONTH = B.DT_MONTH
		   AND A.SEQ = B.SEQ
		   AND EXISTS (SELECT 1 
					   FROM FI_DOCU FD
					   WHERE FD.CD_COMPANY = A.CD_COMPANY
					   AND FD.NO_MDOCU = A.NO_MDOCU))
BEGIN
	EXEC SP_XML_REMOVEDOCUMENT @DOC
	RAISERROR('전표처리된 건은 삭제 할수 없습니다.', 16, 1)
	RETURN
END

-- ================================================== DELETE
INSERT INTO CZ_SA_FORWARD_CHARGE_L_LOG
(
	CD_COMPANY,
	CD_PARTNER,
	TP_DELIVERY,
	DT_MONTH,
	SEQ,
	NO_BL,
	NO_REF,
	NO_IO,
	DT_FORWARD,
	AM_CHARGE,
	AM_ETC,
	AM_VAT_WEEK,
	AM_WEEK,
	AM_CHARGE_MONTH,
	AM_ETC_MONTH,
	AM_VAT_MONTH,
	AM_VAT_TARGET,
	AM_WFG,
	AM_MONTH,
	AM_TAX_MONTH,
	AM_FULL,
	RT_DC,
	RT_DC_IV,
	AM_IV,
	AM_TAX,
	WEIGHT,
	ZONE,
	RT_FSC,
	AM_ZONE,
	DT_TAX_MONTH,
	SEQ_TAX_MONTH,
	NM_NOTE,
	NO_MDOCU,
	DC_RMK,
	ID_INSERT,
	DTS_INSERT,
	ID_UPDATE,
	DTS_UPDATE,
	ID_DELETE,
	DTS_DELETE
)
SELECT A.CD_COMPANY,
	   A.CD_PARTNER,
	   A.TP_DELIVERY,
	   A.DT_MONTH,
	   A.SEQ,
	   A.NO_BL,
	   A.NO_REF,
	   A.NO_IO,
	   A.DT_FORWARD,
	   A.AM_CHARGE,
	   A.AM_ETC,
	   A.AM_VAT_WEEK,
	   A.AM_WEEK,
	   A.AM_CHARGE_MONTH,
	   A.AM_ETC_MONTH,
	   A.AM_VAT_MONTH,
	   A.AM_VAT_TARGET,
	   A.AM_WFG,
	   A.AM_MONTH,
	   A.AM_TAX_MONTH,
	   A.AM_FULL,
	   A.RT_DC,
	   A.RT_DC_IV,
	   A.AM_IV,
	   A.AM_TAX,
	   A.WEIGHT,
	   A.ZONE,
	   A.RT_FSC,
	   A.AM_ZONE,
	   A.DT_TAX_MONTH,
	   A.SEQ_TAX_MONTH,
	   A.NM_NOTE,
	   A.NO_MDOCU,
	   A.DC_RMK,
	   A.ID_INSERT,
	   A.DTS_INSERT,
	   A.ID_UPDATE,
	   A.DTS_UPDATE,
	   @P_ID_USER AS ID_DELETE,
	   NEOE.SF_SYSDATE(GETDATE()) AS DTS_DELETE
FROM CZ_SA_FORWARD_CHARGE_L A 
JOIN OPENXML (@DOC, '/XML/D', 2) 
        WITH (CD_COMPANY	NVARCHAR(7),
			  CD_PARTNER	NVARCHAR(20),
			  TP_DELIVERY	NVARCHAR(4),
			  DT_MONTH		NVARCHAR(6),
			  SEQ			INT) B 
ON A.CD_COMPANY = B.CD_COMPANY 
AND A.CD_PARTNER = B.CD_PARTNER
AND A.TP_DELIVERY = B.TP_DELIVERY
AND A.DT_MONTH = B.DT_MONTH
AND A.SEQ = B.SEQ

DELETE A 
FROM CZ_SA_FORWARD_CHARGE_L A 
JOIN OPENXML (@DOC, '/XML/D', 2) 
        WITH (CD_COMPANY	NVARCHAR(7),
			  CD_PARTNER	NVARCHAR(20),
			  TP_DELIVERY	NVARCHAR(4),
			  DT_MONTH		NVARCHAR(6),
			  SEQ			INT) B 
ON A.CD_COMPANY = B.CD_COMPANY 
AND A.CD_PARTNER = B.CD_PARTNER
AND A.TP_DELIVERY = B.TP_DELIVERY
AND A.DT_MONTH = B.DT_MONTH
AND A.SEQ = B.SEQ
-- ================================================== INSERT
INSERT INTO CZ_SA_FORWARD_CHARGE_L 
(
	CD_COMPANY,
	CD_PARTNER,
	TP_DELIVERY,
	DT_MONTH,
	SEQ,
	NO_BL,
	NO_REF,
	NO_IO,
	DT_FORWARD,
	AM_CHARGE,
	AM_ETC,
	AM_VAT_WEEK,
	AM_WEEK,
	AM_CHARGE_MONTH,
	AM_ETC_MONTH,
	AM_VAT_MONTH,
	AM_VAT_TARGET,
	AM_WFG,
	AM_MONTH,
	AM_TAX_MONTH,
	AM_FULL,
	RT_DC,
	RT_DC_IV,
	AM_IV,
	AM_TAX,
	WEIGHT,
	ZONE,
	RT_FSC,
	AM_ZONE,
	DT_TAX_MONTH,
	SEQ_TAX_MONTH,
	NM_NOTE,
	DC_RMK,
	ID_INSERT,
	DTS_INSERT
)
SELECT CD_COMPANY,
	   CD_PARTNER,
	   TP_DELIVERY,
	   DT_MONTH,
	   SEQ,
	   NO_BL,
	   NO_REF,
	   NO_IO,
	   DT_FORWARD,
	   AM_CHARGE,
	   AM_ETC,
	   AM_VAT_WEEK,
	   AM_WEEK,
	   AM_CHARGE_MONTH,
	   AM_ETC_MONTH,
	   AM_VAT_MONTH,
	   AM_VAT_TARGET,
	   AM_WFG,
	   AM_MONTH,
	   AM_TAX_MONTH,
	   AM_FULL,
	   RT_DC,
	   RT_DC_IV,
	   AM_IV,
	   AM_TAX,
	   WEIGHT,
	   ZONE,
	   RT_FSC,
	   AM_ZONE,
	   DT_TAX_MONTH,
	   SEQ_TAX_MONTH,
	   NM_NOTE,
	   DC_RMK,
       @P_ID_USER, 
       NEOE.SF_SYSDATE(GETDATE()) 
  FROM OPENXML (@DOC, '/XML/I', 2) 
          WITH (CD_COMPANY			NVARCHAR(7), 
			    CD_PARTNER			NVARCHAR(20),
				TP_DELIVERY			NVARCHAR(4),
				DT_MONTH			NVARCHAR(6),
				SEQ					INT,
				NO_BL				NVARCHAR(20),
				NO_REF				NVARCHAR(300),
				NO_IO				NVARCHAR(20),
				DT_FORWARD			NVARCHAR(8),
				AM_CHARGE			NUMERIC(18, 4),
				AM_ETC				NUMERIC(18, 4),
				AM_VAT_WEEK			NUMERIC(18, 4),
				AM_WEEK				NUMERIC(18, 4),
				AM_CHARGE_MONTH     NUMERIC(18, 4),
			    AM_ETC_MONTH		NUMERIC(18, 4),
			    AM_VAT_MONTH		NUMERIC(18, 4),
				AM_VAT_TARGET		NUMERIC(18, 4),
				AM_WFG				NUMERIC(18, 4),
			    AM_MONTH			NUMERIC(18, 4),
				AM_TAX_MONTH	    NUMERIC(18, 4),
				AM_FULL				NUMERIC(18, 4),
				RT_DC				NUMERIC(18, 4),
				RT_DC_IV			NUMERIC(18, 4),
				AM_IV				NUMERIC(18, 4),
				AM_TAX				NUMERIC(18, 4),
				WEIGHT				NUMERIC(18, 2),
				ZONE				INT,
				AM_ZONE				NUMERIC(18, 4),
				RT_FSC				NUMERIC(18, 4),
				DT_TAX_MONTH		NVARCHAR(6),
				SEQ_TAX_MONTH		INT,
				NM_NOTE				NVARCHAR(100),
				DC_RMK				NVARCHAR(500))
-- ================================================== UPDATE
UPDATE A
SET A.NO_BL = B.NO_BL,
	A.NO_REF = B.NO_REF,
	A.NO_IO = B.NO_IO,
	A.DT_FORWARD = B.DT_FORWARD,
	A.AM_CHARGE = B.AM_CHARGE,
	A.AM_ETC = B.AM_ETC,
	A.AM_VAT_WEEK = B.AM_VAT_WEEK,
	A.AM_WEEK = B.AM_WEEK,
    A.AM_CHARGE_MONTH = B.AM_CHARGE_MONTH,
	A.AM_ETC_MONTH = B.AM_ETC_MONTH,
    A.AM_VAT_MONTH = B.AM_VAT_MONTH,
	A.AM_VAT_TARGET = B.AM_VAT_TARGET,
	A.AM_WFG = B.AM_WFG,
	A.AM_MONTH = B.AM_MONTH,
	A.AM_TAX_MONTH = B.AM_TAX_MONTH,
	A.AM_FULL = B.AM_FULL,
	A.RT_DC = B.RT_DC,
	A.RT_DC_IV = B.RT_DC_IV,
	A.AM_IV = B.AM_IV,
	A.AM_TAX = B.AM_TAX,
	A.DT_TAX_MONTH = B.DT_TAX_MONTH,
	A.SEQ_TAX_MONTH = B.SEQ_TAX_MONTH,
	A.NM_NOTE = B.NM_NOTE,
	A.ZONE = B.ZONE,
	A.DC_RMK = B.DC_RMK,
	A.ID_UPDATE = @P_ID_USER,
	A.DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE())
FROM CZ_SA_FORWARD_CHARGE_L A
JOIN OPENXML (@DOC, '/XML/U', 2) 
        WITH (CD_COMPANY		NVARCHAR(7), 
			  CD_PARTNER		NVARCHAR(20),
			  TP_DELIVERY		NVARCHAR(4),
			  DT_MONTH			NVARCHAR(6),
			  SEQ				INT,
			  NO_BL				NVARCHAR(20),
			  NO_REF		    NVARCHAR(300),
			  NO_IO				NVARCHAR(20),
			  DT_FORWARD		NVARCHAR(8),
			  AM_CHARGE			NUMERIC(18, 4),
			  AM_ETC			NUMERIC(18, 4),
			  AM_VAT_WEEK		NUMERIC(18, 4),
			  AM_WEEK			NUMERIC(18, 4),
			  AM_CHARGE_MONTH   NUMERIC(18, 4),
			  AM_ETC_MONTH		NUMERIC(18, 4),
			  AM_VAT_MONTH		NUMERIC(18, 4),
			  AM_VAT_TARGET		NUMERIC(18, 4),
			  AM_WFG			NUMERIC(18, 4),
			  AM_MONTH			NUMERIC(18, 4),
			  AM_TAX_MONTH		NUMERIC(18, 4),
			  AM_FULL			NUMERIC(18, 4),
			  RT_DC				NUMERIC(18, 4),
			  RT_DC_IV			NUMERIC(18, 4),
			  AM_IV				NUMERIC(18, 4),
			  AM_TAX			NUMERIC(18, 4),
			  DT_TAX_MONTH		NVARCHAR(6),
			  SEQ_TAX_MONTH		INT,
			  NM_NOTE			NVARCHAR(100),
			  ZONE				INT,
			  DC_RMK		    NVARCHAR(500)) B
ON B.CD_COMPANY = A.CD_COMPANY 
AND B.CD_PARTNER = A.CD_PARTNER
AND B.TP_DELIVERY = A.TP_DELIVERY
AND B.DT_MONTH = A.DT_MONTH
AND B.SEQ = A.SEQ

EXEC SP_XML_REMOVEDOCUMENT @DOC 

GO