USE [NEOE]
GO

/****** Object:  Table [NEOE].[CZ_SA_BUSINESS_TRIP_EMP]    Script Date: 2020-01-15 오후 5:21:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [NEOE].[CZ_SA_BUSINESS_TRIP_EMP](
	[CD_COMPANY] [nvarchar](7) NOT NULL,
	[NO_BIZ_TRIP] [nvarchar](20) NOT NULL,
	[NO_INDEX] [numeric](18, 0) NOT NULL,
	[CD_COMPANY_EMP] [nvarchar](7) NULL,
	[NO_EMP] [nvarchar](10) NULL,
	[ID_INSERT] [nvarchar](15) NULL,
	[DTS_INSERT] [nvarchar](14) NULL,
	[ID_UPDATE] [nvarchar](15) NULL,
	[DTS_UPDATE] [nvarchar](14) NULL,
 CONSTRAINT [PK_CZ_SA_BUSINESS_TRIP_EMP] PRIMARY KEY CLUSTERED 
(
	[CD_COMPANY] ASC,
	[NO_BIZ_TRIP] ASC,
	[NO_INDEX] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


