USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_GIM_REG_L_S]    Script Date: 2016-01-11 오후 7:20:51 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER PROCEDURE [NEOE].[SP_CZ_SA_GIM_REG_L_S]
(
    @P_CD_COMPANY       NVARCHAR(7),  --회사  
    @P_DT_IO_FROM       NCHAR(8),   --수불일자FROM  
    @P_DT_IO_TO         NCHAR(8),   --수불일자TO  
    @P_DT_LIMIT_FROM    NCHAR(8),   --납기일자FROM  
    @P_DT_LIMIT_TO      NCHAR(8),   --납기일자TO  
    @P_CD_PARTNER       NVARCHAR(20),  --거래처  
    @P_NO_EMP           NVARCHAR(10),  --사번  
    @P_FG_TRANS         NVARCHAR(3),  --거래구분  
    @P_YN_RETURN        NVARCHAR(1),  --출고구분(반품유무)  
    @P_CD_QTIOTP        NVARCHAR(3),  --출고형태  
    @P_MULTI_SALEORG    NVARCHAR(4000), --영업조직(멀티)
    @P_MULTI_SALEGRP    NVARCHAR(4000),
    @P_CD_PJT			NVARCHAR(20),   --프로젝트 2011.04.05 추가
    @P_CD_PARTNER_GRP   NVARCHAR(10), 
    @P_CD_PARTNER_GRP_2 NVARCHAR(10), 
    @P_CD_USERDEF1      NVARCHAR(4), 
    @P_CD_USERDEF2      NVARCHAR(4), 
    @P_NO_IO            NVARCHAR(20),    --수불번호
    @P_NO_SO            NVARCHAR(20)    = NULL
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

/* FG_TRANS			--거래구분
 * QT_IO			--수불수량
 * QT_UNIT_MM		--수불재고수량
 * CD_UNIT_MM		--재고단위
 * YN_AM			--유무환구분
 * NO_ISURCV		--의뢰번호
 * NO_PSO_MGMT		--수주번호
 * NO_PSOLINE_MGMT	--수주항번
 * NO_IO_MGMT		--반품수불번호
 * QT_RETURN		--반품의뢰수량
 */

SELECT	'N' S,
	    L.CD_COMPANY,
		L.NO_IO,
		L.NO_IOLINE,
		L.CD_ITEM,
		P.NM_ITEM,
		P.STND_ITEM,
		L.FG_TRANS,
		MS.NM_SL,
		(CASE P.FG_SERNO WHEN '003' THEN 'S/N' WHEN '002' THEN 'LOT' ELSE '' END) FG_MNG,
		L.QT_IO,
		P.UNIT_IM,
		L.QT_UNIT_MM,
		L.CD_UNIT_MM,
		L.AM,
		L.VAT,
		L.QT_CLS,
		L.YN_AM,
		MJ.NM_QTIOTP,
		L.NO_ISURCV,
		L.NO_PSO_MGMT,
		L.NO_PSOLINE_MGMT,
		L.NO_IO_MGMT,
		L.QT_RETURN,
		L.CD_QTIOTP,
		L.FG_IO,
		SL.STA_SO,
		L.UM,
		L.UM_EX,
		L.AM_EX,
		L.CD_PJT,
		SP.NM_PROJECT,
		H.DT_IO,
		H.YN_RETURN,
		H.DC_RMK,
		MP.LN_PARTNER,
		ME.NM_KOR,
		GL.GI_PARTNER,
		MP2.LN_PARTNER AS LN_GI_PARTNER,
		L.CD_PLANT,
		L.CD_SL,
		L.QT_GOOD_INV, 
        P.FG_SERNO, 
        MI.NM_ITEMGRP, 
        P.CD_ZONE, 
        SL.DT_DUEDATE,
        NEOE.FN_MA_GET_CODEDTL_NM_SYSDEF(@P_CD_COMPANY, 'MA_B000005', L.CD_EXCH) AS NM_EXCH,
        L.DC_RMK AS DC_RMK_L,
        P.MAT_ITEM,
        SL.FG_USE2,
        SL.NO_PO_PARTNER,
        SL.NO_POLINE_PARTNER,
        SH.TXT_USERDEF4 SOH_TXT_USERDEF4,
        L.TP_UM_TAX, 
        L.UMVAT_GI,
        L.ID_MEMO,
        L.CD_WBS,
        L.NO_SHARE,
        L.NO_ISSUE,
        L.DC_RMK1,
        L.DC_RMK2
FROM	MM_QTIO L
		JOIN MM_QTIOH H ON L.CD_COMPANY = H.CD_COMPANY AND L.NO_IO = H.NO_IO
		LEFT JOIN MA_PITEM P ON L.CD_COMPANY = P.CD_COMPANY AND L.CD_PLANT = P.CD_PLANT AND L.CD_ITEM = P.CD_ITEM
		LEFT JOIN SA_SOL SL ON L.CD_COMPANY = SL.CD_COMPANY AND L.NO_PSO_MGMT = SL.NO_SO AND L.NO_PSOLINE_MGMT = SL.SEQ_SO
		LEFT JOIN SA_SOH SH ON L.CD_COMPANY = SH.CD_COMPANY AND L.NO_PSO_MGMT = SH.NO_SO 
		LEFT JOIN SA_GIRL GL ON L.CD_COMPANY = GL.CD_COMPANY AND L.NO_ISURCV = GL.NO_GIR AND L.NO_ISURCVLINE = GL.SEQ_GIR
		LEFT JOIN MA_SL MS ON L.CD_COMPANY = MS.CD_COMPANY AND L.CD_PLANT = MS.CD_PLANT AND L.CD_SL = MS.CD_SL
		LEFT JOIN MM_EJTP MJ ON L.CD_COMPANY = MJ.CD_COMPANY AND L.CD_QTIOTP = MJ.CD_QTIOTP
		LEFT JOIN SA_PROJECTH SP ON L.CD_COMPANY = SP.CD_COMPANY AND L.CD_PJT = SP.NO_PROJECT
		LEFT JOIN MA_PARTNER MP ON H.CD_COMPANY = MP.CD_COMPANY AND H.CD_PARTNER = MP.CD_PARTNER
		LEFT JOIN MA_PARTNER MP2 ON GL.CD_COMPANY = MP2.CD_COMPANY AND GL.GI_PARTNER = MP2.CD_PARTNER
		LEFT JOIN MA_EMP ME ON H.CD_COMPANY = ME.CD_COMPANY AND H.NO_EMP = ME.NO_EMP
        LEFT JOIN MA_ITEMGRP MI ON P.CD_COMPANY = MI.CD_COMPANY AND P.GRP_ITEM = MI.CD_ITEMGRP    --품목군
        LEFT JOIN MA_PARTNER_SUB MB ON MB.CD_COMPANY = H.CD_COMPANY AND MB.CD_PARTNER = H.CD_PARTNER
        LEFT JOIN MA_SALEGRP MSG ON L.CD_COMPANY = MSG.CD_COMPANY AND L.CD_GROUP = MSG.CD_SALEGRP
WHERE (ISNULL(@P_CD_COMPANY, '') = '' OR L.CD_COMPANY = @P_CD_COMPANY)
AND	L.NO_IO = @P_NO_IO
AND	(L.FG_TRANS = @P_FG_TRANS OR @P_FG_TRANS ='' OR @P_FG_TRANS IS NULL)
AND	(L.CD_QTIOTP = @P_CD_QTIOTP OR @P_CD_QTIOTP = '' OR @P_CD_QTIOTP IS NULL)
AND (@P_MULTI_SALEGRP IS NULL OR @P_MULTI_SALEGRP = '' OR L.CD_GROUP IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_MULTI_SALEGRP)))
AND (@P_MULTI_SALEORG IS NULL OR @P_MULTI_SALEORG = '' OR MSG.CD_SALEORG IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_MULTI_SALEORG)))
AND (L.CD_PJT = @P_CD_PJT OR @P_CD_PJT = '' OR @P_CD_PJT IS NULL)	-- 프로젝트 2011.04.05 추가 
AND L.FG_PS = '2'     --출고
--AND	L.FG_IO IN ('010','041','042') --판매출고, 판매반품, 판매반품정리
AND (MP.CD_PARTNER_GRP = @P_CD_PARTNER_GRP OR @P_CD_PARTNER_GRP = '' OR @P_CD_PARTNER_GRP IS NULL)
AND (MP.CD_PARTNER_GRP_2 = @P_CD_PARTNER_GRP_2 OR @P_CD_PARTNER_GRP_2 = '' OR @P_CD_PARTNER_GRP_2 IS NULL)
AND (MB.CD_USERDEF1 = @P_CD_USERDEF1 OR @P_CD_USERDEF1 = '' OR @P_CD_USERDEF1 IS NULL)
AND (MB.CD_USERDEF2 = @P_CD_USERDEF2 OR @P_CD_USERDEF2 = '' OR @P_CD_USERDEF2 IS NULL)
--ORDER  BY L.NO_IO, L.NO_IOLINE

GO