USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_GIR_HISTORYL_S]    Script Date: 2017-01-12 오후 2:55:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO






ALTER PROCEDURE [NEOE].[SP_CZ_SA_GIR_HISTORYL_S]  
(  
    @P_CD_COMPANY   NVARCHAR(7),
	@P_TP_GIR		NVARCHAR(4),
	@P_NO_GIR		NVARCHAR(20),
	@P_NO_HST		NUMERIC(5, 0),
	@P_NO_SO		NVARCHAR(20),
	@P_CD_ITEM		NVARCHAR(20)
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT GL.CD_COMPANY,
	   GL.TP_GIR,
	   GL.NO_GIR,
	   GL.NO_HST,
	   GL.SEQ_GIR,
	   GL.NO_SO,
	   GL.SEQ_SO,
	   QL.NO_DSP,
	   QL.CD_ITEM_PARTNER,
	   QL.NM_ITEM_PARTNER,
	   GL.CD_ITEM,
	   MI.NM_ITEM,
	   GL.UNIT,
	   GL.QT_GIR,
	   ISNULL(GL.QT_GIR_STOCK, 0) AS QT_GIR_STOCK,
	   GL.QT_GI,
	   GL.YN_ADD_STOCK 
FROM CZ_SA_GIRL_LOG GL
LEFT JOIN MA_PITEM MI ON MI.CD_COMPANY = GL.CD_COMPANY AND MI.CD_ITEM = GL.CD_ITEM
LEFT JOIN CZ_SA_QTNL QL ON QL.CD_COMPANY = GL.CD_COMPANY AND QL.NO_FILE = GL.NO_SO AND QL.NO_LINE = GL.SEQ_SO
WHERE (ISNULL(@P_CD_COMPANY, '') = '' OR GL.CD_COMPANY = @P_CD_COMPANY)
AND GL.TP_GIR = @P_TP_GIR
AND GL.NO_GIR = @P_NO_GIR
AND GL.NO_HST = @P_NO_HST
AND (ISNULL(@P_NO_SO, '') = '' OR GL.NO_SO = @P_NO_SO)
AND (ISNULL(@P_CD_ITEM, '') = '' OR GL.CD_ITEM = @P_CD_ITEM)

GO

