USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_MA_ALTERNATIVE_ITEM_REGH_S]    Script Date: 2017-02-07 오후 3:36:10 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER PROCEDURE [NEOE].[SP_CZ_MA_ALTERNATIVE_ITEM_REGH_S2]
(
	@P_NO_PRIME					NVARCHAR(20),
	@P_NO_ALTERNATIVE			NVARCHAR(20),
	@P_NO_PLATE_PRIME			NVARCHAR(20),
	@P_NO_PLATE_ALTERNATIVE		NVARCHAR(20),
	@P_UCODE_PRIME				NVARCHAR(20),
	@P_UCODE_ALTERNATIVE		NVARCHAR(20),
	@P_CD_ITEM_PRIME			NVARCHAR(20),
	@P_CD_ITEM_ALTERNATIVE	    NVARCHAR(20)
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

IF EXISTS (SELECT 1 
		   FROM SYSOBJECTS 
		   WHERE NAME = 'CZ_EZCODE_PITEM')
BEGIN
	CREATE TABLE #EZCODE
	(
		EZCODE		NVARCHAR(20),
		NO_IMO		NVARCHAR(10),
		NO_ENGINE	INT,
		NO_PLATE	NVARCHAR(100)
	)
	
	CREATE NONCLUSTERED INDEX EZCODE ON #EZCODE (EZCODE, NO_IMO, NO_ENGINE, NO_PLATE)
	
	CREATE TABLE #ITEM
	(
		EZCODE		NVARCHAR(20),
		CD_ITEM		NVARCHAR(10)
	)
	
	CREATE NONCLUSTERED INDEX ITEM ON #ITEM (EZCODE, CD_ITEM)
	
	INSERT INTO #EZCODE
	SELECT EH.KCODE,
		   EH.NO_IMO,
		   EH.NO_ENGINE,
		   EH.NO_PLATE 
	FROM (SELECT EH.KCODE,
		  	     EH.NO_IMO,
	             EH.NO_ENGINE,
	             EH.NO_PLATE,
	             ROW_NUMBER() OVER (PARTITION BY EH.KCODE ORDER BY EH.NO_IMO) AS IDX
	FROM CZ_MA_HULL_ENGINE_ITEM EH) EH
	WHERE EH.IDX = 1
	
	INSERT INTO #ITEM
	SELECT EP.EZCODE,
		   MAX(EP.CD_ITEM) AS CD_ITEM
	FROM CZ_EZCODE_PITEM EP
	WHERE EP.CD_COMPANY = 'K100'
	AND EXISTS (SELECT 1 
				FROM MA_PITEM MI
				WHERE MI.CD_COMPANY = EP.CD_COMPANY
				AND MI.CD_ITEM = EP.CD_ITEM
				AND MI.YN_USE = 'Y')
	GROUP BY EP.EZCODE
	
	SELECT AI.NO_PRIME,
	       EI.NO_PLATE AS NO_PLATE_PRIME,
		   EI.NM_PLATE AS NM_PLATE_PRIME,
		   EI.UCODE AS UCODE_PRIME,
		   MI.CD_ITEM AS CD_ITEM_PRIME,
		   AI.NO_MATERIAL,
		   EI1.NO_PLATE AS NO_PLATE_MATERIAL,
		   EI1.NM_PLATE AS NM_PLATE_MATERIAL,
		   EI1.UCODE AS UCODE_MATERIAL,
		   MI1.CD_ITEM AS CD_ITEM_MATERIAL,
		   AI.NO_ALTERNATIVE,
		   EI2.NO_PLATE AS NO_PLATE_ALTERNATIVE,
		   EI2.NM_PLATE AS NM_PLATE_ALTERNATIVE,
		   EI2.UCODE AS UCODE_ALTERNATIVE,
		   MI2.CD_ITEM AS CD_ITEM_ALTERNATIVE,
		   AI.ID_INSERT,
		   (SELECT NM_USER FROM MA_USER WHERE CD_COMPANY = 'K100' AND ID_USER = AI.ID_INSERT) AS NM_INSERT,
		   AI.DTS_INSERT 
	FROM CZ_MA_ALTERNATIVE_ITEM AI
	LEFT JOIN #EZCODE EH ON EH.EZCODE = AI.NO_PRIME
	LEFT JOIN CZ_MA_HULL_ENGINE_ITEM EI ON EI.NO_IMO = EH.NO_IMO AND EI.NO_ENGINE = EH.NO_ENGINE AND EI.NO_PLATE = EH.NO_PLATE
	LEFT JOIN #EZCODE EH1 ON EH1.EZCODE = AI.NO_MATERIAL
	LEFT JOIN CZ_MA_HULL_ENGINE_ITEM EI1 ON EI1.NO_IMO = EH1.NO_IMO AND EI1.NO_ENGINE = EH1.NO_ENGINE AND EI1.NO_PLATE = EH1.NO_PLATE
	LEFT JOIN #EZCODE EH2 ON EH2.EZCODE = AI.NO_ALTERNATIVE
	LEFT JOIN CZ_MA_HULL_ENGINE_ITEM EI2 ON EI2.NO_IMO = EH2.NO_IMO AND EI2.NO_ENGINE = EH2.NO_ENGINE AND EI2.NO_PLATE = EH2.NO_PLATE
	LEFT JOIN #ITEM MI ON MI.EZCODE = AI.NO_PRIME
	LEFT JOIN #ITEM MI1 ON MI1.EZCODE = AI.NO_MATERIAL
	LEFT JOIN #ITEM MI2 ON MI2.EZCODE = AI.NO_ALTERNATIVE
	WHERE (ISNULL(@P_NO_PRIME, '') = '' OR AI.NO_PRIME = @P_NO_PRIME)
	AND (ISNULL(@P_NO_ALTERNATIVE, '') = '' OR (AI.NO_ALTERNATIVE = @P_NO_ALTERNATIVE OR AI.NO_MATERIAL = @P_NO_ALTERNATIVE))
	AND (ISNULL(@P_NO_PLATE_PRIME, '') = '' OR EI.NO_PLATE = @P_NO_PLATE_PRIME)
	AND (ISNULL(@P_NO_PLATE_ALTERNATIVE, '') = '' OR (EI1.NO_PLATE = @P_NO_PLATE_ALTERNATIVE OR EI2.NO_PLATE = @P_NO_PLATE_ALTERNATIVE))
	AND (ISNULL(@P_UCODE_PRIME, '') = '' OR EI.UCODE = @P_UCODE_PRIME)
	AND (ISNULL(@P_UCODE_ALTERNATIVE, '') = '' OR (EI1.UCODE = @P_UCODE_ALTERNATIVE OR EI2.UCODE = @P_UCODE_ALTERNATIVE))
	AND (ISNULL(@P_CD_ITEM_PRIME, '') = '' OR MI.CD_ITEM = @P_CD_ITEM_PRIME)
	AND (ISNULL(@P_CD_ITEM_ALTERNATIVE, '') = '' OR (MI1.CD_ITEM = @P_CD_ITEM_ALTERNATIVE OR MI2.CD_ITEM = @P_CD_ITEM_ALTERNATIVE))

	DROP TABLE #EZCODE
	DROP TABLE #ITEM
END

GO