USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_MA_ALTERNATIVE_ITEM_REGH_S]    Script Date: 2017-02-07 오후 3:36:10 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER PROCEDURE [NEOE].[SP_CZ_MA_ALTERNATIVE_ITEM_REGH_S1]
(
	@P_NO_PRIME					NVARCHAR(20),
	@P_NO_ALTERNATIVE			NVARCHAR(20),
	@P_NO_PLATE_PRIME			NVARCHAR(20),
	@P_NO_PLATE_ALTERNATIVE		NVARCHAR(20),
	@P_UCODE_PRIME				NVARCHAR(20),
	@P_UCODE_ALTERNATIVE		NVARCHAR(20),
	@P_CD_ITEM_PRIME			NVARCHAR(20),
	@P_CD_ITEM_ALTERNATIVE	    NVARCHAR(20)
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

IF EXISTS (SELECT 1 
		   FROM SYSOBJECTS 
		   WHERE NAME = 'CZ_EZCODE_PITEM')
BEGIN
	CREATE TABLE #PRIME
	(
		NO_PRIME	NVARCHAR(20)
	)
	
	CREATE NONCLUSTERED INDEX PRIME ON #PRIME (NO_PRIME)
	
	CREATE TABLE #EZCODE
	(
		EZCODE		NVARCHAR(20),
		NO_IMO		NVARCHAR(10),
		NO_ENGINE	INT,
		NO_PLATE	NVARCHAR(100)
	)
	
	CREATE NONCLUSTERED INDEX EZCODE ON #EZCODE (EZCODE, NO_IMO, NO_ENGINE, NO_PLATE)
	
	CREATE TABLE #ITEM
	(
		EZCODE		NVARCHAR(20),
		CD_ITEM		NVARCHAR(10)
	)
	
	CREATE NONCLUSTERED INDEX ITEM ON #ITEM (EZCODE, CD_ITEM)

	CREATE TABLE #CZ_MA_HULL_ENGINE_ITEM1
	(
		KCODE	NVARCHAR(20)
	)

	CREATE NONCLUSTERED INDEX KCODE ON #CZ_MA_HULL_ENGINE_ITEM1 (KCODE)

	CREATE TABLE #CZ_MA_HULL_ENGINE_ITEM2
	(
		KCODE	NVARCHAR(20)
	)

	CREATE NONCLUSTERED INDEX KCODE ON #CZ_MA_HULL_ENGINE_ITEM2 (KCODE)

	INSERT INTO #CZ_MA_HULL_ENGINE_ITEM1
	SELECT KCODE
	FROM CZ_MA_HULL_ENGINE_ITEM
	WHERE (ISNULL(@P_NO_PLATE_ALTERNATIVE, '') <> '' AND NO_PLATE = @P_NO_PLATE_ALTERNATIVE)

	INSERT INTO #CZ_MA_HULL_ENGINE_ITEM2
	SELECT KCODE
	FROM CZ_MA_HULL_ENGINE_ITEM
	WHERE (ISNULL(@P_UCODE_ALTERNATIVE, '') <> '' AND UCODE = @P_UCODE_ALTERNATIVE)

	INSERT INTO #PRIME
	SELECT AI.NO_PRIME
	FROM CZ_MA_ALTERNATIVE_ITEM AI
	WHERE (ISNULL(@P_NO_PRIME, '') = '' OR AI.NO_PRIME = @P_NO_PRIME)
	AND (ISNULL(@P_NO_ALTERNATIVE, '') = '' OR AI.NO_MATERIAL = @P_NO_ALTERNATIVE)
	AND (ISNULL(@P_NO_PLATE_ALTERNATIVE, '') = '' OR EXISTS (SELECT 1 
														     FROM #CZ_MA_HULL_ENGINE_ITEM1 EH
														     WHERE EH.KCODE = AI.NO_MATERIAL))
	AND (ISNULL(@P_UCODE_ALTERNATIVE, '') = '' OR EXISTS (SELECT 1 
														  FROM #CZ_MA_HULL_ENGINE_ITEM2 EI
														  WHERE EI.KCODE = AI.NO_MATERIAL))
	AND (ISNULL(@P_CD_ITEM_ALTERNATIVE, '') = '' OR EXISTS (SELECT 1 
															FROM CZ_EZCODE_PITEM EP
															WHERE EP.CD_COMPANY = 'K100'
															AND EP.EZCODE = AI.NO_MATERIAL
															AND EP.CD_ITEM = @P_CD_ITEM_ALTERNATIVE
															AND EXISTS (SELECT 1 
																	    FROM MA_PITEM MI
																	    WHERE MI.CD_COMPANY = EP.CD_COMPANY
																	    AND MI.CD_ITEM = EP.CD_ITEM
																	    AND MI.YN_USE = 'Y')))
	GROUP BY AI.NO_PRIME
	
	INSERT INTO #EZCODE
	SELECT EH.KCODE,
		   EH.NO_IMO,
		   EH.NO_ENGINE,
		   EH.NO_PLATE 
	FROM (SELECT EH.KCODE,
		  	     EH.NO_IMO,
	             EH.NO_ENGINE,
	             EH.NO_PLATE,
	             ROW_NUMBER() OVER (PARTITION BY EH.KCODE ORDER BY EH.NO_IMO) AS IDX
	FROM CZ_MA_HULL_ENGINE_ITEM EH
	WHERE EXISTS (SELECT 1 
				  FROM #PRIME
				  WHERE NO_PRIME = EH.KCODE)) EH
	WHERE EH.IDX = 1
	
	INSERT INTO #ITEM
	SELECT EP.EZCODE,
		   MAX(EP.CD_ITEM) AS CD_ITEM
	FROM CZ_EZCODE_PITEM EP
	WHERE EP.CD_COMPANY = 'K100'
	AND EXISTS (SELECT 1 
				FROM #PRIME
				WHERE NO_PRIME = EP.EZCODE)
	AND EXISTS (SELECT 1 
				FROM MA_PITEM MI
				WHERE MI.CD_COMPANY = EP.CD_COMPANY
				AND MI.CD_ITEM = EP.CD_ITEM
				AND MI.YN_USE = 'Y')
	GROUP BY EP.EZCODE
	
	SELECT 'N' AS S,
		   AI.NO_PRIME,
		   EH.NO_PLATE AS NO_PLATE_PRIME,
		   EI.NM_PLATE AS NM_PLATE_PRIME,
		   EI.UCODE AS UCODE_PRIME,
		   EP.CD_ITEM AS CD_ITEM_PRIME,
		   AI1.CNT_ITEM,
		   AI1.ID_INSERT,
		   (SELECT NM_USER FROM MA_USER WHERE CD_COMPANY = 'K100' AND ID_USER = AI1.ID_INSERT) AS NM_INSERT, 
		   AI1.DTS_INSERT
	FROM #PRIME AI
	LEFT JOIN (SELECT AI.NO_PRIME,
			   		  AI.ID_INSERT,
			   		  AI.DTS_INSERT,
					  COUNT(DISTINCT AI.NO_MATERIAL) AS CNT_ITEM
			   FROM CZ_MA_ALTERNATIVE_ITEM AI
			   GROUP BY AI.NO_PRIME, AI.ID_INSERT, AI.DTS_INSERT) AI1
	ON AI1.NO_PRIME = AI.NO_PRIME
	LEFT JOIN #EZCODE EH ON EH.EZCODE = AI.NO_PRIME
	LEFT JOIN CZ_MA_HULL_ENGINE_ITEM EI ON EI.NO_IMO = EH.NO_IMO AND EI.NO_ENGINE = EH.NO_ENGINE AND EI.NO_PLATE = EH.NO_PLATE
	LEFT JOIN #ITEM EP ON EP.EZCODE = AI.NO_PRIME
	WHERE (ISNULL(@P_NO_PLATE_PRIME, '') = '' OR EI.NO_PLATE = @P_NO_PLATE_PRIME)
	AND (ISNULL(@P_UCODE_PRIME, '') = '' OR EI.UCODE = @P_UCODE_PRIME)
	AND (ISNULL(@P_CD_ITEM_PRIME, '') = '' OR EP.CD_ITEM = @P_CD_ITEM_PRIME)
	
	DROP TABLE #PRIME
	DROP TABLE #EZCODE
	DROP TABLE #ITEM
	DROP TABLE #CZ_MA_HULL_ENGINE_ITEM1	
	DROP TABLE #CZ_MA_HULL_ENGINE_ITEM2
END

GO