USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_MA_ALTERNATIVE_ITEM_REGL_S]    Script Date: 2017-02-07 오후 3:51:41 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




ALTER PROCEDURE [NEOE].[SP_CZ_MA_ALTERNATIVE_ITEM_REGL_S]
(
	@P_NO_PRIME					NVARCHAR(20),
	@P_NO_ALTERNATIVE			NVARCHAR(20),
	@P_NO_PLATE_ALTERNATIVE		NVARCHAR(20),
	@P_UCODE_ALTERNATIVE		NVARCHAR(20),
	@P_CD_ITEM_ALTERNATIVE		NVARCHAR(20)
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

SELECT 'N' AS S,
	   AI.NO_PRIME,
	   AI.NO_ALTERNATIVE,
	   MAX(EI.NO_PLATE) AS NO_PLATE_ALTERNATIVE,
	   MAX(EI.NM_PLATE) AS NM_PLATE_ALTERNATIVE,
	   MAX(EI.UCODE) AS UCODE_ALTERNATIVE,
	   MAX(EP.CD_ITEM) AS CD_ITEM_ALTERNATIVE,
	   AI.ID_INSERT,
	   MAX(MU.NM_USER) AS NM_INSERT,
	   AI.DTS_INSERT
FROM CZ_MA_ALTERNATIVE_ITEM AI
LEFT JOIN MA_USER MU ON CD_COMPANY = 'K100' AND ID_USER = AI.ID_INSERT
LEFT JOIN CZ_MA_HULL_ENGINE_ITEM EI ON EI.KCODE = AI.NO_ALTERNATIVE AND EI.YN_UPLOAD = 'Y'
LEFT JOIN CZ_EZCODE_PITEM EP ON EP.CD_COMPANY = 'K100' AND EP.EZCODE = AI.NO_ALTERNATIVE AND EXISTS (SELECT 1 
		   																							 FROM MA_PITEM MI
		   																							 WHERE MI.CD_COMPANY = EP.CD_COMPANY
		   																							 AND MI.CD_ITEM = EP.CD_ITEM
		   																							 AND MI.YN_USE = 'Y')
WHERE AI.NO_PRIME = @P_NO_PRIME
AND (ISNULL(@P_NO_ALTERNATIVE, '') = '' OR (AI.NO_MATERIAL = @P_NO_ALTERNATIVE OR AI.NO_ALTERNATIVE = @P_NO_ALTERNATIVE))
AND (ISNULL(@P_NO_PLATE_ALTERNATIVE, '') = '' OR (EI.NO_PLATE = @P_NO_PLATE_ALTERNATIVE OR EXISTS (SELECT 1
																								   FROM CZ_MA_HULL_ENGINE_ITEM EH
																								   WHERE EH.KCODE = AI.NO_MATERIAL
																								   AND EH.NO_PLATE = @P_NO_PLATE_ALTERNATIVE)))
AND (ISNULL(@P_UCODE_ALTERNATIVE, '') = '' OR (EI.UCODE = @P_UCODE_ALTERNATIVE OR EXISTS (SELECT 1 
																						  FROM CZ_MA_HULL_ENGINE_ITEM EI
																						  WHERE EI.KCODE = AI.NO_MATERIAL
																						  AND EI.UCODE = @P_UCODE_ALTERNATIVE)))
AND (ISNULL(@P_CD_ITEM_ALTERNATIVE, '') = '' OR (EP.CD_ITEM = @P_CD_ITEM_ALTERNATIVE OR EXISTS (SELECT 1 
																								FROM CZ_EZCODE_PITEM EP
																								WHERE EP.EZCODE = AI.NO_MATERIAL
																								AND EP.CD_ITEM = @P_CD_ITEM_ALTERNATIVE)))
GROUP BY AI.NO_PRIME, AI.NO_ALTERNATIVE, AI.ID_INSERT, AI.ID_INSERT, AI.DTS_INSERT

GO

