USE [NEOE]
GO

/****** Object:  Table [NEOE].[CZ_PR_MATCHING_GRADE]    Script Date: 2021-12-03 ¿ÀÈÄ 2:50:09 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [NEOE].[CZ_PR_MATCHING_GRADE](
	[CD_COMPANY] [nvarchar](7) NOT NULL,
	[CD_CLEAR_GRP] [nvarchar](4) NOT NULL,
	[CD_GRADE] [nvarchar](1) NOT NULL,
	[IDX_SPEC] [int] NOT NULL,
	[QT_SPEC] [numeric](18, 4) NULL,
	[ID_INSERT] [nvarchar](10) NULL,
	[DTS_INSERT] [nvarchar](14) NULL,
	[ID_UPDATE] [nvarchar](10) NULL,
	[DTS_UPDATE] [nvarchar](14) NULL,
 CONSTRAINT [PK_CZ_PR_MATCHING_GRADE] PRIMARY KEY CLUSTERED 
(
	[CD_COMPANY] ASC,
	[CD_GRADE] ASC,
	[CD_CLEAR_GRP] ASC,
	[IDX_SPEC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


