USE [NEOE]
GO

/****** Object:  Table [NEOE].[CZ_MA_FORWARD_EXCHANGE]    Script Date: 2016-05-10 오전 10:13:10 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [NEOE].[CZ_MA_FORWARD_EXCHANGE](
	[CD_COMPANY] [nvarchar](7) NOT NULL,
	[CD_BANK] [nvarchar](3) NOT NULL,
	[DT_EXCH] [nvarchar](8) NOT NULL,
	[DT_CONTRACT] [nvarchar](8) NULL,
	[RT_EXCH] [numeric](11, 4) NULL,
	[AM_EX] [numeric](17, 4) NULL,
	[AM] [numeric](17, 4) NULL,
	[SWAP] [numeric](11, 4) NULL,
	[COMMISSION] [numeric](11, 4) NULL,
	[ID_INSERT] [nvarchar](15) NULL,
	[DTS_INSERT] [nvarchar](14) NULL,
	[ID_UPDATE] [nvarchar](15) NULL,
	[DTS_UPDATE] [nvarchar](14) NULL,
 CONSTRAINT [PK_CZ_MA_FORWARD_EXCHANGE] PRIMARY KEY CLUSTERED 
(
	[CD_COMPANY] ASC,
	[CD_BANK] ASC,
	[DT_EXCH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


