USE [NEOE]
GO

/****** Object:  Table [NEOE].[CZ_SA_AUTO_MAIL_FILE]    Script Date: 2022-06-20 ¿ÀÀü 10:03:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [NEOE].[CZ_SA_AUTO_MAIL_FILE](
	[CD_COMPANY] [nvarchar](7) NOT NULL,
	[NO_SO] [nvarchar](20) NOT NULL,
	[YN_EXCLUDE] [nvarchar](1) NULL,
	[YN_INCLUDE] [nvarchar](1) NULL,
	[ID_INSERT] [nvarchar](10) NULL,
	[DTS_INSERT] [nvarchar](14) NULL,
	[ID_UPDATE] [nvarchar](10) NULL,
	[DTS_UPDATE] [nvarchar](14) NULL,
 CONSTRAINT [PK_CZ_SA_AUTO_MAIL_FILE] PRIMARY KEY CLUSTERED 
(
	[CD_COMPANY] ASC,
	[NO_SO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


