USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_PU_STS_BATCH_REGH_U]    Script Date: 2017-02-06 오후 6:46:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER PROCEDURE [NEOE].[SP_CZ_PU_STS_BATCH_REGH_U]
(
	@P_CD_COMPANY			NVARCHAR(7),
	@P_NO_GIREQ				NVARCHAR(20),
	@P_ID_PRINT				NVARCHAR(15)
)
AS

DECLARE @V_NO_HST NUMERIC(5, 0)

SELECT @V_NO_HST = (ISNULL(MAX(CNT_PRINT), 0) + 1)
FROM MM_GIREQH
WHERE CD_COMPANY = @P_CD_COMPANY
AND NO_GIREQ = @P_NO_GIREQ

IF ISNULL(@V_NO_HST, 0) = 0
	SET @V_NO_HST = 1

UPDATE MM_GIREQH
SET CNT_PRINT = @V_NO_HST,
	LAST_PRINT_ID = @P_ID_PRINT
WHERE CD_COMPANY = @P_CD_COMPANY
AND NO_GIREQ = @P_NO_GIREQ


GO

