USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_PU_STS_BATCH_REG_D]    Script Date: 2017-01-26 오후 1:17:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_PU_STS_BATCH_REG_GI_D]        
(
	@P_CD_COMPANY		NVARCHAR(7),
	@P_NO_IO			NVARCHAR(20),
	@P_NO_ISURCVLINE	NUMERIC(5, 0),	
	@P_ID_DELETE		NVARCHAR(15) = NULL
)        
AS

/*2010.03.15 LOG데이터 생성 크라제 때문...*/
INSERT INTO MM_QTIO_PU_LOG
(
	NO_IO,
	NO_IOLINE,
	CD_COMPANY,
	CD_PLANT,
	CD_BIZAREA,
	CD_SL,
	CD_SECTION,
	CD_BIN,
	DT_IO,
	NO_ISURCV, 
	NO_ISURCVLINE,
	NO_PSO_MGMT,
	NO_PSOLINE_MGMT,
	FG_PS,
	YN_PURSALE,
	FG_TPIO,
	FG_IO,
	CD_QTIOTP,
	FG_TRANS,
	FG_TAX, 
	CD_PARTNER,
	CD_ITEM,
	QT_IO,
	QT_RETURN,
	QT_TRANS_INV,
	QT_INSP_INV,
	QT_REJECT_INV,
	QT_GOOD_INV,
	CD_EXCH,
	RT_EXCH, 
	UM_EX,
	AM_EX,
	UM,
	AM,
	QT_CLS,
	AM_CLS,
	VAT,
	VAT_CLS,
	FG_TAXP,
	UM_STOCK, 
	UM_EVAL,
	YN_AM,
	CD_PJT,
	AM_DISTRIBU,
	RT_CUSTOMS,
	AM_CUSTOMS,
	NO_LC,
	NO_LCLINE,
	QT_IMSEAL,
	QT_EXLC, 
    GI_PARTNER,
	NO_EMP,
	CD_GROUP,
	NO_IO_MGMT,
	NO_IOLINE_MGMT,
	CD_BIZAREA_RCV,
	CD_PLANT_RCV,
	CD_SL_REF,
	CD_SECTION_REF, 
    CD_BIN_REF,
	BILL_PARTNER,
	CD_UNIT_MM,
	QT_UNIT_MM,
	UM_EX_PSO,
	QT_CLS_MM,
	QT_RETURN_MM,
	CD_WC,
	CD_OP,
	CD_WCOP, 
	AM_EVAL,
	FG_LC_OPEN,
	QT_INV,
	NO_WORK,
	CD_CC,
	DC_RMK,
	CD_WORKITEM,
	ID_DELETE,
	DTS_DELETE
)
SELECT NO_IO,
	   NO_IOLINE,
	   CD_COMPANY,
	   CD_PLANT,
	   CD_BIZAREA,
	   CD_SL,
	   CD_SECTION,
	   CD_BIN,
	   DT_IO,
	   NO_ISURCV, 
	   NO_ISURCVLINE,
	   NO_PSO_MGMT,
	   NO_PSOLINE_MGMT,
	   FG_PS,
	   YN_PURSALE,
	   FG_TPIO,
	   FG_IO,
	   CD_QTIOTP,
	   FG_TRANS,
	   FG_TAX, 
	   CD_PARTNER,
	   CD_ITEM,
	   QT_IO,
	   QT_RETURN,
	   QT_TRANS_INV,
	   QT_INSP_INV,
	   QT_REJECT_INV,
	   QT_GOOD_INV,
	   CD_EXCH,
	   RT_EXCH, 
	   UM_EX,
	   AM_EX,
	   UM,
	   AM,
	   QT_CLS,
	   AM_CLS,
	   VAT,
	   VAT_CLS,
	   FG_TAXP,
	   UM_STOCK, 
	   UM_EVAL,
	   YN_AM,
	   CD_PJT,
	   AM_DISTRIBU,
	   RT_CUSTOMS,
	   AM_CUSTOMS,
	   NO_LC,
	   NO_LCLINE,
	   QT_IMSEAL,
	   QT_EXLC, 
	   GI_PARTNER,
	   NO_EMP,
	   CD_GROUP,
	   NO_IO_MGMT,
	   NO_IOLINE_MGMT,
	   CD_BIZAREA_RCV,
	   CD_PLANT_RCV,
	   CD_SL_REF,
	   CD_SECTION_REF, 
	   CD_BIN_REF,
	   BILL_PARTNER,
	   CD_UNIT_MM,
	   QT_UNIT_MM,
	   UM_EX_PSO,
	   QT_CLS_MM,
	   QT_RETURN_MM,
	   CD_WC,
	   CD_OP,
	   CD_WCOP, 
	   AM_EVAL,
	   FG_LC_OPEN,
	   QT_INV,
	   NO_WORK,
	   CD_CC,
	   DC_RMK,
	   CD_WORKITEM, 
	   @P_ID_DELETE,
	   NEOE.SF_SYSDATE(GETDATE())  
FROM MM_QTIO 
WHERE CD_COMPANY = @P_CD_COMPANY 
AND NO_IO = @P_NO_IO
AND (ISNULL(@P_NO_ISURCVLINE, 0) = 0 OR NO_ISURCVLINE = @P_NO_ISURCVLINE)
/*****************************************************************************/

-- 수불 라인 삭제      
DELETE MM_QTIO 
WHERE CD_COMPANY = @P_CD_COMPANY 
AND NO_IO = @P_NO_IO
AND (ISNULL(@P_NO_ISURCVLINE, 0) = 0 OR NO_ISURCVLINE = @P_NO_ISURCVLINE)
     
IF NOT EXISTS (SELECT 1 
			   FROM MM_QTIO
			   WHERE CD_COMPANY = @P_CD_COMPANY 
			   AND NO_IO = @P_NO_IO)
BEGIN
	INSERT INTO MM_QTIOH_PU_LOG 
	(
		CD_COMPANY,
		NO_IO,
		CD_PLANT,
		CD_PARTNER,
		FG_TRANS, 
		YN_RETURN,
		DT_IO,
		GI_PARTNER,
		CD_DEPT,
		NO_EMP, 
		DC_RMK,
		DTS_INSERT,
		ID_INSERT,
		DTS_UPDATE,
		ID_UPDATE, 
		CD_QTIOTP,
		ETRADE_KEY,
		ETRADE_SYS,
		FILE_PATH_MNG,
		ID_DELETE,
		DTS_DELETE
	)
	SELECT CD_COMPANY,
		   NO_IO,
		   CD_PLANT,
		   CD_PARTNER,
		   FG_TRANS, 
		   YN_RETURN,
		   DT_IO,
		   GI_PARTNER,
		   CD_DEPT,
		   NO_EMP, 
		   DC_RMK,
		   DTS_INSERT,
		   ID_INSERT,
		   DTS_UPDATE,
		   ID_UPDATE, 
		   CD_QTIOTP,
		   ETRADE_KEY,
		   ETRADE_SYS,
		   FILE_PATH_MNG,
		   @P_ID_DELETE,
		   NEOE.SF_SYSDATE(GETDATE())
	FROM MM_QTIOH 
	WHERE CD_COMPANY = @P_CD_COMPANY   
	AND NO_IO = @P_NO_IO

	-- 수불 헤더 삭제      
	DELETE MM_QTIOH 
	WHERE CD_COMPANY = @P_CD_COMPANY
	AND NO_IO = @P_NO_IO	
END

UPDATE SB
SET SB.QT_GI = (ISNULL(GL.QT_GIR_STOCK_OLD, 0) + ISNULL(QL.QT_GI, 0))
FROM CZ_SA_STOCK_BOOK SB
LEFT JOIN (SELECT GL.CD_COMPANY, GL.NO_SO, GL.SEQ_SO,
				 SUM(CASE WHEN GL.YN_GI_STOCK = 'Y' THEN GL.QT_GIR_STOCK ELSE 0 END) AS QT_GIR_STOCK_OLD 
           FROM SA_GIRL GL
           WHERE GL.QT_GIR_STOCK > 0
		   AND GL.QT_GI > 0
           GROUP BY GL.CD_COMPANY, GL.NO_SO, GL.SEQ_SO) GL
ON GL.CD_COMPANY = SB.CD_COMPANY AND GL.NO_SO = SB.NO_FILE AND GL.SEQ_SO = SB.NO_LINE
LEFT JOIN (SELECT CD_COMPANY, NO_SO, SEQ_SO, 
				  SUM(QT_GI) AS QT_GI
		   FROM MM_GIREQL
		   WHERE CD_SL = 'SL02'
		   AND CD_GRSL = 'SL03'
		   AND QT_GI > 0
		   GROUP BY CD_COMPANY, NO_SO, SEQ_SO) QL
ON QL.CD_COMPANY = SB.CD_COMPANY AND QL.NO_SO = SB.NO_FILE AND QL.SEQ_SO = SB.NO_LINE
WHERE SB.CD_COMPANY = @P_CD_COMPANY
AND EXISTS (SELECT 1 
			FROM MM_QTIO_PU_LOG OL
			WHERE OL.CD_COMPANY = SB.CD_COMPANY
			AND OL.NO_IO = @P_NO_IO
			AND (ISNULL(@P_NO_ISURCVLINE, 0) = 0 OR OL.NO_ISURCVLINE = @P_NO_ISURCVLINE)
			AND OL.NO_PSO_MGMT = SB.NO_FILE
			AND OL.NO_PSOLINE_MGMT = SB.NO_LINE) 
     
GO