USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_PR_ROUT_INSP_SUB_XML]    Script Date: 2016-11-30 오후 5:22:08 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




ALTER PROCEDURE [NEOE].[SP_CZ_PR_ROUT_INSP_SUB_XML] 
(
	@P_XML			XML, 
	@P_ID_USER		NVARCHAR(10), 
    @DOC			INT = NULL
) 
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

EXEC SP_XML_PREPAREDOCUMENT @DOC OUTPUT, @P_XML 

DECLARE @V_ERRMSG NVARCHAR(255)   -- ERROR 메시지

BEGIN TRAN SP_CZ_PR_ROUT_INSP_SUB_XML
BEGIN TRY

-- ================================================== DELETE
SELECT * INTO #XML_D
FROM OPENXML (@DOC, '/XML/D', 2) 
        WITH (CD_COMPANY	NVARCHAR(7),
			  CD_PLANT		NVARCHAR(7),
			  CD_ITEM		NVARCHAR(20),
			  NO_OPPATH		NVARCHAR(3),
			  CD_OP		    NVARCHAR(4),
			  CD_WCOP		NVARCHAR(7),
			  NO_INSP		NUMERIC(4, 0))

IF EXISTS(SELECT 1
		  FROM PR_WO WO
		  JOIN PR_WO_ROUT WR ON WR.CD_COMPANY = WO.CD_COMPANY AND WR.CD_PLANT = WO.CD_PLANT AND WR.NO_WO = WO.NO_WO
		  JOIN CZ_PR_WO_INSP WI ON WI.CD_COMPANY = WR.CD_COMPANY AND WI.NO_WO = WR.NO_WO AND WI.NO_LINE = WR.NO_LINE
		  WHERE EXISTS (SELECT 1 
		                FROM #XML_D XD
		                WHERE XD.CD_COMPANY = WO.CD_COMPANY
		                AND XD.CD_PLANT = WO.CD_PLANT
		                AND XD.CD_ITEM = WO.CD_ITEM
		                AND XD.NO_OPPATH = WO.PATN_ROUT
		                AND XD.CD_OP = WR.CD_OP
		                AND XD.CD_WCOP = WR.CD_WCOP
		                AND XD.NO_INSP = WI.NO_INSP))
BEGIN
	SELECT @V_ERRMSG = '작업 진행 중인 측정항목은 삭제 할 수 없습니다.'                     
    GOTO ERROR
END

DELETE A 
FROM CZ_PR_ROUT_INSP A 
JOIN #XML_D B 
ON A.CD_COMPANY = B.CD_COMPANY
AND A.CD_PLANT = B.CD_PLANT
AND A.CD_ITEM = B.CD_ITEM
AND A.NO_OPPATH = B.NO_OPPATH
AND A.CD_OP = B.CD_OP
AND A.CD_WCOP = B.CD_WCOP
AND A.NO_INSP = B.NO_INSP

-- ================================================== INSERT
INSERT INTO CZ_PR_ROUT_INSP 
(
	CD_COMPANY,
	CD_PLANT,
	CD_ITEM,
	NO_OPPATH,
	CD_OP,
	CD_WCOP,
	NO_INSP,
	DC_ITEM,
	CD_MEASURE,
	DC_MEASURE,
	DC_LOCATION,
	DC_SPEC,
	QT_MIN,
	QT_MAX,
	TP_DATA,
	CNT_INSP,
	YN_CERT,
	YN_SAMPLING,
	YN_USE,
	YN_ASSY,
	CD_CLEAR_GRP,
	DC_RMK,
	ID_INSERT,
	DTS_INSERT
)
SELECT CD_COMPANY,
	   CD_PLANT,
	   CD_ITEM,
	   NO_OPPATH,
	   CD_OP,
	   CD_WCOP,
	   NO_INSP,
	   DC_ITEM,
	   CD_MEASURE,
	   DC_MEASURE,
	   DC_LOCATION,
	   DC_SPEC,
	   QT_MIN,
	   QT_MAX,
	   TP_DATA,
	   CNT_INSP,
	   YN_CERT,
	   YN_SAMPLING,
	   YN_USE,
	   YN_ASSY,
	   CD_CLEAR_GRP,
	   DC_RMK,
       @P_ID_USER, 
       NEOE.SF_SYSDATE(GETDATE()) 
FROM OPENXML (@DOC, '/XML/I', 2) 
        WITH (CD_COMPANY	NVARCHAR(7),
			  CD_PLANT		NVARCHAR(7),
			  CD_ITEM		NVARCHAR(20),
			  NO_OPPATH		NVARCHAR(3),
			  CD_OP			NVARCHAR(4),
			  CD_WCOP		NVARCHAR(7),
			  NO_INSP		NUMERIC(4, 0),
			  DC_ITEM		NVARCHAR(30),
			  CD_MEASURE	NVARCHAR(4),
			  DC_MEASURE	NVARCHAR(10),
			  DC_LOCATION	NVARCHAR(20),
			  DC_SPEC		NVARCHAR(30),
			  QT_MIN		NUMERIC(17, 4),
			  QT_MAX		NUMERIC(17, 4),
			  TP_DATA		NVARCHAR(3),
			  CNT_INSP		TINYINT,
			  YN_CERT		NVARCHAR(1),
			  YN_SAMPLING	NVARCHAR(1),
			  YN_USE		NVARCHAR(1),
			  YN_ASSY		NVARCHAR(1),
			  CD_CLEAR_GRP  NVARCHAR(4),
			  DC_RMK		NVARCHAR(200))

-- ================================================== UPDATE
SELECT * INTO #XML_U
FROM OPENXML (@DOC, '/XML/U', 2) 
        WITH (CD_COMPANY	NVARCHAR(7),
			  CD_PLANT		NVARCHAR(7),
			  CD_ITEM		NVARCHAR(20),
			  NO_OPPATH		NVARCHAR(3),
			  CD_OP			NVARCHAR(4),
			  CD_WCOP		NVARCHAR(7),
			  NO_INSP		NUMERIC(4, 0),
			  DC_ITEM		NVARCHAR(30),
			  CD_MEASURE	NVARCHAR(4),
			  DC_MEASURE	NVARCHAR(10),
			  DC_LOCATION	NVARCHAR(20),
			  DC_SPEC		NVARCHAR(30),
			  QT_MIN		NUMERIC(17, 4),
			  QT_MAX		NUMERIC(17, 4),
			  TP_DATA		NVARCHAR(3),
			  CNT_INSP		TINYINT,
			  YN_CERT		NVARCHAR(1),
			  YN_SAMPLING   NVARCHAR(1),
			  YN_USE		NVARCHAR(1),
			  YN_ASSY		NVARCHAR(1),
			  CD_CLEAR_GRP  NVARCHAR(4),
			  DC_RMK		NVARCHAR(200))

IF EXISTS(SELECT 1
		  FROM PR_WO WO
		  JOIN PR_WO_ROUT WR ON WR.CD_COMPANY = WO.CD_COMPANY AND WR.CD_PLANT = WO.CD_PLANT AND WR.NO_WO = WO.NO_WO
		  JOIN CZ_PR_WO_INSP WI ON WI.CD_COMPANY = WR.CD_COMPANY AND WI.NO_WO = WR.NO_WO AND WI.NO_LINE = WR.NO_LINE
		  WHERE EXISTS (SELECT 1 
		                FROM #XML_U XD
		                WHERE XD.CD_COMPANY = WO.CD_COMPANY
		                AND XD.CD_PLANT = WO.CD_PLANT
		                AND XD.CD_ITEM = WO.CD_ITEM
		                AND XD.NO_OPPATH = WO.PATN_ROUT
		                AND XD.CD_OP = WR.CD_OP
		                AND XD.CD_WCOP = WR.CD_WCOP
		                AND XD.NO_INSP = WI.NO_INSP))
BEGIN
	SELECT @V_ERRMSG = '작업 진행 중인 측정항목은 수정 할 수 없습니다.'                     
    GOTO ERROR
END

UPDATE A 
   SET A.DC_ITEM = B.DC_ITEM,
	   A.CD_MEASURE = B.CD_MEASURE,
	   A.DC_MEASURE = B.DC_MEASURE,
	   A.DC_LOCATION = B.DC_LOCATION,
	   A.DC_SPEC = B.DC_SPEC,
	   A.QT_MIN = B.QT_MIN,
	   A.QT_MAX = B.QT_MAX,
	   A.TP_DATA = B.TP_DATA,
	   A.CNT_INSP = B.CNT_INSP,
	   A.YN_CERT = B.YN_CERT,
	   A.YN_SAMPLING = B.YN_SAMPLING,
	   --A.YN_USE = B.YN_USE, 화면에서 수정함
	   A.YN_ASSY = B.YN_ASSY,
	   A.CD_CLEAR_GRP = B.CD_CLEAR_GRP,
	   A.DC_RMK = B.DC_RMK,
	   A.ID_UPDATE = @P_ID_USER, 
	   A.DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE())
FROM CZ_PR_ROUT_INSP A 
JOIN #XML_U B 
ON A.CD_COMPANY = B.CD_COMPANY
AND A.CD_PLANT = B.CD_PLANT
AND A.CD_ITEM = B.CD_ITEM
AND A.NO_OPPATH = B.NO_OPPATH
AND A.CD_OP = B.CD_OP
AND A.CD_WCOP = B.CD_WCOP
AND A.NO_INSP = B.NO_INSP

DROP TABLE #XML_D
DROP TABLE #XML_U

EXEC SP_XML_REMOVEDOCUMENT @DOC 

COMMIT TRAN SP_CZ_PR_ROUT_INSP_SUB_XML

END TRY
BEGIN CATCH
	ROLLBACK TRAN SP_CZ_PR_ROUT_INSP_SUB_XML
	SELECT @V_ERRMSG = ERROR_MESSAGE()
	GOTO ERROR
END CATCH

RETURN
ERROR: 
RAISERROR(@V_ERRMSG, 16, 1)
ROLLBACK TRAN SP_CZ_PR_ROUT_INSP_SUB_XML

GO

