USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_CONTRACT_RPT_STA]    Script Date: 2015-10-14 오후 2:15:07 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


  
ALTER PROCEDURE [NEOE].[SP_CZ_SA_CONTRACT_RPT_STA]    
(    
    @P_CD_COMPANY       NVARCHAR(7),
    @P_NO_SO            NVARCHAR(20),
    @P_STA_SO           NVARCHAR(3),
	@P_NO_CONTRACT      NVARCHAR(40),
	@P_DT_CONTRACT      NVARCHAR(8),
	@P_YN_CHARGE		NVARCHAR(1) = 'N',
    @P_ID_UPDATE        NVARCHAR(15)
)    
AS    
    
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

DECLARE @V_COUNT  INT, 
        @V_QT_GIR NUMERIC(17, 4)

IF (@P_STA_SO = 'O') -- 미정으로 변경시    
BEGIN
	SELECT @V_COUNT = COUNT(1)    
    FROM TR_LCEXL    
    WHERE CD_COMPANY = @P_CD_COMPANY    
    AND NO_SO = @P_NO_SO    
    
    IF (@V_COUNT > 0)
    BEGIN     
       RAISERROR ('TR_M000089', 18, 1) --이미 LC등록 혹은 LC의뢰되어 수정, 삭제가 불가능합니다.    
       RETURN    
    END    
    
    SELECT @V_QT_GIR = ISNULL(SUM(QT_GIR), 0)    
    FROM SA_SOL    
    WHERE CD_COMPANY = @P_CD_COMPANY    
    AND  NO_SO = @P_NO_SO    
    
    IF (@V_QT_GIR > 0)     --의뢰수량이 0보다 큰면    
    BEGIN    
       RAISERROR ('SA_M000117', 18, 1) --이미 출고의뢰되어 수정, 삭제가 불가능합니다.    
       RETURN    
    END    
END    
    
UPDATE SA_SOL    
SET STA_SO = @P_STA_SO,
    DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE()),  
    ID_UPDATE   = @P_ID_UPDATE,   
    STA_SO_HST  = STA_SO,    
    DTS_STA_HST = ISNULL(DTS_UPDATE, DTS_INSERT),  
    ID_STA_HST  = ISNULL(ID_UPDATE, ID_INSERT)    
WHERE CD_COMPANY = @P_CD_COMPANY    
AND NO_SO = @P_NO_SO

UPDATE SA_SOH 
SET STA_SO = @P_STA_SO,
	NO_CONTRACT = @P_NO_CONTRACT,
	DT_CONTRACT = @P_DT_CONTRACT,
	ID_UPDATE = @P_ID_UPDATE,
	DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE())        
WHERE CD_COMPANY = @P_CD_COMPANY    
AND NO_SO = @P_NO_SO

EXEC SP_CZ_SA_AUTO_MAIL_VESSEL_MSG @P_CD_COMPANY, @P_NO_SO

IF @P_YN_CHARGE = 'N'
BEGIN
	IF @P_STA_SO = 'O'
	BEGIN
		UPDATE CZ_MA_WORKFLOWH
		SET YN_DONE = 'N',
			DTS_DONE = NULL,
			UPDATE_HIST = 'SP_CZ_SA_CONTRACT_RPT_STA',
			ID_UPDATE = @P_ID_UPDATE,
			DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE())
		WHERE CD_COMPANY = @P_CD_COMPANY
		AND TP_STEP = '11'
		AND NO_KEY = @P_NO_SO

		DELETE FROM CZ_MA_WORKFLOWH
		WHERE CD_COMPANY = @P_CD_COMPANY
		AND TP_STEP = '12'
		AND NO_KEY = @P_NO_SO
	
		DELETE FROM CZ_MA_WORKFLOWH
		WHERE CD_COMPANY = @P_CD_COMPANY
		AND TP_STEP = '13'
		AND NO_KEY = @P_NO_SO

		DELETE FROM CZ_SA_CONTRACT_RPTH
		WHERE CD_COMPANY = @P_CD_COMPANY
		AND NO_SO = @P_NO_SO
	END
	ELSE IF @P_STA_SO = 'R'
	BEGIN
		EXEC SP_CZ_MA_WORKFLOW_DONE @P_CD_COMPANY, '10', @P_NO_SO, @P_ID_UPDATE
		EXEC SP_CZ_MA_WORKFLOW_DONE @P_CD_COMPANY, '11', @P_NO_SO, @P_ID_UPDATE
		EXEC SP_CZ_MA_WORKFLOW_NEXT_STEP @P_CD_COMPANY, '12', @P_NO_SO, @P_ID_UPDATE, ''
		EXEC SP_CZ_MA_WORKFLOW_NEXT_STEP @P_CD_COMPANY, '13', @P_NO_SO, @P_ID_UPDATE, ''
	END	
END

GO