USE [NEOE]
GO
/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_CONTRACT_RPTL_S]    Script Date: 2016-01-05 오후 6:05:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_SA_CONTRACT_RPTL_S] 
(
	@P_CD_COMPANY		NVARCHAR(7),    
	@P_KEY				NVARCHAR(20),
	@P_NO_EMP			NVARCHAR(10),
	@P_NO_CONTRACT		NVARCHAR(40),
	@P_CD_PARTNER		NVARCHAR(20),
	@P_CD_PO_PARTNER	NVARCHAR(20),
	@P_GRP_ITEM			NVARCHAR(20)
)
AS
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT SL.NO_SO,
	   SL.SEQ_SO,
	   SL.CD_ITEM_PARTNER,
	   SL.NM_ITEM_PARTNER,
	   SL.NO_DSP,
	   SL.NM_SUBJECT,
	   SL.YN_DSP_RMK,
	   SL.DC_RMK,
	   SL.CD_ITEM, 
	   SL.NM_ITEM, 
	   SL.UNIT_SO,
	   SL.QT_GI,
	   SL.QT_GIR,
	   SL.QT_LC,
	   SL.NO_DSP_BOM,
	   SL.NM_SUBJECT_BOM,
	   SL.CD_ITEM_PARTNER_BOM,
	   SL.NM_ITEM_PARTNER_BOM,
	   SL.CD_SUPPLIER,
	   SL.LN_SUPPLIER,
	   SL.NO_PO_PARTNER,
	   SL.NO_POLINE_PARTNER, 
	   SL.FG_PAYMENT,
	   MC1.NM_SYSDEF AS NM_FG_PAYMENT,
	   SL.CD_PLANT,
	   SL.TP_BUSI,
	   SL.YN_ATP,
	   SL.DT_DUEDATE,
	   SL.CD_SL,
	   SL.AM_VAT,
	   SL.YN_GULL,
	   SL.GRP_ITEM,
	   IG.NM_ITEMGRP,
	   ISNULL(SL.QT_SO, 0) AS QT_SO,
	   (CASE WHEN TP.RET = 'Y' THEN -ISNULL(SL.UM_SO, 0) 
							   ELSE ISNULL(SL.UM_SO, 0) END) AS UM_SO,
	   (CASE WHEN TP.RET = 'Y' THEN -ISNULL(SL.AM_SO, 0) 
							   ELSE ISNULL(SL.AM_SO, 0) END) AS AM_SO,
	   ((CASE WHEN TP.RET = 'Y' THEN -ISNULL(SL.AM_SO, 0) 
							    ELSE ISNULL(SL.AM_SO, 0) END)  * ISNULL(SL.RT_BOM, 0)) AS AM_SO_BOM,
	   ((CASE WHEN TP.RET = 'Y' THEN -ISNULL(SL.AM_WONAMT, 0) 
								ELSE ISNULL(SL.AM_WONAMT, 0) END) * ISNULL(SL.RT_BOM, 0)) AS AM_WONAMT,
	   ISNULL(SL.RT_DC_SO, 0) AS RT_DC_SO,
	   ISNULL(SL.QT_PO_MM, 0) AS QT_PO,
	   (CASE WHEN TP.RET = 'Y' THEN -ISNULL(SL.UM, 0) 
							   ELSE ISNULL(SL.UM, 0) END) AS UM_PO,
	   (CASE WHEN TP.RET = 'Y' THEN -ISNULL(SL.AM, 0) 
							   ELSE ISNULL(SL.AM, 0) END) AS AM_PO,
	   ISNULL(SL.RT_DC_PO, 0) AS RT_DC_PO,
	   (((CASE WHEN TP.RET = 'Y' THEN -ISNULL(SL.AM_WONAMT, 0) 
								 ELSE ISNULL(SL.AM_WONAMT, 0) END)  * ISNULL(SL.RT_BOM, 0)) - (CASE WHEN TP.RET = 'Y' THEN -ISNULL(SL.AM, 0) 
																													  ELSE ISNULL(SL.AM, 0) END)) AS PROFIT,
	   (CASE WHEN ((CASE WHEN TP.RET = 'Y' THEN -ISNULL(SL.AM_WONAMT, 0) 
										   ELSE ISNULL(SL.AM_WONAMT, 0) END) * ISNULL(SL.RT_BOM, 0)) = 0 THEN 0 
																										 ELSE ROUND(((1 - ((CASE WHEN TP.RET = 'Y' THEN -ISNULL(SL.AM, 0) 
																																				   ELSE ISNULL(SL.AM, 0) END) / ((CASE WHEN TP.RET = 'Y' THEN -ISNULL(SL.AM_WONAMT, 0) 
																																																		 ELSE ISNULL(SL.AM_WONAMT, 0) END)  * ISNULL(SL.RT_BOM, 0)))) * 100), 2) END) AS RT_PROFIT,
	   (CASE WHEN TP.RET = 'Y' THEN -ISNULL(SL.AM_WONAMT, 0) 
							   ELSE ISNULL(SL.AM_WONAMT, 0) END) AS AM_SO_ALL,
	   ISNULL(SL.AM_PO_ALL, 0) AS AM_PO_ALL,
	   ((CASE WHEN TP.RET = 'Y' THEN -ISNULL(SL.AM_WONAMT, 0) 
							    ELSE ISNULL(SL.AM_WONAMT, 0) END) - ISNULL(SL.AM_PO_ALL, 0)) AS AM_PROFIT_ALL,
	   (CASE WHEN (CASE WHEN TP.RET = 'Y' THEN -ISNULL(SL.AM_WONAMT, 0) 
										  ELSE ISNULL(SL.AM_WONAMT, 0) END) = 0 THEN 0 
																				ELSE ROUND(((1 - (ISNULL(SL.AM_PO_ALL, 0) / (CASE WHEN TP.RET = 'Y' THEN -ISNULL(SL.AM_WONAMT, 0) 
																																				    ELSE ISNULL(SL.AM_WONAMT, 0) END))) * 100), 2) END) AS RT_PROFIT_ALL,
	   ISNULL(SH.RT_EXCH, 0) AS RT_EXCH,
	   SH.CD_PARTNER,
	   SH.CD_EXCH,
	   MC.NM_SYSDEF AS NM_EXCH,
	   RL.DC_RMK AS DC_RMK_CONTRACT
FROM SA_SOH SH
JOIN (SELECT SL.CD_COMPANY,
			 SL.NO_SO,
			 SL.SEQ_SO,
			 SL.CD_ITEM,
			 SL.UNIT_SO,
			 SL.QT_SO,
			 SL.QT_GIR,
			 SL.QT_GI,
			 SL.QT_LC,
			 SL.UM_SO,
			 SL.AM_SO,
			 SL.AM_WONAMT,
			 SL.NO_PO_PARTNER,
			 SL.NO_POLINE_PARTNER,
			 SL.CD_PLANT,
			 SL.TP_BUSI,
			 SL.DT_DUEDATE,
			 SL.CD_SL,
			 SL.AM_VAT,
			 SL.RT_DC AS RT_DC_SO,
			 QL.CD_ITEM_PARTNER,
	         QL.NM_ITEM_PARTNER,
	         QL.NO_DSP,
	         QL.NM_SUBJECT,
	         QL.YN_DSP_RMK,
	         QL.DC_RMK,
			 QL.YN_GULL,
	         QL.GRP_ITEM,
			 QL1.NO_DSP AS NO_DSP_BOM,
	         QL1.NM_SUBJECT AS NM_SUBJECT_BOM,
	         QL1.CD_ITEM_PARTNER AS CD_ITEM_PARTNER_BOM,
	         QL1.NM_ITEM_PARTNER AS NM_ITEM_PARTNER_BOM,
			 MI.NM_ITEM,
			 MI.YN_ATP,
			 PL.QT_PO_MM,
			 PL.UM,
	  		 PL.AM,
			 PL.RT_DC AS RT_DC_PO,
			 PL.FG_PAYMENT,
			 PL.CD_PARTNER AS CD_SUPPLIER,
			 PL.LN_PARTNER AS LN_SUPPLIER,
			 PL1.AM_PO_ALL,
			 (CASE WHEN QL.TP_BOM = 'P' THEN (CASE WHEN PL1.AM_PO_ALL IS NULL OR PL1.AM_PO_ALL = 0 THEN 1 
																			                       ELSE ROUND(ISNULL(PL.AM, 0) / PL1.AM_PO_ALL, 2) END)
									    ELSE (CASE WHEN SL.QT_SO IS NULL OR SL.QT_SO = 0 THEN 1 
																					     ELSE ISNULL(PL.QT_PO_MM, 0) / SL.QT_SO END) END) AS RT_BOM
	  FROM SA_SOL SL
	  JOIN MA_PITEM MI ON MI.CD_COMPANY = SL.CD_COMPANY AND MI.CD_PLANT = SL.CD_PLANT AND MI.CD_ITEM = SL.CD_ITEM
	  LEFT JOIN CZ_SA_QTNL QL ON QL.CD_COMPANY = SL.CD_COMPANY AND QL.NO_FILE = SL.NO_SO AND QL.NO_LINE = SL.SEQ_SO
	  LEFT JOIN (SELECT PL.CD_COMPANY,
	  				    PL.NO_SO,
	  				    PL.NO_SOLINE,
	  				    PL.NO_LINE AS NO_POLINE,
	  				    PL.QT_PO_MM,
	  				    PL.UM,
	  				    PL.AM,
	  				    PL.RT_DC, 
	  				    PH.FG_PAYMENT,
	  				    PH.CD_PARTNER,
	  				    MP.LN_PARTNER
	  			 FROM PU_POH PH 
	  			 LEFT JOIN MA_PARTNER MP ON MP.CD_COMPANY = PH.CD_COMPANY AND MP.CD_PARTNER = PH.CD_PARTNER
				 JOIN PU_POL PL ON PL.CD_COMPANY = PH.CD_COMPANY AND PL.NO_PO = PH.NO_PO
				 WHERE PH.CD_TPPO NOT IN ('1300', '1400', '2300', '2400')
	  			 UNION ALL
	  			 SELECT SB.CD_COMPANY,
	  					SB.NO_FILE AS NO_SO,
	  					SB.NO_LINE AS NO_SOLINE,
	  					SB.NO_LINE AS NO_POLINE,
	  					SB.QT_STOCK AS QT_PO_MM,
	  					SB.UM_KR AS UM,
	  					(SB.UM_KR * SB.QT_STOCK) AS AM,
	  					0 AS RT_DC,
	  					'' AS FG_PAYMENT,
	  					'STOCK' AS CD_PARTNER,
	  					'STOCK' AS LN_PARTNER
	  			 FROM CZ_SA_STOCK_BOOK SB
	  			 WHERE SB.QT_STOCK > 0) PL 
	  ON PL.CD_COMPANY = SL.CD_COMPANY AND PL.NO_SO = SL.NO_SO AND PL.NO_SOLINE = SL.SEQ_SO
	  LEFT JOIN (SELECT PL.CD_COMPANY, PL.NO_SO, PL.NO_SOLINE,
	  		   	        SUM(PL.AM) AS AM_PO_ALL 
	  		     FROM (SELECT CD_COMPANY, NO_SO, NO_SOLINE,
	  		     	          SUM(AM) AS AM
	  		     	   FROM PU_POL 
	  		     	   GROUP BY CD_COMPANY, NO_SO, NO_SOLINE
	  		     	   UNION ALL
	  		     	   SELECT CD_COMPANY, NO_FILE, NO_LINE, 
	  		     	   	      (UM_KR * QT_STOCK) AS AM
	  		     	   FROM CZ_SA_STOCK_BOOK) PL
	  		     GROUP BY PL.CD_COMPANY, PL.NO_SO, PL.NO_SOLINE) PL1
	  ON PL1.CD_COMPANY = SL.CD_COMPANY AND PL1.NO_SO = SL.NO_SO AND PL1.NO_SOLINE = SL.SEQ_SO
	  LEFT JOIN CZ_SA_QTNL QL1 ON QL1.CD_COMPANY = PL.CD_COMPANY AND QL1.NO_FILE = PL.NO_SO AND QL1.NO_LINE = PL.NO_POLINE
	  WHERE (SL.CD_ITEM NOT LIKE 'SD%' OR SL.QT_PO > 0)
	  AND (ISNULL(@P_GRP_ITEM, '') = '' OR QL.GRP_ITEM = @P_GRP_ITEM)
	  AND (ISNULL(@P_CD_PO_PARTNER, '') = '' OR PL.CD_PARTNER = @P_CD_PO_PARTNER)) SL 
ON SL.CD_COMPANY = SH.CD_COMPANY AND SL.NO_SO = SH.NO_SO
LEFT JOIN SA_TPSO TP ON TP.CD_COMPANY = SH.CD_COMPANY AND TP.TP_SO = SH.TP_SO
LEFT JOIN CZ_SA_CONTRACT_RPTL RL ON RL.CD_COMPANY = SL.CD_COMPANY AND RL.NO_SO = SL.NO_SO AND RL.SEQ_SO = SL.SEQ_SO
LEFT JOIN MA_CODEDTL MC ON MC.CD_COMPANY = SH.CD_COMPANY AND MC.CD_FIELD = 'MA_B000005' AND MC.CD_SYSDEF = SH.CD_EXCH
LEFT JOIN MA_CODEDTL MC1 ON MC1.CD_COMPANY = SL.CD_COMPANY AND MC1.CD_FIELD = 'PU_C000014' AND MC1.CD_SYSDEF = SL.FG_PAYMENT
LEFT JOIN MA_ITEMGRP IG ON IG.CD_COMPANY = SL.CD_COMPANY AND IG.USE_YN = 'Y' AND IG.CD_ITEMGRP = SL.GRP_ITEM
WHERE SH.CD_COMPANY = @P_CD_COMPANY
AND SH.NO_SO = @P_KEY
AND (ISNULL(@P_NO_EMP, '') = '' OR SH.NO_EMP = @P_NO_EMP)
AND (ISNULL(@P_NO_CONTRACT, '') = '' OR SH.NO_CONTRACT = @P_NO_CONTRACT) 
AND (ISNULL(@P_CD_PARTNER, '') = '' OR SH.CD_PARTNER = @P_CD_PARTNER)  
ORDER BY SL.CD_COMPANY, SL.NO_SO, SL.NO_DSP

GO