USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_BI_QTN_SEND_DAY_CHART_S6]    Script Date: 2018-11-08 오전 11:54:11 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




ALTER PROCEDURE [NEOE].[SP_CZ_BI_QTN_SEND_DAY_CHART_S6]
(
	@P_CD_COMPANY		NVARCHAR(7),
	@P_DT_START			NVARCHAR(8),
	@P_DT_END			NVARCHAR(8),
	@P_TP_QTN			NVARCHAR(3)
)
AS
 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

WITH WH AS
(
	SELECT WH.CD_COMPANY, WH.NO_KEY,
		   CONVERT(DATETIME, LEFT(WH.DTS_INSERT, 8) + ' ' + SUBSTRING(WH.DTS_INSERT, 9, 2) + ':' + SUBSTRING(WH.DTS_INSERT, 11, 2) + ':' + SUBSTRING(WH.DTS_INSERT, 13, 2)) AS DTS_INSERT,
		   CONVERT(DATETIME, LEFT(WH1.DTS_DONE, 8) + ' ' + SUBSTRING(WH1.DTS_DONE, 9, 2) + ':' + SUBSTRING(WH1.DTS_DONE, 11, 2) + ':' + SUBSTRING(WH1.DTS_DONE, 13, 2)) AS DTS_DONE,
		   (SELECT COUNT(1) 
			FROM MA_CALENDAR
			WHERE CD_COMPANY = WH.CD_COMPANY
			AND FG1_HOLIDAY = 'H'
			AND DT_CAL BETWEEN LEFT(WH.DTS_INSERT, 8) AND LEFT(WH1.DTS_DONE, 8)) AS QT_HOLIDAY
	FROM CZ_MA_WORKFLOWH WH
	LEFT JOIN (SELECT WH.CD_COMPANY, WH.NO_KEY,
					  (CASE WHEN WL.DTS_INSERT IS NULL THEN NULL
						    WHEN WH1.DTS_INSERT IS NULL THEN WH.DTS_DONE
							ELSE WH1.DTS_DONE END) AS DTS_DONE 
			   FROM CZ_MA_WORKFLOWH WH
			   LEFT JOIN (SELECT CD_COMPANY, NO_KEY,
			   			  	     MIN(DTS_INSERT) AS DTS_INSERT
			   			  FROM CZ_MA_WORKFLOWL
			   			  WHERE TP_STEP = '05'
			   			  GROUP BY CD_COMPANY, NO_KEY) WL
			   ON WL.CD_COMPANY = WH.CD_COMPANY AND WL.NO_KEY = WH.NO_KEY
			   LEFT JOIN CZ_MA_WORKFLOWH WH1 ON WH1.CD_COMPANY = WH.CD_COMPANY AND WH1.NO_KEY = WH.NO_KEY AND WH1.TP_STEP = '06'
			   WHERE WH.TP_STEP = '05') WH1 
	ON WH1.CD_COMPANY = WH.CD_COMPANY AND WH1.NO_KEY = WH.NO_KEY
	WHERE WH.CD_COMPANY = @P_CD_COMPANY
	AND WH.TP_STEP = '01'
	AND WH.DTS_INSERT BETWEEN @P_DT_START + '000000' AND @P_DT_END + '999999'
	AND (WH.NO_KEY LIKE 'FB________' OR 
		 WH.NO_KEY LIKE 'DB________' OR
		 WH.NO_KEY LIKE 'SB________' OR
		 WH.NO_KEY LIKE 'NB________' OR
		 WH.NO_KEY LIKE 'NS________' OR
		 WH.NO_KEY LIKE 'DS________' OR
		 WH.NO_KEY LIKE 'A-________' OR
		 WH.NO_KEY LIKE 'D-________' OR
		 WH.NO_KEY LIKE 'N-________')	
),
WH1 AS
(
	SELECT WH.CD_COMPANY,
		   WH.NO_KEY,
		   QH.NO_FILE,
		   QH.YN_CLOSE,
		   ME.NM_KOR AS NM_EMP,
		   ME1.NM_KOR AS NM_EMP_QTN,
		   ME2.NM_KOR AS NM_EMP_STK,
		   (CASE WHEN @P_TP_QTN = '000' THEN QH.CD_SALEGRP ELSE '010900' END) AS CD_SALEGRP,
		   QH.CD_PARTNER,
		   QH.NO_IMO,
		   WH.DTS_DONE,
		   (ISNULL(DATEDIFF(DAY, WH.DTS_INSERT, WH.DTS_DONE), 0) - WH.QT_HOLIDAY) AS DT_QTN
	FROM WH WH
	LEFT JOIN CZ_SA_QTNH QH ON QH.CD_COMPANY = WH.CD_COMPANY AND QH.NO_FILE = WH.NO_KEY
	LEFT JOIN MA_EMP ME ON ME.CD_COMPANY = QH.CD_COMPANY AND ME.NO_EMP = QH.NO_EMP
	LEFT JOIN MA_EMP ME1 ON ME1.CD_COMPANY = QH.CD_COMPANY AND ME1.NO_EMP = QH.NO_EMP_QTN
	LEFT JOIN MA_EMP ME2 ON ME2.CD_COMPANY = QH.CD_COMPANY AND ME2.NO_EMP = QH.NO_EMP_STK
	WHERE (@P_TP_QTN = '000' OR EXISTS (SELECT 1 
										FROM MA_EMP ME
										WHERE ME.CD_COMPANY = QH.CD_COMPANY
										AND ME.NO_EMP = (CASE WHEN @P_TP_QTN = '001' THEN QH.NO_EMP_STK ELSE QH.NO_EMP_QTN END)
										AND ME.CD_DEPT = '010900'))
),
WH2 AS
(
	SELECT WH.CD_COMPANY,
		   WH.NO_KEY,
		   WH.NM_EMP,
		   WH.NM_EMP_QTN,
		   WH.NM_EMP_STK,
		   SG.CD_SALEORG,
		   SG.CD_CC,
		   WH.CD_PARTNER,
		   WH.NO_IMO,
		   (CASE WHEN WH.DT_QTN < 0 THEN 0.0 ELSE WH.DT_QTN END) AS DT_QTN,
		   QL.YN_ENGINE,
		   QL.QT_ITEM,
		   QL.AM_QTN,
		   SH.NO_SO,
		   (CASE WHEN WH.DTS_DONE IS NULL AND SH.NO_SO IS NULL THEN 'N'
				 WHEN (QL.AM_QTN IS NULL OR QL.AM_QTN = 0) AND SH.NO_SO IS NULL THEN 'N'
				 WHEN WH.YN_CLOSE = 'Y' AND SH.NO_SO IS NULL THEN 'N'
				 ELSE 'Y' END) AS YN_DONE,
		   (CASE WHEN @P_TP_QTN = '000' THEN NULL ELSE (SELECT WH1.ID_LOG
													    FROM CZ_MA_WORKFLOWH WH1
													    WHERE WH1.CD_COMPANY = WH.CD_COMPANY
													    AND WH1.NO_KEY = WH.NO_KEY
													    AND WH1.TP_STEP = '21') END) AS CD_SUPPLIER
	FROM WH1 WH
	LEFT JOIN MA_SALEGRP SG ON SG.CD_COMPANY = WH.CD_COMPANY AND SG.CD_SALEGRP = WH.CD_SALEGRP
	LEFT JOIN (SELECT QL.CD_COMPANY, QL.NO_FILE,
					  (CASE WHEN QL.GRP_ITEM IN ('AE', 'HE', 'ME', 'PP', 'TC') THEN 'Y' ELSE 'N' END) YN_ENGINE,
			   	      SUM(1.0) AS QT_ITEM,
					  SUM(AM_KR_S) AS AM_QTN 
			   FROM CZ_SA_QTNL QL
			   GROUP BY QL.CD_COMPANY, QL.NO_FILE,
					    (CASE WHEN QL.GRP_ITEM IN ('AE', 'HE', 'ME', 'PP', 'TC') THEN 'Y' ELSE 'N' END)) QL
	ON QL.CD_COMPANY = WH.CD_COMPANY AND QL.NO_FILE = WH.NO_KEY
	LEFT JOIN SA_SOH SH ON SH.CD_COMPANY = WH.CD_COMPANY AND SH.NO_SO = WH.NO_KEY
	WHERE SG.CD_SALEORG IN ('010301', '020200', '010900')
),
WH3 AS
(
	SELECT WH.CD_COMPANY, ISNULL(WH1.ID_LOG, QL.CD_SUPPLIER) AS CD_SUPPLIER,
		   SUM(1) AS QT_FILE,
		   SUM(QL.QT_ITEM) AS QT_ITEM
	FROM WH
	LEFT JOIN CZ_MA_WORKFLOWH WH1 ON WH1.CD_COMPANY = WH.CD_COMPANY AND WH1.NO_KEY = WH.NO_KEY AND WH1.TP_STEP = '21'
	JOIN (SELECT QL.CD_COMPANY, QL.NO_FILE, QL.CD_SUPPLIER,
				 COUNT(1) AS QT_ITEM
		  FROM CZ_SA_QTNL QL
		  GROUP BY QL.CD_COMPANY, QL.NO_FILE, QL.CD_SUPPLIER) QL
	ON QL.CD_COMPANY = WH.CD_COMPANY AND QL.NO_FILE = WH.NO_KEY
	GROUP BY WH.CD_COMPANY, ISNULL(WH1.ID_LOG, QL.CD_SUPPLIER)
)
SELECT WH.NO_KEY,
	   SO.NM_SALEORG, 
	   MC.NM_CC, 
	   WH.NM_EMP,
	   WH.NM_EMP_QTN,
	   WH.NM_EMP_STK,
	   MP.LN_PARTNER,
	   MP1.LN_PARTNER AS NM_SUPPLIER,
	   WH.NO_IMO,
	   MH.NM_VESSEL,
	   WH.YN_ENGINE,
	   (CASE WHEN @P_TP_QTN = '000' THEN NULL ELSE (SELECT WH1.QT_FILE 
													FROM WH3 WH1
													WHERE WH1.CD_COMPANY = WH.CD_COMPANY
													AND WH1.CD_SUPPLIER = WH.CD_SUPPLIER) END) AS QT_FILE_SUPPLIER,
	   (CASE WHEN @P_TP_QTN = '000' THEN NULL ELSE (SELECT WH1.QT_ITEM 
													FROM WH3 WH1
													WHERE WH1.CD_COMPANY = WH.CD_COMPANY
													AND WH1.CD_SUPPLIER = WH.CD_SUPPLIER) END) AS QT_ITEM_SUPPLIER,
       1.0 AS QT_INQ,
       (CASE WHEN WH.YN_DONE = 'Y' THEN 1.0 ELSE NULL END) AS QT_DONE,
       (CASE WHEN WH.YN_DONE = 'Y' AND WH.DT_QTN <= 10 THEN 1.0 ELSE NULL END) AS QT_DONE1,
       (CASE WHEN WH.YN_DONE = 'Y' THEN WH.QT_ITEM ELSE NULL END) AS QT_ITEM,
       (CASE WHEN WH.YN_DONE = 'Y' THEN WH.AM_QTN ELSE NULL END) AS AM_QTN,
       (CASE WHEN WH.YN_DONE = 'Y' AND WH.DT_QTN <= 10 THEN WH.DT_QTN ELSE NULL END) AS DT_QTN,
       (CASE WHEN WH.YN_DONE = 'Y' AND WH.DT_QTN <= 2 THEN 1.0 ELSE NULL END) AS QT_2DAY,
       (CASE WHEN WH.NO_SO IS NOT NULL THEN 1.0 ELSE NULL END) AS QT_SO
FROM WH2 WH
LEFT JOIN MA_SALEORG SO ON SO.CD_COMPANY = WH.CD_COMPANY AND SO.CD_SALEORG = WH.CD_SALEORG
LEFT JOIN MA_CC MC ON MC.CD_COMPANY = WH.CD_COMPANY AND MC.CD_CC = WH.CD_CC
LEFT JOIN MA_PARTNER MP ON MP.CD_COMPANY = WH.CD_COMPANY AND MP.CD_PARTNER = WH.CD_PARTNER
LEFT JOIN MA_PARTNER MP1 ON MP1.CD_COMPANY = WH.CD_COMPANY AND MP1.CD_PARTNER = WH.CD_SUPPLIER
LEFT JOIN CZ_MA_HULL MH ON MH.NO_IMO = WH.NO_IMO

GO