USE [NEOE]
GO

/****** Object:  Table [NEOE].[CZ_TR_INVL]    Script Date: 2015-10-22 오후 5:33:52 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [NEOE].[CZ_TR_INVL](
	[NO_INV] [nvarchar](20) NOT NULL,
	[NO_LINE] [numeric](5, 0) NOT NULL,
	[CD_COMPANY] [nvarchar](7) NOT NULL,
	[CD_PLANT] [nvarchar](7) NOT NULL,
	[CD_ITEM] [nvarchar](20) NOT NULL,
	[DT_DELIVERY] [nchar](8) NOT NULL,
	[QT_INVENT] [numeric](17, 4) NOT NULL,
	[UM_INVENT] [numeric](15, 4) NOT NULL,
	[AM_INVENT] [numeric](17, 4) NOT NULL,
	[HS_DISC] [nvarchar](100) NULL,
	[QT_SO] [numeric](17, 4) NULL,
	[UM_SO] [numeric](15, 4) NOT NULL,
	[AM_EXSO] [numeric](17, 4) NOT NULL,
	[NO_QTIO] [nvarchar](20) NULL,
	[NO_LINE_QTIO] [numeric](5, 0) NULL,
	[NO_LC] [nvarchar](20) NULL,
	[NO_LINE_LC] [numeric](5, 0) NULL,
	[NO_PO] [nvarchar](20) NULL,
	[NO_LINE_PO] [numeric](5, 0) NULL,
	[NO_TO] [nvarchar](20) NULL,
	[NO_BL] [nvarchar](20) NULL,
	[DT_TO] [nchar](8) NULL,
	[DTS_INSERT] [nvarchar](14) NULL,
	[ID_INSERT] [nvarchar](15) NULL,
	[DTS_UPDATE] [nvarchar](14) NULL,
	[ID_UPDATE] [nvarchar](15) NULL,
	[TEXT_DEC] [nvarchar](200) NULL,
	[CD_EXCH_PO] [nvarchar](3) NULL,
	[UM_PO] [numeric](17, 4) NULL,
	[AM_PO] [numeric](17, 4) NULL,
	[CD_EXCH_APP] [nvarchar](3) NULL,
	[RT_EXCH_APP] [numeric](17, 4) NULL,
	[RT_MARGIN_APP] [numeric](17, 4) NULL,
	[REPRE_CD_ITEM] [nvarchar](40) NULL,
	[REPRE_NM_ITEM] [nvarchar](100) NULL,
	[YN_PRINT] [nvarchar](1) NOT NULL,
	[RT_EXCH_PO] [numeric](17, 4) NULL,
	[NO_PO_PARTNER] [nvarchar](50) NULL,
	[BL_NO_DOCU] [nvarchar](20) NULL,
	[BL_NO_DOLINE] [numeric](5, 0) NULL,
 CONSTRAINT [PK_CZ_TR_INVL] PRIMARY KEY CLUSTERED 
(
	[NO_INV] ASC,
	[NO_LINE] ASC,
	[CD_COMPANY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [NEOE].[CZ_TR_INVL] ADD  CONSTRAINT [DF__CZ_TR_INVL__DT_DELI__30EEF2A3]  DEFAULT ('00000000') FOR [DT_DELIVERY]
GO

ALTER TABLE [NEOE].[CZ_TR_INVL] ADD  CONSTRAINT [DF__CZ_TR_INVL__QT_INVE__31E316DC]  DEFAULT ((0)) FOR [QT_INVENT]
GO

ALTER TABLE [NEOE].[CZ_TR_INVL] ADD  CONSTRAINT [DF__CZ_TR_INVL__UM_INVE__32D73B15]  DEFAULT ((0)) FOR [UM_INVENT]
GO

ALTER TABLE [NEOE].[CZ_TR_INVL] ADD  CONSTRAINT [DF__CZ_TR_INVL__AM_INVE__33CB5F4E]  DEFAULT ((0)) FOR [AM_INVENT]
GO

ALTER TABLE [NEOE].[CZ_TR_INVL] ADD  CONSTRAINT [DF__CZ_TR_INVL__QT_SO__34BF8387]  DEFAULT ((0)) FOR [QT_SO]
GO

ALTER TABLE [NEOE].[CZ_TR_INVL] ADD  CONSTRAINT [DF__CZ_TR_INVL__UM_SO__35B3A7C0]  DEFAULT ((0)) FOR [UM_SO]
GO

ALTER TABLE [NEOE].[CZ_TR_INVL] ADD  CONSTRAINT [DF__CZ_TR_INVL__AM_EXSO__36A7CBF9]  DEFAULT ((0)) FOR [AM_EXSO]
GO

ALTER TABLE [NEOE].[CZ_TR_INVL] ADD  CONSTRAINT [DF__CZ_TR_INVL__YN_PRIN__20AD99B3]  DEFAULT ('Y') FOR [YN_PRINT]
GO


