USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_LOG_CHARGE_RPT_S]    Script Date: 2016-02-12 오후 1:40:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




ALTER PROCEDURE [NEOE].[SP_CZ_SA_LOG_CHARGE_RPT_S]  
(
    @P_CD_COMPANY		NVARCHAR(7),
	@P_DT_SO_FROM		NVARCHAR(8),
	@P_DT_SO_TO			NVARCHAR(8),
	@P_NO_SO			NVARCHAR(20),
	@P_TP_BILL			NVARCHAR(3),
	@P_TP_PACKING		NVARCHAR(4),
	@P_YN_PACK_CHARGE	NVARCHAR(1),
	@P_YN_OVER			NVARCHAR(1)
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT SH.NO_SO,
	   SH.DT_SO,
	   ISNULL(SH.AM_SO, 0) AS AM_SO,
	   ISNULL(SH.AM_PO, 0) AS AM_PO,
	   ISNULL(SH.AM_STOCK, 0) AS AM_STOCK,
	   ISNULL(SH.AM_PROFIT, 0) AS AM_PROFIT,
	   ISNULL(SH.AM_PACK, 0) AS AM_PACK,
	   ISNULL(SH.AM_CHARGE, 0) AS AM_CHARGE,
	   ISNULL(SH.AM_IV, 0) AS AM_IV,
	   MC.NM_SYSDEF AS NM_PACKING,
	   MC.CD_FLAG1 AS YN_BILL,
	   SH.NM_PACK,
	   SH.DT_WARNING
FROM (SELECT SH.CD_COMPANY,
	  	     SH.NO_SO,
	  	     SH.DT_SO,
			 SH.TP_PACKING,
			 PH.NM_PACK,
	  	     SL.AM_SO,
	  	     SL.AM_PO,
	  	     SL.AM_STOCK,
	  	     (ISNULL(SL.AM_SO, 0) - (ISNULL(SL.AM_PO, 0) + ISNULL(SL.AM_STOCK, 0))) AS AM_PROFIT,
	  	     PH.AM_PACK,
			 SL.AM_CHARGE,
			 IL.AM_IV,
			 SH.DT_USERDEF1 AS DT_WARNING
	  FROM SA_SOH SH
	  JOIN (SELECT SL.CD_COMPANY, SL.NO_SO,
	  			   SUM(CASE WHEN SL.CD_ITEM LIKE 'SD%' THEN 0 ELSE SL.AM_WONAMT END) AS AM_SO,
	  			   SUM(PL.AM_PO) AS AM_PO,
	  			   SUM(SB.UM_KR * SB.QT_STOCK) AS AM_STOCK,
				   SUM(CASE WHEN SL.CD_ITEM LIKE 'SD%' THEN SL.AM_WONAMT ELSE 0 END) AS AM_CHARGE
	        FROM SA_SOL SL
	  	    LEFT JOIN CZ_SA_STOCK_BOOK SB ON SB.CD_COMPANY = SL.CD_COMPANY AND SB.NO_FILE = SL.NO_SO AND SB.NO_LINE = SL.SEQ_SO
	  	    LEFT JOIN (SELECT PL.CD_COMPANY, PL.NO_SO, PL.NO_SOLINE,
	  		  				  SUM(PL.AM) AS AM_PO
	  		  		   FROM PU_POL PL
	  		  		   WHERE PL.CD_ITEM NOT LIKE 'SD%'
	  		  		   GROUP BY PL.CD_COMPANY, PL.NO_SO, PL.NO_SOLINE) PL
	  	    ON PL.CD_COMPANY = SL.CD_COMPANY AND PL.NO_SO = SL.NO_SO AND PL.NO_SOLINE = SL.SEQ_SO
	  	    GROUP BY SL.CD_COMPANY, SL.NO_SO) SL
	  ON SL.CD_COMPANY = SH.CD_COMPANY AND SL.NO_SO = SH.NO_SO
	  LEFT JOIN (SELECT PH.CD_COMPANY,
	  				    PH.NO_FILE,
						MAX(PH.NM_PACK) AS NM_PACK,
	  				    ROUND(SUM(PH.AM_CBM / QT_FILE), 0) AS AM_PACK
	  			 FROM (SELECT PH.CD_COMPANY,
	  				  		  PH.NO_GIR,
	  				  		  PH.NO_PACK,
	  				  		  PH.NO_FILE,
							  PH.NM_PACK,
	  				  		  (CASE WHEN PH.QT_CBM >= 1 THEN PH.QT_CBM * (SELECT TL.UM 
	  				  		  	 										  FROM CZ_MA_TARIFF_CBM_H TH
																		  JOIN CZ_MA_TARIFF_CBM_L TL ON TL.CD_COMPANY = TH.CD_COMPANY AND TL.CD_PARTNER = TH.CD_PARTNER
	  				  		  	 										  WHERE TH.CD_COMPANY = PH.CD_COMPANY
																	      AND ISNULL(TH.YN_USE, 'N') = 'Y'
	  				  		  	 										  AND TL.SIZE = 1
																		  AND CONVERT(NVARCHAR(8), GETDATE(), 112) BETWEEN TL.DT_START AND TL.DT_END) 
	  				  		  	 				        ELSE (SELECT TL.UM 
	  				  		  	 						      FROM CZ_MA_TARIFF_CBM_H TH
															  JOIN CZ_MA_TARIFF_CBM_L TL ON TL.CD_COMPANY = TH.CD_COMPANY AND TL.CD_PARTNER = TH.CD_PARTNER
	  				  		  	 						      WHERE TH.CD_COMPANY = PH.CD_COMPANY
															  AND ISNULL(TH.YN_USE, 'N') = 'Y'
	  				  		  	 						      AND TL.SIZE = PH.QT_CBM
															  AND CONVERT(NVARCHAR(8), GETDATE(), 112) BETWEEN TL.DT_START AND TL.DT_END) END) AS AM_CBM,
	  				  		  (SELECT COUNT(DISTINCT PL.NO_FILE) 
	  				  		   FROM CZ_SA_PACKL PL
	  				  		   WHERE PL.CD_COMPANY = PH.CD_COMPANY
	  				  		   AND PL.NO_GIR = PH.NO_GIR
	  				  		   AND PL.NO_PACK = PH.NO_PACK) AS QT_FILE
	  				   FROM (SELECT PH.CD_COMPANY, 
	  				  		        PH.NO_GIR, 
	  				  		        PH.NO_PACK, 
	  				  		        PL.NO_FILE,
									MC.NM_SYSDEF AS NM_PACK,
	  				  		        (CASE WHEN PH.CD_TYPE = '003' AND PH.YN_OUTSOURCING = 'Y' THEN CONVERT(NUMERIC(17, 2), ((PH.QT_WIDTH * 0.001) * (PH.QT_HEIGHT * 0.001) * (PH.QT_LENGTH * 0.001))) 
																							  ELSE 0 END) AS QT_CBM
	  				  		 FROM CZ_SA_PACKH PH
							 LEFT JOIN MA_CODEDTL MC ON MC.CD_COMPANY = PH.CD_COMPANY AND MC.CD_FIELD = 'CZ_SA00026' AND MC.CD_SYSDEF = PH.CD_TYPE
	  						 JOIN (SELECT PL.CD_COMPANY, PL.NO_GIR, PL.NO_PACK, PL.NO_FILE 
	  				  		       FROM CZ_SA_PACKL PL
	  				  		       GROUP BY PL.CD_COMPANY, PL.NO_GIR, PL.NO_PACK, PL.NO_FILE) PL 
	  						 ON PL.CD_COMPANY = PH.CD_COMPANY AND PL.NO_GIR = PH.NO_GIR AND PL.NO_PACK = PH.NO_PACK
	  				  		 WHERE PH.NO_GIR = PH.NO_GIR_ORG
							 AND PH.NO_PACK = PH.NO_PACK_ORG) PH) PH
	  			 GROUP BY PH.CD_COMPANY, PH.NO_FILE) PH
	  ON PH.CD_COMPANY = SH.CD_COMPANY AND PH.NO_FILE = SH.NO_SO
	  LEFT JOIN (SELECT IL.CD_COMPANY,
				 	    IL1.NO_SO,
				 	    SUM(ROUND(ISNULL(IL.AM_CLS, 0) / ISNULL(IL.QT_SO, 0), 0)) AS AM_IV
				 FROM (SELECT IL.CD_COMPANY,
				 	   	      IL.NO_IO,
				 	   		  COUNT(DISTINCT IL.NO_SO) AS QT_SO,
				 	   	      SUM(IL.AM_CLS) AS AM_CLS
				 	   FROM SA_IVL IL
				 	   WHERE IL.CD_USERDEF1 = 'Y' 
				 	   GROUP BY IL.CD_COMPANY, IL.NO_IO) IL
				 JOIN (SELECT IL.CD_COMPANY, IL.NO_IO, IL.NO_SO 
				 	   FROM SA_IVL IL
				 	   GROUP BY IL.CD_COMPANY, IL.NO_IO, IL.NO_SO) IL1
				 ON IL1.CD_COMPANY = IL.CD_COMPANY AND IL1.NO_IO = IL.NO_IO 
				 GROUP BY IL.CD_COMPANY, IL1.NO_SO) IL
	  ON IL.CD_COMPANY = SH.CD_COMPANY AND IL.NO_SO = SH.NO_SO) SH
LEFT JOIN MA_CODEDTL MC ON MC.CD_COMPANY = SH.CD_COMPANY AND MC.CD_FIELD = 'TR_IM00011' AND MC.CD_SYSDEF = SH.TP_PACKING
WHERE SH.CD_COMPANY = @P_CD_COMPANY
AND SH.DT_SO BETWEEN @P_DT_SO_FROM AND @P_DT_SO_TO
AND (ISNULL(@P_NO_SO, '') = '' OR SH.NO_SO = @P_NO_SO)
AND (ISNULL(@P_TP_PACKING, '') = '' OR SH.TP_PACKING = @P_TP_PACKING)
AND (ISNULL(@P_YN_PACK_CHARGE, 'N') = 'N' OR ISNULL(SH.AM_PACK, 0) > 0)
AND (ISNULL(@P_YN_OVER, 'N') = 'N' OR ISNULL(SH.AM_PACK, 0) > ISNULL(SH.AM_PROFIT, 0))
AND (@P_TP_BILL = '' OR
	 (@P_TP_BILL = '001' AND MC.CD_FLAG1 = 'Y') OR 
	 (@P_TP_BILL = '002' AND MC.CD_FLAG1 = 'N'))
AND EXISTS (SELECT 1 
			FROM CZ_SA_QTNH QH
			WHERE QH.CD_COMPANY = SH.CD_COMPANY
			AND QH.NO_FILE = SH.NO_SO)

GO