USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_IVMNG_INVOICE_I]    Script Date: 2016-03-15 오전 11:57:46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER PROCEDURE [NEOE].[SP_CZ_SA_IVMNG_INVOICE_I]
(
	@P_CD_COMPANY	NVARCHAR(7),
	@P_NO_INVOICE	NVARCHAR(20),
	@P_NO_IV		NVARCHAR(20),
	@P_CD_PARTNER	NVARCHAR(20),
	@P_NO_IMO		NVARCHAR(10),
	@P_DC_COMPANY	NVARCHAR(MAX),
	@P_DC_ADDRESS	NVARCHAR(MAX),
	@P_DC_TEL		NVARCHAR(MAX),
	@P_CD_NATION	NVARCHAR(10),
	@P_ID_INSERT	NVARCHAR(15)
)
AS

INSERT INTO CZ_SA_IVMNG_INVOICE
(
	CD_COMPANY,
	NO_INVOICE,
	NO_IV,
	NO_IO,
	CD_PARTNER,
	NO_IMO,
	DC_COMPANY,
	DC_ADDRESS,
	DC_TEL,
	CD_NATION,
	ID_INSERT,
	DTS_INSERT
)
VALUES
(
	@P_CD_COMPANY,
	@P_NO_INVOICE,
	@P_NO_IV,
	(SELECT MAX(IL.NO_IO) 
	 FROM SA_IVL IL 
	 WHERE IL.CD_COMPANY = @P_CD_COMPANY 
	 AND IL.NO_IV = @P_NO_IV),
	@P_CD_PARTNER,
	@P_NO_IMO,
	@P_DC_COMPANY,
	@P_DC_ADDRESS,
	@P_DC_TEL,
	@P_CD_NATION,
	@P_ID_INSERT,
	NEOE.SF_SYSDATE(GETDATE())
)

GO

