USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_IV_PJT_RPTR_S]    Script Date: 2016-06-23 오후 4:51:05 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




ALTER PROCEDURE [NEOE].[SP_CZ_SA_IV_PJT_RPTR_S]  
(
	@P_CD_COMPANY			NVARCHAR(7),
	@P_NO_PROJECT			NVARCHAR(20)
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT FD.CD_COMPANY,
	   FD.CD_PJT,
	   FD.NO_DOCU,
	   FD.NO_DOLINE,
	   FD.DT_ACCT,
	   FD.TP_DRCR,
	   MC1.NM_SYSDEF AS NM_DRCR,
	   FD.CD_ACCT,
	   AC.NM_ACCT,
	   FD.NM_NOTE,
	   FD.AM_CR,
	   FD.AM_DR,
	   FD.ST_DOCU,
	   MC.NM_SYSDEF AS NM_ST_DOCU,
	   FD.CD_PC,
	   FD.NO_MDOCU
FROM FI_DOCU FD
LEFT JOIN FI_ACCTCODE AC ON AC.CD_COMPANY = FD.CD_COMPANY AND AC.CD_ACCT = FD.CD_ACCT
LEFT JOIN MA_CODEDTL MC ON MC.CD_COMPANY = FD.CD_COMPANY AND MC.CD_FIELD = 'FI_J000003' AND MC.CD_SYSDEF = FD.ST_DOCU
LEFT JOIN MA_CODEDTL MC1 ON MC1.CD_COMPANY = FD.CD_COMPANY AND MC1.CD_FIELD = 'FI_B000002' AND MC1.CD_SYSDEF = FD.TP_DRCR
WHERE FD.CD_COMPANY = @P_CD_COMPANY
AND FD.CD_PJT = @P_NO_PROJECT
AND (AC.CD_ACGRP = '510' OR AC.CD_ACGRP = '560')
ORDER BY FD.NO_DOCU, FD.NO_DOLINE, FD.DT_ACCT

GO

