USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_IV_PJT_RPTH_U]    Script Date: 2016-07-25 오전 11:44:18 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO





ALTER PROCEDURE [NEOE].[SP_CZ_SA_IV_PJT_RPTH_U]  
(
    @P_CD_COMPANY			NVARCHAR(7),
	@P_NO_SO				NVARCHAR(20),
	@P_DC_RMK_CONTRACT		NVARCHAR(4000),
	@P_DC_RMK_PJT			NVARCHAR(4000),
	@P_ID_UPDATE			NVARCHAR(15)
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

UPDATE SA_SOH
SET DC_RMK_CONTRACT = @P_DC_RMK_CONTRACT,
	ID_UPDATE = @P_ID_UPDATE,
	DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE())
WHERE CD_COMPANY = @P_CD_COMPANY
AND NO_SO = @P_NO_SO

UPDATE SA_PROJECTH
SET DC_RMK = @P_DC_RMK_PJT,
	ID_UPDATE = @P_ID_UPDATE,
	DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE())
WHERE CD_COMPANY = @P_CD_COMPANY
AND NO_PROJECT = @P_NO_SO

GO