USE [NEOE]
GO
/****** Object:  StoredProcedure [NEOE].[UP_CZ_PR_OPOUT_PO_ING_L_RPT_SEL]    Script Date: 2023-04-25 오전 10:21:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO



ALTER PROC [NEOE].[UP_CZ_PR_OPOUT_PO_ING_L_RPT_SEL]
(
    @P_CD_COMPANY       NVARCHAR(7), 
	@P_TYPE_DT			NVARCHAR(3),  
    @P_DT_START         NVARCHAR(8), 
    @P_DT_END           NVARCHAR(8), 
    @P_CD_BIZAREA       NVARCHAR(7), 
    @P_CD_PLANT         NVARCHAR(7), 
    @P_CD_PARTNER       NVARCHAR(20), 
    @P_CD_WC            NVARCHAR(7), 
    @P_CD_WCOP          NVARCHAR(4), 
    @P_CD_ITEM_START    NVARCHAR(50), 
    @P_CD_ITEM_END      NVARCHAR(50), 
	@P_YN_RCV			NVARCHAR(4), 
    @P_TAB_NAME         NVARCHAR(50), 
    @P_CONDITION        NVARCHAR(50),
    @P_FG_LANG     NVARCHAR(4) = NULL	--언어
)
AS
-- MultiLang Call
EXEC UP_MA_LOCAL_LANGUAGE @P_FG_LANG

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET NOCOUNT ON

DECLARE @V_QUERY	NVARCHAR(MAX)
DECLARE @V_QUERY_1	NVARCHAR(MAX)
DECLARE @V_QUERY_2	NVARCHAR(MAX)
DECLARE @V_QUERY_3	NVARCHAR(MAX)
DECLARE @V_QUERY_4	NVARCHAR(MAX)
DECLARE @V_QUERY_5	NVARCHAR(MAX)
DECLARE @V_QUERY_6	NVARCHAR(MAX)

SET @V_QUERY_1 = ' SELECT H.NO_PO, H.CD_PLANT, H.CD_PARTNER, H.NO_EMP, H.DT_PO, H.CD_EXCH, H.RT_EXCH, H.FG_TAX, H.VAT_RATE, 
        H.AM_EX AM_EX_H, H.AM AM_H, H.AM_VAT AM_VAT_H, H.DC_RMK DC_RMK_H, 
        L.NO_LINE, L.NO_WO, L.CD_OP, L.CD_WC, L.CD_WCOP, L.NO_WORK, L.CD_ITEM, L.DT_DUE, L.QT_PO, L.QT_RCV, 
        L.QT_CLS, L.UM_EX, L.AM_EX, L.UM, L.AM, L.AM_VAT, L.AM + L.AM_VAT AM_TOTAL, L.DC_RMK, 
        W.QT_ITEM, M.NM_ITEM, M.NO_DESIGN, M.STND_ITEM, M.UNIT_IM, 
        A.LN_PARTNER, B.NM_WC, C.NM_OP, D.NM_SYSDEF NM_EXCH, E.NM_KOR, F.NM_SYSDEF NM_FG_TAX,
        L.OLD_QT_PO,
		L.UNIT_CH,
		L.QT_CHCOEF,
		ISNULL(WR.QT_BAD,0) AS QT_BAD
	FROM PR_OPOUT_POH H
    JOIN PR_OPOUT_POL L ON L.CD_COMPANY = H.CD_COMPANY AND L.CD_PLANT = H.CD_PLANT AND L.NO_PO = H.NO_PO
    JOIN PR_WO W ON W.CD_COMPANY = L.CD_COMPANY AND W.CD_PLANT = L.CD_PLANT AND W.NO_WO = L.NO_WO
    JOIN DZSN_MA_PLANT P ON P.CD_COMPANY = H.CD_COMPANY AND P.CD_PLANT = H.CD_PLANT
    JOIN DZSN_MA_BIZAREA Z ON Z.CD_COMPANY = ''' + @P_CD_COMPANY + ''' AND Z.CD_BIZAREA = ''' + @P_CD_BIZAREA + '''
    LEFT JOIN DZSN_MA_PITEM M ON M.CD_COMPANY = L.CD_COMPANY AND M.CD_PLANT = L.CD_PLANT AND M.CD_ITEM = L.CD_ITEM
    LEFT JOIN DZSN_MA_PARTNER A ON A.CD_COMPANY = H.CD_COMPANY AND A.CD_PARTNER = H.CD_PARTNER
    LEFT JOIN DZSN_MA_WC B ON B.CD_COMPANY = L.CD_COMPANY AND B.CD_PLANT = L.CD_PLANT AND B.CD_WC = L.CD_WC
    LEFT JOIN DZSN_PR_WCOP C ON C.CD_COMPANY = L.CD_COMPANY AND C.CD_PLANT = L.CD_PLANT AND C.CD_WC = L.CD_WC AND C.CD_WCOP = L.CD_WCOP
    LEFT JOIN DZSN_MA_CODEDTL D ON D.CD_COMPANY = H.CD_COMPANY AND D.CD_SYSDEF = H.CD_EXCH AND D.CD_FIELD = ''MA_B000005''   --화폐단위
    LEFT JOIN DZSN_MA_EMP E ON E.CD_COMPANY = H.CD_COMPANY AND E.NO_EMP = H.NO_EMP
    LEFT JOIN DZSN_MA_CODEDTL F ON F.CD_COMPANY = H.CD_COMPANY AND F.CD_SYSDEF = H.FG_TAX AND F.CD_FIELD = ''MA_B000046''   --부가세매입
	LEFT JOIN (SELECT CD_COMPANY, NO_WO, CD_OP, NO_OPOUT_PO, NO_OPOUT_PO_LINE, SUM(QT_BAD) AS QT_BAD
		   FROM PR_WORK
		   GROUP BY CD_COMPANY, NO_WO, CD_OP, NO_OPOUT_PO, NO_OPOUT_PO_LINE) WR 
	ON WR.CD_COMPANY = L.CD_COMPANY AND WR.NO_WO = L.NO_WO AND WR.CD_OP = L.CD_OP AND WR.NO_OPOUT_PO = L.NO_PO AND WR.NO_OPOUT_PO_LINE = L.NO_LINE
    WHERE H.CD_COMPANY = ''' + @P_CD_COMPANY + '''
        AND H.CD_PLANT = ''' + @P_CD_PLANT + '''
		AND	((''' + @P_TYPE_DT + ''' = ''001'' AND (H.DT_PO BETWEEN ''' + @P_DT_START + ''' AND ''' + @P_DT_END + '''))   
	     OR	(''' + @P_TYPE_DT + ''' = ''002'' AND (L.DT_DUE BETWEEN ''' + @P_DT_START + ''' AND ''' + @P_DT_END + ''')))  
        AND (H.CD_PARTNER = ''' + @P_CD_PARTNER + ''' OR ''' + @P_CD_PARTNER + ''' = '''' OR ''' + @P_CD_PARTNER + ''' IS NULL)
        AND (L.CD_WC = ''' + @P_CD_WC + ''' OR ''' + @P_CD_WC + ''' = '''' OR ''' + @P_CD_WC + ''' IS NULL)
        AND (L.CD_WCOP = ''' + @P_CD_WCOP + ''' OR ''' + @P_CD_WCOP + ''' = '''' OR ''' + @P_CD_WCOP + ''' IS NULL)
        AND (L.CD_ITEM >= ''' + @P_CD_ITEM_START + ''' OR ''' + @P_CD_ITEM_START + ''' = '''' OR ''' + @P_CD_ITEM_START + ''' IS NULL)
        AND (L.CD_ITEM <= ''' + @P_CD_ITEM_END + ''' OR ''' + @P_CD_ITEM_END + ''' = '''' OR ''' + @P_CD_ITEM_END + ''' IS NULL)
		AND H.NO_PO = ''' + @P_CONDITION + '''
		'
SET @V_QUERY_2 = 'SELECT H.NO_PO, H.CD_PLANT, H.CD_PARTNER, H.NO_EMP, H.DT_PO, H.CD_EXCH, H.RT_EXCH, H.FG_TAX, H.VAT_RATE, 
        H.AM_EX AM_EX_H, H.AM AM_H, H.AM_VAT AM_VAT_H, H.DC_RMK DC_RMK_H, 
        L.NO_LINE, L.NO_WO, L.CD_OP, L.CD_WC, L.CD_WCOP, L.NO_WORK, L.CD_ITEM, L.DT_DUE, L.QT_PO, L.QT_RCV, 
		L.QT_CLS, L.UM_EX, L.AM_EX, L.UM, L.AM, L.AM_VAT, L.AM + L.AM_VAT AM_TOTAL, L.DC_RMK, 
        W.QT_ITEM, M.NM_ITEM, M.NO_DESIGN, M.STND_ITEM, M.UNIT_IM, 
        A.LN_PARTNER, B.NM_WC, C.NM_OP, D.NM_SYSDEF NM_EXCH, E.NM_KOR, F.NM_SYSDEF NM_FG_TAX,
        L.OLD_QT_PO,
		L.UNIT_CH,
		L.QT_CHCOEF,
		ISNULL(WR.QT_BAD,0) AS QT_BAD
    FROM PR_OPOUT_POH H
    JOIN PR_OPOUT_POL L ON L.CD_COMPANY = H.CD_COMPANY AND L.CD_PLANT = H.CD_PLANT AND L.NO_PO = H.NO_PO
    JOIN PR_WO W ON W.CD_COMPANY = L.CD_COMPANY AND W.CD_PLANT = L.CD_PLANT AND W.NO_WO = L.NO_WO
    JOIN DZSN_MA_PLANT P ON P.CD_COMPANY = H.CD_COMPANY AND P.CD_PLANT = H.CD_PLANT
    JOIN DZSN_MA_BIZAREA Z ON Z.CD_COMPANY = ''' + @P_CD_COMPANY + ''' AND Z.CD_BIZAREA = ''' + @P_CD_BIZAREA + '''
    LEFT JOIN DZSN_MA_PITEM M ON M.CD_COMPANY = L.CD_COMPANY AND M.CD_PLANT = L.CD_PLANT AND M.CD_ITEM = L.CD_ITEM
    LEFT JOIN DZSN_MA_PARTNER A ON A.CD_COMPANY = H.CD_COMPANY AND A.CD_PARTNER = H.CD_PARTNER
    LEFT JOIN DZSN_MA_WC B ON B.CD_COMPANY = L.CD_COMPANY AND B.CD_PLANT = L.CD_PLANT AND B.CD_WC = L.CD_WC
    LEFT JOIN DZSN_PR_WCOP C ON C.CD_COMPANY = L.CD_COMPANY AND C.CD_PLANT = L.CD_PLANT AND C.CD_WC = L.CD_WC AND C.CD_WCOP = L.CD_WCOP
    LEFT JOIN DZSN_MA_CODEDTL D ON D.CD_COMPANY = H.CD_COMPANY AND D.CD_SYSDEF = H.CD_EXCH AND D.CD_FIELD = ''MA_B000005''   --화폐단위
    LEFT JOIN DZSN_MA_EMP E ON E.CD_COMPANY = H.CD_COMPANY AND E.NO_EMP = H.NO_EMP
    LEFT JOIN DZSN_MA_CODEDTL F ON F.CD_COMPANY = H.CD_COMPANY AND F.CD_SYSDEF = H.FG_TAX AND F.CD_FIELD = ''MA_B000046''   --부가세매입
	LEFT JOIN (SELECT CD_COMPANY, NO_WO, CD_OP, NO_OPOUT_PO, NO_OPOUT_PO_LINE, SUM(QT_BAD) AS QT_BAD
		   FROM PR_WORK
		   GROUP BY CD_COMPANY, NO_WO, CD_OP, NO_OPOUT_PO, NO_OPOUT_PO_LINE) WR 
	ON WR.CD_COMPANY = L.CD_COMPANY AND WR.NO_WO = L.NO_WO AND WR.CD_OP = L.CD_OP AND WR.NO_OPOUT_PO = L.NO_PO AND WR.NO_OPOUT_PO_LINE = L.NO_LINE
   WHERE H.CD_COMPANY = ''' + @P_CD_COMPANY + '''
     AND H.CD_PLANT = ''' + @P_CD_PLANT + '''
	 AND ((''' + @P_TYPE_DT + ''' = ''001'' AND (H.DT_PO BETWEEN ''' + @P_DT_START + ''' AND ''' + @P_DT_END + '''))   
	  OR (''' + @P_TYPE_DT + ''' = ''002'' AND (L.DT_DUE BETWEEN ''' + @P_DT_START + ''' AND ''' + @P_DT_END + '''))) 
     AND (H.CD_PARTNER = ''' + @P_CD_PARTNER + ''' OR ''' + @P_CD_PARTNER + ''' = '''' OR ''' + @P_CD_PARTNER + ''' IS NULL)
     AND (L.CD_WC = ''' + @P_CD_WC + ''' OR ''' + @P_CD_WC + ''' = '''' OR ''' + @P_CD_WC + ''' IS NULL)
     AND (L.CD_WCOP = ''' + @P_CD_WCOP + ''' OR ''' + @P_CD_WCOP + ''' = '''' OR ''' + @P_CD_WCOP + ''' IS NULL)
     AND (L.CD_ITEM >= ''' + @P_CD_ITEM_START + ''' OR ''' + @P_CD_ITEM_START + ''' = '''' OR ''' + @P_CD_ITEM_START + ''' IS NULL)
     AND (L.CD_ITEM <= ''' + @P_CD_ITEM_END + ''' OR ''' + @P_CD_ITEM_END + ''' = '''' OR ''' + @P_CD_ITEM_END + ''' IS NULL)
	 AND H.CD_PARTNER = ''' + @P_CONDITION + '''
	 '
SET @V_QUERY_3 = 'SELECT H.NO_PO, H.CD_PLANT, H.CD_PARTNER, H.NO_EMP, H.DT_PO, H.CD_EXCH, H.RT_EXCH, H.FG_TAX, H.VAT_RATE, 
        H.AM_EX AM_EX_H, H.AM AM_H, H.AM_VAT AM_VAT_H, H.DC_RMK DC_RMK_H, 
        L.NO_LINE, L.NO_WO, L.CD_OP, L.CD_WC, L.CD_WCOP, L.NO_WORK, L.CD_ITEM, L.DT_DUE, L.QT_PO, L.QT_RCV, 
        L.QT_CLS, L.UM_EX, L.AM_EX, L.UM, L.AM, L.AM_VAT, L.AM + L.AM_VAT AM_TOTAL, L.DC_RMK, 
        W.QT_ITEM, M.NM_ITEM, M.NO_DESIGN, M.STND_ITEM, M.UNIT_IM, 
        A.LN_PARTNER, B.NM_WC, C.NM_OP, D.NM_SYSDEF NM_EXCH, E.NM_KOR, F.NM_SYSDEF NM_FG_TAX,
        L.OLD_QT_PO,
		L.UNIT_CH,
		L.QT_CHCOEF,
		ISNULL(WR.QT_BAD,0) AS QT_BAD
    FROM PR_OPOUT_POH H
      JOIN PR_OPOUT_POL L ON L.CD_COMPANY = H.CD_COMPANY AND L.CD_PLANT = H.CD_PLANT AND L.NO_PO = H.NO_PO
    JOIN PR_WO W ON W.CD_COMPANY = L.CD_COMPANY AND W.CD_PLANT = L.CD_PLANT AND W.NO_WO = L.NO_WO
    JOIN DZSN_MA_PLANT P ON P.CD_COMPANY = H.CD_COMPANY AND P.CD_PLANT = H.CD_PLANT
    JOIN DZSN_MA_BIZAREA Z ON Z.CD_COMPANY = ''' + @P_CD_COMPANY + ''' AND Z.CD_BIZAREA = ''' + @P_CD_BIZAREA + '''
    LEFT JOIN DZSN_MA_PITEM M ON M.CD_COMPANY = L.CD_COMPANY AND M.CD_PLANT = L.CD_PLANT AND M.CD_ITEM = L.CD_ITEM
    LEFT JOIN DZSN_MA_PARTNER A ON A.CD_COMPANY = H.CD_COMPANY AND A.CD_PARTNER = H.CD_PARTNER
    LEFT JOIN DZSN_MA_WC B ON B.CD_COMPANY = L.CD_COMPANY AND B.CD_PLANT = L.CD_PLANT AND B.CD_WC = L.CD_WC
    LEFT JOIN DZSN_PR_WCOP C ON C.CD_COMPANY = L.CD_COMPANY AND C.CD_PLANT = L.CD_PLANT AND C.CD_WC = L.CD_WC AND C.CD_WCOP = L.CD_WCOP
    LEFT JOIN DZSN_MA_CODEDTL D ON D.CD_COMPANY = H.CD_COMPANY AND D.CD_SYSDEF = H.CD_EXCH AND D.CD_FIELD = ''MA_B000005''   --화폐단위
    LEFT JOIN DZSN_MA_EMP E ON E.CD_COMPANY = H.CD_COMPANY AND E.NO_EMP = H.NO_EMP
    LEFT JOIN DZSN_MA_CODEDTL F ON F.CD_COMPANY = H.CD_COMPANY AND F.CD_SYSDEF = H.FG_TAX AND F.CD_FIELD = ''MA_B000046''   --부가세매입
	LEFT JOIN (SELECT CD_COMPANY, NO_WO, CD_OP, NO_OPOUT_PO, NO_OPOUT_PO_LINE, SUM(QT_BAD) AS QT_BAD
		   FROM PR_WORK
		   GROUP BY CD_COMPANY, NO_WO, CD_OP, NO_OPOUT_PO, NO_OPOUT_PO_LINE) WR 
	ON WR.CD_COMPANY = L.CD_COMPANY AND WR.NO_WO = L.NO_WO AND WR.CD_OP = L.CD_OP AND WR.NO_OPOUT_PO = L.NO_PO AND WR.NO_OPOUT_PO_LINE = L.NO_LINE
   WHERE H.CD_COMPANY = ''' + @P_CD_COMPANY + '''
     AND H.CD_PLANT = ''' + @P_CD_PLANT + '''
	 AND ((''' + @P_TYPE_DT + ''' = ''001'' AND (H.DT_PO BETWEEN ''' + @P_DT_START + ''' AND ''' + @P_DT_END + '''))   
	  OR (''' + @P_TYPE_DT + ''' = ''002'' AND (L.DT_DUE BETWEEN ''' + @P_DT_START + ''' AND ''' + @P_DT_END + '''))) 
     AND (H.CD_PARTNER = ''' + @P_CD_PARTNER + ''' OR ''' + @P_CD_PARTNER + ''' = '''' OR ''' + @P_CD_PARTNER + ''' IS NULL)
     AND (L.CD_WC = ''' + @P_CD_WC + ''' OR ''' + @P_CD_WC + ''' = '''' OR ''' + @P_CD_WC + ''' IS NULL)
     AND (L.CD_WCOP = ''' + @P_CD_WCOP + ''' OR ''' + @P_CD_WCOP + ''' = '''' OR ''' + @P_CD_WCOP + ''' IS NULL)
     AND (L.CD_ITEM >= ''' + @P_CD_ITEM_START + ''' OR ''' + @P_CD_ITEM_START + ''' = '''' OR ''' + @P_CD_ITEM_START + ''' IS NULL)
     AND (L.CD_ITEM <= ''' + @P_CD_ITEM_END + ''' OR ''' + @P_CD_ITEM_END + ''' = '''' OR ''' + @P_CD_ITEM_END + ''' IS NULL)
	 AND L.CD_ITEM = ''' + @P_CONDITION + '''
	 '
SET @V_QUERY_4 = 'SELECT H.CD_PLANT,	H.NO_PO,					L.NO_LINE,				H.CD_PARTNER,				A.LN_PARTNER,	L.CD_ITEM,
			P.NM_ITEM,	P.STND_ITEM,				P.UNIT_IM,				W.QT_ITEM,					L.QT_PO,		L.QT_RCV,
			L.QT_CLS,	H.CD_EXCH,					D.NM_SYSDEF AS NM_EXCH,	H.RT_EXCH,					L.UM_EX,		L.UM,
			L.AM_EX,	L.AM,						L.AM_VAT,				L.AM + L.AM_VAT AS AM_TOTAL,H.NO_EMP,		E.NM_KOR,
			H.FG_TAX,	F.NM_SYSDEF AS NM_FG_TAX,	H.VAT_RATE,				W.NO_WO,					H.DT_PO,		L.DT_DUE,
			L.CD_OP,	L.CD_WC,					B.NM_WC,				L.CD_WCOP,					C.NM_OP,		L.DC_RMK,
			L.QT_CHCOEF,L.OLD_QT_PO,				P.NO_DESIGN,			ISNULL(WR.QT_BAD,0) AS QT_BAD
    FROM PR_OPOUT_POH H
  	INNER JOIN PR_OPOUT_POL L ON L.CD_COMPANY = H.CD_COMPANY AND L.CD_PLANT = H.CD_PLANT AND L.NO_PO = H.NO_PO --
	INNER JOIN PR_WO W ON W.CD_COMPANY = H.CD_COMPANY AND W.CD_PLANT = H.CD_PLANT AND W.NO_WO = L.NO_WO --
	LEFT OUTER JOIN DZSN_MA_PARTNER A ON A.CD_COMPANY = H.CD_COMPANY AND A.CD_PARTNER = H.CD_PARTNER --
	LEFT OUTER JOIN DZSN_MA_PITEM P ON P.CD_COMPANY = H.CD_COMPANY AND P.CD_PLANT = H.CD_PLANT AND P.CD_ITEM = L.CD_ITEM
	LEFT OUTER JOIN DZSN_MA_CODEDTL D ON D.CD_COMPANY = H.CD_COMPANY AND D.CD_SYSDEF = H.CD_EXCH AND D.CD_FIELD = ''MA_B000005''
	LEFT OUTER JOIN DZSN_MA_EMP E ON E.CD_COMPANY = H.CD_COMPANY AND E.CD_PLANT = H.CD_PLANT AND E.NO_EMP = H.NO_EMP
	LEFT OUTER JOIN DZSN_MA_CODEDTL F ON F.CD_COMPANY = H.CD_COMPANY AND F.CD_SYSDEF = H.FG_TAX AND F.CD_FIELD = ''MA_B000046''
	LEFT OUTER JOIN DZSN_MA_WC B	ON B.CD_COMPANY = H.CD_COMPANY AND B.CD_PLANT = H.CD_PLANT AND B.CD_WC = L.CD_WC
	LEFT OUTER JOIN DZSN_PR_WCOP C ON C.CD_COMPANY = H.CD_COMPANY AND C.CD_PLANT = H.CD_PLANT AND C.CD_WC = L.CD_WC AND C.CD_WCOP = L.CD_WCOP
	LEFT JOIN (SELECT CD_COMPANY, NO_WO, CD_OP, NO_OPOUT_PO, NO_OPOUT_PO_LINE, SUM(QT_BAD) AS QT_BAD
		   FROM PR_WORK
		   GROUP BY CD_COMPANY, NO_WO, CD_OP, NO_OPOUT_PO, NO_OPOUT_PO_LINE) WR 
	ON WR.CD_COMPANY = L.CD_COMPANY AND WR.NO_WO = L.NO_WO AND WR.CD_OP = L.CD_OP AND WR.NO_OPOUT_PO = L.NO_PO AND WR.NO_OPOUT_PO_LINE = L.NO_LINE
   WHERE H.CD_COMPANY = ''' + @P_CD_COMPANY + '''
     AND H.CD_PLANT = ''' + @P_CD_PLANT + '''
	 AND ((''' + @P_TYPE_DT + ''' = ''001'' AND (H.DT_PO BETWEEN ''' + @P_DT_START + ''' AND ''' + @P_DT_END + '''))   
	  OR (''' + @P_TYPE_DT + ''' = ''002'' AND (L.DT_DUE BETWEEN ''' + @P_DT_START + ''' AND ''' + @P_DT_END + '''))) 
     AND (H.CD_PARTNER = ''' + @P_CD_PARTNER + ''' OR ''' + @P_CD_PARTNER + ''' = '''' OR ''' + @P_CD_PARTNER + ''' IS NULL)
     AND (L.CD_WC = ''' + @P_CD_WC + ''' OR ''' + @P_CD_WC + ''' = '''' OR ''' + @P_CD_WC + ''' IS NULL)
     AND (L.CD_WCOP = ''' + @P_CD_WCOP + ''' OR ''' + @P_CD_WCOP + ''' = '''' OR ''' + @P_CD_WCOP + ''' IS NULL)
     AND (L.CD_ITEM >= ''' + @P_CD_ITEM_START + ''' OR ''' + @P_CD_ITEM_START + ''' = '''' OR ''' + @P_CD_ITEM_START + ''' IS NULL)
     AND (L.CD_ITEM <= ''' + @P_CD_ITEM_END + ''' OR ''' + @P_CD_ITEM_END + ''' = '''' OR ''' + @P_CD_ITEM_END + ''' IS NULL)
	 AND L.NO_WO = ''' + @P_CONDITION + '''
	 '
SET @V_QUERY_5 = 'AND L.QT_PO - (L.QT_RCV + ISNULL(WR.QT_BAD,0)) = 0
'
SET @V_QUERY_6 = 'AND L.QT_PO - (L.QT_RCV + ISNULL(WR.QT_BAD,0)) > 0
'

IF (@P_TAB_NAME = 'NO_PO')
BEGIN
	IF (@P_YN_RCV = '' OR @P_YN_RCV IS NULL OR @P_YN_RCV = '001')
	BEGIN
		SET @V_QUERY = @V_QUERY_1
	END
	ELSE IF (@P_YN_RCV = '002')
	BEGIN
		SET @V_QUERY = @V_QUERY_1 + @V_QUERY_5
	END
	ELSE IF (@P_YN_RCV = '003')
	BEGIN
		SET @V_QUERY = @V_QUERY_1 + @V_QUERY_6
	END
END
IF (@P_TAB_NAME = 'CD_PARTNER')
BEGIN
	IF (@P_YN_RCV = '' OR @P_YN_RCV IS NULL OR @P_YN_RCV = '001')
	BEGIN
		SET @V_QUERY = @V_QUERY_2
	END
	ELSE IF (@P_YN_RCV = '002')
	BEGIN
		SET @V_QUERY = @V_QUERY_2 + @V_QUERY_5
	END
	ELSE IF (@P_YN_RCV = '003')
	BEGIN
		SET @V_QUERY = @V_QUERY_2 + @V_QUERY_6
	END
END
IF (@P_TAB_NAME = 'CD_ITEM')
BEGIN
	IF (@P_YN_RCV = '' OR @P_YN_RCV IS NULL OR @P_YN_RCV = '001')
	BEGIN
		SET @V_QUERY = @V_QUERY_3
	END
	ELSE IF (@P_YN_RCV = '002')
	BEGIN
		SET @V_QUERY = @V_QUERY_3 + @V_QUERY_5
	END
	ELSE IF (@P_YN_RCV = '003')
	BEGIN
		SET @V_QUERY = @V_QUERY_3 + @V_QUERY_6
	END
END
IF (@P_TAB_NAME = 'NO_WO')
BEGIN
	IF (@P_YN_RCV = '' OR @P_YN_RCV IS NULL OR @P_YN_RCV = '001')
	BEGIN
		SET @V_QUERY = @V_QUERY_4
	END
	ELSE IF (@P_YN_RCV = '002')
	BEGIN
		SET @V_QUERY = @V_QUERY_4 + @V_QUERY_5
	END
	ELSE IF (@P_YN_RCV = '003')
	BEGIN
		SET @V_QUERY = @V_QUERY_4 + @V_QUERY_6
	END
END

PRINT @V_QUERY

EXEC SP_EXECUTESQL @V_QUERY

SET NOCOUNT OFF
