USE [NEOE]
GO
/****** Object:  StoredProcedure [NEOE].[UP_CZ_PR_OPOUT_PO_ING_H_RPT_SEL]    Script Date: 2022-12-01 오후 4:14:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO



ALTER PROCEDURE [NEOE].[UP_CZ_PR_OPOUT_PO_ING_H_RPT_SEL]
(
	@P_CD_COMPANY       NVARCHAR(7), 
	@P_TYPE_DT			NVARCHAR(3),  
	@P_DT_START         NVARCHAR(8), 
	@P_DT_END           NVARCHAR(8), 
	@P_CD_BIZAREA       NVARCHAR(7), 
	@P_CD_PLANT         NVARCHAR(7), 
	@P_CD_PARTNER       NVARCHAR(20), 
	@P_CD_WC            NVARCHAR(7), 
	@P_CD_WCOP          NVARCHAR(4), 
	@P_CD_ITEM_START    NVARCHAR(50), 
	@P_CD_ITEM_END      NVARCHAR(50), 
	@P_YN_RCV			NVARCHAR(4),   
	@P_TAB_NAME         NVARCHAR(50),
    @P_FG_LANG     NVARCHAR(4) = NULL	--언어
)
AS
-- MultiLang Call
EXEC UP_MA_LOCAL_LANGUAGE @P_FG_LANG


IF (@P_TAB_NAME = 'NO_PO')
BEGIN
	SELECT	'N' CHK, H.NO_PO
	FROM	PR_OPOUT_POH H
	INNER JOIN PR_OPOUT_POL L ON L.CD_COMPANY = @P_CD_COMPANY AND L.CD_PLANT = @P_CD_PLANT AND L.NO_PO = H.NO_PO
	LEFT JOIN (SELECT CD_COMPANY, NO_WO, CD_OP, NO_OPOUT_PO, NO_OPOUT_PO_LINE, SUM(QT_BAD) AS QT_BAD
		   FROM PR_WORK
		   GROUP BY CD_COMPANY, NO_WO, CD_OP, NO_OPOUT_PO, NO_OPOUT_PO_LINE) WR 
	ON WR.CD_COMPANY = L.CD_COMPANY AND WR.NO_WO = L.NO_WO AND WR.CD_OP = L.CD_OP AND WR.NO_OPOUT_PO = L.NO_PO AND WR.NO_OPOUT_PO_LINE = L.NO_LINE
	WHERE	H.CD_COMPANY = @P_CD_COMPANY
	AND		H.CD_PLANT = @P_CD_PLANT
    AND	  ((@P_TYPE_DT = '001' AND (H.DT_PO BETWEEN @P_DT_START AND @P_DT_END))   
     OR	   (@P_TYPE_DT = '002' AND (L.DT_DUE BETWEEN @P_DT_START AND @P_DT_END)))  
	AND    (H.CD_PARTNER = @P_CD_PARTNER OR @P_CD_PARTNER = '' OR @P_CD_PARTNER IS NULL)
	AND    (L.CD_WC = @P_CD_WC OR @P_CD_WC = '' OR @P_CD_WC IS NULL)
	AND    (L.CD_WCOP = @P_CD_WCOP OR @P_CD_WCOP = '' OR @P_CD_WCOP IS NULL)
	AND    (L.CD_ITEM >= @P_CD_ITEM_START OR @P_CD_ITEM_START = '' OR @P_CD_ITEM_START IS NULL)
	AND    (L.CD_ITEM <= @P_CD_ITEM_END OR @P_CD_ITEM_END = '' OR @P_CD_ITEM_END IS NULL)
	AND   ((@P_YN_RCV = '' OR @P_YN_RCV IS NULL OR @P_YN_RCV = '001')  
     OR    (@P_YN_RCV = '002' AND L.QT_PO - (L.QT_RCV + ISNULL(WR.QT_BAD,0)) = 0)  
     OR    (@P_YN_RCV = '003' AND L.QT_PO - (L.QT_RCV + ISNULL(WR.QT_BAD,0)) > 0))  
	GROUP BY H.NO_PO
END

ELSE IF (@P_TAB_NAME = 'CD_PARTNER')
BEGIN
	SELECT	'N' CHK, H.CD_PARTNER, A.LN_PARTNER
	FROM	PR_OPOUT_POH H
	INNER JOIN PR_OPOUT_POL L ON L.CD_COMPANY = @P_CD_COMPANY AND L.CD_PLANT = @P_CD_PLANT AND L.NO_PO = H.NO_PO
	LEFT OUTER JOIN DZSN_MA_PARTNER A ON A.CD_COMPANY = @P_CD_COMPANY AND A.CD_PARTNER = H.CD_PARTNER
	LEFT JOIN (SELECT CD_COMPANY, NO_WO, CD_OP, NO_OPOUT_PO, NO_OPOUT_PO_LINE, SUM(QT_BAD) AS QT_BAD
		   FROM PR_WORK
		   GROUP BY CD_COMPANY, NO_WO, CD_OP, NO_OPOUT_PO, NO_OPOUT_PO_LINE) WR 
	ON WR.CD_COMPANY = L.CD_COMPANY AND WR.NO_WO = L.NO_WO AND WR.CD_OP = L.CD_OP AND WR.NO_OPOUT_PO = L.NO_PO AND WR.NO_OPOUT_PO_LINE = L.NO_LINE
	WHERE	H.CD_COMPANY = @P_CD_COMPANY
	AND		H.CD_PLANT = @P_CD_PLANT
    AND	  ((@P_TYPE_DT = '001' AND (H.DT_PO BETWEEN @P_DT_START AND @P_DT_END))   
     OR	   (@P_TYPE_DT = '002' AND (L.DT_DUE BETWEEN @P_DT_START AND @P_DT_END)))  
	AND    (H.CD_PARTNER = @P_CD_PARTNER OR @P_CD_PARTNER = '' OR @P_CD_PARTNER IS NULL)
	AND    (L.CD_WC = @P_CD_WC OR @P_CD_WC = '' OR @P_CD_WC IS NULL)
	AND    (L.CD_WCOP = @P_CD_WCOP OR @P_CD_WCOP = '' OR @P_CD_WCOP IS NULL)
	AND    (L.CD_ITEM >= @P_CD_ITEM_START OR @P_CD_ITEM_START = '' OR @P_CD_ITEM_START IS NULL)
	AND    (L.CD_ITEM <= @P_CD_ITEM_END OR @P_CD_ITEM_END = '' OR @P_CD_ITEM_END IS NULL)
	AND   ((@P_YN_RCV = '' OR @P_YN_RCV IS NULL OR @P_YN_RCV = '001')  
     OR    (@P_YN_RCV = '002' AND L.QT_PO - (L.QT_RCV + ISNULL(WR.QT_BAD,0)) = 0)  
     OR    (@P_YN_RCV = '003' AND L.QT_PO - (L.QT_RCV + ISNULL(WR.QT_BAD,0)) > 0))  
	GROUP BY H.CD_PARTNER, A.LN_PARTNER
END

ELSE IF (@P_TAB_NAME = 'CD_ITEM')
BEGIN
	SELECT	'N' CHK, L.CD_ITEM, M.NM_ITEM, M.NO_DESIGN, M.STND_ITEM, M.UNIT_IM
	FROM	PR_OPOUT_POH H
	INNER JOIN PR_OPOUT_POL L ON L.CD_COMPANY = @P_CD_COMPANY AND L.CD_PLANT = @P_CD_PLANT AND L.NO_PO = H.NO_PO
	LEFT OUTER JOIN DZSN_MA_PITEM M ON M.CD_COMPANY = @P_CD_COMPANY AND M.CD_PLANT = @P_CD_PLANT AND M.CD_ITEM = L.CD_ITEM
	LEFT JOIN (SELECT CD_COMPANY, NO_WO, CD_OP, NO_OPOUT_PO, NO_OPOUT_PO_LINE, SUM(QT_BAD) AS QT_BAD
		   FROM PR_WORK
		   GROUP BY CD_COMPANY, NO_WO, CD_OP, NO_OPOUT_PO, NO_OPOUT_PO_LINE) WR 
	ON WR.CD_COMPANY = L.CD_COMPANY AND WR.NO_WO = L.NO_WO AND WR.CD_OP = L.CD_OP AND WR.NO_OPOUT_PO = L.NO_PO AND WR.NO_OPOUT_PO_LINE = L.NO_LINE
	WHERE	H.CD_COMPANY = @P_CD_COMPANY
	AND		H.CD_PLANT = @P_CD_PLANT
    AND	  ((@P_TYPE_DT = '001' AND (H.DT_PO BETWEEN @P_DT_START AND @P_DT_END))   
     OR	   (@P_TYPE_DT = '002' AND (L.DT_DUE BETWEEN @P_DT_START AND @P_DT_END)))  
	AND    (H.CD_PARTNER = @P_CD_PARTNER OR @P_CD_PARTNER = '' OR @P_CD_PARTNER IS NULL)
	AND    (L.CD_WC = @P_CD_WC OR @P_CD_WC = '' OR @P_CD_WC IS NULL)
	AND    (L.CD_WCOP = @P_CD_WCOP OR @P_CD_WCOP = '' OR @P_CD_WCOP IS NULL)
	AND    (L.CD_ITEM >= @P_CD_ITEM_START OR @P_CD_ITEM_START = '' OR @P_CD_ITEM_START IS NULL)
	AND    (L.CD_ITEM <= @P_CD_ITEM_END OR @P_CD_ITEM_END = '' OR @P_CD_ITEM_END IS NULL)
	AND   ((@P_YN_RCV = '' OR @P_YN_RCV IS NULL OR @P_YN_RCV = '001')  
     OR    (@P_YN_RCV = '002' AND L.QT_PO - (L.QT_RCV + ISNULL(WR.QT_BAD,0)) = 0)  
     OR    (@P_YN_RCV = '003' AND L.QT_PO - (L.QT_RCV + ISNULL(WR.QT_BAD,0)) > 0))  
	GROUP BY L.CD_ITEM, M.NM_ITEM, M.NO_DESIGN, M.STND_ITEM, M.UNIT_IM
END

ELSE IF (@P_TAB_NAME = 'NO_WO')
BEGIN
	SELECT	'N' CHK, L.NO_WO
	FROM	PR_OPOUT_POH H
	INNER JOIN PR_OPOUT_POL L ON L.CD_COMPANY = H.CD_COMPANY AND L.CD_PLANT = H.CD_PLANT AND L.NO_PO = H.NO_PO
	LEFT JOIN (SELECT CD_COMPANY, NO_WO, CD_OP, NO_OPOUT_PO, NO_OPOUT_PO_LINE, SUM(QT_BAD) AS QT_BAD
		   FROM PR_WORK
		   GROUP BY CD_COMPANY, NO_WO, CD_OP, NO_OPOUT_PO, NO_OPOUT_PO_LINE) WR 
	ON WR.CD_COMPANY = L.CD_COMPANY AND WR.NO_WO = L.NO_WO AND WR.CD_OP = L.CD_OP AND WR.NO_OPOUT_PO = L.NO_PO AND WR.NO_OPOUT_PO_LINE = L.NO_LINE
	WHERE	H.CD_COMPANY = @P_CD_COMPANY
	AND		H.CD_PLANT = @P_CD_PLANT
    AND	  ((@P_TYPE_DT = '001' AND (H.DT_PO BETWEEN @P_DT_START AND @P_DT_END))   
     OR	   (@P_TYPE_DT = '002' AND (L.DT_DUE BETWEEN @P_DT_START AND @P_DT_END)))  
	AND		(H.CD_PARTNER = @P_CD_PARTNER OR @P_CD_PARTNER = '' OR @P_CD_PARTNER IS NULL)
	AND		(L.CD_WC = @P_CD_WC OR @P_CD_WC = '' OR @P_CD_WC IS NULL)
	AND		(L.CD_WCOP = @P_CD_WCOP OR @P_CD_WCOP = '' OR @P_CD_WCOP IS NULL)
	AND		(L.CD_ITEM >= @P_CD_ITEM_START OR @P_CD_ITEM_START = '' OR @P_CD_ITEM_START IS NULL)
	AND		(L.CD_ITEM <= @P_CD_ITEM_END OR @P_CD_ITEM_END = '' OR @P_CD_ITEM_END IS NULL)	
	AND   ((@P_YN_RCV = '' OR @P_YN_RCV IS NULL OR @P_YN_RCV = '001')  
     OR    (@P_YN_RCV = '002' AND L.QT_PO - (L.QT_RCV + ISNULL(WR.QT_BAD,0)) = 0)  
     OR    (@P_YN_RCV = '003' AND L.QT_PO - (L.QT_RCV + ISNULL(WR.QT_BAD,0)) > 0))  
	GROUP BY L.NO_WO
END
