USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_PR_ASSEMBLING_ID_OLD_SUB_S]    Script Date: 2017-01-05 오후 5:48:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_PR_ASSEMBLING_ID_OLD_SUB_S]          
(
	@P_CD_COMPANY		NVARCHAR(7),
	@P_CD_PLANT			NVARCHAR(7),
	@P_CD_ITEM			NVARCHAR(20),
	@P_NO_ID			NVARCHAR(10),
	@P_YN_USE			NVARCHAR(1)
)  
AS
   
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT 'N' AS S,
	   ID.NO_ID,
	   ID.CD_ITEM,
	   MI.NM_ITEM,
	   ID.NO_HEAT,
	   ID.NO_LOT,
	   ID.DC_RMK,
	   (CASE WHEN MD.NO_ID IS NULL THEN 'N' ELSE 'Y' END) AS YN_USE
FROM CZ_PR_ASSEMBLING_ID_OLD ID
LEFT JOIN MA_PITEM MI ON MI.CD_COMPANY = ID.CD_COMPANY AND MI.CD_PLANT = ID.CD_PLANT AND MI.CD_ITEM = ID.CD_ITEM
LEFT JOIN (SELECT AD.CD_COMPANY, AD.NO_ID_C AS NO_ID
		   FROM CZ_PR_ASSEMBLING_DATA AD
		   UNION
		   SELECT AL.CD_COMPANY, AL.NO_ID
		   FROM CZ_PR_ASSEMBLING_SA_SOL AL) MD ON MD.CD_COMPANY = ID.CD_COMPANY AND MD.NO_ID = ID.NO_ID
WHERE ID.CD_COMPANY = @P_CD_COMPANY
AND ID.CD_PLANT = @P_CD_PLANT
AND (ISNULL(@P_CD_ITEM, '') = '' OR ID.CD_ITEM = @P_CD_ITEM)
AND (ISNULL(@P_NO_ID, '') = '' OR ID.NO_ID = @P_NO_ID)
AND (ISNULL(@P_YN_USE, '') = '' OR (@P_YN_USE = 'Y' AND MD.NO_ID IS NOT NULL) OR (@P_YN_USE = 'N' AND MD.NO_ID IS NULL))


GO

