USE [NEOE]
GO

/****** Object:  Table [NEOE].[CZ_FI_CARD_VERIFY]    Script Date: 2021-09-02 오후 2:06:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [NEOE].[CZ_FI_CARD_VERIFY](
	[CD_COMPANY] [nvarchar](7) NOT NULL,
	[ACCT_NO] [nvarchar](20) NOT NULL,
	[ADMIN_NO] [nvarchar](20) NOT NULL,
	[YN_VERIFY] [nvarchar](1) NULL,
	[DC_RMK] [nvarchar](200) NULL,
	[ID_INSERT] [nvarchar](15) NULL,
	[DTS_INSERT] [nvarchar](14) NULL,
	[ID_UPDATE] [nvarchar](15) NULL,
	[DTS_UPDATE] [nvarchar](14) NULL,
 CONSTRAINT [PK_CZ_FI_CARD_VERIFY] PRIMARY KEY CLUSTERED 
(
	[CD_COMPANY] ASC,
	[ACCT_NO] ASC,
	[ADMIN_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


