//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:2.0.50727.5485
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 이 소스 코드가 Microsoft.VSDesigner, 버전 2.0.50727.5485에서 자동으로 생성되었습니다.
// 
#pragma warning disable 1591

namespace pur.WebServiceCNP {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FI_CNPPurchaseRequest_providers_CNPPurchaseRequest_Provider_Binder", Namespace="FI.CNPPurchaseRequest.providers:CNPPurchaseRequest_Provider")]
    public partial class FICNPPurchaseRequestprovidersCNPPurchaseRequest_Provider : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CNPPurchaseRequest_TgtGW_FLOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public FICNPPurchaseRequestprovidersCNPPurchaseRequest_Provider() {
            this.Url = global::pur.Settings.Default.P_PU_IV_MNG_WebServiceCNP_LIVE_FI_CNPPurchaseRequest_providers_CNPPurchaseRequest_Provider;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CNPPurchaseRequest_TgtGW_FLCompletedEventHandler CNPPurchaseRequest_TgtGW_FLCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("FI_CNPPurchaseRequest_providers_CNPPurchaseRequest_Provider_Binder_CNPPurchaseReq" +
            "uest_TgtGW_FL", RequestNamespace="FI.CNPPurchaseRequest.providers:CNPPurchaseRequest_Provider", ResponseNamespace="FI.CNPPurchaseRequest.providers:CNPPurchaseRequest_Provider", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("MTYPE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string CNPPurchaseRequest_TgtGW_FL([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string ERP_PKEY, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string SABUN, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string FORM_TYPE, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string JI_PAY, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string KO_PAY, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string PARTNER, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string REQ_DATE, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string REQ_CONDITION, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string BANK_NM, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string BANK_NO, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string BANK_NAME, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string PHONE_NO, [System.Xml.Serialization.XmlElementAttribute("ITEMS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] ITEMS[] ITEMS, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] out string MTEXT) {
            object[] results = this.Invoke("CNPPurchaseRequest_TgtGW_FL", new object[] {
                        ERP_PKEY,
                        SABUN,
                        FORM_TYPE,
                        JI_PAY,
                        KO_PAY,
                        PARTNER,
                        REQ_DATE,
                        REQ_CONDITION,
                        BANK_NM,
                        BANK_NO,
                        BANK_NAME,
                        PHONE_NO,
                        ITEMS});
            MTEXT = ((string)(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CNPPurchaseRequest_TgtGW_FLAsync(string ERP_PKEY, string SABUN, string FORM_TYPE, string JI_PAY, string KO_PAY, string PARTNER, string REQ_DATE, string REQ_CONDITION, string BANK_NM, string BANK_NO, string BANK_NAME, string PHONE_NO, ITEMS[] ITEMS) {
            this.CNPPurchaseRequest_TgtGW_FLAsync(ERP_PKEY, SABUN, FORM_TYPE, JI_PAY, KO_PAY, PARTNER, REQ_DATE, REQ_CONDITION, BANK_NM, BANK_NO, BANK_NAME, PHONE_NO, ITEMS, null);
        }
        
        /// <remarks/>
        public void CNPPurchaseRequest_TgtGW_FLAsync(string ERP_PKEY, string SABUN, string FORM_TYPE, string JI_PAY, string KO_PAY, string PARTNER, string REQ_DATE, string REQ_CONDITION, string BANK_NM, string BANK_NO, string BANK_NAME, string PHONE_NO, ITEMS[] ITEMS, object userState) {
            if ((this.CNPPurchaseRequest_TgtGW_FLOperationCompleted == null)) {
                this.CNPPurchaseRequest_TgtGW_FLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCNPPurchaseRequest_TgtGW_FLOperationCompleted);
            }
            this.InvokeAsync("CNPPurchaseRequest_TgtGW_FL", new object[] {
                        ERP_PKEY,
                        SABUN,
                        FORM_TYPE,
                        JI_PAY,
                        KO_PAY,
                        PARTNER,
                        REQ_DATE,
                        REQ_CONDITION,
                        BANK_NM,
                        BANK_NO,
                        BANK_NAME,
                        PHONE_NO,
                        ITEMS}, this.CNPPurchaseRequest_TgtGW_FLOperationCompleted, userState);
        }
        
        private void OnCNPPurchaseRequest_TgtGW_FLOperationCompleted(object arg) {
            if ((this.CNPPurchaseRequest_TgtGW_FLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CNPPurchaseRequest_TgtGW_FLCompleted(this, new CNPPurchaseRequest_TgtGW_FLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5485")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="FI.CNPPurchaseRequest.providers:CNPPurchaseRequest_Provider")]
    public partial class ITEMS {
        
        private string aRR_DATEField;
        
        private string aRR_PRODUCTIONField;
        
        private string aRR_AMTField;
        
        private string aRR_UNITField;
        
        private string aRR_PAYField;
        
        private string aRR_VATField;
        
        private string aRR_SUMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string ARR_DATE {
            get {
                return this.aRR_DATEField;
            }
            set {
                this.aRR_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string ARR_PRODUCTION {
            get {
                return this.aRR_PRODUCTIONField;
            }
            set {
                this.aRR_PRODUCTIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string ARR_AMT {
            get {
                return this.aRR_AMTField;
            }
            set {
                this.aRR_AMTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string ARR_UNIT {
            get {
                return this.aRR_UNITField;
            }
            set {
                this.aRR_UNITField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string ARR_PAY {
            get {
                return this.aRR_PAYField;
            }
            set {
                this.aRR_PAYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string ARR_VAT {
            get {
                return this.aRR_VATField;
            }
            set {
                this.aRR_VATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string ARR_SUM {
            get {
                return this.aRR_SUMField;
            }
            set {
                this.aRR_SUMField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    public delegate void CNPPurchaseRequest_TgtGW_FLCompletedEventHandler(object sender, CNPPurchaseRequest_TgtGW_FLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CNPPurchaseRequest_TgtGW_FLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CNPPurchaseRequest_TgtGW_FLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string MTEXT {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591