USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_PU_IV_MNGH_S]    Script Date: 2016-11-17 오후 5:00:32 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/*******************************************                              
*********************************************/        
ALTER PROCEDURE [NEOE].[SP_CZ_PU_IV_MNGH_S]        
(             
	@P_CD_COMPANY           NVARCHAR(7),
	@P_DT_PROCESS_FROM      NVARCHAR(8),        
	@P_DT_PROCESS_TO        NVARCHAR(8),        
	@P_CD_PARTNER           NVARCHAR(20),
	@P_FG_TRANS             NVARCHAR(3),        
	@P_TP_AIS               NVARCHAR(1),
	@P_CD_DEPT              NVARCHAR(12),        
	@P_NO_EMP               NVARCHAR(10),
	@P_NO_IV				NVARCHAR(20),
	@P_NO_PO				NVARCHAR(20),
	@P_CD_PJT				NVARCHAR(20),
	@P_YN_BAN               NVARCHAR(1) = NULL
)        
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

;WITH A AS
(
	SELECT *
	FROM PU_IVH IH
	WHERE IH.CD_COMPANY = @P_CD_COMPANY
	AND IH.DT_PROCESS BETWEEN @P_DT_PROCESS_FROM AND @P_DT_PROCESS_TO
	AND (ISNULL(@P_CD_PARTNER, '') = '' OR IH.CD_PARTNER = @P_CD_PARTNER)
	AND (ISNULL(@P_FG_TRANS, '') = '' OR IH.FG_TRANS = @P_FG_TRANS)
	AND (ISNULL(@P_TP_AIS, '') = '' OR IH.TP_AIS = @P_TP_AIS)
	AND (ISNULL(@P_CD_DEPT, '') = '' OR IH.CD_DEPT = @P_CD_DEPT)
	AND (ISNULL(@P_NO_EMP, '') = '' OR IH.NO_EMP = @P_NO_EMP)
	AND (ISNULL(@P_NO_IV, '') = '' OR IH.NO_IV = @P_NO_IV)
)
SELECT 'N' AS S,
	   IH.NO_IV,
	   IH.DT_PROCESS,
	   IH.CD_PARTNER,
	   MP.LN_PARTNER,
	   MP.NO_COMPANY,
	   IH.FG_TRANS,
	   DT.NM_SYSDEF AS NM_TRANS,
	   IH.FG_TAX,
	   DT1.NM_SYSDEF AS NM_TAX,
	   IH.CD_EXCH,
	   DT2.NM_SYSDEF AS NM_EXCH,
	   IH.RT_EXCH,
	   IH.AM_EX,
	   IH.AM_K,
	   IH.VAT_TAX,
	   (IH.AM_K + IH.VAT_TAX) AS AM_TOTAL,
	   ISNULL(IL.AM_EX_ADPAY, 0) AS AM_EX_ADPAY,
	   ISNULL(IL.AM_ADPAY, 0) AS AM_ADPAY,
	   IH.TP_AIS,
	   IH.CD_DOCU,
	   FD.NO_DOCU,
	   ISNULL(FD.AM_EX, 0) AS AM_EXDOCU,
	   ISNULL(FD.AM_DOCU, 0) AS AM_DOCU,
	   ISNULL(FD1.AM_EXBAN, 0) AS AM_EXBAN,
	   ISNULL(FD1.AM_BAN, 0) AS AM_BAN,
	   ISNULL(FD1.AM_EXBAN_ADPAY, 0) AS AM_EXBAN_ADPAY,
	   ISNULL(FD1.AM_BAN_ADPAY, 0) AS AM_BAN_ADPAY,
	   ME.CD_DEPT,
	   MD.NM_DEPT,
	   IH.NO_EMP,
	   ME.NM_KOR AS NM_EMP,
	   IH.DC_RMK,
	   IH.DT_PAY_PREARRANGED,
	   IH.DT_DUE,

	   IH.YN_JEONJA,
	   IH.FG_PAYBILL,
	   IH.NO_BIZAREA,
	   IH.TXT_USERDEF1,
	   IH.DTS_INSERT
FROM A IH
LEFT JOIN (SELECT IL.CD_COMPANY, IL.NO_IV,
				  SUM(PL.AM_EX_ADPAY) AS AM_EX_ADPAY,
				  SUM(PL.AM_ADPAY) AS AM_ADPAY
		   FROM PU_IVL IL
		   JOIN PU_POL PL ON PL.CD_COMPANY = IL.CD_COMPANY AND PL.NO_PO = IL.NO_PO AND PL.NO_LINE = IL.NO_POLINE
		   GROUP BY IL.CD_COMPANY, IL.NO_IV) IL
ON IL.CD_COMPANY = IH.CD_COMPANY AND IL.NO_IV = IH.NO_IV
LEFT JOIN MA_PARTNER MP ON MP.CD_COMPANY = IH.CD_COMPANY AND MP.CD_PARTNER = IH.CD_PARTNER
LEFT JOIN MA_EMP ME ON ME.CD_COMPANY = IH.CD_COMPANY AND ME.NO_EMP = IH.NO_EMP
LEFT JOIN MA_DEPT MD ON MD.CD_COMPANY = IH.CD_COMPANY AND MD.CD_DEPT = IH.CD_DEPT
LEFT JOIN MA_CODEDTL DT ON DT.CD_COMPANY = IH.CD_COMPANY AND DT.CD_FIELD = 'PU_C000016' AND DT.CD_SYSDEF = IH.FG_TRANS
LEFT JOIN MA_CODEDTL DT1 ON DT1.CD_COMPANY = IH.CD_COMPANY AND DT1.CD_FIELD = 'MA_B000046' AND DT1.CD_SYSDEF = IH.FG_TAX
LEFT JOIN MA_CODEDTL DT2 ON DT2.CD_COMPANY = IH.CD_COMPANY AND DT2.CD_FIELD = 'MA_B000005' AND DT2.CD_SYSDEF = IH.CD_EXCH
LEFT JOIN (SELECT FD.CD_COMPANY, FD.NO_MDOCU, FD.NO_DOCU,
				  SUM(BH.AM_EX) AS AM_EX,
				  SUM(BH.AM_DOCU) AS AM_DOCU,
				  SUM(BH.AM_BAN) AS AM_BAN
	       FROM FI_DOCU FD
		   JOIN FI_BANH BH ON BH.CD_COMPANY = FD.CD_COMPANY AND BH.NO_DOCU = FD.NO_DOCU AND BH.NO_DOLINE = FD.NO_DOLINE
		   GROUP BY FD.CD_COMPANY, FD.NO_MDOCU, FD.NO_DOCU) FD
ON FD.CD_COMPANY = IH.CD_COMPANY AND FD.NO_MDOCU = IH.NO_IV
LEFT JOIN (SELECT FD.CD_COMPANY,
				  FD.NO_BDOCU,
				  SUM(CASE WHEN AB.NO_BILLS IS NULL THEN FD.AM_EXDO ELSE 0 END) AS AM_EXBAN,
				  SUM(CASE WHEN AB.NO_BILLS IS NULL THEN (FD.AM_CR + FD.AM_DR) ELSE 0 END) AS AM_BAN,
				  SUM(CASE WHEN AB.NO_BILLS IS NOT NULL THEN FD.AM_EXDO ELSE 0 END) AS AM_EXBAN_ADPAY,
				  SUM(CASE WHEN AB.NO_BILLS IS NOT NULL THEN (FD.AM_CR + FD.AM_DR) ELSE 0 END) AS AM_BAN_ADPAY  
		   FROM FI_DOCU FD
		   LEFT JOIN CZ_PU_ADPAYMENT_BILL_H AB ON AB.CD_COMPANY = FD.CD_COMPANY AND AB.NO_BILLS = FD.NO_MDOCU
		   GROUP BY FD.CD_COMPANY, FD.NO_BDOCU) FD1
ON FD1.CD_COMPANY = FD.CD_COMPANY AND FD1.NO_BDOCU = FD.NO_DOCU
WHERE 1=1
AND ((ISNULL(@P_YN_BAN, '') = '') OR (@P_YN_BAN = 'Y' AND FD.AM_DOCU = FD.AM_BAN) OR (@P_YN_BAN = 'N' AND FD.AM_DOCU <> FD.AM_BAN))
AND (ISNULL(@P_NO_PO, '') = '' OR EXISTS (SELECT 1 
										  FROM PU_IVL
									      WHERE CD_COMPANY = IH.CD_COMPANY
										  AND NO_IV = IH.NO_IV
										  AND NO_PO LIKE @P_NO_PO + '%'))
AND (ISNULL(@P_CD_PJT, '') = '' OR EXISTS (SELECT 1 
										   FROM PU_IVL
									       WHERE CD_COMPANY = IH.CD_COMPANY
										   AND NO_IV = IH.NO_IV
										   AND CD_PJT = @P_CD_PJT))

GO