USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_PR_MATCHING_ITEM_XML]    Script Date: 2016-11-30 오후 5:22:08 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




ALTER PROCEDURE [NEOE].[SP_CZ_PR_MATCHING_ITEM_XML] 
(
	@P_XML			XML, 
	@P_ID_USER		NVARCHAR(10), 
    @DOC			INT = NULL
) 
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

EXEC SP_XML_PREPAREDOCUMENT @DOC OUTPUT, @P_XML 

-- ================================================== DELETE
DELETE A 
FROM CZ_PR_MATCHING_ITEM A 
JOIN OPENXML (@DOC, '/XML/D', 2) 
        WITH (CD_COMPANY	NVARCHAR(7),
			  CD_PLANT		NVARCHAR(7),
			  CD_ITEM		NVARCHAR(20)) B 
 ON A.CD_COMPANY = B.CD_COMPANY
AND A.CD_PLANT = B.CD_PLANT
AND A.CD_ITEM = B.CD_ITEM

-- ================================================== INSERT
INSERT INTO CZ_PR_MATCHING_ITEM 
(
	CD_COMPANY,
	CD_PLANT,
	CD_ITEM,
	CD_PITEM_L,
	CD_PITEM_C,
	CD_PITEM_R,
	NUM_SPEC1_MIN,
	NUM_SPEC1_MAX,
	NUM_SPEC2_MIN,
	NUM_SPEC2_MAX,
	ID_INSERT,
	DTS_INSERT
)
SELECT CD_COMPANY,
	   CD_PLANT,
	   CD_ITEM,
	   CD_PITEM_L,
	   CD_PITEM_C,
	   CD_PITEM_R,
	   NUM_SPEC1_MIN,
	   NUM_SPEC1_MAX,
	   NUM_SPEC2_MIN,
	   NUM_SPEC2_MAX,
       @P_ID_USER, 
       NEOE.SF_SYSDATE(GETDATE()) 
FROM OPENXML (@DOC, '/XML/I', 2) 
        WITH (CD_COMPANY		NVARCHAR(7),
			  CD_PLANT			NVARCHAR(7),
			  CD_ITEM			NVARCHAR(20),
			  CD_PITEM_L		NVARCHAR(20),
			  CD_PITEM_C		NVARCHAR(20),
			  CD_PITEM_R		NVARCHAR(20),
			  NUM_SPEC1_MIN		NUMERIC(7, 4),
			  NUM_SPEC1_MAX		NUMERIC(7, 4),
			  NUM_SPEC2_MIN		NUMERIC(7, 4),
			  NUM_SPEC2_MAX		NUMERIC(7, 4))

-- ================================================== UPDATE    
UPDATE A 
   SET A.CD_PITEM_L = B.CD_PITEM_L,
	   A.CD_PITEM_C = B.CD_PITEM_C,
	   A.CD_PITEM_R = B.CD_PITEM_R,
	   A.NUM_SPEC1_MIN = B.NUM_SPEC1_MIN,
	   A.NUM_SPEC1_MAX = B.NUM_SPEC1_MAX,
	   A.NUM_SPEC2_MIN = B.NUM_SPEC2_MIN,
	   A.NUM_SPEC2_MAX = B.NUM_SPEC2_MAX,
	   A.ID_UPDATE = @P_ID_USER, 
	   A.DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE())
FROM CZ_PR_MATCHING_ITEM A 
JOIN OPENXML (@DOC, '/XML/U', 2) 
        WITH (CD_COMPANY		NVARCHAR(7),
			  CD_PLANT			NVARCHAR(7),
			  CD_ITEM			NVARCHAR(20),
			  CD_PITEM_L		NVARCHAR(20),
			  CD_PITEM_C		NVARCHAR(20),
			  CD_PITEM_R		NVARCHAR(20),
			  NUM_SPEC1_MIN		NUMERIC(7, 4),
			  NUM_SPEC1_MAX		NUMERIC(7, 4),
			  NUM_SPEC2_MIN		NUMERIC(7, 4),
			  NUM_SPEC2_MAX		NUMERIC(7, 4)) B 
 ON A.CD_COMPANY = B.CD_COMPANY
AND A.CD_PLANT = B.CD_PLANT
AND A.CD_ITEM = B.CD_ITEM

EXEC SP_XML_REMOVEDOCUMENT @DOC 

GO

