USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_MM_MONTHLY_STOCK_RPT_PIVOT_S]    Script Date: 2017-01-05 오후 5:48:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_PR_MATCHING_ITEM_S]          
(
	@P_CD_COMPANY	NVARCHAR(7),
	@P_CD_PLANT		NVARCHAR(7),
	@P_CD_ITEM		NVARCHAR(20),
	@P_CD_PITEM_L	NVARCHAR(20) = NULL,
	@P_CD_PITEM_C	NVARCHAR(20) = NULL,
	@P_CD_PITEM_R	NVARCHAR(20) = NULL
)  
AS
   
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT MC.CD_COMPANY,
	   MC.CD_PLANT,
	   MC.CD_ITEM,
	   MI.NM_ITEM,
	   MC.CD_PITEM_L,
	   MI1.NM_ITEM AS NM_PITEM_L,
	   MC.CD_PITEM_C,
	   MI2.NM_ITEM AS NM_PITEM_C,
	   MC.CD_PITEM_R,
	   MI3.NM_ITEM AS NM_PITEM_R,
	   MC.NUM_SPEC1_MIN,
	   MC.NUM_SPEC1_MAX,
	   MC.NUM_SPEC2_MIN,
	   MC.NUM_SPEC2_MAX
FROM CZ_PR_MATCHING_ITEM MC
LEFT JOIN MA_PITEM MI ON MI.CD_COMPANY = MC.CD_COMPANY AND MI.CD_PLANT = MC.CD_PLANT AND MI.CD_ITEM = MC.CD_ITEM
LEFT JOIN MA_PITEM MI1 ON MI1.CD_COMPANY = MC.CD_COMPANY AND MI1.CD_PLANT = MC.CD_PLANT AND MI1.CD_ITEM = MC.CD_PITEM_L
LEFT JOIN MA_PITEM MI2 ON MI2.CD_COMPANY = MC.CD_COMPANY AND MI2.CD_PLANT = MC.CD_PLANT AND MI2.CD_ITEM = MC.CD_PITEM_C
LEFT JOIN MA_PITEM MI3 ON MI3.CD_COMPANY = MC.CD_COMPANY AND MI3.CD_PLANT = MC.CD_PLANT AND MI3.CD_ITEM = MC.CD_PITEM_R
WHERE MC.CD_COMPANY = @P_CD_COMPANY
AND MC.CD_PLANT = @P_CD_PLANT
AND (ISNULL(@P_CD_ITEM, '') = '' OR MC.CD_ITEM = @P_CD_ITEM)
AND (ISNULL(@P_CD_PITEM_L, '') = '' OR MC.CD_PITEM_L = @P_CD_PITEM_L)
AND (ISNULL(@P_CD_PITEM_C, '') = '' OR MC.CD_PITEM_C = @P_CD_PITEM_C)
AND (ISNULL(@P_CD_PITEM_R, '') = '' OR MC.CD_PITEM_R = @P_CD_PITEM_R)

GO

