USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_IV_SUB_EXCH_S]    Script Date: 2016-05-24 오전 10:34:32 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER PROCEDURE [NEOE].[SP_CZ_SA_IV_SUB_EXCH_S]
(      
    @P_CD_COMPANY   NVARCHAR(7),      
    @P_YYMMDD       NVARCHAR(10),   
    @P_CD_EXCH      NVARCHAR(10), 
    @P_RT_EXCH      NUMERIC(17,4) OUTPUT -- 환율
)
AS  

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

DECLARE @V_RATE_BASE  NUMERIC(17, 4)  
DECLARE @V_CD_EXCH NVARCHAR(3)

SELECT @V_RATE_BASE = (CASE WHEN CURR_SOUR = '002' THEN RATE_BASE ELSE ROUND(RATE_BASE, 2) END),
	   @V_CD_EXCH = CURR_SOUR 
FROM MA_EXCHANGE 
WHERE CD_COMPANY = @P_CD_COMPANY 
AND YYMMDD = @P_YYMMDD 
AND CURR_SOUR = @P_CD_EXCH 
AND CURR_DEST = '000'
AND NO_SEQ = 1

IF ( @P_CD_EXCH = '000' OR @V_RATE_BASE IS NULL )
BEGIN
	SET @P_RT_EXCH = 1
END
ELSE
BEGIN 
	SET @P_RT_EXCH = @V_RATE_BASE 
END

GO