USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_PACK_REGH_U]    Script Date: 2015-09-11 오후 1:17:04 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_SA_PACK_REGH_U]
(
	@P_CD_COMPANY			NVARCHAR(7),
	@P_NO_GIR				NVARCHAR(20),
	@P_NO_PACK				NUMERIC(5, 0),
	@P_NM_PACK				NUMERIC(5, 0),
	@P_DT_PACK				NVARCHAR(8), 
	@P_CD_TYPE				NVARCHAR(3),
	@P_CD_SIZE				NVARCHAR(3),
	@P_QT_NET_WEIGHT		NUMERIC(17, 4), 
	@P_QT_GROSS_WEIGHT		NUMERIC(17, 4),
	@P_QT_WIDTH				NUMERIC(17, 4),
	@P_QT_LEGTH				NUMERIC(17, 4),
	@P_QT_HEIGHT			NUMERIC(17, 4),
	@P_DC_RMK				NVARCHAR(MAX), 
	@P_ID_UPDATE			NVARCHAR(15)
) 
AS 

UPDATE CZ_SA_PACKH
SET    NM_PACK = @P_NM_PACK,
	   DT_PACK = @P_DT_PACK,
	   CD_TYPE = @P_CD_TYPE,	
	   CD_SIZE = @P_CD_SIZE,			
	   QT_NET_WEIGHT = @P_QT_NET_WEIGHT,		
	   QT_GROSS_WEIGHT = @P_QT_GROSS_WEIGHT,			
	   QT_WIDTH = @P_QT_WIDTH, 			
	   QT_LENGTH = @P_QT_LEGTH,				
	   QT_HEIGHT = @P_QT_HEIGHT,			
	   DC_RMK = @P_DC_RMK, 
	   ID_UPDATE = @P_ID_UPDATE, 
	   DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE())
WHERE CD_COMPANY = @P_CD_COMPANY 
AND NO_GIR = @P_NO_GIR
AND NO_PACK = @P_NO_PACK

IF EXISTS (SELECT 1 FROM CZ_SA_GIRH_PACK_DETAIL WHERE CD_COMPANY = @P_CD_COMPANY AND NO_GIR = @P_NO_GIR)
BEGIN
	UPDATE CZ_SA_GIRH_PACK_DETAIL
	SET DT_PACKING = NEOE.SF_SYSDATE(GETDATE()),
	    NO_PACK_EMP = @P_ID_UPDATE,
		DC_RESULT = STUFF((SELECT ' SIZE:'
								  + (CASE CD_TYPE WHEN '002' THEN '(P)' WHEN '003' THEN '(W)' ELSE '' END)
								  + FORMAT(QT_WIDTH, 'g15')
								  + ' X ' 
								  + FORMAT(QT_LENGTH, 'g15')
								  + ' X '
								  + FORMAT(QT_HEIGHT, 'g15')
								  + ' (MM), KG:'
								  + FORMAT(QT_GROSS_WEIGHT, 'g15')
								  + CHAR(10)
						   FROM CZ_SA_PACKH
						   WHERE CD_COMPANY = @P_CD_COMPANY
						   AND NO_GIR = @P_NO_GIR 
						   FOR XML PATH(''), TYPE).value('.', 'nvarchar(max)'), 1, 1, '')
	WHERE CD_COMPANY = @P_CD_COMPANY
	AND NO_GIR = @P_NO_GIR
END
ELSE
BEGIN
	UPDATE CZ_SA_GIRH_WORK_DETAIL
	SET DT_PACKING = NEOE.SF_SYSDATE(GETDATE()),
	    NO_PACK_EMP = @P_ID_UPDATE,
		DC_RESULT = STUFF((SELECT ' SIZE:'
								  + (CASE CD_TYPE WHEN '002' THEN '(P)' WHEN '003' THEN '(W)' ELSE '' END)
								  + FORMAT(QT_WIDTH, 'g15')
								  + ' X ' 
								  + FORMAT(QT_LENGTH, 'g15')
								  + ' X '
								  + FORMAT(QT_HEIGHT, 'g15')
								  + ' (MM), KG:'
								  + FORMAT(QT_GROSS_WEIGHT, 'g15')
								  + CHAR(10)
						   FROM CZ_SA_PACKH
						   WHERE CD_COMPANY = @P_CD_COMPANY
						   AND NO_GIR = @P_NO_GIR 
						   FOR XML PATH(''), TYPE).value('.', 'nvarchar(max)'), 1, 1, '')
	WHERE CD_COMPANY = @P_CD_COMPANY
	AND NO_GIR = @P_NO_GIR

	EXEC SP_CZ_SA_PACK_REG_MSG @P_CD_COMPANY, @P_NO_GIR
END

GO

