USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_PACK_LOG]    Script Date: 2018-01-26 오후 4:16:52 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO





ALTER PROCEDURE [NEOE].[SP_CZ_SA_PACK_LOG]  
(  
    @P_CD_COMPANY   NVARCHAR(7),
    @P_NO_GIR       NVARCHAR(20),
	@P_ID_DELETE	NVARCHAR(15),
	@P_NM_PROCEDURE	NVARCHAR(200)
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

DECLARE @V_ERRMSG   VARCHAR(255)   -- ERROR 메시지

BEGIN TRAN SP_CZ_SA_PACK_LOG
BEGIN TRY

INSERT INTO CZ_SA_PACKH_LOG
(
	CD_COMPANY,
	NO_GIR,
	NO_PACK,
	NM_PACK,
	DT_PACK,
	CD_TYPE,
	CD_SIZE,
	QT_NET_WEIGHT,
	QT_GROSS_WEIGHT,
	QT_WIDTH,
	QT_LENGTH,
	QT_HEIGHT,
	CD_LOCATION,
	DC_RMK,
	YN_OUTSOURCING,
	NO_GIR_ORG,
	NO_PACK_ORG,
	NO_WOODEN,
	ID_INSERT,
	DTS_INSERT,
	ID_UPDATE,
	DTS_UPDATE,
	ID_DELETE,
	DTS_DELETE,
	NM_PROCEDURE
)
SELECT CD_COMPANY, 
	   NO_GIR, 
	   NO_PACK, 
	   NM_PACK, 
	   DT_PACK, 
	   CD_TYPE, 
	   CD_SIZE, 
	   QT_NET_WEIGHT, 
	   QT_GROSS_WEIGHT, 
	   QT_WIDTH, 
	   QT_LENGTH, 
	   QT_HEIGHT, 
	   CD_LOCATION, 
	   DC_RMK,
	   YN_OUTSOURCING,
	   NO_GIR_ORG,
	   NO_PACK_ORG,
	   NO_WOODEN,
	   ID_INSERT,
	   DTS_INSERT,
	   ID_UPDATE,
	   DTS_UPDATE,
	   @P_ID_DELETE,
	   NEOE.SF_SYSDATE(GETDATE()),
	   @P_NM_PROCEDURE
FROM CZ_SA_PACKH
WHERE CD_COMPANY = @P_CD_COMPANY
AND NO_GIR = @P_NO_GIR

INSERT INTO CZ_SA_PACKL_LOG
(
	CD_COMPANY, 
	NO_GIR, 
	NO_PACK, 
	SEQ_GIR, 
	CD_ITEM, 
	QT_PACK, 
	NO_FILE, 
	NO_QTLINE, 
	ID_INSERT, 
	DTS_INSERT, 
	ID_UPDATE, 
	DTS_UPDATE, 
	ID_DELETE, 
	DTS_DELETE, 
	NM_PROCEDURE
)
SELECT CD_COMPANY, 
	   NO_GIR, 
	   NO_PACK, 
	   SEQ_GIR, 
	   CD_ITEM, 
	   QT_PACK, 
	   NO_FILE, 
	   NO_QTLINE, 
	   ID_INSERT, 
	   DTS_INSERT, 
	   ID_UPDATE, 
	   DTS_UPDATE, 
	   @P_ID_DELETE,
	   NEOE.SF_SYSDATE(GETDATE()),
	   @P_NM_PROCEDURE
FROM CZ_SA_PACKL
WHERE CD_COMPANY = @P_CD_COMPANY
AND NO_GIR = @P_NO_GIR

COMMIT TRAN SP_CZ_SA_PACK_LOG

END TRY
BEGIN CATCH
	ROLLBACK TRAN SP_CZ_SA_GIR_LOG
	SELECT @V_ERRMSG = ERROR_MESSAGE()
	GOTO ERROR
END CATCH

RETURN
ERROR: 
RAISERROR(@V_ERRMSG, 16, 1)
ROLLBACK TRAN SP_CZ_SA_GIR_LOG


GO

