USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_PACK_REGL_S]    Script Date: 2015-09-14 오후 1:53:45 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_SA_PACK_REGL_S]
(
	@P_CD_COMPANY			NVARCHAR(7),
	@P_NO_GIR				NVARCHAR(20),
	@P_NO_PACK				NUMERIC(5, 0)
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT 'N' AS S,
	   PL.NO_PACK,
	   PL.SEQ_GIR,
	   PL.NO_FILE,
	   QL.NO_LINE AS NO_QTLINE,
	   QL.NO_DSP,
	   PL.CD_ITEM,
	   MP.NM_ITEM,
	   QL.CD_ITEM_PARTNER,
	   QL.NM_ITEM_PARTNER,
	   PL.QT_PACK
FROM CZ_SA_PACKL PL
LEFT JOIN CZ_SA_QTNL QL ON QL.CD_COMPANY = PL.CD_COMPANY AND QL.NO_FILE = PL.NO_FILE AND QL.NO_LINE = PL.NO_QTLINE
LEFT JOIN MA_PITEM MP ON MP.CD_COMPANY = PL.CD_COMPANY AND MP.CD_ITEM = PL.CD_ITEM
WHERE PL.CD_COMPANY = @P_CD_COMPANY
AND PL.NO_GIR = @P_NO_GIR
AND PL.NO_PACK = @P_NO_PACK

GO