USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_PACK_REGH_D]    Script Date: 2015-09-11 오전 9:06:29 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER PROCEDURE [NEOE].[SP_CZ_SA_PACK_REGH_D]
(
	@P_CD_COMPANY			NVARCHAR(7),
	@P_NO_GIR				NVARCHAR(20),
	@P_NO_PACK				NUMERIC(5, 0),
	@P_ID_DELETE			NVARCHAR(15)
)
AS

EXEC SP_CZ_SA_PACK_LOG @P_CD_COMPANY, @P_NO_GIR, @P_ID_DELETE, 'SP_CZ_SA_PACK_REGH_D'

DELETE CZ_SA_PACKH
WHERE CD_COMPANY = @P_CD_COMPANY
AND NO_GIR = @P_NO_GIR
AND NO_PACK = @P_NO_PACK

DELETE CZ_SA_PACKL
WHERE CD_COMPANY = @P_CD_COMPANY
AND NO_GIR = @P_NO_GIR
AND NO_PACK = @P_NO_PACK

IF NOT EXISTS (SELECT 1 FROM CZ_SA_PACKH WHERE CD_COMPANY = @P_CD_COMPANY AND NO_GIR = @P_NO_GIR)
BEGIN
	UPDATE CZ_SA_GIRH_PACK
	SET STA_GIR = 'R',
		ID_UPDATE = @P_ID_DELETE,
		DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE())
	WHERE CD_COMPANY = @P_CD_COMPANY
	AND NO_GIR = @P_NO_GIR
END

IF EXISTS (SELECT 1 FROM CZ_SA_GIRH_PACK WHERE CD_COMPANY = @P_CD_COMPANY AND NO_GIR = @P_NO_GIR)
BEGIN
	UPDATE CZ_SA_GIRH_PACK_DETAIL
	SET DC_RESULT = STUFF((SELECT ' SIZE:'
								  + (CASE CD_TYPE WHEN '002' THEN '(P)' WHEN '003' THEN '(W)' ELSE '' END)
								  + FORMAT(QT_WIDTH, 'g15')
								  + ' X ' 
								  + FORMAT(QT_LENGTH, 'g15')
								  + ' X '
								  + FORMAT(QT_HEIGHT, 'g15')
								  + ' (MM), KG:'
								  + FORMAT(QT_GROSS_WEIGHT, 'g15')
								  + CHAR(10)
						   FROM CZ_SA_PACKH
						   WHERE CD_COMPANY = @P_CD_COMPANY
						   AND NO_GIR = @P_NO_GIR 
						   FOR XML PATH(''), TYPE).value('.', 'nvarchar(max)'), 1, 1, '')
	WHERE CD_COMPANY = @P_CD_COMPANY
	AND NO_GIR = @P_NO_GIR
END
ELSE
BEGIN
	UPDATE CZ_SA_GIRH_WORK_DETAIL
	SET DC_RESULT = STUFF((SELECT ' SIZE:'
								  + (CASE CD_TYPE WHEN '002' THEN '(P)' WHEN '003' THEN '(W)' ELSE '' END)
								  + FORMAT(QT_WIDTH, 'g15')
								  + ' X ' 
								  + FORMAT(QT_LENGTH, 'g15')
								  + ' X '
								  + FORMAT(QT_HEIGHT, 'g15')
								  + ' (MM), KG:'
								  + FORMAT(QT_GROSS_WEIGHT, 'g15')
								  + CHAR(10)
						   FROM CZ_SA_PACKH
						   WHERE CD_COMPANY = @P_CD_COMPANY
						   AND NO_GIR = @P_NO_GIR 
						   FOR XML PATH(''), TYPE).value('.', 'nvarchar(max)'), 1, 1, '')
	WHERE CD_COMPANY = @P_CD_COMPANY
	AND NO_GIR = @P_NO_GIR

	EXEC SP_CZ_SA_PACK_REG_MSG @P_CD_COMPANY, @P_NO_GIR
END

GO