USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_MM_NORMAL_ITEM_RPTD_S]    Script Date: 2017-12-15 오후 3:49:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




ALTER PROCEDURE [NEOE].[SP_CZ_MM_NORMAL_ITEM_RPTD_S]
(
    @P_CD_COMPANY   NVARCHAR(7),
	@P_DT_TODAY		NVARCHAR(8),
	@P_NO_SO		NVARCHAR(20),
	@P_NO_LINE		INT,
	@P_SEQ_SO		NUMERIC(5, 0)
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT PL.CD_COMPANY,
	   PL.NO_SO,
	   PL.NO_PO,
	   IL.NO_IO,
	   PL.NO_LINE,
	   IL.NO_IOLINE,
	   PH.DT_PO,
	   IH.DT_IO,
	   MP.LN_PARTNER AS NM_SUPPLIER,
	   IH.YN_RETURN,
	   MJ.NM_QTIOTP,
	   SL.NM_SL,
	   LC.CD_LOCATION,
	   ISNULL(PL.QT_PO, 0) AS QT_PO,
	   ISNULL(CASE WHEN IH.YN_RETURN = 'Y' THEN -IL.QT_IO ELSE IL.QT_IO END, 0) AS QT_IO,
	   MC.NM_SYSDEF AS NM_EXCH,
	   PH.RT_EXCH,
	   ISNULL(PL.UM_EX, 0) AS UM_EX_PO,
	   ISNULL(PL.UM, 0) AS UM_PO,
	   0 AS UM_STOCK,
	   (ISNULL(CASE WHEN IH.YN_RETURN = 'Y' THEN -IL.QT_IO ELSE IL.QT_IO END, 0) * ISNULL(PL.UM, 0)) AS AM_IO,
	   IL1.NO_IO_OUT,
	   IL1.NO_IOLINE_OUT,
	   IL1.DT_IO_OUT,
	   IL1.CD_ITEM_OUT,
	   ISNULL(IL1.QT_IO_OUT, 0) AS QT_IO_OUT,
	   IL1.NO_IO_IN,
	   IL1.NO_IOLINE_IN,
	   IL1.DT_IO_IN,
	   IL1.CD_ITEM_IN,
	   ISNULL(IL1.QT_IO_IN, 0) AS QT_IO_IN 
FROM MM_QTIO IL
LEFT JOIN MM_QTIOH IH ON IH.CD_COMPANY = IL.CD_COMPANY AND IH.NO_IO = IL.NO_IO
LEFT JOIN (SELECT IL.CD_COMPANY,
				  IL.NO_IO_MGMT,
				  IL.NO_IOLINE_MGMT,
				  IL.NO_IO AS NO_IO_OUT,
				  IL1.NO_IO AS NO_IO_IN,
				  IL.NO_IOLINE AS NO_IOLINE_OUT,
				  IL1.NO_IOLINE AS NO_IOLINE_IN,
				  IL.DT_IO AS DT_IO_OUT,
				  IL1.DT_IO AS DT_IO_IN,
				  IL.CD_ITEM AS CD_ITEM_OUT,
				  IL1.CD_ITEM AS CD_ITEM_IN,
				  IL.QT_IO AS QT_IO_OUT,
				  IL1.QT_IO AS QT_IO_IN
		   FROM MM_QTIO IL
		   LEFT JOIN MM_QTIO IL1 ON IL1.CD_COMPANY = IL.CD_COMPANY AND IL1.NO_IO_MGMT = IL.NO_IO AND IL1.NO_IOLINE_MGMT = IL.NO_IOLINE
		   WHERE (IL.CD_QTIOTP = '400' OR IL.CD_QTIOTP = '500')) IL1 
ON IL1.CD_COMPANY = IL.CD_COMPANY AND IL1.NO_IO_MGMT = IL.NO_IO AND IL1.NO_IOLINE_MGMT = IL.NO_IOLINE
LEFT JOIN MM_QTIO_LOCATION LC ON LC.CD_COMPANY = IL.CD_COMPANY AND LC.NO_IO = IL.NO_IO AND LC.NO_IOLINE = IL.NO_IOLINE
LEFT JOIN PU_POL PL ON PL.CD_COMPANY = IL.CD_COMPANY AND PL.NO_PO = IL.NO_PSO_MGMT AND PL.NO_LINE = IL.NO_PSOLINE_MGMT
LEFT JOIN PU_POH PH ON PH.CD_COMPANY = PL.CD_COMPANY AND PH.NO_PO = PL.NO_PO
LEFT JOIN MA_CODEDTL MC ON MC.CD_COMPANY = PH.CD_COMPANY AND MC.CD_FIELD = 'MA_B000005' AND MC.CD_SYSDEF = PH.CD_EXCH
LEFT JOIN MA_PARTNER MP ON MP.CD_COMPANY = PH.CD_COMPANY AND MP.CD_PARTNER = PH.CD_PARTNER
LEFT JOIN MM_EJTP MJ ON MJ.CD_COMPANY = IL.CD_COMPANY AND MJ.CD_QTIOTP = IL.CD_QTIOTP
LEFT JOIN MA_SL SL ON SL.CD_COMPANY = IL.CD_COMPANY AND SL.CD_SL = IL.CD_SL
WHERE PL.CD_COMPANY = @P_CD_COMPANY
AND PL.NO_SO = @P_NO_SO
AND PL.NO_LINE = @P_NO_LINE
AND PL.CD_ITEM NOT LIKE 'SD%'
AND IH.DT_IO <= @P_DT_TODAY
UNION ALL
SELECT GL.CD_COMPANY,
	   GL.NO_SO,
	   GH.NO_GIREQ AS NO_PO,
	   IL.NO_IO,
	   GL.NO_LINE,
	   IL.NO_IOLINE,
	   GH.DT_GIREQ AS DT_PO,
	   IH.DT_IO,
	   'STOCK' AS NM_SUPPLIER,
	   IH.YN_RETURN,
	   MJ.NM_QTIOTP,
	   SL.NM_SL,
	   NULL AS CD_LOCATION,
	   ISNULL(GL.QT_GIREQ, 0) AS QT_PO,
	   IL.QT_IO,
	   'KRW' AS NM_EXCH,
	   1 AS RT_EXCH,
	   0 AS UM_EX_PO,
	   0 AS UM_PO,
	   ISNULL(SB.UM_KR, 0) AS UM_STOCK,
	   (ISNULL(IL.QT_IO, 0) * ISNULL(SB.UM_KR, 0)) AS AM_IO,
	   NULL AS NO_IO_OUT,
	   0 AS NO_IOLINE_OUT,
	   NULL AS DT_IO_OUT,
	   NULL AS CD_ITEM_OUT,
	   0 AS QT_IO_OUT,
	   NULL AS NO_IO_IN,
	   0 AS NO_IOLINE_IN,
	   NULL AS DT_IO_IN,
	   NULL AS CD_ITEM_IN,
	   0 AS QT_IO_IN
FROM MM_GIREQL GL
LEFT JOIN CZ_SA_STOCK_BOOK SB ON SB.CD_COMPANY = GL.CD_COMPANY AND SB.NO_FILE = GL.NO_SO AND SB.NO_LINE = GL.SEQ_SO
LEFT JOIN MM_GIREQH GH ON GH.CD_COMPANY = GL.CD_COMPANY AND GH.NO_GIREQ = GL.NO_GIREQ
LEFT JOIN MM_QTIO IL ON IL.CD_COMPANY = GL.CD_COMPANY AND IL.NO_ISURCV = GL.NO_GIREQ AND IL.NO_ISURCVLINE = GL.NO_LINE AND IL.CD_SL = 'SL03'
LEFT JOIN MM_QTIOH IH ON IH.CD_COMPANY = IL.CD_COMPANY AND IH.NO_IO = IL.NO_IO
LEFT JOIN MM_EJTP MJ ON MJ.CD_COMPANY = IL.CD_COMPANY AND MJ.CD_QTIOTP = IL.CD_QTIOTP
LEFT JOIN MA_SL SL ON SL.CD_COMPANY = IL.CD_COMPANY AND SL.CD_SL = IL.CD_SL
WHERE GL.CD_COMPANY = @P_CD_COMPANY
AND GL.NO_SO = @P_NO_SO
AND GL.SEQ_SO = @P_SEQ_SO
AND GL.CD_SL = 'SL02' 
AND GL.CD_GRSL = 'SL03'
AND GL.QT_GI > 0
AND IH.DT_IO <= @P_DT_TODAY
ORDER BY IH.DT_IO

SELECT OL.CD_COMPANY,
	   OL.NO_PSO_MGMT AS NO_SO,
	   GL.NO_GIR,
	   OL.NO_IO,
	   OL.NO_PSOLINE_MGMT AS NO_SOLINE,
	   GL.SEQ_GIR,
	   OL.NO_IOLINE,
	   SH.DT_SO,
	   GH.DT_GIR,
	   OH.DT_IO,
	   OH.YN_RETURN,
	   MJ.NM_QTIOTP,
	   MS.NM_SL,
	   ISNULL(SL.QT_SO, 0) AS QT_SO,
	   (CASE WHEN OH.YN_RETURN = 'Y' THEN -OL.QT_IO ELSE OL.QT_IO END) AS QT_IO,
	   MC.NM_SYSDEF AS NM_EXCH,
	   SH.RT_EXCH,
	   ISNULL(SL.UM_EX_S, 0) AS UM_EX_SO,
	   ISNULL(SL.UM_KR_S, 0) AS UM_SO,
	   (ISNULL(CASE WHEN OH.YN_RETURN = 'Y' THEN -OL.QT_IO ELSE OL.QT_IO END, 0) * ISNULL(SL.UM_KR_S, 0)) AS AM_IO,
	   OL1.NO_IO_OUT,
	   OL1.NO_IOLINE_OUT,
	   OL1.DT_IO_OUT,
	   OL1.CD_ITEM_OUT,
	   ISNULL(OL1.QT_IO_OUT, 0) AS QT_IO_OUT,
	   OL1.NO_IO_IN,
	   OL1.NO_IOLINE_IN,
	   OL1.DT_IO_IN,
	   OL1.CD_ITEM_IN,
	   ISNULL(OL1.QT_IO_IN, 0) AS QT_IO_IN 
FROM MM_QTIO OL
LEFT JOIN MM_QTIOH OH ON OH.CD_COMPANY = OL.CD_COMPANY AND OH.NO_IO = OL.NO_IO
LEFT JOIN (SELECT OL.CD_COMPANY,
				  OL.NO_IO_MGMT,
				  OL.NO_IOLINE_MGMT,
				  OL.NO_IO AS NO_IO_OUT,
				  OL1.NO_IO AS NO_IO_IN,
				  OL.NO_IOLINE AS NO_IOLINE_OUT,
				  OL1.NO_IOLINE AS NO_IOLINE_IN,
				  OL.DT_IO AS DT_IO_OUT,
				  OL1.DT_IO AS DT_IO_IN,
				  OL.CD_ITEM AS CD_ITEM_OUT,
				  OL1.CD_ITEM AS CD_ITEM_IN,
				  OL.QT_IO AS QT_IO_OUT,
				  OL1.QT_IO AS QT_IO_IN
		   FROM MM_QTIO OL
		   LEFT JOIN MM_QTIO OL1 ON OL1.CD_COMPANY = OL.CD_COMPANY AND OL1.NO_IO_MGMT = OL.NO_IO AND OL1.NO_IOLINE_MGMT = OL.NO_IOLINE
		   WHERE (OL.CD_QTIOTP = '400' OR OL.CD_QTIOTP = '500')) OL1 
ON OL1.CD_COMPANY = OL.CD_COMPANY AND OL1.NO_IO_MGMT = OL.NO_IO AND OL1.NO_IOLINE_MGMT = OL.NO_IOLINE
LEFT JOIN SA_GIRL GL ON GL.CD_COMPANY = OL.CD_COMPANY AND GL.NO_GIR = OL.NO_ISURCV AND GL.SEQ_GIR = OL.NO_ISURCVLINE
LEFT JOIN SA_GIRH GH ON GH.CD_COMPANY = GL.CD_COMPANY AND GH.NO_GIR = GL.NO_GIR
LEFT JOIN SA_SOL SL ON SL.CD_COMPANY = OL.CD_COMPANY AND SL.NO_SO = OL.NO_PSO_MGMT AND SL.SEQ_SO = OL.NO_PSOLINE_MGMT
LEFT JOIN SA_SOH SH ON SH.CD_COMPANY = SL.CD_COMPANY AND SH.NO_SO = SL.NO_SO
LEFT JOIN MA_CODEDTL MC ON MC.CD_COMPANY = SH.CD_COMPANY AND MC.CD_FIELD = 'MA_B000005' AND MC.CD_SYSDEF = SH.CD_EXCH
LEFT JOIN MM_EJTP MJ ON MJ.CD_COMPANY = OL.CD_COMPANY AND MJ.CD_QTIOTP = OL.CD_QTIOTP
LEFT JOIN MA_SL MS ON MS.CD_COMPANY = OL.CD_COMPANY AND MS.CD_SL = OL.CD_SL
WHERE OL.CD_COMPANY = @P_CD_COMPANY
AND OL.NO_PSO_MGMT = @P_NO_SO
AND OL.NO_PSOLINE_MGMT = @P_SEQ_SO
AND OL.CD_ITEM NOT LIKE 'SD%'
AND OH.DT_IO <= @P_DT_TODAY
ORDER BY OH.DT_IO

GO