
namespace cz
{
	partial class P_CZ_PR_OPOUT_IV_APPLY_SUB
	{
		/// <summary>
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose(bool disposing)
		{
			if (disposing && (components != null))
			{
				components.Dispose();
			}
			base.Dispose(disposing);
		}

		#region Windows Form Designer generated code

		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(P_CZ_PR_OPOUT_IV_APPLY_SUB));
            this._flexM = new Dass.FlexGrid.FlexGrid(this.components);
            this.panel1 = new Duzon.Common.Controls.PanelExt();
            this.per기간 = new Duzon.Common.Controls.PeriodPicker();
            this.bp프로젝트 = new Duzon.Common.BpControls.BpCodeTextBox();
            this.panelExt1 = new Duzon.Common.Controls.PanelExt();
            this.panel8 = new Duzon.Common.Controls.PanelExt();
            this.cur총합계 = new Duzon.Common.Controls.CurrencyTextBox();
            this.btnEXCH = new Duzon.Common.Controls.RoundedButton();
            this.cur부가세합계 = new Duzon.Common.Controls.CurrencyTextBox();
            this.curEXCH = new Duzon.Common.Controls.CurrencyTextBox();
            this.panelExt5 = new Duzon.Common.Controls.PanelExt();
            this.lbl프로젝트 = new Duzon.Common.Controls.LabelExt();
            this.lbl환종 = new Duzon.Common.Controls.LabelExt();
            this.cbo환종 = new Duzon.Common.Controls.DropDownComboBox();
            this.cur원화합계 = new Duzon.Common.Controls.CurrencyTextBox();
            this.cbo공장 = new Duzon.Common.Controls.DropDownComboBox();
            this.bp거래처 = new Duzon.Common.BpControls.BpCodeTextBox();
            this.panel7 = new Duzon.Common.Controls.PanelExt();
            this.lbl총합계 = new Duzon.Common.Controls.LabelExt();
            this.lbl거래처 = new Duzon.Common.Controls.LabelExt();
            this.panel6 = new Duzon.Common.Controls.PanelExt();
            this.lbl부가세합계 = new Duzon.Common.Controls.LabelExt();
            this.lbl실적기간 = new Duzon.Common.Controls.LabelExt();
            this.panel2 = new Duzon.Common.Controls.PanelExt();
            this.lbl원화합계 = new Duzon.Common.Controls.LabelExt();
            this.lbl공장 = new Duzon.Common.Controls.LabelExt();
            this.bp품목 = new Duzon.Common.BpControls.BpCodeTextBox();
            this.cur변경단가 = new Duzon.Common.Controls.CurrencyTextBox();
            this.btn단가변경 = new Duzon.Common.Controls.RoundedButton();
            this.panel4 = new System.Windows.Forms.Panel();
            this.btn_apply_mst_um = new Duzon.Common.Controls.RoundedButton();
            this.btn_apply_um = new Duzon.Common.Controls.RoundedButton();
            this.btn취소 = new Duzon.Common.Controls.RoundedButton();
            this.btn조회 = new Duzon.Common.Controls.RoundedButton();
            this.btn적용 = new Duzon.Common.Controls.RoundedButton();
            this.tableLayoutPanel2 = new System.Windows.Forms.TableLayoutPanel();
            this.panel5 = new System.Windows.Forms.Panel();
            this.panelExt3 = new Duzon.Common.Controls.PanelExt();
            this.lbl변경단가 = new Duzon.Common.Controls.LabelExt();
            this.panelExt2 = new Duzon.Common.Controls.PanelExt();
            this.lbl품목 = new Duzon.Common.Controls.LabelExt();
            ((System.ComponentModel.ISupportInitialize)(this.closeButton)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)this._flexM).BeginInit();
            this.panel1.SuspendLayout();
            this.cur총합계.BeginInit();
            this.cur부가세합계.BeginInit();
            this.curEXCH.BeginInit();
            this.panelExt5.SuspendLayout();
            this.cur원화합계.BeginInit();
            this.panel7.SuspendLayout();
            this.panel6.SuspendLayout();
            this.panel2.SuspendLayout();
            this.cur변경단가.BeginInit();
            this.panel4.SuspendLayout();
            this.tableLayoutPanel2.SuspendLayout();
            this.panel5.SuspendLayout();
            this.panelExt3.SuspendLayout();
            this.panelExt2.SuspendLayout();
            this.SuspendLayout();
            this._flexM.AllowFreezing = C1.Win.C1FlexGrid.AllowFreezingEnum.Both;
            this._flexM.AllowResizing = C1.Win.C1FlexGrid.AllowResizingEnum.Both;
            this._flexM.AllowSorting = C1.Win.C1FlexGrid.AllowSortingEnum.None;
            this._flexM.AutoResize = false;
            this._flexM.ColumnInfo = "1,1,0,0,0,90,Columns:0{TextAlign:CenterCenter;TextAlignFixed:CenterCenter;}\t";
            this._flexM.Dock = System.Windows.Forms.DockStyle.Fill;
            this._flexM.DrawMode = C1.Win.C1FlexGrid.DrawModeEnum.OwnerDraw;
            this._flexM.EnabledHeaderCheck = true;
            this._flexM.Font = new System.Drawing.Font("굴림", 9f);
            this._flexM.KeyActionEnter = C1.Win.C1FlexGrid.KeyActionEnum.MoveAcross;
            this._flexM.Location = new System.Drawing.Point(3, 130);
            this._flexM.Name = "_flexM";
            this._flexM.Rows.Count = 1;
            this._flexM.Rows.DefaultSize = 18;
            this._flexM.SelectionMode = C1.Win.C1FlexGrid.SelectionModeEnum.Row;
            this._flexM.ShowButtons = C1.Win.C1FlexGrid.ShowButtonsEnum.Always;
            this._flexM.ShowSort = false;
            this._flexM.Size = new System.Drawing.Size(1118, 267);
            this._flexM.StyleInfo = resources.GetString("_flexM.StyleInfo");
            this._flexM.TabIndex = 3;
            this._flexM.UseGridCalculator = true;
            this.panel1.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            this.panel1.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.panel1.Controls.Add(this.per기간);
            this.panel1.Controls.Add(this.bp프로젝트);
            this.panel1.Controls.Add(this.panelExt1);
            this.panel1.Controls.Add(this.panel8);
            this.panel1.Controls.Add(this.cur총합계);
            this.panel1.Controls.Add(this.btnEXCH);
            this.panel1.Controls.Add(this.cur부가세합계);
            this.panel1.Controls.Add(this.curEXCH);
            this.panel1.Controls.Add(this.panelExt5);
            this.panel1.Controls.Add(this.cbo환종);
            this.panel1.Controls.Add(this.cur원화합계);
            this.panel1.Controls.Add(this.cbo공장);
            this.panel1.Controls.Add(this.bp거래처);
            this.panel1.Controls.Add(this.panel7);
            this.panel1.Controls.Add(this.panel6);
            this.panel1.Controls.Add(this.panel2);
            this.panel1.Location = new System.Drawing.Point(3, 3);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(1118, 53);
            this.panel1.TabIndex = 1;
            this.per기간.IsNecessaryCondition = true;
            this.per기간.Location = new System.Drawing.Point(341, 3);
            this.per기간.MaximumSize = new System.Drawing.Size(185, 21);
            this.per기간.MinimumSize = new System.Drawing.Size(185, 21);
            this.per기간.Name = "per기간";
            this.per기간.Size = new System.Drawing.Size(185, 21);
            this.per기간.TabIndex = (int)byte.MaxValue;
            this.bp프로젝트.BpControlMode = Duzon.Common.Forms.Help.BpControlMode.Sub;
            this.bp프로젝트.HelpID = Duzon.Common.Forms.Help.HelpID.P_SA_PROJECT_SUB;
            this.bp프로젝트.Location = new System.Drawing.Point(863, 29);
            this.bp프로젝트.Name = "bp프로젝트";
            this.bp프로젝트.ResultMode = Duzon.Common.Forms.Help.ResultMode.SlowMode;
            this.bp프로젝트.Size = new System.Drawing.Size(248, 21);
            this.bp프로젝트.TabIndex = 176;
            this.bp프로젝트.TabStop = false;
            this.bp프로젝트.Text = "bpCodeTextBox1";
            this.bp프로젝트.UserCodeName = "NM_PROJECT";
            this.bp프로젝트.UserCodeValue = "NO_PROJECT";
            this.bp프로젝트.UserHelpID = "H_SA_PRJ_SUB";
            this.panelExt1.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            this.panelExt1.BackColor = System.Drawing.Color.Transparent;
            this.panelExt1.Location = new System.Drawing.Point(4, 26);
            this.panelExt1.Name = "panelExt1";
            this.panelExt1.Size = new System.Drawing.Size(1104, 1);
            this.panelExt1.TabIndex = 0;
            this.panel8.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            this.panel8.BackColor = System.Drawing.Color.Transparent;
            this.panel8.Location = new System.Drawing.Point(5, 26);
            this.panel8.Name = "panel8";
            this.panel8.Size = new System.Drawing.Size(1108, 1);
            this.panel8.TabIndex = 7;
            this.cur총합계.BackColor = System.Drawing.SystemColors.Control;
            this.cur총합계.BorderColor = System.Drawing.Color.FromArgb(189, 199, 217);
            this.cur총합계.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.cur총합계.DecimalValue = new System.Decimal(new int[4]);
            this.cur총합계.ForeColor = System.Drawing.SystemColors.ControlText;
            this.cur총합계.Location = new System.Drawing.Point(606, 29);
            this.cur총합계.Name = "cur총합계";
            this.cur총합계.NullString = "0";
            this.cur총합계.ReadOnly = true;
            this.cur총합계.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.cur총합계.Size = new System.Drawing.Size(183, 21);
            this.cur총합계.TabIndex = 102;
            this.cur총합계.TabStop = false;
            this.cur총합계.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.btnEXCH.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right;
            this.btnEXCH.BackColor = System.Drawing.Color.White;
            this.btnEXCH.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnEXCH.Location = new System.Drawing.Point(1069, 2);
            this.btnEXCH.MaximumSize = new System.Drawing.Size(0, 19);
            this.btnEXCH.Name = "btnEXCH";
            this.btnEXCH.Size = new System.Drawing.Size(42, 19);
            this.btnEXCH.TabIndex = 175;
            this.btnEXCH.TabStop = false;
            this.btnEXCH.Text = "변경";
            this.btnEXCH.UseVisualStyleBackColor = false;
            this.cur부가세합계.BackColor = System.Drawing.SystemColors.Control;
            this.cur부가세합계.BorderColor = System.Drawing.Color.FromArgb(189, 199, 217);
            this.cur부가세합계.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.cur부가세합계.DecimalValue = new System.Decimal(new int[4]);
            this.cur부가세합계.ForeColor = System.Drawing.SystemColors.ControlText;
            this.cur부가세합계.Location = new System.Drawing.Point(341, 29);
            this.cur부가세합계.Name = "cur부가세합계";
            this.cur부가세합계.NullString = "0";
            this.cur부가세합계.ReadOnly = true;
            this.cur부가세합계.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.cur부가세합계.Size = new System.Drawing.Size(192, 21);
            this.cur부가세합계.TabIndex = 101;
            this.cur부가세합계.TabStop = false;
            this.cur부가세합계.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.curEXCH.BorderColor = System.Drawing.Color.FromArgb(189, 199, 217);
            this.curEXCH.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.curEXCH.CurrencyDecimalDigits = 4;
            this.curEXCH.DecimalValue = new System.Decimal(new int[4] { 10000, 0, 0, 262144 });
            this.curEXCH.ForeColor = System.Drawing.Color.Black;
            this.curEXCH.Location = new System.Drawing.Point(977, 2);
            this.curEXCH.Name = "curEXCH";
            this.curEXCH.NullString = "0";
            this.curEXCH.PositiveColor = System.Drawing.Color.Black;
            this.curEXCH.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.curEXCH.Size = new System.Drawing.Size(90, 21);
            this.curEXCH.TabIndex = 174;
            this.curEXCH.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.curEXCH.UseKeyEnter = false;
            this.curEXCH.UseKeyF3 = false;
            this.panelExt5.BackColor = System.Drawing.Color.FromArgb(234, 234, 234);
            this.panelExt5.Controls.Add(this.lbl프로젝트);
            this.panelExt5.Controls.Add(this.lbl환종);
            this.panelExt5.Location = new System.Drawing.Point(792, 1);
            this.panelExt5.Name = "panelExt5";
            this.panelExt5.Size = new System.Drawing.Size(65, 50);
            this.panelExt5.TabIndex = 100;
            this.lbl프로젝트.Location = new System.Drawing.Point(3, 29);
            this.lbl프로젝트.Name = "lbl프로젝트";
            this.lbl프로젝트.Size = new System.Drawing.Size(58, 17);
            this.lbl프로젝트.TabIndex = 2;
            this.lbl프로젝트.Tag = "";
            this.lbl프로젝트.Text = "프로젝트";
            this.lbl프로젝트.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lbl환종.Location = new System.Drawing.Point(3, 6);
            this.lbl환종.Name = "lbl환종";
            this.lbl환종.Size = new System.Drawing.Size(58, 17);
            this.lbl환종.TabIndex = 1;
            this.lbl환종.Tag = "";
            this.lbl환종.Text = "환종";
            this.lbl환종.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.cbo환종.AutoDropDown = true;
            this.cbo환종.BackColor = System.Drawing.Color.FromArgb((int)byte.MaxValue, 234, 242);
            this.cbo환종.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cbo환종.ItemHeight = 12;
            this.cbo환종.Location = new System.Drawing.Point(863, 3);
            this.cbo환종.Name = "cbo환종";
            this.cbo환종.Size = new System.Drawing.Size(111, 20);
            this.cbo환종.TabIndex = 99;
            this.cbo환종.Tag = "CD_EXCH";
            this.cbo환종.UseKeyEnter = false;
            this.cbo환종.UseKeyF3 = false;
            this.cur원화합계.BackColor = System.Drawing.SystemColors.Control;
            this.cur원화합계.BorderColor = System.Drawing.Color.FromArgb(189, 199, 217);
            this.cur원화합계.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.cur원화합계.DecimalValue = new System.Decimal(new int[4]);
            this.cur원화합계.ForeColor = System.Drawing.SystemColors.ControlText;
            this.cur원화합계.Location = new System.Drawing.Point(70, 29);
            this.cur원화합계.Name = "cur원화합계";
            this.cur원화합계.NullString = "0";
            this.cur원화합계.ReadOnly = true;
            this.cur원화합계.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.cur원화합계.Size = new System.Drawing.Size(192, 21);
            this.cur원화합계.TabIndex = 0;
            this.cur원화합계.TabStop = false;
            this.cur원화합계.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.cbo공장.AutoDropDown = true;
            this.cbo공장.BackColor = System.Drawing.Color.FromArgb((int)byte.MaxValue, 234, 242);
            this.cbo공장.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cbo공장.ItemHeight = 12;
            this.cbo공장.Location = new System.Drawing.Point(70, 3);
            this.cbo공장.Name = "cbo공장";
            this.cbo공장.Size = new System.Drawing.Size(192, 20);
            this.cbo공장.TabIndex = 9;
            this.cbo공장.Tag = "CD_BIZAREA";
            this.bp거래처.BpControlMode = Duzon.Common.Forms.Help.BpControlMode.Sub;
            this.bp거래처.HelpID = Duzon.Common.Forms.Help.HelpID.P_MA_PARTNER_SUB;
            this.bp거래처.Location = new System.Drawing.Point(606, 3);
            this.bp거래처.Name = "bp거래처";
            this.bp거래처.Size = new System.Drawing.Size(183, 21);
            this.bp거래처.TabIndex = 3;
            this.bp거래처.TabStop = false;
            this.panel7.BackColor = System.Drawing.Color.FromArgb(234, 234, 234);
            this.panel7.Controls.Add(this.lbl총합계);
            this.panel7.Controls.Add(this.lbl거래처);
            this.panel7.Location = new System.Drawing.Point(538, 1);
            this.panel7.Name = "panel7";
            this.panel7.Size = new System.Drawing.Size(65, 50);
            this.panel7.TabIndex = 2;
            this.lbl총합계.Location = new System.Drawing.Point(3, 29);
            this.lbl총합계.Name = "lbl총합계";
            this.lbl총합계.Size = new System.Drawing.Size(58, 17);
            this.lbl총합계.TabIndex = 2;
            this.lbl총합계.Tag = "";
            this.lbl총합계.Text = "총합계";
            this.lbl총합계.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lbl거래처.Location = new System.Drawing.Point(3, 6);
            this.lbl거래처.Name = "lbl거래처";
            this.lbl거래처.Size = new System.Drawing.Size(58, 17);
            this.lbl거래처.TabIndex = 1;
            this.lbl거래처.Tag = "NM_PARTNER";
            this.lbl거래처.Text = "거래처";
            this.lbl거래처.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.panel6.BackColor = System.Drawing.Color.FromArgb(234, 234, 234);
            this.panel6.Controls.Add(this.lbl부가세합계);
            this.panel6.Controls.Add(this.lbl실적기간);
            this.panel6.Location = new System.Drawing.Point(266, 1);
            this.panel6.Name = "panel6";
            this.panel6.Size = new System.Drawing.Size(72, 50);
            this.panel6.TabIndex = 1;
            this.lbl부가세합계.Location = new System.Drawing.Point(3, 29);
            this.lbl부가세합계.Name = "lbl부가세합계";
            this.lbl부가세합계.Size = new System.Drawing.Size(65, 17);
            this.lbl부가세합계.TabIndex = 1;
            this.lbl부가세합계.Tag = "";
            this.lbl부가세합계.Text = "부가세합계";
            this.lbl부가세합계.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lbl실적기간.Location = new System.Drawing.Point(3, 5);
            this.lbl실적기간.Name = "lbl실적기간";
            this.lbl실적기간.Size = new System.Drawing.Size(65, 17);
            this.lbl실적기간.TabIndex = 0;
            this.lbl실적기간.Tag = "";
            this.lbl실적기간.Text = "실적기간";
            this.lbl실적기간.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.panel2.BackColor = System.Drawing.Color.FromArgb(234, 234, 234);
            this.panel2.Controls.Add(this.lbl원화합계);
            this.panel2.Controls.Add(this.lbl공장);
            this.panel2.Location = new System.Drawing.Point(1, 1);
            this.panel2.Name = "panel2";
            this.panel2.Size = new System.Drawing.Size(65, 50);
            this.panel2.TabIndex = 0;
            this.lbl원화합계.Location = new System.Drawing.Point(3, 29);
            this.lbl원화합계.Name = "lbl원화합계";
            this.lbl원화합계.Size = new System.Drawing.Size(58, 17);
            this.lbl원화합계.TabIndex = 3;
            this.lbl원화합계.Tag = "";
            this.lbl원화합계.Text = "원화합계";
            this.lbl원화합계.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lbl공장.Location = new System.Drawing.Point(3, 4);
            this.lbl공장.Name = "lbl공장";
            this.lbl공장.Size = new System.Drawing.Size(58, 17);
            this.lbl공장.TabIndex = 2;
            this.lbl공장.Tag = "";
            this.lbl공장.Text = "공장";
            this.lbl공장.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bp품목.BpControlMode = Duzon.Common.Forms.Help.BpControlMode.Sub;
            this.bp품목.HelpID = Duzon.Common.Forms.Help.HelpID.P_MA_PITEM_SUB;
            this.bp품목.Location = new System.Drawing.Point(71, 3);
            this.bp품목.Name = "bp품목";
            this.bp품목.Size = new System.Drawing.Size(192, 21);
            this.bp품목.TabIndex = 8;
            this.bp품목.TabStop = false;
            this.cur변경단가.BorderColor = System.Drawing.Color.FromArgb(189, 199, 217);
            this.cur변경단가.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.cur변경단가.CurrencyDecimalDigits = 4;
            this.cur변경단가.CurrencyNegativePattern = 0;
            this.cur변경단가.DecimalValue = new System.Decimal(new int[4]);
            this.cur변경단가.ForeColor = System.Drawing.SystemColors.ControlText;
            this.cur변경단가.Location = new System.Drawing.Point(333, 3);
            this.cur변경단가.Name = "cur변경단가";
            this.cur변경단가.NullString = "0";
            this.cur변경단가.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.cur변경단가.Size = new System.Drawing.Size(137, 21);
            this.cur변경단가.TabIndex = 5;
            this.cur변경단가.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.btn단가변경.BackColor = System.Drawing.Color.White;
            this.btn단가변경.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btn단가변경.Location = new System.Drawing.Point(476, 2);
            this.btn단가변경.MaximumSize = new System.Drawing.Size(0, 19);
            this.btn단가변경.Name = "btn단가변경";
            this.btn단가변경.Size = new System.Drawing.Size(42, 19);
            this.btn단가변경.TabIndex = 0;
            this.btn단가변경.TabStop = false;
            this.btn단가변경.Text = "변경";
            this.btn단가변경.UseVisualStyleBackColor = false;
            this.panel4.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            this.panel4.Controls.Add(this.btn_apply_mst_um);
            this.panel4.Controls.Add(this.btn_apply_um);
            this.panel4.Controls.Add(this.btn취소);
            this.panel4.Controls.Add(this.btn조회);
            this.panel4.Controls.Add(this.btn적용);
            this.panel4.Location = new System.Drawing.Point(3, 95);
            this.panel4.Name = "panel4";
            this.panel4.Size = new System.Drawing.Size(1118, 29);
            this.panel4.TabIndex = 2;
            this.btn_apply_mst_um.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right;
            this.btn_apply_mst_um.BackColor = System.Drawing.Color.White;
            this.btn_apply_mst_um.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btn_apply_mst_um.Location = new System.Drawing.Point(699, 3);
            this.btn_apply_mst_um.MaximumSize = new System.Drawing.Size(0, 19);
            this.btn_apply_mst_um.Name = "btn_apply_mst_um";
            this.btn_apply_mst_um.Size = new System.Drawing.Size(111, 19);
            this.btn_apply_mst_um.TabIndex = 11;
            this.btn_apply_mst_um.TabStop = false;
            this.btn_apply_mst_um.Text = "마스터단가적용";
            this.btn_apply_mst_um.UseVisualStyleBackColor = false;
            this.btn_apply_um.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right;
            this.btn_apply_um.BackColor = System.Drawing.Color.White;
            this.btn_apply_um.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btn_apply_um.Location = new System.Drawing.Point(816, 3);
            this.btn_apply_um.MaximumSize = new System.Drawing.Size(0, 19);
            this.btn_apply_um.Name = "btn_apply_um";
            this.btn_apply_um.Size = new System.Drawing.Size(96, 19);
            this.btn_apply_um.TabIndex = 11;
            this.btn_apply_um.TabStop = false;
            this.btn_apply_um.Text = "최근단가적용";
            this.btn_apply_um.UseVisualStyleBackColor = false;
            this.btn취소.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right;
            this.btn취소.BackColor = System.Drawing.Color.White;
            this.btn취소.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.btn취소.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btn취소.Location = new System.Drawing.Point(1055, 3);
            this.btn취소.MaximumSize = new System.Drawing.Size(0, 19);
            this.btn취소.Name = "btn취소";
            this.btn취소.Size = new System.Drawing.Size(60, 19);
            this.btn취소.TabIndex = 3;
            this.btn취소.TabStop = false;
            this.btn취소.Text = "취소";
            this.btn취소.UseVisualStyleBackColor = false;
            this.btn조회.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right;
            this.btn조회.BackColor = System.Drawing.Color.White;
            this.btn조회.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btn조회.Location = new System.Drawing.Point(931, 3);
            this.btn조회.MaximumSize = new System.Drawing.Size(0, 19);
            this.btn조회.Name = "btn조회";
            this.btn조회.Size = new System.Drawing.Size(60, 19);
            this.btn조회.TabIndex = 2;
            this.btn조회.TabStop = false;
            this.btn조회.Text = "조회";
            this.btn조회.UseVisualStyleBackColor = false;
            this.btn적용.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right;
            this.btn적용.BackColor = System.Drawing.Color.White;
            this.btn적용.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btn적용.Location = new System.Drawing.Point(993, 3);
            this.btn적용.MaximumSize = new System.Drawing.Size(0, 19);
            this.btn적용.Name = "btn적용";
            this.btn적용.Size = new System.Drawing.Size(60, 19);
            this.btn적용.TabIndex = 1;
            this.btn적용.TabStop = false;
            this.btn적용.Text = "적용";
            this.btn적용.UseVisualStyleBackColor = false;
            this.tableLayoutPanel2.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            this.tableLayoutPanel2.AutoScroll = true;
            this.tableLayoutPanel2.ColumnCount = 1;
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100f));
            this.tableLayoutPanel2.Controls.Add(this.panel5, 0, 1);
            this.tableLayoutPanel2.Controls.Add(this._flexM, 0, 3);
            this.tableLayoutPanel2.Controls.Add(this.panel1, 0, 0);
            this.tableLayoutPanel2.Controls.Add(this.panel4, 0, 2);
            this.tableLayoutPanel2.Location = new System.Drawing.Point(0, 47);
            this.tableLayoutPanel2.Name = "tableLayoutPanel2";
            this.tableLayoutPanel2.RowCount = 4;
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20f));
            this.tableLayoutPanel2.Size = new System.Drawing.Size(1124, 400);
            this.tableLayoutPanel2.TabIndex = 3;
            this.panel5.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            this.panel5.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.panel5.Controls.Add(this.panelExt3);
            this.panel5.Controls.Add(this.panelExt2);
            this.panel5.Controls.Add(this.cur변경단가);
            this.panel5.Controls.Add(this.bp품목);
            this.panel5.Controls.Add(this.btn단가변경);
            this.panel5.Location = new System.Drawing.Point(3, 62);
            this.panel5.Name = "panel5";
            this.panel5.Size = new System.Drawing.Size(1118, 27);
            this.panel5.TabIndex = 4;
            this.panelExt3.BackColor = System.Drawing.Color.FromArgb(234, 234, 234);
            this.panelExt3.Controls.Add(this.lbl변경단가);
            this.panelExt3.Location = new System.Drawing.Point(266, 1);
            this.panelExt3.Name = "panelExt3";
            this.panelExt3.Size = new System.Drawing.Size(65, 25);
            this.panelExt3.TabIndex = 9;
            this.lbl변경단가.Location = new System.Drawing.Point(3, 4);
            this.lbl변경단가.Name = "lbl변경단가";
            this.lbl변경단가.Size = new System.Drawing.Size(58, 17);
            this.lbl변경단가.TabIndex = 2;
            this.lbl변경단가.Tag = "";
            this.lbl변경단가.Text = "변경단가";
            this.lbl변경단가.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.panelExt2.BackColor = System.Drawing.Color.FromArgb(234, 234, 234);
            this.panelExt2.Controls.Add(this.lbl품목);
            this.panelExt2.Location = new System.Drawing.Point(1, 1);
            this.panelExt2.Name = "panelExt2";
            this.panelExt2.Size = new System.Drawing.Size(65, 25);
            this.panelExt2.TabIndex = 5;
            this.lbl품목.Location = new System.Drawing.Point(3, 4);
            this.lbl품목.Name = "lbl품목";
            this.lbl품목.Size = new System.Drawing.Size(58, 17);
            this.lbl품목.TabIndex = 2;
            this.lbl품목.Tag = "";
            this.lbl품목.Text = "품목";
            this.lbl품목.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Inherit;
            this.CaptionPaint = true;
            this.ClientSize = new System.Drawing.Size(1127, 450);
            this.Controls.Add(this.tableLayoutPanel2);
            this.Font = new System.Drawing.Font("굴림체", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, (byte)129);
            this.ForeColor = System.Drawing.Color.Black;
            this.Name = "P_PR_OPOUT_IV_APPLY_SUB";
            this.Padding = new System.Windows.Forms.Padding(4);
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.TitleText = "공정외주매입적용";
            ((System.ComponentModel.ISupportInitialize)(this.closeButton)).EndInit();
            this._flexM.EndInit();
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            this.cur총합계.EndInit();
            this.cur부가세합계.EndInit();
            this.curEXCH.EndInit();
            this.panelExt5.ResumeLayout(false);
            this.cur원화합계.EndInit();
            this.panel7.ResumeLayout(false);
            this.panel6.ResumeLayout(false);
            this.panel2.ResumeLayout(false);
            this.cur변경단가.EndInit();
            this.panel4.ResumeLayout(false);
            this.tableLayoutPanel2.ResumeLayout(false);
            this.panel5.ResumeLayout(false);
            this.panel5.PerformLayout();
            this.panelExt3.ResumeLayout(false);
            this.panelExt2.ResumeLayout(false);
            this.ResumeLayout(false);
        }

		#endregion
		private Duzon.Common.Controls.PanelExt panel1;
		private Duzon.Common.BpControls.BpCodeTextBox bp거래처;
		private Duzon.Common.Controls.PanelExt panelExt1;
		private Duzon.Common.Controls.PanelExt panel8;
		private Duzon.Common.Controls.PanelExt panel6;
		private Duzon.Common.Controls.PanelExt panel2;
		private Duzon.Common.Controls.LabelExt lbl실적기간;
		private System.Windows.Forms.Panel panel4;
		private Duzon.Common.Controls.RoundedButton btn취소;
		private Duzon.Common.Controls.RoundedButton btn조회;
		private Duzon.Common.Controls.RoundedButton btn적용;
		private Dass.FlexGrid.FlexGrid _flexM;
		private Duzon.Common.Controls.CurrencyTextBox cur변경단가;
		private Duzon.Common.Controls.CurrencyTextBox cur원화합계;
		private Duzon.Common.Controls.PanelExt panel7;
		private Duzon.Common.Controls.RoundedButton btn단가변경;
		private Duzon.Common.BpControls.BpCodeTextBox bp품목;
		private Duzon.Common.Controls.LabelExt lbl거래처;
		private Duzon.Common.Controls.LabelExt lbl공장;
		private Duzon.Common.Controls.DropDownComboBox cbo공장;
		private System.Windows.Forms.TableLayoutPanel tableLayoutPanel2;
		private System.Windows.Forms.Panel panel5;
		private Duzon.Common.Controls.PanelExt panelExt3;
		private Duzon.Common.Controls.LabelExt lbl변경단가;
		private Duzon.Common.Controls.PanelExt panelExt2;
		private Duzon.Common.Controls.LabelExt lbl품목;
		private Duzon.Common.Controls.PanelExt panelExt5;
		private Duzon.Common.Controls.LabelExt lbl환종;
		private Duzon.Common.Controls.DropDownComboBox cbo환종;
		private Duzon.Common.Controls.LabelExt lbl총합계;
		private Duzon.Common.Controls.LabelExt lbl부가세합계;
		private Duzon.Common.Controls.LabelExt lbl원화합계;
		private Duzon.Common.Controls.CurrencyTextBox cur총합계;
		private Duzon.Common.Controls.CurrencyTextBox cur부가세합계;
		private Duzon.Common.Controls.RoundedButton btnEXCH;
		private Duzon.Common.Controls.CurrencyTextBox curEXCH;
		private Duzon.Common.Controls.RoundedButton btn_apply_um;
		private Duzon.Common.Controls.RoundedButton btn_apply_mst_um;
		private Duzon.Common.Controls.LabelExt lbl프로젝트;
		private Duzon.Common.BpControls.BpCodeTextBox bp프로젝트;
		private Duzon.Common.Controls.PeriodPicker per기간;
	}
}