SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [NEOE].[UP_CZ_SA_GI_WINTEC_H_GI_S]
(
    @P_CD_COMPANY       NVARCHAR(7),
    @P_DT_GIR_FROM      NCHAR(8),
    @P_DT_GIR_TO        NCHAR(8),
    @P_CD_PLANT         NVARCHAR(7),
    @P_CD_PARTNER       NVARCHAR(20),
    @P_GI_PARTNER       NVARCHAR(20),
    @P_TP_GI            NVARCHAR(12),
    @P_RET              NCHAR(1),
    @P_FG_TRANSPORT     NVARCHAR(7),
    @P_NO_EMP           NVARCHAR(10),
    @P_DT_GUBUN		    NVARCHAR(2), 
    @P_CD_SALEGRP       NVARCHAR(7),
    @P_MULTI_TP_SO		NVARCHAR(4000), 
    @P_CD_PJT           NVARCHAR(20), 
    @P_GRP_MFG          NVARCHAR(4),    --제품군
    @P_CD_SL_GIR        NVARCHAR(4000), 
    @P_CD_PARTNER_GRP   NVARCHAR(10), 
    @P_CD_PARTNER_GRP_2 NVARCHAR(10), 
    @P_CD_USERDEF1      NVARCHAR(4), 
    @P_CD_USERDEF2      NVARCHAR(4),
    @P_NO_EMP_LOGIN     NVARCHAR(10),
    @P_CD_USERDEF2_ITEM NVARCHAR(4000),
    @P_CD_ITEM			NVARCHAR(50),
    @P_FG_LANG          NVARCHAR(4) = NULL,	--언어
    @P_GL_CD_USERDEF1		NVARCHAR(4) = NULL,
    @P_GL_TXT_USERDEF1		NVARCHAR(100) = NULL,
    @P_TXT_NO_GIR			NVARCHAR(20)= NULL,
    @P_NO_SO                NVARCHAR(20)
)
AS
-- MultiLang Call
EXEC UP_MA_LOCAL_LANGUAGE @P_FG_LANG

DECLARE @V_QT_GUBUN     NVARCHAR(3),
        @V_BAD_BUGUN    NVARCHAR(3),    --2011.11.16 추가함.
        @V_INV_REQ      NVARCHAR(3),    --2012.04.18
        
        @V_YN_MFG_AUTH  NVARCHAR(1),     --2012.10.30 PIMS:D20121025024 영업그룹 권한
        @V_YN_PICKING   NVARCHAR(3),
        @V_SERVER_KEY   VARCHAR(50),
        @V_CD_EXC       NVARCHAR(3)  
        
SET     @V_QT_GUBUN     = '000'
SET     @V_BAD_BUGUN    = '000'
SET     @V_INV_REQ      = '000'

SELECT	@V_QT_GUBUN = CD_EXC
FROM	MA_EXC A
WHERE	CD_COMPANY = @P_CD_COMPANY
AND		CD_MODULE = 'SA'
AND		EXC_TITLE = '출하등록_검사'

-- 2011-11-16, 최승애 추가함.
SELECT	@V_BAD_BUGUN = CD_EXC 
FROM	MA_EXC A 
WHERE	CD_COMPANY = @P_CD_COMPANY
AND		CD_MODULE = 'SA'  
AND		EXC_TITLE = '불량재검사'

SELECT	@V_INV_REQ = ISNULL(CD_EXC, '000')
FROM	MA_EXC A 
WHERE	CD_COMPANY = @P_CD_COMPANY
AND		CD_MODULE = 'TRE'  
AND		EXC_TITLE = '송장작성-적용기준'

SELECT	@V_YN_PICKING = ISNULL(CD_EXC, 'N')
FROM	MA_EXC A 
WHERE	CD_COMPANY = @P_CD_COMPANY
AND		CD_MODULE = 'SA'  
AND		EXC_TITLE = '배차사용유무'

SELECT  @V_YN_MFG_AUTH = ISNULL(YN_MFG_AUTH, 'N')
FROM    MA_ENV
WHERE   CD_COMPANY = @P_CD_COMPANY

SELECT  @V_SERVER_KEY = SERVER_KEY
FROM    CM_SERVER_CONFIG
WHERE   YN_UPGRADE = 'Y'

SELECT @V_CD_EXC = CD_EXC
FROM   MA_EXC 
WHERE  CD_COMPANY = @P_CD_COMPANY 
AND    EXC_TITLE = '담당자별 창고권한등록-권한통제유무'  

                             
SELECT 'N' S, A.NO_GIR, A.CD_PLANT, ML.NM_PLANT, A.CD_PARTNER, MP.LN_PARTNER, A.DT_GIR, 
    A.DC_RMK, '' NO_IO, '' FG_TRANS, '' DT_IO, '' CD_DEPT, '' NO_EMP, '' YN_RETURN, 
    A.NO_EMP NO_GI_EMP, ME.NM_KOR, ISNULL(C.ST_STAT, '0') ST_STAT,
    A.DC_RMK1, MP.SN_PARTNER, MAX(GL.NO_SO) NO_SO
	,CASE WHEN ISNULL(GW.ST_STAT, '0') = '1' THEN 'Y'
			ELSE 'N'
	END AS GW_ST_STAT, -- GIT 추가
	A.DC_RMK2
FROM SA_GIRL GL
    INNER JOIN  SA_GIRH A ON A.CD_COMPANY = GL.CD_COMPANY AND A.NO_GIR = GL.NO_GIR
    LEFT OUTER JOIN SA_SOL SL ON GL.CD_COMPANY = SL.CD_COMPANY AND GL.NO_SO = SL.NO_SO AND GL.SEQ_SO = SL.SEQ_SO    
    LEFT OUTER JOIN SA_SOH SH ON SL.CD_COMPANY  = SH.CD_COMPANY AND SL.NO_SO = SH.NO_SO
    LEFT OUTER JOIN DZSN_MA_PLANT ML ON A.CD_COMPANY = ML.CD_COMPANY AND A.CD_PLANT = ML.CD_PLANT
    LEFT OUTER JOIN DZSN_MA_PARTNER MP ON A.CD_COMPANY = MP.CD_COMPANY AND A.CD_PARTNER = MP.CD_PARTNER
    LEFT OUTER JOIN DZSN_MA_EMP ME ON A.CD_COMPANY = ME.CD_COMPANY AND A.NO_EMP = ME.NO_EMP
    LEFT OUTER JOIN SA_GIRH_EXC C ON A.CD_COMPANY = C.CD_COMPANY AND A.NO_GIR = C.NO_GIR
    LEFT OUTER JOIN DZSN_MA_PITEM P ON P.CD_COMPANY = @P_CD_COMPANY AND P.CD_PLANT = @P_CD_PLANT AND P.CD_ITEM = GL.CD_ITEM
    LEFT OUTER JOIN MA_PARTNER_SUB MS ON MS.CD_COMPANY = GL.CD_COMPANY AND MS.CD_PARTNER = GL.GI_PARTNER
    LEFT OUTER JOIN FI_GWDOCU GW ON GW.CD_COMPANY = A.CD_COMPANY AND GW.CD_PC = A.CD_PLANT AND GW.NO_DOCU = A.NO_GIR --GIT 추가
WHERE A.CD_COMPANY = @P_CD_COMPANY 
    AND A.DT_GIR BETWEEN @P_DT_GIR_FROM AND @P_DT_GIR_TO
    AND	A.CD_PLANT = @P_CD_PLANT
    AND	(A.CD_PARTNER = @P_CD_PARTNER OR @P_CD_PARTNER = '' OR @P_CD_PARTNER IS NULL)
    AND	(A.NO_EMP = @P_NO_EMP OR @P_NO_EMP = '' OR @P_NO_EMP IS NULL)
    AND	(GL.GI_PARTNER = @P_GI_PARTNER OR @P_GI_PARTNER = '' OR @P_GI_PARTNER IS NULL)
    AND	(GL.TP_GI = @P_TP_GI OR @P_TP_GI = '' OR @P_TP_GI IS NULL)
    AND	(((@V_BAD_BUGUN = '000' OR (ISNULL(GL.YN_INSPECT, 'N') = 'N' OR GL.YN_INSPECT = '')) AND GL.QT_GIR - GL.QT_GI > 0 ) OR (@V_BAD_BUGUN = '100'  AND   GL.QT_QC_PASS - GL.QT_GI > 0)) -- 2011-11-16, 최승애
    AND	GL.RET = @P_RET
    AND	(SH.FG_TRANSPORT = @P_FG_TRANSPORT OR @P_FG_TRANSPORT = '' OR @P_FG_TRANSPORT IS NULL)
    AND ( GL.CD_SALEGRP = @P_CD_SALEGRP OR @P_CD_SALEGRP = '' OR @P_CD_SALEGRP IS NULL) 

    AND ((@V_QT_GUBUN IS NULL OR @V_QT_GUBUN = '' OR @V_QT_GUBUN = '000' OR @V_QT_GUBUN = '200') OR (@V_QT_GUBUN = '100' AND ((GL.YN_INSPECT = 'Y' AND GL.YN_QC_FIX = 'Y') OR (ISNULL(GL.YN_INSPECT, 'N') = 'N' OR GL.YN_INSPECT = ''))))
    AND (@P_MULTI_TP_SO IS NULL OR @P_MULTI_TP_SO = '' OR SH.TP_SO IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_MULTI_TP_SO)))
    -- 수주상태가 종료인건은 조회가 되지 않도록 처리(2011-04-07, 최승애)	 
    --AND (@P_RET = 'Y' OR SH.STA_SO <> 'C')
    -- 2011-04-13, 최승애 추가 수정 시작 ##
    -- 하나의 수주에서 다수의 고객의뢰건 중 일부는 종결되고 일부는 진행중일때를 
    -- 고려한 코드 추가함.  (2011-04-13, 최승애)
    --AND GL.CD_ITEM + CAST(GL.SEQ_SO AS VARCHAR) IN (    SELECT SHD.CD_ITEM + CAST(SHD.SEQ_SO AS VARCHAR)
    --                                                    FROM SA_SOL SHD
    --                                                    WHERE SHD.CD_COMPANY = @P_CD_COMPANY
    --                                                    AND SH.NO_SO = SHD.NO_SO
    --                                                    AND SHD.STA_SO <> 'C'
    --                                                )
    -- 2011-04-13, 최승애 추가 수정 끝 ##
    AND SL.STA_SO <> 'C'
    AND (GL.NO_PROJECT = @P_CD_PJT OR @P_CD_PJT = '' OR @P_CD_PJT IS NULL)
    AND (P.GRP_MFG = @P_GRP_MFG OR @P_GRP_MFG = '' OR @P_GRP_MFG IS NULL)
    AND (@P_CD_SL_GIR IS NULL OR @P_CD_SL_GIR = '' OR GL.CD_SL IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SL_GIR)))
    AND (MP.CD_PARTNER_GRP = @P_CD_PARTNER_GRP OR @P_CD_PARTNER_GRP = '' OR @P_CD_PARTNER_GRP IS NULL)
    AND (MP.CD_PARTNER_GRP_2 = @P_CD_PARTNER_GRP_2 OR @P_CD_PARTNER_GRP_2 = '' OR @P_CD_PARTNER_GRP_2 IS NULL)
    AND (MS.CD_USERDEF1 = @P_CD_USERDEF1 OR @P_CD_USERDEF1 = '' OR @P_CD_USERDEF1 IS NULL)
    AND (MS.CD_USERDEF2 = @P_CD_USERDEF2 OR @P_CD_USERDEF2 = '' OR @P_CD_USERDEF2 IS NULL)
    AND (@V_INV_REQ = '000' OR SL.TP_BUSI NOT IN ('004', '005') OR
        (@V_INV_REQ = '001' AND EXISTS  (   SELECT  1
                                            FROM    TR_INVL_REQ
                                            WHERE   NO_GIR = GL.NO_GIR
                                            AND     NO_LINE_GIR = GL.SEQ_GIR
                                            AND     CD_COMPANY = GL.CD_COMPANY  )))
    AND (@V_YN_MFG_AUTH = 'N' OR
        (@V_YN_MFG_AUTH = 'Y' AND EXISTS (  SELECT  1
                                            FROM    MA_MFG_AUTH AUTH
                                            WHERE   GL.CD_COMPANY   = AUTH.CD_COMPANY
                                            AND     GL.CD_SALEGRP   = AUTH.CD_AUTH
                                            AND     AUTH.FG_AUTH    = 'SA_GROUP'              
                                            AND     AUTH.NO_EMP     = @P_NO_EMP_LOGIN )))
    AND (@P_CD_USERDEF2_ITEM IS NULL OR @P_CD_USERDEF2_ITEM = '' OR P.CD_USERDEF2 IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_USERDEF2_ITEM)))
    AND (@V_YN_PICKING = 'N' OR
        (@V_YN_PICKING = 'Y' AND @V_SERVER_KEY = 'SIMMONS' AND ISNULL(GL.YN_PICKING,'N') = 'N') OR
        (@V_YN_PICKING = 'Y' AND @V_SERVER_KEY <> 'SIMMONS' AND (ISNULL(GL.YN_PICKING,'N') = 'N' OR (GL.YN_PICKING = 'Y' AND GL.QT_GIR = GL.QT_DLV))))
    AND (A.STA_GIR IS NULL OR A.STA_GIR <> 'TRQ')
    AND (P.CD_ITEM = @P_CD_ITEM OR @P_CD_ITEM = '' OR @P_CD_ITEM IS NULL)
    AND NOT EXISTS  (   SELECT  1
                        FROM    SA_Z_LABEL_L_ANJUN
                        WHERE   CD_COMPANY  = GL.CD_COMPANY
                        AND     NO_GIR      = GL.NO_GIR
                        AND     SEQ_GIR     = GL.SEQ_GIR    )
    AND	((ISNULL(@V_CD_EXC,'') = '000' AND (GL.CD_SL IN (SELECT CD_SL 
													     FROM   MA_CD_AUTHSL            
													     WHERE  CD_COMPANY = @P_CD_COMPANY            
													     AND    CD_PLANT   = A.CD_PLANT           
													     AND    NO_EMP     = @P_NO_EMP_LOGIN )            
								        OR NOT EXISTS (SELECT 1 
											           FROM   MA_CD_AUTHSL            
											           WHERE  NO_EMP       = @P_NO_EMP_LOGIN             
											           AND    CD_COMPANY   = @P_CD_COMPANY ))) OR ISNULL(@V_CD_EXC,'') <> '000') 
	AND (@V_SERVER_KEY = 'SUNGBO' AND (GL.CD_USERDEF1 = @P_GL_CD_USERDEF1 OR @P_GL_CD_USERDEF1 = '' OR @P_GL_CD_USERDEF1 IS NULL) OR @V_SERVER_KEY <> 'SUNGBO')
	AND	((@V_SERVER_KEY = 'SUNGBO' AND (@P_GL_TXT_USERDEF1 = '' OR @P_GL_TXT_USERDEF1 IS NULL OR GL.TXT_USERDEF1 = @P_GL_TXT_USERDEF1 )) OR @V_SERVER_KEY <> 'SUNGBO')
	AND (((@V_SERVER_KEY = 'DSTECH' AND (ISNULL(GL.NO_GIR, '') LIKE '%' + @P_TXT_NO_GIR + '%'))
			OR (@V_SERVER_KEY = 'ANYONE' AND (ISNULL(A.TXT_USERDEF1, '') LIKE '%' + @P_TXT_NO_GIR + '%'))
			OR (@V_SERVER_KEY <> 'DSTECH' AND @V_SERVER_KEY <> 'ANYONE')))
    AND (@P_NO_SO IS NULL OR @P_NO_SO = '' OR GL.NO_SO LIKE '%' + @P_NO_SO + '%')
			
GROUP BY A.NO_GIR, A.CD_PLANT, ML.NM_PLANT, A.CD_PARTNER, MP.LN_PARTNER, A.DT_GIR, 
    A.DC_RMK, C.ST_STAT,A.NO_EMP, ME.NM_KOR,A.DC_RMK1, MP.SN_PARTNER, GW.ST_STAT, A.DC_RMK2
OPTION(RECOMPILE)
GO
