USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_SO_MNG_MAIL_SEND_LOG_JSON]    Script Date: 2017-01-05 ¿ÀÈÄ 5:48:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_SA_SO_MNG_MAIL_SEND_LOG_JSON]          
(
	@P_JSON			NVARCHAR(MAX),
	@P_ID_USER		NVARCHAR(10)	
)  
AS
   
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

INSERT INTO CZ_SA_SOL_MAIL_SEND_WINTEC
(
	CD_COMPANY,
	NO_SO,
	SEQ_SO,
	TP_MAIL,
	IDX,
	DC1,
	DC2,
	ID_INSERT,
	DTS_INSERT
)
SELECT CD_COMPANY,
	   NO_SO,
	   SEQ_SO,
	   TP_MAIL,
	   (SELECT ISNULL(MAX(IDX), 0) 
	    FROM CZ_SA_SOL_MAIL_SEND_WINTEC
		WHERE CD_COMPANY = JS.CD_COMPANY
		AND NO_SO = JS.NO_SO
		AND SEQ_SO = JS.SEQ_SO
		AND TP_MAIL = JS.TP_MAIL) + ROW_NUMBER() OVER (PARTITION BY JS.CD_COMPANY, JS.NO_SO, JS.SEQ_SO, JS.TP_MAIL ORDER BY JS.CD_COMPANY, JS.NO_SO, JS.SEQ_SO, JS.TP_MAIL) AS IDX,
	   DC1,
	   DC2,
	   @P_ID_USER,
	   NEOE.SF_SYSDATE(GETDATE())
FROM OPENJSON(@P_JSON)
WITH
(
	CD_COMPANY      NVARCHAR(7),
	NO_SO			NVARCHAR(20),
	SEQ_SO			NUMERIC(5, 0),
	TP_MAIL			NVARCHAR(4),
	IDX				INT,
	DC1				NVARCHAR(200),
	DC2				NVARCHAR(200)
) JS

GO