USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[UP_SA_SOL_STA_LOG_I]    Script Date: 2019-11-14 오후 3:12:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[UP_SA_SOL_STA_LOG_I]
(
	@P_CD_COMPANY		NVARCHAR(7),
	@P_CD_PLANT			NVARCHAR(7),
	@P_NO_SO  			NVARCHAR(20),
	@P_SEQ_SO  			NUMERIC(5,0),
	@P_CD_ITEM  		NVARCHAR(50),
	@P_FG_GUBUN			NVARCHAR(10),	-- 종결,  종결취소
	@P_ID_INSERT		NVARCHAR(15),
	@P_NM_KOR			NVARCHAR(50),
	@P_NM_INSERT		NVARCHAR(50),
	@P_NO_EMP			NVARCHAR(50)
)
AS

SET NOCOUNT ON

DECLARE @P_DTS_INSERT VARCHAR(14)
DECLARE @V_SEQ NUMERIC(5,0)
DECLARE @V_STA_SO_BEFORE NVARCHAR(3)
DECLARE @V_STA_SO_AFTER NVARCHAR(3)

SET @V_STA_SO_AFTER = CASE WHEN @P_FG_GUBUN = '종결' THEN 'C' ELSE 'R' END
SELECT @V_STA_SO_BEFORE = STA_SO FROM SA_SOL 
WHERE CD_COMPANY = @P_CD_COMPANY AND CD_PLANT = @P_CD_PLANT AND NO_SO = @P_NO_SO AND SEQ_SO = @P_SEQ_SO

SELECT @V_SEQ =  (ISNULL(MAX(SEQ), 0) + 1) FROM SA_SOL_STA_LOG 
WHERE CD_COMPANY = @P_CD_COMPANY AND CD_PLANT = @P_CD_PLANT AND NO_SO = @P_NO_SO AND SEQ_SO = @P_SEQ_SO

SET @P_DTS_INSERT = NEOE.SF_SYSDATE(GETDATE())

INSERT INTO SA_SOL_STA_LOG 
(
	CD_COMPANY,			CD_PLANT,			NO_SO,			SEQ_SO,			SEQ,		CD_ITEM,	
	STA_SO_BEFORE,		STA_SO_AFTER,		FG_GUBUN,		DTS_INSERT,		ID_INSERT,	NM_KOR,
	NM_INSERT,			NO_EMP
)
VALUES
(
	@P_CD_COMPANY,			@P_CD_PLANT,			@P_NO_SO,			@P_SEQ_SO,			@V_SEQ,			@P_CD_ITEM,	
	@V_STA_SO_BEFORE,		@V_STA_SO_AFTER,		@P_FG_GUBUN,		@P_DTS_INSERT,		@P_ID_INSERT,	@P_NM_KOR,
	@P_NM_INSERT,			@P_NO_EMP
)

SET NOCOUNT OFF
RETURN
GO

