USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_GIR_PACK_S]    Script Date: 2015-06-04 오전 8:39:14 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/*******************************************              
**  System : 영업              
**  Sub System : 출고의뢰관리               
**  Page  : 고객납품의뢰등록              
**  Desc  : 고객납품의뢰 라인 조회(헤더, 라인의 스키마 정보도 가져온다)              
**              
**  Return Values              
**              
**  작    성    자    :               
**  작    성    일    :               
**  수    정    자    : 허성철              
*********************************************              
** Change History              
*********************************************/              
ALTER PROCEDURE [NEOE].[SP_CZ_SA_GIR_PACK_S]
(
    @P_CD_COMPANY    NVARCHAR(7),
	@P_LANGUAGE		 NVARCHAR(5) = 'KR',
    @P_NO_GIR        NVARCHAR(20),
	@P_NO_HST		 NUMERIC(5, 0)
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

IF (ISNULL(@P_NO_HST, 0)) = 0
BEGIN
	SELECT GH.NO_GIR, 
		   GL.NO_INV,
		   PD.NO_GIREQ, 
		   GH.DT_GIR, 
		   GH.CD_PARTNER, 
		   MP.LN_PARTNER, 
		   GH.CD_PLANT, 
		   GH.NO_EMP, 
		   ME.NM_KOR, 
		   GH.TP_BUSI, 
		   ISNULL(GH.YN_RETURN, 'N') AS YN_RETURN,
		   PD.CD_PACK_CATEGORY, 
		   PD.CD_SUB_CATEGORY, 
		   'N' AS YN_TAX_RETURN,
		   PD.YN_PACKING, 
		   PD.CD_COLLECT_FROM, 
		   MP2.LN_PARTNER AS LN_COLLECT_FROM, 
		   PD.SEQ_COLLECT_PIC,
		   PD.DT_START, 
		   PD.DT_COMPLETE, 
		   MH.NO_IMO, 
		   MH.NO_HULL, 
		   MH.NM_VESSEL,
		   PD.CD_RMK, 
		   PD.DC_RMK, 
		   PD.DC_RMK1, 
		   PD.DC_RMK2,
		   PD.DC_RMK3,
		   PD.DC_RMK4,
		   PD.DC_RMK5
	FROM CZ_SA_GIRH_PACK GH            
	JOIN (SELECT GL.CD_COMPANY, GL.NO_GIR, IL.NO_INV
	      FROM CZ_SA_GIRL_PACK GL
		  LEFT JOIN CZ_TR_INVL IL ON IL.CD_COMPANY = GL.CD_COMPANY AND IL.NO_INV = GL.NO_INV AND IL.NO_LINE = GL.SEQ_GIR
	      GROUP BY GL.CD_COMPANY, GL.NO_GIR, IL.NO_INV) GL
	ON GL.CD_COMPANY = GH.CD_COMPANY AND GL.NO_GIR = GH.NO_GIR
	LEFT JOIN CZ_SA_GIRH_PACK_DETAIL PD ON PD.CD_COMPANY = GH.CD_COMPANY AND PD.NO_GIR = GH.NO_GIR 
	LEFT JOIN CZ_MA_HULL MH ON MH.NO_IMO = PD.NO_IMO        
	LEFT JOIN MA_PARTNER MP ON GH.CD_COMPANY = MP.CD_COMPANY AND GH.CD_PARTNER = MP.CD_PARTNER   
	LEFT JOIN CZ_MA_DELIVERY MP2 ON MP2.CD_COMPANY = GH.CD_COMPANY AND MP2.CD_PARTNER = PD.CD_COLLECT_FROM
	LEFT JOIN MA_EMP ME ON GH.CD_COMPANY = ME.CD_COMPANY AND GH.NO_EMP = ME.NO_EMP
	WHERE GH.CD_COMPANY = @P_CD_COMPANY            
	AND	GH.NO_GIR = @P_NO_GIR            
	ORDER BY GH.NO_GIR
	
	SELECT 'N' AS S,
		   GH.CD_PLANT, 
		   GL.SEQ_GIR,
		   GL.SEQ_SO,
		   TI.NO_LINE,
		   GL.NO_SO,
		   QL.NO_DSP,
		   ISNULL(QL.NM_SUBJECT, '') AS NM_SUBJECT,
		   ISNULL(QL.CD_ITEM_PARTNER, '') AS CD_ITEM_PARTNER,
		   ISNULL(QL.NM_ITEM_PARTNER, '') AS NM_ITEM_PARTNER,
		   GL.CD_ITEM,
		   MI.NM_ITEM,
		   GL.TP_ITEM,
		   MI.STND_ITEM,
		   GL.DT_DUEDATE,
		   ISNULL(QI.DT_IO, '') AS DT_IO,
		   GL.DT_REQGI,
		   GL.YN_INSPECT,
		   GL.CD_SL,
		   MS.NM_SL,
		   GL.TP_GI,
		   MJ.NM_QTIOTP AS NM_GI,
		   GL.CD_EXCH,
		   GL.QT_GIR_IM,
		   NEOE.FN_CZ_GET_STOCK_QTY (SL.CD_COMPANY, CONVERT(CHAR(8), GETDATE(), 112), SL.CD_PLANT, SL.CD_ITEM) AS QT_INV,
		   ISNULL(QI.QT_TAX, 0) AS QT_TAX,
		   ISNULL(QI.CUSTOMS, 0) AS CUSTOMS,
		   ISNULL(QI.QT_BL, 0) AS QT_BL,
		   GL.QT_GIR,
		   GL.QT_GIR_STOCK,
		   GL.QT_GI,
		   GL.UM,
		   GL.AM_GIR,
		   GL.RT_EXCH,
		   GL.AM_GIRAMT,
		   GL.AM_VAT,
		   (GL.AM_GIRAMT + GL.AM_VAT) AS AMT,
		   GL.UNIT,
		   GL.GI_PARTNER,
		   MP.LN_PARTNER,
		   GL.NO_PROJECT,
		   SP.NM_PROJECT,
		   GL.SEQ_PROJECT,
		   GL.CD_SALEGRP,
		   MG.NM_SALEGRP,
		   GL.DC_RMK,
		   SL.NO_PO_PARTNER,
		   SL.NO_POLINE_PARTNER,
		   GL.RT_VAT,
		   GL.TP_VAT,
		   GL.NO_EMP,
		   GL.TP_IV,
		   GL.FG_TAXP,
		   GH.TP_BUSI,
		   GL.NO_LC,
		   GL.SEQ_LC,
		   GL.FG_LC_OPEN,
		   GL.GIR,
		   GL.IV,
		   GL.CD_WH,
		   WH.NM_WH,
		   GL.YN_PICKING,
		   GL.CD_USERDEF1 AS L_CD_USERDEF1,
		   GL.TP_UM_TAX,
		   GL.UMVAT_GIR,
		   MI.RT_PLUS,
		   SL.QT_SO,
		   MI.QT_WIDTH * MI.QT_LENGTH AS QT_SQUARE,
		   CASE WHEN (MI.QT_WIDTH * MI.QT_LENGTH) = 0 THEN 0 ELSE GL.UM / (MI.QT_WIDTH * MI.QT_LENGTH) END AS UM_SQUARE,
		   MI.UNIT_SO_FACT, 
		   GL.YN_ADD_STOCK,
		   (CASE WHEN ISNULL(QI.DT_IO, '') <> '' THEN STUFF((SELECT DISTINCT ',' + A.CD_LOCATION
		   													 FROM MM_QTIO_LOCATION A
		   													 JOIN MM_QTIO B ON B.CD_COMPANY = A.CD_COMPANY AND B.NO_IO = A.NO_IO AND B.NO_IOLINE = A.NO_IOLINE
		   													 WHERE B.FG_PS = '1'
		   													 AND B.CD_COMPANY = GL.CD_COMPANY
		   													 AND B.CD_PJT = GL.NO_SO
		   													 AND B.NO_PSOLINE_MGMT = GL.SEQ_SO
		   													 FOR XML PATH('')),1,1,'')
		   									   ELSE '미입고' END) AS NO_LOCATION,
		   (CASE WHEN ISNULL(GL.QT_GIR_STOCK, 0) > 0 THEN MI.CD_ZONE ELSE '' END) AS NO_LOCATION_STOCK,
		   STUFF((SELECT DISTINCT ',' + PH.CD_PARTNER
				  FROM PU_POL PL
				  LEFT JOIN PU_POH PH ON PH.CD_COMPANY = PL.CD_COMPANY AND PH.NO_PO = PL.NO_PO
				  WHERE PL.CD_COMPANY = GL.CD_COMPANY
				  AND PL.NO_SO =GL.NO_SO
				  AND PL.NO_SOLINE = GL.SEQ_SO
				  FOR XML PATH('')),1,1,'') AS CD_SUPPLIER,
		   STUFF((SELECT DISTINCT ',' + MP.LN_PARTNER 
				  FROM PU_POL PL
				  LEFT JOIN PU_POH PH ON PH.CD_COMPANY = PL.CD_COMPANY AND PH.NO_PO = PL.NO_PO
				  LEFT JOIN MA_PARTNER MP ON MP.CD_COMPANY = PH.CD_COMPANY AND MP.CD_PARTNER = PH.CD_PARTNER
				  WHERE PL.CD_COMPANY = GL.CD_COMPANY
				  AND PL.NO_SO =GL.NO_SO
				  AND PL.NO_SOLINE = GL.SEQ_SO
				  FOR XML PATH('')),1,1,'') AS NM_SUPPLIER
	FROM CZ_SA_GIRL_PACK GL               
	JOIN CZ_SA_GIRH_PACK GH ON GH.CD_COMPANY = GL.CD_COMPANY AND GH.NO_GIR = GL.NO_GIR     
	LEFT JOIN MA_PITEM MI ON MI.CD_COMPANY = GL.CD_COMPANY AND MI.CD_ITEM = GL.CD_ITEM AND MI.CD_PLANT = GH.CD_PLANT 
	LEFT JOIN CZ_SA_QTNL QL ON QL.CD_COMPANY = GL.CD_COMPANY AND QL.NO_FILE = GL.NO_SO AND QL.NO_LINE = GL.SEQ_SO
	LEFT JOIN SA_SOL SL ON SL.CD_COMPANY = GL.CD_COMPANY AND SL.NO_SO = GL.NO_SO AND SL.SEQ_SO = GL.SEQ_SO
	LEFT JOIN MA_SL MS ON MS.CD_COMPANY = GL.CD_COMPANY AND MS.CD_SL = GL.CD_SL AND MS.CD_PLANT = GH.CD_PLANT            
	LEFT JOIN MM_EJTP MJ ON MJ.CD_COMPANY = GL.CD_COMPANY AND MJ.CD_QTIOTP = GL.TP_GI             
	LEFT JOIN MA_PARTNER MP ON MP.CD_COMPANY = GL.CD_COMPANY AND MP.CD_PARTNER = GL.GI_PARTNER
	LEFT JOIN SA_PROJECTH SP ON SP.CD_COMPANY = GL.CD_COMPANY AND SP.NO_PROJECT = GL.NO_PROJECT       
	LEFT JOIN MA_SALEGRP MG ON MG.CD_COMPANY = GL.CD_COMPANY AND MG.CD_SALEGRP = GL.CD_SALEGRP    
	LEFT JOIN MA_WH WH ON WH.CD_COMPANY = GL.CD_COMPANY AND WH.CD_WH = GL.CD_WH
	LEFT JOIN CZ_TR_INVL TI ON TI.CD_COMPANY = GL.CD_COMPANY AND TI.NO_INV = GL.NO_INV AND TI.NO_LINE = GL.SEQ_GIR
	LEFT JOIN (SELECT PL.CD_COMPANY, PL.NO_SO, PL.NO_SOLINE,
			   	      MAX(IL.DT_IO) AS DT_IO,
			   		  SUM(TX.QT_TAX) AS QT_TAX,
					  SUM(TX.CUSTOMS) AS CUSTOMS,
					  SUM(CASE WHEN ISNULL(PL.YN_BL, 'N') = 'Y' THEN PL.QT_PO ELSE 0 END) AS QT_BL
			   FROM PU_POL PL
			   LEFT JOIN (SELECT IL.CD_COMPANY, IL.NO_PSO_MGMT, IL.NO_PSOLINE_MGMT,
			   			  	     MAX(IH.DT_IO) AS DT_IO 
			   			  FROM MM_QTIO IL
			   			  LEFT JOIN MM_QTIOH IH ON IH.CD_COMPANY = IL.CD_COMPANY AND IH.NO_IO = IL.NO_IO
			   			  GROUP BY IL.CD_COMPANY, IL.NO_PSO_MGMT, IL.NO_PSOLINE_MGMT) IL
			   ON IL.CD_COMPANY = PL.CD_COMPANY AND IL.NO_PSO_MGMT = PL.NO_PO AND IL.NO_PSOLINE_MGMT = PL.NO_LINE
			   LEFT JOIN (SELECT IL.CD_COMPANY, IL.NO_PO, IL.NO_POLINE,
			   		   			 SUM(IL.QT_TAX) AS QT_TAX,
								 SUM(DL.CUSTOMS) AS CUSTOMS
			   			  FROM CZ_FI_IMP_PMTL IL
						  LEFT JOIN CZ_PU_IMPORT_DECLARATIONL DL ON DL.CD_COMPANY = IL.CD_COMPANY AND REPLACE(DL.NO_IMPORT, '-', '') = IL.NO_IMPORT AND DL.SEQ = IL.SEQ_IMPORT
			   			  GROUP BY IL.CD_COMPANY, IL.NO_PO, IL.NO_POLINE) TX
			   ON TX.CD_COMPANY = PL.CD_COMPANY AND TX.NO_PO = PL.NO_PO AND TX.NO_POLINE = PL.NO_LINE
	GROUP BY PL.CD_COMPANY, PL.NO_SO, PL.NO_SOLINE) QI
	ON QI.CD_COMPANY = SL.CD_COMPANY AND QI.NO_SO = SL.NO_SO AND QI.NO_SOLINE = SL.SEQ_SO
	WHERE GL.CD_COMPANY = @P_CD_COMPANY          
	AND GL.NO_GIR = @P_NO_GIR  
	ORDER BY GL.NO_GIR, GL.SEQ_GIR	
END
ELSE
BEGIN
	SELECT GH.NO_GIR, 
		   GL.NO_INV, 
		   PD.NO_GIREQ,
		   GH.DT_GIR, 
		   GH.CD_PARTNER, 
		   MP.LN_PARTNER, 
		   GH.CD_PLANT, 
		   GH.NO_EMP, 
		   ME.NM_KOR, 
		   GH.TP_BUSI, 
		   ISNULL(GH.YN_RETURN, 'N') AS YN_RETURN,
		   PD.CD_MAIN_CATEGORY AS CD_PACK_CATEGORY, 
		   PD.CD_SUB_CATEGORY, 
		   PD.YN_PACKING, 
		   PD.CD_DELIVERY_TO AS CD_COLLECT_FROM, 
		   MP2.LN_PARTNER AS LN_COLLECT_FROM, 
		   PD.SEQ_DELIVERY_PIC AS SEQ_COLLECT_PIC,
		   PD.DT_START, 
		   PD.DT_COMPLETE, 
		   MH.NO_IMO, 
		   MH.NO_HULL, 
		   MH.NM_VESSEL,
		   PD.CD_RMK, 
		   PD.DC_RMK, 
		   PD.DC_RMK1, 
		   PD.DC_RMK2,
		   PD.DC_RMK3,
		   PD.DC_RMK4,
		   PD.DC_RMK5
	FROM CZ_SA_GIRH_LOG GH            
	JOIN (SELECT GL.CD_COMPANY, GL.TP_GIR, GL.NO_GIR, GL.NO_HST, IL.NO_INV
	      FROM CZ_SA_GIRL_LOG GL
		  LEFT JOIN CZ_TR_INVL_LOG IL ON IL.CD_COMPANY = GL.CD_COMPANY AND IL.NO_INV = GL.NO_INV AND IL.NO_LINE = GL.SEQ_GIR
	      GROUP BY GL.CD_COMPANY, GL.TP_GIR, GL.NO_GIR, GL.NO_HST, IL.NO_INV) GL
	ON GL.CD_COMPANY = GH.CD_COMPANY AND GL.TP_GIR = GH.TP_GIR AND GL.NO_GIR = GH.NO_GIR AND GL.NO_HST = GH.NO_HST
	LEFT JOIN CZ_SA_GIRH_DETAIL_LOG PD ON PD.CD_COMPANY = GH.CD_COMPANY AND PD.TP_GIR = GH.TP_GIR AND PD.NO_GIR = GH.NO_GIR AND PD.NO_HST = GH.NO_HST 
	LEFT JOIN CZ_MA_HULL MH ON MH.NO_IMO = PD.NO_IMO        
	LEFT JOIN MA_PARTNER MP ON GH.CD_COMPANY = MP.CD_COMPANY AND GH.CD_PARTNER = MP.CD_PARTNER   
	LEFT JOIN CZ_MA_DELIVERY MP2 ON MP2.CD_COMPANY = GH.CD_COMPANY AND MP2.CD_PARTNER = PD.CD_DELIVERY_TO
	LEFT JOIN MA_EMP ME ON GH.CD_COMPANY = ME.CD_COMPANY AND GH.NO_EMP = ME.NO_EMP
	WHERE GH.CD_COMPANY = @P_CD_COMPANY            
	AND GH.TP_GIR = '002'
	AND	GH.NO_GIR = @P_NO_GIR
	AND GH.NO_HST = @P_NO_HST           
	ORDER BY GH.NO_GIR
	
	SELECT 'N' AS S,
		   GH.CD_PLANT, 
		   GL.SEQ_GIR,
		   GL.SEQ_SO,
		   TI.NO_LINE,
		   GL.NO_SO,
		   QL.NO_DSP,
		   ISNULL(QL.NM_SUBJECT, '') AS NM_SUBJECT,
		   ISNULL(QL.CD_ITEM_PARTNER, '') AS CD_ITEM_PARTNER,
		   ISNULL(QL.NM_ITEM_PARTNER, '') AS NM_ITEM_PARTNER,
		   GL.CD_ITEM,
		   MI.NM_ITEM,
		   GL.TP_ITEM,
		   MI.STND_ITEM,
		   GL.DT_DUEDATE,
		   ISNULL(QI.DT_IO, '') AS DT_IO,
		   GL.DT_REQGI,
		   GL.YN_INSPECT,
		   GL.CD_SL,
		   MS.NM_SL,
		   GL.TP_GI,
		   MJ.NM_QTIOTP AS NM_GI,
		   GL.CD_EXCH,
		   GL.QT_GIR_IM,
		   NEOE.FN_CZ_GET_STOCK_QTY (SL.CD_COMPANY, CONVERT(CHAR(8), GETDATE(), 112), SL.CD_PLANT, SL.CD_ITEM) AS QT_INV,
		   ISNULL(QI.QT_TAX, 0) AS QT_TAX,
		   ISNULL(QI.CUSTOMS, 0) AS CUSTOMS,
		   ISNULL(QI.QT_BL, 0) AS QT_BL,
		   GL.QT_GIR,
		   GL.QT_GIR_STOCK,
		   GL.QT_GI,
		   GL.UM,
		   GL.AM_GIR,
		   GL.RT_EXCH,
		   GL.AM_GIRAMT,
		   GL.AM_VAT,
		   (GL.AM_GIRAMT + GL.AM_VAT) AS AMT,
		   GL.UNIT,
		   GL.GI_PARTNER,
		   MP.LN_PARTNER,
		   GL.NO_PROJECT,
		   SP.NM_PROJECT,
		   GL.CD_SALEGRP,
		   MG.NM_SALEGRP,
		   GL.DC_RMK,
		   SL.NO_PO_PARTNER,
		   SL.NO_POLINE_PARTNER,
		   GL.RT_VAT,
		   GL.TP_VAT,
		   GL.NO_EMP,
		   GL.TP_IV,
		   GL.FG_TAXP,
		   GH.TP_BUSI,
		   GL.FG_LC_OPEN,
		   GL.GIR,
		   GL.IV,
		   GL.TP_UM_TAX,
		   GL.UMVAT_GIR,
		   MI.RT_PLUS,
		   SL.QT_SO,
		   MI.QT_WIDTH * MI.QT_LENGTH AS QT_SQUARE,
		   CASE WHEN (MI.QT_WIDTH * MI.QT_LENGTH) = 0 THEN 0 ELSE GL.UM / (MI.QT_WIDTH * MI.QT_LENGTH) END AS UM_SQUARE,
		   MI.UNIT_SO_FACT, 
		   GL.YN_ADD_STOCK,
		   (CASE WHEN ISNULL(QI.DT_IO, '') <> '' THEN STUFF((SELECT DISTINCT ',' + A.CD_LOCATION
		   													 FROM MM_QTIO_LOCATION A
		   													 JOIN MM_QTIO B ON B.CD_COMPANY = A.CD_COMPANY AND B.NO_IO = A.NO_IO AND B.NO_IOLINE = A.NO_IOLINE
		   													 WHERE B.FG_PS = '1'
		   													 AND B.CD_COMPANY = GL.CD_COMPANY
		   													 AND B.CD_PJT = GL.NO_SO
		   													 AND B.NO_PSOLINE_MGMT = GL.SEQ_SO
		   													 FOR XML PATH('')),1,1,'')
		   									   ELSE '미입고' END) AS NO_LOCATION,
		   (CASE WHEN ISNULL(GL.QT_GIR_STOCK, 0) > 0 THEN MI.CD_ZONE ELSE '' END) AS NO_LOCATION_STOCK,
		   STUFF((SELECT DISTINCT ',' + PH.CD_PARTNER
				  FROM PU_POL PL
				  LEFT JOIN PU_POH PH ON PH.CD_COMPANY = PL.CD_COMPANY AND PH.NO_PO = PL.NO_PO
				  WHERE PL.CD_COMPANY = GL.CD_COMPANY
				  AND PL.NO_SO =GL.NO_SO
				  AND PL.NO_SOLINE = GL.SEQ_SO
				  FOR XML PATH('')),1,1,'') AS CD_SUPPLIER,
		   STUFF((SELECT DISTINCT ',' + MP.LN_PARTNER 
				  FROM PU_POL PL
				  LEFT JOIN PU_POH PH ON PH.CD_COMPANY = PL.CD_COMPANY AND PH.NO_PO = PL.NO_PO
				  LEFT JOIN MA_PARTNER MP ON MP.CD_COMPANY = PH.CD_COMPANY AND MP.CD_PARTNER = PH.CD_PARTNER
				  WHERE PL.CD_COMPANY = GL.CD_COMPANY
				  AND PL.NO_SO =GL.NO_SO
				  AND PL.NO_SOLINE = GL.SEQ_SO
				  FOR XML PATH('')),1,1,'') AS NM_SUPPLIER
	FROM CZ_SA_GIRL_LOG GL               
	JOIN CZ_SA_GIRH_LOG GH ON GH.CD_COMPANY = GL.CD_COMPANY AND GH.NO_GIR = GL.NO_GIR AND GH.NO_HST = GL.NO_HST     
	LEFT JOIN MA_PITEM MI ON MI.CD_COMPANY = GL.CD_COMPANY AND MI.CD_ITEM = GL.CD_ITEM AND MI.CD_PLANT = GH.CD_PLANT 
	LEFT JOIN CZ_SA_QTNL QL ON QL.CD_COMPANY = GL.CD_COMPANY AND QL.NO_FILE = GL.NO_SO AND QL.NO_LINE = GL.SEQ_SO
	LEFT JOIN SA_SOL SL ON SL.CD_COMPANY = GL.CD_COMPANY AND SL.NO_SO = GL.NO_SO AND SL.SEQ_SO = GL.SEQ_SO
	LEFT JOIN MA_SL MS ON MS.CD_COMPANY = GL.CD_COMPANY AND MS.CD_SL = GL.CD_SL AND MS.CD_PLANT = GH.CD_PLANT            
	LEFT JOIN MM_EJTP MJ ON MJ.CD_COMPANY = GL.CD_COMPANY AND MJ.CD_QTIOTP = GL.TP_GI             
	LEFT JOIN MA_PARTNER MP ON MP.CD_COMPANY = GL.CD_COMPANY AND MP.CD_PARTNER = GL.GI_PARTNER
	LEFT JOIN SA_PROJECTH SP ON SP.CD_COMPANY = GL.CD_COMPANY AND SP.NO_PROJECT = GL.NO_PROJECT       
	LEFT JOIN MA_SALEGRP MG ON MG.CD_COMPANY = GL.CD_COMPANY AND MG.CD_SALEGRP = GL.CD_SALEGRP    
	LEFT JOIN CZ_TR_INVL TI ON TI.CD_COMPANY = GL.CD_COMPANY AND TI.NO_INV = GL.NO_INV AND TI.NO_LINE = GL.SEQ_GIR
	LEFT JOIN (SELECT PL.CD_COMPANY, PL.NO_SO, PL.NO_SOLINE,
			   	      MAX(IL.DT_IO) AS DT_IO,
			   		  SUM(TX.QT_TAX) AS QT_TAX,
					  SUM(TX.CUSTOMS) AS CUSTOMS,
					  SUM(CASE WHEN ISNULL(PL.YN_BL, 'N') = 'Y' THEN PL.QT_PO ELSE 0 END) AS QT_BL
			   FROM PU_POL PL
			   LEFT JOIN (SELECT IL.CD_COMPANY, IL.NO_PSO_MGMT, IL.NO_PSOLINE_MGMT,
			   			  	     MAX(IH.DT_IO) AS DT_IO 
			   			  FROM MM_QTIO IL
			   			  LEFT JOIN MM_QTIOH IH ON IH.CD_COMPANY = IL.CD_COMPANY AND IH.NO_IO = IL.NO_IO
			   			  GROUP BY IL.CD_COMPANY, IL.NO_PSO_MGMT, IL.NO_PSOLINE_MGMT) IL
			   ON IL.CD_COMPANY = PL.CD_COMPANY AND IL.NO_PSO_MGMT = PL.NO_PO AND IL.NO_PSOLINE_MGMT = PL.NO_LINE
			   LEFT JOIN (SELECT IL.CD_COMPANY, IL.NO_PO, IL.NO_POLINE,
			   		   			 SUM(IL.QT_TAX) AS QT_TAX,
								 SUM(DL.CUSTOMS) AS CUSTOMS
			   			  FROM CZ_FI_IMP_PMTL IL
						  LEFT JOIN CZ_PU_IMPORT_DECLARATIONL DL ON DL.CD_COMPANY = IL.CD_COMPANY AND REPLACE(DL.NO_IMPORT, '-', '') = IL.NO_IMPORT AND DL.SEQ = IL.SEQ_IMPORT
			   			  GROUP BY IL.CD_COMPANY, IL.NO_PO, IL.NO_POLINE) TX
			   ON TX.CD_COMPANY = PL.CD_COMPANY AND TX.NO_PO = PL.NO_PO AND TX.NO_POLINE = PL.NO_LINE
	GROUP BY PL.CD_COMPANY, PL.NO_SO, PL.NO_SOLINE) QI
	ON QI.CD_COMPANY = SL.CD_COMPANY AND QI.NO_SO = SL.NO_SO AND QI.NO_SOLINE = SL.SEQ_SO
	WHERE GL.CD_COMPANY = @P_CD_COMPANY
	AND GL.TP_GIR = '002'          
	AND GL.NO_GIR = @P_NO_GIR
	AND GL.NO_HST = @P_NO_HST    
	ORDER BY GL.NO_GIR, GL.SEQ_GIR
END

GO