USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_MA_WORKFLOW_COUNT_14]    Script Date: 2018-08-21 오후 3:53:22 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




-- 협조전작성
ALTER PROCEDURE [NEOE].[SP_CZ_MA_WORKFLOW_COUNT_14]  
(
	@P_CD_COMPANY			NVARCHAR(7),
	@P_ID_USER				NVARCHAR(15),
	@P_NO_KEY				NVARCHAR(20),
	@P_CD_SALEORG			NVARCHAR(7),		
	@P_CD_SALEGRP			NVARCHAR(500)
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT COUNT(1) AS CNT 
FROM SA_SOH SH
JOIN (SELECT SL.CD_COMPANY, SL.NO_SO,
	  		 SUM(SL.QT_SO) AS QT_SO,
	  		 SUM(ISNULL(SL.QT_PO, 0) + ISNULL(SB.QT_STOCK, 0)) AS QT_PO,
	  		 SUM(CASE WHEN QL.TP_BOM = 'P' THEN ISNULL(QO.QT_BOM, 0) 
	  		 							   ELSE (ISNULL(QI.QT_IO, 0) + ISNULL(SB.QT_BOOK, 0)) END) AS QT_IN,
	  		 SUM(SL.QT_GIR) AS QT_GIR
	  FROM SA_SOL SL
	  JOIN CZ_SA_QTNL QL ON QL.CD_COMPANY = SL.CD_COMPANY AND QL.NO_FILE = SL.NO_SO AND QL.NO_LINE = SL.SEQ_SO
	  LEFT JOIN CZ_SA_STOCK_BOOK SB ON SB.CD_COMPANY = SL.CD_COMPANY AND SB.NO_FILE = SL.NO_SO AND SB.NO_LINE = SL.SEQ_SO
	  LEFT JOIN (SELECT PL.CD_COMPANY, PL.NO_SO, PL.NO_SOLINE,
	  	  	   			SUM(OL.QT_IO) AS QT_IO
	  	  		 FROM PU_POL PL
	  	  		 LEFT JOIN MM_QTIO OL ON OL.CD_COMPANY = PL.CD_COMPANY AND OL.NO_PSO_MGMT = PL.NO_PO AND OL.NO_PSOLINE_MGMT = PL.NO_LINE
	  			 WHERE EXISTS (SELECT 1 
							   FROM MM_QTIOH
							   WHERE CD_COMPANY = OL.CD_COMPANY
							   AND NO_IO = OL.NO_IO
							   AND (YN_RETURN IS NULL OR YN_RETURN = 'N'))
	  	  		 GROUP BY PL.CD_COMPANY, PL.NO_SO, PL.NO_SOLINE) QI 
	  ON QI.CD_COMPANY = SL.CD_COMPANY AND QI.NO_SO = SL.NO_SO AND QI.NO_SOLINE = SL.SEQ_SO
	  LEFT JOIN (SELECT OL.CD_COMPANY, OL.NO_PSO_MGMT, OL.NO_PSOLINE_MGMT,
	  	  	   		    SUM(OL.QT_IO) AS QT_BOM
	  	  	     FROM MM_QTIO OL
	  		     WHERE OL.FG_PS = '1'
				 AND OL.FG_IO = '002'
				 AND EXISTS (SELECT 1 
							 FROM MM_QTIOH
							 WHERE CD_COMPANY = OL.CD_COMPANY
							 AND NO_IO = OL.NO_IO
							 AND (YN_RETURN IS NULL OR YN_RETURN = 'N'))
	  	  	     GROUP BY OL.CD_COMPANY, OL.NO_PSO_MGMT, OL.NO_PSOLINE_MGMT) QO 
	  ON QO.CD_COMPANY = SL.CD_COMPANY AND QO.NO_PSO_MGMT = SL.NO_SO AND QO.NO_PSOLINE_MGMT = SL.SEQ_SO
	  WHERE SL.CD_ITEM NOT LIKE 'SD%'
	  GROUP BY SL.CD_COMPANY, SL.NO_SO) SL
ON SL.CD_COMPANY = SH.CD_COMPANY AND SL.NO_SO = SH.NO_SO
WHERE (SH.YN_CLOSE IS NULL OR SH.YN_CLOSE = 'N')
AND SL.QT_SO > SL.QT_GIR
AND SL.QT_PO = SL.QT_IN
AND (ISNULL(@P_CD_COMPANY, '') = '' OR SH.CD_COMPANY = @P_CD_COMPANY)
AND (ISNULL(@P_NO_KEY, '') = '' OR SH.NO_SO = @P_NO_KEY)
AND EXISTS (SELECT 1 
			FROM CZ_MA_WORKFLOWH WH
			LEFT JOIN MA_USER MU ON MU.CD_COMPANY = WH.CD_COMPANY AND MU.ID_USER = WH.ID_SALES
			WHERE WH.CD_COMPANY = SH.CD_COMPANY
			AND WH.NO_KEY = SH.NO_SO
			AND WH.TP_STEP = '11'
			AND WH.YN_DONE = 'Y'
			AND (ISNULL(@P_ID_USER, '') = '' OR WH.ID_LOG = @P_ID_USER)
			AND (ISNULL(@P_CD_SALEGRP, '') = '' OR MU.CD_SALEGRP IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SALEGRP)))
			AND (ISNULL(@P_CD_SALEORG, '') = '' OR EXISTS (SELECT 1 
											               FROM MA_SALEGRP
											               WHERE CD_COMPANY = MU.CD_COMPANY
											               AND CD_SALEGRP = MU.CD_SALEGRP
											               AND CD_SALEORG = @P_CD_SALEORG)))

GO

