USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_MA_WORKFLOW_COUNT_22]    Script Date: 2019-09-06 오전 10:48:13 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- 계산서확인
ALTER PROCEDURE [NEOE].[SP_CZ_MA_WORKFLOW_COUNT_23]  
(
	@P_CD_COMPANY			NVARCHAR(7),
	@P_ID_USER				NVARCHAR(15),
	@P_NO_KEY				NVARCHAR(20),
	@P_CD_SALEORG			NVARCHAR(7),		
	@P_CD_SALEGRP			NVARCHAR(500)
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

SELECT COUNT(1) AS CNT
FROM CZ_PU_IV_CONFIRM IC
LEFT JOIN PU_POH PH ON PH.CD_COMPANY = IC.CD_COMPANY AND PH.NO_PO = IC.NO_PO
WHERE IC.CD_COMPANY = @P_CD_COMPANY
AND ISNULL(IC.YN_DONE, 'N') = 'N'
AND (ISNULL(@P_ID_USER, '') = '' OR PH.NO_EMP = @P_ID_USER OR IC.ID_INSERT = @P_ID_USER)
AND (ISNULL(@P_NO_KEY, '') = '' OR IC.NO_PO = @P_NO_KEY)
AND (ISNULL(@P_CD_SALEGRP, '') = '' OR EXISTS (SELECT 1 
											   FROM SA_SOH SH
											   WHERE SH.CD_COMPANY = PH.CD_COMPANY
											   AND SH.NO_SO = PH.CD_PJT
											   AND SH.CD_SALEGRP IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SALEGRP))))
AND (ISNULL(@P_CD_SALEORG, '') = '' OR EXISTS (SELECT 1 
											   FROM SA_SOH SH
											   JOIN MA_SALEGRP SG ON SG.CD_COMPANY = SH.CD_COMPANY AND SG.CD_SALEGRP = SH.CD_SALEGRP
											   WHERE SH.CD_COMPANY = PH.CD_COMPANY
											   AND SH.NO_SO = PH.CD_PJT
											   AND SG.CD_SALEORG = @P_CD_SALEORG))


GO

