USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_AC_RECEIVABLE_RPT_U]    Script Date: 2017-03-22 오후 8:15:08 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER PROCEDURE [NEOE].[SP_CZ_SA_AC_RECEIVABLE_RPT_U]        
(        
	 @P_CD_COMPANY		NVARCHAR(7),
	 @P_NO_KEY			NVARCHAR(100),
	 @P_NO_EMP			NVARCHAR(10),
	 @P_DC_RMK			NVARCHAR(MAX),
	 @P_ID_UPDATE		NVARCHAR(15)
)
AS        

IF NOT EXISTS(SELECT 1 
			  FROM CZ_SA_AC_RECEIVABLE
			  WHERE CD_COMPANY = @P_CD_COMPANY
			  AND NO_KEY = @P_NO_KEY)
BEGIN
	INSERT INTO CZ_SA_AC_RECEIVABLE
	(
		CD_COMPANY,
		NO_KEY,
		NO_EMP,
		DC_RMK,
		ID_INSERT,
		DTS_INSERT
	)
	VALUES
	(
		@P_CD_COMPANY,
		@P_NO_KEY,
		@P_NO_EMP,
		@P_DC_RMK,
		@P_ID_UPDATE,
		NEOE.SF_SYSDATE(GETDATE())
	)
END
ELSE
BEGIN
	UPDATE CZ_SA_AC_RECEIVABLE
	SET NO_EMP = @P_NO_EMP,
		DC_RMK = @P_DC_RMK,
		ID_UPDATE = @P_ID_UPDATE,
		DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE())
	WHERE CD_COMPANY = @P_CD_COMPANY
	AND NO_KEY = @P_NO_KEY
END


GO

