USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_AC_RECEIVABLE_RPT_S]    Script Date: 2017-02-22 오후 4:09:40 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER PROCEDURE [NEOE].[SP_CZ_SA_AC_RECEIVABLE_RPT_S2]        
(        
	 @P_CD_COMPANY		NVARCHAR(7),
	 @P_DT_FROM			NVARCHAR(8),
	 @P_DT_TO			NVARCHAR(8),
	 @P_DT_TODAY		NVARCHAR(8),
	 @P_CD_PARTNER		NVARCHAR(MAX),
	 @P_CD_DEPT			NVARCHAR(12),
	 @P_CD_SALEGRP		NVARCHAR(12),
	 @P_NO_EMP			NVARCHAR(10),
	 @P_NO_PROJECT		NVARCHAR(20),
	 @P_NO_SO			NVARCHAR(20),
	 @P_NO_IV			NVARCHAR(20),
	 @P_YN_DSP_ZERO		NVARCHAR(1),
	 @P_NO_MONTH		NUMERIC(5, 0) = 0
)
AS        
 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT IH.CD_COMPANY, 
	   IH.CD_PARTNER AS NO_KEY,
	   MP.LN_PARTNER AS NM_PARTNER,
	   MP.DT_RCP_PREARRANGED,
	   MAX(IH.NM_PARTNER_GRP) AS NM_PARTNER_GRP,
	   AVG(DATEDIFF(DAY, IH.DT_PROCESS, @P_DT_TODAY)) AS DT_IV_DAY,
	   AVG(DATEDIFF(DAY, IH.DT_PROCESS, RH.DT_RCP)) AS DT_RCP_DAY,
	   MAX(IH.NO_EMP) AS NO_EMP,
	   MAX(ME.NM_KOR) AS NM_EMP,
	   MAX(MC.NM_SYSDEF) AS NM_EXCH,
	   SUM(IL.AM_EX_CLS) AS AM_EX_CLS,
	   SUM(IL.AM_CLS) AS AM_CLS,
	   SUM(RH.AM_RCP_EX) AS AM_RCP_EX,
	   SUM(RH.AM_RCP) AS AM_RCP,
	   SUM(ISNULL(IL.AM_EX_CLS, 0) - ISNULL(RH.AM_RCP_EX, 0)) AS AM_EX_REMAIN,
	   SUM(ISNULL(IL.AM_CLS, 0) - ISNULL(RH.AM_RCP, 0)) AS AM_REMAIN,
	   SUM(CASE WHEN IH.DT_IV_MONTH > 2 AND IH.DT_IV_MONTH <= 3 THEN (ISNULL(IL.AM_EX_CLS, 0) - ISNULL(RH.AM_RCP_EX, 0)) ELSE 0 END) AS AM_EX_2MONTH,
	   SUM(CASE WHEN IH.DT_IV_MONTH > 3 AND IH.DT_IV_MONTH <= 6 THEN (ISNULL(IL.AM_EX_CLS, 0) - ISNULL(RH.AM_RCP_EX, 0)) ELSE 0 END) AS AM_EX_3MONTH,
	   SUM(CASE WHEN IH.DT_IV_MONTH > 6 AND IH.DT_IV_MONTH <= 12 THEN (ISNULL(IL.AM_EX_CLS, 0) - ISNULL(RH.AM_RCP_EX, 0)) ELSE 0 END) AS AM_EX_6MONTH,
	   SUM(CASE WHEN IH.DT_IV_MONTH > 12 THEN (ISNULL(IL.AM_EX_CLS, 0) - ISNULL(RH.AM_RCP_EX, 0)) ELSE 0 END) AS AM_EX_12MONTH,
	   SUM(CASE WHEN IH.DT_IV_MONTH > 2 AND IH.DT_IV_MONTH <= 3 THEN (ISNULL(IL.AM_CLS, 0) - ISNULL(RH.AM_RCP, 0)) ELSE 0 END) AS AM_2MONTH,
	   SUM(CASE WHEN IH.DT_IV_MONTH > 3 AND IH.DT_IV_MONTH <= 6 THEN (ISNULL(IL.AM_CLS, 0) - ISNULL(RH.AM_RCP, 0)) ELSE 0 END) AS AM_3MONTH,
	   SUM(CASE WHEN IH.DT_IV_MONTH > 6 AND IH.DT_IV_MONTH <= 12 THEN (ISNULL(IL.AM_CLS, 0) - ISNULL(RH.AM_RCP, 0)) ELSE 0 END) AS AM_6MONTH,
	   SUM(CASE WHEN IH.DT_IV_MONTH > 12 THEN (ISNULL(IL.AM_CLS, 0) - ISNULL(RH.AM_RCP, 0)) ELSE 0 END) AS AM_12MONTH,
	   MAX(AR.DC_RMK) AS DC_RMK
FROM (SELECT IH.CD_COMPANY, IH.NO_IV,
	  		 IH.DT_PROCESS,
	  		 IH.DC_REMARK,
			 IH.CD_EXCH,
	  		 IH.RT_EXCH,
			 IH.CD_PARTNER,
			 MC1.NM_SYSDEF AS NM_PARTNER_GRP,
	  		 (CASE WHEN AR.NO_EMP IS NOT NULL THEN AR.NO_EMP
	  		 	   WHEN AR.NO_EMP IS NULL AND IL.NO_SO_EMP IS NOT NULL THEN IL.NO_SO_EMP 
	  		 	   ELSE IL.NO_PJ_EMP END) AS NO_EMP,
	  		 DATEDIFF(MONTH, IH.DT_PROCESS, @P_DT_TODAY) AS DT_IV_MONTH,
	  		 AR.DC_RMK 
	  FROM SA_IVH IH
	  JOIN (SELECT IL.CD_COMPANY, IL.NO_IV,
	  			   MAX(SH.NO_EMP) AS NO_SO_EMP,
	  			   MAX(PH.NO_EMP) AS NO_PJ_EMP,
				   MAX(QH.CD_PARTNER_GRP) AS CD_PARTNER_GRP
	  	    FROM SA_IVL IL
	  	    LEFT JOIN SA_SOH SH ON SH.CD_COMPANY = IL.CD_COMPANY AND SH.NO_SO = IL.NO_SO
	  	    LEFT JOIN SA_PROJECTH PH ON PH.CD_COMPANY = IL.CD_COMPANY AND PH.NO_PROJECT = IL.CD_PJT
			LEFT JOIN CZ_SA_QTNH QH ON QH.CD_COMPANY = SH.CD_COMPANY AND QH.NO_FILE = SH.NO_SO
	  	    WHERE (ISNULL(@P_NO_PROJECT, '') = '' OR IL.CD_PJT LIKE @P_NO_PROJECT + '%')
	  	    AND (ISNULL(@P_NO_SO, '') = '' OR IL.NO_SO LIKE @P_NO_SO + '%')
	  	    GROUP BY IL.CD_COMPANY, IL.NO_IV) IL
	  ON IL.CD_COMPANY = IH.CD_COMPANY AND IL.NO_IV = IH.NO_IV
	  LEFT JOIN CZ_SA_AC_RECEIVABLE AR ON AR.CD_COMPANY = IH.CD_COMPANY AND AR.NO_KEY = IH.NO_IV
	  LEFT JOIN MA_CODEDTL MC1 ON MC1.CD_COMPANY = IL.CD_COMPANY AND MC1.CD_FIELD = 'MA_B000065' AND MC1.CD_SYSDEF = IL.CD_PARTNER_GRP
	  WHERE IH.CD_COMPANY = @P_CD_COMPANY
	  AND IH.DT_PROCESS BETWEEN @P_DT_FROM AND @P_DT_TO
	  AND IH.DT_PROCESS <= @P_DT_TODAY
	  AND (ISNULL(@P_NO_IV, '') = '' OR IH.NO_IV = @P_NO_IV)
	  AND (ISNULL(@P_CD_PARTNER, '') = '' OR IH.CD_PARTNER IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_PARTNER)))) IH
JOIN (SELECT IH.CD_COMPANY, IH.NO_IV, IH.DT_PROCESS,
			 SUM(CASE WHEN IL.YN_RETURN = 'Y' THEN -(IL.AM_EX_CLS + CONVERT(NUMERIC(17, 4), ROUND(IL.VAT / IH.RT_EXCH, 2))) 
	  									      ELSE (IL.AM_EX_CLS + CONVERT(NUMERIC(17, 4), ROUND(IL.VAT / IH.RT_EXCH, 2))) END) AS AM_EX_CLS,
	  	     SUM(CASE WHEN IL.YN_RETURN = 'Y' THEN -(IL.AM_CLS + IL.VAT) 
	  									      ELSE (IL.AM_CLS + IL.VAT) END) AS AM_CLS 
	  FROM SA_IVH IH
	  JOIN SA_IVL IL ON IL.CD_COMPANY = IH.CD_COMPANY AND IL.NO_IV = IH.NO_IV
	  GROUP BY IH.CD_COMPANY, IH.NO_IV, IH.DT_PROCESS) IL
ON IL.CD_COMPANY = IH.CD_COMPANY AND IL.NO_IV = IH.NO_IV AND IL.DT_PROCESS = IH.DT_PROCESS
LEFT JOIN (SELECT RH.CD_COMPANY,
				  RD.NO_IV,
				  MAX(RH.DT_RCP) AS DT_RCP,
				  SUM(RD.AM_RCP_EX) AS AM_RCP_EX,
				  SUM(RD.AM_RCP) AS AM_RCP
		   FROM SA_RCPH RH
		   LEFT JOIN (SELECT RD.CD_COMPANY, RD.NO_RCP, RD.NO_TX AS NO_IV,
  							 (ISNULL(RD.AM_RCP_TX, 0) + ISNULL(RD.AM_PL, 0)) AS AM_RCP,
  							 ISNULL(RD.AM_RCP_TX_EX, 0) AS AM_RCP_EX 
					  FROM SA_RCPD RD 
					  UNION ALL
					  SELECT BD.CD_COMPANY, BD.NO_RCP, BD.NO_IV,
  							 (ISNULL(BD.AM_RCPS, 0) + ISNULL(BD.AM_PL, 0)) AS AM_RCP,
  							 ISNULL(BD.AM_RCPS_EX, 0) AS AM_RCP_EX 
					  FROM SA_BILLSD BD) RD
		   ON RD.CD_COMPANY = RH.CD_COMPANY AND RD.NO_RCP = RH.NO_RCP
		   WHERE RD.NO_IV IS NOT NULL
		   AND RH.DT_RCP <= @P_DT_TODAY
		   GROUP BY RH.CD_COMPANY, RD.NO_IV) RH
ON RH.CD_COMPANY = IH.CD_COMPANY AND RH.NO_IV = IH.NO_IV
LEFT JOIN MA_EMP ME ON ME.CD_COMPANY = IH.CD_COMPANY AND ME.NO_EMP = IH.NO_EMP
LEFT JOIN MA_PARTNER MP ON MP.CD_COMPANY = IH.CD_COMPANY AND MP.CD_PARTNER = IH.CD_PARTNER
LEFT JOIN MA_CODEDTL MC ON MC.CD_COMPANY = IH.CD_COMPANY AND MC.CD_FIELD = 'MA_B000005' AND MC.CD_SYSDEF = IH.CD_EXCH
LEFT JOIN (SELECT CD_COMPANY, NO_EMP,
			      MAX(CD_SALEGRP) AS CD_SALEGRP 
		   FROM MA_USER
		   GROUP BY CD_COMPANY, NO_EMP) MU
ON MU.CD_COMPANY = ME.CD_COMPANY AND MU.NO_EMP = ME.NO_EMP
LEFT JOIN CZ_SA_AC_RECEIVABLE AR ON AR.CD_COMPANY = IH.CD_COMPANY AND AR.NO_KEY = IH.CD_PARTNER
WHERE (@P_NO_MONTH = 0 OR IH.DT_IV_MONTH > @P_NO_MONTH) 
AND (ISNULL(@P_YN_DSP_ZERO, 'N') = 'Y' OR (ISNULL(IL.AM_CLS, 0) - ISNULL(RH.AM_RCP, 0)) <> 0)
AND (ISNULL(@P_CD_DEPT, '') = '' OR ME.CD_DEPT = @P_CD_DEPT)
AND (ISNULL(@P_CD_SALEGRP, '') = '' OR MU.CD_SALEGRP = @P_CD_SALEGRP)
AND (ISNULL(@P_NO_EMP, '') = '' OR ME.NO_EMP = @P_NO_EMP)
GROUP BY IH.CD_COMPANY, 
		 IH.CD_PARTNER,
		 MP.LN_PARTNER,
		 MP.DT_RCP_PREARRANGED

GO

