USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_AC_RECEIVABLE_RPT_S]    Script Date: 2017-02-22 오후 4:09:40 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [NEOE].[SP_CZ_SA_AC_RECEIVABLE_RPT_S3]        
(        
	 @P_CD_COMPANY		NVARCHAR(7),
	 @P_DT_FROM			NVARCHAR(8),
	 @P_DT_TO			NVARCHAR(8),
	 @P_DT_TODAY		NVARCHAR(8),
	 @P_CD_PARTNER		NVARCHAR(MAX),
	 @P_CD_DEPT			NVARCHAR(12),
	 @P_CD_SALEGRP		NVARCHAR(12),
	 @P_NO_EMP			NVARCHAR(10),
	 @P_NO_PROJECT		NVARCHAR(20),
	 @P_NO_SO			NVARCHAR(20),
	 @P_NO_IV			NVARCHAR(20),
	 @P_YN_DSP_ZERO		NVARCHAR(1),
	 @P_NO_MONTH		NUMERIC(5, 0) = 0
)
AS        
 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT IH.CD_COMPANY, MD.NM_DEPT,
	   SUM(CASE WHEN IH.DT_IV_MONTH <= 2 THEN (ISNULL(IL.AM_CLS, 0) - ISNULL(RH.AM_RCP, 0)) ELSE 0 END) AS AM_1MONTH,
	   SUM(CASE WHEN IH.DT_IV_MONTH > 2 AND IH.DT_IV_MONTH <= 3 THEN (ISNULL(IL.AM_CLS, 0) - ISNULL(RH.AM_RCP, 0)) ELSE 0 END) AS AM_2MONTH,
	   SUM(CASE WHEN IH.DT_IV_MONTH > 3 AND IH.DT_IV_MONTH <= 6 THEN (ISNULL(IL.AM_CLS, 0) - ISNULL(RH.AM_RCP, 0)) ELSE 0 END) AS AM_3MONTH,
	   SUM(CASE WHEN IH.DT_IV_MONTH > 6 AND IH.DT_IV_MONTH <= 12 THEN (ISNULL(IL.AM_CLS, 0) - ISNULL(RH.AM_RCP, 0)) ELSE 0 END) AS AM_6MONTH,
	   SUM(CASE WHEN IH.DT_IV_MONTH > 12 THEN (ISNULL(IL.AM_CLS, 0) - ISNULL(RH.AM_RCP, 0)) ELSE 0 END) AS AM_12MONTH,
	   SUM(CASE WHEN IH.DT_IV_MONTH > 3 THEN (ISNULL(IL.AM_CLS_BEFORE, 0) - ISNULL(RH.AM_RCP_BEFORE, 0)) ELSE 0 END) AS AM_LONG_BEFORE,
	   SUM(ISNULL(IL.AM_CLS_BEFORE, 0) - ISNULL(RH.AM_RCP_BEFORE, 0)) AS AM_BEFORE,
	   SUM(CASE WHEN IH.DT_IV_MONTH > 2 THEN (ISNULL(IL.AM_CLS, 0) - ISNULL(RH.AM_RCP, 0)) ELSE 0 END) AS AM_LONG_TOTAL,
	   SUM(ISNULL(IL.AM_CLS, 0) - ISNULL(RH.AM_RCP, 0)) AS AM_TOTAL,
	   SUM(CASE WHEN IH.DT_IV_MONTH > 3 THEN ISNULL(RH.AM_RCP_MONTH, 0) ELSE 0 END) AS AM_LONG_RCP,
	   SUM(ISNULL(RH.AM_RCP_MONTH, 0)) AS AM_RCP,
	   ROUND(CASE WHEN SUM(CASE WHEN IH.DT_IV_MONTH > 3 THEN (ISNULL(IL.AM_CLS_BEFORE, 0) - ISNULL(RH.AM_RCP_BEFORE, 0)) ELSE 0 END) <> 0 THEN (SUM(CASE WHEN IH.DT_IV_MONTH > 3 THEN ISNULL(RH.AM_RCP_MONTH, 0) ELSE 0 END) / SUM(CASE WHEN IH.DT_IV_MONTH > 3 THEN (ISNULL(IL.AM_CLS_BEFORE, 0) - ISNULL(RH.AM_RCP_BEFORE, 0)) ELSE 0 END) * 100) ELSE 0 END, 2) AS RT_LONG_RCP,
	   ROUND(CASE WHEN SUM(ISNULL(IL.AM_CLS_BEFORE, 0) - ISNULL(RH.AM_RCP_BEFORE, 0)) <> 0 THEN (SUM(ISNULL(RH.AM_RCP_MONTH, 0)) / SUM(ISNULL(IL.AM_CLS_BEFORE, 0) - ISNULL(RH.AM_RCP_BEFORE, 0)) * 100) ELSE 0 END, 2) AS RT_RCP
FROM (SELECT CD_COMPANY,
			 NO_IV,
			 DT_PROCESS,
			 DATEDIFF(MONTH, DT_PROCESS, @P_DT_TODAY) AS DT_IV_MONTH 
	  FROM SA_IVH) IH
LEFT JOIN (SELECT IH.CD_COMPANY, IH.NO_IV,
		   		  (CASE WHEN AR.NO_EMP IS NOT NULL THEN AR.NO_EMP
		   		  	  	WHEN AR.NO_EMP IS NULL AND IL.NO_SO_EMP IS NOT NULL THEN IL.NO_SO_EMP 
		   		  	  	ELSE IL.NO_PJ_EMP END) AS NO_EMP,
		   		  IL.AM_CLS,
		   		  (CASE WHEN LEFT(IH.DT_PROCESS, 6) < LEFT(@P_DT_TODAY, 6) THEN IL.AM_CLS ELSE 0 END) AS AM_CLS_BEFORE 
		   FROM SA_IVH IH
		   JOIN (SELECT IL.CD_COMPANY, IL.NO_IV,
		   			    MAX(SH.NO_EMP) AS NO_SO_EMP,
		   			    MAX(PH.NO_EMP) AS NO_PJ_EMP,
		   			    SUM(CASE WHEN IL.YN_RETURN = 'Y' THEN -(ISNULL(IL.AM_CLS, 0) + ISNULL(IL.VAT, 0)) 
		   			    								 ELSE (ISNULL(IL.AM_CLS, 0) + ISNULL(IL.VAT, 0)) END) AS AM_CLS
		   	     FROM SA_IVL IL
		   	     LEFT JOIN SA_SOH SH ON SH.CD_COMPANY = IL.CD_COMPANY AND SH.NO_SO = IL.NO_SO
		   	     LEFT JOIN SA_PROJECTH PH ON PH.CD_COMPANY = IL.CD_COMPANY AND PH.NO_PROJECT = IL.CD_PJT
		   	     GROUP BY IL.CD_COMPANY, IL.NO_IV) IL
		   ON IL.CD_COMPANY = IH.CD_COMPANY AND IL.NO_IV = IH.NO_IV
		   LEFT JOIN CZ_SA_AC_RECEIVABLE AR ON AR.CD_COMPANY = IH.CD_COMPANY AND AR.NO_KEY = IH.NO_IV) IL
ON IL.CD_COMPANY = IH.CD_COMPANY AND IL.NO_IV = IH.NO_IV
LEFT JOIN (SELECT RH.CD_COMPANY,
				  RD.NO_IV,
				  SUM(RD.AM_RCP) AS AM_RCP,
				  SUM(CASE WHEN LEFT(RH.DT_RCP, 6) < LEFT(@P_DT_TODAY, 6) AND LEFT(IH.DT_PROCESS, 6) < LEFT(@P_DT_TODAY, 6) THEN RD.AM_RCP ELSE 0 END) AS AM_RCP_BEFORE,
				  SUM(CASE WHEN LEFT(RH.DT_RCP, 6) = LEFT(@P_DT_TODAY, 6) THEN RD.AM_RCP ELSE 0 END) AS AM_RCP_MONTH
		   FROM SA_RCPH RH
		   LEFT JOIN (SELECT RD.CD_COMPANY, RD.NO_RCP, RD.NO_TX AS NO_IV,
  		   					 (ISNULL(RD.AM_RCP_TX, 0) + ISNULL(RD.AM_PL, 0)) AS AM_RCP
		   			  FROM SA_RCPD RD 
		   			  UNION ALL
		   			  SELECT BD.CD_COMPANY, BD.NO_RCP, BD.NO_IV,
  		   					 (ISNULL(BD.AM_RCPS, 0) + ISNULL(BD.AM_PL, 0)) AS AM_RCP
		   			  FROM SA_BILLSD BD) RD
		   ON RD.CD_COMPANY = RH.CD_COMPANY AND RD.NO_RCP = RH.NO_RCP
		   LEFT JOIN SA_IVH IH ON IH.CD_COMPANY = RD.CD_COMPANY AND IH.NO_IV = RD.NO_IV
		   WHERE RH.DT_RCP <= @P_DT_TODAY
		   GROUP BY RH.CD_COMPANY, RD.NO_IV) RH
ON RH.CD_COMPANY = IL.CD_COMPANY AND RH.NO_IV = IL.NO_IV
LEFT JOIN MA_EMP ME ON ME.CD_COMPANY = IL.CD_COMPANY AND ME.NO_EMP = IL.NO_EMP
LEFT JOIN MA_DEPT MD ON MD.CD_COMPANY = ME.CD_COMPANY AND MD.CD_DEPT = ME.CD_DEPT
WHERE IH.CD_COMPANY = @P_CD_COMPANY
AND IH.DT_PROCESS <= @P_DT_TODAY
GROUP BY IH.CD_COMPANY, MD.NM_DEPT

SELECT IH.CD_COMPANY, IH.YYYYMM,
	   ISNULL(IL.AM_CLS, 0) AS AM_CLS,
	   ISNULL(RH1.AM_RCP, 0) AS AM_RCP_OLD,
	   ISNULL(RH.AM_RCP, 0) AS AM_RCP,
	   ISNULL(RH1.AM_RCP_MONTH, 0) AS AM_RCP_MONTH,
	   ROUND(CASE WHEN (ISNULL(IL.AM_CLS_BEFORE, 0) - ISNULL(RH1.AM_RCP_BEFORE, 0)) = 0 THEN 0 
																						ELSE ((ISNULL(RH1.AM_RCP_MONTH, 0) / (ISNULL(IL.AM_CLS_BEFORE, 0) - ISNULL(RH1.AM_RCP_BEFORE, 0))) * 100) END, 2) AS RT_RCP_MONTH,
	   ISNULL(RH1.AM_RCP_LONG_MONTH, 0) AS AM_RCP_LONG_MONTH,
	   ROUND(CASE WHEN (ISNULL(IL.AM_CLS_LONG_BEFORE, 0) - ISNULL(RH1.AM_RCP_LONG_BEFORE, 0)) = 0 THEN 0 
																								  ELSE ((ISNULL(RH1.AM_RCP_LONG_MONTH, 0) / (ISNULL(IL.AM_CLS_LONG_BEFORE, 0) - ISNULL(RH1.AM_RCP_LONG_BEFORE, 0))) * 100) END, 2) AS RT_RCP_LONG_MONTH,
	   (ISNULL(IL.AM_CLS_LONG, 0) - ISNULL(RH1.AM_RCP_LONG, 0)) AS AM_REMAIN_LONG_OLD,
	   (ISNULL(IL.AM_CLS_LONG, 0) - ISNULL(RH.AM_RCP_LONG, 0)) AS AM_REMAIN_LONG,
	   (ISNULL(IL.AM_CLS, 0) - ISNULL(RH1.AM_RCP, 0)) AS AM_REMAIN_OLD,
	   (ISNULL(IL.AM_CLS, 0) - ISNULL(RH.AM_RCP, 0)) AS AM_REMAIN,
	   ROUND(CASE WHEN (ISNULL(IL.AM_CLS_LONG_BEFORE, 0) - ISNULL(RH1.AM_RCP_LONG_BEFORE, 0)) = 0 THEN 0 
																								  ELSE ((ISNULL(IL.AM_CLS_LONG, 0) - ISNULL(RH1.AM_RCP_LONG, 0)) / (ISNULL(IL.AM_CLS_LONG_BEFORE, 0) - ISNULL(RH1.AM_RCP_LONG_BEFORE, 0)) * 100) END, 2) AS RT_REMAIN_LONG,
	   ROUND(CASE WHEN (ISNULL(IL.AM_CLS_BEFORE, 0) - ISNULL(RH1.AM_RCP_BEFORE, 0)) = 0 THEN 0 
																						ELSE ((ISNULL(IL.AM_CLS, 0) - ISNULL(RH1.AM_RCP, 0)) / (ISNULL(IL.AM_CLS_BEFORE, 0) - ISNULL(RH1.AM_RCP_BEFORE, 0)) * 100) END, 2) AS RT_REMAIN,
	   (ISNULL(IL.AM_CLS_1, 0) - ISNULL(RH1.AM_RCP_1, 0)) AS AM_REMAIN_OLD_1,
	   (ISNULL(IL.AM_CLS_2, 0) - ISNULL(RH1.AM_RCP_2, 0)) AS AM_REMAIN_OLD_2,
	   (ISNULL(IL.AM_CLS_3, 0) - ISNULL(RH1.AM_RCP_3, 0)) AS AM_REMAIN_OLD_3,
	   (ISNULL(IL.AM_CLS_6, 0) - ISNULL(RH1.AM_RCP_6, 0)) AS AM_REMAIN_OLD_6,
	   (ISNULL(IL.AM_CLS_12, 0) - ISNULL(RH1.AM_RCP_12, 0)) AS AM_REMAIN_OLD_12,
	   (ISNULL(IL.AM_CLS_1, 0) - ISNULL(RH.AM_RCP_1, 0)) AS AM_REMAIN_1,
	   (ISNULL(IL.AM_CLS_2, 0) - ISNULL(RH.AM_RCP_2, 0)) AS AM_REMAIN_2,
	   (ISNULL(IL.AM_CLS_3, 0) - ISNULL(RH.AM_RCP_3, 0)) AS AM_REMAIN_3,
	   (ISNULL(IL.AM_CLS_6, 0) - ISNULL(RH.AM_RCP_6, 0)) AS AM_REMAIN_6,
	   (ISNULL(IL.AM_CLS_12, 0) - ISNULL(RH.AM_RCP_12, 0)) AS AM_REMAIN_12
FROM (SELECT IH.CD_COMPANY, 
	  		 LEFT(IH.DT_PROCESS, 6) AS YYYYMM
	  FROM SA_IVH IH
	  WHERE IH.DT_PROCESS <= @P_DT_TODAY
	  GROUP BY IH.CD_COMPANY, LEFT(IH.DT_PROCESS, 6)) IH
LEFT JOIN (SELECT IH.CD_COMPANY, IH.YYYYMM,
		   	      SUM(IL.AM_CLS) AS AM_CLS,
				  SUM(CASE WHEN LEFT(IL.DT_PROCESS, 6) < IH.YYYYMM THEN IL.AM_CLS ELSE 0 END) AS AM_CLS_BEFORE,
				  SUM(CASE WHEN LEFT(IL.DT_PROCESS, 6) < IH.YYYYMM AND DATEDIFF(MONTH, IL.DT_PROCESS, CONVERT(CHAR(8), DATEADD(MONTH, -1, IH.DT_PROCESS), 112)) > 2 THEN IL.AM_CLS ELSE 0 END) AS AM_CLS_LONG_BEFORE,
				  SUM(CASE WHEN DATEDIFF(MONTH, IL.DT_PROCESS, IH.DT_PROCESS) > 2 THEN IL.AM_CLS ELSE 0 END) AS AM_CLS_LONG,
				  SUM(CASE WHEN DATEDIFF(MONTH, IL.DT_PROCESS, IH.DT_PROCESS) <= 2 THEN IL.AM_CLS ELSE 0 END) AS AM_CLS_1,
				  SUM(CASE WHEN DATEDIFF(MONTH, IL.DT_PROCESS, IH.DT_PROCESS) > 2 AND DATEDIFF(MONTH, IL.DT_PROCESS, IH.DT_PROCESS) <= 3 THEN IL.AM_CLS ELSE 0 END) AS AM_CLS_2,
				  SUM(CASE WHEN DATEDIFF(MONTH, IL.DT_PROCESS, IH.DT_PROCESS) > 3 AND DATEDIFF(MONTH, IL.DT_PROCESS, IH.DT_PROCESS) <= 6 THEN IL.AM_CLS ELSE 0 END) AS AM_CLS_3,
				  SUM(CASE WHEN DATEDIFF(MONTH, IL.DT_PROCESS, IH.DT_PROCESS) > 6 AND DATEDIFF(MONTH, IL.DT_PROCESS, IH.DT_PROCESS) <= 12 THEN IL.AM_CLS ELSE 0 END) AS AM_CLS_6,
				  SUM(CASE WHEN DATEDIFF(MONTH, IL.DT_PROCESS, IH.DT_PROCESS) > 12 THEN IL.AM_CLS ELSE 0 END) AS AM_CLS_12
		   FROM (SELECT IH.CD_COMPANY, 
		   		 		LEFT(IH.DT_PROCESS, 6) AS YYYYMM,
						MAX(IH.DT_PROCESS) AS DT_PROCESS  
		   		 FROM SA_IVH IH
		   		 GROUP BY IH.CD_COMPANY, LEFT(IH.DT_PROCESS, 6)) IH
		   LEFT JOIN (SELECT IH.CD_COMPANY,
		   			  	     IH.DT_PROCESS,
		   			  	     SUM(IL.AM_CLS) AS AM_CLS
		   			  FROM SA_IVH IH
		   			  JOIN (SELECT IL.CD_COMPANY, IL.NO_IV,
		   			  			   SUM(CASE WHEN IL.YN_RETURN = 'Y' THEN -(IL.AM_CLS + IL.VAT) ELSE (IL.AM_CLS + IL.VAT) END) AS AM_CLS  
		   			  		FROM SA_IVL IL
		   			  		GROUP BY IL.CD_COMPANY, IL.NO_IV) IL
		   			  ON IL.CD_COMPANY = IH.CD_COMPANY AND IL.NO_IV = IH.NO_IV
					  WHERE IH.DT_PROCESS <= @P_DT_TODAY
		   			  GROUP BY IH.CD_COMPANY, IH.DT_PROCESS) IL
		   ON IL.CD_COMPANY = IH.CD_COMPANY AND LEFT(IL.DT_PROCESS, 6) <= IH.YYYYMM
		   GROUP BY IH.CD_COMPANY, IH.YYYYMM) IL
ON IL.CD_COMPANY = IH.CD_COMPANY AND IL.YYYYMM = IH.YYYYMM
LEFT JOIN (SELECT IH.CD_COMPANY, IH.YYYYMM,
		   	      SUM(RH.AM_RCP) AS AM_RCP,
				  SUM(CASE WHEN DATEDIFF(MONTH, RH.DT_PROCESS, IH.DT_PROCESS) > 2 THEN RH.AM_RCP ELSE 0 END) AS AM_RCP_LONG,
				  SUM(CASE WHEN DATEDIFF(MONTH, RH.DT_PROCESS, IH.DT_PROCESS) <= 2 THEN RH.AM_RCP ELSE 0 END) AS AM_RCP_1,
				  SUM(CASE WHEN DATEDIFF(MONTH, RH.DT_PROCESS, IH.DT_PROCESS) > 2 AND DATEDIFF(MONTH, RH.DT_PROCESS, IH.DT_PROCESS) <= 3 THEN RH.AM_RCP ELSE 0 END) AS AM_RCP_2,
				  SUM(CASE WHEN DATEDIFF(MONTH, RH.DT_PROCESS, IH.DT_PROCESS) > 3 AND DATEDIFF(MONTH, RH.DT_PROCESS, IH.DT_PROCESS) <= 6 THEN RH.AM_RCP ELSE 0 END) AS AM_RCP_3,
				  SUM(CASE WHEN DATEDIFF(MONTH, RH.DT_PROCESS, IH.DT_PROCESS) > 6 AND DATEDIFF(MONTH, RH.DT_PROCESS, IH.DT_PROCESS) <= 12 THEN RH.AM_RCP ELSE 0 END) AS AM_RCP_6,
				  SUM(CASE WHEN DATEDIFF(MONTH, RH.DT_PROCESS, IH.DT_PROCESS) > 12 THEN RH.AM_RCP ELSE 0 END) AS AM_RCP_12
		   FROM (SELECT IH.CD_COMPANY, 
		   		 		LEFT(IH.DT_PROCESS, 6) AS YYYYMM,
						MAX(IH.DT_PROCESS) AS DT_PROCESS
		   		 FROM SA_IVH IH
		   		 GROUP BY IH.CD_COMPANY, LEFT(IH.DT_PROCESS, 6)) IH
		   LEFT JOIN (SELECT RH.CD_COMPANY, 
		   					 IH.DT_PROCESS,
		   					 SUM(RD.AM_RCP) AS AM_RCP
					  FROM SA_RCPH RH
					  LEFT JOIN (SELECT RD.CD_COMPANY, RD.NO_RCP, RD.NO_TX AS NO_IV,
  										(ISNULL(RD.AM_RCP_TX, 0) + ISNULL(RD.AM_PL, 0)) AS AM_RCP
								 FROM SA_RCPD RD 
								 UNION ALL
								 SELECT BD.CD_COMPANY, BD.NO_RCP, BD.NO_IV,
  										(ISNULL(BD.AM_RCPS, 0) + ISNULL(BD.AM_PL, 0)) AS AM_RCP
								FROM SA_BILLSD BD) RD
					  ON RD.CD_COMPANY = RH.CD_COMPANY AND RD.NO_RCP = RH.NO_RCP
					  LEFT JOIN SA_IVH IH ON IH.CD_COMPANY = RD.CD_COMPANY AND IH.NO_IV = RD.NO_IV
					  WHERE IH.DT_PROCESS <= @P_DT_TODAY
					  GROUP BY RH.CD_COMPANY, IH.DT_PROCESS) RH
		   ON RH.CD_COMPANY = IH.CD_COMPANY AND LEFT(RH.DT_PROCESS, 6) <= IH.YYYYMM
		   GROUP BY IH.CD_COMPANY, IH.YYYYMM) RH
ON RH.CD_COMPANY = IH.CD_COMPANY AND RH.YYYYMM = IH.YYYYMM
LEFT JOIN (SELECT IH.CD_COMPANY, IH.YYYYMM,
				  SUM(RH.AM_RCP) AS AM_RCP,
				  SUM(CASE WHEN LEFT(RH.DT_RCP, 6) = IH.YYYYMM THEN RH.AM_RCP ELSE 0 END) AS AM_RCP_MONTH,
				  SUM(CASE WHEN DATEDIFF(MONTH, RH.DT_PROCESS, CONVERT(CHAR(8), DATEADD(MONTH, -1, IH.DT_PROCESS), 112)) > 2 AND LEFT(RH.DT_RCP, 6) = IH.YYYYMM THEN RH.AM_RCP ELSE 0 END) AS AM_RCP_LONG_MONTH,
				  SUM(CASE WHEN LEFT(RH.DT_PROCESS, 6) < IH.YYYYMM AND LEFT(RH.DT_RCP, 6) < IH.YYYYMM THEN RH.AM_RCP ELSE 0 END) AS AM_RCP_BEFORE,
				  SUM(CASE WHEN DATEDIFF(MONTH, RH.DT_PROCESS, CONVERT(CHAR(8), DATEADD(MONTH, -1, IH.DT_PROCESS), 112)) > 2 AND LEFT(RH.DT_PROCESS, 6) < IH.YYYYMM AND LEFT(RH.DT_RCP, 6) < IH.YYYYMM THEN RH.AM_RCP ELSE 0 END) AS AM_RCP_LONG_BEFORE,
				  SUM(CASE WHEN DATEDIFF(MONTH, RH.DT_PROCESS, IH.DT_PROCESS) > 2 THEN RH.AM_RCP ELSE 0 END) AS AM_RCP_LONG,
				  SUM(CASE WHEN DATEDIFF(MONTH, RH.DT_PROCESS, IH.DT_PROCESS) <= 2 THEN RH.AM_RCP ELSE 0 END) AS AM_RCP_1,
				  SUM(CASE WHEN DATEDIFF(MONTH, RH.DT_PROCESS, IH.DT_PROCESS) > 2 AND DATEDIFF(MONTH, RH.DT_PROCESS, IH.DT_PROCESS) <= 3 THEN RH.AM_RCP ELSE 0 END) AS AM_RCP_2,
				  SUM(CASE WHEN DATEDIFF(MONTH, RH.DT_PROCESS, IH.DT_PROCESS) > 3 AND DATEDIFF(MONTH, RH.DT_PROCESS, IH.DT_PROCESS) <= 6 THEN RH.AM_RCP ELSE 0 END) AS AM_RCP_3,
				  SUM(CASE WHEN DATEDIFF(MONTH, RH.DT_PROCESS, IH.DT_PROCESS) > 6 AND DATEDIFF(MONTH, RH.DT_PROCESS, IH.DT_PROCESS) <= 12 THEN RH.AM_RCP ELSE 0 END) AS AM_RCP_6,
				  SUM(CASE WHEN DATEDIFF(MONTH, RH.DT_PROCESS, IH.DT_PROCESS) > 12 THEN RH.AM_RCP ELSE 0 END) AS AM_RCP_12
		   FROM (SELECT IH.CD_COMPANY, 
		   		 		LEFT(IH.DT_PROCESS, 6) AS YYYYMM,
						MAX(IH.DT_PROCESS) AS DT_PROCESS
		   		 FROM SA_IVH IH
		   		 GROUP BY IH.CD_COMPANY, LEFT(IH.DT_PROCESS, 6)) IH
		   LEFT JOIN (SELECT RH.CD_COMPANY,
							 RH.DT_RCP,
		   					 IH.DT_PROCESS,
		   					 SUM(RD.AM_RCP) AS AM_RCP
					  FROM SA_RCPH RH
					  LEFT JOIN (SELECT RD.CD_COMPANY, RD.NO_RCP, RD.NO_TX AS NO_IV,
  										(ISNULL(RD.AM_RCP_TX, 0) + ISNULL(RD.AM_PL, 0)) AS AM_RCP
								 FROM SA_RCPD RD 
								 UNION ALL
								 SELECT BD.CD_COMPANY, BD.NO_RCP, BD.NO_IV,
  										(ISNULL(BD.AM_RCPS, 0) + ISNULL(BD.AM_PL, 0)) AS AM_RCP
								FROM SA_BILLSD BD) RD
					  ON RD.CD_COMPANY = RH.CD_COMPANY AND RD.NO_RCP = RH.NO_RCP
					  LEFT JOIN SA_IVH IH ON IH.CD_COMPANY = RD.CD_COMPANY AND IH.NO_IV = RD.NO_IV
					  GROUP BY RH.CD_COMPANY, RH.DT_RCP, IH.DT_PROCESS) RH
		   ON RH.CD_COMPANY = IH.CD_COMPANY AND LEFT(RH.DT_RCP, 6) <= IH.YYYYMM AND LEFT(RH.DT_PROCESS, 6) <= IH.YYYYMM 
		   GROUP BY IH.CD_COMPANY, IH.YYYYMM) RH1
ON RH1.CD_COMPANY = IH.CD_COMPANY AND RH1.YYYYMM = IH.YYYYMM
WHERE IH.CD_COMPANY = @P_CD_COMPANY
ORDER BY IH.CD_COMPANY, IH.YYYYMM DESC

GO

