USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_PR_MATCHING_GRADE_SUB_JSON]    Script Date: 2017-01-05 ¿ÀÈÄ 5:48:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_PR_MATCHING_GRADE_SUB_JSON]          
(
	@P_JSON			NVARCHAR(MAX),
	@P_ID_USER		NVARCHAR(10)	
)  
AS
   
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

DELETE MG
FROM CZ_PR_MATCHING_GRADE MG
WHERE EXISTS (SELECT 1 
			  FROM OPENJSON(@P_JSON)
			  WITH
			  (
					CD_COMPANY		NVARCHAR(7),
					CD_CLEAR_GRP	NVARCHAR(4),
			  		CD_GRADE		NVARCHAR(1),
					IDX_SPEC		INT,
			  		JSON_FLAG		NVARCHAR(1)
			  ) JS
			  WHERE JS.JSON_FLAG = 'D'
			  AND JS.CD_COMPANY = MG.CD_COMPANY
			  AND JS.CD_CLEAR_GRP = MG.CD_CLEAR_GRP
			  AND JS.CD_GRADE = MG.CD_GRADE
			  AND JS.IDX_SPEC = MG.IDX_SPEC)

INSERT INTO CZ_PR_MATCHING_GRADE
(
	CD_COMPANY,
	CD_CLEAR_GRP,
	CD_GRADE,
	IDX_SPEC,
	QT_SPEC,
	ID_INSERT,
	DTS_INSERT
)
SELECT JS.CD_COMPANY,
	   JS.CD_CLEAR_GRP,
	   JS.CD_GRADE,
	   (ISNULL(MG.IDX_SPEC, 0) + ROW_NUMBER() OVER (PARTITION BY JS.CD_CLEAR_GRP, JS.CD_GRADE ORDER BY JS.CD_GRADE)) AS IDX_SPEC,
	   JS.QT_SPEC,
	   @P_ID_USER,
	   NEOE.SF_SYSDATE(GETDATE())
FROM OPENJSON(@P_JSON)
WITH
(
	CD_COMPANY		NVARCHAR(7),
	CD_CLEAR_GRP	NVARCHAR(4),
	CD_GRADE		NVARCHAR(1),
	QT_SPEC			NUMERIC(18, 4),
	JSON_FLAG		NVARCHAR(1)
) JS
LEFT JOIN (SELECT CD_COMPANY, CD_CLEAR_GRP, CD_GRADE,
				  MAX(IDX_SPEC) AS IDX_SPEC
		   FROM CZ_PR_MATCHING_GRADE
		   GROUP BY CD_COMPANY, CD_CLEAR_GRP, CD_GRADE) MG
ON MG.CD_COMPANY = JS.CD_COMPANY AND MG.CD_CLEAR_GRP = JS.CD_CLEAR_GRP AND MG.CD_GRADE = JS.CD_GRADE
WHERE JS.JSON_FLAG = 'I'

UPDATE MG
SET MG.QT_SPEC = JS.QT_SPEC,
	MG.ID_UPDATE = @P_ID_USER,
	MG.DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE())
FROM CZ_PR_MATCHING_GRADE MG
JOIN OPENJSON(@P_JSON)
     WITH (CD_COMPANY		NVARCHAR(7),
		   CD_CLEAR_GRP		NVARCHAR(4),
		   CD_GRADE		    NVARCHAR(1),
		   IDX_SPEC		    INT,
		   QT_SPEC			NUMERIC(18, 4),
		   JSON_FLAG		NVARCHAR(1)) JS
ON JS.JSON_FLAG = 'U' AND JS.CD_COMPANY = MG.CD_COMPANY AND JS.CD_CLEAR_GRP = MG.CD_CLEAR_GRP AND JS.CD_GRADE = MG.CD_GRADE AND JS.IDX_SPEC = MG.IDX_SPEC

GO