USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_PR_MATCHING_MNG_JSON1]    Script Date: 2017-01-05 오후 5:48:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_PR_MATCHING_MNG_JSON1]          
(
	@P_JSON			NVARCHAR(MAX),
	@P_ID_USER		NVARCHAR(10)	
)  
AS
   
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

DECLARE @V_ERRMSG NVARCHAR(255)   -- ERROR 메시지

BEGIN TRAN SP_CZ_PR_MATCHING_MNG_JSON1
BEGIN TRY

DELETE WI
FROM CZ_PR_WO_INSP WI
WHERE EXISTS (SELECT 1 
			  FROM OPENJSON(@P_JSON)
			  WITH
			  (
					CD_COMPANY      NVARCHAR(7),
					NO_WO			NVARCHAR(20),
					NO_LINE         NUMERIC(5, 0),
					SEQ_WO			NUMERIC(5, 0),
					JSON_FLAG		NVARCHAR(1)
			  ) JS
			  WHERE JS.JSON_FLAG = 'D'
			  AND JS.CD_COMPANY = WI.CD_COMPANY
			  AND JS.NO_WO = WI.NO_WO
			  AND JS.NO_LINE = WI.NO_LINE
			  AND JS.SEQ_WO = WI.SEQ_WO
			  AND WI.NO_INSP = 997)

SELECT * INTO #JSON_I
FROM OPENJSON(@P_JSON)
WITH
(
	CD_COMPANY      NVARCHAR(7),
	NO_WO           NVARCHAR(20),
	NO_LINE         NUMERIC(5, 0),
	SEQ_WO          NUMERIC(5, 0),
	NO_SO           NVARCHAR(20),
	DC_RMK          NVARCHAR(500),
	JSON_FLAG		NVARCHAR(1)
) JS
WHERE JS.JSON_FLAG = 'I'

INSERT INTO CZ_PR_WO_INSP
(
	CD_COMPANY,  
	NO_WO, 
	NO_LINE,     
	SEQ_WO,    
	NO_INSP,     
	NO_SO,
	DC_RMK, 
	DTS_INSERT,  
	ID_INSERT
)
SELECT CD_COMPANY,  
	   NO_WO, 
	   NO_LINE,     
	   SEQ_WO,    
	   997 AS NO_INSP,     
	   NO_SO,
	   DC_RMK, 
	   @P_ID_USER,
	   NEOE.SF_SYSDATE(GETDATE())
FROM #JSON_I

SELECT * INTO #JSON_U
FROM OPENJSON(@P_JSON)
WITH
(
	CD_COMPANY      NVARCHAR(7),
	NO_WO           NVARCHAR(20),
	NO_LINE         NUMERIC(5, 0),
	SEQ_WO          NUMERIC(5, 0),
	NO_SO           NVARCHAR(20),
	DC_RMK          NVARCHAR(500),
	JSON_FLAG		NVARCHAR(1)
) JS
WHERE JS.JSON_FLAG = 'U'

UPDATE WI
SET WI.NO_SO = JS.NO_SO,
	WI.DC_RMK = JS.DC_RMK,
	WI.ID_UPDATE = @P_ID_USER,
	WI.DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE())
FROM CZ_PR_WO_INSP WI
JOIN #JSON_U JS 
ON JS.CD_COMPANY = WI.CD_COMPANY AND JS.NO_WO = WI.NO_WO AND JS.NO_LINE = WI.NO_LINE AND JS.SEQ_WO = WI.SEQ_WO AND 997 = WI.NO_INSP

DROP TABLE #JSON_I
DROP TABLE #JSON_U

COMMIT TRAN SP_CZ_PR_MATCHING_MNG_JSON1

END TRY
BEGIN CATCH
	ROLLBACK TRAN SP_CZ_PR_MATCHING_MNG_JSON1
	SELECT @V_ERRMSG = ERROR_MESSAGE()
	GOTO ERROR
END CATCH

RETURN
ERROR: 
RAISERROR(@V_ERRMSG, 16, 1)
ROLLBACK TRAN SP_CZ_PR_MATCHING_MNG_JSON1

GO