USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_PR_MATCHING_MNG_S1]    Script Date: 2017-01-05 오후 5:48:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_PR_MATCHING_MNG_S1]          
(
	@P_CD_COMPANY		NVARCHAR(7),
	@P_CD_PLANT			NVARCHAR(7),
    @P_CD_ITEM          NVARCHAR(20),
    @P_NO_SO            NVARCHAR(20)
)  
AS
   
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT PV.NO_WO,
       PV.NO_LINE,
       PV.SEQ_WO,
       PV.NO_ID,
       MD1.CD_GRADE_IN AS CD_GRADE_IN1,
       MD1.NO_HEAT AS NO_HEAT1,
       [001] AS NO_ID_C1,
       MD1.NO_LOT AS NO_LOT1,
       MD1.QT_SPEC_IN AS QT_SPEC_IN1,
       ((ISNULL(MD1.QT_SPEC_IN, 0) - ISNULL(MD2.QT_SPEC_OUT, 0)) * 1000) AS QT_CLEARANCE1,
       MD2.CD_GRADE_OUT AS CD_GRADE_OUT2,
       MD2.NO_HEAT AS NO_HEAT2,
       [002] AS NO_ID_C2,
       MD2.NO_LOT AS NO_LOT2,
       MD2.QT_SPEC_OUT AS QT_SPEC_OUT2,
       MD2.QT_SPEC_IN AS QT_SPEC_IN2,
       MD2.CD_GRADE_IN AS CD_GRADE_IN2,
       ((ISNULL(MD2.QT_SPEC_IN, 0) - ISNULL(MD3.QT_SPEC_OUT, 0)) * 1000) AS QT_CLEARANCE2,
       MD3.CD_GRADE_OUT AS CD_GRADE_OUT3,
       MD3.NO_HEAT AS NO_HEAT3,
       [003] AS NO_ID_C3,
       MD3.NO_LOT AS NO_LOT3,
       MD3.QT_SPEC_OUT AS QT_SPEC_OUT3,
       MD3.QT_SPEC_IN AS QT_SPEC_IN3,
       MD3.CD_GRADE_IN AS CD_GRADE_IN3,
       ((ISNULL(MD3.QT_SPEC_IN, 0) - ISNULL(MD4.QT_SPEC_OUT, 0)) * 1000) AS QT_CLEARANCE3,
       MD4.CD_GRADE_OUT AS CD_GRADE_OUT4,
       MD4.NO_HEAT AS NO_HEAT4,
       [004] AS NO_ID_C4,
       MD4.NO_LOT AS NO_LOT4,
       MD4.QT_SPEC_OUT AS QT_SPEC_OUT4,
       MD4.QT_SPEC_IN AS QT_SPEC_IN4,
       MD4.CD_GRADE_IN AS CD_GRADE_IN4,
       ((ISNULL(MD4.QT_SPEC_IN, 0) - ISNULL(MD5.QT_SPEC_OUT, 0)) * 1000) AS QT_CLEARANCE4,
       MD5.CD_GRADE_OUT AS CD_GRADE_OUT5,
       MD5.NO_HEAT AS NO_HEAT5,
       [005] AS NO_ID_C5,
       MD5.NO_LOT AS NO_LOT5,
       MD5.QT_SPEC_OUT AS QT_SPEC_OUT5,
       WI.NO_SO,
       WI.DC_RMK
FROM (SELECT MD.CD_COMPANY,
             MD.CD_PLANT,
             MD.NO_WO,
             MD.NO_LINE,
             MD.SEQ_WO,
             MD.NO_ID,
             MD.TP_POS,
             MD.NO_ID_C
      FROM CZ_PR_MATCHING_DATA MD
      WHERE MD.CD_COMPANY = @P_CD_COMPANY
      AND MD.CD_PLANT = @P_CD_PLANT) MD
PIVOT(MAX(MD.NO_ID_C) FOR MD.TP_POS IN ([001], [002], [003], [004], [005])) AS PV
LEFT JOIN CZ_PR_MATCHING_DATA MD1 ON MD1.CD_COMPANY = PV.CD_COMPANY AND MD1.CD_PLANT = PV.CD_PLANT AND MD1.NO_ID = PV.NO_ID AND MD1.NO_ID_C = PV.[001]
LEFT JOIN CZ_PR_MATCHING_DATA MD2 ON MD2.CD_COMPANY = PV.CD_COMPANY AND MD2.CD_PLANT = PV.CD_PLANT AND MD2.NO_ID = PV.NO_ID AND MD2.NO_ID_C = PV.[002]
LEFT JOIN CZ_PR_MATCHING_DATA MD3 ON MD3.CD_COMPANY = PV.CD_COMPANY AND MD3.CD_PLANT = PV.CD_PLANT AND MD3.NO_ID = PV.NO_ID AND MD3.NO_ID_C = PV.[003]
LEFT JOIN CZ_PR_MATCHING_DATA MD4 ON MD4.CD_COMPANY = PV.CD_COMPANY AND MD4.CD_PLANT = PV.CD_PLANT AND MD4.NO_ID = PV.NO_ID AND MD4.NO_ID_C = PV.[004]
LEFT JOIN CZ_PR_MATCHING_DATA MD5 ON MD5.CD_COMPANY = PV.CD_COMPANY AND MD5.CD_PLANT = PV.CD_PLANT AND MD5.NO_ID = PV.NO_ID AND MD5.NO_ID_C = PV.[005]
LEFT JOIN CZ_PR_WO_INSP WI ON WI.CD_COMPANY = PV.CD_COMPANY AND WI.NO_WO = PV.NO_WO AND WI.NO_LINE = PV.NO_LINE AND WI.SEQ_WO = PV.SEQ_WO AND WI.NO_INSP = 997
WHERE 1=1
AND (ISNULL(@P_NO_SO, '') = '' OR WI.NO_SO = @P_NO_SO)
AND (ISNULL(@P_CD_ITEM, '') = '' OR EXISTS (SELECT 1 
                                            FROM CZ_PR_WO_REQ_D WD
                                            WHERE WD.CD_COMPANY = PV.CD_COMPANY
                                            AND WD.NO_ID = PV.NO_ID
                                            AND WD.CD_ITEM = @P_CD_ITEM))
ORDER BY PV.NO_ID ASC

GO