USE [NEOE]
GO
/****** Object:  StoredProcedure [NEOE].[SP_CZ_PR_MATCHING_MNG_JSON2]    Script Date: 2023-02-20 ¿ÀÈÄ 7:12:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_PR_MATCHING_MNG_JSON2]          
(
	@P_JSON			NVARCHAR(MAX),
	@P_ID_USER		NVARCHAR(10)	
)  
AS
   
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

UPDATE MD
SET MD.NO_ID_C = JS.NO_ID_C,
	MD.CD_GRADE_IN = JS.CD_GRADE_IN,
	MD.CD_GRADE_OUT = JS.CD_GRADE_OUT,
	MD.NO_DATA_IN = JS.NO_DATA_IN,
	MD.NO_DATA_OUT = JS.NO_DATA_OUT,
	MD.QT_SPEC_IN = JS.QT_SPEC_IN,
	MD.QT_SPEC_OUT = JS.QT_SPEC_OUT,
	MD.CD_CLEAR_GRP_IN = JS.CD_CLEAR_GRP_IN,
    MD.CD_CLEAR_GRP_OUT = JS.CD_CLEAR_GRP_OUT,
	MD.NO_HEAT = JS.NO_HEAT,
	MD.NO_LOT = JS.NO_LOT,
	MD.DT_MATCH = CONVERT(CHAR(8), GETDATE(), 112),
	MD.ID_UPDATE = @P_ID_USER,
	MD.DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE())
FROM CZ_PR_MATCHING_DATA MD
JOIN OPENJSON(@P_JSON)
WITH
(
	CD_COMPANY			NVARCHAR(7),
	CD_PLANT			NVARCHAR(7),
	NO_WO				NVARCHAR(20),
	NO_LINE				NUMERIC(5, 0),
	SEQ_WO				NUMERIC(5, 0),
	NO_ID				NVARCHAR(20),
	TP_POS				NVARCHAR(4),
	NO_ID_C				NVARCHAR(20),
	CD_PITEM			NVARCHAR(20),
	CD_GRADE_IN			NVARCHAR(1),
	CD_GRADE_OUT		NVARCHAR(1),
	NO_DATA_IN			NUMERIC(18, 4),
	NO_DATA_OUT			NUMERIC(18, 4),
	QT_SPEC_IN			NUMERIC(6, 4),
	QT_SPEC_OUT			NUMERIC(6, 4),
	CD_CLEAR_GRP_IN		NVARCHAR(4),
    CD_CLEAR_GRP_OUT	NVARCHAR(4),
	NO_HEAT				NVARCHAR(200),
	NO_LOT				NVARCHAR(20),
	JSON_FLAG			NVARCHAR(1)
) JS
ON JS.CD_COMPANY = MD.CD_COMPANY AND JS.CD_PLANT = MD.CD_PLANT AND JS.NO_WO = MD.NO_WO AND JS.NO_LINE = MD.NO_LINE AND JS.SEQ_WO = MD.SEQ_WO AND JS.NO_ID = MD.NO_ID AND JS.CD_PITEM = MD.CD_PITEM
WHERE JS.JSON_FLAG = 'I'

UPDATE AD
SET AD.NO_ID_C = JS.NO_ID_C,
	AD.NO_HEAT = JS.NO_HEAT,
	AD.NO_LOT = JS.NO_LOT,
	AD.DT_ASSEMBLE = CONVERT(CHAR(8), GETDATE(), 112),
	AD.ID_UPDATE = @P_ID_USER,
	AD.DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE())
FROM CZ_PR_ASSEMBLING_DATA AD
JOIN OPENJSON(@P_JSON)
WITH
(
	CD_COMPANY			NVARCHAR(7),
	CD_PLANT			NVARCHAR(7),
	NO_WO				NVARCHAR(20),
	NO_LINE				NUMERIC(5, 0),
	SEQ_WO				NUMERIC(5, 0),
	NO_ID				NVARCHAR(20),
	TP_POS				NVARCHAR(4),
	NO_ID_C				NVARCHAR(20),
	CD_PITEM			NVARCHAR(20),
	NO_HEAT				NVARCHAR(200),
	NO_LOT				NVARCHAR(20),
	NO_ID_BEFORE		NVARCHAR(20),
	JSON_FLAG			NVARCHAR(1)
) JS
ON JS.CD_COMPANY = AD.CD_COMPANY AND JS.CD_PLANT = AD.CD_PLANT AND JS.NO_ID_BEFORE = AD.NO_ID_C AND JS.CD_PITEM = AD.CD_PITEM
WHERE JS.JSON_FLAG = 'I'
