USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_PR_MATCHING_MNG_S2]    Script Date: 2017-01-05 오후 5:48:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_PR_MATCHING_MNG_S2]          
(
	@P_CD_COMPANY		NVARCHAR(7),
	@P_NO_WO			NVARCHAR(20)
)  
AS
   
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT SW.NO_WO,
       SW.NO_SO,
       SW.NO_LINE,
       SL.DT_DUEDATE,
       SW.QT_APPLY,
       ISNULL(WI.QT_INSP, 0) AS QT_INSP
FROM CZ_PR_SA_SOL_PR_WO_MAPPING SW
LEFT JOIN SA_SOL SL ON SL.CD_COMPANY = SW.CD_COMPANY AND SL.NO_SO = SW.NO_SO AND SL.SEQ_SO = SW.NO_LINE
LEFT JOIN (SELECT WI.CD_COMPANY, WI.NO_WO, WI.NO_LINE, WI.NO_SO,
                  COUNT(1) AS QT_INSP
           FROM CZ_PR_WO_INSP WI
           WHERE WI.NO_INSP = 997
           GROUP BY WI.CD_COMPANY, WI.NO_WO, WI.NO_LINE, WI.NO_SO) WI
ON WI.CD_COMPANY = SW.CD_COMPANY AND WI.NO_WO = SW.NO_WO AND WI.NO_SO = SW.NO_SO
WHERE SW.CD_COMPANY = @P_CD_COMPANY
AND SW.NO_WO = @P_NO_WO
ORDER BY SL.DT_DUEDATE ASC, SL.NO_SO ASC

GO