USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_FI_ACCT_EVIDENCE_REGL_S]    Script Date: 2016-11-23 오전 11:21:37 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO





ALTER PROCEDURE [NEOE].[SP_CZ_FI_ACCT_EVIDENCE_REGL_S] 
(
	@P_CD_COMPANY		NVARCHAR(7),
	@P_CD_ACCT			NVARCHAR(10)
) 
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT EL.NO_LINE,
	   EL.CD_ACCT,
	   EL.FG_TAX,
	   MC.NM_SYSDEF AS NM_TAX,
	   EL.TP_EVIDENCE,
	   MC1.NM_SYSDEF AS NM_EVIDENCE 
FROM CZ_FI_ACCT_EVIDENCEL EL
LEFT JOIN FI_ACCTCODE AC ON AC.CD_COMPANY = EL.CD_COMPANY AND AC.CD_ACCT = EL.CD_ACCT
LEFT JOIN MA_CODEDTL MC ON MC.CD_COMPANY = EL.CD_COMPANY AND MC.CD_FIELD = 'MA_B000046' AND MC.CD_SYSDEF = EL.FG_TAX
LEFT JOIN MA_CODEDTL MC1 ON MC1.CD_COMPANY = EL.CD_COMPANY AND MC1.CD_FIELD = 'FI_F000105' AND MC1.CD_SYSDEF = EL.TP_EVIDENCE
WHERE EL.CD_COMPANY = @P_CD_COMPANY
AND EL.CD_ACCT = @P_CD_ACCT



GO

