USE [NEOE]
GO

/****** Object:  Table [NEOE].[SA_BILLSL]    Script Date: 2016-05-03 오후 2:53:13 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [NEOE].[SA_BILLSL](
	[CD_COMPANY] [nvarchar](7) NOT NULL,
	[NO_BILLS] [nvarchar](20) NOT NULL,
	[NO_LINE] [numeric](3, 0) NOT NULL,
	[NO_DOCU] [nvarchar](20) NOT NULL,
	[NO_DOLINE] [numeric](5, 0) NOT NULL,
	[CD_PJT] [nvarchar](20) NOT NULL,
	[AM_TARGET] [numeric](17, 4) NOT NULL,
	[AM_BILLS] [numeric](17, 4) NOT NULL,
	[NO_RCP] [nvarchar](20) NULL,
	[CD_EXCH] [nvarchar](3) NULL,
	[RT_EXCH] [numeric](11, 4) NULL,
	[AM_TARGET_EX] [numeric](17, 4) NULL,
	[AM_BILLS_EX] [numeric](17, 4) NULL,
	[FG_MAP] [nchar](1) NULL,
	[NO_MGMT] [nvarchar](40) NULL,
 CONSTRAINT [PK_SA_BILLSL_1] PRIMARY KEY CLUSTERED 
(
	[CD_COMPANY] ASC,
	[NO_BILLS] ASC,
	[NO_LINE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [NEOE].[SA_BILLSL] ADD  CONSTRAINT [DF__SA_BILLSL__AM_TA__5CAD7950]  DEFAULT ((0)) FOR [AM_TARGET]
GO

ALTER TABLE [NEOE].[SA_BILLSL] ADD  CONSTRAINT [DF__SA_BILLSL__AM_BI__5DA19D89]  DEFAULT ((0)) FOR [AM_BILLS]
GO


