USE [NEOE]
GO

/****** Object:  Table [NEOE].[SA_BILLSD]    Script Date: 2018-07-18 오후 3:57:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [NEOE].[SA_BILLSD](
	[CD_COMPANY] [nvarchar](7) NOT NULL,
	[NO_BILLS] [nvarchar](20) NOT NULL,
	[NO_IV] [nvarchar](20) NOT NULL,
	[NO_DOCU_RCP] [nvarchar](20) NOT NULL,
	[NO_DOLINE_RCP] [numeric](5, 0) NOT NULL,
	[NO_DOCU_IV] [nvarchar](20) NOT NULL,
	[NO_DOLINE_IV] [numeric](5, 0) NOT NULL,
	[DT_IV] [nchar](8) NOT NULL,
	[AM_TARGET] [numeric](17, 4) NOT NULL,
	[AM_RCPS] [numeric](17, 4) NOT NULL,
	[GUBUN] [nvarchar](40) NULL,
	[CD_EXCH_IV] [nvarchar](3) NULL,
	[RT_EXCH_IV] [numeric](11, 4) NULL,
	[AM_TARGET_EX] [numeric](17, 4) NULL,
	[AM_RCPS_EX] [numeric](17, 4) NULL,
	[AM_PL] [numeric](17, 4) NULL,
	[NO_RCP] [nvarchar](20) NULL,
	[TP_SO] [nvarchar](3) NOT NULL,
 CONSTRAINT [PK_SA_BILLSD] PRIMARY KEY CLUSTERED 
(
	[CD_COMPANY] ASC,
	[NO_BILLS] ASC,
	[NO_IV] ASC,
	[NO_DOCU_RCP] ASC,
	[NO_DOLINE_RCP] ASC,
	[NO_DOCU_IV] ASC,
	[NO_DOLINE_IV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [NEOE].[SA_BILLSD] ADD  CONSTRAINT [DF__SA_BILLSD__DT_IV__69135035]  DEFAULT ('00000000') FOR [DT_IV]
GO

ALTER TABLE [NEOE].[SA_BILLSD] ADD  CONSTRAINT [DF__SA_BILLSD__AM_TA__6A07746E]  DEFAULT ((0)) FOR [AM_TARGET]
GO

ALTER TABLE [NEOE].[SA_BILLSD] ADD  CONSTRAINT [DF__SA_BILLSD__AM_RC__6AFB98A7]  DEFAULT ((0)) FOR [AM_RCPS]
GO


