USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_PU_PACK_MNG_D]    Script Date: 2016-07-05 오후 4:29:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_PU_PACK_MNG_D]
(
	@P_CD_COMPANY			NVARCHAR(7),
	@P_NO_PO				NVARCHAR(20),
	@P_NO_PACK				NUMERIC(5, 0)
)
AS

DELETE CZ_PU_PACKH
WHERE CD_COMPANY = @P_CD_COMPANY
AND NO_PO = @P_NO_PO
AND NO_PACK = @P_NO_PACK

DELETE CZ_PU_PACKL
WHERE CD_COMPANY = @P_CD_COMPANY
AND NO_PO = @P_NO_PO
AND NO_PACK = @P_NO_PACK

GO