USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_PU_PACK_MNGL_S]    Script Date: 2016-07-05 오후 3:20:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO






ALTER PROCEDURE [NEOE].[SP_CZ_PU_PACK_MNGL_S]
(
	@P_CD_COMPANY			NVARCHAR(7),
	@P_NO_PO				NVARCHAR(20),
	@P_NO_PACK				NUMERIC(5, 0)
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT PK.CD_COMPANY,
	   PK.NO_PO,
	   PK.NO_PACK,
	   PK.NO_LINE,
	   QL.NO_FILE,
	   QL.NO_DSP,
	   QL.CD_ITEM_PARTNER,
	   QL.NM_ITEM_PARTNER,
	   PK.CD_ITEM,
	   MI.NM_ITEM,
	   PK.QT_PACK
FROM CZ_PU_PACKL PK
LEFT JOIN MA_PITEM MI ON MI.CD_COMPANY = PK.CD_COMPANY AND MI.CD_ITEM = PK.CD_ITEM
LEFT JOIN PU_POL PL ON PL.CD_COMPANY = PK.CD_COMPANY AND PL.NO_PO = PK.NO_PO AND PL.NO_LINE = PK.NO_LINE
LEFT JOIN CZ_SA_QTNL QL ON QL.CD_COMPANY = PL.CD_COMPANY AND QL.NO_FILE = PL.NO_SO AND QL.NO_LINE = PL.NO_LINE
WHERE PK.CD_COMPANY = @P_CD_COMPANY
AND PK.NO_PO = @P_NO_PO
AND PK.NO_PACK = @P_NO_PACK

GO

