SELECT DISTINCT
		MC.NM_COMPANY,
		ME.NO_EMP,
		ME.NM_KOR,
		MD.NM_DEPT,
		CD.CD_FLAG2
FROM MA_EMP ME
LEFT JOIN MA_COMPANY MC ON MC.CD_COMPANY = ME.CD_COMPANY
LEFT JOIN MA_DEPT MD ON MD.CD_COMPANY = ME.CD_COMPANY AND MD.CD_DEPT = ME.CD_DEPT
LEFT JOIN MA_CODEDTL CD ON CD.CD_COMPANY = ME.CD_COMPANY AND CD.CD_FIELD = 'HR_H000002' AND CD.CD_SYSDEF = ME.CD_DUTY_RANK
WHERE  ME.DT_RETIRE = 00000000
AND ((ME.CD_COMPANY ='k100' and ME.NO_EMP LIKE 's-___')
OR (ME.CD_COMPANY ='k200' and ME.NO_EMP LIKE 'd-___'))
ORDER BY MC.NM_COMPANY, MD.NM_DEPT