USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_UNINV_MNGH_U]    Script Date: 2019-01-03 오전 10:06:11 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER PROCEDURE [NEOE].[SP_CZ_SA_UNINV_MNGH_U]
( 
	@P_CD_COMPANY			NVARCHAR(7),
	@P_NO_SO				NVARCHAR(20),
	@P_TP_SO				NVARCHAR(4),
	@P_ID_UPDATE			NVARCHAR(15)
)
AS

UPDATE SA_SOH
SET TP_SO = @P_TP_SO,
    ID_UPDATE = @P_ID_UPDATE,
	DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE())
WHERE CD_COMPANY = @P_CD_COMPANY
AND NO_SO = @P_NO_SO

GO

