USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_PTR_PLAN_S]    Script Date: 2015-10-29 오전 10:00:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




ALTER PROCEDURE [NEOE].[SP_CZ_SA_PTR_PLAN_S]  
(
    @P_CD_COMPANY			NVARCHAR(7),
	@P_LANGUAGE				NVARCHAR(5) = 'KR',
	@P_DT_YEAR				NVARCHAR(4),
	@P_TP_PLAN				NVARCHAR(1)
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT SP.CD_COMPANY,
	   SP.YY_PLAN,
	   SP.TP_PLAN,
	   SP.CD_KEY,
	   (CASE WHEN @P_TP_PLAN = 0 THEN MC.NM_CC
			 WHEN @P_TP_PLAN = 1 THEN (SELECT (CASE @P_LANGUAGE WHEN 'KR' THEN NM_SYSDEF
									   						    WHEN 'US' THEN NM_SYSDEF_E
									   						    WHEN 'JP' THEN NM_SYSDEF_JP
									   						    WHEN 'CH' THEN NM_SYSDEF_CH END)
									   FROM MA_CODEDTL
									   WHERE CD_COMPANY = SP.CD_COMPANY
									   AND CD_FIELD = 'MA_B000065'
									   AND CD_SYSDEF = SP.CD_KEY)
			 WHEN @P_TP_PLAN = 2 THEN MS.NM_SALEGRP
			 WHEN @P_TP_PLAN = 3 THEN MP.LN_PARTNER END) AS NM_KEY,
	   SP.AM_TOTWON,
	   SP.AM_TOT_JAN,
	   SP.AM_TOT_FEB,
	   SP.AM_TOT_MAR,
	   SP.AM_TOT_APR,
	   SP.AM_TOT_MAY,
	   SP.AM_TOT_JUN,
	   SP.AM_TOT_JUL,
	   SP.AM_TOT_AUG,
	   SP.AM_TOT_SEP,
	   SP.AM_TOT_OCT,
	   SP.AM_TOT_NOV,
	   SP.AM_TOT_DEC
FROM CZ_SA_PTR_PLAN SP
LEFT JOIN MA_CC MC ON MC.CD_COMPANY = SP.CD_COMPANY AND MC.CD_CC = SP.CD_KEY
LEFT JOIN MA_SALEGRP MS ON MS.CD_COMPANY = SP.CD_COMPANY AND MS.CD_SALEGRP = SP.CD_KEY
LEFT JOIN MA_PARTNER MP ON MP.CD_COMPANY = SP.CD_COMPANY AND MP.CD_PARTNER = SP.CD_KEY
WHERE SP.CD_COMPANY = @P_CD_COMPANY
AND SP.YY_PLAN = @P_DT_YEAR
AND SP.TP_PLAN = @P_TP_PLAN

GO