USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_MA_PARTNER_REQ_ROLLBACK]    Script Date: 2016-08-25 오전 10:54:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




ALTER PROCEDURE [NEOE].[SP_CZ_MA_PARTNER_REQ_ROLLBACK]
(
	@P_CD_COMPANY 	NVARCHAR(7),
	@P_NO_REQ		NVARCHAR(20),
	@P_CD_PARTNER	NVARCHAR(20)
) 
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

DECLARE @V_ERRMSG		VARCHAR(255)   -- ERROR 메시지

IF EXISTS (SELECT 1 
		   FROM MA_PARTNER
		   WHERE CD_PARTNER = @P_CD_PARTNER)
BEGIN
	SELECT @V_ERRMSG = '등록된 거래처가 있습니다.'                      
	GOTO ERROR
END

UPDATE CZ_MA_PARTNER_REQ
SET CD_PARTNER = NULL
WHERE CD_COMPANY = @P_CD_COMPANY
AND NO_REQ = @P_NO_REQ

RETURN
ERROR: 
RAISERROR(@V_ERRMSG, 16, 1)


GO

