USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_GIR_LIV_WARNING]    Script Date: 2021-02-02 오후 2:55:57 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER PROCEDURE [NEOE].[SP_CZ_SA_GIR_LIV_WARNING]  
(
    @P_CD_COMPANY		NVARCHAR(7),
    @P_NO_GIR           NVARCHAR(20)
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

IF @P_CD_COMPANY <> 'K200'
BEGIN
	;WITH A AS
	(
		SELECT PH.CD_COMPANY,
		       PH.NO_GIR,
			   PH.NO_PACK,
			   PH.QT_CBM
		FROM (SELECT PH.CD_COMPANY,
			  	    PH.NO_GIR,
			  		PH.NO_PACK,
			  		CONVERT(NUMERIC(17, 2), ((PH.QT_WIDTH * 0.001) * (PH.QT_HEIGHT * 0.001) * (PH.QT_LENGTH * 0.001))) AS QT_CBM
			  FROM CZ_SA_PACKH PH
			  WHERE PH.NO_GIR = PH.NO_GIR_ORG
			  AND PH.NO_PACK = PH.NO_PACK_ORG
			  AND PH.CD_TYPE = '003' 
			  AND PH.YN_OUTSOURCING = 'Y') PH
		UNION ALL
		SELECT PH.CD_COMPANY,
		       PH.NO_GIR,
			   PH.NO_PACK,
			   PH.QT_CBM
		FROM (SELECT PH.CD_COMPANY,
				     PH.NO_GIR,
					 PH.NO_PACK,
					 CONVERT(NUMERIC(17, 2), ((PH1.QT_WIDTH * 0.001) * (PH1.QT_HEIGHT * 0.001) * (PH1.QT_LENGTH * 0.001))) AS QT_CBM
			  FROM CZ_SA_PACKH PH
			  JOIN CZ_SA_PACKH PH1 ON PH1.CD_COMPANY = PH.CD_COMPANY AND PH1.NO_GIR = PH.NO_GIR_ORG AND PH1.NO_PACK = PH.NO_PACK_ORG
			  WHERE (PH.NO_GIR <> PH.NO_GIR_ORG OR PH.NO_PACK <> PH.NO_PACK_ORG)
			  AND PH1.CD_TYPE = '003' 
			  AND PH1.YN_OUTSOURCING = 'Y') PH
	),
	B AS
	(
		SELECT A.CD_COMPANY,
			   A.NO_GIR,
			   A.NO_PACK,
			   (CASE WHEN A.QT_CBM >= 1 THEN A.QT_CBM * (SELECT TL.UM 
		    				 	   				         FROM CZ_MA_TARIFF_CBM_H TH
		  						   				         JOIN CZ_MA_TARIFF_CBM_L TL ON TL.CD_COMPANY = TH.CD_COMPANY AND TL.CD_PARTNER = TH.CD_PARTNER
		    				 	   				         WHERE TH.CD_COMPANY = A.CD_COMPANY
		  						   				         AND ISNULL(TH.YN_USE, 'N') = 'Y'
		    				 	   				         AND TL.SIZE = 1
		  						   				         AND CONVERT(NVARCHAR(8), GETDATE(), 112) BETWEEN TL.DT_START AND TL.DT_END) 
		    				 	        ELSE (SELECT TL.UM 
		    				 	   	          FROM CZ_MA_TARIFF_CBM_H TH
		  						   	          JOIN CZ_MA_TARIFF_CBM_L TL ON TL.CD_COMPANY = TH.CD_COMPANY AND TL.CD_PARTNER = TH.CD_PARTNER
		    				 	   	          WHERE TH.CD_COMPANY = A.CD_COMPANY
		  						   	          AND ISNULL(TH.YN_USE, 'N') = 'Y'
		    				 	   	          AND TL.SIZE = A.QT_CBM
		  						   	          AND CONVERT(NVARCHAR(8), GETDATE(), 112) BETWEEN TL.DT_START AND TL.DT_END) END) AS AM_CBM
		FROM A
	)
	SELECT GH.CD_COMPANY,
		   GH.NO_GIR,
		   SH.NO_SO,
		   SH.NO_EMP,
		   GH.NO_EMP AS NO_EMP_LOG,
		   PH.AM_CBM AS AM_PACK,
		   GL.AM_PROFIT
	FROM SA_GIRH GH
	JOIN (SELECT GL.CD_COMPANY, GL.NO_GIR,
				 SUM(ISNULL(SL.AM_SO, 0) - (ISNULL(SL.AM_PO, 0) + ISNULL(SL.AM_STOCK, 0))) AS AM_PROFIT
	      FROM SA_GIRL GL
		  JOIN (SELECT SL.CD_COMPANY, SL.NO_SO, SL.SEQ_SO,
		   			   SL.AM_WONAMT AS AM_SO,
		   			   PL.AM_PO,
		   			   (SB.UM_KR * SB.QT_STOCK) AS AM_STOCK
		        FROM SA_SOL SL
		   		LEFT JOIN CZ_SA_STOCK_BOOK SB ON SB.CD_COMPANY = SL.CD_COMPANY AND SB.NO_FILE = SL.NO_SO AND SB.NO_LINE = SL.SEQ_SO
		   		LEFT JOIN (SELECT PL.CD_COMPANY, PL.NO_SO, PL.NO_SOLINE,
		   		 			      SUM(PL.AM) AS AM_PO
		   		 	       FROM PU_POL PL
		   		 	       WHERE PL.CD_ITEM NOT LIKE 'SD%'
		   		 	       GROUP BY PL.CD_COMPANY, PL.NO_SO, PL.NO_SOLINE) PL
		   	    ON PL.CD_COMPANY = SL.CD_COMPANY AND PL.NO_SO = SL.NO_SO AND PL.NO_SOLINE = SL.SEQ_SO
		   	    WHERE SL.CD_ITEM NOT LIKE 'SD%') SL
		  ON SL.CD_COMPANY = GL.CD_COMPANY AND SL.NO_SO = GL.NO_SO AND SL.SEQ_SO = GL.SEQ_SO
		  GROUP BY GL.CD_COMPANY, GL.NO_GIR) GL
	ON GL.CD_COMPANY = GH.CD_COMPANY AND GL.NO_GIR = GH.NO_GIR
	JOIN (SELECT B.CD_COMPANY, B.NO_GIR,
			     SUM(B.AM_CBM) AS AM_CBM
		  FROM B
		  GROUP BY B.CD_COMPANY, B.NO_GIR) PH 
	ON PH.CD_COMPANY = GL.CD_COMPANY AND PH.NO_GIR = GL.NO_GIR
	JOIN (SELECT GL.CD_COMPANY, GL.NO_GIR, GL.NO_SO 
		  FROM SA_GIRL GL
		  GROUP BY GL.CD_COMPANY, GL.NO_GIR, GL.NO_SO) GL1
	ON GL1.CD_COMPANY = GL.CD_COMPANY AND GL1.NO_GIR = GL.NO_GIR
	JOIN SA_SOH SH ON SH.CD_COMPANY = GL1.CD_COMPANY AND SH.NO_SO = GL1.NO_SO
	JOIN MA_CODEDTL MC ON MC.CD_COMPANY = SH.CD_COMPANY AND MC.CD_FIELD = 'TR_IM00011' AND MC.CD_SYSDEF = SH.TP_PACKING
	WHERE GH.CD_COMPANY = @P_CD_COMPANY
	AND GH.NO_GIR = @P_NO_GIR
	AND ISNULL(PH.AM_CBM, 0) > ISNULL(GL.AM_PROFIT, 0)
	AND ISNULL(MC.CD_FLAG1, 'N') = 'N'
	UNION ALL
	SELECT GH.CD_COMPANY,
		   GH.NO_GIR,
		   SH.NO_SO,
		   SH.NO_EMP,
		   GH.NO_EMP AS NO_EMP_LOG,
		   PH.AM_CBM AS AM_PACK,
		   GL.AM_PROFIT
	FROM CZ_SA_GIRH_PACK GH
	JOIN (SELECT GL.CD_COMPANY, GL.NO_GIR,
				 SUM(ISNULL(SL.AM_SO, 0) - (ISNULL(SL.AM_PO, 0) + ISNULL(SL.AM_STOCK, 0))) AS AM_PROFIT
	      FROM CZ_SA_GIRL_PACK GL
		  JOIN (SELECT SL.CD_COMPANY, SL.NO_SO, SL.SEQ_SO,
		   			   SL.AM_WONAMT AS AM_SO,
		   			   PL.AM_PO,
		   			   (SB.UM_KR * SB.QT_STOCK) AS AM_STOCK
		        FROM SA_SOL SL
		   		LEFT JOIN CZ_SA_STOCK_BOOK SB ON SB.CD_COMPANY = SL.CD_COMPANY AND SB.NO_FILE = SL.NO_SO AND SB.NO_LINE = SL.SEQ_SO
		   		LEFT JOIN (SELECT PL.CD_COMPANY, PL.NO_SO, PL.NO_SOLINE,
		   		 			      SUM(PL.AM) AS AM_PO
		   		 	       FROM PU_POL PL
		   		 	       WHERE PL.CD_ITEM NOT LIKE 'SD%'
		   		 	       GROUP BY PL.CD_COMPANY, PL.NO_SO, PL.NO_SOLINE) PL
		   	    ON PL.CD_COMPANY = SL.CD_COMPANY AND PL.NO_SO = SL.NO_SO AND PL.NO_SOLINE = SL.SEQ_SO
		   	    WHERE SL.CD_ITEM NOT LIKE 'SD%') SL
		  ON SL.CD_COMPANY = GL.CD_COMPANY AND SL.NO_SO = GL.NO_SO AND SL.SEQ_SO = GL.SEQ_SO
		  GROUP BY GL.CD_COMPANY, GL.NO_GIR) GL
	ON GL.CD_COMPANY = GH.CD_COMPANY AND GL.NO_GIR = GH.NO_GIR
	JOIN (SELECT B.CD_COMPANY, B.NO_GIR,
			     SUM(B.AM_CBM) AS AM_CBM
		  FROM B
		  GROUP BY B.CD_COMPANY, B.NO_GIR) PH 
	ON PH.CD_COMPANY = GL.CD_COMPANY AND PH.NO_GIR = GL.NO_GIR
	JOIN (SELECT GL.CD_COMPANY, GL.NO_GIR, GL.NO_SO 
		  FROM CZ_SA_GIRL_PACK GL
		  GROUP BY GL.CD_COMPANY, GL.NO_GIR, GL.NO_SO) GL1
	ON GL1.CD_COMPANY = GL.CD_COMPANY AND GL1.NO_GIR = GL.NO_GIR
	JOIN SA_SOH SH ON SH.CD_COMPANY = GL1.CD_COMPANY AND SH.NO_SO = GL1.NO_SO
	JOIN MA_CODEDTL MC ON MC.CD_COMPANY = SH.CD_COMPANY AND MC.CD_FIELD = 'TR_IM00011' AND MC.CD_SYSDEF = SH.TP_PACKING
	WHERE GH.CD_COMPANY = @P_CD_COMPANY
	AND GH.NO_GIR = @P_NO_GIR
	AND ISNULL(PH.AM_CBM, 0) > ISNULL(GL.AM_PROFIT, 0)
	AND ISNULL(MC.CD_FLAG1, 'N') = 'N'
END

GO