USE [cus_dat]
GO

/****** Object:  StoredProcedure [dbo].[SP_CZ_MA_FILEINFO_I]    Script Date: 2015-10-23 오후 6:23:16 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER PROCEDURE [dbo].[SP_CZ_MA_FILEINFO_I] 
(
	@P_ORD_NO		VARCHAR(20),
	@P_TP_FILE		NVARCHAR(3),
	@P_FILE_NAME	NVARCHAR(100)
) 
AS 

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

INSERT INTO CZ_MA_FILEINFO
(
	SEQ,
	ODR_NO,
	TP_FILE,
	DT_INPUT,
	FILE_NAME,
	DTS_INSERT
)
VALUES
(
	(SELECT ISNULL(MAX(SEQ), 0) + 1 
	 FROM CZ_MA_FILEINFO),
	@P_ORD_NO,
	@P_TP_FILE,
	CONVERT(CHAR(8), GETDATE(), 112),
	@P_FILE_NAME,
	REPLACE(REPLACE(REPLACE(CONVERT(CHAR, GETDATE(), 20), '-', ''), ' ', ''), ':', '')
)

GO