SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [NEOE].[CZ_PU_IMPORT_DECLARATION_LOG](
	[SEQ] [int] IDENTITY(1,1) NOT NULL,
	[CD_COMPANY] [nvarchar](7) NOT NULL,
	[NO_IMPORT] [nvarchar](30) NOT NULL,
	[DC_LOG] [nvarchar](500) NULL,
	[DTS_LOG] [datetime] NULL,
 CONSTRAINT [PK_CZ_PU_IMPORT_DECLARATIOIN_LOG] PRIMARY KEY CLUSTERED 
(
	[SEQ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [NEOE].[CZ_PU_IMPORT_DECLARATION_LOG] ADD  CONSTRAINT [DF_CZ_PU_IMPORT_DECLARATIOIN_LOG_DTS_LOG]  DEFAULT (getdate()) FOR [DTS_LOG]
GO
