USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_MA_WORKFLOWL_S]    Script Date: 2015-07-09 오후 3:45:07 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_MA_WORKFLOWL_S]  
(
    @P_CD_COMPANY			NVARCHAR(7),
	@P_STEP					NVARCHAR(2),
	@P_NO_KEY			    NVARCHAR(20)
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

/* 고객문의등록, 매입문의등록 */
IF @P_STEP = '01' OR @P_STEP = '02'
BEGIN
	SELECT WL.NO_KEY,
		   WL.NM_FILE,
		   WL.NM_FILE_REAL,
		   WL.YN_PARSING,
		   WL.ID_INSERT,
		   MU.NM_USER AS NM_INSERT,
		   WL.DTS_INSERT
	FROM CZ_MA_WORKFLOWL WL
	LEFT JOIN MA_USER MU ON MU.CD_COMPANY = WL.CD_COMPANY AND MU.ID_USER = WL.ID_INSERT
	WHERE WL.CD_COMPANY = @P_CD_COMPANY
	AND WL.TP_STEP = '01'
	AND WL.NO_KEY = @P_NO_KEY
	AND WL.YN_DONE = 'N'
	AND ISNULL(WL.NM_FILE_REAL, '') <> ''
	AND (WL.YN_INCLUDED IS NULL OR WL.YN_INCLUDED = 'N')
	ORDER BY WL.NO_KEY, WL.NO_LINE
END

/* 문의서검토 */
ELSE IF @P_STEP = '03'
BEGIN
	SELECT WL.NO_KEY,
		   WL.NM_FILE,
		   WL.NM_FILE_REAL,
		   WL.ID_INSERT,
		   MU.NM_USER AS NM_INSERT,
		   WL.DTS_INSERT,
		   WH.DC_RMK
	FROM CZ_MA_WORKFLOWL WL
	LEFT JOIN CZ_MA_WORKFLOWH WH ON WH.CD_COMPANY = WL.CD_COMPANY AND WH.TP_STEP = WL.TP_STEP AND WH.NO_KEY = WL.NO_KEY
	LEFT JOIN MA_USER MU ON MU.CD_COMPANY = WL.CD_COMPANY AND MU.ID_USER = WL.ID_INSERT
	WHERE WL.CD_COMPANY = @P_CD_COMPANY
	AND WL.TP_STEP = '01'
	AND WL.NO_KEY = @P_NO_KEY
	AND ISNULL(WL.NM_FILE_REAL, '') <> ''
	AND (WL.YN_INCLUDED IS NULL OR WL.YN_INCLUDED = 'N')
	ORDER BY WL.NO_KEY, WL.NO_LINE
	
	SELECT QH.NO_FILE AS NO_KEY,
		   QH.CD_PARTNER AS CD_SUPPLIER,
		   MP.LN_PARTNER AS NM_SUPPLIER,
		   WH.NM_FILE,
		   WH.NM_FILE_REAL,
		   WH.ID_INSERT,
		   WH.NM_INSERT,
		   WH.DTS_INSERT,
		   QH.DT_SEND,
		   WH.DC_RMK 
	FROM CZ_PU_QTNH QH
	LEFT JOIN MA_PARTNER MP ON MP.CD_COMPANY = QH.CD_COMPANY AND MP.CD_PARTNER = QH.CD_PARTNER
	LEFT JOIN (SELECT WH.CD_COMPANY, WH.NO_KEY, WL.CD_SUPPLIER,
					  WL.NM_FILE,
					  WL.NM_FILE_REAL,
					  WL.ID_INSERT,
					  MU.NM_USER AS NM_INSERT,
					  WL.DTS_INSERT,
					  WH.DC_RMK  
			   FROM CZ_MA_WORKFLOWH WH
			   JOIN CZ_MA_WORKFLOWL WL ON WL.CD_COMPANY = WH.CD_COMPANY AND WL.TP_STEP = WH.TP_STEP AND WL.NO_KEY = WH.NO_KEY
			   LEFT JOIN MA_USER MU ON MU.CD_COMPANY = WL.CD_COMPANY AND MU.ID_USER = WL.ID_INSERT
			   WHERE WH.TP_STEP = '02'
			   AND WL.YN_DONE = 'Y'
			   AND (WL.YN_INCLUDED IS NULL OR WL.YN_INCLUDED = 'N')
			   AND ISNULL(WL.NM_FILE_REAL, '') <> '') WH
	ON WH.CD_COMPANY = QH.CD_COMPANY AND WH.NO_KEY = QH.NO_FILE AND WH.CD_SUPPLIER = QH.CD_PARTNER
	WHERE QH.CD_COMPANY = @P_CD_COMPANY
	AND QH.NO_FILE = @P_NO_KEY
END

/* 매입가등록 */
ELSE IF @P_STEP = '04'
BEGIN
	SELECT PH.NO_FILE AS NO_KEY,
		   WL.YN_PARSING,
		   (CASE WHEN (PL.AM_KR IS NOT NULL AND ISNULL(WL.NM_FILE, '') <> '') THEN '001'
				 WHEN PL.AM_KR IS NOT NULL THEN '002' 
				 ELSE '003' END) AS TP_STATE,
		   PH.CD_PARTNER AS CD_SUPPLIER,
		   MP.LN_PARTNER AS NM_SUPPLIER,
		   WL.NO_LINE,
		   WL.NM_FILE,
		   WL.NM_FILE_REAL,
		   WL.YN_DB_FILE,
		   WL.ID_INSERT,
		   MU.NM_USER AS NM_INSERT,
		   WL.DTS_INSERT,
		   WH.DC_RMK	 
	FROM CZ_PU_QTNH PH
	LEFT JOIN (SELECT CD_COMPANY, NO_FILE, CD_PARTNER,
					  SUM(AM_KR) AS AM_KR 
			   FROM CZ_PU_QTNL
			   GROUP BY CD_COMPANY, NO_FILE, CD_PARTNER) PL 
	ON PL.CD_COMPANY = PH.CD_COMPANY AND PL.NO_FILE = PH.NO_FILE AND PL.CD_PARTNER = PH.CD_PARTNER
	LEFT JOIN MA_PARTNER MP ON MP.CD_COMPANY = PH.CD_COMPANY AND MP.CD_PARTNER = PH.CD_PARTNER
	LEFT JOIN CZ_MA_WORKFLOWH WH ON WH.CD_COMPANY = PH.CD_COMPANY AND WH.NO_KEY = PH.NO_FILE AND WH.TP_STEP = '04'
	LEFT JOIN (SELECT CD_COMPANY, NO_KEY, CD_SUPPLIER,
					  NO_LINE,
					  NM_FILE,
					  NM_FILE_REAL,
					  'N' AS YN_DB_FILE,
					  YN_PARSING,
					  ID_INSERT, 
					  DTS_INSERT  
			   FROM CZ_MA_WORKFLOWL
			   WHERE ISNULL(NM_FILE_REAL, '') <> ''
			   AND TP_STEP = '04'
			   AND (YN_INCLUDED IS NULL OR YN_INCLUDED = 'N')
			   UNION ALL
			   SELECT SA.CD_COMPANY, SA.NO_FILE, SA.CD_PARTNER,
					  SA.SEQ AS NO_LINE,
					  SA.FILE_NAME,
					  NULL AS NM_FILE_REAL,
					  'Y' AS YN_DB_FILE,
					  'N' AS YN_PARSING,
					  NULL AS ID_INSERT,
					  NULL AS DTS_INSERT 
			   FROM CZ_SRM_QTNH_ATTACHMENT SA
			   LEFT JOIN CZ_SRM_QTNH SQ ON SQ.CD_COMPANY = SA.CD_COMPANY AND SQ.CD_PARTNER = SA.CD_PARTNER AND SQ.NO_FILE = SA.NO_FILE
			   WHERE SQ.CD_STATUS IN ('S', 'C')) WL 
	ON WL.CD_COMPANY = WH.CD_COMPANY AND WL.NO_KEY = WH.NO_KEY AND WL.CD_SUPPLIER = PH.CD_PARTNER
	LEFT JOIN MA_USER MU ON MU.CD_COMPANY = WL.CD_COMPANY AND MU.ID_USER = WL.ID_INSERT
	WHERE PH.CD_COMPANY = @P_CD_COMPANY
	AND PH.NO_FILE = @P_NO_KEY
	ORDER BY PH.NO_FILE, MP.LN_PARTNER

	SELECT WL.NO_KEY,
		   WL.NM_FILE,
		   WL.NM_FILE_REAL,
		   WL.ID_INSERT,
		   MU.NM_USER AS NM_INSERT,
		   WL.DTS_INSERT,
		   WH.DC_RMK
	FROM CZ_MA_WORKFLOWL WL
	LEFT JOIN CZ_MA_WORKFLOWH WH ON WH.CD_COMPANY = WL.CD_COMPANY AND WH.TP_STEP = WL.TP_STEP AND WH.NO_KEY = WL.NO_KEY
	LEFT JOIN CZ_SA_QTNH QH ON QH.CD_COMPANY = WL.CD_COMPANY AND QH.NO_FILE = WL.NO_KEY
	LEFT JOIN MA_USER MU ON MU.CD_COMPANY = WL.CD_COMPANY AND MU.ID_USER = WL.ID_INSERT
	WHERE WL.CD_COMPANY = @P_CD_COMPANY
	AND WL.TP_STEP = '05'
	AND WL.NO_KEY = @P_NO_KEY
	AND ISNULL(WL.NM_FILE_REAL, '') <> ''
	AND WL.NO_HST = QH.NO_HST
	ORDER BY WL.NO_KEY, WL.NO_LINE
END

/* 견적작성 */
ELSE IF @P_STEP = '05'
BEGIN
	SELECT PH.NO_FILE AS NO_KEY, 
		   PH.CD_PARTNER AS CD_SUPPLIER,
		   MP.LN_PARTNER AS NM_SUPPLIER,
		   PL.AM_KR,
		   (CASE WHEN (PL.AM_KR IS NOT NULL AND WL.NM_FILE_REAL IS NOT NULL) 
				 THEN '001'
				 WHEN (PL.AM_KR IS NOT NULL)
				 THEN '002' 
				 ELSE '003' END) AS TP_STATE,
		   SRM.CD_STATUS,
		   (CASE WHEN SRM.CD_STATUS = '0' THEN ''
				 WHEN SRM.CD_STATUS = 'S' THEN '가능'
				 WHEN SRM.CD_STATUS = 'C' THEN '완료' END) AS SRM_STATUS,
		   WL.NO_LINE,
		   WL.NM_FILE,
		   WL.NM_FILE_REAL,
		   WL.YN_DB_FILE,
		   WL.ID_INSERT,
		   MU.NM_USER AS NM_INSERT,
		   WL1.DT_PU_REG,
		   WL.DTS_INSERT,
		   PH.DC_RMK_QTN
	FROM CZ_PU_QTNH PH
	LEFT JOIN CZ_SRM_QTNH SRM ON SRM.CD_COMPANY = PH.CD_COMPANY AND SRM.NO_FILE = PH.NO_FILE AND SRM.CD_PARTNER = PH.CD_PARTNER
	LEFT JOIN (SELECT CD_COMPANY,
					  NO_FILE,
					  CD_PARTNER,
					  SUM(AM_KR) AS AM_KR 
			   FROM CZ_PU_QTNL
			   GROUP BY CD_COMPANY, NO_FILE, CD_PARTNER) PL 
	ON PL.CD_COMPANY = PH.CD_COMPANY AND PL.NO_FILE = PH.NO_FILE AND PL.CD_PARTNER = PH.CD_PARTNER
	LEFT JOIN MA_PARTNER MP ON MP.CD_COMPANY = PH.CD_COMPANY AND MP.CD_PARTNER = PH.CD_PARTNER
	LEFT JOIN (SELECT WL.CD_COMPANY,
					  WL.NO_KEY,
					  WL.CD_SUPPLIER,
					  WL.NO_LINE,
					  WL.NM_FILE,
					  WL.NM_FILE_REAL,
					  'N' AS YN_DB_FILE,
					  WL.ID_INSERT,
					  WL.DTS_INSERT 
			   FROM CZ_MA_WORKFLOWL WL
			   WHERE ISNULL(WL.NM_FILE_REAL, '') <> ''
			   AND WL.TP_STEP = '04'
			   AND (WL.YN_INCLUDED IS NULL OR WL.YN_INCLUDED = 'N')
			   UNION ALL
			   SELECT SA.CD_COMPANY, 
					  SA.NO_FILE,
					  SA.CD_PARTNER,
					  SA.SEQ AS NO_LINE,
					  SA.FILE_NAME,
					  NULL AS NM_FILE_REAL,
					  'Y' AS YN_DB_FILE,
					  NULL AS ID_INSERT,
					  NULL AS DTS_INSERT 
			   FROM CZ_SRM_QTNH_ATTACHMENT SA
			   LEFT JOIN CZ_SRM_QTNH SQ ON SQ.CD_COMPANY = SA.CD_COMPANY AND SQ.CD_PARTNER = SA.CD_PARTNER AND SQ.NO_FILE = SA.NO_FILE
			   WHERE SQ.CD_STATUS IN ('S', 'C')) WL 
	ON WL.CD_COMPANY = PH.CD_COMPANY AND WL.NO_KEY = PH.NO_FILE AND WL.CD_SUPPLIER = PH.CD_PARTNER
	LEFT JOIN (SELECT CD_COMPANY, 
					  NO_KEY,
					  NO_HST,
					  CD_SUPPLIER,
					  ISNULL(SUBSTRING(MAX(DTS_DONE), 1, 8), 0) AS DT_PU_REG
			   FROM CZ_MA_WORKFLOWL
			   WHERE YN_DONE = 'Y'
			   AND TP_STEP = '04'
			   AND (YN_INCLUDED IS NULL OR YN_INCLUDED = 'N')
			   GROUP BY CD_COMPANY, NO_KEY, NO_HST, CD_SUPPLIER) WL1
	ON WL1.CD_COMPANY = PH.CD_COMPANY AND WL1.NO_KEY = PH.NO_FILE AND WL1.NO_HST = PH.NO_HST AND WL1.CD_SUPPLIER = PH.CD_PARTNER
	LEFT JOIN MA_USER MU ON MU.CD_COMPANY = WL.CD_COMPANY AND MU.ID_USER = WL.ID_INSERT
	WHERE PH.CD_COMPANY = @P_CD_COMPANY
	AND PH.NO_FILE = @P_NO_KEY
	ORDER BY PH.NO_FILE, PH.CD_PARTNER
END

/* 수주등록 */
ELSE IF @P_STEP = '08'
BEGIN
	SELECT WL.NO_KEY,
		   WL.NM_FILE,
		   WL.NM_FILE_REAL,
		   WL.ID_INSERT,
		   MU.NM_USER AS NM_INSERT,
		   WL.DTS_INSERT,
		   WH.DC_RMK
	FROM CZ_MA_WORKFLOWL WL
	LEFT JOIN CZ_MA_WORKFLOWH WH ON WH.CD_COMPANY = WL.CD_COMPANY AND WH.TP_STEP = WL.TP_STEP AND WH.NO_KEY = WL.NO_KEY
	LEFT JOIN CZ_SA_QTNH QH ON QH.CD_COMPANY = WL.CD_COMPANY AND QH.NO_FILE = WL.NO_KEY
	LEFT JOIN MA_USER MU ON MU.CD_COMPANY = WL.CD_COMPANY AND MU.ID_USER = WL.ID_INSERT
	WHERE WL.CD_COMPANY = @P_CD_COMPANY
	AND WL.TP_STEP = '05'
	AND WL.NO_KEY = @P_NO_KEY
	AND ISNULL(WL.NM_FILE_REAL, '') <> ''
	AND WL.NO_HST = QH.NO_HST
	ORDER BY WL.NO_KEY, WL.NO_LINE

	SELECT WL.NO_KEY,
		   WL.NM_FILE,
		   WL.NM_FILE_REAL,
		   WL.ID_INSERT,
		   MU.NM_USER AS NM_INSERT,
		   WL.DTS_INSERT,
		   WH.DC_RMK
	FROM CZ_MA_WORKFLOWL WL
	LEFT JOIN CZ_MA_WORKFLOWH WH ON WH.CD_COMPANY = WL.CD_COMPANY AND WH.TP_STEP = WL.TP_STEP AND WH.NO_KEY = WL.NO_KEY
	LEFT JOIN MA_USER MU ON MU.CD_COMPANY = WL.CD_COMPANY AND MU.ID_USER = WL.ID_INSERT
	WHERE WL.CD_COMPANY = @P_CD_COMPANY
	AND WL.TP_STEP = '08'
	AND WL.NO_KEY = @P_NO_KEY
	AND WL.YN_DONE = 'N'
	AND ISNULL(WL.NM_FILE_REAL, '') <> ''
	AND (WL.YN_INCLUDED IS NULL OR WL.YN_INCLUDED = 'N')
	ORDER BY WL.NO_KEY, WL.NO_LINE

	SELECT PL.NO_FILE AS NO_KEY,
		   PL.CD_PARTNER AS CD_SUPPLIER,
		   MP.LN_PARTNER AS NM_SUPPLIER,
		   ISNULL(SUM(PL.AM_KR), 0) AS AM_KR,
		   WL.NM_FILE,
		   WL.NM_FILE_REAL,
		   WL.ID_INSERT,
		   MU.NM_USER AS NM_INSERT,
		   WL.DTS_INSERT,
		   PH.DC_RMK_QTN
	FROM CZ_PU_QTNL PL
	LEFT JOIN CZ_PU_QTNH PH ON PH.CD_COMPANY = PL.CD_COMPANY AND PH.NO_FILE = PL.NO_FILE AND PH.CD_PARTNER = PL.CD_PARTNER 
	LEFT JOIN CZ_MA_WORKFLOWL WL ON WL.CD_COMPANY = PL.CD_COMPANY AND WL.NO_KEY = PL.NO_FILE AND WL.TP_STEP = '04' AND WL.CD_SUPPLIER = PL.CD_PARTNER AND ISNULL(WL.NM_FILE_REAL, '') <> ''
	LEFT JOIN MA_USER MU ON MU.CD_COMPANY = WL.CD_COMPANY AND MU.ID_USER = WL.ID_INSERT
	LEFT JOIN MA_PARTNER MP ON MP.CD_COMPANY = PL.CD_COMPANY AND MP.CD_PARTNER = PL.CD_PARTNER
	WHERE PL.CD_COMPANY = @P_CD_COMPANY
	AND PL.NO_FILE = @P_NO_KEY 
	AND PL.YN_CHOICE = 'Y'
	AND (WL.YN_INCLUDED IS NULL OR WL.YN_INCLUDED = 'N')
	GROUP BY PL.CD_COMPANY, PL.NO_FILE, PL.CD_PARTNER, MP.LN_PARTNER, WL.NM_FILE, WL.NM_FILE_REAL, WL.ID_INSERT, MU.NM_USER, WL.DTS_INSERT, PH.DC_RMK_QTN
	ORDER BY PL.NO_FILE, PL.CD_PARTNER
END 

/* 수주확인서 */
ELSE IF @P_STEP = '09'
BEGIN
	SELECT WL.NO_KEY,
		   WL.NM_FILE,
		   WL.NM_FILE_REAL,
		   WL.ID_INSERT,
		   MU.NM_USER AS NM_INSERT,
		   WL.DTS_INSERT,
		   WH.DC_RMK
	FROM CZ_MA_WORKFLOWL WL
	LEFT JOIN CZ_MA_WORKFLOWH WH ON WH.CD_COMPANY = WL.CD_COMPANY AND WH.TP_STEP = WL.TP_STEP AND WH.NO_KEY = WL.NO_KEY
	LEFT JOIN MA_USER MU ON MU.CD_COMPANY = WL.CD_COMPANY AND MU.ID_USER = WL.ID_INSERT
	WHERE WL.CD_COMPANY = @P_CD_COMPANY
	AND WL.TP_STEP = '08'
	AND WL.NO_KEY = @P_NO_KEY
	AND ISNULL(WL.NM_FILE_REAL, '') <> ''
	AND (WL.YN_INCLUDED IS NULL OR WL.YN_INCLUDED = 'N')
	ORDER BY WL.NO_KEY, WL.NO_LINE

	SELECT WL.NO_KEY,
		   WL.NM_FILE,
		   WL.NM_FILE_REAL,
		   WL.ID_INSERT,
		   MU.NM_USER AS NM_INSERT,
		   WL.DTS_INSERT,
		   WH.DC_RMK
	FROM CZ_MA_WORKFLOWL WL
	LEFT JOIN CZ_MA_WORKFLOWH WH ON WH.CD_COMPANY = WL.CD_COMPANY AND WH.TP_STEP = WL.TP_STEP AND WH.NO_KEY = WL.NO_KEY
	LEFT JOIN CZ_SA_QTNH QH ON QH.CD_COMPANY = WL.CD_COMPANY AND QH.NO_FILE = WL.NO_KEY
	LEFT JOIN MA_USER MU ON MU.CD_COMPANY = WL.CD_COMPANY AND MU.ID_USER = WL.ID_INSERT
	WHERE WL.CD_COMPANY = @P_CD_COMPANY
	AND WL.TP_STEP = '05'
	AND WL.NO_KEY = @P_NO_KEY
	AND ISNULL(WL.NM_FILE_REAL, '') <> ''
	AND WL.NO_HST = QH.NO_HST
	ORDER BY WL.NO_KEY, WL.NO_LINE
END

/* 매입구매 */
ELSE IF @P_STEP = '10'
BEGIN
	SELECT WL.NO_KEY,
		   WL.NM_FILE,
		   WL.NM_FILE_REAL,
		   WL.ID_INSERT,
		   MU.NM_USER AS NM_INSERT,
		   WL.DTS_INSERT,
		   WH.DC_RMK
	FROM CZ_MA_WORKFLOWL WL
	LEFT JOIN CZ_MA_WORKFLOWH WH ON WH.CD_COMPANY = WL.CD_COMPANY AND WH.TP_STEP = WL.TP_STEP AND WH.NO_KEY = WL.NO_KEY
	LEFT JOIN MA_USER MU ON MU.CD_COMPANY = WL.CD_COMPANY AND MU.ID_USER = WL.ID_INSERT
	WHERE WL.CD_COMPANY = @P_CD_COMPANY
	AND WL.TP_STEP = '08'
	AND WL.NO_KEY = @P_NO_KEY
	AND ISNULL(WL.NM_FILE_REAL, '') <> ''
	AND (WL.YN_INCLUDED IS NULL OR WL.YN_INCLUDED = 'N')
	ORDER BY WL.NO_KEY, WL.NO_LINE

	SELECT WL.NO_KEY,
		   WL.NM_FILE,
		   WL.NM_FILE_REAL,
		   WL.ID_INSERT,
		   MU.NM_USER AS NM_INSERT,
		   WL.DTS_INSERT,
		   WH.DC_RMK
	FROM CZ_MA_WORKFLOWL WL
	LEFT JOIN CZ_MA_WORKFLOWH WH ON WH.CD_COMPANY = WL.CD_COMPANY AND WH.TP_STEP = WL.TP_STEP AND WH.NO_KEY = WL.NO_KEY
	LEFT JOIN CZ_SA_QTNH QH ON QH.CD_COMPANY = WL.CD_COMPANY AND QH.NO_FILE = WL.NO_KEY
	LEFT JOIN MA_USER MU ON MU.CD_COMPANY = WL.CD_COMPANY AND MU.ID_USER = WL.ID_INSERT
	WHERE WL.CD_COMPANY = @P_CD_COMPANY
	AND WL.TP_STEP = '05'
	AND WL.NO_KEY = @P_NO_KEY
	AND ISNULL(WL.NM_FILE_REAL, '') <> ''
	AND WL.NO_HST = QH.NO_HST
	ORDER BY WL.NO_KEY, WL.NO_LINE

	SELECT PL.NO_FILE AS NO_KEY,
		   PL.CD_PARTNER AS CD_SUPPLIER,
		   MP.LN_PARTNER AS NM_SUPPLIER,
		   ISNULL(SUM(PL.AM_KR), 0) AS AM_KR,
		   WL.NM_FILE,
		   WL.NM_FILE_REAL,
		   WL.ID_INSERT,
		   MU.NM_USER AS NM_INSERT,
		   WL.DTS_INSERT,
		   PH.DC_RMK_QTN
	FROM CZ_PU_QTNL PL
	LEFT JOIN CZ_PU_QTNH PH ON PH.CD_COMPANY = PL.CD_COMPANY AND PH.NO_FILE = PL.NO_FILE AND PH.CD_PARTNER = PL.CD_PARTNER 
	LEFT JOIN CZ_MA_WORKFLOWL WL ON WL.CD_COMPANY = PL.CD_COMPANY AND WL.NO_KEY = PL.NO_FILE AND WL.TP_STEP = '04' AND WL.CD_SUPPLIER = PL.CD_PARTNER AND ISNULL(WL.NM_FILE_REAL, '') <> ''
	LEFT JOIN MA_USER MU ON MU.CD_COMPANY = WL.CD_COMPANY AND MU.ID_USER = WL.ID_INSERT
	LEFT JOIN MA_PARTNER MP ON MP.CD_COMPANY = PL.CD_COMPANY AND MP.CD_PARTNER = PL.CD_PARTNER
	WHERE PL.CD_COMPANY = @P_CD_COMPANY
	AND PL.NO_FILE = @P_NO_KEY 
	AND PL.YN_CHOICE = 'Y'
	AND (WL.YN_INCLUDED IS NULL OR WL.YN_INCLUDED = 'N')
	GROUP BY PL.CD_COMPANY, PL.NO_FILE, PL.CD_PARTNER, MP.LN_PARTNER, WL.NM_FILE, WL.NM_FILE_REAL, WL.ID_INSERT, MU.NM_USER, WL.DTS_INSERT, PH.DC_RMK_QTN
	ORDER BY PL.NO_FILE, PL.CD_PARTNER
END

/* 납품목록 */
ELSE IF @P_STEP = '13'
BEGIN
	SELECT WL.NO_KEY,
		   WL.NM_FILE,
		   WL.NM_FILE_REAL,
		   WL.ID_INSERT,
		   MU.NM_USER AS NM_INSERT,
		   WL.DTS_INSERT,
		   WH.DC_RMK
	FROM CZ_MA_WORKFLOWL WL
	LEFT JOIN CZ_MA_WORKFLOWH WH ON WH.CD_COMPANY = WL.CD_COMPANY AND WH.TP_STEP = WL.TP_STEP AND WH.NO_KEY = WL.NO_KEY
	LEFT JOIN MA_USER MU ON MU.CD_COMPANY = WL.CD_COMPANY AND MU.ID_USER = WL.ID_INSERT
	WHERE WL.CD_COMPANY = @P_CD_COMPANY
	AND WL.TP_STEP = '08'
	AND WL.NO_KEY = @P_NO_KEY
	AND ISNULL(WL.NM_FILE_REAL, '') <> ''
	AND (WL.YN_INCLUDED IS NULL OR WL.YN_INCLUDED = 'N')
	ORDER BY WL.NO_KEY, WL.NO_LINE
END

/* 협조전작성 */
ELSE IF @P_STEP = '14'
BEGIN
	SELECT SL.NO_SO AS NO_KEY, 
		   SL.SEQ_SO,
		   QL.NO_DSP,
		   QL.CD_ITEM_PARTNER,
		   QL.NM_ITEM_PARTNER,
		   SL.CD_ITEM,
		   (CASE WHEN ISNULL(SL.QT_PO, 0) = ISNULL(SB.QT_STOCK, 0) THEN 'STOCK' ELSE MP.LN_PARTNER END) AS NM_SUPPLIER,
		   SL.DT_DUEDATE,
		   SL.DT_REQGI,
		   QI.DT_PO,
		   QI.DT_IO AS DT_IN,
		   QO.DT_IO AS DT_OUT,
		   MI.STND_ITEM,
		   MI.UNIT_SO,
		   ISNULL(SL.QT_SO, 0) AS QT_SO,
		   ISNULL(SB.QT_STOCK, 0) AS QT_STOCK,
		   ISNULL(SB.QT_BOOK, 0) AS QT_BOOK,
		   (ISNULL(SL.QT_PO, 0) + ISNULL(SB.QT_STOCK, 0)) AS QT_PO,
		   (CASE WHEN QL.TP_BOM = 'P' THEN ISNULL(QO.QT_BOM, 0) 
		   							  ELSE (ISNULL(QI.QT_IO, 0) + ISNULL(SB.QT_BOOK, 0)) END) AS QT_IN,
		   ISNULL(SL.QT_GIR, 0) AS QT_GIR,
		   ISNULL(SL.QT_GI, 0) AS QT_OUT,
		   (ISNULL(SL.QT_SO, 0) - ISNULL(SL.QT_GI, 0)) AS QT_GI_REMAIN,
		   NEOE.FN_CZ_GET_STOCK_QTY (SL.CD_COMPANY, CONVERT(CHAR(8), GETDATE(), 112), SL.CD_PLANT, SL.CD_ITEM) AS QT_INV,
		   SL.STA_SO
	FROM SA_SOL SL
	LEFT JOIN MA_PITEM MI ON MI.CD_COMPANY = SL.CD_COMPANY AND MI.CD_PLANT = SL.CD_PLANT AND MI.CD_ITEM = SL.CD_ITEM
	LEFT JOIN CZ_SA_QTNL QL ON QL.CD_COMPANY = SL.CD_COMPANY AND QL.NO_FILE = SL.NO_SO AND QL.NO_LINE = SL.SEQ_SO
	LEFT JOIN CZ_SA_STOCK_BOOK SB ON SB.CD_COMPANY = SL.CD_COMPANY AND SB.NO_FILE = SL.NO_SO AND SB.NO_LINE = SL.SEQ_SO
	LEFT JOIN (SELECT PL.CD_COMPANY, PL.NO_SO, PL.NO_SOLINE,
					  MAX(PH.CD_PARTNER) AS CD_PARTNER,
					  MAX(PH.DT_PO) AS DT_PO,
					  MAX(OH.DT_IO) AS DT_IO,
		  	   		  SUM(OL.QT_IO) AS QT_IO
		  		 FROM PU_POH PH
				 LEFT JOIN PU_POL PL ON PL.CD_COMPANY = PH.CD_COMPANY AND PL.NO_PO = PH.NO_PO
		  		 LEFT JOIN MM_QTIO OL ON OL.CD_COMPANY = PL.CD_COMPANY AND OL.NO_PSO_MGMT = PL.NO_PO AND OL.NO_PSOLINE_MGMT = PL.NO_LINE
		  		 LEFT JOIN MM_QTIOH OH ON OH.CD_COMPANY = OL.CD_COMPANY AND OH.NO_IO = OL.NO_IO
				 WHERE OH.YN_RETURN <> 'Y'
		  		 GROUP BY PL.CD_COMPANY, PL.NO_SO, PL.NO_SOLINE) QI 
	ON QI.CD_COMPANY = SL.CD_COMPANY AND QI.NO_SO = SL.NO_SO AND QI.NO_SOLINE = SL.SEQ_SO
	LEFT JOIN MA_PARTNER MP ON MP.CD_COMPANY = QI.CD_COMPANY AND MP.CD_PARTNER = QI.CD_PARTNER
	LEFT JOIN (SELECT OL.CD_COMPANY, OL.NO_PSO_MGMT, OL.NO_PSOLINE_MGMT,
					  MAX(OH.DT_IO) AS DT_IO,
		  	   		  SUM(OL.QT_IO) AS QT_BOM
		  	     FROM MM_QTIOH OH
		  	     LEFT JOIN MM_QTIO OL ON OL.CD_COMPANY = OH.CD_COMPANY AND OL.NO_IO = OH.NO_IO
			     WHERE OH.YN_RETURN <> 'Y' 
			     AND OL.FG_PS = '1'
				 AND OL.FG_IO = '002'
		  	     GROUP BY OL.CD_COMPANY, OL.NO_PSO_MGMT, OL.NO_PSOLINE_MGMT) QO 
	ON QO.CD_COMPANY = SL.CD_COMPANY AND QO.NO_PSO_MGMT = SL.NO_SO AND QO.NO_PSOLINE_MGMT = SL.SEQ_SO
	WHERE SL.CD_COMPANY = @P_CD_COMPANY
	AND SL.NO_SO = @P_NO_KEY
END

/* 견적요청 */
ELSE IF @P_STEP = '21'
BEGIN
	SELECT QL.NO_FILE AS NO_KEY,
		   QL.NO_LINE,
		   QL.NO_DSP,
		   IG.NM_ITEMGRP,
		   QL.NM_SUBJECT,
		   QL.CD_ITEM_PARTNER,
		   QL.NM_ITEM_PARTNER,
		   QL.CD_ITEM,
		   QL.UNIT_QTN,
		   QL.QT_QTN,
		   MP.LN_PARTNER AS NM_SUPPLIER,
		   QL.UM_EX_P,
		   QL.UM_KR_P,
		   QL.AM_EX_P,
		   QL.AM_KR_P,
		   QL.RT_PROFIT,
		   QL.UM_EX_Q,
		   QL.UM_KR_Q,
		   QL.AM_EX_Q,
		   QL.AM_KR_Q,
		   QL.RT_DC,
		   QL.UM_EX_S,
		   QL.UM_KR_S,
		   QL.AM_EX_S,
		   QL.AM_KR_S,
		   QL.RT_MARGIN,
		   QL.LT,
		   QL.DC_RMK
	FROM CZ_SA_QTNH QH
	JOIN CZ_SA_QTNL QL ON QL.CD_COMPANY = QH.CD_COMPANY AND QL.NO_FILE = QH.NO_FILE
	LEFT JOIN MA_ITEMGRP IG ON IG.CD_COMPANY = QL.CD_COMPANY AND IG.USE_YN = 'Y' AND IG.CD_ITEMGRP = QL.GRP_ITEM
	LEFT JOIN MA_PARTNER MP ON MP.CD_COMPANY = QL.CD_COMPANY AND MP.CD_PARTNER = QL.CD_SUPPLIER
	WHERE QH.CD_COMPANY = @P_CD_COMPANY
	AND QH.NO_FILE = @P_NO_KEY
	ORDER BY QL.NO_DSP
END

/* 인수증확인, 계산서발행 */
ELSE IF @P_STEP = '22' OR @P_STEP = '18'
BEGIN
	SELECT MF.CD_FILE,
		   MF.NO_SEQ,
		   MF.FILE_NAME AS NM_FILE,
		   MF.NO_REF,
		   MU.NM_USER AS NM_INSERT,
		   CONVERT(CHAR(19), MF.DTS_INSERT, 20) AS DTS_INSERT
	FROM MA_FILEINFO MF
	LEFT JOIN MA_USER MU ON MU.CD_COMPANY = MF.CD_COMPANY AND MU.ID_USER = MF.ID_INSERT
	WHERE MF.CD_COMPANY = @P_CD_COMPANY
	AND MF.CD_MODULE = 'SA'
	AND MF.ID_MENU = 'P_CZ_SA_GIM_REG'
	AND MF.CD_FILE = @P_NO_KEY
END

GO