USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_CUST_REL_MNG_PIC_COMMENT_S]    Script Date: 2017-06-08 오후 7:52:31 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




ALTER PROCEDURE [NEOE].[SP_CZ_SA_BUSINESS_TRIP_DETAIL_S]
(
	@P_CD_COMPANY	NVARCHAR(7),
	@P_NO_BIZ_TRIP	NVARCHAR(20)
) 
AS
 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT TS.CD_COMPANY,
	   TS.NO_BIZ_TRIP,
	   TS.NO_INDEX,
	   TS.DT_FROM,
	   TS.DT_TO,
	   TS.DC_SCHEDULE
FROM CZ_SA_BUSINESS_TRIP_SCHEDULE TS
WHERE TS.CD_COMPANY = @P_CD_COMPANY
AND TS.NO_BIZ_TRIP = @P_NO_BIZ_TRIP

SELECT TE.CD_COMPANY,
	   TE.NO_BIZ_TRIP,
	   TE.NO_INDEX,
	   TE.CD_COMPANY_EMP,
	   MC.NM_COMPANY,
	   TE.NO_EMP,
	   ME.NM_KOR,
	   MD.NM_DEPT,
	   CD.NM_SYSDEF AS NM_DUTY_RANK
FROM CZ_SA_BUSINESS_TRIP_EMP TE
LEFT JOIN MA_COMPANY MC ON MC.CD_COMPANY = TE.CD_COMPANY_EMP
LEFT JOIN MA_EMP ME ON ME.CD_COMPANY = TE.CD_COMPANY_EMP AND ME.NO_EMP = TE.NO_EMP
LEFT JOIN MA_DEPT MD ON MD.CD_COMPANY = ME.CD_COMPANY AND MD.CD_DEPT = ME.CD_DEPT
LEFT JOIN MA_CODEDTL CD ON CD.CD_COMPANY = ME.CD_COMPANY AND CD.CD_FIELD = 'HR_H000002' AND CD.CD_SYSDEF = ME.CD_DUTY_RANK
WHERE TE.CD_COMPANY = @P_CD_COMPANY
AND TE.NO_BIZ_TRIP = @P_NO_BIZ_TRIP

SELECT TX.CD_COMPANY,
	   TX.NO_BIZ_TRIP,
	   TX.NO_INDEX,
	   TX.TP_EXPENSE,
	   TX.AM_EXPENSE,
	   TX.DC_EXPENSE
FROM CZ_SA_BUSINESS_TRIP_EXPENSE TX
WHERE TX.CD_COMPANY = @P_CD_COMPANY
AND TX.NO_BIZ_TRIP = @P_NO_BIZ_TRIP

SELECT TM.CD_COMPANY,
	   TM.NO_BIZ_TRIP,
	   TM.NO_INDEX,
	   TM.NO_MEETING, 
	   MM.CD_PARTNER,
	   MP.LN_PARTNER,
	   MM.DT_MEETING,
	   MM.DC_TIME,
	   MM.DC_LOCATION,
	   MM.DC_SUBJECT,
	   MM.DC_PURPOSE,
	   MM.DC_MEETING
FROM CZ_SA_BUSINESS_TRIP_MEETING TM
LEFT JOIN CZ_SA_MEETING_MEMO MM ON MM.CD_COMPANY = TM.CD_COMPANY AND MM.NO_MEETING = TM.NO_MEETING
LEFT JOIN MA_PARTNER MP ON MP.CD_COMPANY = MM.CD_COMPANY AND MP.CD_PARTNER = MM.CD_PARTNER
WHERE TM.CD_COMPANY = @P_CD_COMPANY
AND TM.NO_BIZ_TRIP = @P_NO_BIZ_TRIP

GO