USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_HR_EMP_RPT_U]    Script Date: 2016-09-20 오후 4:45:17 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER PROCEDURE [NEOE].[SP_CZ_HR_EMP_RPT_U] 
(
	@P_CD_COMPANY		NVARCHAR(7),
	@P_NO_EMP			NVARCHAR(10),
	@P_DC_RMK			NVARCHAR(1000),
	@P_ID_UPDATE		NVARCHAR(15)
) 
AS

IF EXISTS(SELECT 1 
		  FROM CZ_MA_EMP 
		  WHERE CD_COMPANY = @P_CD_COMPANY
		  AND NO_EMP = @P_NO_EMP)
BEGIN
	UPDATE CZ_MA_EMP
	SET DC_RMK = @P_DC_RMK,
		ID_UPDATE = @P_ID_UPDATE,
		DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE())
	WHERE CD_COMPANY = @P_CD_COMPANY
	AND NO_EMP = @P_NO_EMP
END
ELSE
BEGIN
	INSERT INTO CZ_MA_EMP
	(
		CD_COMPANY,
		NO_EMP,
		DC_RMK,
		ID_INSERT,
		DTS_INSERT
	)
	VALUES
	(
		@P_CD_COMPANY,
		@P_NO_EMP,
		@P_DC_RMK,
		@P_ID_UPDATE,
		NEOE.SF_SYSDATE(GETDATE())
	)
END


GO

