USE [NEOE]
GO

/****** Object:  Table [NEOE].[CZ_SA_LOG_PLAN_REV]    Script Date: 2023-02-22 오후 1:58:51 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [NEOE].[CZ_SA_LOG_PLAN_REV](
	[CD_COMPANY] [nvarchar](7) NOT NULL,
	[NO_REV] [int] NOT NULL,
	[DT_WORK] [nvarchar](8) NULL,
	[DC_RMK] [nvarchar](100) NULL,
	[ID_INSERT] [nvarchar](14) NULL,
	[DTS_INSERT] [nvarchar](15) NULL,
	[ID_UPDATE] [nvarchar](14) NULL,
	[DTS_UPDATE] [nvarchar](15) NULL,
 CONSTRAINT [PK_CZ_SA_LOG_PLAN_REV_1] PRIMARY KEY CLUSTERED 
(
	[CD_COMPANY] ASC,
	[NO_REV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


