USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_MA_HULL_RPT_S]    Script Date: 2017-08-08 오전 9:06:10 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER PROCEDURE [NEOE].[SP_CZ_MA_HULL_RPTH_S]
(
	@P_CD_COMPANY      NVARCHAR(7),
	@P_TP_DATE		   NVARCHAR(4),
	@P_DT_FROM		   NVARCHAR(8),
	@P_DT_TO		   NVARCHAR(8),
	@P_CD_PARTNER	   NVARCHAR(20),
	@P_NO_IMO		   NVARCHAR(10),
	@P_NO_HULL		   NVARCHAR(20),
	@P_NM_VESSEL	   NVARCHAR(50),
	@P_CD_NATION	   NVARCHAR(4),
	@P_DC_SHIPBUILDER  NVARCHAR(100),
	@P_YN_NEWSHIP	   NVARCHAR(1),
	@P_YN_DSP_QTN	   NVARCHAR(1),
	@P_NO_FILE_PREFIX  NVARCHAR(500),
	@P_CD_SUPPLIER	   NVARCHAR(20),
	@P_CD_PARTNER1	   NVARCHAR(20)
) 
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

IF @P_YN_DSP_QTN = 'Y'
BEGIN
	SELECT MH.NO_IMO,
		   MH.NO_HULL,
		   MH.NM_VESSEL,
		   MH.NM_SHIP_OWNER,
		   MH.CD_PARTNER,
		   MP.LN_PARTNER AS NM_PARTNER,
		   MP.CD_NATION,
		   MC.NM_SYSDEF AS NM_NATION,
		   MH.DC_SHIPBUILDER,
		   MH.DT_SHIP_DLV,
		   MH.TP_SHIP,
		   MC1.NM_SYSDEF AS NM_TP_SHIP,
		   MH.YN_NEWSHIP,
		   MH.QT_DEAD_WEIGHT,
		   P1.ME1 AS ME1_MODEL,
		   P2.ME1 AS ME1_MAKER,
		   P1.GE1 AS GE1_MODEL,
		   P2.GE1 AS GE1_MAKER,
		   P1.GE2 AS GE2_MODEL,
		   P2.GE2 AS GE2_MAKER,
		   P1.TC1 AS TC1_MODEL,
		   P2.TC1 AS TC1_MAKER,
		   P1.TC2 AS TC2_MODEL,
		   P2.TC2 AS TC2_MAKER,
		   P1.TC3 AS TC3_MODEL,
		   P2.TC3 AS TC3_MAKER,
		   ISNULL(QH.QT_QTN, 0) AS QT_QTN,
		   ISNULL(QH.QT_SO, 0) AS QT_SO,
		   ISNULL(QH.AM_EX_QTN_TOTAL, 0) AS AM_EX_QTN_TOTAL,
		   ISNULL(QH.AM_QTN_TOTAL, 0) AS AM_QTN_TOTAL,
		   ISNULL(QH.AM_QTN_ME, 0) AS AM_QTN_ME,
		   ISNULL(QH.AM_QTN_AE, 0) AS AM_QTN_AE,
		   ISNULL(QH.AM_QTN_EQ, 0) AS AM_QTN_EQ,
		   ISNULL(QH.AM_QTN_GS, 0) AS AM_QTN_GS,
	 	   ISNULL(QH.AM_QTN_ETC, 0) AS AM_QTN_ETC,
		   ISNULL(QH.AM_EX_SO_TOTAL, 0) AS AM_EX_SO_TOTAL,
		   ISNULL(QH.AM_SO_TOTAL, 0) AS AM_SO_TOTAL,
		   ISNULL(QH.AM_SO_ME, 0) AS AM_SO_ME,
		   ISNULL(QH.AM_SO_AE, 0) AS AM_SO_AE,
		   ISNULL(QH.AM_SO_EQ, 0) AS AM_SO_EQ,
		   ISNULL(QH.AM_SO_GS, 0) AS AM_SO_GS,
	 	   ISNULL(QH.AM_SO_ETC, 0) AS AM_SO_ETC,
		   MH.DC_RMK,
		   HR.DC_RMK AS DC_RMK_RPT
	FROM CZ_MA_HULL MH
	LEFT JOIN (SELECT QH.NO_IMO,
					  COUNT(CASE WHEN ISNULL(@P_CD_SUPPLIER, '') = '' THEN QH.NO_FILE
								 WHEN QL.CD_COMPANY IS NOT NULL THEN QH.NO_FILE
								 ELSE NULL END) AS QT_QTN,
					  COUNT(CASE WHEN ISNULL(@P_CD_SUPPLIER, '') = '' THEN SH.NO_SO
								 WHEN SL.CD_COMPANY IS NOT NULL THEN SH.NO_SO
								 ELSE NULL END) AS QT_SO,
					  SUM(QL.AM_EX_QTN_TOTAL) AS AM_EX_QTN_TOTAL,
					  SUM(QL.AM_QTN_TOTAL) AS AM_QTN_TOTAL,
			   		  SUM(QL.AM_QTN_ME) AS AM_QTN_ME,
			   		  SUM(QL.AM_QTN_AE) AS AM_QTN_AE,
			   		  SUM(QL.AM_QTN_EQ) AS AM_QTN_EQ,
			   		  SUM(QL.AM_QTN_GS) AS AM_QTN_GS,
			   		  SUM(QL.AM_QTN_ETC) AS AM_QTN_ETC,
					  SUM(SL.AM_EX_SO_TOTAL) AS AM_EX_SO_TOTAL,
					  SUM(SL.AM_SO_TOTAL) AS AM_SO_TOTAL,
			   		  SUM(SL.AM_SO_ME) AS AM_SO_ME,
			   		  SUM(SL.AM_SO_AE) AS AM_SO_AE,
			   		  SUM(SL.AM_SO_EQ) AS AM_SO_EQ,
			   		  SUM(SL.AM_SO_GS) AS AM_SO_GS,
			   		  SUM(SL.AM_SO_ETC) AS AM_SO_ETC
			   FROM CZ_SA_QTNH QH
			   LEFT JOIN SA_SOH SH ON SH.CD_COMPANY = QH.CD_COMPANY AND SH.NO_SO = QH.NO_FILE
			   LEFT JOIN (SELECT QL.CD_COMPANY, QL.NO_FILE,
							     SUM(QL.AM_EX_S) AS AM_EX_QTN_TOTAL,
			   					 SUM(QL.AM_KR_S) AS AM_QTN_TOTAL,
			   					 SUM(CASE WHEN QL.GRP_ITEM = 'ME' THEN QL.AM_KR_S ELSE 0 END) AS AM_QTN_ME,
			   					 SUM(CASE WHEN QL.GRP_ITEM IN ('AE', 'HE') THEN QL.AM_KR_S ELSE 0 END) AS AM_QTN_AE,
			   					 SUM(CASE WHEN QL.GRP_ITEM = 'EQ' THEN QL.AM_KR_S ELSE 0 END) AS AM_QTN_EQ,
			   					 SUM(CASE WHEN QL.GRP_ITEM = 'GS' THEN QL.AM_KR_S ELSE 0 END) AS AM_QTN_GS,
			   					 SUM(CASE WHEN QL.GRP_ITEM NOT IN ('ME', 'AE', 'HE', 'EQ', 'GS') THEN QL.AM_KR_S ELSE 0 END) AS AM_QTN_ETC 
			   			  FROM CZ_SA_QTNL QL
						  WHERE ISNULL(QL.CD_ITEM, '') NOT LIKE 'SD%'
						  AND (ISNULL(@P_CD_SUPPLIER, '') = '' OR QL.CD_SUPPLIER = @P_CD_SUPPLIER)
			   			  GROUP BY CD_COMPANY, NO_FILE) QL 
			   ON QL.CD_COMPANY = QH.CD_COMPANY AND QL.NO_FILE = QH.NO_FILE
			   LEFT JOIN (SELECT SL.CD_COMPANY, SL.NO_SO,
								 SUM(ISNULL(SL.AM_EX_S, SL.AM_SO)) AS AM_EX_SO_TOTAL,
			   					 SUM(ISNULL(SL.AM_KR_S, SL.AM_WONAMT)) AS AM_SO_TOTAL,
			   					 SUM(CASE WHEN MI.GRP_ITEM = 'ME' THEN ISNULL(SL.AM_KR_S, SL.AM_WONAMT) ELSE 0 END) AS AM_SO_ME,
			   					 SUM(CASE WHEN MI.GRP_ITEM IN ('AE', 'HE') THEN ISNULL(SL.AM_KR_S, SL.AM_WONAMT) ELSE 0 END) AS AM_SO_AE,
			   					 SUM(CASE WHEN MI.GRP_ITEM = 'EQ' THEN ISNULL(SL.AM_KR_S, SL.AM_WONAMT) ELSE 0 END) AS AM_SO_EQ,
			   					 SUM(CASE WHEN MI.GRP_ITEM = 'GS' THEN ISNULL(SL.AM_KR_S, SL.AM_WONAMT) ELSE 0 END) AS AM_SO_GS,
			   					 SUM(CASE WHEN MI.GRP_ITEM NOT IN ('ME', 'AE', 'HE', 'EQ', 'GS') THEN ISNULL(SL.AM_KR_S, SL.AM_WONAMT) ELSE 0 END) AS AM_SO_ETC 
			   			  FROM SA_SOL SL
			   			  LEFT JOIN MA_PITEM MI ON MI.CD_COMPANY = SL.CD_COMPANY AND MI.CD_PLANT = SL.CD_PLANT AND MI.CD_ITEM = SL.CD_ITEM
						  WHERE ISNULL(SL.CD_ITEM, '') NOT LIKE 'SD%'
						  AND (ISNULL(@P_CD_SUPPLIER, '') = '' OR EXISTS (SELECT 1 
																		  FROM PU_POH PH
																		  JOIN PU_POL PL ON PL.CD_COMPANY = PH.CD_COMPANY AND PL.NO_PO = PH.NO_PO
																		  WHERE PH.CD_COMPANY = SL.CD_COMPANY
																		  AND PH.CD_PARTNER = @P_CD_SUPPLIER
																		  AND PL.NO_SO = SL.NO_SO
																		  AND PL.NO_SOLINE = SL.SEQ_SO))
			   			  GROUP BY SL.CD_COMPANY, SL.NO_SO) SL 
			   ON SL.CD_COMPANY = SH.CD_COMPANY AND SL.NO_SO = SH.NO_SO
			   WHERE QH.CD_COMPANY = @P_CD_COMPANY
			   AND (ISNULL(@P_CD_PARTNER1, '') = '' OR QH.CD_PARTNER = @P_CD_PARTNER1)
			   AND (ISNULL(@P_NO_FILE_PREFIX, '') = '' OR LEFT(QH.NO_FILE, 2) IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_NO_FILE_PREFIX)))
			   AND (@P_TP_DATE <> '000' OR (@P_TP_DATE = '000' AND QH.DT_QTN BETWEEN @P_DT_FROM AND @P_DT_TO))
			   AND (@P_TP_DATE <> '001' OR (@P_TP_DATE = '001' AND SH.DT_SO BETWEEN @P_DT_FROM AND @P_DT_TO))
			   AND (@P_TP_DATE <> '003' OR (@P_TP_DATE = '003' AND SH.DT_CONTRACT BETWEEN @P_DT_FROM AND @P_DT_TO))
			   GROUP BY QH.NO_IMO) QH
	ON QH.NO_IMO = MH.NO_IMO
	LEFT JOIN (SELECT *
			   FROM (SELECT ME.NO_IMO,
			   				ME.CD_ENGINE + CONVERT(NVARCHAR, ROW_NUMBER() OVER (PARTITION BY ME.NO_IMO, ME.CD_ENGINE ORDER BY ME.CD_ENGINE)) AS CD_ENGINE,
			   				ME.NM_MODEL
					 FROM CZ_MA_HULL_ENGINE ME) AS ME
			   PIVOT (MAX(ME.NM_MODEL) FOR ME.CD_ENGINE IN ([ME1],[GE1],[GE2],[TC1],[TC2],[TC3])) PV) P1
	ON P1.NO_IMO = MH.NO_IMO
	LEFT JOIN (SELECT *
			   FROM (SELECT ME.NO_IMO,
			   				ME.CD_ENGINE + CONVERT(NVARCHAR, ROW_NUMBER() OVER (PARTITION BY ME.NO_IMO, ME.CD_ENGINE ORDER BY ME.CD_ENGINE)) AS CD_ENGINE,
			   				MC.NM_SYSDEF AS NM_MAKER
			   		 FROM CZ_MA_HULL_ENGINE ME
			   		 LEFT JOIN MA_CODEDTL MC ON MC.CD_COMPANY = @P_CD_COMPANY AND MC.CD_FIELD = 'CZ_MA00003' AND MC.CD_SYSDEF = ME.CD_MAKER) AS ME
			   PIVOT (MAX(ME.NM_MAKER) FOR ME.CD_ENGINE IN ([ME1],[GE1],[GE2],[TC1],[TC2],[TC3])) PV) P2
	ON P2.NO_IMO = MH.NO_IMO
	LEFT JOIN CZ_MA_HULL_RPT HR ON HR.CD_COMPANY = @P_CD_COMPANY AND HR.NO_IMO = MH.NO_IMO
	LEFT JOIN MA_PARTNER MP ON MP.CD_COMPANY = @P_CD_COMPANY AND MP.CD_PARTNER = MH.CD_PARTNER
	LEFT JOIN MA_CODEDTL MC ON MC.CD_COMPANY = @P_CD_COMPANY AND MC.CD_FIELD = 'MA_B000020' AND MC.CD_SYSDEF = MP.CD_NATION
	LEFT JOIN MA_CODEDTL MC1 ON MC1.CD_COMPANY = @P_CD_COMPANY AND MC1.CD_FIELD = 'CZ_MA00002' AND MC1.CD_SYSDEF = MH.TP_SHIP
	WHERE 1=1 
	AND (ISNULL(@P_NO_IMO, '') = '' OR MH.NO_IMO = @P_NO_IMO)
	AND (ISNULL(@P_NO_HULL, '') = '' OR MH.NO_HULL LIKE @P_NO_HULL + '%')
	AND (ISNULL(@P_NM_VESSEL, '') = '' OR MH.NM_VESSEL LIKE @P_NM_VESSEL + '%')
	AND (ISNULL(@P_CD_PARTNER, '') = '' OR MH.CD_PARTNER = @P_CD_PARTNER)
	AND (ISNULL(@P_CD_NATION, '') = '' OR MP.CD_NATION = @P_CD_NATION)
	AND (ISNULL(@P_DC_SHIPBUILDER, '') = '' OR MH.DC_SHIPBUILDER LIKE @P_DC_SHIPBUILDER + '%')
	AND (ISNULL(@P_YN_NEWSHIP, 'N') = 'N' OR MH.YN_NEWSHIP = @P_YN_NEWSHIP)
    AND (@P_TP_DATE <> '002' OR (@P_TP_DATE = '002' AND ISNULL(MH.DT_SHIP_DLV, '') BETWEEN @P_DT_FROM AND @P_DT_TO))
END
ELSE
BEGIN
	SELECT MH.NO_IMO,
		   MH.NO_HULL,
		   MH.NM_VESSEL,
		   MH.NM_SHIP_OWNER,
		   MH.CD_PARTNER,
		   MP.LN_PARTNER AS NM_PARTNER,
		   MP.CD_NATION,
		   MC.NM_SYSDEF AS NM_NATION,
		   MH.DC_SHIPBUILDER,
		   MH.DT_SHIP_DLV,
		   MH.TP_SHIP,
		   MC1.NM_SYSDEF AS NM_TP_SHIP,
		   MH.YN_NEWSHIP,
		   MH.QT_DEAD_WEIGHT,
		   P1.ME1 AS ME1_MODEL,
		   P2.ME1 AS ME1_MAKER,
		   P1.GE1 AS GE1_MODEL,
		   P2.GE1 AS GE1_MAKER,
		   P1.GE2 AS GE2_MODEL,
		   P2.GE2 AS GE2_MAKER,
		   P1.TC1 AS TC1_MODEL,
		   P2.TC1 AS TC1_MAKER,
		   P1.TC2 AS TC2_MODEL,
		   P2.TC2 AS TC2_MAKER,
		   P1.TC3 AS TC3_MODEL,
		   P2.TC3 AS TC3_MAKER,
		   0 AS QT_QTN,
		   ISNULL(SH.QT_SO, 0) AS QT_SO,
		   0 AS AM_QTN_TOTAL,
		   0 AS AM_QTN_ME,
		   0 AS AM_QTN_AE,
		   0 AS AM_QTN_EQ,
		   0 AS AM_QTN_GS,
	 	   0 AS AM_QTN_ETC,
		   ISNULL(SH.AM_EX_SO_TOTAL, 0) AS AM_EX_SO_TOTAL,
		   ISNULL(SH.AM_SO_TOTAL, 0) AS AM_SO_TOTAL,
		   ISNULL(SH.AM_SO_ME, 0) AS AM_SO_ME,
		   ISNULL(SH.AM_SO_AE, 0) AS AM_SO_AE,
		   ISNULL(SH.AM_SO_EQ, 0) AS AM_SO_EQ,
		   ISNULL(SH.AM_SO_GS, 0) AS AM_SO_GS,
	 	   ISNULL(SH.AM_SO_ETC, 0) AS AM_SO_ETC,
		   MH.DC_RMK,
		   HR.DC_RMK AS DC_RMK_RPT
	FROM CZ_MA_HULL MH
	LEFT JOIN (SELECT SH.NO_IMO,
			   		  COUNT(CASE WHEN ISNULL(@P_CD_SUPPLIER, '') = '' THEN SH.NO_SO
								 WHEN SL.CD_COMPANY IS NOT NULL THEN SH.NO_SO
								 ELSE NULL END) AS QT_SO,
					  SUM(SL.AM_EX_SO_TOTAL) AS AM_EX_SO_TOTAL,
			   		  SUM(SL.AM_SO_TOTAL) AS AM_SO_TOTAL,
			   		  SUM(SL.AM_SO_ME) AS AM_SO_ME,
			   		  SUM(SL.AM_SO_AE) AS AM_SO_AE,
			   		  SUM(SL.AM_SO_EQ) AS AM_SO_EQ,
			   		  SUM(SL.AM_SO_GS) AS AM_SO_GS,
			   		  SUM(SL.AM_SO_ETC) AS AM_SO_ETC   
			   FROM CZ_SA_QTNH QH
			   JOIN SA_SOH SH ON SH.CD_COMPANY = QH.CD_COMPANY AND SH.NO_SO = QH.NO_FILE
			   LEFT JOIN (SELECT SL.CD_COMPANY, SL.NO_SO,
							     SUM(ISNULL(SL.AM_EX_S, SL.AM_SO)) AS AM_EX_SO_TOTAL,
			   					 SUM(ISNULL(SL.AM_KR_S, SL.AM_WONAMT)) AS AM_SO_TOTAL,
			   					 SUM(CASE WHEN MI.GRP_ITEM = 'ME' THEN ISNULL(SL.AM_KR_S, SL.AM_WONAMT) ELSE 0 END) AS AM_SO_ME,
			   					 SUM(CASE WHEN MI.GRP_ITEM IN ('AE', 'HE') THEN ISNULL(SL.AM_KR_S, SL.AM_WONAMT) ELSE 0 END) AS AM_SO_AE,
			   					 SUM(CASE WHEN MI.GRP_ITEM = 'EQ' THEN ISNULL(SL.AM_KR_S, SL.AM_WONAMT) ELSE 0 END) AS AM_SO_EQ,
			   					 SUM(CASE WHEN MI.GRP_ITEM = 'GS' THEN ISNULL(SL.AM_KR_S, SL.AM_WONAMT) ELSE 0 END) AS AM_SO_GS,
			   					 SUM(CASE WHEN MI.GRP_ITEM NOT IN ('ME', 'AE', 'HE', 'EQ', 'GS') THEN ISNULL(SL.AM_KR_S, SL.AM_WONAMT) ELSE 0 END) AS AM_SO_ETC 
			   			  FROM SA_SOL SL
			   			  LEFT JOIN MA_PITEM MI ON MI.CD_COMPANY = SL.CD_COMPANY AND MI.CD_PLANT = SL.CD_PLANT AND MI.CD_ITEM = SL.CD_ITEM
						  WHERE ISNULL(SL.CD_ITEM, '') NOT LIKE 'SD%'
						  AND (ISNULL(@P_CD_SUPPLIER, '') = '' OR EXISTS (SELECT 1 
																		  FROM PU_POH PH
																		  JOIN PU_POL PL ON PL.CD_COMPANY = PH.CD_COMPANY AND PL.NO_PO = PH.NO_PO
																		  WHERE PH.CD_COMPANY = SL.CD_COMPANY
																		  AND PH.CD_PARTNER = @P_CD_SUPPLIER
																		  AND PL.NO_SO = SL.NO_SO
																		  AND PL.NO_SOLINE = SL.SEQ_SO))
			   			  GROUP BY SL.CD_COMPANY, SL.NO_SO) SL 
			   ON SL.CD_COMPANY = SH.CD_COMPANY AND SL.NO_SO = SH.NO_SO
			   WHERE QH.CD_COMPANY = @P_CD_COMPANY
			   AND (ISNULL(@P_CD_PARTNER1, '') = '' OR QH.CD_PARTNER = @P_CD_PARTNER1)
			   AND (ISNULL(@P_NO_FILE_PREFIX, '') = '' OR LEFT(SH.NO_SO, 2) IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_NO_FILE_PREFIX)))
			   AND (@P_TP_DATE <> '000' OR (@P_TP_DATE = '000' AND QH.DT_QTN BETWEEN @P_DT_FROM AND @P_DT_TO))
			   AND (@P_TP_DATE <> '001' OR (@P_TP_DATE = '001' AND SH.DT_SO BETWEEN @P_DT_FROM AND @P_DT_TO))
			   AND (@P_TP_DATE <> '003' OR (@P_TP_DATE = '003' AND SH.DT_CONTRACT BETWEEN @P_DT_FROM AND @P_DT_TO))
			   GROUP BY SH.NO_IMO) SH
	ON SH.NO_IMO = MH.NO_IMO
	LEFT JOIN (SELECT *
			   FROM (SELECT ME.NO_IMO,
			   				ME.CD_ENGINE + CONVERT(NVARCHAR, ROW_NUMBER() OVER (PARTITION BY ME.NO_IMO, ME.CD_ENGINE ORDER BY ME.CD_ENGINE)) AS CD_ENGINE,
			   				ME.NM_MODEL
					 FROM CZ_MA_HULL_ENGINE ME) AS ME
			   PIVOT (MAX(ME.NM_MODEL) FOR ME.CD_ENGINE IN ([ME1],[GE1],[GE2],[TC1],[TC2],[TC3])) PV) P1
	ON P1.NO_IMO = MH.NO_IMO
	LEFT JOIN (SELECT *
			   FROM (SELECT ME.NO_IMO,
			   				ME.CD_ENGINE + CONVERT(NVARCHAR, ROW_NUMBER() OVER (PARTITION BY ME.NO_IMO, ME.CD_ENGINE ORDER BY ME.CD_ENGINE)) AS CD_ENGINE,
			   				MC.NM_SYSDEF AS NM_MAKER
			   		 FROM CZ_MA_HULL_ENGINE ME
			   		 LEFT JOIN MA_CODEDTL MC ON MC.CD_COMPANY = @P_CD_COMPANY AND MC.CD_FIELD = 'CZ_MA00003' AND MC.CD_SYSDEF = ME.CD_MAKER) AS ME
			   PIVOT (MAX(ME.NM_MAKER) FOR ME.CD_ENGINE IN ([ME1],[GE1],[GE2],[TC1],[TC2],[TC3])) PV) P2
	ON P2.NO_IMO = MH.NO_IMO
	LEFT JOIN CZ_MA_HULL_RPT HR ON HR.CD_COMPANY = @P_CD_COMPANY AND HR.NO_IMO = MH.NO_IMO
	LEFT JOIN MA_PARTNER MP ON MP.CD_COMPANY = @P_CD_COMPANY AND MP.CD_PARTNER = MH.CD_PARTNER
	LEFT JOIN MA_CODEDTL MC ON MC.CD_COMPANY = @P_CD_COMPANY AND MC.CD_FIELD = 'MA_B000020' AND MC.CD_SYSDEF = MP.CD_NATION
	LEFT JOIN MA_CODEDTL MC1 ON MC1.CD_COMPANY = @P_CD_COMPANY AND MC1.CD_FIELD = 'CZ_MA00002' AND MC1.CD_SYSDEF = MH.TP_SHIP
	WHERE 1=1 
	AND (ISNULL(@P_NO_IMO, '') = '' OR MH.NO_IMO = @P_NO_IMO)
	AND (ISNULL(@P_NO_HULL, '') = '' OR MH.NO_HULL LIKE @P_NO_HULL + '%')
	AND (ISNULL(@P_NM_VESSEL, '') = '' OR MH.NM_VESSEL LIKE @P_NM_VESSEL + '%')
	AND (ISNULL(@P_CD_PARTNER, '') = '' OR MH.CD_PARTNER = @P_CD_PARTNER)
	AND (ISNULL(@P_CD_NATION, '') = '' OR MP.CD_NATION = @P_CD_NATION)
	AND (ISNULL(@P_DC_SHIPBUILDER, '') = '' OR MH.DC_SHIPBUILDER LIKE @P_DC_SHIPBUILDER + '%')
	AND (ISNULL(@P_YN_NEWSHIP, 'N') = 'N' OR MH.YN_NEWSHIP = @P_YN_NEWSHIP)
    AND (@P_TP_DATE <> '002' OR (@P_TP_DATE = '002' AND ISNULL(MH.DT_SHIP_DLV, '') BETWEEN @P_DT_FROM AND @P_DT_TO))
END


GO

