USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_MA_PITEM_S]    Script Date: 2016-06-27 오후 5:01:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_MA_PITEM_S]          
(  
	@P_CD_COMPANY		NVARCHAR(7),	-- 회사코드  
	@P_CD_PLANT			NVARCHAR(7),	-- 공장코드(필수)  
	@P_CLS_ITEM			NVARCHAR(1000),	-- 품목계정  
	@P_YN_USE			NVARCHAR(1),	-- 사용유무  
	@P_CLS_L			NVARCHAR(4),	-- 대분류
	@P_CLS_M			NVARCHAR(4),	-- 중분류  
	@P_CLS_S			NVARCHAR(4),	-- 소분류
	@P_MULTI_GRP_ITEM	NVARCHAR(4000), -- 품목군  
	@P_GRP_MFG			NVARCHAR(4),	-- 제품군  
	@P_CD_PARTNER		NVARCHAR(20),	-- 주거래처
	@P_TP_PART			NVARCHAR(3),	-- 내외자구분
	@P_TP_PROC			NVARCHAR(3),	-- 조달구분
	@P_CD_MNG1			NVARCHAR(3) = NULL,
	@P_CD_MNG2			NVARCHAR(3) = NULL,
	@P_CD_MNG3			NVARCHAR(3) = NULL,
	@P_CD_METHOD1		NVARCHAR(3) = NULL,
	@P_CD_METHOD2		NVARCHAR(3) = NULL,
	@P_CD_METHOD3		NVARCHAR(3) = NULL,
	@P_CD_SEARCH1		NVARCHAR(4000) = NULL,
	@P_CD_SEARCH2		NVARCHAR(4000) = NULL,
	@P_CD_SEARCH3		NVARCHAR(4000) = NULL,
	@P_YN_INTRA			NVARCHAR(1)
)  
AS  
-- ==========================================================  
-- 설    명 : 공장품목등록  
-- 수 정 자 : 김명수  
-- 수 정 일 : 2011.07.05  
-- 유    형 : 수정(컬럼 추가)  
-- 내    역 : 품목의 IMAGE 관리 탭 추가(PMIS번호 : D20110607041)  
-- ==========================================================  
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

IF EXISTS (SELECT 1 
		   FROM SYSOBJECTS 
		   WHERE NAME = 'CZ_EZCODE_PITEM')
BEGIN
	SELECT 'N' AS S,
		   MI.CD_PLANT,
		   MI.CD_ITEM,
		   MI.NM_ITEM, 
		   MI.CD_ITEM_PARTNER,
		   MI.NM_ITEM_PARTNER,
		   MI.STND_DETAIL_ITEM, 
		   MI.STND_ITEM, 
		   MI.MAT_ITEM, 
		   MI.DC_OFFER,
		   MI.NO_STND, 
		   MI.CLS_ITEM,
		   CD4.NM_SYSDEF AS NM_CLS_ITEM,
		   MI.UNIT_IM,
		   CD5.NM_SYSDEF AS NM_UNIT_IM,
		   MI.GRP_ITEM, 
		   IG.NM_ITEMGRP AS NM_GRP_ITEM, 
		   MI.GRP_MFG, 
		   CD.NM_SYSDEF AS NM_GRP_MFG,
		   (CASE WHEN NULLIF(MI.WEIGHT, 0) IS NOT NULL THEN MI.WEIGHT 
		         WHEN MK.WEIGHT_LOG IS NOT NULL THEN MK.WEIGHT_LOG
				 WHEN MK.WEIGHT_HGS IS NOT NULL THEN MK.WEIGHT_HGS
				 WHEN MU.WEIGHT_LOG IS NOT NULL THEN MU.WEIGHT_LOG
				 ELSE 0 END) AS WEIGHT, 
		   MI.FG_ABC, 
		   MI.CD_ZONE,  
		   MI.STAND_PRC, 
		   MI.CLS_L, 
		   CD1.NM_SYSDEF AS NM_CLS_L, 
		   MI.CLS_M, 
		   CD2.NM_SYSDEF AS NM_CLS_M, 
		   MI.CLS_S, 
		   CD3.NM_SYSDEF AS NM_CLS_S,
		   MI.YN_USE, 
		   MI.ID_INSERT AS INSERT_ID, 
		   ME.NM_KOR AS NM_INSERT_ID,
		   MI.DTS_INSERT,
		   MI.ID_UPDATE AS UPDATE_ID, 
		   ME1.NM_KOR AS NM_UPDATE_ID,
		   MI.DTS_UPDATE,
		   MI.DC_RMK,
		   MI.DC_RMK1,
		   MI.DC_RMK2,
		   MI.PARTNER,
		   MP.LN_PARTNER,
		   MI.CD_PARTNER1,
		   MP1.LN_PARTNER AS LN_PARTNER1,
		   MI.CD_PARTNER2,
		   MP2.LN_PARTNER AS LN_PARTNER2,
		   MI.TP_PROC,
		   MI.TP_ITEM,
		   CD6.NM_SYSDEF AS NM_TP_ITEM,
		   MI.TP_PART,
		   MI.FG_GIR,
		   MI.DT_VALID,
		   MI.QT_SSTOCK, 
		   MI.LT_SAFE, 
		   MI.YN_PHANTOM,  
		   MI.FG_LONG, 
		   MI.LT_ITEM,
		   MI.LOTSIZE,
		   MI.QT_MIN,
		   MI.CLS_PO,
		   ISNULL(MF1.IMAGE1, MF.IMAGE1) AS IMAGE1,
		   ISNULL(MF1.IMAGE2, MF.IMAGE2) AS IMAGE2,
		   ISNULL(MF1.IMAGE3, MF.IMAGE3) AS IMAGE3,
		   ISNULL(MF1.IMAGE4, MF.IMAGE4) AS IMAGE4,
		   ISNULL(MF1.IMAGE5, MF.IMAGE5) AS IMAGE5,
		   ISNULL(MF1.IMAGE6, MF.IMAGE6) AS IMAGE6,
		   ISNULL(MF1.IMAGE7, MF.IMAGE7) AS IMAGE7,
		   MF.DC_IMAGE1,
		   MF.DC_IMAGE2,
		   MF.DC_IMAGE3,
		   MF.DC_IMAGE4,
		   MF.DC_IMAGE5,
		   MF.DC_IMAGE6,
		   MF.DC_IMAGE7,
		   MI.UCODE2,
		   MI.NUM_USERDEF3,
		   MI.CD_SL,
		   MS.NM_SL,
		   MI.CD_GISL,
		   MS1.NM_SL AS NM_GISL,
		   MI.DC_KEYWORD,
		   MI.DC_KEYWORD_WE,
		   MI.DC_KEYWORD_CO,
		   MI.DC_KEYWORD_EX1,
		   MI.DC_KEYWORD_EX2,
		   MI.DC_MODEL,
		   MI.KCODE2,
		   ISNULL(MI.YN_MGMT, 'N') AS YN_MGMT,
		   MI.DC_RMK3,
		   (CASE WHEN @P_YN_INTRA = 'Y' THEN EI.EZCODE ELSE NULL END) AS EZCODE,
		   MI.LT_STDEV,
		   MI.RT_STDEV,
		   MF.YN_MAIN,
		   MI.YN_MATCH,
		   MI.DC_RMK4
	FROM MA_PITEM MI
	JOIN MA_PLANT PT ON PT.CD_COMPANY = MI.CD_COMPANY AND PT.CD_PLANT = MI.CD_PLANT
	LEFT JOIN CZ_MA_PITEM_FILE MF ON MF.CD_COMPANY = MI.CD_COMPANY AND MF.CD_PLANT = MI.CD_PLANT AND MF.CD_ITEM = MI.CD_ITEM
	LEFT JOIN CZ_MA_PITEM_FILE MF1 ON MF1.CD_COMPANY = 'K100' AND MI.CD_COMPANY = 'K200' AND MF1.CD_ITEM = MI.CD_ITEM 
	AND ((MI.CD_ITEM LIKE 'EQ%' AND MI.CLS_ITEM = '009' AND LEN(MI.CD_ITEM) = 9) OR LEFT(MI.CD_ITEM, 2) IN ('BF', 'BR', 'BX', 'SA') OR LEFT(MI.CD_ITEM, 3) IN ('SAM', 'SAR'))
	LEFT JOIN MA_ITEMGRP IG ON IG.CD_COMPANY = MI.CD_COMPANY AND IG.CD_ITEMGRP = MI.GRP_ITEM
	LEFT JOIN MA_CODEDTL CD ON CD.CD_COMPANY = MI.CD_COMPANY AND CD.CD_FIELD = 'MA_B000066' AND CD.CD_SYSDEF = MI.GRP_MFG 
	LEFT JOIN MA_CODEDTL CD1 ON CD1.CD_COMPANY = MI.CD_COMPANY AND CD1.CD_FIELD = 'MA_B000030' AND CD1.CD_SYSDEF = MI.CLS_L
	LEFT JOIN MA_CODEDTL CD2 ON CD2.CD_COMPANY = MI.CD_COMPANY AND CD2.CD_FIELD = 'MA_B000031' AND CD2.CD_SYSDEF = MI.CLS_M
	LEFT JOIN MA_CODEDTL CD3 ON CD3.CD_COMPANY = MI.CD_COMPANY AND CD3.CD_FIELD = 'MA_B000032' AND CD3.CD_SYSDEF = MI.CLS_S 
	LEFT JOIN MA_CODEDTL CD4 ON CD4.CD_COMPANY = MI.CD_COMPANY AND CD4.CD_FIELD = 'MA_B000010' AND CD4.CD_SYSDEF = MI.CLS_ITEM
	LEFT JOIN MA_CODEDTL CD5 ON CD5.CD_COMPANY = MI.CD_COMPANY AND CD5.CD_FIELD = 'MA_B000004' AND CD5.CD_SYSDEF = MI.UNIT_IM
	LEFT JOIN MA_CODEDTL CD6 ON CD6.CD_COMPANY = MI.CD_COMPANY AND CD6.CD_FIELD = 'MA_B000011' AND CD6.CD_SYSDEF = MI.TP_ITEM
	LEFT JOIN MA_EMP ME ON ME.CD_COMPANY = MI.CD_COMPANY AND ME.NO_EMP = MI.ID_INSERT
	LEFT JOIN MA_EMP ME1 ON ME1.CD_COMPANY = MI.CD_COMPANY AND ME1.NO_EMP = MI.ID_UPDATE
	LEFT JOIN MA_PARTNER MP ON MP.CD_COMPANY = MI.CD_COMPANY AND MP.CD_PARTNER = MI.PARTNER
	LEFT JOIN MA_PARTNER MP1 ON MP1.CD_COMPANY = MI.CD_COMPANY AND MP1.CD_PARTNER = MI.CD_PARTNER1
	LEFT JOIN MA_PARTNER MP2 ON MP2.CD_COMPANY = MI.CD_COMPANY AND MP2.CD_PARTNER = MI.CD_PARTNER2
	LEFT JOIN MA_SL MS ON MS.CD_COMPANY = MI.CD_COMPANY AND MS.CD_BIZAREA = MI.CD_BIZAREA AND MS.CD_PLANT = MI.CD_PLANT AND MS.CD_SL = MI.CD_SL
	LEFT JOIN MA_SL MS1 ON MS1.CD_COMPANY = MI.CD_COMPANY AND MS1.CD_BIZAREA = MI.CD_BIZAREA AND MS1.CD_PLANT = MI.CD_PLANT AND MS1.CD_SL = MI.CD_GISL
	LEFT JOIN CZ_EZCODE_PITEM EI ON EI.CD_COMPANY = MI.CD_COMPANY AND EI.CD_ITEM = MI.CD_ITEM
	LEFT JOIN CZ_MA_KCODE_HGS MK ON MK.CD_COMPANY = EI.CD_COMPANY AND MK.KCODE = EI.EZCODE AND MK.KCODE != ''
	LEFT JOIN CZ_MA_UCODE_HGS MU ON MU.CD_COMPANY = MI.CD_COMPANY AND MU.UCODE = MI.STND_DETAIL_ITEM AND MU.UCODE != ''
	WHERE MI.CD_COMPANY = @P_CD_COMPANY
	AND MI.CD_PLANT = @P_CD_PLANT   
	AND (ISNULL(@P_MULTI_GRP_ITEM, '') = '' OR MI.GRP_ITEM IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_MULTI_GRP_ITEM)))  
	AND (ISNULL(@P_YN_USE, '') = '' OR MI.YN_USE = @P_YN_USE)     
	AND (ISNULL(@P_CLS_ITEM, '') = '' OR MI.CLS_ITEM IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CLS_ITEM)))    
	AND (ISNULL(@P_GRP_MFG, '') = '' OR MI.GRP_MFG = @P_GRP_MFG)
	AND (ISNULL(@P_TP_PART, '') = '' OR MI.TP_PART = @P_TP_PART)
	AND (ISNULL(@P_TP_PROC, '') = '' OR MI.TP_PROC = @P_TP_PROC)
	AND (ISNULL(@P_CD_PARTNER, '') = '' OR MI.PARTNER = @P_CD_PARTNER)
	AND (ISNULL(@P_CLS_L, '') = '' OR MI.CLS_L = @P_CLS_L)    
	AND (ISNULL(@P_CLS_M, '') = '' OR MI.CLS_M = @P_CLS_M)    
	AND (ISNULL(@P_CLS_S, '') = '' OR MI.CLS_S = @P_CLS_S)    
	AND (ISNULL(@P_CD_SEARCH1, '') = '' OR
		 (@P_CD_MNG1 = '000' AND ((@P_CD_METHOD1= '000' AND MI.CD_ITEM = @P_CD_SEARCH1) OR
								  (@P_CD_METHOD1= '001' AND MI.CD_ITEM LIKE @P_CD_SEARCH1 + '%') OR
								  (@P_CD_METHOD1= '002' AND MI.CD_ITEM LIKE '%' + @P_CD_SEARCH1 + '%') OR
								  (@P_CD_METHOD1= '003' AND MI.CD_ITEM IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH1))))) OR
		 (@P_CD_MNG1 = '001' AND ((@P_CD_METHOD1= '000' AND MI.NM_ITEM = @P_CD_SEARCH1) OR
								  (@P_CD_METHOD1= '001' AND MI.NM_ITEM LIKE @P_CD_SEARCH1 + '%') OR
								  (@P_CD_METHOD1= '002' AND MI.NM_ITEM LIKE '%' + @P_CD_SEARCH1 + '%') OR
								  (@P_CD_METHOD1= '003' AND MI.NM_ITEM IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH1))))) OR
		 (@P_CD_MNG1 = '002' AND ((@P_CD_METHOD1= '000' AND MI.STND_ITEM = @P_CD_SEARCH1) OR
								  (@P_CD_METHOD1= '001' AND MI.STND_ITEM LIKE @P_CD_SEARCH1 + '%') OR
								  (@P_CD_METHOD1= '002' AND MI.STND_ITEM LIKE '%' + @P_CD_SEARCH1 + '%') OR
								  (@P_CD_METHOD1= '003' AND MI.STND_ITEM IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH1))))) OR
		 (@P_CD_MNG1 = '003' AND ((@P_CD_METHOD1= '000' AND MI.UCODE2 = @P_CD_SEARCH1) OR
								  (@P_CD_METHOD1= '001' AND MI.UCODE2 LIKE @P_CD_SEARCH1 + '%') OR
								  (@P_CD_METHOD1= '002' AND MI.UCODE2 LIKE '%' + @P_CD_SEARCH1 + '%') OR
								  (@P_CD_METHOD1= '003' AND MI.UCODE2 IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH1))))) OR
		 (@P_CD_MNG1 = '004' AND ((@P_CD_METHOD1= '000' AND MI.STND_DETAIL_ITEM = @P_CD_SEARCH1) OR
								  (@P_CD_METHOD1= '001' AND MI.STND_DETAIL_ITEM LIKE @P_CD_SEARCH1 + '%') OR
								  (@P_CD_METHOD1= '002' AND MI.STND_DETAIL_ITEM LIKE '%' + @P_CD_SEARCH1 + '%') OR
								  (@P_CD_METHOD1= '003' AND MI.STND_DETAIL_ITEM IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH1))))) OR
		 (@P_CD_MNG1 = '005' AND ((@P_CD_METHOD1= '000' AND MI.NM_MAKER = @P_CD_SEARCH1) OR
								  (@P_CD_METHOD1= '001' AND MI.NM_MAKER LIKE @P_CD_SEARCH1 + '%') OR
								  (@P_CD_METHOD1= '002' AND MI.NM_MAKER LIKE '%' + @P_CD_SEARCH1 + '%') OR
								  (@P_CD_METHOD1= '003' AND MI.NM_MAKER IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH1))))) OR
		 (@P_CD_MNG1 = '006' AND ((@P_CD_METHOD1= '000' AND MI.BARCODE = @P_CD_SEARCH1) OR
								  (@P_CD_METHOD1= '001' AND MI.BARCODE LIKE @P_CD_SEARCH1 + '%') OR
								  (@P_CD_METHOD1= '002' AND MI.BARCODE LIKE '%' + @P_CD_SEARCH1 + '%') OR
								  (@P_CD_METHOD1= '003' AND MI.BARCODE IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH1))))) OR
		 (@P_CD_MNG1 = '007' AND ((@P_CD_METHOD1= '000' AND MI.DC_MODEL = @P_CD_SEARCH1) OR
								  (@P_CD_METHOD1= '001' AND MI.DC_MODEL LIKE @P_CD_SEARCH1 + '%') OR
								  (@P_CD_METHOD1= '002' AND MI.DC_MODEL LIKE '%' + @P_CD_SEARCH1 + '%') OR
								  (@P_CD_METHOD1= '003' AND MI.DC_MODEL IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH1))))) OR
		 (@P_CD_MNG1 = '008' AND ((@P_CD_METHOD1= '000' AND MI.DC_KEYWORD = @P_CD_SEARCH1) OR
								  (@P_CD_METHOD1= '001' AND MI.DC_KEYWORD LIKE @P_CD_SEARCH1 + '%') OR
								  (@P_CD_METHOD1= '002' AND MI.DC_KEYWORD LIKE '%' + @P_CD_SEARCH1 + '%') OR
								  (@P_CD_METHOD1= '003' AND MI.DC_KEYWORD IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH1))))) OR
		 (@P_CD_MNG1 = '009' AND ((@P_CD_METHOD1= '000' AND MI.MAT_ITEM = @P_CD_SEARCH1) OR
								  (@P_CD_METHOD1= '001' AND MI.MAT_ITEM LIKE @P_CD_SEARCH1 + '%') OR
								  (@P_CD_METHOD1= '002' AND MI.MAT_ITEM LIKE '%' + @P_CD_SEARCH1 + '%') OR
								  (@P_CD_METHOD1= '003' AND MI.MAT_ITEM IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH1))))) OR
		 (@P_CD_MNG1 = '010' AND ((@P_CD_METHOD1= '000' AND MI.NO_STND = @P_CD_SEARCH1) OR
								  (@P_CD_METHOD1= '001' AND MI.NO_STND LIKE @P_CD_SEARCH1 + '%') OR
								  (@P_CD_METHOD1= '002' AND MI.NO_STND LIKE '%' + @P_CD_SEARCH1 + '%') OR
								  (@P_CD_METHOD1= '003' AND MI.NO_STND IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH1))))) OR
		 (@P_CD_MNG1 = '010' AND @P_YN_INTRA = 'Y' AND EXISTS(SELECT 1 
															  FROM CZ_EZCODE_PITEM 
															  WHERE CD_COMPANY = MI.CD_COMPANY 
															  AND CD_ITEM = MI.CD_ITEM 
															  AND ((@P_CD_METHOD1= '000' AND EZCODE = @P_CD_SEARCH1) OR
																   (@P_CD_METHOD1= '001' AND EZCODE LIKE @P_CD_SEARCH1 + '%') OR
																   (@P_CD_METHOD1= '002' AND EZCODE LIKE '%' + @P_CD_SEARCH1 + '%') OR
																   (@P_CD_METHOD1= '003' AND EZCODE IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH1)))))))
	AND (ISNULL(@P_CD_SEARCH2, '') = '' OR
		 (@P_CD_MNG2 = '000' AND ((@P_CD_METHOD2= '000' AND MI.CD_ITEM = @P_CD_SEARCH2) OR
								  (@P_CD_METHOD2= '001' AND MI.CD_ITEM LIKE @P_CD_SEARCH2 + '%') OR
								  (@P_CD_METHOD2= '002' AND MI.CD_ITEM LIKE '%' + @P_CD_SEARCH2 + '%') OR
								  (@P_CD_METHOD2= '003' AND MI.CD_ITEM IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH2))))) OR
		 (@P_CD_MNG2 = '001' AND ((@P_CD_METHOD2= '000' AND MI.NM_ITEM = @P_CD_SEARCH2) OR
								  (@P_CD_METHOD2= '001' AND MI.NM_ITEM LIKE @P_CD_SEARCH2 + '%') OR
								  (@P_CD_METHOD2= '002' AND MI.NM_ITEM LIKE '%' + @P_CD_SEARCH2 + '%') OR
								  (@P_CD_METHOD2= '003' AND MI.NM_ITEM IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH2))))) OR
		 (@P_CD_MNG2 = '002' AND ((@P_CD_METHOD2= '000' AND MI.STND_ITEM = @P_CD_SEARCH2) OR
								  (@P_CD_METHOD2= '001' AND MI.STND_ITEM LIKE @P_CD_SEARCH2 + '%') OR
								  (@P_CD_METHOD2= '002' AND MI.STND_ITEM LIKE '%' + @P_CD_SEARCH2 + '%') OR
								  (@P_CD_METHOD2= '003' AND MI.STND_ITEM IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH2))))) OR
		 (@P_CD_MNG2 = '003' AND ((@P_CD_METHOD2= '000' AND MI.UCODE2 = @P_CD_SEARCH2) OR
								  (@P_CD_METHOD2= '001' AND MI.UCODE2 LIKE @P_CD_SEARCH2 + '%') OR
								  (@P_CD_METHOD2= '002' AND MI.UCODE2 LIKE '%' + @P_CD_SEARCH2 + '%') OR
								  (@P_CD_METHOD2= '003' AND MI.UCODE2 IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH2))))) OR
		 (@P_CD_MNG2 = '004' AND ((@P_CD_METHOD2= '000' AND MI.STND_DETAIL_ITEM = @P_CD_SEARCH2) OR
								  (@P_CD_METHOD2= '001' AND MI.STND_DETAIL_ITEM LIKE @P_CD_SEARCH2 + '%') OR
								  (@P_CD_METHOD2= '002' AND MI.STND_DETAIL_ITEM LIKE '%' + @P_CD_SEARCH2 + '%') OR
								  (@P_CD_METHOD2= '003' AND MI.STND_DETAIL_ITEM IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH2))))) OR
		 (@P_CD_MNG2 = '005' AND ((@P_CD_METHOD2= '000' AND MI.NM_MAKER = @P_CD_SEARCH2) OR
								  (@P_CD_METHOD2= '001' AND MI.NM_MAKER LIKE @P_CD_SEARCH2 + '%') OR
								  (@P_CD_METHOD2= '002' AND MI.NM_MAKER LIKE '%' + @P_CD_SEARCH2 + '%') OR
								  (@P_CD_METHOD2= '003' AND MI.NM_MAKER IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH2))))) OR
		 (@P_CD_MNG2 = '006' AND ((@P_CD_METHOD2= '000' AND MI.BARCODE = @P_CD_SEARCH2) OR
								  (@P_CD_METHOD2= '001' AND MI.BARCODE LIKE @P_CD_SEARCH2 + '%') OR
								  (@P_CD_METHOD2= '002' AND MI.BARCODE LIKE '%' + @P_CD_SEARCH2 + '%') OR
								  (@P_CD_METHOD2= '003' AND MI.BARCODE IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH2))))) OR
		 (@P_CD_MNG2 = '007' AND ((@P_CD_METHOD2= '000' AND MI.DC_MODEL = @P_CD_SEARCH2) OR
								  (@P_CD_METHOD2= '001' AND MI.DC_MODEL LIKE @P_CD_SEARCH2 + '%') OR
								  (@P_CD_METHOD2= '002' AND MI.DC_MODEL LIKE '%' + @P_CD_SEARCH2 + '%') OR
								  (@P_CD_METHOD2= '003' AND MI.DC_MODEL IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH2))))) OR
		 (@P_CD_MNG2 = '008' AND ((@P_CD_METHOD2= '000' AND MI.DC_KEYWORD = @P_CD_SEARCH2) OR
								  (@P_CD_METHOD2= '001' AND MI.DC_KEYWORD LIKE @P_CD_SEARCH2 + '%') OR
								  (@P_CD_METHOD2= '002' AND MI.DC_KEYWORD LIKE '%' + @P_CD_SEARCH2 + '%') OR
								  (@P_CD_METHOD2= '003' AND MI.DC_KEYWORD IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH2))))) OR
		 (@P_CD_MNG2 = '009' AND ((@P_CD_METHOD2= '000' AND MI.MAT_ITEM = @P_CD_SEARCH2) OR
								  (@P_CD_METHOD2= '001' AND MI.MAT_ITEM LIKE @P_CD_SEARCH2 + '%') OR
								  (@P_CD_METHOD2= '002' AND MI.MAT_ITEM LIKE '%' + @P_CD_SEARCH2 + '%') OR
								  (@P_CD_METHOD2= '003' AND MI.MAT_ITEM IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH2))))) OR
		 (@P_CD_MNG2 = '010' AND ((@P_CD_METHOD2= '000' AND MI.NO_STND = @P_CD_SEARCH2) OR
								  (@P_CD_METHOD2= '001' AND MI.NO_STND LIKE @P_CD_SEARCH2 + '%') OR
								  (@P_CD_METHOD2= '002' AND MI.NO_STND LIKE '%' + @P_CD_SEARCH2 + '%') OR
								  (@P_CD_METHOD2= '003' AND MI.NO_STND IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH2))))) OR
		 (@P_CD_MNG1 = '010' AND @P_YN_INTRA = 'Y' AND EXISTS(SELECT 1 
															  FROM CZ_EZCODE_PITEM 
															  WHERE CD_COMPANY = MI.CD_COMPANY 
															  AND CD_ITEM = MI.CD_ITEM 
															  AND ((@P_CD_METHOD2= '000' AND EZCODE = @P_CD_SEARCH2) OR
																   (@P_CD_METHOD2= '001' AND EZCODE LIKE @P_CD_SEARCH2 + '%') OR
																   (@P_CD_METHOD2= '002' AND EZCODE LIKE '%' + @P_CD_SEARCH2 + '%') OR
																   (@P_CD_METHOD2= '003' AND EZCODE IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH2)))))))
	AND (ISNULL(@P_CD_SEARCH3, '') = '' OR
		 (@P_CD_MNG3 = '000' AND ((@P_CD_METHOD3= '000' AND MI.CD_ITEM = @P_CD_SEARCH3) OR
								  (@P_CD_METHOD3= '001' AND MI.CD_ITEM LIKE @P_CD_SEARCH3 + '%') OR
								  (@P_CD_METHOD3= '002' AND MI.CD_ITEM LIKE '%' + @P_CD_SEARCH3 + '%') OR
								  (@P_CD_METHOD3= '003' AND MI.CD_ITEM IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH3))))) OR
		 (@P_CD_MNG3 = '001' AND ((@P_CD_METHOD3= '000' AND MI.NM_ITEM = @P_CD_SEARCH3) OR
								  (@P_CD_METHOD3= '001' AND MI.NM_ITEM LIKE @P_CD_SEARCH3 + '%') OR
								  (@P_CD_METHOD3= '002' AND MI.NM_ITEM LIKE '%' + @P_CD_SEARCH3 + '%') OR
								  (@P_CD_METHOD3= '003' AND MI.NM_ITEM IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH3))))) OR
		 (@P_CD_MNG3 = '002' AND ((@P_CD_METHOD3= '000' AND MI.STND_ITEM = @P_CD_SEARCH3) OR
								  (@P_CD_METHOD3= '001' AND MI.STND_ITEM LIKE @P_CD_SEARCH3 + '%') OR
								  (@P_CD_METHOD3= '002' AND MI.STND_ITEM LIKE '%' + @P_CD_SEARCH3 + '%') OR
								  (@P_CD_METHOD3= '003' AND MI.STND_ITEM IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH3))))) OR
		 (@P_CD_MNG3 = '003' AND ((@P_CD_METHOD3= '000' AND MI.UCODE2 = @P_CD_SEARCH3) OR
								  (@P_CD_METHOD3= '001' AND MI.UCODE2 LIKE @P_CD_SEARCH3 + '%') OR
								  (@P_CD_METHOD3= '002' AND MI.UCODE2 LIKE '%' + @P_CD_SEARCH3 + '%') OR
								  (@P_CD_METHOD3= '003' AND MI.UCODE2 IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH3))))) OR
		 (@P_CD_MNG3 = '004' AND ((@P_CD_METHOD3= '000' AND MI.STND_DETAIL_ITEM = @P_CD_SEARCH3) OR
								  (@P_CD_METHOD3= '001' AND MI.STND_DETAIL_ITEM LIKE @P_CD_SEARCH3 + '%') OR
								  (@P_CD_METHOD3= '002' AND MI.STND_DETAIL_ITEM LIKE '%' + @P_CD_SEARCH3 + '%') OR
								  (@P_CD_METHOD3= '003' AND MI.STND_DETAIL_ITEM IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH3))))) OR
		 (@P_CD_MNG3 = '005' AND ((@P_CD_METHOD3= '000' AND MI.NM_MAKER = @P_CD_SEARCH3) OR
								  (@P_CD_METHOD3= '001' AND MI.NM_MAKER LIKE @P_CD_SEARCH3 + '%') OR
								  (@P_CD_METHOD3= '002' AND MI.NM_MAKER LIKE '%' + @P_CD_SEARCH3 + '%') OR
								  (@P_CD_METHOD3= '003' AND MI.NM_MAKER IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH3))))) OR
		 (@P_CD_MNG3 = '006' AND ((@P_CD_METHOD3= '000' AND MI.BARCODE = @P_CD_SEARCH3) OR
								  (@P_CD_METHOD3= '001' AND MI.BARCODE LIKE @P_CD_SEARCH3 + '%') OR
								  (@P_CD_METHOD3= '002' AND MI.BARCODE LIKE '%' + @P_CD_SEARCH3 + '%') OR
								  (@P_CD_METHOD3= '003' AND MI.BARCODE IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH3))))) OR
		 (@P_CD_MNG3 = '007' AND ((@P_CD_METHOD3= '000' AND MI.DC_MODEL = @P_CD_SEARCH3) OR
								  (@P_CD_METHOD3= '001' AND MI.DC_MODEL LIKE @P_CD_SEARCH3 + '%') OR
								  (@P_CD_METHOD3= '002' AND MI.DC_MODEL LIKE '%' + @P_CD_SEARCH3 + '%') OR
								  (@P_CD_METHOD3= '003' AND MI.DC_MODEL IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH3))))) OR
		 (@P_CD_MNG3 = '008' AND ((@P_CD_METHOD3= '000' AND MI.DC_KEYWORD = @P_CD_SEARCH3) OR
								  (@P_CD_METHOD3= '001' AND MI.DC_KEYWORD LIKE @P_CD_SEARCH3 + '%') OR
								  (@P_CD_METHOD3= '002' AND MI.DC_KEYWORD LIKE '%' + @P_CD_SEARCH3 + '%') OR
								  (@P_CD_METHOD3= '003' AND MI.DC_KEYWORD IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH3))))) OR
		 (@P_CD_MNG3 = '009' AND ((@P_CD_METHOD3= '000' AND MI.MAT_ITEM = @P_CD_SEARCH3) OR
								  (@P_CD_METHOD3= '001' AND MI.MAT_ITEM LIKE @P_CD_SEARCH3 + '%') OR
								  (@P_CD_METHOD3= '002' AND MI.MAT_ITEM LIKE '%' + @P_CD_SEARCH3 + '%') OR
								  (@P_CD_METHOD3= '003' AND MI.MAT_ITEM IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH3))))) OR
		 (@P_CD_MNG3 = '010' AND ((@P_CD_METHOD3= '000' AND MI.NO_STND = @P_CD_SEARCH3) OR
								  (@P_CD_METHOD3= '001' AND MI.NO_STND LIKE @P_CD_SEARCH3 + '%') OR
								  (@P_CD_METHOD3= '002' AND MI.NO_STND LIKE '%' + @P_CD_SEARCH3 + '%') OR
								  (@P_CD_METHOD3= '003' AND MI.NO_STND IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH3))))) OR
		 (@P_CD_MNG1 = '010' AND @P_YN_INTRA = 'Y' AND EXISTS(SELECT 1 
															  FROM CZ_EZCODE_PITEM 
															  WHERE CD_COMPANY = MI.CD_COMPANY 
															  AND CD_ITEM = MI.CD_ITEM
															  AND ((@P_CD_METHOD3= '000' AND EZCODE = @P_CD_SEARCH3) OR
																   (@P_CD_METHOD3= '001' AND EZCODE LIKE @P_CD_SEARCH3 + '%') OR
																   (@P_CD_METHOD3= '002' AND EZCODE LIKE '%' + @P_CD_SEARCH3 + '%') OR
																   (@P_CD_METHOD3= '003' AND EZCODE IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH3)))))))
	ORDER BY MI.CD_ITEM
	OPTION(RECOMPILE)
END
ELSE
BEGIN
	SELECT 'N' AS S,
		   MI.CD_PLANT,
		   MI.CD_ITEM,
		   MI.NM_ITEM, 
		   MI.CD_ITEM_PARTNER,
		   MI.NM_ITEM_PARTNER,
		   MI.STND_DETAIL_ITEM, 
		   MI.STND_ITEM, 
		   MI.MAT_ITEM, 
		   MI.DC_OFFER,
		   MI.NO_STND, 
		   MI.CLS_ITEM,
		   CD4.NM_SYSDEF AS NM_CLS_ITEM,
		   MI.UNIT_IM,
		   CD5.NM_SYSDEF AS NM_UNIT_IM,
		   MI.GRP_ITEM, 
		   IG.NM_ITEMGRP AS NM_GRP_ITEM, 
		   MI.GRP_MFG, 
		   CD.NM_SYSDEF AS NM_GRP_MFG,
		   (CASE WHEN NULLIF(MI.WEIGHT, 0) IS NOT NULL THEN MI.WEIGHT
				 WHEN MU.WEIGHT_LOG IS NOT NULL THEN MU.WEIGHT_LOG
				 ELSE 0 END) AS WEIGHT, 
		   MI.FG_ABC, 
		   MI.CD_ZONE,  
		   MI.STAND_PRC, 
		   MI.CLS_L, 
		   CD1.NM_SYSDEF AS NM_CLS_L, 
		   MI.CLS_M, 
		   CD2.NM_SYSDEF AS NM_CLS_M, 
		   MI.CLS_S, 
		   CD3.NM_SYSDEF AS NM_CLS_S,
		   MI.YN_USE, 
		   MI.ID_INSERT AS INSERT_ID, 
		   ME.NM_KOR AS NM_INSERT_ID,
		   MI.DTS_INSERT,
		   MI.ID_UPDATE AS UPDATE_ID, 
		   ME1.NM_KOR AS NM_UPDATE_ID,
		   MI.DTS_UPDATE,
		   MI.DC_RMK,
		   MI.DC_RMK1,
		   MI.DC_RMK2,
		   MI.PARTNER,
		   MP.LN_PARTNER,
		   MI.CD_PARTNER1,
		   MP1.LN_PARTNER AS LN_PARTNER1,
		   MI.CD_PARTNER2,
		   MP2.LN_PARTNER AS LN_PARTNER2,
		   MI.TP_PROC,
		   MI.TP_ITEM,
		   CD6.NM_SYSDEF AS NM_TP_ITEM,
		   MI.TP_PART,
		   MI.FG_GIR,
		   MI.DT_VALID,
		   MI.QT_SSTOCK, 
		   MI.LT_SAFE, 
		   MI.YN_PHANTOM,  
		   MI.FG_LONG, 
		   MI.LT_ITEM,
		   MI.LOTSIZE,
		   MI.QT_MIN,
		   MI.CLS_PO,
		   MF.IMAGE1,
		   MF.IMAGE2,
		   MF.IMAGE3,
		   MF.IMAGE4,
		   MF.IMAGE5,
		   MF.IMAGE6,
		   MF.IMAGE7,
		   MF.DC_IMAGE1,
		   MF.DC_IMAGE2,
		   MF.DC_IMAGE3,
		   MF.DC_IMAGE4,
		   MF.DC_IMAGE5,
		   MF.DC_IMAGE6,
		   MF.DC_IMAGE7,
		   MI.UCODE2,
		   MI.NUM_USERDEF3,
		   MI.CD_SL,
		   MS.NM_SL,
		   MI.CD_GISL,
		   MS1.NM_SL AS NM_GISL,
		   MI.DC_KEYWORD,
		   MI.DC_KEYWORD_WE,
		   MI.DC_KEYWORD_CO,
		   MI.DC_KEYWORD_EX1,
		   MI.DC_KEYWORD_EX2,
		   MI.DC_MODEL,
		   MI.KCODE2,
		   ISNULL(MI.YN_MGMT, 'N') AS YN_MGMT,
		   MI.DC_RMK3,
		   NULL AS EZCODE,
		   MI.LT_STDEV,
		   MI.RT_STDEV,
		   MF.YN_MAIN,
		   MI.YN_MATCH,
		   MI.DC_RMK4
	FROM MA_PITEM MI
	JOIN MA_PLANT PT ON PT.CD_COMPANY = MI.CD_COMPANY AND PT.CD_PLANT = MI.CD_PLANT
	LEFT JOIN CZ_MA_PITEM_FILE MF ON MF.CD_COMPANY = MI.CD_COMPANY AND MF.CD_PLANT = MI.CD_PLANT AND MF.CD_ITEM = MI.CD_ITEM
	LEFT JOIN MA_ITEMGRP IG ON IG.CD_COMPANY = MI.CD_COMPANY AND IG.CD_ITEMGRP = MI.GRP_ITEM
	LEFT JOIN MA_CODEDTL CD ON CD.CD_COMPANY = MI.CD_COMPANY AND CD.CD_FIELD = 'MA_B000066' AND CD.CD_SYSDEF = MI.GRP_MFG 
	LEFT JOIN MA_CODEDTL CD1 ON CD1.CD_COMPANY = MI.CD_COMPANY AND CD1.CD_FIELD = 'MA_B000030' AND CD1.CD_SYSDEF = MI.CLS_L
	LEFT JOIN MA_CODEDTL CD2 ON CD2.CD_COMPANY = MI.CD_COMPANY AND CD2.CD_FIELD = 'MA_B000031' AND CD2.CD_SYSDEF = MI.CLS_M
	LEFT JOIN MA_CODEDTL CD3 ON CD3.CD_COMPANY = MI.CD_COMPANY AND CD3.CD_FIELD = 'MA_B000032' AND CD3.CD_SYSDEF = MI.CLS_S 
	LEFT JOIN MA_CODEDTL CD4 ON CD4.CD_COMPANY = MI.CD_COMPANY AND CD4.CD_FIELD = 'MA_B000010' AND CD4.CD_SYSDEF = MI.CLS_ITEM
	LEFT JOIN MA_CODEDTL CD5 ON CD5.CD_COMPANY = MI.CD_COMPANY AND CD5.CD_FIELD = 'MA_B000004' AND CD5.CD_SYSDEF = MI.UNIT_IM
	LEFT JOIN MA_CODEDTL CD6 ON CD6.CD_COMPANY = MI.CD_COMPANY AND CD6.CD_FIELD = 'MA_B000011' AND CD6.CD_SYSDEF = MI.TP_ITEM
	LEFT JOIN MA_EMP ME ON ME.CD_COMPANY = MI.CD_COMPANY AND ME.NO_EMP = MI.ID_INSERT
	LEFT JOIN MA_EMP ME1 ON ME1.CD_COMPANY = MI.CD_COMPANY AND ME1.NO_EMP = MI.ID_UPDATE
	LEFT JOIN MA_PARTNER MP ON MP.CD_COMPANY = MI.CD_COMPANY AND MP.CD_PARTNER = MI.PARTNER
	LEFT JOIN MA_PARTNER MP1 ON MP1.CD_COMPANY = MI.CD_COMPANY AND MP1.CD_PARTNER = MI.CD_PARTNER1
	LEFT JOIN MA_PARTNER MP2 ON MP2.CD_COMPANY = MI.CD_COMPANY AND MP2.CD_PARTNER = MI.CD_PARTNER2
	LEFT JOIN MA_SL MS ON MS.CD_COMPANY = MI.CD_COMPANY AND MS.CD_BIZAREA = MI.CD_BIZAREA AND MS.CD_PLANT = MI.CD_PLANT AND MS.CD_SL = MI.CD_SL
	LEFT JOIN MA_SL MS1 ON MS1.CD_COMPANY = MI.CD_COMPANY AND MS1.CD_BIZAREA = MI.CD_BIZAREA AND MS1.CD_PLANT = MI.CD_PLANT AND MS1.CD_SL = MI.CD_GISL
	LEFT JOIN CZ_MA_UCODE_HGS MU ON MU.CD_COMPANY = MI.CD_COMPANY AND MU.UCODE = MI.STND_DETAIL_ITEM AND MU.UCODE != ''
	WHERE MI.CD_COMPANY = @P_CD_COMPANY
	AND MI.CD_PLANT = @P_CD_PLANT   
	AND (ISNULL(@P_MULTI_GRP_ITEM, '') = '' OR MI.GRP_ITEM IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_MULTI_GRP_ITEM)))  
	AND (ISNULL(@P_YN_USE, '') = '' OR MI.YN_USE = @P_YN_USE)     
	AND (ISNULL(@P_CLS_ITEM, '') = '' OR MI.CLS_ITEM IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CLS_ITEM)))    
	AND (ISNULL(@P_GRP_MFG, '') = '' OR MI.GRP_MFG = @P_GRP_MFG)
	AND (ISNULL(@P_TP_PART, '') = '' OR MI.TP_PART = @P_TP_PART)
	AND (ISNULL(@P_TP_PROC, '') = '' OR MI.TP_PROC = @P_TP_PROC)
	AND (ISNULL(@P_CD_PARTNER, '') = '' OR MI.PARTNER = @P_CD_PARTNER)
	AND (ISNULL(@P_CLS_L, '') = '' OR MI.CLS_L = @P_CLS_L)    
	AND (ISNULL(@P_CLS_M, '') = '' OR MI.CLS_M = @P_CLS_M)    
	AND (ISNULL(@P_CLS_S, '') = '' OR MI.CLS_S = @P_CLS_S)    
	AND (ISNULL(@P_CD_SEARCH1, '') = '' OR
		 (@P_CD_MNG1 = '000' AND ((@P_CD_METHOD1= '000' AND MI.CD_ITEM = @P_CD_SEARCH1) OR
								  (@P_CD_METHOD1= '001' AND MI.CD_ITEM LIKE @P_CD_SEARCH1 + '%') OR
								  (@P_CD_METHOD1= '002' AND MI.CD_ITEM LIKE '%' + @P_CD_SEARCH1 + '%') OR
								  (@P_CD_METHOD1= '003' AND MI.CD_ITEM IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH1))))) OR
		 (@P_CD_MNG1 = '001' AND ((@P_CD_METHOD1= '000' AND MI.NM_ITEM = @P_CD_SEARCH1) OR
								  (@P_CD_METHOD1= '001' AND MI.NM_ITEM LIKE @P_CD_SEARCH1 + '%') OR
								  (@P_CD_METHOD1= '002' AND MI.NM_ITEM LIKE '%' + @P_CD_SEARCH1 + '%') OR
								  (@P_CD_METHOD1= '003' AND MI.NM_ITEM IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH1))))) OR
		 (@P_CD_MNG1 = '002' AND ((@P_CD_METHOD1= '000' AND MI.STND_ITEM = @P_CD_SEARCH1) OR
								  (@P_CD_METHOD1= '001' AND MI.STND_ITEM LIKE @P_CD_SEARCH1 + '%') OR
								  (@P_CD_METHOD1= '002' AND MI.STND_ITEM LIKE '%' + @P_CD_SEARCH1 + '%') OR
								  (@P_CD_METHOD1= '003' AND MI.STND_ITEM IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH1))))) OR
		 (@P_CD_MNG1 = '003' AND ((@P_CD_METHOD1= '000' AND MI.UCODE2 = @P_CD_SEARCH1) OR
								  (@P_CD_METHOD1= '001' AND MI.UCODE2 LIKE @P_CD_SEARCH1 + '%') OR
								  (@P_CD_METHOD1= '002' AND MI.UCODE2 LIKE '%' + @P_CD_SEARCH1 + '%') OR
								  (@P_CD_METHOD1= '003' AND MI.UCODE2 IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH1))))) OR
		 (@P_CD_MNG1 = '004' AND ((@P_CD_METHOD1= '000' AND MI.STND_DETAIL_ITEM = @P_CD_SEARCH1) OR
								  (@P_CD_METHOD1= '001' AND MI.STND_DETAIL_ITEM LIKE @P_CD_SEARCH1 + '%') OR
								  (@P_CD_METHOD1= '002' AND MI.STND_DETAIL_ITEM LIKE '%' + @P_CD_SEARCH1 + '%') OR
								  (@P_CD_METHOD1= '003' AND MI.STND_DETAIL_ITEM IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH1))))) OR
		 (@P_CD_MNG1 = '005' AND ((@P_CD_METHOD1= '000' AND MI.NM_MAKER = @P_CD_SEARCH1) OR
								  (@P_CD_METHOD1= '001' AND MI.NM_MAKER LIKE @P_CD_SEARCH1 + '%') OR
								  (@P_CD_METHOD1= '002' AND MI.NM_MAKER LIKE '%' + @P_CD_SEARCH1 + '%') OR
								  (@P_CD_METHOD1= '003' AND MI.NM_MAKER IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH1))))) OR
		 (@P_CD_MNG1 = '006' AND ((@P_CD_METHOD1= '000' AND MI.BARCODE = @P_CD_SEARCH1) OR
								  (@P_CD_METHOD1= '001' AND MI.BARCODE LIKE @P_CD_SEARCH1 + '%') OR
								  (@P_CD_METHOD1= '002' AND MI.BARCODE LIKE '%' + @P_CD_SEARCH1 + '%') OR
								  (@P_CD_METHOD1= '003' AND MI.BARCODE IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH1))))) OR
		 (@P_CD_MNG1 = '007' AND ((@P_CD_METHOD1= '000' AND MI.DC_MODEL = @P_CD_SEARCH1) OR
								  (@P_CD_METHOD1= '001' AND MI.DC_MODEL LIKE @P_CD_SEARCH1 + '%') OR
								  (@P_CD_METHOD1= '002' AND MI.DC_MODEL LIKE '%' + @P_CD_SEARCH1 + '%') OR
								  (@P_CD_METHOD1= '003' AND MI.DC_MODEL IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH1))))) OR
		 (@P_CD_MNG1 = '008' AND ((@P_CD_METHOD1= '000' AND MI.DC_KEYWORD = @P_CD_SEARCH1) OR
								  (@P_CD_METHOD1= '001' AND MI.DC_KEYWORD LIKE @P_CD_SEARCH1 + '%') OR
								  (@P_CD_METHOD1= '002' AND MI.DC_KEYWORD LIKE '%' + @P_CD_SEARCH1 + '%') OR
								  (@P_CD_METHOD1= '003' AND MI.DC_KEYWORD IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH1))))) OR
		 (@P_CD_MNG1 = '009' AND ((@P_CD_METHOD1= '000' AND MI.MAT_ITEM = @P_CD_SEARCH1) OR
								  (@P_CD_METHOD1= '001' AND MI.MAT_ITEM LIKE @P_CD_SEARCH1 + '%') OR
								  (@P_CD_METHOD1= '002' AND MI.MAT_ITEM LIKE '%' + @P_CD_SEARCH1 + '%') OR
								  (@P_CD_METHOD1= '003' AND MI.MAT_ITEM IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH1))))) OR
		 (@P_CD_MNG1 = '010' AND ((@P_CD_METHOD1= '000' AND MI.NO_STND = @P_CD_SEARCH1) OR
								  (@P_CD_METHOD1= '001' AND MI.NO_STND LIKE @P_CD_SEARCH1 + '%') OR
								  (@P_CD_METHOD1= '002' AND MI.NO_STND LIKE '%' + @P_CD_SEARCH1 + '%') OR
								  (@P_CD_METHOD1= '003' AND MI.NO_STND IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH1))))))
	AND (ISNULL(@P_CD_SEARCH2, '') = '' OR
		 (@P_CD_MNG2 = '000' AND ((@P_CD_METHOD2= '000' AND MI.CD_ITEM = @P_CD_SEARCH2) OR
								  (@P_CD_METHOD2= '001' AND MI.CD_ITEM LIKE @P_CD_SEARCH2 + '%') OR
								  (@P_CD_METHOD2= '002' AND MI.CD_ITEM LIKE '%' + @P_CD_SEARCH2 + '%') OR
								  (@P_CD_METHOD2= '003' AND MI.CD_ITEM IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH2))))) OR
		 (@P_CD_MNG2 = '001' AND ((@P_CD_METHOD2= '000' AND MI.NM_ITEM = @P_CD_SEARCH2) OR
								  (@P_CD_METHOD2= '001' AND MI.NM_ITEM LIKE @P_CD_SEARCH2 + '%') OR
								  (@P_CD_METHOD2= '002' AND MI.NM_ITEM LIKE '%' + @P_CD_SEARCH2 + '%') OR
								  (@P_CD_METHOD2= '003' AND MI.NM_ITEM IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH2))))) OR
		 (@P_CD_MNG2 = '002' AND ((@P_CD_METHOD2= '000' AND MI.STND_ITEM = @P_CD_SEARCH2) OR
								  (@P_CD_METHOD2= '001' AND MI.STND_ITEM LIKE @P_CD_SEARCH2 + '%') OR
								  (@P_CD_METHOD2= '002' AND MI.STND_ITEM LIKE '%' + @P_CD_SEARCH2 + '%') OR
								  (@P_CD_METHOD2= '003' AND MI.STND_ITEM IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH2))))) OR
		 (@P_CD_MNG2 = '003' AND ((@P_CD_METHOD2= '000' AND MI.UCODE2 = @P_CD_SEARCH2) OR
								  (@P_CD_METHOD2= '001' AND MI.UCODE2 LIKE @P_CD_SEARCH2 + '%') OR
								  (@P_CD_METHOD2= '002' AND MI.UCODE2 LIKE '%' + @P_CD_SEARCH2 + '%') OR
								  (@P_CD_METHOD2= '003' AND MI.UCODE2 IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH2))))) OR
		 (@P_CD_MNG2 = '004' AND ((@P_CD_METHOD2= '000' AND MI.STND_DETAIL_ITEM = @P_CD_SEARCH2) OR
								  (@P_CD_METHOD2= '001' AND MI.STND_DETAIL_ITEM LIKE @P_CD_SEARCH2 + '%') OR
								  (@P_CD_METHOD2= '002' AND MI.STND_DETAIL_ITEM LIKE '%' + @P_CD_SEARCH2 + '%') OR
								  (@P_CD_METHOD2= '003' AND MI.STND_DETAIL_ITEM IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH2))))) OR
		 (@P_CD_MNG2 = '005' AND ((@P_CD_METHOD2= '000' AND MI.NM_MAKER = @P_CD_SEARCH2) OR
								  (@P_CD_METHOD2= '001' AND MI.NM_MAKER LIKE @P_CD_SEARCH2 + '%') OR
								  (@P_CD_METHOD2= '002' AND MI.NM_MAKER LIKE '%' + @P_CD_SEARCH2 + '%') OR
								  (@P_CD_METHOD2= '003' AND MI.NM_MAKER IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH2))))) OR
		 (@P_CD_MNG2 = '006' AND ((@P_CD_METHOD2= '000' AND MI.BARCODE = @P_CD_SEARCH2) OR
								  (@P_CD_METHOD2= '001' AND MI.BARCODE LIKE @P_CD_SEARCH2 + '%') OR
								  (@P_CD_METHOD2= '002' AND MI.BARCODE LIKE '%' + @P_CD_SEARCH2 + '%') OR
								  (@P_CD_METHOD2= '003' AND MI.BARCODE IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH2))))) OR
		 (@P_CD_MNG2 = '007' AND ((@P_CD_METHOD2= '000' AND MI.DC_MODEL = @P_CD_SEARCH2) OR
								  (@P_CD_METHOD2= '001' AND MI.DC_MODEL LIKE @P_CD_SEARCH2 + '%') OR
								  (@P_CD_METHOD2= '002' AND MI.DC_MODEL LIKE '%' + @P_CD_SEARCH2 + '%') OR
								  (@P_CD_METHOD2= '003' AND MI.DC_MODEL IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH2))))) OR
		 (@P_CD_MNG2 = '008' AND ((@P_CD_METHOD2= '000' AND MI.DC_KEYWORD = @P_CD_SEARCH2) OR
								  (@P_CD_METHOD2= '001' AND MI.DC_KEYWORD LIKE @P_CD_SEARCH2 + '%') OR
								  (@P_CD_METHOD2= '002' AND MI.DC_KEYWORD LIKE '%' + @P_CD_SEARCH2 + '%') OR
								  (@P_CD_METHOD2= '003' AND MI.DC_KEYWORD IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH2))))) OR
		 (@P_CD_MNG2 = '009' AND ((@P_CD_METHOD2= '000' AND MI.MAT_ITEM = @P_CD_SEARCH2) OR
								  (@P_CD_METHOD2= '001' AND MI.MAT_ITEM LIKE @P_CD_SEARCH2 + '%') OR
								  (@P_CD_METHOD2= '002' AND MI.MAT_ITEM LIKE '%' + @P_CD_SEARCH2 + '%') OR
								  (@P_CD_METHOD2= '003' AND MI.MAT_ITEM IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH2))))) OR
		 (@P_CD_MNG2 = '010' AND ((@P_CD_METHOD2= '000' AND MI.NO_STND = @P_CD_SEARCH2) OR
								  (@P_CD_METHOD2= '001' AND MI.NO_STND LIKE @P_CD_SEARCH2 + '%') OR
								  (@P_CD_METHOD2= '002' AND MI.NO_STND LIKE '%' + @P_CD_SEARCH2 + '%') OR
								  (@P_CD_METHOD2= '003' AND MI.NO_STND IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH2))))))
	AND (ISNULL(@P_CD_SEARCH3, '') = '' OR
		 (@P_CD_MNG3 = '000' AND ((@P_CD_METHOD3= '000' AND MI.CD_ITEM = @P_CD_SEARCH3) OR
								  (@P_CD_METHOD3= '001' AND MI.CD_ITEM LIKE @P_CD_SEARCH3 + '%') OR
								  (@P_CD_METHOD3= '002' AND MI.CD_ITEM LIKE '%' + @P_CD_SEARCH3 + '%') OR
								  (@P_CD_METHOD3= '003' AND MI.CD_ITEM IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH3))))) OR
		 (@P_CD_MNG3 = '001' AND ((@P_CD_METHOD3= '000' AND MI.NM_ITEM = @P_CD_SEARCH3) OR
								  (@P_CD_METHOD3= '001' AND MI.NM_ITEM LIKE @P_CD_SEARCH3 + '%') OR
								  (@P_CD_METHOD3= '002' AND MI.NM_ITEM LIKE '%' + @P_CD_SEARCH3 + '%') OR
								  (@P_CD_METHOD3= '003' AND MI.NM_ITEM IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH3))))) OR
		 (@P_CD_MNG3 = '002' AND ((@P_CD_METHOD3= '000' AND MI.STND_ITEM = @P_CD_SEARCH3) OR
								  (@P_CD_METHOD3= '001' AND MI.STND_ITEM LIKE @P_CD_SEARCH3 + '%') OR
								  (@P_CD_METHOD3= '002' AND MI.STND_ITEM LIKE '%' + @P_CD_SEARCH3 + '%') OR
								  (@P_CD_METHOD3= '003' AND MI.STND_ITEM IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH3))))) OR
		 (@P_CD_MNG3 = '003' AND ((@P_CD_METHOD3= '000' AND MI.UCODE2 = @P_CD_SEARCH3) OR
								  (@P_CD_METHOD3= '001' AND MI.UCODE2 LIKE @P_CD_SEARCH3 + '%') OR
								  (@P_CD_METHOD3= '002' AND MI.UCODE2 LIKE '%' + @P_CD_SEARCH3 + '%') OR
								  (@P_CD_METHOD3= '003' AND MI.UCODE2 IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH3))))) OR
		 (@P_CD_MNG3 = '004' AND ((@P_CD_METHOD3= '000' AND MI.STND_DETAIL_ITEM = @P_CD_SEARCH3) OR
								  (@P_CD_METHOD3= '001' AND MI.STND_DETAIL_ITEM LIKE @P_CD_SEARCH3 + '%') OR
								  (@P_CD_METHOD3= '002' AND MI.STND_DETAIL_ITEM LIKE '%' + @P_CD_SEARCH3 + '%') OR
								  (@P_CD_METHOD3= '003' AND MI.STND_DETAIL_ITEM IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH3))))) OR
		 (@P_CD_MNG3 = '005' AND ((@P_CD_METHOD3= '000' AND MI.NM_MAKER = @P_CD_SEARCH3) OR
								  (@P_CD_METHOD3= '001' AND MI.NM_MAKER LIKE @P_CD_SEARCH3 + '%') OR
								  (@P_CD_METHOD3= '002' AND MI.NM_MAKER LIKE '%' + @P_CD_SEARCH3 + '%') OR
								  (@P_CD_METHOD3= '003' AND MI.NM_MAKER IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH3))))) OR
		 (@P_CD_MNG3 = '006' AND ((@P_CD_METHOD3= '000' AND MI.BARCODE = @P_CD_SEARCH3) OR
								  (@P_CD_METHOD3= '001' AND MI.BARCODE LIKE @P_CD_SEARCH3 + '%') OR
								  (@P_CD_METHOD3= '002' AND MI.BARCODE LIKE '%' + @P_CD_SEARCH3 + '%') OR
								  (@P_CD_METHOD3= '003' AND MI.BARCODE IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH3))))) OR
		 (@P_CD_MNG3 = '007' AND ((@P_CD_METHOD3= '000' AND MI.DC_MODEL = @P_CD_SEARCH3) OR
								  (@P_CD_METHOD3= '001' AND MI.DC_MODEL LIKE @P_CD_SEARCH3 + '%') OR
								  (@P_CD_METHOD3= '002' AND MI.DC_MODEL LIKE '%' + @P_CD_SEARCH3 + '%') OR
								  (@P_CD_METHOD3= '003' AND MI.DC_MODEL IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH3))))) OR
		 (@P_CD_MNG3 = '008' AND ((@P_CD_METHOD3= '000' AND MI.DC_KEYWORD = @P_CD_SEARCH3) OR
								  (@P_CD_METHOD3= '001' AND MI.DC_KEYWORD LIKE @P_CD_SEARCH3 + '%') OR
								  (@P_CD_METHOD3= '002' AND MI.DC_KEYWORD LIKE '%' + @P_CD_SEARCH3 + '%') OR
								  (@P_CD_METHOD3= '003' AND MI.DC_KEYWORD IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH3))))) OR
		 (@P_CD_MNG3 = '009' AND ((@P_CD_METHOD3= '000' AND MI.MAT_ITEM = @P_CD_SEARCH3) OR
								  (@P_CD_METHOD3= '001' AND MI.MAT_ITEM LIKE @P_CD_SEARCH3 + '%') OR
								  (@P_CD_METHOD3= '002' AND MI.MAT_ITEM LIKE '%' + @P_CD_SEARCH3 + '%') OR
								  (@P_CD_METHOD3= '003' AND MI.MAT_ITEM IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH3))))) OR
		 (@P_CD_MNG3 = '010' AND ((@P_CD_METHOD3= '000' AND MI.NO_STND = @P_CD_SEARCH3) OR
								  (@P_CD_METHOD3= '001' AND MI.NO_STND LIKE @P_CD_SEARCH3 + '%') OR
								  (@P_CD_METHOD3= '002' AND MI.NO_STND LIKE '%' + @P_CD_SEARCH3 + '%') OR
								  (@P_CD_METHOD3= '003' AND MI.NO_STND IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SEARCH3))))))
	ORDER BY MI.CD_ITEM
	OPTION(RECOMPILE)
END

GO