USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_MA_PITEM_EXCEL]    Script Date: 2016-06-28 오후 1:28:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




ALTER PROCEDURE [NEOE].[SP_CZ_MA_PITEM_EXCEL] 
(
	@P_XML			XML, 
	@P_ID_USER		NVARCHAR(10)
) 
AS 

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

DECLARE @V_DOC INT

EXEC SP_XML_PREPAREDOCUMENT @V_DOC OUTPUT, @P_XML 

SELECT * INTO #XML
FROM OPENXML (@V_DOC, '/XML/ROW', 2) WITH 
(
	CD_COMPANY			NVARCHAR(7),
	CD_BIZAREA			NVARCHAR(7),
	CD_PLANT			NVARCHAR(7),

	CD_ITEM				NVARCHAR(20),
	NM_ITEM				NVARCHAR(MAX),
	CD_ITEM_PARTNER		NVARCHAR(30),
	NM_ITEM_PARTNER		NVARCHAR(MAX),
	STND_ITEM			NVARCHAR(MAX),
	MAT_ITEM			NVARCHAR(MAX),
	DC_OFFER			NVARCHAR(MAX),
	NO_STND				NVARCHAR(MAX),
	CLS_ITEM			NVARCHAR(3),
	GRP_ITEM			NVARCHAR(20),
	GRP_MFG				NVARCHAR(4),
	WEIGHT				NUMERIC(21, 6),
	UNIT_IM				NVARCHAR(3),
	FG_ABC				NCHAR(1),
	CD_ZONE				NVARCHAR(20),        
	STAND_PRC			NUMERIC(15, 4),
	CLS_L				NVARCHAR(4),
	CLS_M				NVARCHAR(4),
	CLS_S				NVARCHAR(4),
	DC_RMK1				NVARCHAR(MAX),
	DC_RMK2				NVARCHAR(MAX),
	YN_USE				NCHAR(1),
	TP_ITEM				NVARCHAR(3),
	TP_PART				NCHAR(1),
	FG_GIR				NCHAR(1),
	TP_PROC				NVARCHAR(3),
	PARTNER				NVARCHAR(20),
	CD_PARTNER1			NVARCHAR(20),
	CD_PARTNER2			NVARCHAR(20),
	CD_SL				NVARCHAR(7),
	CD_GISL				NVARCHAR(7),
	DC_MODEL			NVARCHAR(MAX),
	KCODE2				NVARCHAR(MAX),
	YN_MGMT				NVARCHAR(1),
	YN_MATCH			NVARCHAR(1),
	DC_RMK				NVARCHAR(MAX),
	DC_RMK3				NVARCHAR(MAX),
	DC_RMK4				NVARCHAR(200),
	YN_DELETE			NVARCHAR(1),

	QT_SSTOCK			NUMERIC(17, 4),
	LT_SAFE				NUMERIC(3, 0),
	YN_PHANTOM			NCHAR(1),  
	FG_LONG				NCHAR(1),
	LT_ITEM				NUMERIC(3, 0),

	DT_VALID			NCHAR(8),
	CLS_PO				NVARCHAR(3),
	LOTSIZE				NUMERIC(17, 4),
	QT_MIN				NUMERIC(17, 4),
	DC_KEYWORD			NVARCHAR(2000),

	EZCODE				NVARCHAR(20)
)

EXEC SP_XML_REMOVEDOCUMENT @V_DOC 

-- ================================================== DELETE
DELETE A 
FROM MA_PITEM A
WHERE EXISTS (SELECT 1 
			  FROM #XML B 
			  WHERE B.CD_COMPANY = A.CD_COMPANY 
			  AND B.CD_PLANT = A.CD_PLANT 
			  AND B.CD_ITEM = A.CD_ITEM
			  AND B.YN_DELETE = 'Y');

DELETE A 
FROM CZ_MA_PITEM_FILE A 
WHERE EXISTS (SELECT 1 
			  FROM #XML B 
			  WHERE B.CD_COMPANY = A.CD_COMPANY 
			  AND B.CD_PLANT = A.CD_PLANT 
			  AND B.CD_ITEM = A.CD_ITEM
			  AND B.YN_DELETE = 'Y');

-- ================================================== UPDATE
UPDATE A
SET A.NM_ITEM = B.NM_ITEM,
	A.CD_ITEM_PARTNER = B.CD_ITEM_PARTNER,
	A.NM_ITEM_PARTNER = B.NM_ITEM_PARTNER,
	A.STND_ITEM = B.STND_ITEM,
	A.MAT_ITEM = B.MAT_ITEM,
	A.DC_OFFER = B.DC_OFFER, 
	A.NO_STND = B.NO_STND,
	A.CLS_ITEM = B.CLS_ITEM,
	A.GRP_ITEM = B.GRP_ITEM,
	A.GRP_MFG = B.GRP_MFG,
	A.WEIGHT = (CASE WHEN B.WEIGHT = 0 THEN A.WEIGHT ELSE B.WEIGHT END),
	A.UNIT_IM = B.UNIT_IM,
	A.UNIT_SO = B.UNIT_IM,
	A.UNIT_PO = B.UNIT_IM,
	A.UNIT_GI = B.UNIT_IM,
	A.UNIT_MO = B.UNIT_IM,
	A.FG_ABC = B.FG_ABC,
	A.CD_ZONE = B.CD_ZONE,     
	A.STAND_PRC = (CASE WHEN B.STAND_PRC = 0 THEN A.STAND_PRC ELSE B.STAND_PRC END),
	A.CLS_L = B.CLS_L,
	A.CLS_M = B.CLS_M,
	A.CLS_S = B.CLS_S,
	A.DC_RMK1 = B.DC_RMK1,
	A.DC_RMK2 = B.DC_RMK2,
	A.YN_USE = B.YN_USE,
	A.TP_ITEM = B.TP_ITEM,
	A.TP_PART = B.TP_PART,
	A.FG_GIR = B.FG_GIR,
	A.TP_PROC = B.TP_PROC,
	A.PARTNER = B.PARTNER,
	A.CD_PARTNER1 = B.CD_PARTNER1,
	A.CD_PARTNER2 = B.CD_PARTNER2,
	A.CD_SL = B.CD_SL,
	A.CD_GISL = B.CD_GISL, 
	A.DC_MODEL = B.DC_MODEL,
	A.KCODE2 = B.KCODE2,
	A.YN_MGMT = B.YN_MGMT,
	A.YN_MATCH = B.YN_MATCH,
	A.DC_RMK = REPLACE(B.DC_RMK, CHAR(10), CHAR(13) + CHAR(10)),
	A.DC_RMK3 = REPLACE(B.DC_RMK3, CHAR(10), CHAR(13) + CHAR(10)),
	A.DC_RMK4 = REPLACE(B.DC_RMK4, CHAR(10), CHAR(13) + CHAR(10)),
	
	A.QT_SSTOCK = B.QT_SSTOCK,
	A.LT_SAFE = B.LT_SAFE,
	A.YN_PHANTOM = B.YN_PHANTOM,  
	A.FG_LONG = B.FG_LONG,
	A.LT_ITEM = B.LT_ITEM,
	
	A.DT_VALID = B.DT_VALID,
	A.CLS_PO = B.CLS_PO,
	A.LOTSIZE = B.LOTSIZE,
	A.QT_MIN = B.QT_MIN,
	A.DC_KEYWORD = B.DC_KEYWORD,
	
	A.ID_UPDATE = @P_ID_USER, 
	A.DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE())
FROM MA_PITEM A
JOIN #XML B ON B.CD_COMPANY = A.CD_COMPANY AND B.CD_PLANT = A.CD_PLANT AND B.CD_ITEM = A.CD_ITEM
WHERE ISNULL(B.YN_DELETE, 'N') = 'N'

-- ================================================== INSERT
INSERT INTO MA_PITEM
(
	CD_COMPANY,
	CD_BIZAREA,
	CD_PLANT,
	CD_ITEM,
	NM_ITEM, 
	CD_ITEM_PARTNER,
	NM_ITEM_PARTNER,
	STND_ITEM, 
	MAT_ITEM, 
	DC_OFFER,
	NO_STND, 
	CLS_ITEM,
	GRP_ITEM, 
	GRP_MFG, 
	WEIGHT, 
	UNIT_IM,
	UNIT_SO,
	UNIT_PO,
	UNIT_GI,
	UNIT_MO,
	FG_ABC, 
	CD_ZONE,  
	STAND_PRC, 
	CLS_L, 
	CLS_M, 
	CLS_S, 
	DC_RMK1,
	DC_RMK2,
	YN_USE,
	TP_ITEM,
	TP_PART,
	FG_GIR,
	TP_PROC,
	PARTNER,
	CD_PARTNER1,
	CD_PARTNER2,
	CD_SL,
	CD_GISL, 
	DC_MODEL,
	KCODE2,
	YN_MGMT,
	YN_MATCH,
	DC_RMK,
	DC_RMK3,
	DC_RMK4,
	
	QT_SSTOCK, 
	LT_SAFE, 
	YN_PHANTOM,  
	FG_LONG, 
	LT_ITEM,

	DT_VALID,
	CLS_PO,
	LOTSIZE,
	QT_MIN,
	DC_KEYWORD,

	ID_INSERT,
	DTS_INSERT
)
SELECT A.CD_COMPANY,
	   A.CD_BIZAREA,
	   A.CD_PLANT,
	   A.CD_ITEM,
	   A.NM_ITEM, 
	   A.CD_ITEM_PARTNER,
	   A.NM_ITEM_PARTNER,
	   A.STND_ITEM, 
	   A.MAT_ITEM, 
	   A.DC_OFFER,
	   A.NO_STND, 
	   A.CLS_ITEM,
	   A.GRP_ITEM, 
	   A.GRP_MFG, 
	   A.WEIGHT, 
	   A.UNIT_IM,
	   A.UNIT_IM,
	   A.UNIT_IM,
	   A.UNIT_IM,
	   A.UNIT_IM,
	   A.FG_ABC, 
	   A.CD_ZONE,  
	   A.STAND_PRC, 
	   A.CLS_L, 
	   A.CLS_M, 
	   A.CLS_S, 
	   A.DC_RMK1,
	   A.DC_RMK2,
	   ISNULL(A.YN_USE, 'N') AS YN_USE,
	   A.TP_ITEM,
	   A.TP_PART,
	   ISNULL(A.FG_GIR, 'N') AS FG_GIR,
	   A.TP_PROC,
	   A.PARTNER,
	   A.CD_PARTNER1,
	   A.CD_PARTNER2,
	   A.CD_SL,
	   A.CD_GISL, 
	   A.DC_MODEL,
	   A.KCODE2,
	   A.YN_MGMT,
	   ISNULL(A.YN_MATCH, 'N') AS YN_MATCH,
	   REPLACE(A.DC_RMK, CHAR(10), CHAR(13) + CHAR(10)),
	   REPLACE(A.DC_RMK3, CHAR(10), CHAR(13) + CHAR(10)),
	   REPLACE(A.DC_RMK4, CHAR(10), CHAR(13) + CHAR(10)),
	   
	   A.QT_SSTOCK, 
	   A.LT_SAFE, 
	   A.YN_PHANTOM,  
	   A.FG_LONG, 
	   A.LT_ITEM,
	   
	   A.DT_VALID,
	   A.CLS_PO,
	   A.LOTSIZE,
	   A.QT_MIN,
	   A.DC_KEYWORD,

	   @P_ID_USER, 
	   NEOE.SF_SYSDATE(GETDATE())
FROM #XML A
WHERE ISNULL(A.YN_DELETE, 'N') = 'N'
AND NOT EXISTS (SELECT 1 
			    FROM MA_PITEM B
				WHERE B.CD_COMPANY = A.CD_COMPANY
				AND B.CD_PLANT = A.CD_PLANT
				AND B.CD_ITEM = A.CD_ITEM)

INSERT INTO CZ_MA_PITEM_FILE
(
	CD_COMPANY,
	CD_PLANT,
	CD_ITEM,
	ID_INSERT,
	DTS_INSERT
)
SELECT A.CD_COMPANY,
	   A.CD_PLANT,
	   A.CD_ITEM,
	   @P_ID_USER, 
	   NEOE.SF_SYSDATE(GETDATE())
FROM #XML A
WHERE ISNULL(A.YN_DELETE, 'N') = 'N'
AND NOT EXISTS (SELECT 1 
			    FROM CZ_MA_PITEM_FILE B
				WHERE B.CD_COMPANY = A.CD_COMPANY
				AND B.CD_PLANT = A.CD_PLANT
				AND B.CD_ITEM = A.CD_ITEM)


IF EXISTS (SELECT 1 
		   FROM SYSOBJECTS 
		   WHERE NAME = 'CZ_EZCODE_PITEM')
BEGIN
-- ================================================== DELETE
DELETE A 
FROM CZ_EZCODE_PITEM A
WHERE EXISTS (SELECT 1 
			  FROM #XML B 
			  WHERE B.CD_COMPANY = A.CD_COMPANY 
			  AND B.CD_ITEM = A.CD_ITEM
			  AND B.YN_DELETE = 'Y');

-- ================================================== INSERT, UPDATE
MERGE INTO CZ_EZCODE_PITEM AS T
	  USING (SELECT CD_COMPANY,
					CD_ITEM,
					EZCODE
	         FROM #XML
			 WHERE ISNULL(YN_DELETE, 'N') = 'N') AS S
	  ON T.CD_COMPANY = S.CD_COMPANY
	  AND T.CD_ITEM = S.CD_ITEM
	  WHEN MATCHED THEN
		UPDATE SET T.EZCODE = S.EZCODE,
				   T.ID_UPDATE = @P_ID_USER,
				   T.DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE())
	  WHEN NOT MATCHED THEN
		INSERT (CD_COMPANY,
				CD_ITEM,
				EZCODE,
				ID_INSERT,
				DTS_INSERT) 
		VALUES (S.CD_COMPANY,
				S.CD_ITEM,
				S.EZCODE,
				@P_ID_USER,
				NEOE.SF_SYSDATE(GETDATE()));
END

DROP TABLE #XML

GO

