USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_INQ_REGL_S]    Script Date: 2015-07-03 오후 7:42:45 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER PROCEDURE [NEOE].[SP_CZ_SA_INQ_REGL_S]
(
	@P_CD_COMPANY       NVARCHAR(7),
	@P_TP_STEP          NVARCHAR(3),
	@P_NO_KEY           NVARCHAR(20),
	@P_YN_INCLUDED		NVARCHAR(1) = 'N'
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT 'N' AS S,
	   WL.NO_KEY,
	   WL.NO_LINE,
	   '' AS FULL_PATH,
	   WL.NM_FILE,
	   WL.NM_FILE_REAL,
	   WL.CD_SUPPLIER,
	   MP.LN_PARTNER AS NM_SUPPLIER,
	   WL.YN_PARSING,
	   WL.DTS_INSERT,
	   '' AS FILE_STATE,
	   WL.YN_INCLUDED
FROM CZ_MA_WORKFLOWL WL
LEFT JOIN MA_PARTNER MP ON MP.CD_COMPANY = WL.CD_COMPANY AND MP.CD_PARTNER = WL.CD_SUPPLIER
WHERE WL.CD_COMPANY = @P_CD_COMPANY
AND WL.TP_STEP = @P_TP_STEP
AND WL.NO_KEY = @P_NO_KEY
AND ISNULL(WL.NM_FILE, '') <> ''
AND (ISNULL(@P_YN_INCLUDED, 'N') = 'Y' OR (WL.YN_INCLUDED IS NULL OR WL.YN_INCLUDED = 'N'))

GO