USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_INQ_REG_U]    Script Date: 2015-07-03 오후 5:28:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER PROCEDURE [NEOE].[SP_CZ_SA_INQ_REGH_U]
(
	@P_CD_COMPANY	NVARCHAR(7),
	@P_TP_STEP		NVARCHAR(3),
	@P_NO_KEY		NVARCHAR(20),
	@P_TP_SALES		NVARCHAR(2),
	@P_ID_SALES		NVARCHAR(15),
	@P_ID_TYPIST	NVARCHAR(15),
	@P_ID_PUR		NVARCHAR(15),
	@P_ID_LOG		NVARCHAR(15),
	@P_DC_RMK		NVARCHAR(MAX),
	@P_ID_UPDATE	NVARCHAR(15)
) AS	

DECLARE @V_NO_HIST NUMERIC(5, 0)

SELECT @V_NO_HIST = (ISNULL(MAX(NO_HIST), 0) + 1)
FROM CZ_MA_WORKFLOWH_LOG
WHERE CD_COMPANY = @P_CD_COMPANY
AND TP_STEP = @P_TP_STEP
AND NO_KEY = @P_NO_KEY

INSERT INTO CZ_MA_WORKFLOWH_LOG
(
	CD_COMPANY, 
	NO_KEY, 
	TP_STEP, 
	NO_HIST, 
	TP_SALES, 
	ID_SALES, 
	ID_TYPIST, 
	ID_PUR, 
	ID_LOG, 
	YN_DONE, 
	DTS_DONE, 
	CD_RMK, 
	DC_RMK, 
	INSERT_HIST, 
	UPDATE_HIST, 
	ID_INSERT, 
	DTS_INSERT, 
	ID_UPDATE, 
	DTS_UPDATE
)
SELECT WH.CD_COMPANY, 
	   WH.NO_KEY, 
	   WH.TP_STEP, 
	   @V_NO_HIST, 
	   WH.TP_SALES, 
	   WH.ID_SALES, 
	   WH.ID_TYPIST, 
	   WH.ID_PUR, 
	   WH.ID_LOG, 
	   WH.YN_DONE, 
	   WH.DTS_DONE, 
	   WH.CD_RMK, 
	   WH.DC_RMK, 
	   WH.INSERT_HIST, 
	   WH.UPDATE_HIST, 
	   WH.ID_INSERT, 
	   WH.DTS_INSERT, 
	   WH.ID_UPDATE, 
	   WH.DTS_UPDATE 
FROM CZ_MA_WORKFLOWH WH
WHERE WH.CD_COMPANY = @P_CD_COMPANY
AND WH.TP_STEP = @P_TP_STEP
AND WH.NO_KEY = @P_NO_KEY

UPDATE CZ_MA_WORKFLOWH 
SET TP_SALES = @P_TP_SALES,
	ID_SALES = (CASE WHEN @P_TP_STEP = '01' THEN @P_ID_SALES ELSE (SELECT ID_SALES FROM CZ_MA_WORKFLOWH WHERE CD_COMPANY = @P_CD_COMPANY AND TP_STEP = '01' AND NO_KEY = @P_NO_KEY) END),
	ID_TYPIST = (CASE WHEN @P_TP_STEP = '01' THEN @P_ID_TYPIST ELSE (SELECT ID_TYPIST FROM CZ_MA_WORKFLOWH WHERE CD_COMPANY = @P_CD_COMPANY AND TP_STEP = '01' AND NO_KEY = @P_NO_KEY) END),
	ID_PUR = (CASE WHEN @P_TP_STEP = '08' THEN @P_ID_PUR ELSE (SELECT ID_PUR FROM CZ_MA_WORKFLOWH WHERE CD_COMPANY = @P_CD_COMPANY AND TP_STEP = '08' AND NO_KEY = @P_NO_KEY) END),
	ID_LOG = (CASE WHEN @P_TP_STEP = '08' THEN @P_ID_LOG ELSE (SELECT ID_LOG FROM CZ_MA_WORKFLOWH WHERE CD_COMPANY = @P_CD_COMPANY AND TP_STEP = '08' AND NO_KEY = @P_NO_KEY) END),
	DC_RMK = @P_DC_RMK,
	UPDATE_HIST = 'SP_CZ_SA_INQ_REGH_U',
	ID_UPDATE = @P_ID_UPDATE,
	DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE())
WHERE CD_COMPANY = @P_CD_COMPANY
AND TP_STEP = @P_TP_STEP
AND NO_KEY = @P_NO_KEY

IF @P_TP_STEP = '01'
BEGIN
	UPDATE CZ_MA_WORKFLOWH 
	SET TP_SALES = @P_TP_SALES,
		ID_SALES = @P_ID_SALES,
		ID_TYPIST = @P_ID_TYPIST,
		DC_RMK = @P_DC_RMK,
		UPDATE_HIST = 'SP_CZ_SA_INQ_REGH_U',
		ID_UPDATE = @P_ID_UPDATE,
		DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE())
	WHERE CD_COMPANY = @P_CD_COMPANY
	AND TP_STEP = '02'
	AND NO_KEY = @P_NO_KEY
END

GO