USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_INQ_REG_DEFAULT]    Script Date: 2018-05-29 오후 2:51:03 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER PROCEDURE [NEOE].[SP_CZ_SA_INQ_REG_DEFAULT]
(
	@P_CD_COMPANY       NVARCHAR(7),
	@P_ID_USER			NVARCHAR(15)
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

DECLARE @V_TP_SALES NVARCHAR(MAX),
		@V_ID_SALES NVARCHAR(MAX),
		@V_ID_PUR NVARCHAR(MAX),
		@V_ID_LOG NVARCHAR(MAX)

SELECT @V_TP_SALES = TP_SALES,
	   @V_ID_SALES = ID_SALES,
	   @V_ID_PUR = ID_PUR,
	   @V_ID_LOG = ID_LOG
FROM CZ_SA_USER
WHERE CD_COMPANY = @P_CD_COMPANY
AND ID_USER = @P_ID_USER

SELECT TP_SALES,
       TP_SALES_DEF,
       ID_SALES,
       ID_SALES_DEF,
       ID_TYPIST_DEF,
       ID_PUR,
       ID_PUR_DEF,
       ID_LOG, 
       ID_LOG_DEF,
	   TP_BIZ
FROM CZ_SA_USER
WHERE CD_COMPANY = @P_CD_COMPANY
AND ID_USER = @P_ID_USER

SELECT MC.CD_SYSDEF AS CODE,
	   MC.NM_SYSDEF AS NAME 
FROM GETTABLEFROMSPLIT(@V_TP_SALES) A
JOIN MA_CODEDTL MC ON MC.CD_COMPANY = @P_CD_COMPANY AND MC.CD_FIELD = 'CZ_SA00023' AND MC.CD_SYSDEF = A.CD_STR
ORDER BY NAME

SELECT MU.ID_USER AS CODE,
	   MU.NM_USER AS NAME
FROM GETTABLEFROMSPLIT(@V_ID_SALES) A
JOIN MA_USER MU ON MU.CD_COMPANY = @P_CD_COMPANY AND MU.ID_USER = A.CD_STR
JOIN MA_EMP ME ON ME.CD_COMPANY = MU.CD_COMPANY AND ME.NO_EMP = MU.NO_EMP
WHERE ISNULL(ME.DT_RETIRE, '00000000') = '00000000'
ORDER BY NAME

SELECT MU.ID_USER AS CODE,
	   MU.NM_USER AS NAME
FROM GETTABLEFROMSPLIT(@V_ID_PUR) A
JOIN MA_USER MU ON MU.CD_COMPANY = @P_CD_COMPANY AND MU.ID_USER = A.CD_STR
JOIN MA_EMP ME ON ME.CD_COMPANY = MU.CD_COMPANY AND ME.NO_EMP = MU.NO_EMP
WHERE ISNULL(ME.DT_RETIRE, '00000000') = '00000000'
ORDER BY NAME

SELECT MU.ID_USER AS CODE,
	   MU.NM_USER AS NAME
FROM GETTABLEFROMSPLIT(@V_ID_LOG) A
JOIN MA_USER MU ON MU.CD_COMPANY = @P_CD_COMPANY AND MU.ID_USER = A.CD_STR
JOIN MA_EMP ME ON ME.CD_COMPANY = MU.CD_COMPANY AND ME.NO_EMP = MU.NO_EMP
WHERE ISNULL(ME.DT_RETIRE, '00000000') = '00000000'
ORDER BY NAME

GO

