USE [NEOE]
GO
/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_INQ_REGH_I]    Script Date: 2015-07-03 오후 8:00:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


ALTER PROCEDURE [NEOE].[SP_CZ_SA_INQ_REGH_I]
(
	@P_CD_COMPANY	NVARCHAR(7),
	@P_TP_STEP		NVARCHAR(3),
	@P_NO_KEY		NVARCHAR(20),
	@P_TP_SALES		NVARCHAR(2),
	@P_ID_SALES		NVARCHAR(15),
	@P_ID_TYPIST	NVARCHAR(15),
	@P_ID_PUR		NVARCHAR(15),
	@P_ID_LOG		NVARCHAR(15),
	@P_DC_RMK		NVARCHAR(MAX),
	@P_ID_INSERT	NVARCHAR(15)
) 
AS	

IF ISNULL(@P_NO_KEY, '') = '' OR (@P_NO_KEY NOT LIKE 'ZB%' AND LEN(@P_NO_KEY) < 8)
BEGIN
	DECLARE @V_DC_MSG NVARCHAR(500)
	SET @V_DC_MSG = '[SP_CZ_SA_INQ_REGH_I] 파일번호가 잘못 되었습니다.' + ' [파일번호 : ' + ISNULL(@P_NO_KEY, '') + ', 비고 : ' + ISNULL(@P_DC_RMK, '') + ']'

	RAISERROR(@V_DC_MSG, 16, 1)
	RETURN
END

IF NOT EXISTS(SELECT * FROM CZ_MA_WORKFLOWH WHERE CD_COMPANY = @P_CD_COMPANY AND TP_STEP = @P_TP_STEP AND NO_KEY = @P_NO_KEY)
BEGIN
	INSERT INTO CZ_MA_WORKFLOWH 
	(
		CD_COMPANY,
		TP_STEP,	
		NO_KEY,		
		TP_SALES,	
		ID_SALES,	
		ID_TYPIST,
		ID_PUR,		
		ID_LOG,
		YN_DONE,		
		DC_RMK,
		INSERT_HIST,
		ID_INSERT,
		DTS_INSERT
	)
	VALUES 
	(
		@P_CD_COMPANY,
		@P_TP_STEP,		
		@P_NO_KEY,		
		(CASE WHEN @P_TP_STEP = '01' THEN @P_TP_SALES ELSE (SELECT TP_SALES FROM CZ_MA_WORKFLOWH WHERE CD_COMPANY = @P_CD_COMPANY AND TP_STEP = '01' AND NO_KEY = @P_NO_KEY) END),		
		(CASE WHEN @P_TP_STEP = '01' THEN @P_ID_SALES ELSE (SELECT ID_SALES FROM CZ_MA_WORKFLOWH WHERE CD_COMPANY = @P_CD_COMPANY AND TP_STEP = '01' AND NO_KEY = @P_NO_KEY) END),		
		(CASE WHEN @P_TP_STEP = '01' THEN @P_ID_TYPIST ELSE (SELECT ID_TYPIST FROM CZ_MA_WORKFLOWH WHERE CD_COMPANY = @P_CD_COMPANY AND TP_STEP = '01' AND NO_KEY = @P_NO_KEY) END),
		(CASE WHEN @P_TP_STEP = '08' THEN @P_ID_PUR ELSE (SELECT ID_PUR FROM CZ_MA_WORKFLOWH WHERE CD_COMPANY = @P_CD_COMPANY AND TP_STEP = '08' AND NO_KEY = @P_NO_KEY) END),
		(CASE WHEN @P_TP_STEP = '08' THEN (CASE WHEN @P_CD_COMPANY = 'K100' THEN (SELECT CD_FLAG1 FROM V_CZ_SA_QTN_LOG_EMP WHERE CD_COMPANY = @P_CD_COMPANY AND NO_FILE = @P_NO_KEY) 
																			ELSE @P_ID_LOG END) 
									 ELSE (SELECT ID_LOG FROM CZ_MA_WORKFLOWH WHERE CD_COMPANY = @P_CD_COMPANY AND TP_STEP = '08' AND NO_KEY = @P_NO_KEY) END),
		'N',		
		@P_DC_RMK,
		'SP_CZ_SA_INQ_REGH_I',
		@P_ID_INSERT,
		NEOE.SF_SYSDATE(GETDATE()) 	
	)
END
ELSE
BEGIN
	UPDATE CZ_MA_WORKFLOWH 
	SET ID_SALES = (CASE WHEN @P_TP_STEP = '01' THEN @P_ID_SALES ELSE (SELECT ID_SALES FROM CZ_MA_WORKFLOWH WHERE CD_COMPANY = @P_CD_COMPANY AND TP_STEP = '01' AND NO_KEY = @P_NO_KEY) END),
		ID_TYPIST = (CASE WHEN @P_TP_STEP = '01' THEN @P_ID_TYPIST ELSE (SELECT ID_TYPIST FROM CZ_MA_WORKFLOWH WHERE CD_COMPANY = @P_CD_COMPANY AND TP_STEP = '01' AND NO_KEY = @P_NO_KEY) END),
		ID_PUR = (CASE WHEN @P_TP_STEP = '08' THEN @P_ID_PUR ELSE (SELECT ID_PUR FROM CZ_MA_WORKFLOWH WHERE CD_COMPANY = @P_CD_COMPANY AND TP_STEP = '08' AND NO_KEY = @P_NO_KEY) END),
		ID_LOG = (CASE WHEN @P_TP_STEP = '08' THEN (CASE WHEN @P_CD_COMPANY = 'K100' THEN (SELECT CD_FLAG1 FROM V_CZ_SA_QTN_LOG_EMP WHERE CD_COMPANY = @P_CD_COMPANY AND NO_FILE = @P_NO_KEY) 
																					 ELSE @P_ID_LOG END) 
											  ELSE (SELECT ID_LOG FROM CZ_MA_WORKFLOWH WHERE CD_COMPANY = @P_CD_COMPANY AND TP_STEP = '08' AND NO_KEY = @P_NO_KEY) END),
		DC_RMK = @P_DC_RMK,
		UPDATE_HIST = 'SP_CZ_SA_INQ_REGH_I',
		ID_UPDATE = @P_ID_INSERT,
		DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE())
	WHERE CD_COMPANY = @P_CD_COMPANY
	AND TP_STEP = @P_TP_STEP
	AND NO_KEY = @P_NO_KEY
END

IF @P_TP_STEP = '01'
BEGIN
	EXEC SP_CZ_MA_WORKFLOW_NEXT_STEP @P_CD_COMPANY, '02', @P_NO_KEY, @P_ID_INSERT, @P_DC_RMK
END
ELSE IF @P_TP_STEP = '04'
BEGIN
	EXEC SP_CZ_MA_WORKFLOW_NEXT_STEP @P_CD_COMPANY, @P_TP_STEP, @P_NO_KEY, @P_ID_INSERT, ''

	IF EXISTS (SELECT 1 FROM CZ_MA_WORKFLOWH WHERE CD_COMPANY = @P_CD_COMPANY AND TP_STEP = '03' AND NO_KEY = @P_NO_KEY AND YN_DONE = 'N')
	BEGIN
		EXEC SP_CZ_MA_WORKFLOW_DONE @P_CD_COMPANY, '03', @P_NO_KEY, @P_ID_INSERT
	END

	IF EXISTS(SELECT 1 FROM CZ_SA_QTNH WHERE CD_COMPANY = @P_CD_COMPANY AND NO_FILE = @P_NO_KEY AND ISNULL(YN_CLOSE, 'N') = 'Y')
	BEGIN
		UPDATE CZ_SA_QTNH
		SET YN_CLOSE = 'N'
		WHERE CD_COMPANY = @P_CD_COMPANY
		AND NO_FILE = @P_NO_KEY
		
		EXEC SP_CZ_MA_WORKFLOW_DONE @P_CD_COMPANY, '07', @P_NO_KEY, @P_ID_INSERT
	END
END
ELSE IF @P_TP_STEP = '08'
BEGIN
	EXEC SP_CZ_MA_WORKFLOW_NEXT_STEP @P_CD_COMPANY, @P_TP_STEP, @P_NO_KEY, @P_ID_INSERT, ''
END

GO