USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_INQ_REGL_U]    Script Date: 2015-07-06 오전 9:21:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER PROCEDURE [NEOE].[SP_CZ_SA_INQ_REGL_U]
(
	@P_CD_COMPANY       NVARCHAR(7),
	@P_TP_STEP          NVARCHAR(3),
	@P_NO_KEY			NVARCHAR(20),
	@P_NO_LINE          INT,
	@P_NM_FILE			NVARCHAR(MAX),
	@P_NM_FILE_REAL		NVARCHAR(MAX),
	@P_CD_SUPPLIER		NVARCHAR(20),
	@P_YN_PARSING		NVARCHAR(1),
	@P_ID_UPDATE		NVARCHAR(15)
) AS	

UPDATE CZ_MA_WORKFLOWL 
SET NM_FILE = @P_NM_FILE,
	NM_FILE_REAL = @P_NM_FILE_REAL,
	CD_SUPPLIER = @P_CD_SUPPLIER,
	YN_PARSING = @P_YN_PARSING,
	ID_UPDATE = @P_ID_UPDATE,
	DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE())
WHERE CD_COMPANY = @P_CD_COMPANY
AND TP_STEP = @P_TP_STEP
AND NO_KEY = @P_NO_KEY
AND NO_LINE = @P_NO_LINE

GO