USE [NEOE]
GO
/****** Object:  StoredProcedure [NEOE].[CZ_MAILBAGLIST_DL]    Script Date: 2023-05-03 오후 4:45:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--작성삭제용
ALTER PROCEDURE [NEOE].[CZ_MAILBAGLIST_DL]
(
	@P_CD_SEND		NVARCHAR(2),
	@P_DT_ACCT		NVARCHAR(14),
	@P_SEQ			NUMERIC(3,0)
)  
AS
   
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

DELETE CZ_MAILBAGLIST_L
WHERE CD_SEND = @P_CD_SEND
AND DT_ACCT	= @P_DT_ACCT
AND SEQ = @P_SEQ