USE [NEOE]
GO
/****** Object:  StoredProcedure [NEOE].[CZ_MAILBAGLIST_IL]    Script Date: 2023-05-03 ¿ÀÈÄ 4:45:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[CZ_MAILBAGLIST_IL]
(
	@P_CD_SEND			NVARCHAR(2),
	@P_DT_ACCT			NVARCHAR(14),
	@P_SEQ				NUMERIC(3,0),
	@P_NM_ITEM			NVARCHAR(MAX),
	@P_QT				NUMERIC(3,0),
	@P_NO_EMP_SEND		NVARCHAR(15),
	@P_NO_EMP_RECEIVE	NVARCHAR(15),
	@P_NO_EMP_INSPECT	NVARCHAR(15),
	@P_DC_RMK			NVARCHAR(MAX),
	@P_DTS_INSERT		NVARCHAR(14),
	@P_ID_INSERT		NVARCHAR(15)
)  
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

INSERT CZ_MAILBAGLIST_L
(
	CD_SEND,
	DT_ACCT,
	SEQ,
	NM_ITEM,
	QT,
	NO_EMP_SEND,
	NO_EMP_RECEIVE,
	NO_EMP_INSPECT,
	DC_RMK,
	DTS_INSERT,
	ID_INSERT
)
VALUES
(
	@P_CD_SEND,
	@P_DT_ACCT,
	@P_SEQ,
	@P_NM_ITEM,
	@P_QT,
	@P_NO_EMP_SEND,
	@P_NO_EMP_RECEIVE,
	@P_NO_EMP_INSPECT,
	@P_DC_RMK,
	@P_DTS_INSERT,
	@P_ID_INSERT
)
