USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_FI_VAT_MNG_S]    Script Date: 2015-08-12 오후 3:03:52 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_FI_IMP_PMT_MNGH_S] 
(
	@P_CD_COMPANY		NVARCHAR(7),
	@P_TP_DATE			NVARCHAR(4),
	@P_DT_FROM			NVARCHAR(8),
	@P_DT_TO			NVARCHAR(8),
	@P_NO_IMPORT		NVARCHAR(20),
	@P_NO_SO			NVARCHAR(20),
	@P_NO_BL			NVARCHAR(20),
	@P_NO_EMP			NVARCHAR(10),
	@P_NO_IMO			NVARCHAR(10),
	@P_CD_SUPPLIER		NVARCHAR(20),
	@P_YN_RETURN		NVARCHAR(3) -- 001 : 전체, 002 : 환급, 003 : 미환급
) 
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT 'N' AS S,
	   IH.NO_IMPORT,
	   IH.DT_IMPORT,
	   IH.DT_LIMIT,
	   IH.DT_APPLICATION,
	   IH.DT_RETURN,
	   IL.DT_IO,
	   IL.AM_EX,
	   IL.AM,
	   IL.AM_TAX,
	   ISNULL(IH.AM_VAT_BASE, 0) AS AM_VAT_BASE,
	   ISNULL(IH.AM_VAT, 0) AS AM_VAT,
	   IL.AM_RETURN,
	   IH.NO_EMP,
	   ME.NM_KOR AS NM_EMP,
	   IL.NM_GIR,
	   MF.NAME + '(' + MF.CNT + ')' AS FILE_PATH_MNG,
	   IH.DC_RMK,
	   IH.NO_BL,
	   IH.DC_FREIGHT,
	   IH.CD_PAYMENT,
	   MP.LN_PARTNER AS NM_PAYMENT,
	   IH.NO_PAYMENT,
	   FD.NO_DOCU AS NO_PAYMENT_DOCU,
	   IL.NO_SO,
	   ME1.NM_KOR AS NM_EMP_SALE,
	   (SELECT STRING_AGG(MP.LN_PARTNER, ',') 
	    FROM (SELECT MP.LN_PARTNER
			  FROM CZ_FI_IMP_PMTL IL
	          LEFT JOIN PU_POH PH ON PH.CD_COMPANY = IL.CD_COMPANY AND PH.NO_PO = IL.NO_PO
		      LEFT JOIN MA_PARTNER MP ON MP.CD_COMPANY = PH.CD_COMPANY AND MP.CD_PARTNER = PH.CD_PARTNER
		      WHERE IL.CD_COMPANY = IH.CD_COMPANY
		      AND IL.NO_IMPORT = IH.NO_IMPORT
	          GROUP BY MP.LN_PARTNER) MP) AS NM_SUPPLIER
FROM CZ_FI_IMP_PMTH IH
JOIN (SELECT IL.CD_COMPANY, 
	  		 IL.NO_IMPORT,
			 MAX(IL.NO_SO) AS NO_SO,
			 MAX(SH.NO_EMP) AS NO_EMP,
			 MAX(OL.NM_GIR) AS NM_GIR,
			 ISNULL(MAX(OL.DT_IO), '') AS DT_IO,
	  		 ISNULL(SUM(IL.AM_EX), 0) AS AM_EX, 
	  		 ISNULL(SUM(IL.AM), 0) AS AM, 
	         ISNULL(SUM(IL.AM_TAX), 0) AS AM_TAX,
	  		 ISNULL(SUM(IL.AM_RETURN), 0) AS AM_RETURN
	  FROM CZ_FI_IMP_PMTL IL
	  LEFT JOIN SA_SOH SH ON SH.CD_COMPANY = IL.CD_COMPANY AND SH.NO_SO = IL.NO_SO
	  LEFT JOIN PU_POH PH ON PH.CD_COMPANY = IL.CD_COMPANY AND PH.NO_PO = IL.NO_PO
	  LEFT JOIN (SELECT OL.CD_COMPANY, OL.NO_PSO_MGMT, OL.NO_PSOLINE_MGMT, 
	  			 	    MAX(OL.DT_IO) AS DT_IO,
						MAX(ME.NM_KOR) AS NM_GIR
	  			 FROM MM_QTIO OL
				 LEFT JOIN SA_GIRL GL ON GL.CD_COMPANY = OL.CD_COMPANY AND GL.NO_GIR = OL.NO_ISURCV AND GL.SEQ_GIR = OL.NO_ISURCVLINE
				 LEFT JOIN SA_GIRH GH ON GH.CD_COMPANY = GL.CD_COMPANY AND GH.NO_GIR = GL.NO_GIR
				 LEFT JOIN MA_EMP ME ON ME.CD_COMPANY = GH.CD_COMPANY AND ME.NO_EMP = GH.NO_EMP
	  			 WHERE OL.FG_PS = '2'
	  			 GROUP BY OL.CD_COMPANY, OL.NO_PSO_MGMT, OL.NO_PSOLINE_MGMT) OL 
	  ON OL.CD_COMPANY = IL.CD_COMPANY AND OL.NO_PSO_MGMT = IL.NO_SO AND OL.NO_PSOLINE_MGMT = IL.NO_SOLINE
	  WHERE (ISNULL(@P_NO_SO, '') = '' OR IL.NO_SO = @P_NO_SO)
	  AND (ISNULL(@P_NO_EMP, '') = '' OR SH.NO_EMP = @P_NO_EMP)
	  AND (ISNULL(@P_NO_IMO, '') = '' OR SH.NO_IMO = @P_NO_IMO)
	  AND (ISNULL(@P_CD_SUPPLIER, '') = '' OR PH.CD_PARTNER = @P_CD_SUPPLIER)
	  GROUP BY IL.CD_COMPANY, IL.NO_IMPORT) IL
ON IL.CD_COMPANY = IH.CD_COMPANY AND IL.NO_IMPORT = IH.NO_IMPORT
LEFT JOIN MA_PARTNER MP ON MP.CD_COMPANY = IH.CD_COMPANY AND MP.CD_PARTNER = IH.CD_PAYMENT
LEFT JOIN MA_EMP ME ON ME.CD_COMPANY = IH.CD_COMPANY AND ME.NO_EMP = IH.NO_EMP
LEFT JOIN MA_EMP ME1 ON ME1.CD_COMPANY = IL.CD_COMPANY AND ME1.NO_EMP = IL.NO_EMP
LEFT JOIN (SELECT CD_COMPANY, NO_MDOCU,
		   		  MAX(NO_DOCU) AS NO_DOCU 
		   FROM FI_DOCU
		   WHERE NO_MODULE = 'D03'
		   GROUP BY CD_COMPANY, NO_MDOCU) FD 
ON FD.CD_COMPANY = IH.CD_COMPANY AND FD.NO_MDOCU = IH.NO_PAYMENT
LEFT JOIN (SELECT CD_COMPANY,
				  CD_FILE,
				  MAX(FILE_NAME) AS NAME,
				  CONVERT(VARCHAR, COUNT(1)) AS CNT 
		   FROM MA_FILEINFO
		   WHERE CD_MODULE = 'FI'
		   AND ID_MENU = 'P_CZ_FI_IMP_PMT_MNG'
		   GROUP BY CD_COMPANY, CD_MODULE, ID_MENU, CD_FILE) MF 
ON MF.CD_COMPANY = IH.CD_COMPANY AND MF.CD_FILE = IH.NO_IMPORT + '_' + IH.CD_COMPANY
WHERE IH.CD_COMPANY = @P_CD_COMPANY
AND ((@P_TP_DATE = '001' AND IH.DT_IMPORT BETWEEN @P_DT_FROM AND @P_DT_TO) OR
	 (@P_TP_DATE = '002' AND IH.DT_RETURN BETWEEN @P_DT_FROM AND @P_DT_TO))
AND (ISNULL(@P_NO_IMPORT, '') = '' OR IH.NO_IMPORT = REPLACE(@P_NO_IMPORT, '-', ''))
AND (ISNULL(@P_NO_BL, '') = '' OR IH.NO_BL = @P_NO_BL)
AND (@P_YN_RETURN = '001' OR 
    (@P_YN_RETURN = '002' AND ISNULL(IH.DT_RETURN, '') <> '') OR 
	(@P_YN_RETURN = '003' AND ISNULL(IH.DT_RETURN, '') = ''))

GO