USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_FI_TAX_REG_U]    Script Date: 2015-08-11 오전 11:18:27 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_FI_IMP_PMT_MNGH_U] 
(
	@P_CD_COMPANY		NVARCHAR(7),
	@P_NO_IMPORT		NVARCHAR(14),
	@P_NO_BL			NVARCHAR(20),
	@P_DT_APPLICATION	NVARCHAR(8),
	@P_DT_RETURN		NVARCHAR(8),
	@P_DC_FREIGHT		NVARCHAR(100),
	@P_CD_PAYMENT		NVARCHAR(20),
	@P_DT_LIMIT			NVARCHAR(8),
	@P_AM_VAT_BASE		NUMERIC(17, 4),
	@P_AM_VAT			NUMERIC(17, 4),
	@P_DC_RMK			NVARCHAR(100),
	@P_ID_UPDATE		NVARCHAR(15)
) 
AS

UPDATE CZ_FI_IMP_PMTH
SET DT_APPLICATION = @P_DT_APPLICATION,
	DT_RETURN = @P_DT_RETURN,
	DT_LIMIT = @P_DT_LIMIT,
	CD_PAYMENT = @P_CD_PAYMENT,
	NO_BL = @P_NO_BL,
	AM_VAT_BASE = @P_AM_VAT_BASE,
	AM_VAT = @P_AM_VAT,
	DC_FREIGHT = @P_DC_FREIGHT,
	DC_RMK = @P_DC_RMK,
	ID_UPDATE = @P_ID_UPDATE,
	DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE())
WHERE CD_COMPANY = @P_CD_COMPANY
AND NO_IMPORT = @P_NO_IMPORT

GO