USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_PU_IMPORT_DECLARATIONL_S]    Script Date: 2015-08-12 오후 3:03:52 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_PU_IMPORT_DECLARATIONL_S] 
(
	@P_CD_COMPANY		NVARCHAR(7),
	@P_NO_IMPORT		NVARCHAR(30)
) 
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT IL.NO_IMPORT,
       IL.SEQ,
       IL.NO_RAN,
       IL.NO_DSP,
       IL.MODEL,
       IL.QT,
       IL.UM,
       IL.AM,
       IL.HSCODE,
       IL.NET_WEIGHT,
       IL.TAXABLE_USD,
       IL.TAXABLE_KRW,
       IL.CUSTOMS,
       IL.VAT,
       IL.ORIGIN,
       IL.NO_PO,
       IL.NO_LINE
FROM CZ_PU_IMPORT_DECLARATIONL IL
WHERE IL.CD_COMPANY = @P_CD_COMPANY
AND IL.NO_IMPORT = @P_NO_IMPORT

GO