USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[UP_SA_TRCREDITSCH1_S]    Script Date: 2016-01-14 오전 11:34:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[UP_SA_TRCREDITSCH1_S]
( 
	@CD_COMPANY			NVARCHAR(7),
	@DT_PROCESS_FROM	NVARCHAR(8),
	@DT_PROCESS_TO		NVARCHAR(8),
	@CD_PARTNER			NVARCHAR(20),
	@DT_TODAY			NVARCHAR(8),
	@CD_DEPT			NVARCHAR(4000),
	@NO_EMP				NVARCHAR(20),
	@BILL_PARTNER		NVARCHAR(20),
	@CHK_AM_MISU		NVARCHAR(1)
)
AS

DECLARE @V_SERVER_KEY   VARCHAR(50)  
        
SELECT  @V_SERVER_KEY = SERVER_KEY  
FROM    CM_SERVER_CONFIG  
WHERE   YN_UPGRADE = 'Y'  

--SELECT	A.S,            
--		A.NO_IV,
--		A.CD_COMPANY,
--		A.CD_PARTNER,
--		A.DT_PROCESS,
--		A.BILL_PARTNER,
--		A.AM,
--		A.AM_BAN,
--		A.AM_MISU,
--		A.NM_PARTNER,
--		A.BILL_NM_PARTNER,
--		A.DT_RCP_RSV,
--		A.DT,
--		MD.NM_DEPT,
--		A.NM_EMP,
--		A.MEMO_CD,
--		A.GUBUN,
--		A.AM_EX,
--		A.RT_EXCH,
--		A.CD_EXCH,
--		A.AM_BAN_EX,
--		A.AM_MISU_EX
--FROM	(              
--		SELECT	'N' S, --국내
--				A.NO_IV,
--				A.CD_COMPANY,
--				A.CD_PARTNER,
--				A.DT_PROCESS,
--				A.BILL_PARTNER,
--				(A.AM_K+A.VAT_TAX) AS AM,
--				A.AM_BAN,
--				(A.AM_K+A.VAT_TAX-A.AM_BAN) AS AM_MISU,
--				E.LN_PARTNER NM_PARTNER,
--				F.LN_PARTNER BILL_NM_PARTNER,
--				A.DT_RCP_RSV,
--				DATEDIFF(DAY, A.DT_RCP_RSV, @DT_TODAY) AS DT,
--				M.CD_DEPT,
--				M.NM_KOR AS NM_EMP,
--				A.MEMO_CD,
--				'국내' GUBUN,
--				A.AM_EX,
--				A.RT_EXCH,
--				A.CD_EXCH,
--				A.AM_BAN_EX,
--				A.AM_EX - A.AM_BAN_EX AM_MISU_EX 
--		FROM	SA_IVH A
--		LEFT OUTER JOIN MA_PARTNER E ON A.CD_COMPANY = E.CD_COMPANY AND A.CD_PARTNER = E.CD_PARTNER
--		LEFT OUTER JOIN MA_PARTNER F ON A.CD_COMPANY = F.CD_COMPANY AND A.BILL_PARTNER = F.CD_PARTNER
--		LEFT OUTER JOIN MA_EMP     M ON A.CD_COMPANY = M.CD_COMPANY AND A.NO_EMP = M.NO_EMP
--		WHERE	A.CD_COMPANY = @CD_COMPANY
--		AND		A.DT_PROCESS BETWEEN @DT_PROCESS_FROM AND @DT_PROCESS_TO
--		AND		(A.CD_PARTNER = @CD_PARTNER OR @CD_PARTNER = '' OR @CD_PARTNER IS NULL)
--		AND		(A.NO_EMP = @NO_EMP OR @NO_EMP = '' OR @NO_EMP IS NULL)
--		AND		(M.CD_DEPT IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@CD_DEPT)) OR @CD_DEPT = '' OR @CD_DEPT IS NULL)
--		AND		(A.BILL_PARTNER = @BILL_PARTNER OR @BILL_PARTNER = '' OR @BILL_PARTNER IS NULL)

--		UNION  ALL

--		SELECT	'N' S, --해외
--				A.NO_BL AS NO_IV,
--				A.CD_COMPANY,
--				A.CD_PARTNER,
--				A.DT_BALLOT AS DT_PROCESS,
--				A.CD_PARTNER AS BILL_PARTNER,
--				CASE WHEN A.YN_RETURN = 'Y' THEN - A.AM ELSE A.AM END AS AM,
--				CASE WHEN A.YN_RETURN = 'Y' THEN - A.AM_NEGO ELSE A.AM_NEGO END AS AM_BAN,
--			   (CASE WHEN A.YN_RETURN = 'Y' THEN - A.AM ELSE A.AM END)- (CASE WHEN A.YN_RETURN = 'Y' THEN - A.AM_NEGO ELSE A.AM_NEGO END) AM_MISU,
--				--A.AM_EXNEGO AS AM_BAN,
--				--(A.AM - A.AM_EXNEGO) AS AM_MISU,
--				E.LN_PARTNER NM_PARTNER,
--				F.LN_PARTNER BILL_NM_PARTNER,
--				A.DT_PAYABLE AS DT_RCP_RSV,
--				DATEDIFF(DAY, A.DT_PAYABLE, @DT_TODAY) AS DT,
--				M.CD_DEPT,
--				M.NM_KOR AS NM_EMP,
--				A.MEMO_CD,
--				'해외' GUBUN,
--				CASE WHEN A.YN_RETURN = 'Y' THEN - A.AM_EX ELSE A.AM_EX END AS AM_EX,
--				A.RT_EXCH,
--				A.CD_EXCH,
--				A.AM_EXNEGO AM_BAN_EX,
--				A.AM_EX - A.AM_EXNEGO AM_MISU_EX
--		FROM  TR_EXBL A
--		LEFT OUTER JOIN MA_PARTNER E ON A.CD_COMPANY = E.CD_COMPANY AND A.CD_PARTNER = E.CD_PARTNER
--		LEFT OUTER JOIN MA_PARTNER F ON A.CD_COMPANY = F.CD_COMPANY AND A.CD_PARTNER = F.CD_PARTNER
--		LEFT OUTER JOIN MA_EMP     M ON A.CD_COMPANY = M.CD_COMPANY AND A.NO_EMP = M.NO_EMP
--		WHERE	A.CD_COMPANY = @CD_COMPANY
--		AND		A.DT_BALLOT BETWEEN @DT_PROCESS_FROM AND @DT_PROCESS_TO
--		AND		(A.CD_PARTNER = @CD_PARTNER OR @CD_PARTNER = '' OR @CD_PARTNER IS NULL)
--		AND		(A.NO_EMP = @NO_EMP OR @NO_EMP = '' OR @NO_EMP IS NULL)
--		AND		(M.CD_DEPT IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@CD_DEPT)) OR @CD_DEPT = '' OR @CD_DEPT IS NULL)
--		AND		(A.CD_PARTNER = @BILL_PARTNER OR @BILL_PARTNER = '' OR @BILL_PARTNER IS NULL)
		
--       UNION ALL
       
--       SELECT 'N' S,
--              '기초채권' NO_IV,
--              X.CD_COMPANY, 
--              X.CD_PARTNER,
--              CONVERT(NVARCHAR(8),DATEADD(DAY, -1, @DT_PROCESS_FROM),112) DT_PROCESS,
--              '' BILL_PARTNER,
--              SUM(X.AM_IV) AM,
--              SUM(X.AM_RCP) AM_BAN,
--              SUM(X.AM_IV) - SUM(X.AM_RCP) AM_MISU, 
--              E.LN_PARTNER NM_PARTNER,
--              '' BILL_NM_PARTNER,
--              '' DT_RCP_RSV,
--              NULL DT,
--              '' CD_DEPT,
--              '' NM_EMP,
--              '' MEMO_CD,
--              '' GUBUN,
--              NULL AM_EX,
--              NULL RT_EXCH,
--              '000' CD_EXCH,
--              NULL AM_BAN_EX,
--              NULL AM_MISU_EX
--       FROM(
--             SELECT CD_COMPANY,  
--                    CD_PARTNER,  
--                    AM_IV,   
--                    AM_RCP  
--             FROM   SA_AR      
--             WHERE  CD_COMPANY = @CD_COMPANY        
--             AND   YYMM >= LEFT(@DT_PROCESS_FROM, 4) + '00'    
--             AND   YYMM < LEFT(@DT_PROCESS_FROM, 6)   
--             AND  (CD_PARTNER = @CD_PARTNER OR @CD_PARTNER = '' OR @CD_PARTNER IS NULL)
--             AND  (CD_PARTNER = @BILL_PARTNER OR @BILL_PARTNER = '' OR @BILL_PARTNER IS NULL)
             
--             UNION ALL      
           
--             SELECT CD_COMPANY,   
--                    CD_PARTNER,       
--                    AM_IV,       
--                    AM_RCP   
--             FROM   SA_ARD      
--             WHERE  CD_COMPANY = @CD_COMPANY   
--             AND    DT_AR >= LEFT(@DT_PROCESS_FROM, 6) + '01'   
--             AND    DT_AR < @DT_PROCESS_FROM    
--             AND   (CD_PARTNER = @CD_PARTNER OR @CD_PARTNER = '' OR @CD_PARTNER IS NULL)
--             AND   (CD_PARTNER = @BILL_PARTNER OR @BILL_PARTNER = '' OR @BILL_PARTNER IS NULL) 
--             )X
--             LEFT OUTER JOIN MA_PARTNER E ON X.CD_COMPANY = E.CD_COMPANY AND X.CD_PARTNER = E.CD_PARTNER
--         WHERE @V_SERVER_KEY = 'ABOV' -- 그린칩스
--         GROUP BY X.CD_COMPANY, X.CD_PARTNER, E.LN_PARTNER 
--         ) A
--LEFT JOIN MA_DEPT MD ON A.CD_COMPANY = MD.CD_COMPANY AND A.CD_DEPT = MD.CD_DEPT
--WHERE(@CHK_AM_MISU = 'Y' OR (ISNULL(AM_MISU,0) <> 0 AND @CHK_AM_MISU = 'N'))           
--ORDER BY A.CD_PARTNER, A.DT_PROCESS

SELECT	A.S,            
		A.NO_IV,
		A.CD_COMPANY,
		A.CD_PARTNER,
		A.DT_PROCESS,
		A.BILL_PARTNER,
		A.AM,
		A.AM_BAN,
		A.AM_MISU,
		A.NM_PARTNER,
		A.BILL_NM_PARTNER,
		A.DT_RCP_RSV,
		A.DT,
		MD.NM_DEPT,
		A.NM_EMP,
		A.MEMO_CD,
		A.GUBUN,
		A.AM_EX,
		A.RT_EXCH,
		A.CD_EXCH,
		A.AM_BAN_EX,
		A.AM_MISU_EX
FROM	(              
		SELECT	'N' S, --국내
				(CASE WHEN ISNULL(A.DC_REMARK, '') = '' THEN A.NO_IV ELSE (A.NO_IV + '-' + A.DC_REMARK) END) AS NO_IV,
				A.CD_COMPANY,
				A.CD_PARTNER,
				A.DT_PROCESS,
				A.BILL_PARTNER,
				(A.AM_K+A.VAT_TAX) AS AM,
				A.AM_BAN,
				(A.AM_K+A.VAT_TAX-A.AM_BAN) AS AM_MISU,
				E.LN_PARTNER NM_PARTNER,
				F.LN_PARTNER BILL_NM_PARTNER,
				A.DT_RCP_RSV,
				DATEDIFF(DAY, A.DT_RCP_RSV, @DT_TODAY) AS DT,
				M.CD_DEPT,
				M.NM_KOR AS NM_EMP,
				A.MEMO_CD,
				'국내' GUBUN,
				A.AM_EX,
				A.RT_EXCH,
				A.CD_EXCH,
				A.AM_BAN_EX,
				A.AM_EX - A.AM_BAN_EX AM_MISU_EX 
		FROM	SA_IVH A
		LEFT OUTER JOIN (SELECT IL.CD_COMPANY, IL.NO_IV, MAX(SH.NO_EMP) AS NO_EMP
						 FROM SA_IVL IL
						 LEFT JOIN SA_SOH SH ON SH.CD_COMPANY = IL.CD_COMPANY AND SH.NO_SO = IL.NO_SO
						 GROUP BY IL.CD_COMPANY, IL.NO_IV) IL
		ON IL.CD_COMPANY = A.CD_COMPANY AND IL.NO_IV = A.NO_IV
		LEFT OUTER JOIN MA_PARTNER E ON A.CD_COMPANY = E.CD_COMPANY AND A.CD_PARTNER = E.CD_PARTNER
		LEFT OUTER JOIN MA_PARTNER F ON A.CD_COMPANY = F.CD_COMPANY AND A.BILL_PARTNER = F.CD_PARTNER
		LEFT OUTER JOIN MA_EMP     M ON IL.CD_COMPANY = M.CD_COMPANY AND IL.NO_EMP = M.NO_EMP
		WHERE	A.CD_COMPANY = @CD_COMPANY
		AND		A.DT_PROCESS BETWEEN @DT_PROCESS_FROM AND @DT_PROCESS_TO
		AND		(A.CD_PARTNER = @CD_PARTNER OR @CD_PARTNER = '' OR @CD_PARTNER IS NULL)
		AND		(A.NO_EMP = @NO_EMP OR @NO_EMP = '' OR @NO_EMP IS NULL)
		AND		(M.CD_DEPT IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@CD_DEPT)) OR @CD_DEPT = '' OR @CD_DEPT IS NULL)
		AND		(A.BILL_PARTNER = @BILL_PARTNER OR @BILL_PARTNER = '' OR @BILL_PARTNER IS NULL)

		UNION  ALL

		SELECT	'N' S, --해외
				A.NO_BL AS NO_IV,
				A.CD_COMPANY,
				A.CD_PARTNER,
				A.DT_BALLOT AS DT_PROCESS,
				A.CD_PARTNER AS BILL_PARTNER,
				CASE WHEN A.YN_RETURN = 'Y' THEN - A.AM ELSE A.AM END AS AM,
				CASE WHEN A.YN_RETURN = 'Y' THEN - A.AM_NEGO ELSE A.AM_NEGO END AS AM_BAN,
			   (CASE WHEN A.YN_RETURN = 'Y' THEN - A.AM ELSE A.AM END)- (CASE WHEN A.YN_RETURN = 'Y' THEN - A.AM_NEGO ELSE A.AM_NEGO END) AM_MISU,
				--A.AM_EXNEGO AS AM_BAN,
				--(A.AM - A.AM_EXNEGO) AS AM_MISU,
				E.LN_PARTNER NM_PARTNER,
				F.LN_PARTNER BILL_NM_PARTNER,
				A.DT_PAYABLE AS DT_RCP_RSV,
				DATEDIFF(DAY, A.DT_PAYABLE, @DT_TODAY) AS DT,
				M.CD_DEPT,
				M.NM_KOR AS NM_EMP,
				A.MEMO_CD,
				'해외' GUBUN,
				CASE WHEN A.YN_RETURN = 'Y' THEN - A.AM_EX ELSE A.AM_EX END AS AM_EX,
				A.RT_EXCH,
				A.CD_EXCH,
				A.AM_EXNEGO AM_BAN_EX,
				A.AM_EX - A.AM_EXNEGO AM_MISU_EX
		FROM  TR_EXBL A
		LEFT OUTER JOIN MA_PARTNER E ON A.CD_COMPANY = E.CD_COMPANY AND A.CD_PARTNER = E.CD_PARTNER
		LEFT OUTER JOIN MA_PARTNER F ON A.CD_COMPANY = F.CD_COMPANY AND A.CD_PARTNER = F.CD_PARTNER
		LEFT OUTER JOIN MA_EMP     M ON A.CD_COMPANY = M.CD_COMPANY AND A.NO_EMP = M.NO_EMP
		WHERE	A.CD_COMPANY = @CD_COMPANY
		AND		A.DT_BALLOT BETWEEN @DT_PROCESS_FROM AND @DT_PROCESS_TO
		AND		(A.CD_PARTNER = @CD_PARTNER OR @CD_PARTNER = '' OR @CD_PARTNER IS NULL)
		AND		(A.NO_EMP = @NO_EMP OR @NO_EMP = '' OR @NO_EMP IS NULL)
		AND		(M.CD_DEPT IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@CD_DEPT)) OR @CD_DEPT = '' OR @CD_DEPT IS NULL)
		AND		(A.CD_PARTNER = @BILL_PARTNER OR @BILL_PARTNER = '' OR @BILL_PARTNER IS NULL)
		
       UNION ALL
       
       SELECT 'N' S,
              '기초채권' NO_IV,
              X.CD_COMPANY, 
              X.CD_PARTNER,
              CONVERT(NVARCHAR(8),DATEADD(DAY, -1, @DT_PROCESS_FROM),112) DT_PROCESS,
              '' BILL_PARTNER,
              SUM(X.AM_IV) AM,
              SUM(X.AM_RCP) AM_BAN,
              SUM(X.AM_IV) - SUM(X.AM_RCP) AM_MISU, 
              E.LN_PARTNER NM_PARTNER,
              '' BILL_NM_PARTNER,
              '' DT_RCP_RSV,
              NULL DT,
              '' CD_DEPT,
              '' NM_EMP,
              '' MEMO_CD,
              '' GUBUN,
              NULL AM_EX,
              NULL RT_EXCH,
              '000' CD_EXCH,
              NULL AM_BAN_EX,
              NULL AM_MISU_EX
       FROM(
             SELECT CD_COMPANY,  
                    CD_PARTNER,  
                    AM_IV,   
                    AM_RCP  
             FROM   SA_AR      
             WHERE  CD_COMPANY = @CD_COMPANY        
             AND   YYMM >= LEFT(@DT_PROCESS_FROM, 4) + '00'    
             AND   YYMM < LEFT(@DT_PROCESS_FROM, 6)   
             AND  (CD_PARTNER = @CD_PARTNER OR @CD_PARTNER = '' OR @CD_PARTNER IS NULL)
             AND  (CD_PARTNER = @BILL_PARTNER OR @BILL_PARTNER = '' OR @BILL_PARTNER IS NULL)
             
             UNION ALL      
           
             SELECT CD_COMPANY,   
                    CD_PARTNER,       
                    AM_IV,       
                    AM_RCP   
             FROM   SA_ARD      
             WHERE  CD_COMPANY = @CD_COMPANY   
             AND    DT_AR >= LEFT(@DT_PROCESS_FROM, 6) + '01'   
             AND    DT_AR < @DT_PROCESS_FROM    
             AND   (CD_PARTNER = @CD_PARTNER OR @CD_PARTNER = '' OR @CD_PARTNER IS NULL)
             AND   (CD_PARTNER = @BILL_PARTNER OR @BILL_PARTNER = '' OR @BILL_PARTNER IS NULL) 
             )X
             LEFT OUTER JOIN MA_PARTNER E ON X.CD_COMPANY = E.CD_COMPANY AND X.CD_PARTNER = E.CD_PARTNER
         WHERE @V_SERVER_KEY = 'ABOV' -- 그린칩스
         GROUP BY X.CD_COMPANY, X.CD_PARTNER, E.LN_PARTNER 
         ) A
LEFT JOIN MA_DEPT MD ON A.CD_COMPANY = MD.CD_COMPANY AND A.CD_DEPT = MD.CD_DEPT
WHERE(@CHK_AM_MISU = 'Y' OR (ISNULL(AM_MISU,0) <> 0 AND @CHK_AM_MISU = 'N'))           
ORDER BY A.CD_PARTNER, A.DT_PROCESS

GO