USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_QU_INSP_SCHEDULE1_S]    Script Date: 2015-04-14 오전 8:31:11 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER PROCEDURE [NEOE].[SP_CZ_QU_INSP_SCHEDULE1_S]
(
	@P_CD_COMPANY		NVARCHAR(7),
	@P_DT_MONTH			NVARCHAR(6)
) 
AS
 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT CD_COMPANY,
	   NO_SO,
	   TP_COMPANY,
	   DT_INSP,
	   TP_INSP,
	   TP_CONTENTS,
	   TP_RESULT,
	   DC_RMK
FROM CZ_QU_INSP_SCHEDULE
WHERE CD_COMPANY = @P_CD_COMPANY
AND LEFT(DT_INSP, 6) = @P_DT_MONTH

GO