USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_QU_INSP_SCHEDULE_I]    Script Date: 2015-10-26 오후 7:48:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_QU_INSP_SCHEDULE_I] 
(
	@P_CD_COMPANY	NVARCHAR(7),
	@P_NO_SO		NVARCHAR(20),
	@P_ID_USER		NVARCHAR(10)
) 
AS 

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

IF NOT EXISTS (SELECT 1 
			   FROM CZ_QU_INSP_SCHEDULE QS
			   WHERE QS.CD_COMPANY = @P_CD_COMPANY
			   AND QS.NO_SO = @P_NO_SO)
BEGIN
	INSERT INTO CZ_QU_INSP_SCHEDULE 
	(
		CD_COMPANY,
		NO_SO,
		TP_COMPANY,
		DT_INSP,
		ID_INSERT,
		DTS_INSERT
	)
	VALUES
	(
		@P_CD_COMPANY,
		@P_NO_SO,
		'',
		'',
		@P_ID_USER, 
		NEOE.SF_SYSDATE(GETDATE())
	)
END

GO