USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_CRM_PARTNER_PIC_PEOPLE_TREE]    Script Date: 2018-04-20 오후 2:37:05 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO








ALTER PROCEDURE [NEOE].[SP_CZ_SA_CRM_PARTNER_PIC_PEOPLE_TREE]
(
	@P_CD_COMPANY		NVARCHAR(7),
	@P_CD_PARTNER		NVARCHAR(20),
	@P_SEQ				NUMERIC(5, 0)
) 
AS
 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

WITH TREE_QUERY AS (
	SELECT PP.CD_COMPANY,
		   PP.CD_PARTNER,
		   PP.SEQ,
		   PP.CD_PARTNER_SUB,
		   PP.SEQ_SUB,
		   PP.DC_RMK,
		   CONVERT(NVARCHAR(MAX), PP.CD_PARTNER_SUB + '-' + CONVERT(NVARCHAR, PP.SEQ_SUB)) AS SORT
	FROM CZ_CRM_PARTNER_PIC_PEOPLE PP
    WHERE PP.CD_COMPANY = @P_CD_COMPANY
	AND PP.CD_PARTNER = @P_CD_PARTNER
	AND PP.SEQ = @P_SEQ
	UNION ALL
	SELECT PP.CD_COMPANY,
		   PP.CD_PARTNER,
		   PP.SEQ,
		   PP.CD_PARTNER_SUB,
		   PP.SEQ_SUB,
		   PP.DC_RMK,
		   CONVERT(NVARCHAR(MAX), TQ.SORT + ' -> ' + PP.CD_PARTNER_SUB + '-' + CONVERT(NVARCHAR, PP.SEQ_SUB)) AS SORT
	FROM TREE_QUERY TQ
	JOIN CZ_CRM_PARTNER_PIC_PEOPLE PP ON PP.CD_COMPANY = TQ.CD_COMPANY AND PP.CD_PARTNER = TQ.CD_PARTNER_SUB AND PP.SEQ = TQ.SEQ_SUB
)
SELECT TQ.CD_COMPANY,
	   (TQ.CD_PARTNER + '-' + CONVERT(NVARCHAR, TQ.SEQ)) AS ID_PARENT,
	   (TQ.CD_PARTNER_SUB + '-' + CONVERT(NVARCHAR, TQ.SEQ_SUB)) AS ID_CHILD,
	   (MP.LN_PARTNER + '-' + FP.NM_PTR) AS NAME 
FROM TREE_QUERY TQ
LEFT JOIN FI_PARTNERPTR FP ON FP.CD_COMPANY = TQ.CD_COMPANY AND FP.CD_PARTNER = TQ.CD_PARTNER_SUB AND FP.SEQ = TQ.SEQ_SUB
LEFT JOIN MA_PARTNER MP ON MP.CD_COMPANY = FP.CD_COMPANY AND MP.CD_PARTNER = FP.CD_PARTNER
ORDER BY SORT;

WITH TREE_QUERY1 AS (
	SELECT PP.CD_COMPANY,
		   PP.CD_PARTNER_SUB AS CD_PARTNER,
		   PP.SEQ_SUB AS SEQ,
		   PP.CD_PARTNER AS CD_PARTNER_SUB,
		   PP.SEQ AS SEQ_SUB,
		   PP.DC_RMK,
		   CONVERT(NVARCHAR(MAX), PP.CD_PARTNER + '-' + CONVERT(NVARCHAR, PP.SEQ)) AS SORT
	FROM CZ_CRM_PARTNER_PIC_PEOPLE PP
    WHERE PP.CD_COMPANY = @P_CD_COMPANY
	AND PP.CD_PARTNER_SUB = @P_CD_PARTNER
	AND PP.SEQ_SUB = @P_SEQ
	UNION ALL
	SELECT PP.CD_COMPANY,
		   PP.CD_PARTNER_SUB AS CD_PARTNER,
		   PP.SEQ_SUB AS SEQ,
		   PP.CD_PARTNER AS CD_PARTNER_SUB,
		   PP.SEQ AS SEQ_SUB,
		   PP.DC_RMK,
		   CONVERT(NVARCHAR(MAX), PP.CD_PARTNER + '-' + CONVERT(NVARCHAR, PP.SEQ) + ' <- ' + TQ.SORT) AS SORT
	FROM TREE_QUERY1 TQ
	JOIN CZ_CRM_PARTNER_PIC_PEOPLE PP ON PP.CD_COMPANY = TQ.CD_COMPANY AND PP.CD_PARTNER_SUB = TQ.CD_PARTNER_SUB AND PP.SEQ_SUB = TQ.SEQ_SUB
)
SELECT TQ.CD_COMPANY,
	   (TQ.CD_PARTNER + '-' + CONVERT(NVARCHAR, TQ.SEQ)) AS ID_PARENT,
	   (TQ.CD_PARTNER_SUB + '-' + CONVERT(NVARCHAR, TQ.SEQ_SUB)) AS ID_CHILD,
	   (MP.LN_PARTNER + '-' + FP.NM_PTR) AS NAME 
FROM TREE_QUERY1 TQ
LEFT JOIN FI_PARTNERPTR FP ON FP.CD_COMPANY = TQ.CD_COMPANY AND FP.CD_PARTNER = TQ.CD_PARTNER_SUB AND FP.SEQ = TQ.SEQ_SUB
LEFT JOIN MA_PARTNER MP ON MP.CD_COMPANY = FP.CD_COMPANY AND MP.CD_PARTNER = FP.CD_PARTNER
ORDER BY SORT

GO

