USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_CRM_PARTNER_PIC_ACTIVITY_S]    Script Date: 2018-04-20 오후 4:13:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO





ALTER PROCEDURE [NEOE].[SP_CZ_SA_CRM_PARTNER_PIC_ACTIVITY_S]
(
	@P_CD_COMPANY	NVARCHAR(7),
	@P_CD_PARTNER	NVARCHAR(20),
	@P_SEQ			NUMERIC(5, 0)
) 
AS
 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT PA.CD_COMPANY,
	   PA.CD_PARTNER,
	   @P_SEQ AS SEQ,
	   PA.NO_INDEX,
	   PA.NM_TITLE,
	   PA.DT_START,
	   PA.DT_END,
	   PA.NM_PIC,
	   PA.NM_EMP,
	   PA.DC_ACTIVITY,
	   PA.ID_INSERT 
FROM CZ_CRM_PARTNER_ACTIVITY PA
WHERE PA.CD_COMPANY = @P_CD_COMPANY
AND PA.CD_PARTNER = @P_CD_PARTNER
AND PA.NO_PIC LIKE '%' + CONVERT(NVARCHAR, @P_SEQ) + '|%'

GO

