USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_CRM_PARTNER_PIC_ITEM_S]    Script Date: 2018-04-10 오전 10:16:36 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO





ALTER PROCEDURE [NEOE].[SP_CZ_SA_CRM_PARTNER_PIC_ITEM_S]
(
	@P_CD_COMPANY		NVARCHAR(7),
	@P_CD_PARTNER		NVARCHAR(20),
	@P_SEQ				NUMERIC(5, 0)
) 
AS
 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT CD_COMPANY,
	   CD_PARTNER,
	   SEQ,
	   CD_ITEM,
	   NM_ITEM,
	   DC_ITEM 
FROM CZ_CRM_PARTNER_PIC_ITEM
WHERE CD_COMPANY = @P_CD_COMPANY
AND CD_PARTNER = @P_CD_PARTNER
AND SEQ = @P_SEQ

GO

