USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_CRM_PARTNER_PIC_COMMISSION_S]    Script Date: 2018-04-16 오전 9:50:31 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




ALTER PROCEDURE [NEOE].[SP_CZ_SA_CRM_PARTNER_PIC_COMMISSION_S]
(
	@P_CD_COMPANY		NVARCHAR(7),
	@P_CD_PARTNER		NVARCHAR(20),
	@P_SEQ				NUMERIC(5, 0)
) 
AS
 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT MC1.NM_SYSDEF AS NM_STAT,
	   CH.CD_PARTNER,
	   CL.SEQ,
	   CH.NO_COMMISSION,
	   LEFT(CH.DTS_INSERT, 8) AS DT_COMMISSION,
	   CH.ID_INSERT AS ID_USER,
	   MU.NM_USER,
	   CD.CD_EXCH,
	   MC.NM_SYSDEF AS NM_EXCH,
	   CD.AM_COMMISSION,
	   CH.DC_COMMISSION 
FROM CZ_SA_COMMISSIONH CH
JOIN CZ_SA_COMMISSIONL CL ON CL.CD_COMPANY = CH.CD_COMPANY AND CL.NO_COMMISSION = CH.NO_COMMISSION
LEFT JOIN (SELECT CD.CD_COMPANY, CD.NO_COMMISSION, CD.CD_EXCH,
			      SUM(CD.AM_COMMISSION) AS AM_COMMISSION
		   FROM CZ_SA_COMMISSIOND CD
		   GROUP BY CD.CD_COMPANY, CD.NO_COMMISSION, CD.CD_EXCH) CD
ON CD.CD_COMPANY = CH.CD_COMPANY AND CD.NO_COMMISSION = CH.NO_COMMISSION
LEFT JOIN MA_USER MU ON MU.CD_COMPANY = CH.CD_COMPANY AND MU.ID_USER = CH.ID_INSERT
LEFT JOIN FI_GWDOCU GW ON GW.CD_COMPANY = 'K100' AND GW.CD_PC = '010000' AND GW.NO_DOCU = CH.CD_COMPANY + '-' + CH.NO_GW_DOCU
LEFT JOIN MA_CODEDTL MC ON MC.CD_COMPANY = CD.CD_COMPANY AND MC.CD_FIELD = 'MA_B000005' AND MC.CD_SYSDEF = CD.CD_EXCH
LEFT JOIN MA_CODEDTL MC1 ON MC1.CD_COMPANY = GW.CD_COMPANY AND MC1.CD_FIELD = 'PU_C000065' AND MC1.CD_SYSDEF = GW.ST_STAT
WHERE CH.CD_COMPANY = @P_CD_COMPANY
AND CH.CD_PARTNER = @P_CD_PARTNER
AND CL.SEQ = @P_SEQ

GO

