USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_CRM_PARTNER_PIC_HULL_S]    Script Date: 2018-04-11 오후 7:28:12 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO






ALTER PROCEDURE [NEOE].[SP_CZ_SA_CRM_PARTNER_PIC_HULL_S]
(
	@P_CD_COMPANY		NVARCHAR(7),
	@P_CD_PARTNER		NVARCHAR(20),
	@P_SEQ				NUMERIC(5, 0)
) 
AS
 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT PH.CD_COMPANY,
	   PH.CD_PARTNER,
	   MP.LN_PARTNER,
	   PH.SEQ,
	   PH.NO_IMO,
	   MH.NO_HULL,
	   MH.NM_VESSEL,
	   PH.DC_RMK 
FROM CZ_CRM_PARTNER_PIC_HULL PH
LEFT JOIN CZ_MA_HULL MH ON MH.NO_IMO = PH.NO_IMO
LEFT JOIN MA_PARTNER MP ON MP.CD_COMPANY = @P_CD_COMPANY AND MP.CD_PARTNER = MH.CD_PARTNER
WHERE PH.CD_COMPANY = @P_CD_COMPANY
AND PH.CD_PARTNER = @P_CD_PARTNER
AND PH.SEQ = @P_SEQ

GO

