USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_CRM_PARTNER_PIC_ITEM_XML]    Script Date: 2018-04-10 오전 10:43:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




ALTER PROCEDURE [NEOE].[SP_CZ_SA_CRM_PARTNER_PIC_ITEM_XML] 
(
	@P_XML			XML, 
	@P_ID_USER		NVARCHAR(10), 
    @DOC			INT = NULL
) 
AS 

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

EXEC SP_XML_PREPAREDOCUMENT @DOC OUTPUT, @P_XML 

-- ================================================== DELETE
DELETE A 
FROM CZ_CRM_PARTNER_PIC_ITEM A 
JOIN OPENXML (@DOC, '/XML/D', 2) 
        WITH (CD_COMPANY NVARCHAR(7),
			  CD_PARTNER NVARCHAR(20),
			  SEQ		 NUMERIC(5, 0),
			  CD_ITEM	 NVARCHAR(4)) B 
ON A.CD_COMPANY = B.CD_COMPANY
AND A.CD_PARTNER = B.CD_PARTNER
AND A.SEQ = B.SEQ
AND A.CD_ITEM = B.CD_ITEM
-- ================================================== INSERT
INSERT INTO CZ_CRM_PARTNER_PIC_ITEM 
(
	CD_COMPANY,
	CD_PARTNER,
	SEQ,
	CD_ITEM,
    NM_ITEM,
	DC_ITEM, 
	ID_INSERT,
	DTS_INSERT
)
SELECT CD_COMPANY,
	   CD_PARTNER,
	   SEQ,
	   CD_ITEM,
	   NM_ITEM,
	   DC_ITEM, 
       @P_ID_USER, 
       NEOE.SF_SYSDATE(GETDATE()) 
  FROM OPENXML (@DOC, '/XML/I', 2) 
          WITH (CD_COMPANY  NVARCHAR(7),
				CD_PARTNER  NVARCHAR(20),
				SEQ			NUMERIC(5, 0),
				CD_ITEM		NVARCHAR(4),
			    NM_ITEM		NVARCHAR(50),
				DC_ITEM		NVARCHAR(MAX)) 
-- ================================================== UPDATE    
UPDATE A 
   SET A.NM_ITEM = B.NM_ITEM,
	   A.DC_ITEM = B.DC_ITEM,
	   A.ID_UPDATE = @P_ID_USER, 
	   A.DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE())
  FROM CZ_CRM_PARTNER_PIC_ITEM A 
  JOIN OPENXML (@DOC, '/XML/U', 2) 
          WITH (CD_COMPANY  NVARCHAR(7),
				CD_PARTNER  NVARCHAR(20),
				SEQ			NUMERIC(5, 0),
				CD_ITEM		NVARCHAR(4),
			    NM_ITEM		NVARCHAR(50),
				DC_ITEM		NVARCHAR(MAX)) B 
  ON A.CD_COMPANY = B.CD_COMPANY
  AND A.CD_PARTNER = B.CD_PARTNER
  AND A.SEQ = B.SEQ
  AND A.CD_ITEM = B.CD_ITEM

EXEC SP_XML_REMOVEDOCUMENT @DOC 




GO

