USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_CRM_PARTNER_PIC_MEETING_MEMO_S]    Script Date: 2018-04-12 오후 2:22:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER PROCEDURE [NEOE].[SP_CZ_SA_CRM_PARTNER_PIC_MEETING_MEMO_S]
(
	@P_CD_COMPANY		NVARCHAR(7),
	@P_CD_PARTNER		NVARCHAR(20),
	@P_SEQ				NUMERIC(5, 0)
) 
AS
 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT MA.CD_COMPANY,
	   MA.CD_PARTNER,
	   MA.NO_ATTENDEE AS SEQ,
	   MA.NO_MEETING,
	   MM.DT_MEETING,
	   MM.DC_TIME,
	   MM.DC_LOCATION,
	   MM.DC_SUBJECT,
	   MM.DC_PURPOSE,
	   MM.DC_MEETING
FROM (SELECT MA.CD_COMPANY, 
			 MA.CD_PARTNER,
			 MA.NO_ATTENDEE,
			 MA.NO_MEETING 
	  FROM CZ_SA_MEETING_ATTENDEE MA
	  WHERE MA.CD_COMPANY = @P_CD_COMPANY
	  AND MA.TP_INOUT = 'OUT'
	  AND MA.CD_PARTNER = @P_CD_PARTNER
	  AND MA.NO_ATTENDEE = @P_SEQ
	  GROUP BY MA.CD_COMPANY, 
			   MA.CD_PARTNER,
			   MA.NO_ATTENDEE,
			   MA.NO_MEETING) MA
LEFT JOIN CZ_SA_MEETING_MEMO MM ON MM.CD_COMPANY = MA.CD_COMPANY AND MM.NO_MEETING = MA.NO_MEETING

GO

