USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_CRM_PARTNER_PIC_U]    Script Date: 2018-04-09 오후 4:14:48 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO





ALTER PROCEDURE [NEOE].[SP_CZ_SA_CRM_PARTNER_PIC_U]
(
	@P_CD_COMPANY		NVARCHAR(7),
	@P_CD_PARTNER		NVARCHAR(20),
	@P_SEQ				NUMERIC(5, 0),
	@P_CD_GENDER		NVARCHAR(4),
	@P_CD_NATION		NVARCHAR(4),
	@P_CD_RELIGION		NVARCHAR(4),
	@P_CD_RANK			NVARCHAR(4),
	@P_DT_BERTH			NVARCHAR(8),
	@P_DC_MEMO			NVARCHAR(MAX),
	@P_ID_UPDATE		NVARCHAR(15)
) 
AS
 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

IF EXISTS (SELECT 1 
		   FROM CZ_FI_PARTNERPTR
		   WHERE CD_COMPANY = @P_CD_COMPANY
		   AND CD_PARTNER = @P_CD_PARTNER
		   AND SEQ = @P_SEQ)
BEGIN
	UPDATE CZ_FI_PARTNERPTR
	SET CD_GENDER = @P_CD_GENDER,
		CD_NATION = @P_CD_NATION,
		CD_RELIGION = @P_CD_RELIGION,
		CD_RANK = @P_CD_RANK,
		DT_BERTH = @P_DT_BERTH,
		DC_MEMO = @P_DC_MEMO,
		ID_UPDATE = @P_ID_UPDATE,
		DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE())
	WHERE CD_COMPANY = @P_CD_COMPANY
	AND CD_PARTNER = @P_CD_PARTNER
	AND SEQ = @P_SEQ
END
ELSE
BEGIN
	INSERT INTO CZ_FI_PARTNERPTR
	(
		CD_COMPANY,
		CD_PARTNER,
		SEQ,
		CD_GENDER,
		CD_NATION,
		CD_RELIGION,
		CD_RANK,
		DT_BERTH,
		DC_MEMO,
		ID_INSERT,
		DTS_INSERT
	)
	VALUES
	(
		@P_CD_COMPANY,
		@P_CD_PARTNER,
		@P_SEQ,
		@P_CD_GENDER,
		@P_CD_NATION,
		@P_CD_RELIGION,
		@P_CD_RANK,
		@P_DT_BERTH,
		@P_DC_MEMO,
		@P_ID_UPDATE,
		NEOE.SF_SYSDATE(GETDATE())
	)
END

GO

