USE [NEOE]
GO

/****** Object:  Table [NEOE].[CZ_PR_MARKING_SETTING]    Script Date: 2021-05-11 오후 3:16:31 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [NEOE].[CZ_PR_MARKING_SETTING](
	[CD_COMPANY] [nvarchar](7) NOT NULL,
	[CD_ITEM] [nvarchar](20) NOT NULL,
	[CD_PARTNER] [nvarchar](20) NOT NULL,
	[YN_CERT] [nvarchar](1) NULL,
	[DTS_INSERT] [nvarchar](14) NULL,
	[ID_INSERT] [nvarchar](15) NULL,
	[DTS_UPDATE] [nvarchar](14) NULL,
	[ID_UPDATE] [nvarchar](15) NULL,
 CONSTRAINT [PK_CZ_PR_MARKING_SETTING_1] PRIMARY KEY CLUSTERED 
(
	[CD_COMPANY] ASC,
	[CD_ITEM] ASC,
	[CD_PARTNER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


