USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_SO_TP_VAT_U]    Script Date: 2016-12-09 오전 10:32:45 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


-- EXEC SP_CZ_SA_SO_TP_VAT_U 'K100', 'DB16013806', '14'
ALTER PROCEDURE [NEOE].[SP_CZ_SA_SO_TP_VAT_U]
(
    @P_CD_COMPANY   NVARCHAR(7),
    @P_NO_SO        NVARCHAR(20),
	@P_TP_VAT		NVARCHAR(4)
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

DECLARE @V_ERRMSG   VARCHAR(255),   -- ERROR 메시지
		@V_NO_KEY	NVARCHAR(20)   

BEGIN TRAN SP_CZ_SA_SO_TP_VAT_U
BEGIN TRY

IF EXISTS (SELECT 1 
		   FROM SA_IVL 
		   WHERE CD_COMPANY = @P_CD_COMPANY 
		   AND NO_SO = @P_NO_SO
		   AND YN_RETURN = 'N')
BEGIN
	SELECT @V_ERRMSG = '매출 등록된 수주건 입니다. 매출 취소후 변경 하시기 바랍니다.'                      
	GOTO ERROR
END

PRINT '-- 수주'

UPDATE SL
SET SL.TP_VAT = MC.CD_SYSDEF,
	SL.AM_VAT = (SL.AM_WONAMT * ROUND(CONVERT(NUMERIC(17, 4), CASE WHEN ISNULL(CD_FLAG1, '') = '' THEN '0' ELSE CD_FLAG1 END) / 100, 2)),
	SL.RT_VAT = MC.CD_FLAG1,
	SL.FG_VAT = (CASE WHEN MC.CD_FLAG1 > 0 THEN 'Y' ELSE 'N' END)
FROM SA_SOL SL
LEFT JOIN MA_CODEDTL MC ON MC.CD_COMPANY = SL.CD_COMPANY AND MC.CD_FIELD = 'MA_B000040' AND MC.CD_SYSDEF = @P_TP_VAT
WHERE SL.CD_COMPANY = @P_CD_COMPANY
AND SL.NO_SO = @P_NO_SO

UPDATE SH
SET SH.TP_VAT = MC.CD_SYSDEF,
	SH.AM_VAT = SL.AM_VAT,
	SH.FG_VAT = (CASE WHEN MC.CD_FLAG1 > 0 THEN 'Y' ELSE 'N' END)
FROM SA_SOH SH
LEFT JOIN (SELECT CD_COMPANY, NO_SO,
				  SUM(AM_VAT) AS AM_VAT
		   FROM SA_SOL
		   GROUP BY CD_COMPANY, NO_SO) SL
ON SL.CD_COMPANY = SH.CD_COMPANY AND SL.NO_SO = SH.NO_SO
LEFT JOIN MA_CODEDTL MC ON MC.CD_COMPANY = SH.CD_COMPANY AND MC.CD_FIELD = 'MA_B000040' AND MC.CD_SYSDEF = @P_TP_VAT
WHERE SH.CD_COMPANY = @P_CD_COMPANY
AND SH.NO_SO = @P_NO_SO

PRINT '-- 출고의뢰'

UPDATE GL
SET GL.TP_VAT = MC.CD_SYSDEF,
	GL.RT_VAT = MC.CD_FLAG1,
	GL.AM_VAT = (GL.AM_GIRAMT * ROUND(CONVERT(NUMERIC(17, 4), CASE WHEN ISNULL(CD_FLAG1, '') = '' THEN '0' ELSE CD_FLAG1 END) / 100, 2))
FROM SA_GIRL GL
LEFT JOIN MA_CODEDTL MC ON MC.CD_COMPANY = GL.CD_COMPANY AND MC.CD_FIELD = 'MA_B000040' AND MC.CD_SYSDEF = @P_TP_VAT
WHERE GL.CD_COMPANY = @P_CD_COMPANY
AND GL.NO_SO = @P_NO_SO

PRINT '-- 출고'

UPDATE OL
SET OL.FG_TAX = MC.CD_SYSDEF,
	OL.VAT = (OL.AM * ROUND(CONVERT(NUMERIC(17, 4), CASE WHEN ISNULL(CD_FLAG1, '') = '' THEN '0' ELSE CD_FLAG1 END) / 100, 2)),
	OL.VAT_CLS = (OL.AM_CLS * ROUND(CONVERT(NUMERIC(17, 4), CASE WHEN ISNULL(CD_FLAG1, '') = '' THEN '0' ELSE CD_FLAG1 END) / 100, 2))
FROM MM_QTIO OL
LEFT JOIN MA_CODEDTL MC ON MC.CD_COMPANY = OL.CD_COMPANY AND MC.CD_FIELD = 'MA_B000040' AND MC.CD_SYSDEF = @P_TP_VAT
WHERE OL.CD_COMPANY = @P_CD_COMPANY
AND OL.NO_PSO_MGMT = @P_NO_SO

COMMIT TRAN SP_CZ_SA_SO_TP_VAT_U

END TRY
BEGIN CATCH
	ROLLBACK TRAN SP_CZ_SA_SO_TP_VAT_U
	SELECT @V_ERRMSG = ERROR_MESSAGE()
	GOTO ERROR
END CATCH

RETURN
ERROR: 
RAISERROR(@V_ERRMSG, 16, 1)
ROLLBACK TRAN SP_CZ_SA_SO_TP_VAT_U


GO

