USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_SO_PROCESS_D]    Script Date: 2016-03-31 오전 9:08:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


--EXEC SP_CZ_SA_SO_PROCESS_D 'TEST', 'ADM20160034', 'N'
ALTER PROCEDURE [NEOE].[SP_CZ_SA_SO_PROCESS_D]  
(  
    @P_CD_COMPANY   NVARCHAR(7),
    @P_NO_SO        NVARCHAR(20),
	@P_YN_DELETE    NVARCHAR(1)
)
AS

DECLARE @V_ERRMSG   VARCHAR(255)   -- ERROR 메시지   

CREATE TABLE #SA_SOH
(
	CD_COMPANY	NVARCHAR(7),
	NO_SO		NVARCHAR(20),
	NO_GIR		NVARCHAR(20),
	NO_IO		NVARCHAR(20),
	NO_IV		NVARCHAR(20),
	NO_DOCU		NVARCHAR(20)
)

INSERT INTO #SA_SOH
SELECT SL.CD_COMPANY, SL.NO_SO, GL.NO_GIR, OL.NO_IO, IL.NO_IV, FD.NO_DOCU 
FROM SA_SOL SL
LEFT JOIN SA_GIRL GL ON GL.CD_COMPANY = SL.CD_COMPANY AND GL.NO_SO = SL.NO_SO AND GL.SEQ_SO = SL.SEQ_SO
LEFT JOIN MM_QTIO OL ON OL.CD_COMPANY = GL.CD_COMPANY AND OL.NO_ISURCV = GL.NO_GIR AND OL.NO_ISURCVLINE = GL.SEQ_GIR
LEFT JOIN SA_IVL IL ON IL.CD_COMPANY = OL.CD_COMPANY AND IL.NO_IO = OL.NO_IO AND IL.NO_IOLINE = OL.NO_IOLINE
LEFT JOIN FI_DOCU FD ON FD.CD_COMPANY = IL.CD_COMPANY AND FD.NO_MDOCU = IL.NO_IV
WHERE SL.CD_COMPANY = @P_CD_COMPANY
AND SL.NO_SO = @P_NO_SO
GROUP BY SL.CD_COMPANY, SL.NO_SO, GL.NO_GIR, OL.NO_IO, IL.NO_IV, FD.NO_DOCU

SELECT * FROM #SA_SOH

IF EXISTS (SELECT 1 FROM #SA_SOH WHERE NO_DOCU IS NOT NULL)
BEGIN
	DROP TABLE #SA_SOH
	SELECT @V_ERRMSG = '전표 처리된 수주건 입니다. 전표 취소후 삭제 하시기 바랍니다.'                      
	GOTO ERROR
END

BEGIN TRAN SP_CZ_SA_SO_PROCESS_D
BEGIN TRY

PRINT '- SA_IVL 제거'

IF (@P_YN_DELETE = 'N')
	SELECT *
	FROM SA_IVL IL
	JOIN #SA_SOH IH ON IH.CD_COMPANY = IL.CD_COMPANY AND IH.NO_IV = IL.NO_IV AND IH.NO_SO = IL.NO_SO
ELSE
	DELETE IL
	FROM SA_IVL IL
	JOIN #SA_SOH IH ON IH.CD_COMPANY = IL.CD_COMPANY AND IH.NO_IV = IL.NO_IV AND IH.NO_SO = IL.NO_SO

PRINT '- SA_IVH 제거'

IF (@P_YN_DELETE = 'N')
	SELECT *
	FROM SA_IVH IH 
	JOIN #SA_SOH TH ON TH.CD_COMPANY = IH.CD_COMPANY AND TH.NO_IV = IH.NO_IV
ELSE
	DELETE IH
	FROM SA_IVH IH 
	JOIN #SA_SOH TH ON TH.CD_COMPANY = IH.CD_COMPANY AND TH.NO_IV = IH.NO_IV
	WHERE NOT EXISTS (SELECT 1 FROM SA_IVL
					  WHERE CD_COMPANY = IH.CD_COMPANY
					  AND NO_IV = IH.NO_IV)

PRINT '- MM_QTIO 제거'

IF (@P_YN_DELETE = 'N')
	SELECT *
	FROM MM_QTIO OL
	JOIN #SA_SOH OH ON OH.CD_COMPANY = OL.CD_COMPANY AND OH.NO_IO = OH.NO_IO AND OH.NO_SO = OL.NO_PSO_MGMT
ELSE
	DELETE OL
	FROM MM_QTIO OL
	JOIN #SA_SOH OH ON OH.CD_COMPANY = OL.CD_COMPANY AND OH.NO_IO = OH.NO_IO AND OH.NO_SO = OL.NO_PSO_MGMT

PRINT '- MM_QTIOH 제거'

IF (@P_YN_DELETE = 'N')
	SELECT *
	FROM MM_QTIOH OH 
	JOIN #SA_SOH TH ON TH.CD_COMPANY = OH.CD_COMPANY AND TH.NO_IO = OH.NO_IO
ELSE
	DELETE OH
	FROM MM_QTIOH OH 
	JOIN #SA_SOH TH ON TH.CD_COMPANY = OH.CD_COMPANY AND TH.NO_IO = OH.NO_IO
	WHERE NOT EXISTS (SELECT 1 FROM MM_QTIO
					  WHERE CD_COMPANY = OH.CD_COMPANY
					  AND NO_IO = OH.NO_IO)

PRINT '- SA_GIRL 제거'

IF (@P_YN_DELETE = 'N')
	SELECT *
	FROM SA_GIRL GL
	JOIN #SA_SOH GH ON GH.CD_COMPANY = GL.CD_COMPANY AND GH.NO_GIR = GL.NO_GIR AND GH.NO_SO = GL.NO_SO
ELSE
	DELETE GL
	FROM SA_GIRL GL
	JOIN #SA_SOH GH ON GH.CD_COMPANY = GL.CD_COMPANY AND GH.NO_GIR = GL.NO_GIR AND GH.NO_SO = GL.NO_SO

PRINT '- SA_GIRH 제거'

IF (@P_YN_DELETE = 'N')
	SELECT *
	FROM SA_GIRH GH 
	JOIN #SA_SOH TH ON TH.CD_COMPANY = GH.CD_COMPANY AND TH.NO_GIR = GH.NO_GIR
ELSE
	DELETE GH
	FROM SA_GIRH GH 
	JOIN #SA_SOH TH ON TH.CD_COMPANY = GH.CD_COMPANY AND TH.NO_GIR = GH.NO_GIR
	WHERE NOT EXISTS (SELECT 1 FROM SA_GIRL
					  WHERE CD_COMPANY = GH.CD_COMPANY
					  AND NO_GIR = GH.NO_GIR)

PRINT '- SA_SOL 상태 UPDATE'

IF (@P_YN_DELETE = 'Y')
	UPDATE SA_SOL
	SET STA_SO = 'O'
	FROM SA_SOL
	WHERE CD_COMPANY = @P_CD_COMPANY
	AND NO_SO = @P_NO_SO

PRINT '- SA_SOL 제거'

IF (@P_YN_DELETE = 'N')
	SELECT * FROM SA_SOL
	WHERE CD_COMPANY = @P_CD_COMPANY
	AND NO_SO = @P_NO_SO
ELSE
	DELETE FROM SA_SOL
	WHERE CD_COMPANY = @P_CD_COMPANY
	AND NO_SO = @P_NO_SO

PRINT '- SA_SOL_DLV 제거'

IF (@P_YN_DELETE = 'N')
	SELECT * FROM SA_SOL_DLV
	WHERE CD_COMPANY = @P_CD_COMPANY
	AND NO_SO = @P_NO_SO
ELSE
	DELETE FROM SA_SOL_DLV
	WHERE CD_COMPANY = @P_CD_COMPANY
	AND NO_SO = @P_NO_SO

PRINT '- SA_SOH 제거'

IF (@P_YN_DELETE = 'N')
	SELECT * FROM SA_SOH
	WHERE CD_COMPANY = @P_CD_COMPANY
	AND NO_SO = @P_NO_SO
ELSE
	DELETE FROM SA_SOH
	WHERE CD_COMPANY = @P_CD_COMPANY
	AND NO_SO = @P_NO_SO

PRINT '- SA_SOH_SUB 제거'

IF (@P_YN_DELETE = 'N')
	SELECT * FROM SA_SOH_SUB
	WHERE CD_COMPANY = @P_CD_COMPANY
	AND NO_SO = @P_NO_SO
ELSE
	DELETE FROM SA_SOH_SUB
	WHERE CD_COMPANY = @P_CD_COMPANY
	AND NO_SO = @P_NO_SO

DROP TABLE #SA_SOH

COMMIT TRAN SP_CZ_SA_SO_PROCESS_D

END TRY
BEGIN CATCH
	ROLLBACK TRAN SP_CZ_SA_SO_PROCESS_D
	SELECT @V_ERRMSG = ERROR_MESSAGE()
	GOTO ERROR
END CATCH

RETURN
ERROR: RAISERROR(@V_ERRMSG, 16, 1)

GO