USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_SO_TP_SO_U]    Script Date: 2016-04-11 오후 4:16:52 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- EXEC SP_CZ_SA_SO_TP_SO_U 'K100', 'FB569418', '2200'
ALTER PROCEDURE [NEOE].[SP_CZ_SA_SO_TP_SO_U]
(
    @P_CD_COMPANY   NVARCHAR(7),
    @P_NO_SO        NVARCHAR(20),
	@P_TP_SO		NVARCHAR(4)
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

DECLARE @V_ERRMSG   VARCHAR(255),   -- ERROR 메시지
		@V_NO_KEY	NVARCHAR(20)   

BEGIN TRAN SP_CZ_SA_SO_TP_SO_U
BEGIN TRY

IF EXISTS (SELECT 1 
		   FROM SA_IVL 
		   WHERE CD_COMPANY = @P_CD_COMPANY 
		   AND NO_SO = @P_NO_SO
		   AND YN_RETURN = 'N')
BEGIN
	SELECT @V_ERRMSG = '매출 등록된 수주건 입니다. 매출 취소후 변경 하시기 바랍니다.'                      
	GOTO ERROR
END

PRINT '-- 수주'

UPDATE SA_SOH
SET TP_SO = @P_TP_SO
WHERE CD_COMPANY = @P_CD_COMPANY
AND NO_SO = @P_NO_SO

UPDATE SL
SET SL.TP_GI = TS.TP_GI,
	SL.TP_IV = TS.TP_IV,
	SL.TP_BUSI = TS.TP_BUSI,
	SL.GIR = TS.GIR,
	SL.IV = TS.IV
FROM SA_SOL SL
JOIN SA_SOH SH ON SH.CD_COMPANY = SL.CD_COMPANY AND SH.NO_SO = SL.NO_SO
LEFT JOIN SA_TPSO TS ON TS.CD_COMPANY = SH.CD_COMPANY AND TS.TP_SO = SH.TP_SO
WHERE SL.CD_COMPANY = @P_CD_COMPANY
AND SL.NO_SO = @P_NO_SO

PRINT '-- 출고의뢰'

IF EXISTS (SELECT GL.CD_COMPANY, GL.NO_GIR, COUNT(DISTINCT GL.NO_SO)
		   FROM SA_GIRL GL
		   LEFT JOIN SA_GIRH GH ON GH.CD_COMPANY = GL.CD_COMPANY AND GH.NO_GIR = GL.NO_GIR
		   WHERE GL.CD_COMPANY = @P_CD_COMPANY
		   AND GL.NO_GIR IN (SELECT DISTINCT NO_GIR
		   					 FROM SA_GIRL
		   					 WHERE CD_COMPANY = @P_CD_COMPANY
		   					 AND NO_SO = @P_NO_SO)
		   AND GH.YN_RETURN = 'N'
		   GROUP BY GL.CD_COMPANY, GL.NO_GIR
		   HAVING COUNT(DISTINCT GL.NO_SO) > 1)
BEGIN
	SELECT @V_ERRMSG = '여러건 합쳐서 의뢰된 수주건 입니다.'                      
	GOTO ERROR
END
ELSE
BEGIN
	UPDATE GH
	SET GH.TP_BUSI = SL.TP_BUSI,
		GH.YN_RETURN = ST.RET
	FROM SA_GIRH GH
	JOIN SA_GIRL GL ON GL.CD_COMPANY = GH.CD_COMPANY AND GL.NO_GIR = GH.NO_GIR
	JOIN SA_SOL SL ON SL.CD_COMPANY = GL.CD_COMPANY AND SL.NO_SO = GL.NO_SO AND SL.SEQ_SO = GL.SEQ_SO
	JOIN SA_SOH SH ON SH.CD_COMPANY = SL.CD_COMPANY AND SH.NO_SO = SL.NO_SO
	JOIN SA_TPSO ST ON ST.CD_COMPANY = SH.CD_COMPANY AND ST.TP_SO = SH.TP_SO
	WHERE GL.CD_COMPANY = @P_CD_COMPANY
	AND GL.NO_SO = @P_NO_SO
	AND GH.YN_RETURN = 'N'
	
	UPDATE TH
	SET TH.FG_LC = SL.TP_BUSI
	FROM CZ_TR_INVH TH
	JOIN SA_GIRL GL ON GL.CD_COMPANY = TH.CD_COMPANY AND GL.NO_INV = TH.NO_INV
	JOIN SA_SOL SL ON SL.CD_COMPANY = GL.CD_COMPANY AND SL.NO_SO = GL.NO_SO AND SL.SEQ_SO = GL.SEQ_SO
	WHERE GL.CD_COMPANY = @P_CD_COMPANY
	AND GL.NO_SO = @P_NO_SO
END

UPDATE GL
SET GL.TP_GI = SL.TP_GI,
    GL.TP_IV = SL.TP_IV,
	GL.TP_BUSI = SL.TP_BUSI,
	GL.GIR = SL.GIR,
	GL.IV = SL.IV,
	GL.RET = ST.RET
FROM SA_GIRL GL
LEFT JOIN SA_GIRH GH ON GH.CD_COMPANY = GL.CD_COMPANY AND GH.NO_GIR = GL.NO_GIR
JOIN SA_SOL SL ON SL.CD_COMPANY = GL.CD_COMPANY AND SL.NO_SO = GL.NO_SO AND SL.SEQ_SO = GL.SEQ_SO
JOIN SA_SOH SH ON SH.CD_COMPANY = SL.CD_COMPANY AND SH.NO_SO = SL.NO_SO
JOIN SA_TPSO ST ON ST.CD_COMPANY = SH.CD_COMPANY AND ST.TP_SO = SH.TP_SO
WHERE GL.CD_COMPANY = @P_CD_COMPANY
AND GL.NO_SO = @P_NO_SO
AND GH.YN_RETURN = 'N'

PRINT '-- 출고'

IF EXISTS (SELECT OL.CD_COMPANY, OL.NO_IO, COUNT(DISTINCT OL.NO_PSO_MGMT)
		   FROM MM_QTIO OL
		   LEFT JOIN MM_QTIOH OH ON OH.CD_COMPANY = OL.CD_COMPANY AND OH.NO_IO = OL.NO_IO
		   WHERE OL.CD_COMPANY = @P_CD_COMPANY
		   AND OL.NO_IO IN (SELECT DISTINCT NO_IO
		   					FROM MM_QTIO
		   					WHERE CD_COMPANY = @P_CD_COMPANY
		   					AND NO_PSO_MGMT = @P_NO_SO)
		   AND OH.YN_RETURN = 'N'
		   GROUP BY OL.CD_COMPANY, OL.NO_IO
		   HAVING COUNT(DISTINCT OL.NO_PSO_MGMT) > 1)
BEGIN
	SELECT @V_ERRMSG = '여러건 합쳐서 출고된 수주건 입니다.'                      
	GOTO ERROR
END
ELSE
BEGIN
	UPDATE OH 
	SET OH.CD_QTIOTP = GL.TP_GI,
		OH.FG_TRANS = GL.TP_BUSI,
		OH.YN_RETURN = GL.RET 
	FROM MM_QTIOH OH
	JOIN MM_QTIO OL ON OL.CD_COMPANY = OH.CD_COMPANY AND OL.NO_IO = OH.NO_IO
	JOIN SA_GIRL GL ON GL.CD_COMPANY = OL.CD_COMPANY AND GL.NO_GIR = OL.NO_ISURCV AND GL.SEQ_GIR = OL.NO_ISURCVLINE
	WHERE OL.CD_COMPANY = @P_CD_COMPANY
	AND OL.NO_PSO_MGMT = @P_NO_SO
	AND OH.YN_RETURN = 'N'	
END

UPDATE OL
SET OL.YN_PURSALE = EP.YN_SALE,
	OL.FG_TPIO = GL.TP_IV,
	OL.CD_QTIOTP = GL.TP_GI,
	OL.FG_TRANS = GL.TP_BUSI,
	OL.YN_AM = EP.YN_AM,
	OL.FG_IO = EP.FG_IO
FROM MM_QTIO OL
JOIN MM_QTIOH OH ON OH.CD_COMPANY = OL.CD_COMPANY AND OH.NO_IO = OL.NO_IO
JOIN SA_GIRL GL ON GL.CD_COMPANY = OL.CD_COMPANY AND GL.NO_GIR = OL.NO_ISURCV AND GL.SEQ_GIR = OL.NO_ISURCVLINE
LEFT JOIN MM_EJTP EP ON EP.CD_COMPANY = GL.CD_COMPANY AND EP.CD_QTIOTP = GL.TP_GI
WHERE OL.CD_COMPANY = @P_CD_COMPANY
AND OL.NO_PSO_MGMT = @P_NO_SO
AND OH.YN_RETURN = 'N'

-- PRINT '-- 매출'

--UPDATE IH
--SET IH.FG_TRANS = OL.FG_TRANS
--FROM SA_IVH IH
--JOIN SA_IVL IL ON IL.CD_COMPANY = IH.CD_COMPANY AND IL.NO_IV = IH.NO_IV
--JOIN MM_QTIO OL ON OL.CD_COMPANY = IL.CD_COMPANY AND OL.NO_IO = IL.NO_IO AND OL.NO_IOLINE = IL.NO_IOLINE
--WHERE IL.CD_COMPANY = @P_CD_COMPANY
--AND IL.NO_SO = @P_NO_SO

--UPDATE IL
--SET IL.TP_IV = OL.FG_TPIO,
--	IL.YN_RETURN = OH.YN_RETURN,
--	IL.FG_TRANS = OL.FG_TRANS
--FROM SA_IVL IL
--JOIN MM_QTIO OL ON OL.CD_COMPANY = IL.CD_COMPANY AND OL.NO_IO = IL.NO_IO AND OL.NO_IOLINE = IL.NO_IOLINE
--JOIN MM_QTIOH OH ON OH.CD_COMPANY = OL.CD_COMPANY AND OH.NO_IO = OL.NO_IO
--WHERE IL.CD_COMPANY = @P_CD_COMPANY
--AND IL.NO_SO = @P_NO_SO

-- PRINT '-- 출고반품'

--UPDATE SA_GIRH
--SET TP_GI = '231'
--WHERE CD_COMPANY = 'K100'
--AND NO_GIR = 'RT2016020026'

--UPDATE SA_GIRL
--SET TP_GI = '231'
--WHERE CD_COMPANY = 'K100'
--AND NO_GIR = 'RT2016020026'

--UPDATE OH 
--SET OH.CD_QTIOTP = GL.TP_GI,
--	OH.FG_TRANS = GL.TP_BUSI,
--	OH.YN_RETURN = GL.RET 
--FROM MM_QTIOH OH
--JOIN MM_QTIO OL ON OL.CD_COMPANY = OH.CD_COMPANY AND OL.NO_IO = OH.NO_IO
--JOIN SA_GIRL GL ON GL.CD_COMPANY = OL.CD_COMPANY AND GL.NO_GIR = OL.NO_ISURCV AND GL.SEQ_GIR = OL.NO_ISURCVLINE
--WHERE OL.CD_COMPANY = 'K100'
--AND OL.NO_ISURCV = 'RT2016020026'

--UPDATE OL
--SET OL.YN_PURSALE = EP.YN_SALE,
--	OL.FG_TPIO = GL.TP_IV,
--	OL.CD_QTIOTP = GL.TP_GI,
--	OL.FG_TRANS = GL.TP_BUSI,
--	OL.YN_AM = EP.YN_AM,
--	OL.FG_IO = EP.FG_IO
--FROM MM_QTIO OL
--JOIN MM_QTIOH OH ON OH.CD_COMPANY = OL.CD_COMPANY AND OH.NO_IO = OL.NO_IO
--JOIN SA_GIRL GL ON GL.CD_COMPANY = OL.CD_COMPANY AND GL.NO_GIR = OL.NO_ISURCV AND GL.SEQ_GIR = OL.NO_ISURCVLINE
--LEFT JOIN MM_EJTP EP ON EP.CD_COMPANY = GL.CD_COMPANY AND EP.CD_QTIOTP = GL.TP_GI
--WHERE OL.CD_COMPANY = 'K100'
--AND OL.NO_ISURCV = 'RT2016020026'

COMMIT TRAN SP_CZ_SA_SO_TP_SO_U

END TRY
BEGIN CATCH
	ROLLBACK TRAN SP_CZ_SA_SO_TP_SO_U
	SELECT @V_ERRMSG = ERROR_MESSAGE()
	GOTO ERROR
END CATCH

RETURN
ERROR: 
RAISERROR(@V_ERRMSG, 16, 1)
ROLLBACK TRAN SP_CZ_SA_SO_TP_SO_U

GO

