USE [NEOE]
GO
/****** Object:  StoredProcedure [NEOE].[SP_CZ_PR_MATCHING_DEACTIVATE_SUB_S]    Script Date: 2022-11-21 오후 7:29:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_PR_MATCHING_DEACTIVATE_SUB_S]          
(
	@P_CD_COMPANY		NVARCHAR(7),
	@P_CD_PLANT			NVARCHAR(7),
	@P_STA_DEACTIVATE   NVARCHAR(4),
	@P_NO_ID			NVARCHAR(10)
)  
AS
   
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT 'N' AS S,
	   MD.NO_ID,
	   MD.STA_DEACTIVATE,
	   MD.DC_RMK,
	   MD.YN_DEACTIVATE
FROM CZ_PR_MATCHING_DEACTIVATE MD
WHERE MD.CD_COMPANY = @P_CD_COMPANY
AND MD.CD_PLANT = @P_CD_PLANT
AND (ISNULL(@P_STA_DEACTIVATE, '') = '' OR MD.STA_DEACTIVATE = @P_STA_DEACTIVATE)
AND (ISNULL(@P_NO_ID, '') = '' OR MD.NO_ID LIKE '%' + @P_NO_ID + '%')
