USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_FI_CARD_VERIFYL_07_S]    Script Date: 2016-12-28 오후 3:03:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_FI_CARD_VERIFYL_07_S]
(
	@P_CARD_NO		VARCHAR(20),
	@P_APPR_NO		VARCHAR(20)
)
AS  

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT CARDNO AS ACCT_NO,
	   APPRNO AS ADMIN_NO,
	   SENDDATE,
	   ORGNAPPRDATE,
	   BILAMT,
	   BILFEE,
	   BILTOT,
	   ACQUEXCH,
	   USDACQUTOT,
	   SETTDATE,
	   MERCHNAME,
	   WORKDATE
FROM [EBRANCH].[ebranch].[dbo].CATS_TMP_BILL
WHERE CARDNO = @P_CARD_NO
AND APPRNO = @P_APPR_NO

GO