USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_FI_CARD_VERIFYL_01_S]    Script Date: 2016-12-28 오후 3:03:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_FI_CARD_VERIFYL_01_S]
(
	@P_CD_COMPANY	VARCHAR(10),
	@P_ACCT_NO		VARCHAR(20),
	@P_ADMIN_NO		VARCHAR(20)
)
AS  

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

SELECT CT.ACCT_NO,
	   CT.ADMIN_NO,
	   CT.SEQ,
	   CT.TRADE_DATE,
	   CT.TRADE_TIME,
	   CT.TRADE_PLACE,
	   CT.S_IDNO,
	   CT.MCC_CODE_NAME,
	   CT.CURRENCY,
	   CT.AQUI_RATE,
	   CT.AQUI_DOLL,
	   CT.SUPPLY_AMT,
	   CT.VAT_AMT,
	   CT.ADMIN_AMT,
	   CT.NO_DOCU,
	   CT.LINE_NO,
	   FD.ST_DOCU
FROM CARD_TEMP CT
LEFT JOIN FI_DOCU FD ON FD.CD_COMPANY = CT.C_CODE AND FD.NO_DOCU = CT.NO_DOCU AND FD.NO_DOLINE = CT.LINE_NO
WHERE CT.C_CODE = @P_CD_COMPANY
AND CT.ACCT_NO = @P_ACCT_NO
AND CT.ADMIN_NO = @P_ADMIN_NO
ORDER BY CT.TRADE_DATE, CT.TRADE_TIME

GO