USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_FI_CARD_VERIFYL_05_S]    Script Date: 2016-12-28 오후 3:03:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_FI_CARD_VERIFYL_05_S]
(
	@P_CARD_NO		VARCHAR(20),
	@P_APPR_NO		VARCHAR(20)
)
AS  

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT CARDNO AS ACCT_NO,
	   APPRNO AS ADMIN_NO,
	   SENDDATE,
	   TRANSDATE,
	   TRANSTIME,
	   CURRCODE,
	   APPREXCH,
	   (CASE WHEN CLASS = 'B' THEN -USDAPPRTOT ELSE USDAPPRTOT END) AS USDAPPRTOT,
	   (CASE WHEN CLASS = 'B' THEN -APPRAMT ELSE APPRAMT END) AS APPRAMT,
	   (CASE WHEN CLASS = 'B' THEN -VAT ELSE VAT END) AS VAT,
	   (CASE WHEN CLASS = 'B' THEN -APPRTOT ELSE APPRTOT END) AS APPRTOT,
	   MERCHNAME,
	   MCCNAME
FROM [EBRANCH].[ebranch].[dbo].CATS_TMP_APPROVAL
WHERE CARDNO = @P_CARD_NO
AND APPRNO = @P_APPR_NO

GO