USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_FI_CARD_VERIFYL_06_S]    Script Date: 2016-12-28 오후 3:03:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_FI_CARD_VERIFYL_06_S]
(
	@P_CARD_NO		VARCHAR(20),
	@P_APPR_NO		VARCHAR(20)
)
AS  

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT CARDNO AS ACCT_NO,
	   APPRNO AS ADMIN_NO,
	   SENDDATE,
	   APPRDATE,
	   PURCHDATE,
	   PURCHTIME,
	   SETTDATE,
	   CURRCODE,
	   (CASE WHEN CLASS = 'B' THEN -ACQUTOT ELSE ACQUTOT END) AS ACQUTOT,
	   ACQUEXCH,
	   (CASE WHEN CLASS = 'B' THEN -USDACQUTOT ELSE USDACQUTOT END) AS USDACQUTOT,
	   (CASE WHEN CLASS = 'B' THEN -PURCHTOT ELSE PURCHTOT END) AS PURCHTOT,
	   MERCHNAME,
	   MCCNAME,
	   (CASE WHEN CLASS = 'B' THEN -APPRAMT ELSE APPRAMT END) AS APPRAMT,
	   (CASE WHEN CLASS = 'B' THEN -VAT ELSE VAT END) AS VAT
FROM [EBRANCH].[ebranch].[dbo].CATS_TMP_ACQUIRE
WHERE CARDNO = @P_CARD_NO
AND APPRNO = @P_APPR_NO

GO