USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_HR_EVALU_DLG1]    Script Date: 2015-11-17 오전 10:08:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/*******************************************  
**  System  : 인사관리  
**  Sub System : 고과관리  
**  Page  : 평가표  
**  Desc  : 관련정보 조회  
**    
**  Return Values  
**  
**  작    성    자  : 강연철  
**  작    성    일 : 2015.01.20  
**  수    정    자  :   
**  수  정  내  용  :   
*********************************************  
** Change History  
*********************************************  
*********************************************/  
  
ALTER PROCEDURE [NEOE].[SP_CZ_HR_EVALU_DLG1]  
(  
	@P_CD_COMPANY	NVARCHAR(7),  
	@P_NO_EMP		NVARCHAR(10),
	@P_ST_DAY		NVARCHAR(6),
	@P_DT_DAY		NVARCHAR(6)
)  
AS  

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT A.NO_EMP,
	   C.NM_SYSDEF AS SECTION, 
	   A.CD_PRIZE AS CODE, 
	   B.NM_PRIZE AS NM_PDI, 
	   (SELECT NM_SYSDEF FROM MA_CODEDTL WHERE CD_COMPANY = A.CD_COMPANY AND CD_FIELD = 'HR_H000049' AND CD_SYSDEF = A.TP_PRIZE) AS GRD,
	   A.DT_PRIZE AS DT_PDI,		
	   A.DC_ITEM AS DC_PDI, 
	   A.AM_PRIZE AS PAY,
	   A.DC_RMK
FROM HR_HUPRIZE AS A
JOIN HR_HUPCODE AS B ON A.CD_COMPANY = B.CD_COMPANY AND A.CD_PRIZE = B.CD_PRIZE AND A.GRD_PRIZE = B.GRD_PRIZE
JOIN MA_CODEDTL AS C ON A.CD_COMPANY = C.CD_COMPANY AND C.CD_FIELD = 'HR_H000047' AND C.CD_SYSDEF = '001'
WHERE A.CD_COMPANY = @P_CD_COMPANY
AND A.NO_EMP = @P_NO_EMP
AND	(SUBSTRING(A.DT_PRIZE, 1, 6) BETWEEN @P_ST_DAY AND @P_DT_DAY)
UNION ALL
SELECT A.NO_EMP,
	   C.NM_SYSDEF AS SECTION, 
	   A.CD_DISCIP AS CODE, 
	   B.NM_DISCIP AS NM_PDI, 
	   '' AS GRD,
	   A.DT_DISCIP AS DT_PDI,
	   A.DC_ITEM AS DC_PDI, 
	   A.AM_DISCIP AS PAY,
	   A.DC_RMK
FROM HR_HUDISCIP AS A
JOIN HR_HUDCODE AS B ON A.CD_COMPANY = B.CD_COMPANY AND	A.CD_DISCIP = B.CD_DISCIP
JOIN MA_CODEDTL AS C ON A.CD_COMPANY = C.CD_COMPANY AND C.CD_FIELD = 'HR_H000047' AND C.CD_SYSDEF = '002'
WHERE A.CD_COMPANY = @P_CD_COMPANY
AND A.NO_EMP = @P_NO_EMP
AND	(SUBSTRING(A.DT_DISCIP, 1, 6) BETWEEN @P_ST_DAY AND @P_DT_DAY)
AND	(A.DT_EXPIRE >= SUBSTRING(NEOE.SF_SYSDATE(GETDATE()), 0 , 8) OR A.DT_EXPIRE = '' OR A.DT_EXPIRE IS NULL)
ORDER BY SECTION DESC, DT_PDI ASC, CODE ASC

GO