USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_HR_PEVALU_S1]    Script Date: 2015-11-04 오후 3:28:42 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


/*******************************************
**  System		: 인사관리
**  Sub System	: 인사평가
**  Page		: 평가등록
**  Desc		: HEADER 조회
**  
**  Return Values
**
**  작    성    자 	: 강연철
**  작    성    일	: 2015.05.28
**  수    정    자  : 
**  수  정  내  용  : 
*********************************************
** Change History
*********************************************
*********************************************/

ALTER PROCEDURE [NEOE].[SP_CZ_HR_PEVALU_S1]
(
	@P_CD_EVALU		NVARCHAR(8),
	@P_CD_EVTYPE	NVARCHAR(3),
	@P_CD_EVNUMBER	NVARCHAR(3),
	@P_CD_GROUP		NVARCHAR(3),
	@P_NO_EMPM		NVARCHAR(10)
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT HN.CD_COMPANY,
	   HN.CD_BIZAREA,
	   HN.CD_EVALU,
	   HN.CD_EVTYPE,
	   HN.CD_EVNUMBER,
	   PC.YN_OBJECT,
	   HN.CD_GROUP,
	   HN.NO_EMPM,
	   HN.NO_EMPAN,
	   EP.NM_KOR,
	   CM.DC_COMMENTS AS COMMENT1, 
	   CT.DC_COMMENTS AS COMMENT2
FROM HR_PEVALU_HUMEMPAN HN
LEFT JOIN MA_EMP EP ON EP.CD_COMPANY = HN.CD_BIZAREA AND EP.NO_EMP = HN.NO_EMPAN
LEFT JOIN HR_PEVALU_CODE PC ON PC.CD_COMPANY = HN.CD_COMPANY AND PC.CD_EVALU = HN.CD_EVALU AND PC.CD_FIELD = '100' AND PC.YN_USE = 'Y' AND PC.CD_HCODE = HN.CD_EVTYPE
LEFT JOIN HR_PEVALU_CMTS CM ON CM.CD_COMPANY = HN.CD_COMPANY AND CM.CD_EVALU = HN.CD_EVALU AND CM.CD_EVTYPE	= HN.CD_EVTYPE AND CM.CD_EVNUMBER = HN.CD_EVNUMBER AND CM.NO_EMPM = HN.NO_EMPM AND CM.NO_EMPAN = HN.NO_EMPAN
LEFT JOIN HR_PEVALU_CODE BF ON BF.CD_COMPANY = HN.CD_COMPANY AND BF.CD_EVALU = HN.CD_EVALU AND BF.CD_FIELD = '300' AND BF.YN_USE = 'Y' AND BF.CD_HCODE = HN.CD_EVNUMBER
LEFT JOIN (SELECT CD_COMPANY, CD_EVALU, CD_EVTYPE, CD_EVNUMBER, NO_EMPAN, MAX(DC_COMMENTS) AS DC_COMMENTS 
		   FROM HR_PEVALU_CMTS
		   GROUP BY CD_COMPANY, CD_EVALU, CD_EVTYPE, CD_EVNUMBER, NO_EMPAN) CT 
ON CT.CD_COMPANY = HN.CD_COMPANY AND CT.CD_EVALU = HN.CD_EVALU AND CT.CD_EVTYPE = HN.CD_EVTYPE AND CT.CD_EVNUMBER = BF.CD_HCODE_BF AND CT.NO_EMPAN = HN.NO_EMPAN
WHERE HN.CD_COMPANY <> 'TEST'
AND HN.CD_EVALU	= @P_CD_EVALU
AND	HN.CD_EVTYPE = @P_CD_EVTYPE
AND	HN.CD_EVNUMBER = @P_CD_EVNUMBER
AND	HN.CD_GROUP	= @P_CD_GROUP
AND	HN.NO_EMPM = @P_NO_EMPM

GO