USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_PACK_REG_SUBH_S]    Script Date: 2015-09-10 오전 10:49:04 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER PROCEDURE [NEOE].[SP_CZ_SA_PACK_REG_SUBH_S]
(
	@P_CD_COMPANY		NVARCHAR(7),
	@P_NO_GIR			NVARCHAR(20),
	@P_DT_GIR_FROM		NVARCHAR(8),
	@P_DT_GIR_TO		NVARCHAR(8)
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT GH.CD_COMPANY,
	   MC.NM_COMPANY,
	   GH.NO_GIR, 
	   GH.DT_GIR, 
	   GH.CD_PARTNER, 
	   MP.LN_PARTNER AS NM_PARTNER, 
	   GH.NO_IMO, 
	   MH.NO_HULL, 
	   MH.NM_VESSEL
FROM (SELECT GH.CD_COMPANY,
	  		 GH.NO_GIR,
	  		 GH.DT_GIR,
	  		 GH.CD_PARTNER,
	  		 GD.NO_IMO
	  FROM SA_GIRH GH
	  LEFT JOIN CZ_SA_GIRH_WORK_DETAIL GD ON GD.CD_COMPANY = GH.CD_COMPANY AND GD.NO_GIR = GH.NO_GIR
	  LEFT JOIN (SELECT GL.CD_COMPANY,
				 	    GL.NO_GIR,
				 	    ISNULL(SUM(GL.QT_GIR), 0) AS QT_GIR,
				 	    ISNULL(SUM(PL.QT_PACK), 0) AS QT_PACK
				 FROM SA_GIRL GL
				 LEFT JOIN (SELECT CD_COMPANY, NO_GIR, SEQ_GIR,
		   		                   SUM(QT_PACK) AS QT_PACK 
		   		            FROM CZ_SA_PACKL
		   		            GROUP BY CD_COMPANY, NO_GIR, SEQ_GIR) PL 
		         ON PL.CD_COMPANY = GL.CD_COMPANY AND PL.NO_GIR = GL.NO_GIR AND PL.SEQ_GIR = GL.SEQ_GIR
				 WHERE GL.CD_ITEM NOT LIKE 'SD%'
				 GROUP BY GL.CD_COMPANY, GL.NO_GIR) GL
	  ON GL.CD_COMPANY = GH.CD_COMPANY AND GL.NO_GIR = GH.NO_GIR
	  WHERE GH.CD_COMPANY = @P_CD_COMPANY
	  AND ISNULL(GH.STA_GIR, '') = 'C'
	  AND (ISNULL(@P_NO_GIR, '') = '' OR GH.NO_GIR = @P_NO_GIR)
	  AND (GH.DT_GIR BETWEEN @P_DT_GIR_FROM AND @P_DT_GIR_TO)
	  AND GL.QT_GIR > GL.QT_PACK
	  UNION ALL
	  SELECT PH.CD_COMPANY,
	  		 PH.NO_GIR,
	  		 PH.DT_GIR,
	  		 PH.CD_PARTNER,
	  		 PD.NO_IMO
	  FROM CZ_SA_GIRH_PACK PH
	  LEFT JOIN CZ_SA_GIRH_PACK_DETAIL PD ON PD.CD_COMPANY = PH.CD_COMPANY AND PD.NO_GIR = PH.NO_GIR
	  LEFT JOIN (SELECT GL.CD_COMPANY,
				 	    GL.NO_GIR,
				 	    ISNULL(SUM(GL.QT_GIR), 0) AS QT_GIR,
				 	    ISNULL(SUM(PL.QT_PACK), 0) AS QT_PACK
				 FROM CZ_SA_GIRL_PACK GL
				 LEFT JOIN (SELECT CD_COMPANY, NO_GIR, SEQ_GIR,
		   		                   SUM(QT_PACK) AS QT_PACK 
		   		            FROM CZ_SA_PACKL
		   		            GROUP BY CD_COMPANY, NO_GIR, SEQ_GIR) PL 
		         ON PL.CD_COMPANY = GL.CD_COMPANY AND PL.NO_GIR = GL.NO_GIR AND PL.SEQ_GIR = GL.SEQ_GIR 
				 WHERE GL.CD_ITEM NOT LIKE 'SD%'
				 GROUP BY GL.CD_COMPANY, GL.NO_GIR) PL
	  ON PL.CD_COMPANY = PH.CD_COMPANY AND PL.NO_GIR = PH.NO_GIR
	  WHERE PH.CD_COMPANY = @P_CD_COMPANY
	  AND (ISNULL(PH.STA_GIR, '') = 'R' OR ISNULL(PH.STA_GIR, '') = 'C')
	  AND (ISNULL(@P_NO_GIR, '') = '' OR PH.NO_GIR = @P_NO_GIR)
	  AND (PH.DT_GIR BETWEEN @P_DT_GIR_FROM AND @P_DT_GIR_TO)
	  AND PL.QT_GIR > PL.QT_PACK) GH
LEFT JOIN MA_PARTNER MP ON MP.CD_COMPANY = GH.CD_COMPANY AND MP.CD_PARTNER = GH.CD_PARTNER
LEFT JOIN CZ_MA_HULL MH ON MH.NO_IMO = GH.NO_IMO
LEFT JOIN MA_COMPANY MC ON MC.CD_COMPANY = GH.CD_COMPANY

GO