USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_MA_EXCHANGE_S]    Script Date: 2015-06-18 오후 1:24:26 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER PROCEDURE [NEOE].[SP_CZ_MA_EXCHANGE_S]
(  
	@P_CD_COMPANY	NVARCHAR(7),
	@P_LANGUAGE		NVARCHAR(5) = 'KR',
	@P_YYMMDD		NVARCHAR(6),
	@P_NO_SEQ		NUMERIC(2, 0),  
	@P_CURR_SOUR	NVARCHAR(3),  
	@P_CURR_DEST	NVARCHAR(3)  
) AS  

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

IF @P_NO_SEQ = 0
BEGIN
	SELECT	CD_COMPANY, YYMMDD, NO_SEQ, CURR_SOUR, MAX(NM_SOUR) NM_SOUR, CURR_DEST, MAX(NM_DEST) NM_DEST, 
			MAX(RATE_BASE) RATE_BASE, MAX(RATE_BUY) RATE_BUY, MAX(RATE_SALE) RATE_SALE, ISNULL(MAX(RATE_PURCHASE), 0) RATE_PURCHASE, ISNULL(MAX(RATE_SALES), 0) RATE_SALES,
			MAX(QUOTATION_TIME) QUOTATION_TIME
	FROM	(
			SELECT	EX.CD_COMPANY,
					EX.YYMMDD,   
					EX.NO_SEQ, 
					EX.CURR_SOUR,
					(SELECT (CASE @P_LANGUAGE WHEN 'KR' THEN NM_SYSDEF
											  WHEN 'US' THEN NM_SYSDEF_E
											  WHEN 'JP' THEN NM_SYSDEF_JP
											  WHEN 'CH' THEN NM_SYSDEF_CH END)
					 FROM MA_CODEDTL
					 WHERE CD_COMPANY = EX.CD_COMPANY
					 AND CD_FIELD = 'MA_B000005'
					 AND CD_SYSDEF = EX.CURR_SOUR) AS NM_SOUR,
					EX.CURR_DEST,
					(SELECT (CASE @P_LANGUAGE WHEN 'KR' THEN NM_SYSDEF
							                  WHEN 'US' THEN NM_SYSDEF_E
							                  WHEN 'JP' THEN NM_SYSDEF_JP
							                  WHEN 'CH' THEN NM_SYSDEF_CH END)
					 FROM MA_CODEDTL
					 WHERE CD_COMPANY = EX.CD_COMPANY
					 AND CD_FIELD = 'MA_B000005'
					 AND CD_SYSDEF = EX.CURR_DEST) AS NM_DEST,
					EX.RATE_BUY,   
					EX.RATE_SALE,
					EX.RATE_BASE,   
					CE.RATE_PURCHASE,
					CE.RATE_SALES,
					EX.QUOTATION_TIME
			FROM    MA_EXCHANGE EX
			LEFT JOIN CZ_MA_EXCHANGE CE ON CE.CD_COMPANY = EX.CD_COMPANY AND CE.YYMMDD = EX.YYMMDD AND CE.NO_SEQ = EX.NO_SEQ AND CE.CURR_SOUR = EX.CURR_SOUR AND CE.CURR_DEST = EX.CURR_DEST
			WHERE   EX.CD_COMPANY = @P_CD_COMPANY 
			AND		((EX.YYMMDD LIKE @P_YYMMDD + '%') OR ((@P_YYMMDD + '%') IS NULL) OR ((@P_YYMMDD + '%') = ''))
			AND		EX.CURR_SOUR = @P_CURR_SOUR
			AND		EX.CURR_DEST = @P_CURR_DEST
			AND		EX.NO_SEQ > @P_NO_SEQ
			
			UNION ALL

			SELECT	@P_CD_COMPANY AS CD_COMPANY, 
				    CONVERT(CHAR(8), DATEADD(D, NUMBER, @P_YYMMDD + '01'), 112) AS YYMMDD,
					(CASE WHEN @P_NO_SEQ = 0 THEN 1 ELSE @P_NO_SEQ END) AS NO_SEQ, 
					@P_CURR_SOUR AS CURR_SOUR,
					(SELECT (CASE @P_LANGUAGE WHEN 'KR' THEN NM_SYSDEF
							 WHEN 'US' THEN NM_SYSDEF_E
							 WHEN 'JP' THEN NM_SYSDEF_JP
							 WHEN 'CH' THEN NM_SYSDEF_CH END)
					 FROM MA_CODEDTL
					 WHERE CD_COMPANY = @P_CD_COMPANY
					 AND CD_FIELD = 'MA_B000005'
					 AND CD_SYSDEF = @P_CURR_SOUR) AS NM_SOUR,
					@P_CURR_DEST AS CURR_DEST,
					(SELECT (CASE @P_LANGUAGE WHEN 'KR' THEN NM_SYSDEF
							 WHEN 'US' THEN NM_SYSDEF_E
							 WHEN 'JP' THEN NM_SYSDEF_JP
							 WHEN 'CH' THEN NM_SYSDEF_CH END)
					 FROM MA_CODEDTL
					 WHERE CD_COMPANY = @P_CD_COMPANY
					 AND CD_FIELD = 'MA_B000005'
					 AND CD_SYSDEF = @P_CURR_DEST) AS NM_DEST,
					0 AS RATE_BASE, 
					0 AS RATE_BUY, 
					0 AS RATE_SALE, 
					0 AS RATE_PURCHASE, 
					0 AS RATE_SALES,
					'' AS QUOTATION_TIME
			FROM	MASTER..SPT_VALUES 
			WHERE	TYPE = 'P' 
			AND		CONVERT(CHAR(6), DATEADD(D, NUMBER, @P_YYMMDD + '01'), 112) = @P_YYMMDD
			) A
	GROUP BY CD_COMPANY, YYMMDD, NO_SEQ, CURR_SOUR, CURR_DEST
	ORDER BY CD_COMPANY, YYMMDD, NO_SEQ DESC
END
ELSE
BEGIN
	SELECT	CD_COMPANY, YYMMDD, NO_SEQ, CURR_SOUR, MAX(NM_SOUR) NM_SOUR, CURR_DEST, MAX(NM_DEST) NM_DEST, 
			MAX(RATE_BASE) RATE_BASE, MAX(RATE_BUY) RATE_BUY, MAX(RATE_SALE) RATE_SALE, MAX(RATE_PURCHASE) RATE_PURCHASE, MAX(RATE_SALES) RATE_SALES,
			MAX(QUOTATION_TIME) QUOTATION_TIME
	FROM	(
			SELECT	EX.CD_COMPANY,
					EX.YYMMDD,   
					EX.NO_SEQ, 
					EX.CURR_SOUR,
					(SELECT (CASE @P_LANGUAGE WHEN 'KR' THEN NM_SYSDEF
							 WHEN 'US' THEN NM_SYSDEF_E
							 WHEN 'JP' THEN NM_SYSDEF_JP
							 WHEN 'CH' THEN NM_SYSDEF_CH END)
					 FROM MA_CODEDTL
					 WHERE CD_COMPANY = EX.CD_COMPANY
					 AND CD_FIELD = 'MA_B000005'
					 AND CD_SYSDEF = EX.CURR_SOUR) AS NM_SOUR,
					EX.CURR_DEST,
					(SELECT (CASE @P_LANGUAGE WHEN 'KR' THEN NM_SYSDEF
							 WHEN 'US' THEN NM_SYSDEF_E
							 WHEN 'JP' THEN NM_SYSDEF_JP
							 WHEN 'CH' THEN NM_SYSDEF_CH END)
					 FROM MA_CODEDTL
					 WHERE CD_COMPANY = EX.CD_COMPANY
					 AND CD_FIELD = 'MA_B000005'
					 AND CD_SYSDEF = EX.CURR_DEST) AS NM_DEST,
					EX.RATE_BUY,   
					EX.RATE_SALE,
					EX.RATE_BASE,   
					CE.RATE_PURCHASE,
					CE.RATE_SALES,
					EX.QUOTATION_TIME
			FROM    MA_EXCHANGE EX
			LEFT JOIN CZ_MA_EXCHANGE CE ON CE.CD_COMPANY = EX.CD_COMPANY AND CE.YYMMDD = EX.YYMMDD AND CE.NO_SEQ = EX.NO_SEQ AND CE.CURR_SOUR = EX.CURR_SOUR AND CE.CURR_DEST = EX.CURR_DEST
			WHERE   EX.CD_COMPANY = @P_CD_COMPANY 
			AND		((EX.YYMMDD LIKE @P_YYMMDD + '%') OR ((@P_YYMMDD + '%') IS NULL) OR ((@P_YYMMDD + '%') = ''))
			AND		EX.CURR_SOUR = @P_CURR_SOUR
			AND		EX.CURR_DEST = @P_CURR_DEST
			AND		EX.NO_SEQ = @P_NO_SEQ
			
			UNION ALL

			SELECT	@P_CD_COMPANY AS CD_COMPANY, 
					CONVERT(CHAR(8), DATEADD(D, NUMBER, @P_YYMMDD + '01'), 112) AS YYMMDD,
					(CASE WHEN @P_NO_SEQ = 0 THEN 1 ELSE @P_NO_SEQ END) AS NO_SEQ, 
					@P_CURR_SOUR AS CURR_SOUR,
					(SELECT (CASE @P_LANGUAGE WHEN 'KR' THEN NM_SYSDEF
							 WHEN 'US' THEN NM_SYSDEF_E
							 WHEN 'JP' THEN NM_SYSDEF_JP
							 WHEN 'CH' THEN NM_SYSDEF_CH END)
					 FROM MA_CODEDTL
					 WHERE CD_COMPANY = @P_CD_COMPANY
					 AND CD_FIELD = 'MA_B000005'
					 AND CD_SYSDEF = @P_CURR_SOUR) AS NM_SOUR,
					@P_CURR_DEST AS CURR_DEST,
					(SELECT (CASE @P_LANGUAGE WHEN 'KR' THEN NM_SYSDEF
							 WHEN 'US' THEN NM_SYSDEF_E
							 WHEN 'JP' THEN NM_SYSDEF_JP
							 WHEN 'CH' THEN NM_SYSDEF_CH END)
					 FROM MA_CODEDTL
					 WHERE CD_COMPANY = @P_CD_COMPANY
					 AND CD_FIELD = 'MA_B000005'
					 AND CD_SYSDEF = @P_CURR_DEST) AS NM_DEST,
					0 AS RATE_BASE, 
					0 AS RATE_BUY, 
					0 AS RATE_SALE, 
					0 AS RATE_PURCHASE, 
					0 AS RATE_SALES, 
					'' AS QUOTATION_TIME
			FROM	MASTER..SPT_VALUES 
			WHERE	TYPE = 'P' 
			AND		CONVERT(CHAR(6), DATEADD(D, NUMBER, @P_YYMMDD + '01'), 112) = @P_YYMMDD
			) A
	GROUP BY CD_COMPANY, YYMMDD, NO_SEQ, CURR_SOUR, CURR_DEST
	ORDER BY CD_COMPANY, YYMMDD, NO_SEQ DESC
END

GO

