USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_MA_HULL_DOM_RPTL_S]    Script Date: 2018-03-07 오전 11:11:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




ALTER PROCEDURE [NEOE].[SP_CZ_MA_HULL_DOM_RPTL_S]
(
	@P_CD_COMPANY      NVARCHAR(7),
	@P_NO_IMO		   NVARCHAR(10),
	@P_TP_DATE		   NVARCHAR(4),
	@P_DT_FROM		   NVARCHAR(8),
	@P_DT_TO		   NVARCHAR(8)
) 
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

DECLARE @P_AM_FSIZE NUMERIC(3, 0)   -- 소수점

IF @P_CD_COMPANY = 'S100'
	SET @P_AM_FSIZE = 2
ELSE
	SET @P_AM_FSIZE = 0

SELECT SH.NO_IMO,
	   SH.NO_SO,
	   SH.DT_SO,
	   IG.NM_ITEMGRP,
	   SL.SEQ_SO,
	   QL.NO_DSP,
	   SL.CD_ITEM,
	   MI.NM_ITEM,
	   QL.CD_ITEM_PARTNER,
	   QL.NM_ITEM_PARTNER,
	   GL.NM_MAIN_CATEGORY,
	   GL.NM_SUB_CATEGORY,
	   MI.UNIT_SO,
	   SL.QT_SO,
	   MC.NM_SYSDEF AS NM_EXCH,
	   SH.RT_EXCH,
	   SL.UM_EX_P,
	   SL.UM_KR_P,
	   SL.AM_EX_P,
	   SL.AM_KR_P,
	   ISNULL(SL.UM_EX_S, SL.UM_SO) AS UM_EX_S,
	   ISNULL(SL.UM_KR_S, ROUND(SL.UM_SO * SH.RT_EXCH, @P_AM_FSIZE)) AS UM_KR_S,
	   ISNULL(SL.AM_EX_S, SL.AM_SO) AS AM_EX_S,
	   ISNULL(SL.AM_KR_S, SL.AM_WONAMT) AS AM_KR_S
FROM SA_SOH SH
LEFT JOIN SA_SOL SL ON SL.CD_COMPANY = SH.CD_COMPANY AND SL.NO_SO = SH.NO_SO
LEFT JOIN CZ_SA_QTNL QL ON QL.CD_COMPANY = SL.CD_COMPANY AND QL.NO_FILE = SL.NO_SO AND QL.NO_LINE = SL.SEQ_SO
LEFT JOIN (SELECT GL.CD_COMPANY, GL.NO_SO, GL.SEQ_SO,
				  MAX(MC.NM_SYSDEF) AS NM_MAIN_CATEGORY,
				  MAX(MC1.NM_SYSDEF) AS NM_SUB_CATEGORY
		   FROM SA_GIRL GL
		   LEFT JOIN CZ_SA_GIRH_WORK_DETAIL WD ON WD.CD_COMPANY = GL.CD_COMPANY AND WD.NO_GIR = GL.NO_GIR
		   LEFT JOIN MA_CODEDTL MC ON MC.CD_COMPANY = WD.CD_COMPANY AND MC.CD_FIELD = 'CZ_SA00006' AND MC.CD_SYSDEF = WD.CD_MAIN_CATEGORY
		   LEFT JOIN MA_CODEDTL MC1 ON MC1.CD_COMPANY = WD.CD_COMPANY AND MC1.CD_FIELD = MC.CD_FLAG1 AND MC1.CD_SYSDEF = WD.CD_SUB_CATEGORY
		   GROUP BY GL.CD_COMPANY, GL.NO_SO, GL.SEQ_SO) GL
ON GL.CD_COMPANY = QL.CD_COMPANY AND GL.NO_SO = QL.NO_FILE AND GL.SEQ_SO = QL.NO_LINE
LEFT JOIN MA_PITEM MI ON MI.CD_COMPANY = SL.CD_COMPANY AND MI.CD_PLANT = SL.CD_PLANT AND MI.CD_ITEM = SL.CD_ITEM
LEFT JOIN MA_ITEMGRP IG ON IG.CD_COMPANY = MI.CD_COMPANY AND IG.CD_ITEMGRP = MI.GRP_ITEM
LEFT JOIN MA_CODEDTL MC ON MC.CD_COMPANY = SH.CD_COMPANY AND MC.CD_FIELD = 'MA_B000005' AND MC.CD_SYSDEF = SH.CD_EXCH
WHERE SH.CD_COMPANY = @P_CD_COMPANY
AND SH.NO_IMO = @P_NO_IMO
AND (@P_TP_DATE <> '001' OR (@P_TP_DATE = '001' AND ISNULL(SH.DT_SO, '') BETWEEN @P_DT_FROM AND @P_DT_TO))
ORDER BY SH.DT_SO DESC, SH.NO_SO, QL.NO_DSP

GO

