USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_MA_HULL_DOM_RPT_U]    Script Date: 2018-03-07 오후 4:45:52 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO






ALTER PROCEDURE [NEOE].[SP_CZ_MA_HULL_DOM_RPT_U] 
(
	@P_CD_COMPANY	NVARCHAR(7),
	@P_NO_IMO		NVARCHAR(10),
	@P_CD_AGENT		NVARCHAR(3),
	@P_CD_PUR		NVARCHAR(3),
	@P_DC_RMK_DOM	NVARCHAR(MAX),
	@P_ID_UPDATE	NVARCHAR(15)
) 
AS 

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

IF EXISTS (SELECT 1 
		   FROM CZ_MA_HULL_RPT
		   WHERE CD_COMPANY = @P_CD_COMPANY
		   AND NO_IMO = @P_NO_IMO)
BEGIN
	UPDATE CZ_MA_HULL_RPT
	SET CD_AGENT = @P_CD_AGENT,
		CD_PUR = @P_CD_PUR,
		DC_RMK_DOM = @P_DC_RMK_DOM,
		ID_UPDATE = @P_ID_UPDATE,
		DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE())
	WHERE CD_COMPANY = @P_CD_COMPANY
	AND NO_IMO = @P_NO_IMO
END
ELSE
BEGIN
	INSERT INTO CZ_MA_HULL_RPT
	(
		CD_COMPANY,
		NO_IMO,
		CD_AGENT,
		CD_PUR,
		DC_RMK_DOM,
		ID_INSERT,
		DTS_INSERT
	)
	VALUES
	(
		@P_CD_COMPANY,
		@P_NO_IMO,
		@P_CD_AGENT,
		@P_CD_PUR,
		@P_DC_RMK_DOM,
		@P_ID_UPDATE,
		NEOE.SF_SYSDATE(GETDATE())
	)
END


GO

