USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_GIRR_REG_SUBH_S]    Script Date: 2015-09-03 오후 6:57:48 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_PU_REQR_REG_SUBH_S]
(  
    @P_CD_COMPANY			NVARCHAR(7),
    @P_DT_FROM				NVARCHAR(8),
    @P_DT_TO				NVARCHAR(8),
    @P_NO_PO				NVARCHAR(20)
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT 'N' AS S,
	   IH.NO_IO,
	   IH.DT_IO,
	   ME.NM_KOR AS NM_KOR,
	   IH.DC_RMK
FROM MM_QTIOH IH
JOIN(SELECT IL.CD_COMPANY,
		    IL.NO_IO
     FROM MM_QTIO IL
     WHERE IL.FG_IO = '001'
     AND ISNULL(IL.QT_UNIT_MM, 0) - ISNULL(IL.QT_RETURN_MM, 0) > 0
	 AND (ISNULL(@P_NO_PO, '') = '' OR IL.NO_PSO_MGMT = @P_NO_PO)
     GROUP BY IL.CD_COMPANY, IL.NO_IO) IL
ON IL.CD_COMPANY = IH.CD_COMPANY AND IL.NO_IO = IH.NO_IO
LEFT JOIN MA_EMP ME ON ME.CD_COMPANY = IH.CD_COMPANY AND ME.NO_EMP = IH.NO_EMP
WHERE IH.CD_COMPANY = @P_CD_COMPANY
AND IH.DT_IO BETWEEN @P_DT_FROM AND @P_DT_TO

GO