USE [NEOE]
GO

/****** Object:  Table [NEOE].[CZ_SA_PACKL_LOG]    Script Date: 2018-01-26 오후 4:18:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [NEOE].[CZ_SA_PACKL_LOG](
	[CD_COMPANY] [nvarchar](7) NOT NULL,
	[NO_GIR] [nvarchar](20) NOT NULL,
	[NO_PACK] [numeric](5, 0) NOT NULL,
	[SEQ_GIR] [numeric](5, 0) NOT NULL,
	[DTS_DELETE] [nvarchar](14) NOT NULL,
	[ID_DELETE] [nvarchar](15) NOT NULL,
	[NM_PROCEDURE] [nvarchar](200) NOT NULL,
	[CD_ITEM] [nvarchar](20) NULL,
	[QT_PACK] [numeric](17, 4) NULL,
	[NO_FILE] [nvarchar](20) NULL,
	[NO_QTLINE] [int] NULL,
	[DTS_INSERT] [nvarchar](14) NULL,
	[ID_INSERT] [nvarchar](15) NULL,
	[DTS_UPDATE] [nvarchar](14) NULL,
	[ID_UPDATE] [nvarchar](15) NULL,
 CONSTRAINT [PK_CZ_SA_PACKL_BACK] PRIMARY KEY CLUSTERED 
(
	[CD_COMPANY] ASC,
	[NO_GIR] ASC,
	[NO_PACK] ASC,
	[SEQ_GIR] ASC,
	[DTS_DELETE] ASC,
	[ID_DELETE] ASC,
	[NM_PROCEDURE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


