USE [NEOE]
GO

/****** Object:  Table [NEOE].[CZ_SA_PACKH_LOG]    Script Date: 2020-12-18 오후 2:10:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [NEOE].[CZ_SA_PACKH_LOG](
	[CD_COMPANY] [nvarchar](7) NOT NULL,
	[NO_GIR] [nvarchar](20) NOT NULL,
	[NO_PACK] [numeric](5, 0) NOT NULL,
	[DTS_DELETE] [nvarchar](14) NOT NULL,
	[ID_DELETE] [nvarchar](15) NOT NULL,
	[NM_PROCEDURE] [nvarchar](200) NOT NULL,
	[NM_PACK] [numeric](5, 0) NULL,
	[DT_PACK] [nvarchar](8) NULL,
	[CD_TYPE] [nvarchar](3) NULL,
	[CD_SIZE] [nvarchar](3) NULL,
	[QT_NET_WEIGHT] [numeric](17, 4) NULL,
	[QT_GROSS_WEIGHT] [numeric](17, 4) NULL,
	[QT_WIDTH] [numeric](17, 4) NULL,
	[QT_LENGTH] [numeric](17, 4) NULL,
	[QT_HEIGHT] [numeric](17, 4) NULL,
	[CD_LOCATION] [nvarchar](20) NULL,
	[DC_RMK] [nvarchar](max) NULL,
	[YN_OUTSOURCING] [nvarchar](1) NULL,
	[NO_GIR_ORG] [nvarchar](20) NULL,
	[NO_PACK_ORG] [numeric](5, 0) NULL,
	[NO_WOODEN] [nvarchar](20) NULL,
	[ID_INSERT] [nvarchar](14) NULL,
	[DTS_INSERT] [nvarchar](15) NULL,
	[ID_UPDATE] [nvarchar](14) NULL,
	[DTS_UPDATE] [nvarchar](15) NULL,
 CONSTRAINT [PK_CZ_SA_PACKH_BACK] PRIMARY KEY CLUSTERED 
(
	[CD_COMPANY] ASC,
	[NO_GIR] ASC,
	[NO_PACK] ASC,
	[DTS_DELETE] ASC,
	[ID_DELETE] ASC,
	[NM_PROCEDURE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [NEOE].[CZ_SA_PACKH_LOG] ADD  CONSTRAINT [DF_CZ_SA_PACKH_BACK_QT_NET_WEIGHT]  DEFAULT ((0)) FOR [QT_NET_WEIGHT]
GO

ALTER TABLE [NEOE].[CZ_SA_PACKH_LOG] ADD  CONSTRAINT [DF_CZ_SA_PACKH_BACK_QT_GROSS_WEIGHT]  DEFAULT ((0)) FOR [QT_GROSS_WEIGHT]
GO


