USE [NEOE]
GO

/****** Object:  View [NEOE].[V_CZ_SA_SOSCH2]    Script Date: 2016-03-29 오후 2:55:31 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




ALTER VIEW [NEOE].[V_CZ_SA_SOSCH2]
AS

SELECT SL.CD_COMPANY,
	   ISNULL(SL.NO_SO, '') AS NO_SO,
	   SL.SEQ_SO,
	   SL.STA_SO,
	   SL.TP_BUSI,
	   SL.NO_PO_PARTNER,
	   SL.NO_POLINE_PARTNER,
	   SL.UNIT_SO,
	   PH.DT_LIMIT,
	   SL.DT_DUEDATE,
	   SL.DT_REQGI,
	   SL.GI_PARTNER,
	   PG.LN_PARTNER AS LN_GI_PARTNER,
	   SL.CD_SL,
	   MSL.NM_SL,
	   SL.CD_PLANT,
	   SD.TP_DLV,
	   SD.TP_DLV_DUE,    
	   QL.NO_DSP,
	   QL.NM_SUBJECT,
	   QL.CD_ITEM_PARTNER,
	   QL.NM_ITEM_PARTNER,
	   SH.DT_SO,
	   ISNULL(SH.TP_SO, '') AS TP_SO,
	   ST.NM_SO,
	   ISNULL(SH.CD_PARTNER, '') AS CD_PARTNER,
	   PS.LN_PARTNER,
	   PS.SN_PARTNER,
	   ISNULL(SH.CD_SALEGRP, '') AS CD_SALEGRP,
	   MS.NM_SALEGRP,
	   SH.NO_EMP,
	   ME.NM_KOR,
	   SH.NO_PROJECT,
	   SP.NM_PROJECT,
	   SH.FG_TRANSPORT,
	   SH.MEMO_CD,
	   SH.CHECK_PEN,
	   ISNULL(SL.CD_ITEM, '') AS CD_ITEM,
	   MI.NM_ITEM,
	   MI.STND_ITEM,
	   MI.GRP_MFG,
	   (CASE WHEN PH.CD_PARTNER IS NULL AND ISNULL(SB.QT_STOCK, 0) > 0 THEN 'STOCK' 
																	   ELSE PH.CD_PARTNER END) AS CD_SUPPLIER,
	   (CASE WHEN PH.LN_PARTNER IS NULL AND ISNULL(SB.QT_STOCK, 0) > 0 THEN 'STOCK' 
																	   ELSE PH.LN_PARTNER END) AS LN_SUPPLIER,
	   MH.NO_IMO,
	   MH.NO_HULL,
	   MH.NM_VESSEL,
	   ISNULL(PH.NO_PO, '') AS NO_PO,
	   (CASE WHEN ISNULL(ST.RET, 'N') = 'N' THEN ISNULL(SL.QT_SO, 0) 
								            ELSE -ISNULL(SL.QT_SO, 0) END) AS QT_SO,
	   ISNULL(SB.QT_STOCK, 0) AS QT_STOCK,
	   ISNULL(SB.QT_BOOK, 0) AS QT_BOOK,
	   (ISNULL(SL.QT_PO, 0) + ISNULL(SB.QT_STOCK, 0)) AS QT_PO,
	   (CASE WHEN QL.TP_BOM = 'P' THEN ISNULL(QO.QT_BOM, 0) 
								  ELSE (ISNULL(QI.QT_IO, 0) + ISNULL(SB.QT_BOOK, 0)) END) AS QT_IN,
	   (CASE WHEN QL.TP_BOM = 'P' THEN ISNULL(QO.QT_BOM_RETURN, 0) 
			                      ELSE ISNULL(QI.QT_IO_RETURN, 0) END) AS QT_IN_RETURN,
	   ISNULL(GL.QT_GIR, 0) AS QT_GIR,
	   ISNULL(PK.QT_GIR, 0) AS QT_GIR_PACK,
	   ISNULL(PK.QT_PACK, 0) AS QT_PACK,
	   ISNULL(QO.QT_IO, 0) AS QT_OUT,
	   ISNULL(QO.QT_IO_RETURN, 0) AS QT_OUT_RETURN,
	   ISNULL(QO.QT_IV, 0) AS QT_IV,
	   PH.DT_PO,
	   QI.DT_IO AS DT_IN,
	   QO.DT_IO AS DT_OUT,
	   GL.DT_LOADING,
	   QO.DT_IV AS DT_IV,
	   RH.AM_RCP_A,
	   RH.DT_RCP,
	   WH.ID_LOG,
	   SH.DC_RMK_TEXT2,
	   MS.CD_CC,
	   MC.NM_CC,
	   OW.WEIGHT,
	   OW.YN_PACK,
	   SL.UM_EX_S,
	   SL.UM_SO,
	   SL.AM_SO,
	   SL.AM_WONAMT,
	   (CASE WHEN WH1.NO_KEY IS NOT NULL THEN 'Y' 
										 ELSE 'N' END) AS YN_PROFORMA,
	   SH.DC_RMK1,
	   SH.CD_PARTNER_GRP,
	   CD.NM_SYSDEF AS NM_PARTNER_GRP,
	   PS.CD_NATION,
	   CD1.NM_SYSDEF AS NM_NATION,
	   ISNULL(SH.YN_CLOSE, 'N') AS YN_CLOSE,
	   SH.TP_TRANS,
	   CD2.NM_SYSDEF + ' ' + SH.PORT_LOADING AS NM_TP_TRANSPORT,
	   ISNULL(GH.YN_AUTO_SUBMIT, 'N') AS YN_AUTO_SUBMIT,
	   DD.DT_EXPECT AS DT_EXPECT_IN,
	   GW.ST_STAT
FROM SA_SOL SL
JOIN MA_PITEM MI ON MI.CD_COMPANY = SL.CD_COMPANY AND MI.CD_PLANT = SL.CD_PLANT AND MI.CD_ITEM = SL.CD_ITEM
JOIN SA_SOH SH ON SH.CD_COMPANY = SL.CD_COMPANY AND SH.NO_SO = SL.NO_SO
LEFT JOIN FI_GWDOCU GW ON GW.CD_COMPANY = 'K100' AND GW.CD_PC = '010000' AND GW.NO_DOCU = SH.NO_DOCU
LEFT JOIN MA_PARTNER PS ON PS.CD_COMPANY = SH.CD_COMPANY AND PS.CD_PARTNER = SH.CD_PARTNER 
LEFT JOIN MA_EMP ME ON ME.CD_COMPANY = SH.CD_COMPANY AND ME.NO_EMP = SH.NO_EMP 
LEFT JOIN MA_SALEGRP MS ON MS.CD_COMPANY = SH.CD_COMPANY AND MS.CD_SALEGRP = SH.CD_SALEGRP
LEFT JOIN SA_PROJECTH SP ON SP.CD_COMPANY = SH.CD_COMPANY AND SP.NO_PROJECT = SH.NO_PROJECT   
LEFT JOIN SA_TPSO ST ON ST.CD_COMPANY = SH.CD_COMPANY AND ST.TP_SO = SH.TP_SO      
LEFT JOIN CZ_SA_QTNL QL ON QL.CD_COMPANY = SL.CD_COMPANY AND QL.NO_FILE = SL.NO_SO AND QL.NO_LINE = SL.SEQ_SO
LEFT JOIN CZ_MA_HULL MH ON MH.NO_IMO = SH.NO_IMO 
LEFT JOIN (SELECT PL.CD_COMPANY, PL.NO_SO, PL.NO_SOLINE,
				  MAX(PH.NO_PO) AS NO_PO,
				  MAX(PH.DT_PO) AS DT_PO,
				  MAX(PH.CD_PARTNER) AS CD_PARTNER,
				  MAX(MP.LN_PARTNER) AS LN_PARTNER,
				  MAX(PL.DT_LIMIT) AS DT_LIMIT 
		   FROM PU_POH PH 
		   LEFT JOIN PU_POL PL ON PL.CD_COMPANY = PH.CD_COMPANY AND PL.NO_PO = PH.NO_PO
		   LEFT JOIN MA_PARTNER MP ON MP.CD_COMPANY = PH.CD_COMPANY AND MP.CD_PARTNER = PH.CD_PARTNER
		   GROUP BY PL.CD_COMPANY, PL.NO_SO, PL.NO_SOLINE) PH
ON  PH.CD_COMPANY = SL.CD_COMPANY AND  PH.NO_SO = SL.NO_SO AND PH.NO_SOLINE = SL.SEQ_SO
LEFT JOIN (SELECT GL.CD_COMPANY, GL.NO_SO, GL.SEQ_SO, 
				  SUM(CASE WHEN GH.YN_RETURN = 'Y' THEN -GL.QT_GIR ELSE GL.QT_GIR END) AS QT_GIR, 
				  MAX(WD.DT_LOADING) AS DT_LOADING 
		   FROM SA_GIRL GL
		   LEFT JOIN SA_GIRH GH ON GH.CD_COMPANY = GL.CD_COMPANY AND GH.NO_GIR = GL.NO_GIR
		   LEFT JOIN CZ_SA_GIRH_WORK_DETAIL WD ON WD.CD_COMPANY = GL.CD_COMPANY AND WD.NO_GIR = GL.NO_GIR
		   GROUP BY GL.CD_COMPANY, GL.NO_SO, GL.SEQ_SO) GL 
ON GL.CD_COMPANY = SL.CD_COMPANY AND GL.NO_SO = SL.NO_SO AND GL.SEQ_SO = SL.SEQ_SO
LEFT JOIN (SELECT PL.CD_COMPANY, PL.NO_SO, PL.SEQ_SO,
		   	      SUM(PL.QT_GIR) AS QT_GIR,
		   	      SUM(PK.QT_PACK) AS QT_PACK 
		   FROM CZ_SA_GIRH_PACK PH
		   LEFT JOIN CZ_SA_GIRL_PACK PL ON PL.CD_COMPANY = PH.CD_COMPANY AND PL.NO_GIR = PH.NO_GIR
		   LEFT JOIN (SELECT CD_COMPANY, NO_GIR, SEQ_GIR,
		   				     SUM(QT_PACK) AS QT_PACK 
		   		      FROM CZ_SA_PACKL
		   			  GROUP BY CD_COMPANY, NO_GIR, SEQ_GIR) PK 
		   ON PK.CD_COMPANY = PL.CD_COMPANY AND PK.NO_GIR = PL.NO_GIR AND PK.SEQ_GIR = PL.SEQ_GIR 
		   GROUP BY PL.CD_COMPANY, PL.NO_SO, PL.SEQ_SO) PK
ON PK.CD_COMPANY = SL.CD_COMPANY AND PK.NO_SO = SL.NO_SO AND PK.SEQ_SO = SL.SEQ_SO
LEFT JOIN (SELECT PL.CD_COMPANY, PL.NO_SO, PL.NO_SOLINE,
		   	      SUM(CASE WHEN OH.YN_RETURN = 'Y' THEN 0 ELSE OL.QT_IO END) AS QT_IO,
				  SUM(CASE WHEN OH.YN_RETURN = 'Y' THEN -OL.QT_IO ELSE 0 END) AS QT_IO_RETURN,
		   	      ISNULL(MAX(OH.DT_IO), '') AS DT_IO
		   FROM PU_POL PL
		   LEFT JOIN MM_QTIO OL ON OL.CD_COMPANY = PL.CD_COMPANY AND OL.NO_PSO_MGMT = PL.NO_PO AND OL.NO_PSOLINE_MGMT = PL.NO_LINE
		   LEFT JOIN MM_QTIOH OH ON OH.CD_COMPANY = OL.CD_COMPANY AND OH.NO_IO = OL.NO_IO
		   WHERE OL.FG_PS = '1'
		   GROUP BY PL.CD_COMPANY, PL.NO_SO, PL.NO_SOLINE) QI 
ON QI.CD_COMPANY = SL.CD_COMPANY AND QI.NO_SO = SL.NO_SO AND QI.NO_SOLINE = SL.SEQ_SO
LEFT JOIN (SELECT SL.CD_COMPANY, SL.NO_SO, SL.SEQ_SO,
		   		  SUM(CASE WHEN OH.YN_RETURN = 'Y' THEN 0 
												   ELSE (CASE WHEN OL.FG_PS = '2' THEN OL.QT_IO 
																				  ELSE 0 END) END) AS QT_IO,
				  SUM(CASE WHEN OH.YN_RETURN = 'Y' THEN (CASE WHEN OL.FG_PS = '2' THEN -OL.QT_IO 
																				  ELSE 0 END) 
												   ELSE 0 END) AS QT_IO_RETURN,
				  SUM(CASE WHEN OH.YN_RETURN = 'Y' THEN 0 
												   ELSE (CASE WHEN OL.FG_PS = '1' THEN OL.QT_IO 
																				  ELSE 0 END) END) AS QT_BOM,
				  SUM(CASE WHEN OH.YN_RETURN = 'Y' THEN (CASE WHEN OL.FG_PS = '1' THEN -OL.QT_IO 
																				  ELSE 0 END) 
												   ELSE 0 END) AS QT_BOM_RETURN,
				  SUM(CASE WHEN OH.YN_RETURN = 'Y' THEN -IL.QT_CLS 
												   ELSE IL.QT_CLS END) AS QT_IV,
		   		  ISNULL(MAX(OH.DT_IO), '') AS DT_IO,
				  ISNULL(MAX(IH.DT_PROCESS), '') AS DT_IV
		   FROM SA_SOL SL
		   LEFT JOIN SA_SOH SH ON SH.CD_COMPANY = SL.CD_COMPANY AND SH.NO_SO = SL.NO_SO
		   LEFT JOIN MM_QTIO OL ON OL.CD_COMPANY = SL.CD_COMPANY AND OL.NO_PSO_MGMT = SL.NO_SO AND OL.NO_PSOLINE_MGMT = SL.SEQ_SO
		   LEFT JOIN MM_QTIOH OH ON OH.CD_COMPANY = OL.CD_COMPANY AND OH.NO_IO = OL.NO_IO
		   LEFT JOIN SA_IVL IL ON IL.CD_COMPANY = OL.CD_COMPANY AND IL.NO_IO = OL.NO_IO AND IL.NO_IOLINE = OL.NO_IOLINE AND IL.CD_ITEM = SL.CD_ITEM
		   LEFT JOIN SA_IVH IH ON IH.CD_COMPANY = IL.CD_COMPANY AND IH.NO_IV = IL.NO_IV
		   GROUP BY SL.CD_COMPANY, SL.NO_SO, SL.SEQ_SO) QO 
ON QO.CD_COMPANY = SL.CD_COMPANY AND QO.NO_SO = SL.NO_SO AND QO.SEQ_SO = SL.SEQ_SO
LEFT JOIN (SELECT OW.CD_COMPANY, OW.NO_SO, 
				  SUM(OW.WEIGHT) AS WEIGHT,
				  (CASE WHEN MAX(ISNULL(OW.DC_RMK, '')) = '' THEN 'N' ELSE 'Y' END) AS YN_PACK
		   FROM (SELECT PL.CD_COMPANY, PL.NO_SO, OH.NO_IO, OH.WEIGHT, OH.DC_RMK
				 FROM PU_POL PL
				 JOIN MM_QTIO OL ON OL.CD_COMPANY = PL.CD_COMPANY AND OL.NO_PSO_MGMT = PL.NO_PO AND OL.NO_PSOLINE_MGMT = PL.NO_LINE
				 JOIN MM_QTIOH OH ON OH.CD_COMPANY = OL.CD_COMPANY AND OH.NO_IO = OL.NO_IO
				 WHERE OL.FG_PS = '1'
				 GROUP BY PL.CD_COMPANY, PL.NO_SO, OH.NO_IO, OH.WEIGHT, OH.DC_RMK) OW
		   GROUP BY OW.CD_COMPANY, OW.NO_SO) OW
ON OW.CD_COMPANY = SL.CD_COMPANY AND OW.NO_SO = SL.NO_SO
LEFT JOIN CZ_SA_STOCK_BOOK SB ON SB.CD_COMPANY = SL.CD_COMPANY AND SB.NO_FILE = SL.NO_SO AND SB.NO_LINE = SL.SEQ_SO
LEFT JOIN MA_PARTNER PG ON PG.CD_COMPANY = SL.CD_COMPANY AND PG.CD_PARTNER = SL.GI_PARTNER
LEFT JOIN MA_PLANT MPT ON MPT.CD_COMPANY = SL.CD_COMPANY AND MPT.CD_PLANT = SL.CD_PLANT
LEFT JOIN MA_SL MSL ON MSL.CD_COMPANY = MPT.CD_COMPANY AND MSL.CD_PLANT = MPT.CD_PLANT AND MSL.CD_BIZAREA = MPT.CD_BIZAREA AND MSL.CD_SL = SL.CD_SL
LEFT JOIN SA_SOL_DLV SD ON SD.CD_COMPANY = SL.CD_COMPANY AND SD.NO_SO = SL.NO_SO AND SD.SEQ_SO = SL.SEQ_SO AND SD.FG_TRACK = 'SO'   
LEFT JOIN (SELECT CD_COMPANY, NO_PROJECT, 
				  ISNULL(SUM(AM_RCP_A), 0) AS AM_RCP_A, 
				  MAX(DT_RCP) AS DT_RCP 
		   FROM SA_RCPH
		   GROUP BY CD_COMPANY, NO_PROJECT) RH 
ON RH.CD_COMPANY = SH.CD_COMPANY AND RH.NO_PROJECT = SH.NO_PROJECT
LEFT JOIN CZ_MA_WORKFLOWH WH ON WH.CD_COMPANY = SL.CD_COMPANY AND WH.NO_KEY = SL.NO_SO AND WH.TP_STEP = '08'
LEFT JOIN CZ_MA_WORKFLOWH WH1 ON WH1.CD_COMPANY = SL.CD_COMPANY AND WH1.NO_KEY = SL.NO_SO AND WH1.TP_STEP = '56'
LEFT JOIN MA_CC MC ON MC.CD_COMPANY = MS.CD_COMPANY AND MC.CD_CC = MS.CD_CC
LEFT JOIN MA_CODEDTL CD ON CD.CD_COMPANY = SH.CD_COMPANY AND CD.CD_FIELD = 'MA_B000065' AND CD.CD_SYSDEF = SH.CD_PARTNER_GRP
LEFT JOIN MA_CODEDTL CD1 ON CD1.CD_COMPANY = PS.CD_COMPANY AND CD1.CD_FIELD = 'MA_B000020' AND CD1.CD_SYSDEF = PS.CD_NATION
LEFT JOIN MA_CODEDTL CD2 ON CD2.CD_COMPANY = SH.CD_COMPANY AND CD2.CD_FIELD = 'TR_IM00003' AND CD2.CD_SYSDEF = SH.TP_TRANS
LEFT JOIN (SELECT GL.CD_COMPANY, GL.NO_SO, 
				  MAX(WD.YN_AUTO_SUBMIT) AS YN_AUTO_SUBMIT 
		   FROM CZ_SA_GIRH_WORK_DETAIL WD
		   LEFT JOIN SA_GIRL GL ON GL.CD_COMPANY = WD.CD_COMPANY AND GL.NO_GIR = WD.NO_GIR
		   GROUP BY GL.CD_COMPANY, GL.NO_SO) GH
ON GH.CD_COMPANY = SH.CD_COMPANY AND GH.NO_SO = SH.NO_SO
LEFT JOIN (SELECT CD_COMPANY, NO_SO, MAX(DT_EXPECT) AS DT_EXPECT 
		   FROM CZ_SA_DEFERRED_DELIVERY
		   WHERE TP_TYPE = '2'
		   GROUP BY CD_COMPANY, NO_SO) DD
ON DD.CD_COMPANY = SH.CD_COMPANY AND DD.NO_SO = SH.NO_SO

GO