USE [NEOE]
GO
/****** Object:  StoredProcedure [NEOE].[SP_CZ_PR_OPOUT_PO_WORK_SUB_S]    Script Date: 2023-01-31 오후 5:35:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO




ALTER PROCEDURE [NEOE].[SP_CZ_PR_OPOUT_PO_WORK_SUB_S]
(          
    @P_CD_COMPANY			NVARCHAR(7),           
    @P_CD_PLANT				NVARCHAR(7),           
    @P_CD_PARTNER			NVARCHAR(20),           
    @P_DT_START				NVARCHAR(8),           
    @P_DT_END				NVARCHAR(8),           
    @P_CD_EXCH				NVARCHAR(3),           
    @P_RT_EXCH				NUMERIC(17, 4),           
    @P_EXCEPT_LIST			VARCHAR(8000),          
    @P_DT_PO				NVARCHAR(8),        
    @P_RT_RATE				NUMERIC(17,4),      
    @P_NO_WO				NVARCHAR(20)	= '',       
    @P_NO_LOT				NVARCHAR(20)	= '',
    @P_CD_MULTI_TP_ROUT 	NVARCHAR(4000)	= NULL,
    @P_WO_DCRMK_APPLY_YN	NVARCHAR(1)		= NULL,
	@P_NO_EMP				NVARCHAR(10)	= NULL
)
AS

DECLARE @YN_MFG_AUTH NCHAR(1)
SELECT @YN_MFG_AUTH = ISNULL((SELECT YN_MFG_AUTH FROM MA_ENV WHERE CD_COMPANY = @P_CD_COMPANY), 'N')


SELECT	'N' CHK, 
		X.CD_PLANT, 
		X.CD_PARTNER,
		C.LN_PARTNER,
		X.CD_WC,
		D.NM_WC, 
		X.CD_WCOP, 
		X.NO_WO, 
		X.NO_LINE,
		X.CD_OP, 
		X.CD_ITEM,
		P.NM_ITEM,
		P.STND_ITEM,
		P.UNIT_IM,        
		X.QT_WO,           
		X.QT_OUTPO,
		X.QT_OPOUT_PO, 
		X.QT_APPLY_YET, 
		X.QT_APPLY, 
		ISNULL(XX.UM, 0) AS UM_EX,           
		(ISNULL(X.QT_OUTPO, 0) - ISNULL(X.QT_OPOUT_PO, 0)) * ISNULL(XX.UM, 0) AS AM_EX,           
		ISNULL(XX.UM, 0) * @P_RT_EXCH AS UM,           
		((ISNULL(X.QT_OUTPO, 0) - ISNULL(X.QT_OPOUT_PO, 0)) * ISNULL(XX.UM, 0) * @P_RT_EXCH) AS AM,           
		(CASE WHEN ISNULL(@P_RT_RATE, 0) = 0 THEN 0 
			  ELSE (ISNULL(X.QT_OUTPO, 0) - ISNULL(X.QT_OPOUT_PO, 0)) * ISNULL(XX.UM, 0) * @P_RT_EXCH / @P_RT_RATE END) AS AM_VAT,           
		X.NM_OP,           
		X.DT_REL,
		X.DT_DUE, 
		X.NO_WO_CD_OP,        
		XX.UM_MATL,   
		XX.UM_SOUL,   
		T.NM_TP_WO,  
		X.NO_LOT,  
		P.FG_SERNO,
		NEOE.FN_MA_GET_CODEDTL_NM_SYSDEF(@P_CD_COMPANY,'MA_B000015',P.FG_SERNO) AS NM_FG_SERNO, 
		P.GRP_ITEM,
		G.NM_ITEMGRP AS NM_GRP_ITEM,  
		X.DC_RMK1,
		'' AS UNIT_CH, 
		0  AS QT_CHCOEF,
		0  AS OLD_QT_PO,
		'' AS NO_WORK,
		X.NO_PJT,
		X.NM_PJT,
		P.EN_ITEM,
		P.STND_DETAIL_ITEM,
		P.MAT_ITEM,
		P.NM_MAKER,
		P.BARCODE,
		P.NO_MODEL,
		X.TXT_USERDEF1_WO,
		P.NO_DESIGN,
		'' AS NO_PR,
		0 AS NO_PR_LINE
FROM (SELECT A.CD_COMPANY, 
			 A.CD_PLANT, 
			 E.CD_PARTNER, 
			 A.NO_LINE,
			 A.CD_WC, 
			 A.CD_WCOP, 
			 E.NM_OP, 
			 A.NO_WO, 
			 A.CD_OP, 
			 W.CD_ITEM, 
			 W.QT_ITEM AS QT_WO, 
			 A.QT_WIP AS QT_OUTPO, 
			 SUM(ISNULL(B.QT_PO, 0)) AS QT_OPOUT_PO, 
			 A.QT_WIP - SUM(ISNULL(B.QT_PO, 0)) AS QT_APPLY_YET, 
			 A.QT_WIP - SUM(ISNULL(B.QT_PO, 0)) AS QT_APPLY, 
			 W.DT_REL, 
			 W.DT_DUE, 
			 (A.NO_WO + '&' + A.CD_OP) AS NO_WO_CD_OP,        
			 W.TP_ROUT,
			 W.NO_LOT, 
			 (CASE WHEN ISNULL(@P_WO_DCRMK_APPLY_YN, 'N') = 'N' THEN '' ELSE W.DC_RMK END) AS DC_RMK1,
			 W.NO_PJT,
			 J.NM_PROJECT AS NM_PJT,
			 W.TXT_USERDEF1 AS TXT_USERDEF1_WO
	  FROM PR_WO_ROUT A         
	  JOIN PR_WO W ON W.CD_COMPANY = A.CD_COMPANY AND W.CD_PLANT = A.CD_PLANT  AND W.NO_WO = A.NO_WO AND W.DT_REL >= @P_DT_START AND W.DT_DUE <= @P_DT_END          
	  JOIN PR_WCOP E ON E.CD_COMPANY = A.CD_COMPANY AND E.CD_PLANT = A.CD_PLANT AND E.CD_WC = A.CD_WC AND E.CD_WCOP = A.CD_WCOP 
	  LEFT JOIN PR_OPOUT_POL B ON B.CD_COMPANY = A.CD_COMPANY   AND B.CD_PLANT = A.CD_PLANT AND B.NO_WO = A.NO_WO AND B.CD_OP = A.CD_OP AND B.CD_WC = A.CD_WC AND B.CD_WCOP = A.CD_WCOP
	  LEFT JOIN SA_PROJECTH J ON W.CD_COMPANY = J.CD_COMPANY AND W.NO_PJT = J.NO_PROJECT			
	  LEFT JOIN CZ_PR_OPOUT_PR Z ON A.CD_COMPANY = Z.CD_COMPANY AND A.NO_WO = Z.NO_WO AND A.CD_OP = Z.CD_OP
	  WHERE	A.CD_COMPANY = @P_CD_COMPANY
	  AND A.CD_PLANT = @P_CD_PLANT
	  AND A.ST_OP NOT IN ('C')
	  AND A.YN_SUBCON = 'Y'
	  AND (A.NO_WO + '&' + A.CD_OP NOT IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_EXCEPT_LIST)) OR ISNULL(@P_EXCEPT_LIST, '') = '')
	  AND (A.NO_WO LIKE '%' + ISNULL(@P_NO_WO,'') + '%')
	  AND (ISNULL(W.NO_LOT, '') LIKE '%' + ISNULL(@P_NO_LOT,'') + '%')
	  AND (W.TP_ROUT IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_MULTI_TP_ROUT)) OR ISNULL(@P_CD_MULTI_TP_ROUT, '') = '')
	  AND (E.CD_PARTNER = @P_CD_PARTNER OR @P_CD_PARTNER  = '' OR @P_CD_PARTNER IS NULL)
	  AND EXISTS (SELECT 1 
				  FROM CZ_PR_WO_REQ_D WD
				  WHERE WD.CD_COMPANY = W.CD_COMPANY
				  AND WD.NO_WO = W.NO_WO)
	  GROUP BY A.CD_COMPANY, A.CD_PLANT, E.CD_PARTNER, A.CD_WC, A.CD_WCOP, E.NM_OP, A.NO_WO, A.CD_OP, W.CD_ITEM, W.QT_ITEM, A.QT_WIP, 
			   W.DT_REL, W.DT_DUE, W.TP_ROUT, W.NO_LOT, (CASE WHEN ISNULL(@P_WO_DCRMK_APPLY_YN, 'N') = 'N' THEN '' ELSE W.DC_RMK END),
			   W.NO_PJT, J.NM_PROJECT, W.TXT_USERDEF1, A.NO_LINE
	  HAVING A.QT_WIP - SUM(ISNULL(B.QT_PO, 0)) > 0    
) X
LEFT JOIN (SELECT U.CD_COMPANY, 
			      U.CD_PLANT, 
			      U.CD_WC, 
			      U.CD_WCOP, 
			      U.CD_PARTNER, 
			      U.CD_ITEM, 
			      U.CD_EXCH, 
			      U.UM, 
			      U.UM_MATL, 
			      U.UM_SOUL, 
			      U.DT_END
		   FROM SU_UM_OP U
	       JOIN (SELECT	A.CD_COMPANY,
						A.CD_PLANT,
						A.CD_WC,
						A.CD_WCOP,
						W.CD_ITEM,
						U.CD_PARTNER,
						U.CD_EXCH,
						MAX(DT_START) AS DT_START
				 FROM PR_WO_ROUT	A         
				 JOIN PR_WO	W ON W.CD_COMPANY = A.CD_COMPANY AND W.CD_PLANT = A.CD_PLANT  AND W.NO_WO = A.NO_WO AND W.DT_REL >= @P_DT_START AND W.DT_DUE <= @P_DT_END          
				 JOIN SU_UM_OP U ON A.CD_COMPANY = U.CD_COMPANY AND A.CD_PLANT = U.CD_PLANT AND A.CD_WC = U.CD_WC AND A.CD_WCOP = U.CD_WCOP AND W.CD_ITEM = U.CD_ITEM
				 WHERE A.CD_COMPANY = @P_CD_COMPANY        
				 AND A.CD_PLANT = @P_CD_PLANT          
				 AND A.ST_OP NOT IN ('C')        
				 AND A.YN_SUBCON = 'Y'
				 AND (A.NO_WO + '&' + A.CD_OP NOT IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_EXCEPT_LIST)) OR ISNULL(@P_EXCEPT_LIST, '') = '')       
				 AND (A.NO_WO LIKE '%' + ISNULL(@P_NO_WO,'') + '%')      
				 AND (ISNULL(W.NO_LOT, '') LIKE '%' + ISNULL(@P_NO_LOT,'') + '%') 
				 AND (W.TP_ROUT IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_MULTI_TP_ROUT)) OR ISNULL(@P_CD_MULTI_TP_ROUT, '') = '')
				 AND U.CD_EXCH  = @P_CD_EXCH
				 GROUP BY A.CD_COMPANY, A.CD_PLANT, A.CD_WC, A.CD_WCOP, W.CD_ITEM, U.CD_PARTNER, U.CD_EXCH) M 
ON U.CD_COMPANY = M.CD_COMPANY AND U.CD_PLANT = M.CD_PLANT AND U.CD_WC = M.CD_WC AND U.CD_WCOP = M.CD_WCOP AND U.CD_PARTNER = M.CD_PARTNER AND U.CD_ITEM = M.CD_ITEM AND U.CD_EXCH = M.CD_EXCH AND U.DT_START = M.DT_START
WHERE U.CD_COMPANY = @P_CD_COMPANY
AND U.CD_PLANT = @P_CD_PLANT
AND U.DT_START <= @P_DT_PO) XX 
ON X.CD_COMPANY = XX.CD_COMPANY AND X.CD_PLANT = XX.CD_PLANT AND X.CD_WC = XX.CD_WC AND X.CD_WCOP = XX.CD_WCOP AND X.CD_PARTNER = XX.CD_PARTNER AND X.CD_ITEM = XX.CD_ITEM AND XX.DT_END >= X.DT_DUE   
LEFT JOIN MA_PITEM P ON P.CD_COMPANY = X.CD_COMPANY AND P.CD_PLANT = X.CD_PLANT AND P.CD_ITEM = X.CD_ITEM          
LEFT JOIN MA_WC D ON D.CD_COMPANY = X.CD_COMPANY AND D.CD_PLANT = X.CD_PLANT AND D.CD_WC = X.CD_WC          
LEFT JOIN MA_PARTNER C ON C.CD_COMPANY = X.CD_COMPANY AND C.CD_PARTNER = X.CD_PARTNER         
LEFT JOIN PR_TPWO T ON T.CD_COMPANY = X.CD_COMPANY AND T.TP_WO = X.TP_ROUT
LEFT JOIN MA_ITEMGRP G ON G.CD_COMPANY = P.CD_COMPANY AND G.CD_ITEMGRP = P.GRP_ITEM
WHERE ((@YN_MFG_AUTH <> 'Y' OR  ISNULL(@P_NO_EMP,'') =  '') OR	
	   (@YN_MFG_AUTH =  'Y' AND ISNULL(@P_NO_EMP,'') <> '' AND EXISTS (SELECT 1       
																	   FROM	MA_MFG_AUTH AUTH      
																	   WHERE AUTH.CD_COMPANY = X.CD_COMPANY
																	   AND AUTH.CD_AUTH	= X.TP_ROUT
																	   AND AUTH.FG_AUTH	= 'PR_TPWO'      
																	   AND AUTH.NO_EMP = @P_NO_EMP)))   
AND ((@YN_MFG_AUTH <> 'Y' OR  ISNULL(@P_NO_EMP,'') =  '') OR
     (@YN_MFG_AUTH =  'Y' AND ISNULL(@P_NO_EMP,'') <> '' AND EXISTS (SELECT	1
																	 FROM MA_MFG_AUTH AUTH
																	 WHERE AUTH.CD_COMPANY = X.CD_COMPANY
																	 AND AUTH.CD_AUTH = X.CD_WC
																	 AND AUTH.FG_AUTH = 'MA_WC'
																	 AND AUTH.NO_EMP = @P_NO_EMP)))			
																	 
UNION ALL

SELECT	'N' CHK, 
		X.CD_PLANT, 
		X.CD_PARTNER,
		C.LN_PARTNER,
		X.CD_WC,
		D.NM_WC, 
		X.CD_WCOP, 
		X.NO_WO, 
		X.NO_LINE,
		X.CD_OP, 
		X.CD_ITEM,
		P.NM_ITEM,
		P.STND_ITEM,
		P.UNIT_IM,        
		X.QT_WO,           
		X.QT_OUTPO,
		X.QT_OPOUT_PO, 
		X.QT_APPLY_YET, 
		X.QT_APPLY, 
		ISNULL(XX.UM, 0) AS UM_EX,           
		(ISNULL(X.QT_OUTPO, 0) - ISNULL(X.QT_OPOUT_PO, 0)) * ISNULL(XX.UM, 0) AS AM_EX,           
		ISNULL(XX.UM, 0) * @P_RT_EXCH AS UM,           
		((ISNULL(X.QT_OUTPO, 0) - ISNULL(X.QT_OPOUT_PO, 0)) * ISNULL(XX.UM, 0) * @P_RT_EXCH) AS AM,           
		(CASE WHEN ISNULL(@P_RT_RATE, 0) = 0 THEN 0 
			  ELSE (ISNULL(X.QT_OUTPO, 0) - ISNULL(X.QT_OPOUT_PO, 0)) * ISNULL(XX.UM, 0) * @P_RT_EXCH / @P_RT_RATE END) AS AM_VAT,           
		X.NM_OP,           
		X.DT_REL,
		X.DT_DUE, 
		X.NO_WO_CD_OP,        
		XX.UM_MATL,   
		XX.UM_SOUL,   
		T.NM_TP_WO,  
		X.NO_LOT,  
		P.FG_SERNO,
		NEOE.FN_MA_GET_CODEDTL_NM_SYSDEF(@P_CD_COMPANY,'MA_B000015',P.FG_SERNO) AS NM_FG_SERNO, 
		P.GRP_ITEM,
		G.NM_ITEMGRP AS NM_GRP_ITEM,  
		X.DC_RMK1,
		'' AS UNIT_CH, 
		0  AS QT_CHCOEF,
		0  AS OLD_QT_PO,
		'' AS NO_WORK,
		X.NO_PJT,
		X.NM_PJT,
		P.EN_ITEM,
		P.STND_DETAIL_ITEM,
		P.MAT_ITEM,
		P.NM_MAKER,
		P.BARCODE,
		P.NO_MODEL,
		X.TXT_USERDEF1_WO,
		P.NO_DESIGN,
		X.NO_PR,
		X.NO_LINE AS NO_PR_LINE
FROM (SELECT A.CD_COMPANY, 
			 A.CD_PLANT, 
			 Z.CD_PARTNER,
			 A.NO_LINE,
			 A.CD_WC, 
			 A.CD_WCOP, 
			 E.NM_OP, 
			 A.NO_WO, 
			 A.CD_OP, 
			 W.CD_ITEM, 
			 W.QT_ITEM AS QT_WO, 
			 Z.QT_PR AS QT_OUTPO, 
			 SUM(ISNULL(B.QT_PO, 0)) AS QT_OPOUT_PO, 
			 Z.QT_PR - SUM(ISNULL(B.QT_PO, 0)) AS QT_APPLY_YET, 
			 Z.QT_PR - SUM(ISNULL(B.QT_PO, 0)) AS QT_APPLY, 
			 W.DT_REL, 
			 W.DT_DUE, 
			 (A.NO_WO + '&' + A.CD_OP) AS NO_WO_CD_OP,        
			 W.TP_ROUT,
			 W.NO_LOT, 
			 (CASE WHEN ISNULL(@P_WO_DCRMK_APPLY_YN, 'N') = 'N' THEN '' ELSE W.DC_RMK END) AS DC_RMK1,
			 W.NO_PJT,
			 J.NM_PROJECT AS NM_PJT,
			 W.TXT_USERDEF1 AS TXT_USERDEF1_WO,
			 Z.NO_PR
	  FROM PR_WO_ROUT A         
	  JOIN PR_WO W ON W.CD_COMPANY = A.CD_COMPANY AND W.CD_PLANT = A.CD_PLANT  AND W.NO_WO = A.NO_WO AND W.DT_REL >= @P_DT_START AND W.DT_DUE <= @P_DT_END          
	  JOIN PR_WCOP E ON E.CD_COMPANY = A.CD_COMPANY AND E.CD_PLANT = A.CD_PLANT AND E.CD_WC = A.CD_WC AND E.CD_WCOP = A.CD_WCOP 
	  LEFT JOIN CZ_PR_OPOUT_PR Z ON A.CD_COMPANY = Z.CD_COMPANY AND A.NO_WO = Z.NO_WO AND A.CD_OP = Z.CD_OP
	  LEFT JOIN PR_OPOUT_POL B ON B.CD_COMPANY = A.CD_COMPANY   AND B.CD_PLANT = A.CD_PLANT AND B.NO_WO = A.NO_WO AND B.NO_PR = Z.NO_PR
	  LEFT JOIN SA_PROJECTH J ON W.CD_COMPANY = J.CD_COMPANY AND W.NO_PJT = J.NO_PROJECT			
	  WHERE	A.CD_COMPANY = @P_CD_COMPANY
	  AND A.CD_PLANT = @P_CD_PLANT
	  AND A.ST_OP NOT IN ('C')
	  AND (ISNULL(Z.QT_PR, 0) > 0 AND ISNULL(Z.QT_PR, 0) > ISNULL(B.QT_PO, 0))
	  AND (A.NO_WO + '&' + A.CD_OP NOT IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_EXCEPT_LIST)) OR ISNULL(@P_EXCEPT_LIST, '') = '')
	  AND (A.NO_WO LIKE '%' + ISNULL(@P_NO_WO,'') + '%')
	  AND (ISNULL(W.NO_LOT, '') LIKE '%' + ISNULL(@P_NO_LOT,'') + '%')
	  AND (W.TP_ROUT IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_MULTI_TP_ROUT)) OR ISNULL(@P_CD_MULTI_TP_ROUT, '') = '')
	  AND (E.CD_PARTNER = @P_CD_PARTNER OR @P_CD_PARTNER  = '' OR @P_CD_PARTNER IS NULL)
	  AND EXISTS (SELECT 1 
				  FROM CZ_PR_WO_REQ_D WD
				  WHERE WD.CD_COMPANY = W.CD_COMPANY
				  AND WD.NO_WO = W.NO_WO)
	  GROUP BY A.CD_COMPANY, A.CD_PLANT, Z.CD_PARTNER, A.CD_WC, A.CD_WCOP, E.NM_OP, A.NO_WO, A.CD_OP, W.CD_ITEM, W.QT_ITEM, A.QT_WIP, 
			   W.DT_REL, W.DT_DUE, W.TP_ROUT, W.NO_LOT, (CASE WHEN ISNULL(@P_WO_DCRMK_APPLY_YN, 'N') = 'N' THEN '' ELSE W.DC_RMK END),
			   W.NO_PJT, J.NM_PROJECT, W.TXT_USERDEF1, Z.NO_PR, Z.NO_LINE, Z.QT_PR, A.NO_LINE
	  HAVING Z.QT_PR - SUM(ISNULL(B.QT_PO, 0)) > 0    
) X
LEFT JOIN (SELECT U.CD_COMPANY, 
			      U.CD_PLANT, 
			      U.CD_WC, 
			      U.CD_WCOP, 
			      U.CD_PARTNER, 
			      U.CD_ITEM, 
			      U.CD_EXCH, 
			      U.UM, 
			      U.UM_MATL, 
			      U.UM_SOUL, 
			      U.DT_END
		   FROM SU_UM_OP U
	       JOIN (SELECT	A.CD_COMPANY,
						A.CD_PLANT,
						A.CD_WC,
						A.CD_WCOP,
						W.CD_ITEM,
						U.CD_PARTNER,
						U.CD_EXCH,
						MAX(DT_START) AS DT_START
				 FROM PR_WO_ROUT	A         
				 JOIN PR_WO	W ON W.CD_COMPANY = A.CD_COMPANY AND W.CD_PLANT = A.CD_PLANT  AND W.NO_WO = A.NO_WO AND W.DT_REL >= @P_DT_START AND W.DT_DUE <= @P_DT_END          
				 JOIN SU_UM_OP U ON A.CD_COMPANY = U.CD_COMPANY AND A.CD_PLANT = U.CD_PLANT AND A.CD_WC = U.CD_WC AND A.CD_WCOP = U.CD_WCOP AND W.CD_ITEM = U.CD_ITEM
				 LEFT JOIN PR_OPOUT_POL B ON B.CD_COMPANY = A.CD_COMPANY   AND B.CD_PLANT = A.CD_PLANT AND B.NO_WO = A.NO_WO AND B.CD_OP = A.CD_OP AND B.CD_WC = A.CD_WC AND B.CD_WCOP = A.CD_WCOP
				 LEFT JOIN CZ_PR_OPOUT_PR Z ON A.CD_COMPANY = Z.CD_COMPANY AND A.NO_WO = Z.NO_WO AND A.CD_OP = Z.CD_OP
				 WHERE A.CD_COMPANY = @P_CD_COMPANY        
				 AND A.CD_PLANT = @P_CD_PLANT          
				 AND A.ST_OP NOT IN ('C')        
				 AND (ISNULL(Z.QT_PR, 0) > 0 AND ISNULL(Z.QT_PR, 0) > ISNULL(B.QT_PO, 0))
				 AND (A.NO_WO + '&' + A.CD_OP NOT IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_EXCEPT_LIST)) OR ISNULL(@P_EXCEPT_LIST, '') = '')       
				 AND (A.NO_WO LIKE '%' + ISNULL(@P_NO_WO,'') + '%')      
				 AND (ISNULL(W.NO_LOT, '') LIKE '%' + ISNULL(@P_NO_LOT,'') + '%') 
				 AND (W.TP_ROUT IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_MULTI_TP_ROUT)) OR ISNULL(@P_CD_MULTI_TP_ROUT, '') = '')
				 AND U.CD_EXCH  = @P_CD_EXCH
				 GROUP BY A.CD_COMPANY, A.CD_PLANT, A.CD_WC, A.CD_WCOP, W.CD_ITEM, U.CD_PARTNER, U.CD_EXCH) M 
ON U.CD_COMPANY = M.CD_COMPANY AND U.CD_PLANT = M.CD_PLANT AND U.CD_WC = M.CD_WC AND U.CD_WCOP = M.CD_WCOP AND U.CD_PARTNER = M.CD_PARTNER AND U.CD_ITEM = M.CD_ITEM AND U.CD_EXCH = M.CD_EXCH AND U.DT_START = M.DT_START
WHERE U.CD_COMPANY = @P_CD_COMPANY
AND U.CD_PLANT = @P_CD_PLANT
AND U.DT_START <= @P_DT_PO) XX 
ON X.CD_COMPANY = XX.CD_COMPANY AND X.CD_PLANT = XX.CD_PLANT AND X.CD_WC = XX.CD_WC AND X.CD_WCOP = XX.CD_WCOP AND X.CD_PARTNER = XX.CD_PARTNER AND X.CD_ITEM = XX.CD_ITEM AND XX.DT_END >= X.DT_DUE   
LEFT JOIN MA_PITEM P ON P.CD_COMPANY = X.CD_COMPANY AND P.CD_PLANT = X.CD_PLANT AND P.CD_ITEM = X.CD_ITEM          
LEFT JOIN MA_WC D ON D.CD_COMPANY = X.CD_COMPANY AND D.CD_PLANT = X.CD_PLANT AND D.CD_WC = X.CD_WC          
LEFT JOIN MA_PARTNER C ON C.CD_COMPANY = X.CD_COMPANY AND C.CD_PARTNER = X.CD_PARTNER         
LEFT JOIN PR_TPWO T ON T.CD_COMPANY = X.CD_COMPANY AND T.TP_WO = X.TP_ROUT
LEFT JOIN MA_ITEMGRP G ON G.CD_COMPANY = P.CD_COMPANY AND G.CD_ITEMGRP = P.GRP_ITEM
WHERE ((@YN_MFG_AUTH <> 'Y' OR  ISNULL(@P_NO_EMP,'') =  '') OR	
	   (@YN_MFG_AUTH =  'Y' AND ISNULL(@P_NO_EMP,'') <> '' AND EXISTS (SELECT 1       
																	   FROM	MA_MFG_AUTH AUTH      
																	   WHERE AUTH.CD_COMPANY = X.CD_COMPANY
																	   AND AUTH.CD_AUTH	= X.TP_ROUT
																	   AND AUTH.FG_AUTH	= 'PR_TPWO'      
																	   AND AUTH.NO_EMP = @P_NO_EMP)))   
AND ((@YN_MFG_AUTH <> 'Y' OR  ISNULL(@P_NO_EMP,'') =  '') OR
     (@YN_MFG_AUTH =  'Y' AND ISNULL(@P_NO_EMP,'') <> '' AND EXISTS (SELECT	1
																	 FROM MA_MFG_AUTH AUTH
																	 WHERE AUTH.CD_COMPANY = X.CD_COMPANY
																	 AND AUTH.CD_AUTH = X.CD_WC
																	 AND AUTH.FG_AUTH = 'MA_WC'
																	 AND AUTH.NO_EMP = @P_NO_EMP)))		

