USE [NEOE]
GO
/****** Object:  StoredProcedure [NEOE].[UP_PR_OPOUT_PO_WORK_SUB_CHC_S]    Script Date: 2021-07-20 오후 7:07:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/********************************************
*********************************************/
CREATE PROCEDURE [NEOE].[UP_PR_OPOUT_PO_WORK_SUB_CHC_S]
(              
    @P_CD_COMPANY			NVARCHAR(7),             
    @P_CD_PLANT				NVARCHAR(7),             
    @P_CD_PARTNER			NVARCHAR(20),             
    @P_DT_START				NVARCHAR(8),             
    @P_DT_END				NVARCHAR(8),             
    @P_CD_EXCH				NVARCHAR(3),             
    @P_RT_EXCH				NUMERIC(17, 4),             
    @P_EXCEPT_LIST			VARCHAR(8000),            
    @P_DT_PO				NVARCHAR(8),          
    @P_RT_RATE				NUMERIC(17,4),        
    @P_NO_WO				NVARCHAR(20)	= '',         
    @P_NO_LOT				NVARCHAR(20)	= '',  
    @P_CD_MULTI_TP_ROUT		NVARCHAR(4000)	= NULL,  
    @P_WO_DCRMK_APPLY_YN	NVARCHAR(1)		= NULL,
	@P_NO_EMP				NVARCHAR(10)	= NULL
            
)  AS            
  
DECLARE @CD_EXC_CH		NVARCHAR(3),
		@YN_MFG_AUTH	NCHAR(1)
		    
SELECT	@CD_EXC_CH = ISNULL((SELECT CD_EXC        
							 FROM	MA_EXC
							 WHERE	CD_COMPANY = @P_CD_COMPANY        
							 AND	CD_MODULE = 'PR'        
							 AND	EXC_TITLE = '공정외주임가공단가 단위 변환 사용'), '000')


SELECT	@YN_MFG_AUTH  = ISNULL((SELECT	YN_MFG_AUTH
								FROM	MA_ENV
								WHERE	CD_COMPANY = @P_CD_COMPANY ), 'N')

BEGIN
	SELECT	'N' CHK, 
			X.CD_PLANT, 
			X.CD_PARTNER,	C.LN_PARTNER, 
			X.CD_WC,		D.NM_WC, 
			X.CD_WCOP,		X.NM_OP, 
			X.NO_WO, 
			X.CD_OP, 
			X.CD_ITEM,		P.NM_ITEM,		P.STND_ITEM,		P.UNIT_IM,           
			X.QT_WO,             
			X.QT_OUTPO,  
			X.QT_OPOUT_PO, 
			X.QT_APPLY_YET, 
			X.QT_APPLY,
			CASE WHEN ISNULL(XX.QT_CHCOEF, 0) = 0 THEN X.QT_APPLY ELSE XX.QT_CHCOEF * X.QT_APPLY END AS QT_APPLY_CALC,
			ISNULL(XX.UM, 0) AS UM_EX,             
			((CASE WHEN ISNULL(XX.QT_CHCOEF, 0) = 0 THEN X.QT_APPLY ELSE XX.QT_CHCOEF * X.QT_APPLY END) * ISNULL(XX.UM, 0)) AS AM_EX,             
			ISNULL(XX.UM, 0) * @P_RT_EXCH AS UM,             
			((CASE WHEN ISNULL(XX.QT_CHCOEF, 0) = 0 THEN X.QT_APPLY ELSE XX.QT_CHCOEF * X.QT_APPLY END) * ISNULL(XX.UM, 0) * @P_RT_EXCH) AS AM,
			ROUND(CASE WHEN ISNULL(@P_RT_RATE, 0) = 0 THEN 0 
					   ELSE (CASE WHEN ISNULL(XX.QT_CHCOEF, 0) = 0 THEN X.QT_APPLY ELSE XX.QT_CHCOEF * X.QT_APPLY END) 
							* ISNULL(XX.UM, 0) * @P_RT_EXCH / @P_RT_RATE END, 0, 1) AS AM_VAT,             
			X.DT_REL,		X.DT_DUE, 
			X.NO_WO_CD_OP,          
			XX.UM_MATL,     
			XX.UM_SOUL,     
			X.TP_ROUT,		T.NM_TP_WO,     
			X.NO_LOT,    
			P.FG_SERNO,		NEOE.FN_MA_GET_CODEDTL_NM_SYSDEF(@P_CD_COMPANY,'MA_B000015',P.FG_SERNO) AS NM_FG_SERNO, 
			P.GRP_ITEM,		G.NM_ITEMGRP AS NM_GRP_ITEM,  
			X.DC_RMK1,  
			XX.UNIT_CH,   
			XX.QT_CHCOEF,  
			X.QT_APPLY_YET AS OLD_QT_PO,
			P.EN_ITEM,
			P.STND_DETAIL_ITEM,
			P.MAT_ITEM,
			P.NM_MAKER,
			P.BARCODE,
			P.NO_MODEL,
			X.TXT_USERDEF1_WO
	FROM   
	(      
		SELECT	A.CD_COMPANY,  
				A.CD_PLANT, 
				E.CD_PARTNER, 
				A.CD_WC, 
				A.CD_WCOP, 
				E.NM_OP, 
				A.NO_WO, 
				A.CD_OP, 
				W.CD_ITEM, 
				W.QT_ITEM  AS QT_WO, 
				A.QT_START AS QT_OUTPO,       
				CASE WHEN @CD_EXC_CH = '000' THEN SUM(ISNULL(B.QT_PO, 0)) ELSE SUM(ISNULL(B.OLD_QT_PO, 0)) END AS QT_OPOUT_PO,           
				A.QT_START - (CASE WHEN @CD_EXC_CH = '000' THEN SUM(ISNULL(B.QT_PO, 0)) ELSE SUM(ISNULL(B.OLD_QT_PO, 0)) END) AS QT_APPLY_YET, 
				A.QT_START - (CASE WHEN @CD_EXC_CH = '000' THEN SUM(ISNULL(B.QT_PO, 0)) ELSE SUM(ISNULL(B.OLD_QT_PO, 0)) END) AS QT_APPLY, 
				W.DT_REL, 
				W.DT_DUE, 
				A.NO_WO + '&' + A.CD_OP AS NO_WO_CD_OP,          
				W.TP_ROUT,
				W.NO_LOT,    
				CASE WHEN ISNULL(@P_WO_DCRMK_APPLY_YN, 'N') = 'N' THEN '' ELSE W.DC_RMK END AS DC_RMK1,
				W.TXT_USERDEF1 AS TXT_USERDEF1_WO
		FROM PR_WO_ROUT A           
		INNER JOIN PR_WO		W ON W.CD_COMPANY = A.CD_COMPANY AND W.CD_PLANT = A.CD_PLANT  AND W.NO_WO = A.NO_WO AND W.DT_REL >= @P_DT_START  
								 AND W.DT_DUE <= @P_DT_END            
		INNER JOIN PR_WCOP		E ON E.CD_COMPANY = A.CD_COMPANY AND E.CD_PLANT = A.CD_PLANT AND E.CD_WC = A.CD_WC   AND E.CD_WCOP = A.CD_WCOP   
		LEFT  JOIN PR_OPOUT_POL	B ON B.CD_COMPANY = A.CD_COMPANY AND B.CD_PLANT = A.CD_PLANT AND B.NO_WO = A.NO_WO AND B.CD_OP = A.CD_OP            
								 AND B.CD_WC = A.CD_WC AND B.CD_WCOP = A.CD_WCOP  
      
		WHERE	(A.CD_COMPANY = @P_CD_COMPANY)          
		AND		(A.CD_PLANT = @P_CD_PLANT)            
		AND		(A.ST_OP NOT IN ('C'))            
		AND		(A.YN_SUBCON = 'Y')            
		AND		(A.NO_WO + '&' + A.CD_OP NOT IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_EXCEPT_LIST)) OR ISNULL(@P_EXCEPT_LIST, '') = '')            
		AND		(A.NO_WO LIKE '%' + ISNULL(@P_NO_WO,'') + '%')        
		AND		(ISNULL(W.NO_LOT, '') LIKE '%' + ISNULL(@P_NO_LOT,'') + '%')   
		AND		(W.TP_ROUT IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_MULTI_TP_ROUT)) OR ISNULL(@P_CD_MULTI_TP_ROUT, '') = '')        
		AND		(E.CD_PARTNER = @P_CD_PARTNER OR @P_CD_PARTNER  = '' OR @P_CD_PARTNER IS NULL)  
		GROUP BY A.CD_COMPANY, A.CD_PLANT, E.CD_PARTNER, A.CD_WC, A.CD_WCOP, E.NM_OP, A.NO_WO, A.CD_OP, W.CD_ITEM, W.QT_ITEM, A.QT_START, 
				W.DT_REL, W.DT_DUE, W.TP_ROUT, W.NO_LOT, CASE WHEN ISNULL(@P_WO_DCRMK_APPLY_YN, 'N') = 'N' THEN '' ELSE W.DC_RMK END,
				W.TXT_USERDEF1
		HAVING	 A.QT_START - (CASE WHEN @CD_EXC_CH = '000' THEN SUM(ISNULL(B.QT_PO, 0)) ELSE SUM(ISNULL(B.OLD_QT_PO, 0)) END) > 0      
	) X  
	LEFT JOIN (  
		SELECT	U.CD_COMPANY, 
				U.CD_PLANT, 
				U.CD_WC, 
				U.CD_WCOP, 
				U.CD_PARTNER, 
				U.CD_ITEM, 
				U.CD_EXCH, 
				U.UM, 
				U.UM_MATL, 
				U.UM_SOUL, 
				U.DT_END,  
				U.UNIT_CH, 
				U.QT_CHCOEF  
		FROM SU_UM_OP U  
		INNER JOIN (  
			SELECT	A.CD_COMPANY, A.CD_PLANT, A.CD_WC, A.CD_WCOP, W.CD_ITEM, U.CD_PARTNER, U.CD_EXCH, MAX(DT_START) AS DT_START  
			FROM	PR_WO_ROUT	A           
			INNER JOIN PR_WO	W ON W.CD_COMPANY = A.CD_COMPANY AND W.CD_PLANT = A.CD_PLANT AND W.NO_WO = A.NO_WO 
								 AND W.DT_REL >= @P_DT_START AND W.DT_DUE <= @P_DT_END            
			INNER JOIN SU_UM_OP U ON A.CD_COMPANY = U.CD_COMPANY AND A.CD_PLANT = U.CD_PLANT AND A.CD_WC = U.CD_WC 
								 AND A.CD_WCOP = U.CD_WCOP AND W.CD_ITEM = U.CD_ITEM  
			WHERE	(A.CD_COMPANY = @P_CD_COMPANY)          
			AND		(A.CD_PLANT = @P_CD_PLANT)            
			AND		(A.ST_OP NOT IN ('C'))            
			AND		(A.YN_SUBCON = 'Y')            
			AND		(A.NO_WO + '&' + A.CD_OP NOT IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_EXCEPT_LIST)) OR ISNULL(@P_EXCEPT_LIST, '') = '')             
			AND		(A.NO_WO LIKE '%' + ISNULL(@P_NO_WO,'') + '%')        
			AND		(ISNULL(W.NO_LOT, '') LIKE '%' + ISNULL(@P_NO_LOT,'') + '%')   
			AND		(W.TP_ROUT IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_MULTI_TP_ROUT)) OR ISNULL(@P_CD_MULTI_TP_ROUT, '') = '')    
			AND		(U.CD_EXCH  = @P_CD_EXCH)
			GROUP BY A.CD_COMPANY, A.CD_PLANT, A.CD_WC, A.CD_WCOP, W.CD_ITEM, U.CD_PARTNER, U.CD_EXCH  
		) M ON U.CD_COMPANY = M.CD_COMPANY AND U.CD_PLANT = M.CD_PLANT AND U.CD_WC = M.CD_WC AND U.CD_WCOP = M.CD_WCOP 
		   AND U.CD_PARTNER = M.CD_PARTNER AND U.CD_ITEM = M.CD_ITEM AND U.CD_EXCH = M.CD_EXCH AND U.DT_START = M.DT_START  
		WHERE	(U.CD_COMPANY = @P_CD_COMPANY)
		AND		(U.CD_PLANT   = @P_CD_PLANT)
		AND		(U.DT_START  <= @P_DT_PO)
	) XX ON X.CD_COMPANY = XX.CD_COMPANY AND X.CD_PLANT = XX.CD_PLANT AND X.CD_WC = XX.CD_WC AND X.CD_WCOP = XX.CD_WCOP 
		AND X.CD_PARTNER = XX.CD_PARTNER AND X.CD_ITEM = XX.CD_ITEM  AND XX.DT_END >= X.DT_DUE   
	LEFT JOIN MA_PITEM		P ON P.CD_COMPANY = X.CD_COMPANY AND P.CD_PLANT = X.CD_PLANT AND P.CD_ITEM = X.CD_ITEM  
	LEFT JOIN MA_WC			D ON D.CD_COMPANY = X.CD_COMPANY AND D.CD_PLANT = X.CD_PLANT AND D.CD_WC = X.CD_WC            
	LEFT JOIN MA_PARTNER	C ON C.CD_COMPANY = X.CD_COMPANY AND C.CD_PARTNER = X.CD_PARTNER           
	LEFT JOIN PR_TPWO		T ON T.CD_COMPANY = X.CD_COMPANY AND T.TP_WO = X.TP_ROUT      
	LEFT JOIN MA_ITEMGRP	G ON G.CD_COMPANY = P.CD_COMPANY AND G.CD_ITEMGRP = P.GRP_ITEM
	WHERE (	(@YN_MFG_AUTH <> 'Y' OR  ISNULL(@P_NO_EMP,'') =  '') 
		OR	(@YN_MFG_AUTH =  'Y' AND ISNULL(@P_NO_EMP,'') <> ''  AND EXISTS (SELECT	1       
																			 FROM	MA_MFG_AUTH AUTH      
																			 WHERE	AUTH.CD_COMPANY = X.CD_COMPANY
																			 AND	AUTH.CD_AUTH	= X.TP_ROUT
																			 AND	AUTH.FG_AUTH	= 'PR_TPWO'      
																			 AND	AUTH.NO_EMP		= @P_NO_EMP)) )   
	AND (	(@YN_MFG_AUTH <> 'Y' OR  ISNULL(@P_NO_EMP,'') =  '')
	    OR	(@YN_MFG_AUTH =  'Y' AND ISNULL(@P_NO_EMP,'') <> ''  AND EXISTS (SELECT	1
																			 FROM	MA_MFG_AUTH AUTH
																			 WHERE	AUTH.CD_COMPANY = X.CD_COMPANY
																			 AND	AUTH.CD_AUTH	= X.CD_WC
																			 AND	AUTH.FG_AUTH	= 'MA_WC'
																			 AND	AUTH.NO_EMP		= @P_NO_EMP)) )
END