USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_GIR_AUTO_MAIL_SETTING_S]    Script Date: 2015-06-04 오전 8:44:12 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_SA_GIR_AUTO_MAIL_SETTING_S]        
(  
    @P_CD_COMPANY   NVARCHAR(7),
    @P_NO_GIR       NVARCHAR(20)
)   
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT AM.TP_SEND,
       AM.TP_TRANS,
       AM.YN_DHL,
       AM.YN_FEDEX,
       AM.YN_TPO,
       AM.YN_SK,
       AM.YN_SR,
       AM.YN_ETC,
       AM.CD_COUNTRY_DHL,
       MC.NM_SYSDEF AS NM_COUNTRY_DHL,
       AM.CD_COUNTRY_FEDEX,
       MC1.NM_SYSDEF AS NM_COUNTRY_FEDEX,
       AM.DC_COUNTRY_ETC,
       AM.CD_PARTNER_ETC,
       MP.LN_PARTNER AS NM_PARTNER_ETC,
       AM.DC_EMAIL_ETC,
       AM.DC_CONSIGNEE
FROM CZ_SA_GIR_AUTO_MAIL_SETTING AM
LEFT JOIN MA_PARTNER MP ON MP.CD_COMPANY = AM.CD_COMPANY AND MP.CD_PARTNER = CD_PARTNER_ETC
LEFT JOIN CZ_MA_CODEDTL MC ON MC.CD_COMPANY = AM.CD_COMPANY AND MC.CD_FIELD = 'CZ_SA00054' AND MC.CD_SYSDEF = AM.CD_COUNTRY_DHL
LEFT JOIN CZ_MA_CODEDTL MC1 ON MC1.CD_COMPANY = AM.CD_COMPANY AND MC1.CD_FIELD = 'CZ_SA00055' AND MC1.CD_SYSDEF = AM.CD_COUNTRY_FEDEX
WHERE AM.CD_COMPANY = @P_CD_COMPANY
AND AM.NO_GIR = @P_NO_GIR

GO