USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_GIR_AUTO_MAIL_PACK]    Script Date: 2015-06-04 오전 8:44:12 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_SA_GIR_AUTO_MAIL_PACK]        
(  
    @P_CD_COMPANY   NVARCHAR(7),
    @P_NO_GIR       NVARCHAR(20)
)   
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

;WITH A AS
(
    SELECT PH.CD_COMPANY,
           PH.NO_GIR,
           PH.NO_PACK,
           PL.NO_FILE,
           SH.NO_PO_PARTNER,
           SH.CD_EXCH,
           SH.RT_EXCH,
           PL.AM_SO,
           MC.NM_SYSDEF AS NM_PACKING,
           'SIZE:(W)' + FORMAT(PH.QT_WIDTH, 'g15') + ' X ' + FORMAT(PH.QT_LENGTH, 'g15') + ' X ' + FORMAT(PH.QT_HEIGHT, 'g15') + ' (MM), KG:' + FORMAT(PH.QT_GROSS_WEIGHT, 'g15') AS DC_PACKING,
           CONVERT(NUMERIC(17, 2), ((PH1.QT_WIDTH * 0.001) * (PH1.QT_HEIGHT * 0.001) * (PH1.QT_LENGTH * 0.001))) AS QT_CBM,
           ROW_NUMBER() OVER (PARTITION BY PH.NO_GIR, PH.NO_PACK ORDER BY PL.AM_SO DESC) AS IDX,
           COUNT(1) OVER (PARTITION BY PH.NO_GIR, PH.NO_PACK ORDER BY PH.NO_GIR, PH.NO_PACK) AS CNT
    FROM CZ_SA_PACKH PH
    JOIN CZ_SA_PACKH PH1 ON PH1.CD_COMPANY = PH.CD_COMPANY AND PH1.NO_GIR = PH.NO_GIR_ORG AND PH1.NO_PACK = PH.NO_PACK_ORG
    JOIN (SELECT PL.CD_COMPANY, PL.NO_GIR, PL.NO_FILE,
                 SUM(SL.AM_WONAMT) AS AM_SO 
          FROM CZ_SA_PACKL PL
          LEFT JOIN SA_SOL SL ON  SL.CD_COMPANY = PL.CD_COMPANY AND SL.NO_SO = PL.NO_FILE AND SL.SEQ_SO = PL.NO_QTLINE
          GROUP BY PL.CD_COMPANY, PL.NO_GIR, PL.NO_FILE) PL
    ON PL.CD_COMPANY = PH.CD_COMPANY AND PL.NO_GIR = PH.NO_GIR
    JOIN SA_SOH SH ON SH.CD_COMPANY = PL.CD_COMPANY AND SH.NO_SO = PL.NO_FILE
    LEFT JOIN MA_CODEDTL MC ON MC.CD_COMPANY = SH.CD_COMPANY AND MC.CD_FIELD = 'TR_IM00011' AND MC.CD_SYSDEF = SH.TP_PACKING
    WHERE PH.CD_COMPANY = @P_CD_COMPANY
    AND PH.NO_GIR = @P_NO_GIR
    AND PH.CD_TYPE = '003'
    AND PH.YN_OUTSOURCING = 'Y'
    AND MC.CD_FLAG1 = 'Y'
)
SELECT A.NO_GIR,
       MH.NM_VESSEL,
       (SELECT STRING_AGG(GH.NO_PO_PARTNER, ',') 
        FROM A GH
        WHERE GH.CD_COMPANY = A.CD_COMPANY
        AND GH.NO_GIR = A.NO_GIR
        AND GH.NO_PACK = A.NO_PACK) AS NO_PO_PARTNER,
       A.NM_PACKING,
       A.DC_PACKING,
       IM.DC_URL,
       MC.NM_SYSDEF + ' ' + FORMAT(ROUND(TC.UM / A.RT_EXCH, 2), '0.00') AS AM_PACKING,
       (CASE WHEN A.CNT > 1 THEN 'To be charged to PO : ' + ISNULL(A.NO_PO_PARTNER, '') ELSE NULL END) AS DC_RMK
FROM A
JOIN SA_GIRH GH ON GH.CD_COMPANY = A.CD_COMPANY AND GH.NO_GIR = A.NO_GIR
LEFT JOIN CZ_SA_GIRH_WORK_DETAIL WD ON WD.CD_COMPANY = GH.CD_COMPANY AND WD.NO_GIR = GH.NO_GIR
LEFT JOIN CZ_MA_HULL MH ON MH.NO_IMO = WD.NO_IMO
LEFT JOIN MA_CODEDTL MC ON MC.CD_COMPANY = A.CD_COMPANY AND MC.CD_FIELD = 'MA_B000005' AND MC.CD_SYSDEF = A.CD_EXCH
LEFT JOIN (SELECT TH.CD_COMPANY,
	       	      TL.SIZE,
	       	      TL.UM 
	       FROM CZ_MA_TARIFF_CBM_H TH
	       JOIN CZ_MA_TARIFF_CBM_L TL ON TL.CD_COMPANY = TH.CD_COMPANY AND TL.CD_PARTNER = TH.CD_PARTNER
	       WHERE ISNULL(TH.YN_USE, 'N') = 'Y'
	       AND CONVERT(NVARCHAR(8), GETDATE(), 112) BETWEEN TL.DT_START AND TL.DT_END) TC
ON TC.CD_COMPANY = A.CD_COMPANY AND TC.SIZE = (CASE WHEN A.QT_CBM >= 1 THEN 1 ELSE A.QT_CBM END)
LEFT JOIN (SELECT IM.CD_COMPANY,
                  IM.NO_GIR,
                  STRING_AGG(DC_URL, ',') AS DC_URL
           FROM (SELECT SUBSTRING(DATA, CHARINDEX('/', DATA, 8) + 1, 4) AS CD_COMPANY,
                        SUBSTRING(DATA, CHARINDEX('/', DATA, 25) + 1, 10) AS NO_GIR,
                        'http://dint.ec/' + ENCODED AS DC_URL 
                 FROM CZ_DX_URL_BASE62
                 WHERE DATA LIKE 'Upload/CZ_SA_PACKH_FILE/%') IM
           GROUP BY IM.CD_COMPANY, IM.NO_GIR) IM
ON IM.CD_COMPANY = A.CD_COMPANY AND IM.NO_GIR = A.NO_GIR
WHERE A.IDX = 1

GO

