USE [NEOE]
GO

/****** Object:  Table [NEOE].[BANK_SENDH]    Script Date: 2019-03-04 오전 9:54:27 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [NEOE].[BANK_SENDH](
	[C_CODE] [varchar](20) NOT NULL,
	[NODE_CODE] [varchar](20) NULL,
	[TRANS_DATE] [char](8) NOT NULL,
	[TRANS_SEQ] [varchar](16) NOT NULL,
	[BANK_CODE] [varchar](10) NOT NULL,
	[ACCT_NO] [varchar](20) NOT NULL,
	[SEQ] [varchar](16) NOT NULL,
	[TRANS_BANK_CODE] [varchar](10) NOT NULL,
	[TRANS_ACCT_NO] [varchar](40) NOT NULL,
	[TRANS_NAME] [varchar](100) NOT NULL,
	[CD_EXCH] [nvarchar](4) NULL,
	[TRANS_AMT_EX] [numeric](19, 4) NOT NULL,
	[TRANS_AMT] [numeric](19, 4) NOT NULL,
	[CLIENT_NOTE] [varchar](100) NULL,
	[CUST_CODE] [varchar](20) NULL,
	[CUST_NAME] [nvarchar](50) NULL,
	[SETTLE_YN] [varchar](10) NULL,
	[SETTLE_DATE] [varchar](8) NULL,
	[TRANS_GU] [varchar](5) NULL,
	[ERR_MSG] [varchar](100) NULL,
	[TRANS_FLAG] [varchar](3) NULL,
	[DOCU_STAT] [varchar](3) NULL,
	[INSERT_DATE] [char](8) NULL,
	[INSERT_TIME] [char](6) NULL,
	[INSERT_ID] [varchar](20) NULL,
	[INSERT_NAME] [varchar](20) NULL,
	[DATA_CODE] [varchar](40) NULL,
	[TRANS_NOTE] [varchar](100) NULL,
	[NO_COMPANY] [varchar](20) NULL,
	[SEND_STATUS] [nchar](1) NULL,
	[NO_DOCU] [nvarchar](20) NULL,
	[NO_DOLINE] [numeric](5, 0) NULL,
	[YN_LIMITE] [nchar](1) NULL,
	[NO_LIMITE] [nvarchar](20) NULL,
	[NM_DEPOSIT_BANK] [nvarchar](40) NULL,
	[DC_RMK] [nvarchar](200) NULL,
	[TRANS_REAL_DATE] [char](8) NULL,
	[TP_CHARGE] [nvarchar](4) NULL,
	[TP_SEND_BY] [nvarchar](4) NULL,
	[DC_RELATION] [nvarchar](50) NULL,
 CONSTRAINT [PK_BANK_SENDH] PRIMARY KEY CLUSTERED 
(
	[C_CODE] ASC,
	[TRANS_DATE] ASC,
	[TRANS_SEQ] ASC,
	[SEQ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [NEOE].[BANK_SENDH] ADD  CONSTRAINT [DF__BANK_SEND__TRANS__30E667B0]  DEFAULT ('00000000') FOR [TRANS_DATE]
GO

ALTER TABLE [NEOE].[BANK_SENDH] ADD  CONSTRAINT [DF__BANK_SEND__TRANS__31DA8BE9]  DEFAULT ('1') FOR [TRANS_SEQ]
GO

ALTER TABLE [NEOE].[BANK_SENDH] ADD  CONSTRAINT [DF__BANK_SENDH__SEQ__32CEB022]  DEFAULT ('1') FOR [SEQ]
GO

ALTER TABLE [NEOE].[BANK_SENDH] ADD  CONSTRAINT [DF_BANK_SENDH_TRANS_AMT_EX]  DEFAULT ((0)) FOR [TRANS_AMT_EX]
GO

ALTER TABLE [NEOE].[BANK_SENDH] ADD  CONSTRAINT [DF__BANK_SEND__TRANS__33C2D45B]  DEFAULT ((0)) FOR [TRANS_AMT]
GO

ALTER TABLE [NEOE].[BANK_SENDH] ADD  CONSTRAINT [DF__BANK_SEND__TRANS__34B6F894]  DEFAULT ('000') FOR [TRANS_FLAG]
GO

ALTER TABLE [NEOE].[BANK_SENDH] ADD  CONSTRAINT [DF__BANK_SEND__DOCU___35AB1CCD]  DEFAULT ('0') FOR [DOCU_STAT]
GO

ALTER TABLE [NEOE].[BANK_SENDH] ADD  CONSTRAINT [DF__BANK_SEND__INSER__369F4106]  DEFAULT ('00000000') FOR [INSERT_DATE]
GO

ALTER TABLE [NEOE].[BANK_SENDH] ADD  CONSTRAINT [DF__BANK_SEND__INSER__3793653F]  DEFAULT ('000000') FOR [INSERT_TIME]
GO

ALTER TABLE [NEOE].[BANK_SENDH] ADD  CONSTRAINT [DF__BANK_SEND__SEND___2CDD9B17]  DEFAULT ('N') FOR [SEND_STATUS]
GO

ALTER TABLE [NEOE].[BANK_SENDH] ADD  CONSTRAINT [DF__BANK_SEND__NO_DO__040B3217]  DEFAULT ((0)) FOR [NO_DOLINE]
GO

ALTER TABLE [NEOE].[BANK_SENDH] ADD  CONSTRAINT [DF__BANK_SEND__YN_LI__04FF5650]  DEFAULT ('N') FOR [YN_LIMITE]
GO


