USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_MA_PARTNER_PRICEH_S]    Script Date: 2016-08-09 오후 1:30:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER PROCEDURE [NEOE].[SP_CZ_MA_PARTNER_PRICEH_S]
(
	@P_CD_COMPANY			NVARCHAR(7),
	@P_CD_PLANT				NVARCHAR(20),
	@P_CD_PARTNER			NVARCHAR(20),
	@P_TP_PS				NVARCHAR(3),
	@P_TP_SEARCH1		    NVARCHAR(3),
	@P_TP_SEARCH2		    NVARCHAR(3),
	@P_DC_SEARCH1		    NVARCHAR(100),
	@P_DC_SEARCH2		    NVARCHAR(100),
	@P_CD_CLS_S				NVARCHAR(4),
	@P_CD_CLS_M				NVARCHAR(4),
	@P_YN_USE				NVARCHAR(1),
	@P_YN_REG				NVARCHAR(1),
	@P_CD_ITEMGRP			NVARCHAR(20),
	@P_YN_VALID				NVARCHAR(1),
	@P_TP_PROC				NVARCHAR(3)
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT 'N' AS S,
	   MP.CD_PARTNER,
	   MP.LN_PARTNER,
	   MP.CLS_PARTNER,
	   (SELECT NM_SYSDEF FROM MA_CODEDTL WHERE CD_COMPANY = MP.CD_COMPANY AND CD_FIELD = 'MA_B000003' AND CD_SYSDEF = MP.CLS_PARTNER) AS NM_CLS_PARTNER,
	   MP.USE_YN,
	   ISNULL(UP.QT_REG, 0) AS QT_REG
FROM MA_PARTNER MP
LEFT JOIN (SELECT MU.CD_COMPANY, 
				  MU.CD_PARTNER, 
				  COUNT(1) AS QT_REG 
		   FROM MA_ITEM_UMPARTNER MU
		   WHERE MU.CD_COMPANY = @P_CD_COMPANY
		   AND MU.CD_PLANT = @P_CD_PLANT
		   AND MU.TP_UMMODULE = @P_TP_PS
		   AND (ISNULL(@P_YN_VALID, 'N') <> 'Y' OR CONVERT(NVARCHAR(8), GETDATE(), 112) BETWEEN SDT_UM AND EDT_UM)
		   AND EXISTS (SELECT 1 
					   FROM MA_PITEM MI
					   WHERE MI.CD_COMPANY = MU.CD_COMPANY 
					   AND MI.CD_ITEM = MU.CD_ITEM 
					   AND (ISNULL(@P_CD_CLS_S, '') = '' OR MI.CLS_S = @P_CD_CLS_S)
					   AND (ISNULL(@P_CD_CLS_M, '') = '' OR MI.CLS_M = @P_CD_CLS_M)
					   AND (ISNULL(@P_CD_ITEMGRP, '') = '' OR MI.GRP_ITEM = @P_CD_ITEMGRP)
					   AND (ISNULL(@P_TP_PROC, '') = '' OR MI.TP_PROC = @P_TP_PROC)
					   AND (ISNULL(@P_DC_SEARCH1, '') = '' OR 
						    (@P_TP_SEARCH1 = '000' AND MI.CD_ITEM LIKE @P_DC_SEARCH1 + '%') OR
					   		(@P_TP_SEARCH1 = '001' AND MI.NM_ITEM LIKE '%' + @P_DC_SEARCH1 + '%') OR
					   		(@P_TP_SEARCH1 = '002' AND MI.STND_DETAIL_ITEM LIKE @P_DC_SEARCH1 + '%') OR
					   		(@P_TP_SEARCH1 = '003' AND MI.STND_ITEM LIKE @P_DC_SEARCH1 + '%') OR
					   		(@P_TP_SEARCH1 = '004' AND MI.MAT_ITEM LIKE '%' + @P_DC_SEARCH1 + '%') OR
					   		(@P_TP_SEARCH1 = '005' AND MI.DC_RMK1 LIKE '%' + @P_DC_SEARCH1 + '%') OR
					   		(@P_TP_SEARCH1 = '006' AND MI.DC_RMK2 LIKE '%' + @P_DC_SEARCH1 + '%'))
					   AND (ISNULL(@P_DC_SEARCH2, '') = '' OR 
							(@P_TP_SEARCH2 = '000' AND MI.CD_ITEM LIKE @P_DC_SEARCH2 + '%') OR
					   		(@P_TP_SEARCH2 = '001' AND MI.NM_ITEM LIKE '%' + @P_DC_SEARCH2 + '%') OR
					   		(@P_TP_SEARCH2 = '002' AND MI.STND_DETAIL_ITEM LIKE @P_DC_SEARCH2 + '%') OR
					   		(@P_TP_SEARCH2 = '003' AND MI.STND_ITEM LIKE @P_DC_SEARCH2 + '%') OR
					   		(@P_TP_SEARCH2 = '004' AND MI.MAT_ITEM LIKE '%' + @P_DC_SEARCH2 + '%') OR
					   		(@P_TP_SEARCH2 = '005' AND MI.DC_RMK1 LIKE '%' + @P_DC_SEARCH2 + '%') OR
					   		(@P_TP_SEARCH2 = '006' AND MI.DC_RMK2 LIKE '%' + @P_DC_SEARCH2 + '%')))
		   GROUP BY MU.CD_COMPANY, MU.CD_PARTNER) UP 
ON UP.CD_COMPANY = MP.CD_COMPANY AND  UP.CD_PARTNER = MP.CD_PARTNER
WHERE MP.CD_COMPANY = @P_CD_COMPANY
AND (ISNULL(@P_CD_PARTNER, '') = '' OR MP.CD_PARTNER = @P_CD_PARTNER)
AND (ISNULL(@P_YN_USE, '') = '' OR @P_YN_USE = @P_YN_USE)
AND ((ISNULL(MP.CLS_PARTNER, '') = '007') OR (@P_TP_PS = '001' AND ISNULL(MP.CLS_PARTNER, '') = '005') OR (@P_TP_PS = '002' AND ISNULL(MP.CLS_PARTNER, '') = '006'))
AND ((ISNULL(@P_DC_SEARCH1, '') = '' AND ISNULL(@P_DC_SEARCH2, '') = '' AND ISNULL(@P_CD_CLS_S, '') = '') OR ISNULL(UP.QT_REG, 0) > 0)
AND ((ISNULL(@P_YN_REG, '') = '') OR (@P_YN_REG = 'Y' AND ISNULL(UP.QT_REG, 0) > 0) OR (@P_YN_REG = 'N' AND ISNULL(UP.QT_REG, 0) = 0))
AND (ISNULL(@P_YN_VALID, 'N') <> 'Y' OR ISNULL(UP.QT_REG, 0) > 0)
ORDER BY ISNULL(UP.QT_REG, 0) DESC

GO

