USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_WEEKLY_RPT_L_JSON]    Script Date: 2017-01-05 오후 5:48:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_SA_WEEKLY_RPT_L_JSON]          
(
	@P_JSON			NVARCHAR(MAX),
	@P_ID_USER		NVARCHAR(10)	
)  
AS
   
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

DELETE RL
FROM CZ_SA_WEEKLY_RPT_L RL
WHERE EXISTS (SELECT 1 
			  FROM OPENJSON(@P_JSON)
			  WITH
			  (
					CD_COMPANY      NVARCHAR(7),
					NO_EMP			NVARCHAR(10),
					DT_YEAR			NVARCHAR(4),
					QT_WEEK			INT,
					TP_GUBUN		NVARCHAR(3),
					NO_KEY			NVARCHAR(20),
					JSON_FLAG		NVARCHAR(1)
			  ) JS
			  WHERE JS.JSON_FLAG = 'D'
			  AND JS.CD_COMPANY = RL.CD_COMPANY
			  AND JS.NO_EMP = RL.NO_EMP
			  AND JS.DT_YEAR = RL.DT_YEAR
			  AND JS.QT_WEEK = RL.QT_WEEK
			  AND JS.TP_GUBUN = RL.TP_GUBUN
			  AND JS.NO_KEY = RL.NO_KEY)

INSERT INTO CZ_SA_WEEKLY_RPT_L
(
	CD_COMPANY,
	NO_EMP,
	DT_YEAR,
	QT_WEEK,
	TP_GUBUN,
	NO_KEY,
	DC_CATEGORY,
	DT_FROM,
	DT_TO,
	DC_RMK,
	ID_INSERT,
	DTS_INSERT
)
SELECT CD_COMPANY,
	   NO_EMP,
	   DT_YEAR,
	   QT_WEEK,
	   TP_GUBUN,
	   NO_KEY,
	   DC_CATEGORY,
	   DT_FROM,
	   DT_TO,
	   DC_RMK,
	   @P_ID_USER,
	   NEOE.SF_SYSDATE(GETDATE())
FROM OPENJSON(@P_JSON)
WITH
(
	CD_COMPANY      NVARCHAR(7),
	NO_EMP			NVARCHAR(10),
	DT_YEAR			NVARCHAR(4),
	QT_WEEK			INT,
	TP_GUBUN		NVARCHAR(3),
	NO_KEY			NVARCHAR(20),
	DC_CATEGORY		NVARCHAR(100),
	DT_FROM			NVARCHAR(8),
	DT_TO			NVARCHAR(8),
	DC_RMK			NVARCHAR(2000),
	JSON_FLAG		NVARCHAR(1)
) JS
WHERE JS.JSON_FLAG = 'I'

UPDATE RL
SET RL.DC_CATEGORY = JS.DC_CATEGORY,
	RL.DT_FROM = JS.DT_FROM,
	RL.DT_TO = JS.DT_TO,
	RL.DC_RMK = JS.DC_RMK,
	RL.ID_UPDATE = @P_ID_USER,
	RL.DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE())
FROM CZ_SA_WEEKLY_RPT_L RL
JOIN OPENJSON(@P_JSON)
WITH
(
	CD_COMPANY      NVARCHAR(7),
	NO_EMP			NVARCHAR(10),
	DT_YEAR			NVARCHAR(4),
	QT_WEEK			INT,
	TP_GUBUN		NVARCHAR(3),
	NO_KEY			NVARCHAR(20),
	DC_CATEGORY		NVARCHAR(100),
	DT_FROM			NVARCHAR(8),
	DT_TO			NVARCHAR(8),
	DC_RMK			NVARCHAR(2000),
	JSON_FLAG		NVARCHAR(1)
) JS
ON JS.CD_COMPANY = RL.CD_COMPANY AND JS.NO_EMP = RL.NO_EMP AND JS.DT_YEAR = RL.DT_YEAR AND JS.QT_WEEK = RL.QT_WEEK AND JS.TP_GUBUN = RL.TP_GUBUN AND JS.NO_KEY = RL.NO_KEY
WHERE JS.JSON_FLAG = 'U'

GO