USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_WEEKLY_RPT_S3]    Script Date: 2018-11-26 오후 3:09:09 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_SA_WEEKLY_RPT_S3]
(
    @P_CD_COMPANY	NVARCHAR(7),
    @P_NO_EMP       NVARCHAR(10),
    @P_DT_YEAR      NVARCHAR(4),
    @P_QT_WEEK      INT
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT 'N' AS S,
       @P_NO_EMP AS NO_EMP,
       @P_DT_YEAR AS DT_YEAR,
       @P_QT_WEEK AS QT_WEEK,
       CH.NO_CLAIM,
       CH.NO_SO,
       CH.DT_INPUT,
       MP.LN_PARTNER AS NM_PARTNER,
       MP1.LN_PARTNER AS NM_SUPPLIER,
       MH.NM_VESSEL,
       ME.NM_KOR,
       MC.NM_SYSDEF AS NM_CLAIM,
       MC1.NM_SYSDEF AS NM_CAUSE,
       MC2.NM_SYSDEF AS NM_ITEM,
       MC3.NM_SYSDEF AS NM_GW_STAT,
       MC4.NM_SYSDEF AS NM_STATUS,
       MC5.NM_SYSDEF AS NM_REASON,
       MC6.NM_SYSDEF AS NM_RETURN,
       MC7.NM_SYSDEF AS NM_REQUEST,
       (CH.AM_ITEM_RCV + CH.AM_ADD_RCV) AS AM_TOTAL_RCV,
       CH.CD_STATUS, GW.ST_STAT
FROM CZ_SA_CLAIMH CH
LEFT JOIN (SELECT CL.CD_COMPANY, CL.NO_CLAIM, 
		   		  MAX(CL.CD_SUPPLIER) AS CD_SUPPLIER 
		   FROM CZ_SA_CLAIML CL
		   GROUP BY CL.CD_COMPANY, CL.NO_CLAIM) CL
ON CL.CD_COMPANY = CH.CD_COMPANY AND CL.NO_CLAIM = CH.NO_CLAIM 
LEFT JOIN MA_PARTNER MP ON MP.CD_COMPANY = CH.CD_COMPANY AND MP.CD_PARTNER = CH.CD_PARTNER
LEFT JOIN MA_PARTNER MP1 ON MP1.CD_COMPANY = CH.CD_COMPANY AND MP1.CD_PARTNER = CL.CD_SUPPLIER
LEFT JOIN CZ_MA_HULL MH ON MH.NO_IMO = CH.NO_IMO
LEFT JOIN MA_EMP ME ON ME.CD_COMPANY = CH.CD_COMPANY AND ME.NO_EMP = CH.NO_EMP
LEFT JOIN FI_GWDOCU GW ON GW.CD_COMPANY = 'K100' AND GW.CD_PC = '010000' AND GW.NO_DOCU = CH.CD_COMPANY + '-' + CH.NO_CLAIM + '-' + CH.CD_STATUS
LEFT JOIN MA_CODEDTL MC ON MC.CD_COMPANY = CH.CD_COMPANY AND MC.CD_FIELD = 'CZ_SA00001' AND MC.CD_SYSDEF = CH.TP_CLAIM
LEFT JOIN MA_CODEDTL MC1 ON MC1.CD_COMPANY = CH.CD_COMPANY AND MC1.CD_FIELD = 'CZ_SA00002' AND MC1.CD_SYSDEF = CH.TP_CAUSE
LEFT JOIN MA_CODEDTL MC2 ON MC2.CD_COMPANY = CH.CD_COMPANY AND MC2.CD_FIELD = 'CZ_SA00003' AND MC2.CD_SYSDEF = CH.TP_ITEM
LEFT JOIN MA_CODEDTL MC3 ON MC3.CD_COMPANY = GW.CD_COMPANY AND MC3.CD_FIELD = 'PU_C000065' AND MC3.CD_SYSDEF = GW.ST_STAT
LEFT JOIN MA_CODEDTL MC4 ON MC4.CD_COMPANY = CH.CD_COMPANY AND MC4.CD_FIELD = 'CZ_SA00004' AND MC4.CD_SYSDEF = CH.CD_STATUS
LEFT JOIN MA_CODEDTL MC5 ON MC5.CD_COMPANY = CH.CD_COMPANY AND MC5.CD_FIELD = 'CZ_SA00048' AND MC5.CD_SYSDEF = CH.TP_REASON
LEFT JOIN MA_CODEDTL MC6 ON MC6.CD_COMPANY = CH.CD_COMPANY AND MC6.CD_FIELD = 'CZ_SA00050' AND MC6.CD_SYSDEF = CH.TP_RETURN
LEFT JOIN MA_CODEDTL MC7 ON MC7.CD_COMPANY = CH.CD_COMPANY AND MC7.CD_FIELD = 'CZ_SA00049' AND MC7.CD_SYSDEF = CH.TP_REQUEST
WHERE CH.CD_COMPANY = @P_CD_COMPANY
AND CH.NO_EMP = @P_NO_EMP
AND (ISNULL(CH.CD_STATUS, '') <> '3' OR ISNULL(GW.ST_STAT, '') <> '1')
AND NOT EXISTS (SELECT 1 
                FROM CZ_SA_WEEKLY_RPT_L RL
                WHERE RL.CD_COMPANY = CH.CD_COMPANY
                AND RL.NO_EMP = @P_NO_EMP
                AND RL.DT_YEAR = @P_DT_YEAR
                AND RL.QT_WEEK = @P_QT_WEEK
                AND RL.TP_GUBUN = '004'
                AND RL.NO_KEY = CH.NO_CLAIM)

GO