USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_CRM_PARTNER_HIST_S]    Script Date: 2017-06-08 오후 7:52:31 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




ALTER PROCEDURE [NEOE].[SP_CZ_SA_CRM_PARTNER_HIST_S]
(
	@P_CD_COMPANY		NVARCHAR(7),
	@P_CD_PARTNER		NVARCHAR(1000),
	@P_NO_EMP_SALES		NVARCHAR(20) = '',
	@P_NO_EMP_LOG		NVARCHAR(20) = '',
	@P_CD_PARTNER_GRP	NVARCHAR(3)
) 
AS
 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT PH.SEQ,
       PH.CD_PARTNER,
       MP.LN_PARTNER,
	   MP.CD_PARTNER_GRP,
	   CD.NM_SYSDEF AS NM_PARTNER_GRP,
	   PH.DT_HIST,
	   MP1.TP_INQ,
	   MP1.TP_QTN,
	   MP1.TP_PO,
	   MP1.RT_SALES_DC,
	   PH.NO_EMP_SALES,
	   ME.NM_KOR AS NM_EMP_SALES,
	   PH.NO_EMP_SALES1,
	   ME1.NM_KOR AS NM_EMP_SALES1,
	   PH.NO_EMP_SALES2,
	   ME2.NM_KOR AS NM_EMP_SALES2,
	   PH.NO_EMP_SALES3,
	   ME3.NM_KOR AS NM_EMP_SALES3,
	   PH.NO_EMP_LOG,
	   ME4.NM_KOR AS NM_EMP_LOG,
	   PH.DC_ADDRESS1,
	   PH.DC_ADDRESS2,
	   PH.DC_ADDRESS3,
	   PH.DC_POTAL_ADDR,
	   PH.DC_POTAL_ID,
	   PH.DC_POTAL_PW,
	   PH.TP_ACK_SEND,
	   ISNULL(PH.YN_DUEDATE, 'N') AS YN_DUEDATE,
	   PH.DC_MARGIN_ENGINE,
	   PH.DC_MARGIN_SUPPLIER,
	   PH.DC_COMPETE,
	   PH.DC_INQ,
	   PH.DC_QTN,
	   PH.DC_QTN_SEND,
	   PH.DC_ACK,
	   PH.DC_DELIVERY,
	   PH.DC_INVOICE,
	   PH.DC_OUTSTANDING,
	   PH.DC_RMK,
	   PH.DC_GS,
	   PH.DC_PV,
	   PH.DC_NB
FROM CZ_SA_CRM_PARTNER_HIST PH
LEFT JOIN MA_PARTNER MP ON MP.CD_COMPANY = PH.CD_COMPANY AND MP.CD_PARTNER = PH.CD_PARTNER
LEFT JOIN CZ_MA_PARTNER MP1 ON MP1.CD_COMPANY = PH.CD_COMPANY AND MP1.CD_PARTNER = PH.CD_PARTNER
LEFT JOIN MA_EMP ME ON ME.CD_COMPANY = PH.CD_COMPANY AND ME.NO_EMP = PH.NO_EMP_SALES
LEFT JOIN MA_EMP ME1 ON ME1.CD_COMPANY = PH.CD_COMPANY AND ME1.NO_EMP = PH.NO_EMP_SALES1
LEFT JOIN MA_EMP ME2 ON ME2.CD_COMPANY = PH.CD_COMPANY AND ME2.NO_EMP = PH.NO_EMP_SALES2
LEFT JOIN MA_EMP ME3 ON ME3.CD_COMPANY = PH.CD_COMPANY AND ME3.NO_EMP = PH.NO_EMP_SALES3
LEFT JOIN MA_EMP ME4 ON ME4.CD_COMPANY = PH.CD_COMPANY AND ME4.NO_EMP = PH.NO_EMP_LOG
LEFT JOIN MA_CODEDTL CD ON CD.CD_COMPANY = MP.CD_COMPANY AND CD.CD_FIELD = 'MA_B000065' AND CD.CD_SYSDEF = MP.CD_PARTNER_GRP
WHERE PH.CD_COMPANY = @P_CD_COMPANY
AND (ISNULL(@P_CD_PARTNER, '') = '' OR PH.CD_PARTNER IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_PARTNER)))
AND (ISNULL(@P_NO_EMP_SALES, '') = '' OR (PH.NO_EMP_SALES = @P_NO_EMP_SALES OR 
										  PH.NO_EMP_SALES1 = @P_NO_EMP_SALES OR 
										  PH.NO_EMP_SALES2 = @P_NO_EMP_SALES OR 
										  PH.NO_EMP_SALES3 = @P_NO_EMP_SALES))
AND (ISNULL(@P_NO_EMP_LOG, '') = '' OR PH.NO_EMP_LOG = @P_NO_EMP_LOG)
AND (ISNULL(@P_CD_PARTNER_GRP, '') = '' OR MP.CD_PARTNER_GRP = @P_CD_PARTNER_GRP)
ORDER BY PH.SEQ DESC

GO