USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_PU_STS_REG_SUBL_S]    Script Date: 2018-03-22 오후 5:40:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER PROCEDURE [NEOE].[SP_CZ_PU_STS_REG_SUBL_S]
(
	@P_CD_COMPANY       NVARCHAR(7),
	@P_NO_IO			NVARCHAR(20)
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT 'N' AS S,
	   OL.NO_IO,
	   OL.NO_IOLINE,
	   OL.CD_ITEM,
	   MI.NM_ITEM,
	   MI.UNIT_IM,
	   OL.CD_SL,
	   MS.NM_SL,
	   ISNULL(OL.QT_IO, 0) AS QT_IO,
	   ISNULL(OL1.QT_IO, 0) AS QT_TARGET,
	   (ISNULL(OL.QT_IO, 0) - ISNULL(OL1.QT_IO, 0)) AS QT_GOOD_INV,
	   OL.CD_PJT,
	   PH.NM_PROJECT AS NM_PJT,
	   OL.NO_PSO_MGMT,
	   OL.NO_PSOLINE_MGMT,
	   OH.NO_EMP,
	   ME.NM_KOR,
	   MD.NM_DEPT
FROM MM_QTIO OL
LEFT JOIN MM_QTIOH OH ON OH.CD_COMPANY = OL.CD_COMPANY AND OH.NO_IO = OL.NO_IO
LEFT JOIN (SELECT CD_COMPANY, NO_IO_MGMT, NO_IOLINE_MGMT,
			      SUM(QT_IO) AS QT_IO 
		   FROM MM_QTIO
		   GROUP BY CD_COMPANY, NO_IO_MGMT, NO_IOLINE_MGMT) OL1
ON OL1.CD_COMPANY = OL.CD_COMPANY AND OL1.NO_IO_MGMT = OL.NO_IO AND OL1.NO_IOLINE_MGMT = OL.NO_IOLINE
LEFT JOIN MA_PITEM MI ON MI.CD_COMPANY = OL.CD_COMPANY AND MI.CD_ITEM = OL.CD_ITEM
LEFT JOIN MA_SL MS ON MS.CD_COMPANY = OL.CD_COMPANY AND MS.CD_SL = OL.CD_SL
LEFT JOIN SA_PROJECTH PH ON PH.CD_COMPANY = OL.CD_COMPANY AND PH.NO_PROJECT = OL.CD_PJT
LEFT JOIN MA_EMP ME ON ME.CD_COMPANY = OH.CD_COMPANY AND ME.NO_EMP = OH.NO_EMP
LEFT JOIN MA_DEPT MD ON MD.CD_COMPANY = ME.CD_COMPANY AND MD.CD_DEPT = ME.CD_DEPT
WHERE OL.CD_COMPANY = @P_CD_COMPANY
AND OL.NO_IO = @P_NO_IO
AND ISNULL(OL.QT_IO, 0) > ISNULL(OL1.QT_IO, 0)

GO

