USE [NEOE]
GO

/****** Object:  Table [NEOE].[CZ_SA_MEETING_MEMO_LOG]    Script Date: 2020-01-15 오후 2:14:26 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [NEOE].[CZ_SA_MEETING_MEMO_LOG](
	[CD_COMPANY] [nvarchar](7) NOT NULL,
	[NO_MEETING] [nvarchar](20) NOT NULL,
	[SEQ] [numeric](18, 0) NOT NULL,
	[CD_PARTNER] [nvarchar](20) NULL,
	[DT_MEETING] [nvarchar](8) NULL,
	[DC_TIME] [nvarchar](100) NULL,
	[DC_LOCATION] [nvarchar](500) NULL,
	[DC_SUBJECT] [nvarchar](500) NULL,
	[DC_PURPOSE] [nvarchar](500) NULL,
	[DC_MEETING] [nvarchar](max) NULL,
	[NO_GW_DOCU] [nvarchar](20) NULL,
	[TP_LOG] [nvarchar](1) NULL,
	[ID_LOG] [nvarchar](15) NULL,
	[DTS_LOG] [nvarchar](14) NULL,
 CONSTRAINT [PK_CZ_SA_MEETING_MEMO_LOG] PRIMARY KEY CLUSTERED 
(
	[CD_COMPANY] ASC,
	[NO_MEETING] ASC,
	[SEQ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


