USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_PU_HSD_STOCK_RPT_U]    Script Date: 2015-06-16 ¿ÀÈÄ 3:36:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_PU_HSD_STOCK_RPT_U] 
(
	@P_CD_COMPANY		NVARCHAR(7),
	@P_NO_FILE			NVARCHAR(20),
	@P_NO_LINE			NUMERIC(5, 0),
	@P_DT_SO			NVARCHAR(8),
	@P_NO_PO_PARTNER	NVARCHAR(200),
	@P_NM_PARTNER		NVARCHAR(200),
	@P_NM_VESSEL		NVARCHAR(200),
	@P_NM_MODEL			NVARCHAR(200),
	@P_ID_USER			NVARCHAR(15)
) 
AS 

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

IF EXISTS (SELECT 1 
		   FROM CZ_PU_HSD_STOCK_RPT
		   WHERE CD_COMPANY = @P_CD_COMPANY
		   AND NO_FILE = @P_NO_FILE
		   AND NO_LINE = @P_NO_LINE)
BEGIN
	UPDATE CZ_PU_HSD_STOCK_RPT
	SET DT_SO = @P_DT_SO,
		NO_PO_PARTNER = @P_NO_PO_PARTNER,
		NM_PARTNER = @P_NM_PARTNER,
		NM_VESSEL = @P_NM_VESSEL,
		NM_MODEL = @P_NM_MODEL,
		ID_UPDATE = @P_ID_USER,
		DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE())
	WHERE CD_COMPANY = @P_CD_COMPANY
	AND NO_FILE = @P_NO_FILE
	AND NO_LINE = @P_NO_LINE
END
ELSE
BEGIN
	INSERT INTO CZ_PU_HSD_STOCK_RPT
	(
		CD_COMPANY,
		NO_FILE,
		NO_LINE,
		DT_SO,
		NO_PO_PARTNER,
		NM_PARTNER,
		NM_VESSEL,
		NM_MODEL,
		ID_INSERT,
		DTS_INSERT
	)
	VALUES
	(
		@P_CD_COMPANY,
		@P_NO_FILE,
		@P_NO_LINE,
		@P_DT_SO,
		@P_NO_PO_PARTNER,
		@P_NM_PARTNER,
		@P_NM_VESSEL,
		@P_NM_MODEL,
		@P_ID_USER,
		NEOE.SF_SYSDATE(GETDATE())
	)
END

GO