USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_LOG_PLAN_MNG_OLD_XML]    Script Date: 2016-02-12 오후 1:40:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_SA_LOG_PLAN_MNG_OLD_XML]  
(
    @P_XML			XML, 
	@P_ID_USER		NVARCHAR(10), 
    @DOC			INT = NULL
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

EXEC SP_XML_PREPAREDOCUMENT @DOC OUTPUT, @P_XML 

-- ================================================== DELETE
DELETE A 
FROM CZ_SA_LOG_PLAN_OLD A 
JOIN OPENXML (@DOC, '/XML/D', 2) 
        WITH (NO_IDX		INT) B 
ON A.NO_IDX = B.NO_IDX

DELETE A 
FROM CZ_SA_LOG_PLAN_OLD_L A 
JOIN OPENXML (@DOC, '/XML/D', 2) 
        WITH (NO_IDX		INT) B 
ON A.NO_IDX = B.NO_IDX
-- ================================================== INSERT
INSERT INTO CZ_SA_LOG_PLAN_OLD
(
    CD_COMPANY,
	NO_IDX,
	NM_VESSEL,
    NO_IMO,
	DC_LOCATION,
    DC_PORT,
    DC_EMP,
    DC_ETB,
    DC_ETD,
    DT_COMPLETE,
    DC_CAR,
    DC_ITEM,
    DC_TEL,
    DC_ETC,
	NO_GIR,
	ID_INSERT,
	DTS_INSERT
)
SELECT CD_COMPANY,
	   NO_IDX,
	   NM_VESSEL,
       NO_IMO,
	   DC_LOCATION,
       DC_PORT,
       REPLACE(DC_EMP, CHAR(10), CHAR(13) + CHAR(10)),
       REPLACE(DC_ETB, CHAR(10), CHAR(13) + CHAR(10)),
       REPLACE(DC_ETD, CHAR(10), CHAR(13) + CHAR(10)),
       DT_COMPLETE,
       REPLACE(DC_CAR, CHAR(10), CHAR(13) + CHAR(10)),
	   REPLACE(DC_ITEM, CHAR(10), CHAR(13) + CHAR(10)) AS DC_ITEM,
       REPLACE(DC_TEL, CHAR(10), CHAR(13) + CHAR(10)),
	   REPLACE(DC_ETC, CHAR(10), CHAR(13) + CHAR(10)) AS DC_ETC,
	   REPLACE(NO_GIR, CHAR(10), CHAR(13) + CHAR(10)) AS NO_GIR,
       @P_ID_USER, 
       NEOE.SF_SYSDATE(GETDATE()) 
  FROM OPENXML (@DOC, '/XML/I', 2) 
          WITH (CD_COMPANY		NVARCHAR(7),
				NO_IDX			INT,
				NM_VESSEL		NVARCHAR(50),
				NO_IMO			NVARCHAR(10),
				DC_LOCATION		NVARCHAR(20),
				DC_PORT			NVARCHAR(20),
				DC_EMP			NVARCHAR(100),
				DC_ETB			NVARCHAR(10),
				DC_ETD			NVARCHAR(10),
				DT_COMPLETE		NVARCHAR(8),
				DC_CAR			NVARCHAR(50),
				DC_ITEM			NVARCHAR(MAX),
				DC_TEL			NVARCHAR(10),
				DC_ETC			NVARCHAR(MAX),
				NO_GIR			NVARCHAR(200)) 
-- ================================================== UPDATE    
UPDATE A 
   SET A.NM_VESSEL = B.NM_VESSEL,
	   A.DC_LOCATION = B.DC_LOCATION,
	   A.DC_PORT = B.DC_PORT,
	   A.DC_EMP = REPLACE(B.DC_EMP, CHAR(10), CHAR(13) + CHAR(10)),
	   A.DC_ETB = REPLACE(B.DC_ETB, CHAR(10), CHAR(13) + CHAR(10)),
	   A.DC_ETD = REPLACE(B.DC_ETD, CHAR(10), CHAR(13) + CHAR(10)),
	   A.DT_COMPLETE = B.DT_COMPLETE,
	   A.DC_CAR = REPLACE(B.DC_CAR, CHAR(10), CHAR(13) + CHAR(10)),
	   A.DC_ITEM = REPLACE(B.DC_ITEM, CHAR(10), CHAR(13) + CHAR(10)),
	   A.DC_TEL = REPLACE(B.DC_TEL, CHAR(10), CHAR(13) + CHAR(10)),
	   A.DC_ETC = REPLACE(B.DC_ETC, CHAR(10), CHAR(13) + CHAR(10)),
	   A.NO_GIR = REPLACE(B.NO_GIR, CHAR(10), CHAR(13) + CHAR(10)),
	   A.ID_UPDATE = @P_ID_USER, 
	   A.DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE())
  FROM CZ_SA_LOG_PLAN_OLD A 
  JOIN OPENXML (@DOC, '/XML/U', 2) 
          WITH (CD_COMPANY		NVARCHAR(7),
				NO_IDX			INT,
				NM_VESSEL		NVARCHAR(50),
				NO_IMO			NVARCHAR(10),
				DC_LOCATION		NVARCHAR(20),
				DC_PORT			NVARCHAR(20),
				DC_EMP			NVARCHAR(100),
				DC_ETB			NVARCHAR(10),
				DC_ETD			NVARCHAR(10),
				DT_COMPLETE		NVARCHAR(8),
				DC_CAR			NVARCHAR(50),
				DC_ITEM			NVARCHAR(MAX),
				DC_TEL			NVARCHAR(10),
				DC_ETC			NVARCHAR(MAX),
				NO_GIR			NVARCHAR(200)) B 
  ON A.NO_IDX = B.NO_IDX

EXEC SP_XML_REMOVEDOCUMENT @DOC 

GO