USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_LOG_PLAN_MNG_VESSEL_S]    Script Date: 2016-02-12 오후 1:40:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_SA_LOG_PLAN_MNG_VESSEL_S]  
(
    @P_NO_REV       INT
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT 'N' AS S,
       PV.CD_COMPANY,
       PV.NO_REV,
       PV.NO_IDX,
       PV.NO_IMO,
       PV.NM_VESSEL,
       PV.DC_LOCATION,
       PV.DC_PORT,
       PV.DC_EMP,
       PV.DC_ETB,
       PV.DC_ETD,
       PV.DT_COMPLETE,
       PV.DC_CAR,
       SP.DC_ITEM,
       PV.DC_TEL,
       PV.DC_ETC,
       SP.NO_GIR,
       PV.DC_SORT,
       STUFF((SELECT '+' + MC.CD_FLAG2 + CONVERT(VARCHAR, CONVERT(INT, PH.QT_WIDTH))
			  FROM CZ_SA_LOG_PLAN_SHIP PS
              JOIN CZ_SA_PACKH PH ON PH.CD_COMPANY = PS.CD_COMPANY AND PH.NO_GIR = PS.NO_GIR
			  JOIN MA_CODEDTL MC ON MC.CD_COMPANY = PH.CD_COMPANY AND MC.CD_FIELD = 'CZ_SA00026' AND MC.CD_SYSDEF = PH.CD_TYPE
              WHERE PS.CD_COMPANY = PV.CD_COMPANY
              AND PS.NO_REV = PV.NO_REV
              AND PS.NO_IDX = PV.NO_IDX
			  FOR XML PATH('')), 1,1, '') AS DC_PACK,
       (SELECT SUM(CASE WHEN PH.CD_TYPE IN ('002', '003') THEN CONVERT(INT, PH.QT_WIDTH) / 1000.0 ELSE 0 END)
        FROM CZ_SA_LOG_PLAN_SHIP PS
        JOIN CZ_SA_PACKH PH ON PH.CD_COMPANY = PS.CD_COMPANY AND PH.NO_GIR = PS.NO_GIR
        WHERE PS.CD_COMPANY = PV.CD_COMPANY
        AND PS.NO_REV = PV.NO_REV
        AND PS.NO_IDX = PV.NO_IDX) AS QT_PACK
FROM CZ_SA_LOG_PLAN_VESSEL PV
LEFT JOIN (SELECT SP.NO_REV, SP.NO_IDX,
                  STRING_AGG(SP.DC_ITEM, CHAR(13) + CHAR(10)) WITHIN GROUP (ORDER BY SP.NO_REV, SP.NO_IDX) AS DC_ITEM,
                  STRING_AGG(SP.NO_GIR, CHAR(13) + CHAR(10)) WITHIN GROUP (ORDER BY SP.NO_REV, SP.NO_IDX) AS NO_GIR
           FROM CZ_SA_LOG_PLAN_SHIP SP
           GROUP BY SP.NO_REV, SP.NO_IDX) SP
ON SP.NO_REV = PV.NO_REV AND SP.NO_IDX = PV.NO_IDX
WHERE PV.CD_COMPANY IN ('K100', 'K200') 
AND PV.NO_REV = @P_NO_REV
ORDER BY PV.DT_COMPLETE, ISNULL(NULLIF(PV.DC_EMP, ''), '99999'), PV.DC_LOCATION, PV.DC_ETB

GO