USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_LOG_PLAN_MNG_OLD_L_S]    Script Date: 2016-02-12 오후 1:40:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_SA_LOG_PLAN_MNG_OLD_L_S]  
(
    @P_NO_IDX       INT
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT 'N' AS S,
       PS.CD_COMPANY,
       PS.NO_IDX,
       PS.NO_GIR,
       PS.DT_COMPLETE,
       PS.DC_ITEM,
       PS.DC_ETC,
       STUFF((SELECT '+' + MC.CD_FLAG2 + CONVERT(VARCHAR, CONVERT(INT, PH.QT_WIDTH))
			  FROM CZ_SA_PACKH PH
			  JOIN MA_CODEDTL MC ON MC.CD_COMPANY = PH.CD_COMPANY AND MC.CD_FIELD = 'CZ_SA00026' AND MC.CD_SYSDEF = PH.CD_TYPE
			  WHERE PH.CD_COMPANY = PS.CD_COMPANY
			  AND PH.NO_GIR = PS.NO_GIR
			  FOR XML PATH('')), 1,1, '') AS DC_PACK,
       (SELECT SUM(CASE WHEN PH.CD_TYPE IN ('002', '003') THEN CONVERT(INT, PH.QT_WIDTH) / 1000.0 ELSE 0 END)
        FROM CZ_SA_PACKH PH
        WHERE PH.CD_COMPANY = PS.CD_COMPANY
        AND PH.NO_GIR = PS.NO_GIR) AS QT_PACK
FROM CZ_SA_LOG_PLAN_OLD_L PS
WHERE PS.NO_IDX = @P_NO_IDX

GO