USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_LOG_PLAN_MNG_WORD_S]    Script Date: 2016-02-12 오후 1:40:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_SA_LOG_PLAN_MNG_WORD_S]  
(
    @P_CD_COMPANY       NVARCHAR(7)
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT WD.CD_COMPANY,
       WD.SEQ,
       WD.DC_WORD
FROM CZ_SA_LOG_PLAN_WORD WD
WHERE WD.CD_COMPANY = @P_CD_COMPANY

GO