USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_LOG_PLAN_MNG_REV_XML]    Script Date: 2016-02-12 오후 1:40:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_SA_LOG_PLAN_MNG_REV_XML]  
(
    @P_XML			XML, 
	@P_ID_USER		NVARCHAR(10), 
    @DOC			INT = NULL
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

EXEC SP_XML_PREPAREDOCUMENT @DOC OUTPUT, @P_XML 

-- ================================================== DELETE
DELETE A 
FROM CZ_SA_LOG_PLAN_REV A 
JOIN OPENXML (@DOC, '/XML/D', 2) 
        WITH (CD_COMPANY	NVARCHAR(7),
			  NO_REV 		INT) B 
ON A.CD_COMPANY = B.CD_COMPANY
AND A.NO_REV = B.NO_REV

DELETE A 
FROM CZ_SA_LOG_PLAN_VESSEL A 
JOIN OPENXML (@DOC, '/XML/D', 2) 
        WITH (CD_COMPANY	NVARCHAR(7),
			  NO_REV 		INT) B 
ON A.CD_COMPANY = B.CD_COMPANY 
AND A.NO_REV = B.NO_REV

DELETE A 
FROM CZ_SA_LOG_PLAN_SHIP A 
JOIN OPENXML (@DOC, '/XML/D', 2) 
        WITH (CD_COMPANY	NVARCHAR(7),
			  NO_REV 		INT) B 
ON A.CD_COMPANY = B.CD_COMPANY 
AND A.NO_REV = B.NO_REV

DELETE A 
FROM CZ_SA_LOG_PLAN_DELIVERY A 
JOIN OPENXML (@DOC, '/XML/D', 2) 
        WITH (CD_COMPANY	NVARCHAR(7),
			  NO_REV 		INT) B 
ON A.CD_COMPANY = B.CD_COMPANY
AND A.NO_REV = B.NO_REV
-- ================================================== INSERT
INSERT INTO CZ_SA_LOG_PLAN_REV 
(
    CD_COMPANY,
	DT_WORK,
	NO_REV,
	DC_RMK,
	ID_INSERT,
	DTS_INSERT
)
SELECT CD_COMPANY,
       DT_WORK,
	   NO_REV,
	   DC_RMK,
       @P_ID_USER, 
       NEOE.SF_SYSDATE(GETDATE()) 
  FROM OPENXML (@DOC, '/XML/I', 2) 
          WITH (CD_COMPANY		NVARCHAR(7),
				DT_WORK			NVARCHAR(8),
				NO_REV			INT,
				DC_RMK			NVARCHAR(100))
				
-- ================================================== UPDATE    
UPDATE A 
   SET A.DT_WORK = B.DT_WORK,
	   A.DC_RMK = REPLACE(B.DC_RMK, CHAR(10), CHAR(13) + CHAR(10)),
	   A.ID_UPDATE = @P_ID_USER, 
	   A.DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE())
  FROM CZ_SA_LOG_PLAN_REV A 
  JOIN OPENXML (@DOC, '/XML/U', 2) 
          WITH (CD_COMPANY		NVARCHAR(7),
				DT_WORK			NVARCHAR(8),
				NO_REV			INT,
				DC_RMK			NVARCHAR(100)) B 
  ON A.CD_COMPANY = B.CD_COMPANY
  AND A.NO_REV = B.NO_REV

EXEC SP_XML_REMOVEDOCUMENT @DOC 

GO