USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_LOG_PLAN_MNG_GIR_S1]    Script Date: 2016-02-12 오후 1:40:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_SA_LOG_PLAN_MNG_GIR_S1]  
(
    @P_CD_COMPANY       NVARCHAR(7),
    @P_NO_GIR	        NVARCHAR(20)
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

;WITH A AS
(
    SELECT GH.CD_COMPANY,
           MC1.NM_SYSDEF AS NM_SUB_CATEGORY,
           MC2.NM_SYSDEF AS NM_RMK,
           WD.CD_COLLECT_FROM AS GI_PARTNER,
           MP.LN_PARTNER AS NM_GI_PARTNER,
           GH.NO_EMP,
           ME.NM_KOR AS NM_EMP,
           GL.QT_ITEM,
           WD.NO_IMO,
           MH.NM_VESSEL,
           WD.DT_COMPLETE,
           STUFF((SELECT DISTINCT ',' + LEFT(GL.NO_SO, 2)
    			  FROM CZ_SA_GIRL_PACK GL
    			  WHERE GL.CD_COMPANY = GH.CD_COMPANY
    			  AND GL.NO_GIR = GH.NO_GIR
    			  FOR XML PATH('')), 1,1, '')AS NO_SO_PRE,
            WD.DC_RMK1,
            GL.NM_ITEMGRP,
            GH.NO_GIR,
            STUFF((SELECT '+' + MC.CD_FLAG2 + CONVERT(VARCHAR, CONVERT(INT, PH.QT_WIDTH))
    			  FROM CZ_SA_PACKH PH
    			  JOIN MA_CODEDTL MC ON MC.CD_COMPANY = PH.CD_COMPANY AND MC.CD_FIELD = 'CZ_SA00026' AND MC.CD_SYSDEF = PH.CD_TYPE
    			  WHERE PH.CD_COMPANY = GH.CD_COMPANY
    			  AND PH.NO_GIR = GH.NO_GIR
    			  FOR XML PATH('')), 1,1, '')AS DC_RESULT_PACK,
            WD.DC_RMK AS DC_RMK_CI,
            WD.DC_RMK3,
            WD.DC_RESULT,
            GL.AM_GIR_10000,
            PH.DC_RMK AS DC_RMK_PL,
            WD.DTS_CONFIRM,
            WD.DTS_UPDATE
    FROM CZ_SA_GIRH_PACK GH
    JOIN CZ_SA_GIRH_PACK_DETAIL WD ON WD.CD_COMPANY = GH.CD_COMPANY AND WD.NO_GIR = GH.NO_GIR
    LEFT JOIN (SELECT GL.CD_COMPANY, GL.NO_GIR,
                      COUNT(1) AS QT_ITEM,
                      MAX(IG.NM_ITEMGRP) AS NM_ITEMGRP,
                      ROUND(SUM(GL.AM_GIRAMT) / 10000, 0, 1) AS AM_GIR_10000
               FROM CZ_SA_GIRL_PACK GL
    		   LEFT JOIN CZ_SA_QTNL QL ON QL.CD_COMPANY = GL.CD_COMPANY AND QL.NO_FILE = ISNULL(GL.NO_SO, GL.NO_SO_MGMT) AND QL.NO_LINE = (CASE WHEN GL.SEQ_SO = 0 THEN GL.NO_SOLINE_MGMT ELSE GL.SEQ_SO END)
    		   LEFT JOIN MA_ITEMGRP IG ON IG.CD_COMPANY = QL.CD_COMPANY AND IG.CD_ITEMGRP = QL.GRP_ITEM
               GROUP BY GL.CD_COMPANY, GL.NO_GIR) GL
    ON GL.CD_COMPANY = GH.CD_COMPANY AND GL.NO_GIR = GH.NO_GIR
    LEFT JOIN (SELECT CD_COMPANY, NO_GIR,
    				  MAX(DC_RMK) AS DC_RMK 
    		   FROM CZ_SA_PACKH
    		   GROUP BY CD_COMPANY, NO_GIR) PH
    ON PH.CD_COMPANY = GH.CD_COMPANY AND PH.NO_GIR = GH.NO_GIR
    LEFT JOIN CZ_MA_DELIVERY MP ON MP.CD_COMPANY = WD.CD_COMPANY AND MP.CD_PARTNER = WD.CD_COLLECT_FROM
    LEFT JOIN MA_EMP ME ON ME.CD_COMPANY = GH.CD_COMPANY AND ME.NO_EMP = GH.NO_EMP
    LEFT JOIN CZ_MA_HULL MH ON MH.NO_IMO = WD.NO_IMO
    LEFT JOIN MA_CODEDTL MC ON MC.CD_COMPANY = GH.CD_COMPANY AND MC.CD_FIELD = 'CZ_SA00020' AND MC.CD_SYSDEF = WD.CD_PACK_CATEGORY
    LEFT JOIN MA_CODEDTL MC1 ON MC1.CD_COMPANY = GH.CD_COMPANY AND MC1.CD_FIELD = MC.CD_FLAG1 AND MC1.CD_SYSDEF = WD.CD_SUB_CATEGORY
    LEFT JOIN MA_CODEDTL MC2 ON MC2.CD_COMPANY = GH.CD_COMPANY AND MC2.CD_FIELD = 'CZ_SA00032' AND MC2.CD_SYSDEF = WD.CD_RMK
    WHERE GH.CD_COMPANY = @P_CD_COMPANY
    AND GH.NO_GIR = @P_NO_GIR
    UNION ALL
    SELECT GH.CD_COMPANY,
           MC1.NM_SYSDEF AS NM_SUB_CATEGORY,
           MC2.NM_SYSDEF AS NM_RMK,
           WD.CD_DELIVERY_TO AS GI_PARTNER,
           MP.LN_PARTNER AS NM_GI_PARTNER,
           GH.NO_EMP,
           ME.NM_KOR AS NM_EMP,
           GL.QT_ITEM,
           WD.NO_IMO,
           MH.NM_VESSEL,
           WD.DT_COMPLETE,
           STUFF((SELECT DISTINCT ',' + LEFT(GL.NO_SO, 2)
    			  FROM SA_GIRL GL
    			  WHERE GL.CD_COMPANY = GH.CD_COMPANY
    			  AND GL.NO_GIR = GH.NO_GIR
    			  FOR XML PATH('')), 1,1, '')AS NO_SO_PRE,
            WD.DC_RMK1,
            GL.NM_ITEMGRP,
            GH.NO_GIR,
            STUFF((SELECT '+' + MC.CD_FLAG2 + CONVERT(VARCHAR, CONVERT(INT, PH.QT_WIDTH))
    			  FROM CZ_SA_PACKH PH
    			  JOIN MA_CODEDTL MC ON MC.CD_COMPANY = PH.CD_COMPANY AND MC.CD_FIELD = 'CZ_SA00026' AND MC.CD_SYSDEF = PH.CD_TYPE
    			  WHERE PH.CD_COMPANY = GH.CD_COMPANY
    			  AND PH.NO_GIR = GH.NO_GIR
    			  FOR XML PATH('')), 1,1, '')AS DC_RESULT_PACK,
            WD.DC_RMK AS DC_RMK_CI,
            WD.DC_RMK3,
            WD.DC_RESULT,
            GL.AM_GIR_10000,
            PH.DC_RMK AS DC_RMK_PL,
            WD.DTS_CONFIRM,
            WD.DTS_UPDATE
    FROM SA_GIRH GH
    JOIN CZ_SA_GIRH_WORK_DETAIL WD ON WD.CD_COMPANY = GH.CD_COMPANY AND WD.NO_GIR = GH.NO_GIR
    LEFT JOIN (SELECT GL.CD_COMPANY, GL.NO_GIR,
                      COUNT(1) AS QT_ITEM,
                      MAX(IG.NM_ITEMGRP) AS NM_ITEMGRP,
                      ROUND(SUM(GL.AM_GIRAMT) / 10000, 0, 1) AS AM_GIR_10000
               FROM SA_GIRL GL
    		   LEFT JOIN CZ_SA_QTNL QL ON QL.CD_COMPANY = GL.CD_COMPANY AND QL.NO_FILE = ISNULL(GL.NO_SO, GL.NO_SO_MGMT) AND QL.NO_LINE = (CASE WHEN GL.SEQ_SO = 0 THEN GL.NO_SOLINE_MGMT ELSE GL.SEQ_SO END)
    		   LEFT JOIN MA_ITEMGRP IG ON IG.CD_COMPANY = QL.CD_COMPANY AND IG.CD_ITEMGRP = QL.GRP_ITEM
               GROUP BY GL.CD_COMPANY, GL.NO_GIR) GL
    ON GL.CD_COMPANY = GH.CD_COMPANY AND GL.NO_GIR = GH.NO_GIR
    LEFT JOIN (SELECT CD_COMPANY, NO_GIR,
    				  MAX(DC_RMK) AS DC_RMK 
    		   FROM CZ_SA_PACKH
    		   GROUP BY CD_COMPANY, NO_GIR) PH
    ON PH.CD_COMPANY = GH.CD_COMPANY AND PH.NO_GIR = GH.NO_GIR
    LEFT JOIN CZ_MA_DELIVERY MP ON MP.CD_COMPANY = WD.CD_COMPANY AND MP.CD_PARTNER = WD.CD_DELIVERY_TO
    LEFT JOIN MA_EMP ME ON ME.CD_COMPANY = GH.CD_COMPANY AND ME.NO_EMP = GH.NO_EMP
    LEFT JOIN CZ_MA_HULL MH ON MH.NO_IMO = WD.NO_IMO
    LEFT JOIN MA_CODEDTL MC ON MC.CD_COMPANY = GH.CD_COMPANY AND MC.CD_FIELD = 'CZ_SA00006' AND MC.CD_SYSDEF = WD.CD_MAIN_CATEGORY
    LEFT JOIN MA_CODEDTL MC1 ON MC1.CD_COMPANY = GH.CD_COMPANY AND MC1.CD_FIELD = MC.CD_FLAG1 AND MC1.CD_SYSDEF = WD.CD_SUB_CATEGORY
    LEFT JOIN MA_CODEDTL MC2 ON MC2.CD_COMPANY = GH.CD_COMPANY AND MC2.CD_FIELD = 'CZ_SA00032' AND MC2.CD_SYSDEF = WD.CD_RMK
    WHERE GH.CD_COMPANY = @P_CD_COMPANY
    AND GH.NO_GIR = @P_NO_GIR
)
SELECT 'N' AS S,
       *,
       (ISNULL(A.NO_SO_PRE, '') + '-' + 
        CONVERT(NVARCHAR, CONVERT(INT, ISNULL(A.QT_ITEM, 0))) + '-' + 
        TRIM(ISNULL(A.NM_ITEMGRP, '')) + '-' + 
        CONVERT(NVARCHAR, CONVERT(INT, ISNULL(A.AM_GIR_10000, 0))) + '만원') AS DC_RMK_QTY 
FROM A
ORDER BY A.NM_VESSEL
OPTION(RECOMPILE)

GO