USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_COMMISSION_MNGD2_S]    Script Date: 2018-11-02 오전 10:01:23 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_SA_COMMISSION_MNGD2_S]
(
	@P_CD_COMPANY		NVARCHAR(7),
	@P_NO_COMMISSION	NVARCHAR(20)
) 
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT @P_CD_COMPANY AS CD_COMPANY,
	   @P_NO_COMMISSION AS NO_COMMISSION,
	   CD.NO_SO,
	   SH.NM_EXCH,
	   SH.RT_EXCH,
	   SL.NM_ITEMGRP,
	   ISNULL(SH.AM_SO, 0) AS AM_SO,
	   ISNULL(PH.AM_PO, 0) AS AM_PO,
	   ISNULL(SH.AM_STOCK, 0) AS AM_STOCK,
	   (ISNULL(CD.AM_COMMISSION, 0) * ISNULL(SH.RT_EXCH, 0)) AS AM_COMMISSION,
	   (ISNULL(CD.AM_COMMISSION_BEFORE, 0) * ISNULL(SH.RT_EXCH, 0)) AS AM_COMMISSION_BEFORE,
	   (ISNULL(SH.AM_SO, 0) - (ISNULL(PH.AM_PO, 0) + ISNULL(SH.AM_STOCK, 0))) AS AM_PROFIT,
	   (ISNULL(SH.AM_SO, 0) - (ISNULL(PH.AM_PO, 0) + ISNULL(SH.AM_STOCK, 0) + (ISNULL(CD.AM_COMMISSION, 0) * ISNULL(SH.RT_EXCH, 0)) + (ISNULL(CD.AM_COMMISSION_BEFORE, 0) * ISNULL(SH.RT_EXCH, 0)))) AS AM_PROFIT1,
	   (CASE WHEN ISNULL(SH.AM_SO, 0) = 0 THEN 0 ELSE ROUND(((ISNULL(SH.AM_SO, 0) - (ISNULL(PH.AM_PO, 0) + ISNULL(SH.AM_STOCK, 0))) / ISNULL(SH.AM_SO, 0)) * 100, 2) END) AS RT_PROFIT,
	   (CASE WHEN ISNULL(SH.AM_SO, 0) = 0 THEN 0 ELSE ROUND(((ISNULL(SH.AM_SO, 0) - (ISNULL(PH.AM_PO, 0) + ISNULL(SH.AM_STOCK, 0) + (ISNULL(CD.AM_COMMISSION, 0) * ISNULL(SH.RT_EXCH, 0)) + (ISNULL(CD.AM_COMMISSION_BEFORE, 0) * ISNULL(SH.RT_EXCH, 0)))) / ISNULL(SH.AM_SO, 0)) * 100, 2) END) AS RT_PROFIT1
FROM (SELECT CD.CD_COMPANY, CD.NO_SO,
	  	     SUM(CD.AM_COMMISSION) AS AM_COMMISSION,
			 SUM(CD.AM_COMMISSION_BEFORE) AS AM_COMMISSION_BEFORE
	  FROM CZ_SA_COMMISSIOND CD
	  WHERE CD.CD_COMPANY = @P_CD_COMPANY
	  AND CD.NO_COMMISSION = @P_NO_COMMISSION
	  GROUP BY CD.CD_COMPANY, CD.NO_SO, CD.YN_ADDED) CD
LEFT JOIN (SELECT SH.CD_COMPANY, 
				  SH.NO_SO,
				  MC.NM_SYSDEF AS NM_EXCH,
				  SH.RT_EXCH,
				  SUM(SL.AM_WONAMT) AS AM_SO,
				  ISNULL(SUM(SB.UM_KR * SB.QT_STOCK), 0) AS AM_STOCK
	       FROM SA_SOH SH
		   JOIN SA_SOL SL ON SL.CD_COMPANY = SH.CD_COMPANY AND SL.NO_SO = SH.NO_SO
		   LEFT JOIN CZ_SA_STOCK_BOOK SB ON SB.CD_COMPANY = SL.CD_COMPANY AND SB.NO_FILE = SL.NO_SO AND SB.NO_LINE = SL.SEQ_SO
		   LEFT JOIN MA_CODEDTL MC ON MC.CD_COMPANY = SH.CD_COMPANY AND MC.CD_FIELD = 'MA_B000005' AND MC.CD_SYSDEF = SH.CD_EXCH
		   LEFT JOIN MA_PITEM MI ON MI.CD_COMPANY = SL.CD_COMPANY AND MI.CD_PLANT = SL.CD_PLANT AND MI.CD_ITEM = SL.CD_ITEM
	       LEFT JOIN MA_ITEMGRP IG ON IG.CD_COMPANY = MI.CD_COMPANY AND IG.CD_ITEMGRP = MI.GRP_ITEM
		   GROUP BY SH.CD_COMPANY, 
				    SH.NO_SO, 
					SH.RT_EXCH, 
					MC.NM_SYSDEF) SH
ON SH.CD_COMPANY = CD.CD_COMPANY AND SH.NO_SO = CD.NO_SO
LEFT JOIN (SELECT PH.CD_COMPANY, PH.CD_PJT,
		   	      ISNULL(SUM(PL.AM), 0) AS AM_PO
		   FROM PU_POH PH
		   JOIN PU_POL PL ON PL.CD_COMPANY = PH.CD_COMPANY AND PL.NO_PO = PH.NO_PO
		   GROUP BY PH.CD_COMPANY, PH.CD_PJT) PH
ON PH.CD_COMPANY = SH.CD_COMPANY AND PH.CD_PJT = SH.NO_SO
LEFT JOIN (SELECT SL.CD_COMPANY, SL.NO_SO,
		          STRING_AGG(TRIM(SL.NM_ITEMGRP), ',') AS NM_ITEMGRP 
		   FROM (SELECT SL.CD_COMPANY, SL.NO_SO, IG.NM_ITEMGRP
		         FROM SA_SOL SL
		         LEFT JOIN MA_PITEM MI ON MI.CD_COMPANY = SL.CD_COMPANY AND MI.CD_PLANT = SL.CD_PLANT AND MI.CD_ITEM = SL.CD_ITEM
		         LEFT JOIN MA_ITEMGRP IG ON IG.CD_COMPANY = MI.CD_COMPANY AND IG.CD_ITEMGRP = MI.GRP_ITEM
		         GROUP BY SL.CD_COMPANY, SL.NO_SO, IG.NM_ITEMGRP) SL
		   GROUP BY SL.CD_COMPANY, SL.NO_SO) SL
ON SL.CD_COMPANY = CD.CD_COMPANY AND SL.NO_SO = CD.NO_SO

GO

