USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_COMMISSION_MNGL_S]    Script Date: 2018-04-16 오후 2:06:36 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO






ALTER PROCEDURE [NEOE].[SP_CZ_SA_COMMISSION_MNGL_S]
(
	@P_CD_COMPANY		NVARCHAR(7),
	@P_NO_COMMISSION	NVARCHAR(20)
) 
AS
 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT CH.CD_COMPANY,
	   CH.NO_COMMISSION,
	   CL.SEQ,
	   FP.NM_PTR,
	   FP.NM_DEPT,
	   FP.NM_DUTY_RESP,
	   FP.NM_EMAIL,
	   CL.DC_RMK 
FROM CZ_SA_COMMISSIONH CH
JOIN CZ_SA_COMMISSIONL CL ON CL.CD_COMPANY = CH.CD_COMPANY AND CL.NO_COMMISSION = CH.NO_COMMISSION
JOIN FI_PARTNERPTR FP ON FP.CD_COMPANY = CH.CD_COMPANY AND FP.CD_PARTNER = CH.CD_PARTNER AND FP.SEQ = CL.SEQ
WHERE CH.CD_COMPANY = @P_CD_COMPANY
AND CH.NO_COMMISSION = @P_NO_COMMISSION

GO

