USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_COMMISSION_MNGD_XML]    Script Date: 2018-11-02 오후 1:31:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO







ALTER PROCEDURE [NEOE].[SP_CZ_SA_COMMISSION_MNGD_XML] 
(
	@P_XML			XML, 
	@P_ID_USER		NVARCHAR(10), 
    @DOC			INT = NULL
) 
AS 

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

EXEC SP_XML_PREPAREDOCUMENT @DOC OUTPUT, @P_XML 

-- ================================================== DELETE
DELETE A 
FROM CZ_SA_COMMISSIOND A 
JOIN OPENXML (@DOC, '/XML/D', 2) 
        WITH (CD_COMPANY	NVARCHAR(7),
			  NO_COMMISSION NVARCHAR(20),
			  YN_ADDED		NVARCHAR(1),
			  NO_IV			NVARCHAR(20),
			  NO_SO			NVARCHAR(20)) B 
ON A.CD_COMPANY = B.CD_COMPANY
AND A.NO_COMMISSION = B.NO_COMMISSION
AND A.YN_ADDED = B.YN_ADDED
AND A.NO_IV = B.NO_IV
AND A.NO_SO = B.NO_SO
-- ================================================== INSERT
INSERT INTO CZ_SA_COMMISSIOND 
(
	CD_COMPANY,
	NO_COMMISSION,
	YN_ADDED,
	NO_IV,
	NO_SO,
	DT_SO,
	DT_IV,
	DT_RCP,
	CD_EXCH,
	AM_IV,
	AM_CHARGE,
	AM_NET,
	YN_CHARGE,
	RT_COMMISSION,
	AM_COMMISSION,
	AM_OUTSTANDING,
	AM_COMMISSION_BEFORE,
	ID_INSERT,
	DTS_INSERT
)
SELECT CD_COMPANY,
	   NO_COMMISSION,
	   YN_ADDED,
	   NO_IV,
	   NO_SO,
	   DT_SO,
	   DT_IV,
	   DT_RCP,
	   CD_EXCH,
	   AM_IV,
	   AM_CHARGE,
	   AM_NET,
	   YN_CHARGE,
	   RT_COMMISSION,
	   AM_COMMISSION,
	   AM_OUTSTANDING,
	   AM_COMMISSION_BEFORE,
       @P_ID_USER, 
       NEOE.SF_SYSDATE(GETDATE()) 
  FROM OPENXML (@DOC, '/XML/I', 2) 
          WITH (CD_COMPANY			  NVARCHAR(7),
			    NO_COMMISSION		  NVARCHAR(20),
				YN_ADDED			  NVARCHAR(1),
				NO_IV				  NVARCHAR(20),
				NO_SO				  NVARCHAR(20),
				DT_SO				  NVARCHAR(8),
				DT_IV				  NVARCHAR(8),
				DT_RCP				  NVARCHAR(8),
				CD_EXCH				  NVARCHAR(4),
				AM_IV				  NUMERIC(18, 2),
				AM_CHARGE			  NUMERIC(18, 2),
				AM_NET				  NUMERIC(18, 2),
				YN_CHARGE			  NVARCHAR(1),
				RT_COMMISSION		  NUMERIC(5, 2),
				AM_COMMISSION		  NUMERIC(18, 2),
				AM_OUTSTANDING		  NUMERIC(18, 2),
				AM_COMMISSION_BEFORE  NUMERIC(18, 2))
-- ================================================== UPDATE    
UPDATE A 
   SET A.RT_COMMISSION = B.RT_COMMISSION,
	   A.AM_COMMISSION = B.AM_COMMISSION,
	   A.ID_UPDATE = @P_ID_USER, 
	   A.DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE())
  FROM CZ_SA_COMMISSIOND A 
  JOIN OPENXML (@DOC, '/XML/U', 2) 
          WITH (CD_COMPANY	   NVARCHAR(7),
			    NO_COMMISSION  NVARCHAR(20),
				NO_IV		   NVARCHAR(20),
				NO_SO		   NVARCHAR(20),
				RT_COMMISSION  NUMERIC(5, 2),
				AM_COMMISSION  NUMERIC(18, 2)) B 
  ON A.CD_COMPANY = B.CD_COMPANY
  AND A.NO_COMMISSION = B.NO_COMMISSION
  AND A.NO_IV = B.NO_IV
  AND A.NO_SO = B.NO_SO

EXEC SP_XML_REMOVEDOCUMENT @DOC 

GO

