USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_COMMISSION_DT_RCP_U]    Script Date: 2018-11-01 오후 4:03:14 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_SA_COMMISSION_DT_RCP_U]
(
	@P_CD_COMPANY		NVARCHAR(7),
    @P_NO_IV		    NVARCHAR(20),
    @P_NO_SO		    NVARCHAR(20),
    @P_ID_UPDATE        NVARCHAR(10)
) 
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

;WITH A AS
(
    SELECT IH.CD_COMPANY, 
           IH.NO_IV,
           IL.NO_SO,
    	   RH.DT_RCP,
    	   ((ISNULL(IL.AM_IV, 0) + ISNULL(IL.VAT_EX, 0)) - ISNULL(RH.AM_RCP_EX, 0)) AS AM_OUTSTANDING
    FROM SA_IVH IH
    JOIN (SELECT IL.CD_COMPANY, IL.NO_IV,
    			 (CASE WHEN IL.CD_PJT LIKE 'PJT%' THEN IL.NO_SO ELSE IL.CD_PJT END) AS NO_SO,
    			 MAX(IL.CD_PJT) AS CD_PJT,
    			 SUM(CASE WHEN IL.YN_RETURN = 'Y' THEN -IL.AM_EX_CLS ELSE IL.AM_EX_CLS END) AS AM_IV,
    			 SUM(CASE WHEN IL.YN_RETURN = 'Y' THEN -ROUND(IL.VAT / IL.RT_EXCH, 2) 
    											  ELSE ROUND(IL.VAT / IL.RT_EXCH, 2) END) AS VAT_EX
    	  FROM SA_IVL IL
    	  LEFT JOIN MA_PITEM MI ON MI.CD_COMPANY = IL.CD_COMPANY AND MI.CD_PLANT = IL.CD_PLANT AND MI.CD_ITEM = IL.CD_ITEM
    	  GROUP BY IL.CD_COMPANY, IL.NO_IV, (CASE WHEN IL.CD_PJT LIKE 'PJT%' THEN IL.NO_SO ELSE IL.CD_PJT END)) IL 
    ON IL.CD_COMPANY = IH.CD_COMPANY AND IL.NO_IV = IH.NO_IV
    LEFT JOIN (SELECT RH.CD_COMPANY, RD.NO_TX, RD.CD_PJT,
    				  MAX(RH.DT_RCP) AS DT_RCP,
    		          SUM(RD.AM_RCP_TX_EX) AS AM_RCP_EX
    		   FROM SA_RCPH RH
    		   JOIN (SELECT RD.CD_COMPANY, RD.NO_RCP, RD.NO_TX, FD.CD_PJT,
    		   		        RD.AM_RCP_TX_EX
    		   		 FROM SA_RCPD RD
    		   		 LEFT JOIN FI_DOCU FD ON FD.CD_COMPANY = RD.CD_COMPANY AND FD.NO_DOCU = RD.NO_DOCU AND FD.NO_DOLINE = RD.NO_DOLINE
    		   		 UNION ALL
    		   		 SELECT BD.CD_COMPANY, BD.NO_RCP, BD.NO_IV, FD.CD_PJT,
    		   		        BD.AM_RCPS_EX
    		   		 FROM SA_BILLSD BD
    		   		 LEFT JOIN FI_DOCU FD ON FD.CD_COMPANY = BD.CD_COMPANY AND FD.NO_DOCU = BD.NO_DOCU_IV AND FD.NO_DOLINE = BD.NO_DOLINE_IV) RD
    		   ON RD.CD_COMPANY = RH.CD_COMPANY AND RD.NO_RCP = RH.NO_RCP
    		   WHERE RD.NO_TX IS NOT NULL
    		   GROUP BY RH.CD_COMPANY, RD.NO_TX, RD.CD_PJT) RH
    ON RH.CD_COMPANY = IH.CD_COMPANY AND RH.NO_TX = IH.NO_IV AND RH.CD_PJT = IL.CD_PJT
)
UPDATE CD
SET CD.DT_RCP = A.DT_RCP,
    CD.AM_OUTSTANDING = A.AM_OUTSTANDING,
    CD.ID_UPDATE = @P_ID_UPDATE,
    CD.DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE())
FROM CZ_SA_COMMISSIOND CD
JOIN A ON A.CD_COMPANY = CD.CD_COMPANY AND A.NO_IV = CD.NO_IV AND A.NO_SO = CD.NO_SO 
WHERE CD.CD_COMPANY = @P_CD_COMPANY
AND CD.NO_IV = @P_NO_IV
AND CD.NO_SO = @P_NO_SO

GO

