USE [NEOE]
GO

/****** Object:  Table [NEOE].[CZ_FI_ACCT_EVIDENCEH]    Script Date: 2016-11-23 오전 11:41:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [NEOE].[CZ_FI_ACCT_EVIDENCEH](
	[CD_COMPANY] [nvarchar](7) NOT NULL,
	[CD_ACCT] [nvarchar](10) NOT NULL,
	[ID_INSERT] [nvarchar](15) NULL,
	[DTS_INSERT] [nvarchar](14) NULL,
 CONSTRAINT [PK_CZ_FI_ACCT_EVIDENCEH] PRIMARY KEY CLUSTERED 
(
	[CD_COMPANY] ASC,
	[CD_ACCT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


