USE [NEOE]
GO

/****** Object:  Table [NEOE].[CZ_FI_ACCT_EVIDENCEL]    Script Date: 2016-11-24 오전 10:16:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [NEOE].[CZ_FI_ACCT_EVIDENCEL](
	[CD_COMPANY] [nvarchar](7) NOT NULL,
	[CD_ACCT] [nvarchar](10) NOT NULL,
	[NO_LINE] [numeric](18, 0) NOT NULL,
	[FG_TAX] [nvarchar](3) NULL,
	[TP_EVIDENCE] [nvarchar](3) NOT NULL,
	[ID_INSERT] [nvarchar](15) NULL,
	[DTS_INSERT] [nvarchar](14) NULL,
	[ID_UPDATE] [nvarchar](15) NULL,
	[DTS_UPDATE] [nvarchar](14) NULL,
 CONSTRAINT [PK_CZ_FI_ACCT_EVIDENCEL_1] PRIMARY KEY CLUSTERED 
(
	[CD_COMPANY] ASC,
	[CD_ACCT] ASC,
	[NO_LINE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


