USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_FI_CARD_STATE_EXCEL]    Script Date: 2016-06-28 오후 1:28:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_FI_CARD_STATE_EXCEL] 
(
	@P_CD_COMPANY	NVARCHAR(7),
	@P_DT_MONTH     NVARCHAR(6),
	@P_XML			XML, 
	@P_ID_USER		NVARCHAR(10)
) 
AS 

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

DECLARE @V_DOC INT

EXEC SP_XML_PREPAREDOCUMENT @V_DOC OUTPUT, @P_XML 

SELECT * INTO #XML
FROM OPENXML (@V_DOC, '/XML/ROW', 2) WITH 
(
	부서명				NVARCHAR(50),
	카드번호				NVARCHAR(20)
)

EXEC SP_XML_REMOVEDOCUMENT @V_DOC

-- ================================================== INSERT
INSERT INTO CZ_FI_CARD_STATE
(
	CD_COMPANY,
	DT_MONTH,
	TP_CARD,
	NO_CARD,
	CD_DEPT,
	ID_INSERT,
	DTS_INSERT
)
SELECT @P_CD_COMPANY,
	   @P_DT_MONTH,
	   'BC카드',
       XL.[카드번호],
	   (CASE WHEN CHARINDEX('(', XL.[부서명]) > 0 THEN SUBSTRING(XL.[부서명], 0, CHARINDEX('(', XL.[부서명])) ELSE XL.[부서명] END),
	   @P_ID_USER,
	   NEOE.SF_SYSDATE(GETDATE())
FROM #XML XL
WHERE NOT EXISTS (SELECT 1 
				  FROM CZ_FI_CARD_STATE A
				  WHERE A.CD_COMPANY = @P_CD_COMPANY
				  AND A.DT_MONTH = @P_DT_MONTH
				  AND A.NO_CARD = XL.[카드번호])


GO