USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_FI_CARD_STATE_S]    Script Date: 2016-12-28 오후 3:03:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_FI_CARD_STATE_S]
(
	@P_CD_COMPANY			NVARCHAR(7),
	@P_DT_MONTH				NVARCHAR(8),
	@P_NO_CARD_MULTI		NVARCHAR(MAX)
)
AS  

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT CS.DT_MONTH,
	   CS.TP_CARD,
	   CS.NO_CARD,
	   CS.CD_DEPT,
	   CS.NM_FILE
FROM CZ_FI_CARD_STATE CS
WHERE CS.CD_COMPANY = @P_CD_COMPANY
AND CS.DT_MONTH = @P_DT_MONTH
AND REPLACE(CS.NO_CARD, '-', '') IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_NO_CARD_MULTI))

GO