USE [NEOE]
GO

/****** Object:  Table [NEOE].[CZ_FI_CARD_STATE]    Script Date: 2021-11-04 오후 4:53:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [NEOE].[CZ_FI_CARD_STATE](
	[CD_COMPANY] [nvarchar](7) NOT NULL,
	[DT_MONTH] [nvarchar](8) NOT NULL,
	[NO_CARD] [nvarchar](20) NOT NULL,
	[TP_CARD] [nvarchar](10) NULL,
	[CD_DEPT] [nvarchar](50) NULL,
	[NM_FILE] [nvarchar](100) NULL,
	[ID_INSERT] [nvarchar](15) NULL,
	[DTS_INSERT] [nvarchar](14) NULL,
	[ID_UPDATE] [nvarchar](15) NULL,
	[DTS_UPDATE] [nvarchar](14) NULL,
 CONSTRAINT [PK_CZ_FI_CARD_STATE_MONTH] PRIMARY KEY CLUSTERED 
(
	[CD_COMPANY] ASC,
	[DT_MONTH] ASC,
	[NO_CARD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


