USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_MA_WORKFLOWH_S_2]    Script Date: 2018-08-13 오전 9:45:20 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- 매입문의등록
ALTER PROCEDURE [NEOE].[SP_CZ_MA_WORKFLOWH_S_2]  
(
	@P_CD_COMPANY			NVARCHAR(7),
	@P_ID_USER				NVARCHAR(15),
	@P_NO_KEY				NVARCHAR(20),
	@P_CD_SALEORG			NVARCHAR(7),		
	@P_CD_SALEGRP			NVARCHAR(500)
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

CREATE TABLE #CZ_MA_WORKFLOWH
(
	CD_COMPANY  NVARCHAR(7),
	NO_KEY      NVARCHAR(20),
    ID_SALES    NVARCHAR(15),
    NM_SALES    NVARCHAR(40),
    ID_TYPIST   NVARCHAR(15),
    DC_RMK      NVARCHAR(MAX),
    DTS_INSERT  NVARCHAR(14)
)

CREATE NONCLUSTERED INDEX CZ_MA_WORKFLOWH ON #CZ_MA_WORKFLOWH (CD_COMPANY, NO_KEY)

CREATE TABLE #CZ_SA_QTNH
(
	CD_COMPANY  NVARCHAR(7),
	NO_FILE     NVARCHAR(20),
    CD_PARTNER  NVARCHAR(20),
    NO_IMO      NVARCHAR(10),
    YN_CLOSE    NVARCHAR(1)
)

CREATE NONCLUSTERED INDEX CZ_SA_QTNH ON #CZ_SA_QTNH (CD_COMPANY, NO_FILE)

CREATE TABLE #CZ_RPA_WORK_QUEUE
(
	CD_COMPANY  NVARCHAR(7),
	NO_FILE     NVARCHAR(20),
    SEQ         INT,
    YN_DONE     NVARCHAR(1),
    ST_RPA      NVARCHAR(4),
    DC_RPA      NVARCHAR(500)
)

CREATE NONCLUSTERED INDEX CZ_RPA_WORK_QUEUE ON #CZ_RPA_WORK_QUEUE (CD_COMPANY, NO_FILE)

INSERT INTO #CZ_MA_WORKFLOWH
(
    CD_COMPANY,
    NO_KEY,
    ID_SALES,
    NM_SALES,
    ID_TYPIST,
    DC_RMK,
    DTS_INSERT
)
SELECT WH.CD_COMPANY,
       WH.NO_KEY,
       WH.ID_SALES,
       MU.NM_USER AS NM_SALES,
       WH.ID_TYPIST,
       WH.DC_RMK,
       WH.DTS_INSERT
FROM CZ_MA_WORKFLOWH WH
LEFT JOIN MA_USER MU ON MU.CD_COMPANY = WH.CD_COMPANY AND MU.ID_USER = WH.ID_SALES
WHERE WH.TP_STEP = '02'
AND (WH.YN_DONE IS NULL OR WH.YN_DONE = 'N')
AND (ISNULL(@P_CD_COMPANY, '') = '' OR WH.CD_COMPANY = @P_CD_COMPANY)
-- AND (ISNULL(@P_ID_USER, '') = '' OR (CASE WHEN WH.CD_COMPANY = 'K100' AND
-- 											   WH.NO_KEY LIKE 'FB%' AND
-- 											   EXISTS (SELECT 1 
-- 											           FROM CZ_MA_WORKFLOWL
-- 											           WHERE CD_COMPANY = WH.CD_COMPANY
-- 											           AND NO_KEY = WH.NO_KEY
-- 											           AND TP_STEP = '01'
-- 											           AND (ISNULL(YN_PARSING, 'N') = 'Y')) AND
-- 											   NOT EXISTS(SELECT 1 
-- 											              FROM CZ_MA_WORKFLOWL
-- 											              WHERE CD_COMPANY = WH.CD_COMPANY
-- 											              AND NO_KEY = WH.NO_KEY
-- 											              AND TP_STEP = '01'
-- 											              AND (NM_FILE LIKE '현대웹%' OR 
-- 															   NM_FILE LIKE '정아%')) THEN WH.ID_SALES 
-- 																					  ELSE WH.ID_TYPIST END) = @P_ID_USER)
 AND (ISNULL(@P_ID_USER, '') = '' OR WH.ID_TYPIST = @P_ID_USER)
 AND (ISNULL(@P_NO_KEY, '') = '' OR WH.NO_KEY = @P_NO_KEY)
 AND (ISNULL(@P_CD_SALEGRP, '') = '' OR MU.CD_SALEGRP IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SALEGRP)))
 AND (ISNULL(@P_CD_SALEORG, '') = '' OR EXISTS (SELECT 1
 											    FROM MA_SALEGRP
 											    WHERE CD_COMPANY = MU.CD_COMPANY
 											    AND CD_SALEGRP = MU.CD_SALEGRP
 											    AND CD_SALEORG = @P_CD_SALEORG))

INSERT INTO #CZ_SA_QTNH
(
    CD_COMPANY,
    NO_FILE,
    CD_PARTNER,
    NO_IMO,
    YN_CLOSE
)
SELECT QH.CD_COMPANY,
       QH.NO_FILE,
       QH.CD_PARTNER,
       QH.NO_IMO,
       QH.YN_CLOSE
FROM CZ_SA_QTNH QH
WHERE (ISNULL(@P_CD_COMPANY, '') = '' OR QH.CD_COMPANY = @P_CD_COMPANY)
AND EXISTS (SELECT 1 
            FROM #CZ_MA_WORKFLOWH WH
            WHERE WH.CD_COMPANY = QH.CD_COMPANY
            AND WH.NO_KEY = QH.NO_FILE)

INSERT INTO #CZ_RPA_WORK_QUEUE
SELECT A.CD_COMPANY,
       A.NO_FILE,
       A.SEQ,
	   A.YN_DONE,
       (CASE WHEN A.YN_DONE = 'Y' THEN '완료'
			 WHEN A.YN_DONE = 'N' AND ISNULL(A.DTS_DONE, '') <> '' THEN '실패'
			 WHEN A.YN_READ = 'Y' THEN '실행중'
			 WHEN A.YN_READ = 'N' THEN '실행대상'
			 ELSE NULL END) AS ST_RPA,
       (SELECT QL.DC_JOB 
		FROM (SELECT QL.DC_JOB,
			  	     ISNULL(ROW_NUMBER() OVER(PARTITION BY QL.CD_COMPANY, QL.SEQ ORDER BY QL.DTS_INSERT DESC), 1) AS IDX
			  FROM CZ_RPA_WORK_QUEUE_LOG QL
			  WHERE QL.CD_COMPANY = A.CD_COMPANY
			  AND QL.SEQ = A.SEQ
			  AND QL.CD_JOB NOT IN ('READ', 'END', 'QUEUE', '시작', 'PlateNo 찾기-성공', 'PlateNo 찾기-실패', 'PlateNo 찾기-성공1')
			  AND QL.DC_JOB NOT LIKE '담당자 아이디%') QL
		WHERE QL.IDX = 1) AS DC_RPA
FROM (SELECT WQ.CD_COMPANY,
	  	     WQ.NO_FILE,
	  	     WQ.SEQ,
             WQ.YN_READ,
	  	     WQ.YN_DONE,
			 WQ.DTS_DONE,
	  	     ROW_NUMBER() OVER(PARTITION BY WQ.CD_COMPANY, WQ.NO_FILE ORDER BY WQ.YN_DONE DESC, WQ.DTS_INSERT DESC) AS IDX
	     FROM CZ_RPA_WORK_QUEUE WQ
	 WHERE CD_RPA LIKE '%INQ'
	 AND CD_RPA <> 'SHIPSERV_INQ') A
WHERE A.IDX = 1
AND EXISTS (SELECT 1
            FROM #CZ_MA_WORKFLOWH WH
            WHERE WH.CD_COMPANY = A.CD_COMPANY
            AND WH.NO_KEY = A.NO_FILE)

SELECT 'N' AS S,
	   WH.CD_COMPANY,
	   (CASE WHEN EXISTS (SELECT 1
		                  FROM CZ_MA_WORKFLOWL WL
		                  WHERE WL.CD_COMPANY = WH.CD_COMPANY
                          AND WL.NO_KEY = WH.NO_KEY
                          AND TP_STEP = '01'
		                  AND YN_PARSING = 'Y'
		                  AND (YN_INCLUDED IS NULL OR YN_INCLUDED = 'N')) THEN 'Y' ELSE NULL END) AS YN_PARSING,
       (CASE WHEN EXISTS (SELECT 1 
                          FROM CZ_PU_QTNH QH
                          WHERE QH.CD_COMPANY = WH.CD_COMPANY
                          AND QH.NO_FILE = WH.NO_KEY) THEN '002'
			 WHEN QH.NO_FILE IS NOT NULL THEN '003'
			 ELSE NULL END) AS TP_STATE,
	   WH.NO_KEY,
	   WH.DTS_INSERT,
	   WH.ID_SALES,
	   WH.NM_SALES,
	    (SELECT NM_USER 
         FROM MA_USER MU 
         WHERE MU.CD_COMPANY = WH.CD_COMPANY 
         AND MU.ID_USER = WH.ID_TYPIST) AS NM_TYPIST,
	   (SELECT MP.LN_PARTNER 
        FROM MA_PARTNER MP 
        WHERE MP.CD_COMPANY = QH.CD_COMPANY 
        AND MP.CD_PARTNER = QH.CD_PARTNER) AS NM_PARTNER,
	   (SELECT MH.NM_VESSEL 
        FROM CZ_MA_HULL MH 
        WHERE MH.NO_IMO = QH.NO_IMO) AS NM_VESSEL,
	   WH.DC_RMK,
	   WQ.SEQ,
	   WQ.YN_DONE,
       WQ.ST_RPA,
       WQ.DC_RPA
FROM #CZ_MA_WORKFLOWH WH
LEFT JOIN #CZ_SA_QTNH QH ON QH.CD_COMPANY = WH.CD_COMPANY AND QH.NO_FILE = WH.NO_KEY
LEFT JOIN #CZ_RPA_WORK_QUEUE WQ ON WQ.CD_COMPANY = WH.CD_COMPANY AND WQ.NO_FILE = WH.NO_KEY
WHERE 1=1
AND (QH.YN_CLOSE IS NULL OR QH.YN_CLOSE = 'N')
ORDER BY WH.DTS_INSERT, WH.NO_KEY
OPTION(RECOMPILE)

DROP TABLE #CZ_SA_QTNH
DROP TABLE #CZ_MA_WORKFLOWH
DROP TABLE #CZ_RPA_WORK_QUEUE

GO

