USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_MA_WORKFLOWH_S_15]    Script Date: 2018-08-13 오전 9:48:09 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



-- 협조전완결
ALTER PROCEDURE [NEOE].[SP_CZ_MA_WORKFLOWH_S_15]  
(
	@P_CD_COMPANY			NVARCHAR(7),
	@P_ID_USER				NVARCHAR(15),
	@P_NO_KEY				NVARCHAR(20),
	@P_CD_SALEORG			NVARCHAR(7),		
	@P_CD_SALEGRP			NVARCHAR(500)
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

DECLARE @V_NM_TYPE1 NVARCHAR(20)

SELECT @V_NM_TYPE1 = NM_SYSDEF
FROM MA_CODEDTL
WHERE CD_COMPANY = @P_CD_COMPANY
AND CD_FIELD = 'CZ_SA00021'
AND CD_SYSDEF = '001'

SELECT GH.CD_COMPANY,
	   GH.NO_GIR AS NO_KEY,
	   GH.DT_GIR,
	   GD.DT_COMPLETE,
	   @V_NM_TYPE1 AS NM_TYPE1,
	   MD.NM_SYSDEF AS NM_TYPE2,
	   MD1.NM_SYSDEF AS NM_TYPE3,
	   GD.YN_PACKING,
	   MD2.NM_SYSDEF AS NM_STA_GIR,
	   ME.NM_KOR AS NM_EMP_GIR,
	   MP.LN_PARTNER AS NM_PARTNER,
	   MH.NM_VESSEL,
	   MP1.LN_PARTNER AS NM_GIR_PARTNER,
	   MD3.NM_SYSDEF AS NM_RETURN, 
	   MC.NM_COMPANY,
	   GD.DC_RMK
FROM (SELECT GH.CD_COMPANY, GH.NO_GIR,
			 GH.NO_EMP,
			 GH.STA_GIR,
			 GH.YN_RETURN,
			 GH.DT_GIR,
			 GH.CD_PARTNER 
	  FROM SA_GIRH GH
	  WHERE GH.YN_RETURN = 'N' 
	  AND (GH.STA_GIR IS NULL OR GH.STA_GIR IN ('', 'O', 'R', 'D'))
	  AND (ISNULL(@P_CD_COMPANY, '') = '' OR GH.CD_COMPANY = @P_CD_COMPANY)
	  AND (ISNULL(@P_NO_KEY, '') = '' OR GH.NO_GIR = @P_NO_KEY)
	  AND (ISNULL(@P_ID_USER, '') = '' OR GH.NO_EMP = @P_ID_USER)
	  AND EXISTS (SELECT 1 
				  FROM SA_GIRL GL
				  JOIN CZ_SA_QTNL QL ON QL.CD_COMPANY = GL.CD_COMPANY AND QL.NO_FILE = GL.NO_SO AND QL.NO_LINE = GL.SEQ_SO
				  WHERE GL.CD_COMPANY = GH.CD_COMPANY
				  AND GL.NO_GIR = GH.NO_GIR
				  AND (ISNULL(@P_CD_SALEGRP, '') = '' OR GL.CD_SALEGRP IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SALEGRP)))
				  AND (ISNULL(@P_CD_SALEORG, '') = '' OR EXISTS (SELECT 1 
																 FROM MA_SALEGRP SG
																 WHERE SG.CD_COMPANY = GL.CD_COMPANY
																 AND SG.CD_SALEGRP = GL.CD_SALEGRP
																 AND SG.CD_SALEORG = @P_CD_SALEORG)))
	  UNION ALL
	  SELECT GH.CD_COMPANY, GH.NO_GIR,
			 GH.NO_EMP,
			 GH.STA_GIR,
			 GH.YN_RETURN,
			 GH.DT_GIR,
			 GH.CD_PARTNER
	  FROM SA_GIRH GH
	  WHERE GH.YN_RETURN = 'Y'
	  AND (ISNULL(@P_CD_COMPANY, '') = '' OR GH.CD_COMPANY = @P_CD_COMPANY)
	  AND (ISNULL(@P_NO_KEY, '') = '' OR GH.NO_GIR = @P_NO_KEY)
	  AND (ISNULL(@P_ID_USER, '') = '' OR GH.NO_EMP = @P_ID_USER)
	  AND EXISTS (SELECT 1 
	  			  FROM SA_GIRL GL
				  JOIN CZ_SA_QTNL QL ON QL.CD_COMPANY = GL.CD_COMPANY AND QL.NO_FILE = GL.NO_SO_MGMT AND QL.NO_LINE = GL.NO_SOLINE_MGMT
	  			  WHERE GL.CD_COMPANY = GH.CD_COMPANY
	  			  AND GL.NO_GIR = GH.NO_GIR
	  			  AND GL.QT_GIR > GL.QT_GI
				  AND (ISNULL(@P_CD_SALEGRP, '') = '' OR GL.CD_SALEGRP IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SALEGRP)))
				  AND (ISNULL(@P_CD_SALEORG, '') = '' OR EXISTS (SELECT 1 
																 FROM MA_SALEGRP SG
																 WHERE SG.CD_COMPANY = GL.CD_COMPANY
																 AND SG.CD_SALEGRP = GL.CD_SALEGRP
																 AND SG.CD_SALEORG = @P_CD_SALEORG)))) GH
LEFT JOIN CZ_SA_GIRH_WORK_DETAIL GD ON GD.CD_COMPANY = GH.CD_COMPANY AND GD.NO_GIR = GH.NO_GIR
LEFT JOIN MA_EMP ME ON ME.CD_COMPANY = GH.CD_COMPANY AND ME.NO_EMP = GH.NO_EMP
LEFT JOIN CZ_MA_HULL MH ON MH.NO_IMO = GD.NO_IMO
LEFT JOIN MA_PARTNER MP ON MP.CD_COMPANY = GH.CD_COMPANY AND MP.CD_PARTNER = GH.CD_PARTNER
LEFT JOIN CZ_MA_DELIVERY MP1 ON MP1.CD_COMPANY = GD.CD_COMPANY AND MP1.CD_PARTNER = GD.CD_DELIVERY_TO
LEFT JOIN MA_COMPANY MC ON MC.CD_COMPANY = GH.CD_COMPANY
LEFT JOIN MA_CODEDTL MD ON MD.CD_COMPANY = GD.CD_COMPANY AND MD.CD_FIELD = 'CZ_SA00006' AND MD.CD_SYSDEF = GD.CD_MAIN_CATEGORY
LEFT JOIN MA_CODEDTL MD1 ON MD1.CD_COMPANY = @P_CD_COMPANY AND MD1.CD_FIELD = MD.CD_FLAG1 AND MD1.CD_SYSDEF = GD.CD_SUB_CATEGORY
LEFT JOIN MA_CODEDTL MD2 ON MD2.CD_COMPANY = @P_CD_COMPANY AND MD2.CD_FIELD = 'CZ_SA00030' AND MD2.CD_SYSDEF = GH.STA_GIR
LEFT JOIN MA_CODEDTL MD3 ON MD3.CD_COMPANY = @P_CD_COMPANY AND MD3.CD_FIELD = 'PU_C000027' AND MD3.CD_SYSDEF = GH.YN_RETURN

GO

