USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_MA_WORKFLOWH_S_11]    Script Date: 2018-08-13 오전 9:47:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



-- 수발주통보서
ALTER PROCEDURE [NEOE].[SP_CZ_MA_WORKFLOWH_S_11]  
(
	@P_CD_COMPANY			NVARCHAR(7),
	@P_ID_USER				NVARCHAR(15),
	@P_NO_KEY				NVARCHAR(20),
	@P_CD_SALEORG			NVARCHAR(7),		
	@P_CD_SALEGRP			NVARCHAR(500)
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT WH.CD_COMPANY,
	   WH.NO_KEY,
	   (SELECT TOP 1 NM_FILE 
	    FROM CZ_MA_WORKFLOWL 
		WHERE CD_COMPANY = WH.CD_COMPANY 
		AND TP_STEP = '11' 
		AND NO_KEY = WH.NO_KEY 
		ORDER BY DTS_INSERT DESC) AS NM_FILE,
	   (SELECT TOP 1 NM_FILE_REAL 
	    FROM CZ_MA_WORKFLOWL 
		WHERE CD_COMPANY = WH.CD_COMPANY 
		AND TP_STEP = '11' 
		AND NO_KEY = WH.NO_KEY 
		ORDER BY DTS_INSERT DESC) AS NM_FILE_REAL,
	   MP.LN_PARTNER AS NM_PARTNER,
	   MH.NM_VESSEL,
	   SH.DT_CONTRACT,
	   WH.ID_SALES,
	   MU.NM_USER AS NM_SALES,
	   MU1.NM_USER AS NM_PUR,
	   SH.AM_SO,
	   SH.AM_SO_CHARGE,
	   SH.AM_PO,
	   SH.AM_PO_CHARGE,
	   SH.PROFIT,
	   SH.PROFIT_ALL,
	   (CASE WHEN SH.AM_SO IS NULL OR SH.AM_SO = 0 THEN NULL 
												   ELSE ROUND((ISNULL(SH.PROFIT, 0) / ISNULL(SH.AM_SO, 0)) * 100, 2) END) AS RT_PROFIT, 
	   (CASE WHEN SH.AM_SO_ALL IS NULL OR SH.AM_SO_ALL = 0 THEN NULL 
														   ELSE ROUND((ISNULL(SH.PROFIT_ALL, 0) / ISNULL(SH.AM_SO_ALL, 0)) * 100, 2) END) AS RT_PROFIT_ALL, 
	   WH.DC_RMK
FROM CZ_MA_WORKFLOWH WH
LEFT JOIN (SELECT SH.CD_COMPANY, SH.NO_SO,
				  SH.CD_PARTNER,
				  SH.NO_IMO,
				  SH.DT_CONTRACT,
				  SL.AM_SO,
				  SL.AM_SO_CHARGE,
				  SL.AM_SO_ALL,
				  (ISNULL(PL.AM_PO, 0) + ISNULL(SL.AM_STOCK, 0)) AS AM_PO,
				  PL.AM_PO_CHARGE,
				  (ISNULL(SL.AM_SO, 0) - (ISNULL(PL.AM_PO, 0) + ISNULL(SL.AM_STOCK, 0))) AS PROFIT,
				  (ISNULL(SL.AM_SO_ALL, 0) - (ISNULL(PL.AM_PO_ALL, 0) + ISNULL(SL.AM_STOCK, 0))) AS PROFIT_ALL,
				  SH.YN_CLOSE 
		   FROM SA_SOH SH
		   LEFT JOIN (SELECT SL.CD_COMPANY, SL.NO_SO, 
		   	  	             SUM(CASE WHEN SL.CD_ITEM NOT LIKE 'SD%' THEN SL.AM_KR_S ELSE 0 END) AS AM_SO,
		   	  	             SUM(CASE WHEN SL.CD_ITEM LIKE 'SD%' THEN SL.AM_KR_S ELSE 0 END) AS AM_SO_CHARGE,
		   	  	             SUM(SL.AM_KR_S) AS AM_SO_ALL,
		   				     SUM(ISNULL(SB.UM_KR, 0) * ISNULL(SB.QT_STOCK, 0)) AS AM_STOCK
		   	          FROM SA_SOL SL
		   	          LEFT JOIN CZ_SA_QTNL QL ON QL.CD_COMPANY = SL.CD_COMPANY AND QL.NO_FILE = SL.NO_SO AND QL.NO_LINE = SL.SEQ_SO
		   		      LEFT JOIN CZ_SA_STOCK_BOOK SB ON SB.CD_COMPANY = SL.CD_COMPANY AND SB.NO_FILE = SL.NO_SO AND SB.NO_LINE = SL.SEQ_SO 
		   	          GROUP BY SL.CD_COMPANY, SL.NO_SO) SL
		   ON SL.CD_COMPANY = SH.CD_COMPANY AND SL.NO_SO = SH.NO_SO
		   LEFT JOIN (SELECT PL.CD_COMPANY, PL.CD_PJT,
		   		   	         SUM(CASE WHEN PL.CD_ITEM NOT LIKE 'SD%' THEN PL.AM ELSE 0 END) AS AM_PO,
		   		   	         SUM(CASE WHEN PL.CD_ITEM LIKE 'SD%' THEN PL.AM ELSE 0 END) AS AM_PO_CHARGE,
		   				     SUM(PL.AM) AS AM_PO_ALL
		   		      FROM PU_POL PL
		   		      LEFT JOIN CZ_SA_QTNL QL ON QL.CD_COMPANY = PL.CD_COMPANY AND QL.NO_FILE = PL.NO_SO AND QL.NO_LINE = PL.NO_SOLINE
		   		      GROUP BY PL.CD_COMPANY, PL.CD_PJT) PL
		   ON PL.CD_COMPANY = SH.CD_COMPANY AND PL.CD_PJT = SH.NO_SO) SH 
ON SH.CD_COMPANY = WH.CD_COMPANY AND SH.NO_SO = WH.NO_KEY
LEFT JOIN MA_USER MU ON MU.CD_COMPANY = WH.CD_COMPANY AND MU.ID_USER = WH.ID_SALES
LEFT JOIN MA_USER MU1 ON MU1.CD_COMPANY = WH.CD_COMPANY AND MU1.ID_USER = WH.ID_PUR
LEFT JOIN MA_PARTNER MP ON MP.CD_COMPANY = SH.CD_COMPANY AND MP.CD_PARTNER = SH.CD_PARTNER
LEFT JOIN CZ_MA_HULL MH ON MH.NO_IMO = SH.NO_IMO
WHERE WH.TP_STEP = '11'
AND (WH.YN_DONE IS NULL OR WH.YN_DONE = 'N')
AND (SH.YN_CLOSE IS NULL OR SH.YN_CLOSE = 'N')
AND (ISNULL(@P_CD_COMPANY, '') = '' OR WH.CD_COMPANY = @P_CD_COMPANY)
AND (ISNULL(@P_ID_USER, '') = '' OR WH.ID_PUR = @P_ID_USER)
AND (ISNULL(@P_NO_KEY, '') = '' OR WH.NO_KEY = @P_NO_KEY)
AND (ISNULL(@P_CD_SALEGRP, '') = '' OR MU.CD_SALEGRP IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SALEGRP)))
AND (ISNULL(@P_CD_SALEORG, '') = '' OR EXISTS (SELECT 1 
											   FROM MA_SALEGRP
											   WHERE CD_COMPANY = MU.CD_COMPANY
											   AND CD_SALEGRP = MU.CD_SALEGRP
											   AND CD_SALEORG = @P_CD_SALEORG))

GO

