USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_MA_WORKFLOWH_S_1]    Script Date: 2018-08-13 오전 9:45:12 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

--고객문의등록
ALTER PROCEDURE [NEOE].[SP_CZ_MA_WORKFLOWH_S_1]  
(
	@P_CD_COMPANY			NVARCHAR(7),
	@P_ID_USER				NVARCHAR(15),
	@P_NO_KEY				NVARCHAR(20),
	@P_CD_SALEORG			NVARCHAR(7),		
	@P_CD_SALEGRP			NVARCHAR(500)
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT 'N' AS S,
	   WH.CD_COMPANY,
	   (SELECT MAX(YN_PARSING) 
		FROM CZ_MA_WORKFLOWL
		WHERE CD_COMPANY = WH.CD_COMPANY
		AND NO_KEY = WH.NO_KEY
		AND TP_STEP = '01'
		AND YN_PARSING = 'Y'
		AND (YN_INCLUDED IS NULL OR YN_INCLUDED = 'N')) AS YN_PARSING,
	   WH.NO_KEY,
	   WH.DTS_INSERT,
	   WH.ID_SALES,
	   MU.NM_USER AS NM_SALES,
	   MU1.NM_USER AS NM_TYPIST,
	   WH.DC_RMK
FROM CZ_MA_WORKFLOWH WH
LEFT JOIN MA_USER MU ON MU.CD_COMPANY = WH.CD_COMPANY AND MU.ID_USER = WH.ID_SALES
LEFT JOIN MA_USER MU1 ON MU1.CD_COMPANY = WH.CD_COMPANY AND MU1.ID_USER = WH.ID_TYPIST
WHERE WH.TP_STEP = '01'
AND (WH.YN_DONE IS NULL OR WH.YN_DONE = 'N')
AND NOT EXISTS (SELECT 1 
			    FROM CZ_SA_QTNH
			    WHERE CD_COMPANY = WH.CD_COMPANY
			    AND NO_FILE = WH.NO_KEY
			    AND YN_CLOSE = 'Y')
AND (ISNULL(@P_CD_COMPANY, '') = '' OR WH.CD_COMPANY = @P_CD_COMPANY)
AND (ISNULL(@P_ID_USER, '') = '' OR WH.ID_SALES = @P_ID_USER)
AND (ISNULL(@P_NO_KEY, '') = '' OR WH.NO_KEY = @P_NO_KEY)
AND (ISNULL(@P_CD_SALEGRP, '') = '' OR MU.CD_SALEGRP IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SALEGRP)))
AND (ISNULL(@P_CD_SALEORG, '') = '' OR EXISTS (SELECT 1 
											   FROM MA_SALEGRP
											   WHERE CD_COMPANY = MU.CD_COMPANY
											   AND CD_SALEGRP = MU.CD_SALEGRP
											   AND CD_SALEORG = @P_CD_SALEORG))
ORDER BY WH.DTS_INSERT, WH.NO_KEY

GO

