USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_PR_ID_NO_HISTORYH_S]    Script Date: 2019-03-26 오전 11:26:39 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_PR_ID_NO_HISTORYH_S]
(
    @P_CD_COMPANY   NVARCHAR(7),
    @P_NO_WO        NVARCHAR(20),
    @P_NO_ID        NVARCHAR(10),
    @P_NO_ID_OLD    NVARCHAR(10)
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT WD.NO_WO,
       WD.SEQ_WO,
       WD.NO_ID,
       WD.NO_ID_OLD,
       MI.CD_ITEM,
       MI.NM_ITEM,
       MI.STND_ITEM,
       MI.NO_DESIGN,
       ISNULL(NULLIF(WD.NO_HEAT, ''), WO.TXT_USERDEF1) AS NO_HEAT,
       (CASE WHEN EXISTS (SELECT 1 
						  FROM CZ_PR_WO_INSP WI
						  WHERE WI.CD_COMPANY = WD.CD_COMPANY
						  AND WI.NO_WO = WD.NO_WO
						  AND WI.SEQ_WO = WD.SEQ_WO
						  AND WI.NO_INSP = -1) THEN 'Y' ELSE 'N' END) AS YN_BAD
FROM CZ_PR_WO_REQ_D WD
LEFT JOIN PR_WO WO ON WO.CD_COMPANY = WD.CD_COMPANY AND WO.NO_WO = WD.NO_WO
LEFT JOIN MA_PITEM MI ON MI.CD_COMPANY = WD.CD_COMPANY AND MI.CD_ITEM = WD.CD_ITEM
WHERE WD.CD_COMPANY = @P_CD_COMPANY
AND (ISNULL(@P_NO_WO, '') = '' OR WD.NO_WO = @P_NO_WO)
AND (ISNULL(@P_NO_ID, '') = '' OR WD.NO_ID = @P_NO_ID)
AND (ISNULL(@P_NO_ID_OLD, '') = '' OR WD.NO_ID_OLD = @P_NO_ID_OLD)
AND EXISTS (SELECT 1 
			FROM PR_WO WO
			WHERE WO.CD_COMPANY = WD.CD_COMPANY
			AND WO.NO_WO = WD.NO_WO)

GO

