USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_PR_ID_NO_HISTORYL2_S]    Script Date: 2019-03-26 오전 11:26:39 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_PR_ID_NO_HISTORYL2_S]
(
    @P_CD_COMPANY   NVARCHAR(7),
    @P_NO_WO        NVARCHAR(20),
	@P_SEQ_WO		NUMERIC(5, 0),
	@P_NO_LINE		NUMERIC(5, 0),
	@P_CD_OP		NVARCHAR(4)
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT WK.NO_WO,
	   @P_SEQ_WO AS SEQ_WO,
	   @P_NO_LINE AS NO_LINE,
	   WK.NO_WORK,
	   WK.NO_EMP,
	   ME.NM_KOR,
	   WK.DT_WORK,
	   WK.QT_WORK,
	   WK.CD_EQUIP,
	   EQ.NM_EQUIP,
	   WK.DTS_INSERT
FROM PR_WORK WK
LEFT JOIN MA_EMP ME ON ME.CD_COMPANY = WK.CD_COMPANY AND ME.NO_EMP= WK.NO_EMP
LEFT JOIN PR_EQUIP EQ ON EQ.CD_COMPANY = WK.CD_COMPANY AND EQ.CD_PLANT = WK.CD_PLANT AND EQ.CD_EQUIP = WK.CD_EQUIP
WHERE WK.CD_COMPANY = @P_CD_COMPANY
AND WK.NO_WO = @P_NO_WO
AND WK.CD_OP = @P_CD_OP

GO