USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[UP_SA_BIZAREA_OF_PLANT_S]    Script Date: 2019-11-04 오전 10:40:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[UP_SA_BIZAREA_OF_PLANT_S]
(
    @P_CD_COMPANY       NVARCHAR(7),
    @P_MULTI_CD_PLANT   NVARCHAR(4000)
)
AS

BEGIN
    SELECT  CD_BIZAREA
    FROM    MA_PLANT
    WHERE   CD_COMPANY = @P_CD_COMPANY
    AND     CD_PLANT IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_MULTI_CD_PLANT))
    GROUP BY CD_BIZAREA
END
GO

