USE [NEOE]
GO

/****** Object:  Table [NEOE].[CZ_SA_COMMISSIONL]    Script Date: 2020-03-25 오전 9:24:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [NEOE].[CZ_SA_COMMISSIONL](
	[CD_COMPANY] [nvarchar](7) NOT NULL,
	[NO_COMMISSION] [nvarchar](20) NOT NULL,
	[SEQ] [numeric](5, 0) NOT NULL,
	[NM_PTR] [nvarchar](30) NULL,
	[NM_EMAIL] [nvarchar](80) NULL,
	[NM_DEPT] [nvarchar](100) NULL,
	[NM_DUTY_RESP] [nvarchar](100) NULL,
	[DC_RMK] [nvarchar](max) NULL,
	[ID_INSERT] [nvarchar](15) NULL,
	[DTS_INSERT] [nvarchar](14) NULL,
	[ID_UPDATE] [nvarchar](15) NULL,
	[DTS_UPDATE] [nvarchar](14) NULL,
 CONSTRAINT [PK_CZ_SA_COMMISSIONL] PRIMARY KEY CLUSTERED 
(
	[CD_COMPANY] ASC,
	[NO_COMMISSION] ASC,
	[SEQ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


