USE [NEOE]
GO

/****** Object:  Table [NEOE].[CZ_PR_SA_SOL_PR_WO_MAPPING]    Script Date: 2021-04-27 오후 1:07:21 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [NEOE].[CZ_PR_SA_SOL_PR_WO_MAPPING](
	[CD_COMPANY] [nvarchar](7) NOT NULL,
	[CD_PLANT] [nvarchar](7) NOT NULL,
	[NO_SO] [nvarchar](20) NOT NULL,
	[NO_LINE] [numeric](5, 0) NOT NULL,
	[NO_WO] [nvarchar](20) NOT NULL,
	[CD_ITEM] [nvarchar](20) NOT NULL,
	[QT_APPLY] [numeric](17, 4) NOT NULL,
	[ID_INSERT] [nvarchar](15) NULL,
	[DTS_INSERT] [nvarchar](14) NULL,
	[ID_UPDATE] [nvarchar](15) NULL,
	[DTS_UPDATE] [nvarchar](14) NULL,
 CONSTRAINT [PK_CZ_PR_SA_SOL_PR_WO_MAPPING] PRIMARY KEY CLUSTERED 
(
	[CD_COMPANY] ASC,
	[CD_PLANT] ASC,
	[NO_SO] ASC,
	[NO_LINE] ASC,
	[NO_WO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [NEOE].[CZ_PR_SA_SOL_PR_WO_MAPPING] ADD  CONSTRAINT [DF_CZ_PR_SA_SOL_PR_WO_MAPPING_NO_LINE]  DEFAULT ((0)) FOR [NO_LINE]
GO

ALTER TABLE [NEOE].[CZ_PR_SA_SOL_PR_WO_MAPPING] ADD  CONSTRAINT [DF_CZ_PR_SA_SOL_PR_WO_MAPPING_QT_APPLY]  DEFAULT ((0)) FOR [QT_APPLY]
GO

