USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_MA_PARTNER_DEPOSIT_XML]    Script Date: 2016-11-30 오후 5:22:08 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




ALTER PROCEDURE [NEOE].[SP_CZ_MA_PARTNER_DEPOSIT_XML] 
(
	@P_XML			XML, 
	@P_ID_USER		NVARCHAR(10), 
    @DOC			INT = NULL
) 
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

EXEC SP_XML_PREPAREDOCUMENT @DOC OUTPUT, @P_XML 

-- ================================================== DELETE
DELETE A 
FROM CZ_MA_PARTNER_DEPOSIT A 
JOIN OPENXML (@DOC, '/XML/D', 2) 
        WITH (CD_COMPANY	NVARCHAR(7),
			  CD_PARTNER	NVARCHAR(20),
			  NO_DEPOSIT	NVARCHAR(40)) B 
 ON A.CD_COMPANY = B.CD_COMPANY
AND A.CD_PARTNER = B.CD_PARTNER
AND A.NO_DEPOSIT = B.NO_DEPOSIT

DELETE A 
FROM MA_PARTNER_DEPOSIT A 
JOIN OPENXML (@DOC, '/XML/D', 2) 
        WITH (CD_COMPANY	NVARCHAR(7),
			  CD_PARTNER	NVARCHAR(20),
			  NO_DEPOSIT	NVARCHAR(40)) B 
 ON A.CD_COMPANY = B.CD_COMPANY
AND A.CD_PARTNER = B.CD_PARTNER
AND A.NO_DEPOSIT = B.NO_DEPOSIT

UPDATE A
SET A.NO_DEPOSIT = NULL,
    A.NM_DEPOSIT = NULL,
    A.CD_BANK = NULL,
	A.DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE()),
	A.ID_UPDATE = @P_ID_USER
FROM MA_PARTNER A 
JOIN OPENXML (@DOC, '/XML/D', 2) 
        WITH (CD_COMPANY	NVARCHAR(7),
			  CD_PARTNER	NVARCHAR(20),
			  NO_DEPOSIT	NVARCHAR(40)) B 
 ON A.CD_COMPANY = B.CD_COMPANY
AND A.CD_PARTNER = B.CD_PARTNER
AND A.NO_DEPOSIT = B.NO_DEPOSIT
-- ================================================== INSERT
INSERT INTO CZ_MA_PARTNER_DEPOSIT 
(
	CD_COMPANY,
	CD_PARTNER,
	NO_DEPOSIT,
	YN_USE,
	CD_DEPOSIT,
	CD_BANK,
	NM_BANK,
	CD_BANK_NATION,
	NO_SORT,
	NO_SWIFT,
	NM_DEPOSIT,
	DC_DEPOSIT_TEL,
	CD_DEPOSIT_NATION,
	DC_DEPOSIT_ADDRESS,
	NO_BANK_BIC,
	DC_RMK,
	ID_INSERT,
	DTS_INSERT
)
SELECT CD_COMPANY,
	   CD_PARTNER,
	   NO_DEPOSIT,
	   YN_USE,
	   CD_DEPOSIT,
	   CD_BANK,
	   NM_BANK,
	   CD_BANK_NATION,
	   NO_SORT,
	   NO_SWIFT,
	   NM_DEPOSIT,
	   DC_DEPOSIT_TEL,
	   CD_DEPOSIT_NATION,
	   DC_DEPOSIT_ADDRESS,
	   NO_BANK_BIC,
	   DC_RMK,
       @P_ID_USER, 
       NEOE.SF_SYSDATE(GETDATE()) 
FROM OPENXML (@DOC, '/XML/I', 2) 
        WITH (CD_COMPANY			NVARCHAR(7),
			  CD_PARTNER			NVARCHAR(20),
			  NO_DEPOSIT			NVARCHAR(40),
			  YN_USE				NVARCHAR(1),
			  CD_DEPOSIT			NVARCHAR(3),
			  CD_BANK				NVARCHAR(3),
			  NM_BANK				NVARCHAR(200),
			  CD_BANK_NATION		NVARCHAR(3),
			  NO_SORT				NVARCHAR(20),
			  NO_SWIFT				NVARCHAR(20),
			  NM_DEPOSIT			NVARCHAR(100),
			  DC_DEPOSIT_TEL		NVARCHAR(50),
			  CD_DEPOSIT_NATION		NVARCHAR(3),
			  DC_DEPOSIT_ADDRESS	NVARCHAR(200),
			  NO_BANK_BIC			NVARCHAR(20),
			  DC_RMK				NVARCHAR(50))
			  
INSERT INTO MA_PARTNER_DEPOSIT
(
	CD_COMPANY,
	CD_PARTNER,
	NO_DEPOSIT,
	USE_YN,
	CD_BANK,
	CD_DEPOSIT,
	NM_DEPOSIT,
	HELP_USE,
	DC_RMK,
	ID_INSERT,
	DT_INSERT
)
SELECT CD_COMPANY,
	   CD_PARTNER,		
	   NO_DEPOSIT,		
	   YN_USE,
	   CD_BANK,
	   CD_DEPOSIT,
	   NM_DEPOSIT,
	   'Y',
	   DC_RMK,
       @P_ID_USER, 
       NEOE.SF_SYSDATE(GETDATE()) 
FROM OPENXML (@DOC, '/XML/I', 2) 
        WITH (CD_COMPANY		NVARCHAR(7),
			  CD_PARTNER		NVARCHAR(20),
			  NO_DEPOSIT		NVARCHAR(40),
			  YN_USE			NVARCHAR(1),
			  CD_BANK			NVARCHAR(3),
			  CD_DEPOSIT		NVARCHAR(3),
			  NM_DEPOSIT		NVARCHAR(100),
			  DC_RMK			NVARCHAR(50))

UPDATE PD
SET PD.CD_DEPOSITNO = PD2.CD_DEPOSITNO 
FROM MA_PARTNER_DEPOSIT PD
JOIN (SELECT CD_COMPANY, CD_PARTNER
	  FROM OPENXML (@DOC, '/XML/I', 2) 
			  WITH (CD_COMPANY		NVARCHAR(7),
			        CD_PARTNER		NVARCHAR(20))
	  GROUP BY CD_COMPANY, CD_PARTNER) PD1
ON  PD1.CD_COMPANY = PD.CD_COMPANY AND PD1.CD_PARTNER = PD.CD_PARTNER
JOIN (SELECT CD_COMPANY, CD_PARTNER, NO_DEPOSIT,
			 ROW_NUMBER() OVER (PARTITION BY CD_COMPANY, CD_PARTNER ORDER BY CD_DEPOSITNO) AS CD_DEPOSITNO
	  FROM MA_PARTNER_DEPOSIT) PD2
ON PD2.CD_COMPANY = PD.CD_COMPANY AND PD2.CD_PARTNER = PD.CD_PARTNER AND PD2.NO_DEPOSIT = PD.NO_DEPOSIT

UPDATE A
SET A.NO_DEPOSIT = B.NO_DEPOSIT,
	A.NM_DEPOSIT = B.NM_DEPOSIT,
	A.CD_BANK = B.CD_BANK,
	A.DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE()),
	A.ID_UPDATE = @P_ID_USER
FROM MA_PARTNER A 
JOIN OPENXML (@DOC, '/XML/I', 2) 
        WITH (CD_COMPANY	NVARCHAR(7),
			  CD_PARTNER	NVARCHAR(20),
			  YN_USE	    NVARCHAR(1),
			  NO_DEPOSIT	NVARCHAR(40),
			  CD_BANK	    NVARCHAR(3),
			  NM_DEPOSIT	NVARCHAR(100)) B 
 ON A.CD_COMPANY = B.CD_COMPANY
AND A.CD_PARTNER = B.CD_PARTNER
AND B.YN_USE = 'Y'
-- ================================================== UPDATE    
UPDATE A 
   SET A.YN_USE = B.YN_USE,
	   A.CD_DEPOSIT = B.CD_DEPOSIT,
	   A.CD_BANK = B.CD_BANK,
	   A.NM_BANK = B.NM_BANK,
	   A.CD_BANK_NATION = B.CD_BANK_NATION,
	   A.NO_SORT = B.NO_SORT,
	   A.NO_SWIFT = B.NO_SWIFT,
	   A.NM_DEPOSIT = B.NM_DEPOSIT,
	   A.DC_DEPOSIT_TEL = B.DC_DEPOSIT_TEL,
	   A.CD_DEPOSIT_NATION = B.CD_DEPOSIT_NATION,
	   A.DC_DEPOSIT_ADDRESS = B.DC_DEPOSIT_ADDRESS,
	   A.NO_BANK_BIC = B.NO_BANK_BIC,
	   A.DC_RMK = B.DC_RMK,
	   A.ID_UPDATE = @P_ID_USER, 
	   A.DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE())
FROM CZ_MA_PARTNER_DEPOSIT A 
JOIN OPENXML (@DOC, '/XML/U', 2) 
        WITH (CD_COMPANY			NVARCHAR(7),
			  CD_PARTNER			NVARCHAR(20),
			  NO_DEPOSIT			NVARCHAR(40),
			  YN_USE				NVARCHAR(1),
			  CD_DEPOSIT			NVARCHAR(3),
			  CD_BANK				NVARCHAR(3),
			  NM_BANK				NVARCHAR(200),
			  CD_BANK_NATION		NVARCHAR(3),
			  NO_SORT				NVARCHAR(20),
			  NO_SWIFT				NVARCHAR(20),
			  NM_DEPOSIT			NVARCHAR(100),
			  DC_DEPOSIT_TEL		NVARCHAR(50),
			  CD_DEPOSIT_NATION		NVARCHAR(3),
			  DC_DEPOSIT_ADDRESS	NVARCHAR(200),
			  NO_BANK_BIC			NVARCHAR(20),
			  DC_RMK				NVARCHAR(50)) B 
 ON A.CD_COMPANY = B.CD_COMPANY
AND A.CD_PARTNER = B.CD_PARTNER
AND A.NO_DEPOSIT = B.NO_DEPOSIT

UPDATE A 
   SET A.USE_YN = B.YN_USE,
	 A.CD_BANK = B.CD_BANK,
	 A.CD_DEPOSIT = B.CD_DEPOSIT,
	 A.NM_DEPOSIT = B.NM_DEPOSIT,
	 A.DC_RMK = B.DC_RMK,
	 A.ID_UPDATE = @P_ID_USER, 
	 A.DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE())
FROM MA_PARTNER_DEPOSIT A 
JOIN OPENXML (@DOC, '/XML/U', 2) 
        WITH (CD_COMPANY	NVARCHAR(7),
			  CD_PARTNER	NVARCHAR(20),
			  NO_DEPOSIT	NVARCHAR(40),
			  YN_USE		NVARCHAR(1),
			  CD_BANK		NVARCHAR(3),
			  CD_DEPOSIT	NVARCHAR(3),
			  NM_DEPOSIT	NVARCHAR(100),
			  DC_RMK		NVARCHAR(50)) B 
 ON A.CD_COMPANY = B.CD_COMPANY
AND A.CD_PARTNER = B.CD_PARTNER
AND A.NO_DEPOSIT = B.NO_DEPOSIT

UPDATE A
   SET A.NO_DEPOSIT = B.NO_DEPOSIT,
	   A.NM_DEPOSIT = B.NM_DEPOSIT,
	   A.CD_BANK = B.CD_BANK,
	   A.DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE()),
	   A.ID_UPDATE = @P_ID_USER
FROM MA_PARTNER A 
JOIN OPENXML (@DOC, '/XML/U', 2) 
        WITH (CD_COMPANY	NVARCHAR(7),
			  CD_PARTNER	NVARCHAR(20),
			  YN_USE	    NVARCHAR(1),
			  NO_DEPOSIT	NVARCHAR(40),
			  CD_BANK	    NVARCHAR(3),
			  NM_DEPOSIT	NVARCHAR(100)) B 
 ON A.CD_COMPANY = B.CD_COMPANY
AND A.CD_PARTNER = B.CD_PARTNER
AND B.YN_USE = 'Y'

EXEC SP_XML_REMOVEDOCUMENT @DOC 

GO

