USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_MA_PARTNER_DEPOSIT_S]    Script Date: 2016-07-04 오후 5:27:11 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_MA_PARTNER_DEPOSIT_SUB_S]
(
	@P_CD_COMPANY  NVARCHAR(7),
	@P_CD_PARTNER  NVARCHAR(20)
) 
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT 'N' AS S,
	   PD.CD_PARTNER,
	   PD.NO_DEPOSIT,
	   PD.YN_USE,
	   PD.CD_DEPOSIT,
	   PD.CD_BANK,
	   PD.NM_BANK,
	   PD.CD_BANK_NATION,
	   PD.NO_SORT,
	   PD.NO_SWIFT,
	   PD.NM_DEPOSIT,
	   PD.DC_DEPOSIT_TEL,
	   PD.CD_DEPOSIT_NATION,
	   PD.DC_DEPOSIT_ADDRESS,
	   PD.NO_BANK_BIC,
	   PD.DC_RMK,
	   PD.ID_INSERT,
	   MU.NM_USER AS NM_INSERT,
	   PD.DTS_INSERT,
	   PD.ID_UPDATE,
	   MU1.NM_USER AS NM_UPDATE,
	   PD.DTS_UPDATE
FROM CZ_MA_PARTNER_DEPOSIT PD
LEFT JOIN MA_USER MU ON MU.CD_COMPANY = PD.CD_COMPANY AND MU.ID_USER = PD.ID_INSERT
LEFT JOIN MA_USER MU1 ON MU1.CD_COMPANY = PD.CD_COMPANY AND MU1.ID_USER = PD.ID_UPDATE
WHERE PD.CD_COMPANY = @P_CD_COMPANY
AND PD.CD_PARTNER = @P_CD_PARTNER

GO