USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_MA_TARIFF_CBM_H_S]    Script Date: 2016-06-27 오후 5:01:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_MA_TARIFF_CBM_H_S]          
(  
	@P_CD_COMPANY		NVARCHAR(7),
	@P_CD_PARTNER		NVARCHAR(20)
)  
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT TC.CD_PARTNER,
	   MP.LN_PARTNER,
	   TC.YN_USE
FROM CZ_MA_TARIFF_CBM_H TC
LEFT JOIN MA_PARTNER MP ON MP.CD_COMPANY = TC.CD_COMPANY AND MP.CD_PARTNER = TC.CD_PARTNER
WHERE TC.CD_COMPANY = @P_CD_COMPANY
AND (ISNULL(@P_CD_PARTNER, '') = '' OR TC.CD_PARTNER = @P_CD_PARTNER)

GO