USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_MA_TARIFF_CBM_L_S]    Script Date: 2016-06-27 오후 5:01:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_MA_TARIFF_CBM_L_S]          
(  
	@P_CD_COMPANY		NVARCHAR(7),
	@P_CD_PARTNER		NVARCHAR(20)
)  
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT 'N' AS S,
	   TC.CD_PARTNER,
	   TC.SIZE,
	   TC.SEQ,
	   TC.UM,
	   TC.DT_START,
	   TC.DT_END
FROM CZ_MA_TARIFF_CBM_L TC
WHERE TC.CD_COMPANY = @P_CD_COMPANY
AND TC.CD_PARTNER = @P_CD_PARTNER

GO