USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_MA_TARIFF_DHL_STD_H_XML]    Script Date: 2016-06-28 오후 1:28:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




ALTER PROCEDURE [NEOE].[SP_CZ_MA_TARIFF_DHL_STD_H_XML] 
(
	@P_XML			XML, 
	@P_ID_USER		NVARCHAR(10), 
    @DOC			INT = NULL
) 
AS 

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

EXEC SP_XML_PREPAREDOCUMENT @DOC OUTPUT, @P_XML 

-- ================================================== DELETE
DELETE A 
FROM CZ_MA_TARIFF_DHL_STD_H A 
JOIN OPENXML (@DOC, '/XML/D', 2) 
        WITH (CD_COMPANY	NVARCHAR(7),
			  DT_YEAR	    NVARCHAR(4),
			  TP_TARIFF		NVARCHAR(4)) B 
ON A.CD_COMPANY = B.CD_COMPANY 
AND A.DT_YEAR = B.DT_YEAR
AND A.TP_TARIFF = B.TP_TARIFF
-- ================================================== INSERT
INSERT INTO CZ_MA_TARIFF_DHL_STD_H 
(
	CD_COMPANY,
	DT_YEAR,
	TP_TARIFF,
	ID_INSERT,
	DTS_INSERT
)
SELECT CD_COMPANY,
	   DT_YEAR,
	   TP_TARIFF,
       @P_ID_USER, 
       NEOE.SF_SYSDATE(GETDATE()) 
  FROM OPENXML (@DOC, '/XML/I', 2) 
          WITH (CD_COMPANY		NVARCHAR(7),
				DT_YEAR			NVARCHAR(4),
				TP_TARIFF		NVARCHAR(4))

EXEC SP_XML_REMOVEDOCUMENT @DOC 

GO