USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_LN_CURR_QUARTER]    Script Date: 2019-06-07 오후 4:50:14 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




ALTER PROCEDURE [NEOE].[SP_CZ_LN_CURR_QUARTER]
(
	@P_QUARTER		NVARCHAR(8),
	@P_EC_R_K		NVARCHAR(50),
	@P_EC_R_US		NVARCHAR(50)
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

IF EXISTS (SELECT 1 
		   FROM CZ_LN_CURR_QUARTER
		   WHERE QUARTER = @P_QUARTER)
BEGIN
	UPDATE CZ_LN_CURR_QUARTER
	SET EC_R_K = ISNULL(@P_EC_R_K, EC_R_K),
		EC_R_US = ISNULL(@P_EC_R_US, EC_R_US),
		DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE())
	WHERE QUARTER = @P_QUARTER
END
ELSE
BEGIN
	INSERT INTO CZ_LN_CURR_QUARTER
	(
		QUARTER,
		EC_R_K,
		EC_R_US,
		DTS_INSERT
	)
	VALUES
	(
		@P_QUARTER,
		@P_EC_R_K,
		@P_EC_R_US,
		NEOE.SF_SYSDATE(GETDATE())
	)
END

GO

