USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_GIR_CHARGE_XML]    Script Date: 2016-06-28 오후 1:28:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_SA_GIR_CHARGE_XML] 
(
	@P_XML			XML, 
	@P_ID_USER		NVARCHAR(10), 
    @DOC			INT = NULL
) 
AS 

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

EXEC SP_XML_PREPAREDOCUMENT @DOC OUTPUT, @P_XML 

-- ================================================== DELETE
DELETE A 
FROM CZ_SA_GIRH_CHARGE A 
JOIN OPENXML (@DOC, '/XML/D', 2) 
        WITH (CD_COMPANY	NVARCHAR(7),
			  NO_GIR		NVARCHAR(20),
			  CD_ITEM		NVARCHAR(20)) B 
ON A.CD_COMPANY = B.CD_COMPANY 
AND A.NO_GIR = B.NO_GIR
AND A.CD_ITEM = B.CD_ITEM
-- ================================================== INSERT
INSERT INTO CZ_SA_GIRH_CHARGE 
(
	CD_COMPANY,
	NO_GIR,
	CD_ITEM,
	AM_EX_CHARGE,
	DC_RMK,
	ID_INSERT,
	DTS_INSERT
)
SELECT CD_COMPANY,
	   NO_GIR,
	   CD_ITEM,
	   AM_EX_CHARGE,
	   DC_RMK,
       @P_ID_USER, 
       NEOE.SF_SYSDATE(GETDATE()) 
  FROM OPENXML (@DOC, '/XML/I', 2) 
          WITH (CD_COMPANY		NVARCHAR(7), 
			    NO_GIR			NVARCHAR(20),
				CD_ITEM			NVARCHAR(20),
				AM_EX_CHARGE    NUMERIC(17, 4),
				DC_RMK			NVARCHAR(MAX))
-- ================================================== UPDATE
UPDATE A
SET A.AM_EX_CHARGE = B.AM_EX_CHARGE,
	A.DC_RMK = B.DC_RMK,
	A.ID_UPDATE = @P_ID_USER,
	A.DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE())
FROM CZ_SA_GIRH_CHARGE A
JOIN OPENXML (@DOC, '/XML/U', 2) 
        WITH (CD_COMPANY		NVARCHAR(7), 
			  NO_GIR			NVARCHAR(20),
			  CD_ITEM			NVARCHAR(20),
			  AM_EX_CHARGE		NUMERIC(17, 4),
			  DC_RMK			NVARCHAR(MAX)) B
ON B.CD_COMPANY = A.CD_COMPANY 
AND B.NO_GIR = A.NO_GIR
AND B.CD_ITEM = A.CD_ITEM

EXEC SP_XML_REMOVEDOCUMENT @DOC 

GO