USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_GIR_CHARGE_S]    Script Date: 2015-06-02 오후 7:34:10 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
            
ALTER PROCEDURE [NEOE].[SP_CZ_SA_GIR_CHARGE_S]
(
    @P_CD_COMPANY    NVARCHAR(7),
    @P_NO_GIR        NVARCHAR(20)
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT GC.NO_GIR,
       GC.CD_ITEM,
       GC.AM_EX_CHARGE,
       GC.DC_RMK
FROM CZ_SA_GIRH_CHARGE GC
WHERE GC.CD_COMPANY = @P_CD_COMPANY
AND GC.NO_GIR = @P_NO_GIR

GO