USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_PR_MARKING_REG_GIR_D]    Script Date: 2017-01-05 오후 5:48:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_PR_MARKING_REG_GIR_D]          
(
	@P_CD_COMPANY		NVARCHAR(7),
	@P_NO_GIR			NVARCHAR(20),
	@P_SEQ_GIR			NUMERIC(5, 0),
	@P_NO_SEQ			NUMERIC(5, 0),
	@P_CD_MATL			NVARCHAR(20)
)
AS
   
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

DELETE A
FROM CZ_SA_GIRL_MARKING A
JOIN (SELECT CD_COMPANY, NO_GIR, SEQ_GIR, NO_SEQ, CD_MATL, NO_LINE,
		  	 ROW_NUMBER() OVER (PARTITION BY NO_GIR, SEQ_GIR ORDER BY NO_LINE DESC) AS IDX
	  FROM CZ_SA_GIRL_MARKING) B
ON B.CD_COMPANY = A.CD_COMPANY AND B.NO_GIR = A.NO_GIR AND B.SEQ_GIR = A.SEQ_GIR AND B.NO_SEQ = A.NO_SEQ AND B.CD_MATL = A.CD_MATL AND B.NO_LINE = A.NO_LINE AND B.IDX = 1
WHERE A.CD_COMPANY = @P_CD_COMPANY
AND A.NO_GIR = @P_NO_GIR
AND A.SEQ_GIR = @P_SEQ_GIR
AND A.NO_SEQ = @P_NO_SEQ
AND A.CD_MATL = @P_CD_MATL

GO