USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_PR_MARKING_REG_GIR_I]    Script Date: 2017-01-05 오후 5:48:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_PR_MARKING_REG_GIR_I]          
(
	@P_CD_COMPANY		NVARCHAR(7),
	@P_NO_GIR			NVARCHAR(20),
	@P_SEQ_GIR			NUMERIC(5, 0),
	@P_NO_SEQ			NUMERIC(5, 0),
	@P_CD_MATL			NVARCHAR(20),
	@P_DC_TEXT			NVARCHAR(500),
	@P_ID_INSERT		NVARCHAR(15)
)
AS
   
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

INSERT INTO CZ_SA_GIRL_MARKING
(
	CD_COMPANY,
	NO_GIR,
	SEQ_GIR,
	NO_SEQ,
	CD_MATL,
	NO_LINE,
	DC_TEXT,
	DTS_INSERT,
	ID_INSERT
)
SELECT @P_CD_COMPANY,
	   @P_NO_GIR,
	   @P_SEQ_GIR,
	   @P_NO_SEQ,
	   @P_CD_MATL,
	   ((SELECT ISNULL(MAX(NO_LINE), 0) 
		 FROM CZ_SA_GIRL_MARKING MK
		 WHERE MK.CD_COMPANY = @P_CD_COMPANY
		 AND MK.NO_GIR = @P_NO_GIR
		 AND MK.SEQ_GIR = @P_SEQ_GIR
		 AND MK.NO_SEQ = @P_NO_SEQ
		 AND MK.CD_MATL = @P_CD_MATL) + 1),
	   @P_DC_TEXT,
	   NEOE.SF_SYSDATE(GETDATE()),
	   @P_ID_INSERT

GO