USE [NEOE]
GO

/****** Object:  Table [NEOE].[CZ_PU_ADPAYMENT_BILL_H]    Script Date: 2015-08-05 오후 5:16:22 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [NEOE].[CZ_PU_ADPAYMENT_BILL_H](
	[CD_COMPANY] [nvarchar](7) NOT NULL,
	[NO_BILLS] [nvarchar](20) NOT NULL,
	[CD_PARTNER] [nvarchar](20) NULL,
	[DT_BILLS] [nchar](8) NOT NULL,
	[TP_BUSI] [nvarchar](3) NULL,
	[AM_BILLS] [numeric](17, 4) NOT NULL,
	[ST_BILL] [nchar](1) NULL,
	[CD_BILLTGRP] [nvarchar](7) NULL,
	[NO_EMP] [nvarchar](10) NULL,
	[DC_RMK] [nvarchar](100) NULL,
	[AM_IV] [numeric](17, 4) NOT NULL,
	[CD_TP] [nvarchar](6) NULL,
	[CD_DOCU] [nvarchar](3) NULL,
	[ID_INSERT] [nvarchar](15) NULL,
	[DTS_INSERT] [nvarchar](14) NULL,
	[ID_UPDATE] [nvarchar](15) NULL,
	[DTS_UPDATE] [nvarchar](14) NULL,
 CONSTRAINT [PK_CZ_PU_ADPAYMENT_BILL_H] PRIMARY KEY CLUSTERED 
(
	[CD_COMPANY] ASC,
	[NO_BILLS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [NEOE].[CZ_PU_ADPAYMENT_BILL_H] ADD  DEFAULT ('00000000') FOR [DT_BILLS]
GO

ALTER TABLE [NEOE].[CZ_PU_ADPAYMENT_BILL_H] ADD  DEFAULT ((0)) FOR [AM_BILLS]
GO

ALTER TABLE [NEOE].[CZ_PU_ADPAYMENT_BILL_H] ADD  DEFAULT ((0)) FOR [AM_IV]
GO