USE [NEOE]
GO

/****** Object:  Table [NEOE].[CZ_PU_ADPAYMENT_BILL_L]    Script Date: 2016-03-11 오후 2:24:12 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [NEOE].[CZ_PU_ADPAYMENT_BILL_L](
	[CD_COMPANY] [nvarchar](7) NOT NULL,
	[NO_BILLS] [nvarchar](20) NOT NULL,
	[NO_LINE] [numeric](3, 0) NOT NULL,
	[CD_PJT] [nvarchar](20) NULL,
	[NO_DOCU] [nvarchar](20) NULL,
	[NO_DOLINE] [numeric](5, 0) NULL,
	[AM_TARGET] [numeric](17, 4) NOT NULL,
	[AM_BILLS] [numeric](17, 4) NOT NULL,
	[NO_ADPAY] [nvarchar](20) NULL,
	[CD_EXCH] [nvarchar](3) NULL,
	[RT_EXCH] [numeric](11, 4) NULL,
	[AM_TARGET_EX] [numeric](17, 4) NULL,
	[AM_BILLS_EX] [numeric](17, 4) NULL,
	[NO_MGMT] [nvarchar](40) NULL,
	[ID_INSERT] [nvarchar](15) NULL,
	[DTS_INSERT] [nvarchar](14) NULL,
	[ID_UPDATE] [nvarchar](15) NULL,
	[DTS_UPDATE] [nvarchar](14) NULL,
 CONSTRAINT [PK_CZ_PU_ADPAYMENT_BILL_L] PRIMARY KEY CLUSTERED 
(
	[CD_COMPANY] ASC,
	[NO_BILLS] ASC,
	[NO_LINE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [NEOE].[CZ_PU_ADPAYMENT_BILL_L] ADD  CONSTRAINT [DF__CZ_PU_ADP__AM_TA__4B058EAA]  DEFAULT ((0)) FOR [AM_TARGET]
GO

ALTER TABLE [NEOE].[CZ_PU_ADPAYMENT_BILL_L] ADD  CONSTRAINT [DF__CZ_PU_ADP__AM_BI__4BF9B2E3]  DEFAULT ((0)) FOR [AM_BILLS]
GO


