USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_GIR_AUTO_SUBMIT_S]    Script Date: 2016-07-13 오후 2:40:04 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

	 
ALTER PROCEDURE [NEOE].[SP_CZ_SA_GIR_AUTO_SUBMIT_S]
(
	@P_CD_COMPANY    NVARCHAR(7),
	@P_CD_PARTNER	 NVARCHAR(20),
	@P_NO_IMO		 NVARCHAR(10),
	@P_NO_SO		 NVARCHAR(20)
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

DECLARE @V_ERRMSG   VARCHAR(255)   -- ERROR 메시지

IF EXISTS (SELECT 1 
		   FROM SA_SOH
		   WHERE CD_COMPANY = @P_CD_COMPANY
		   AND NO_SO = @P_NO_SO
		   AND STA_SO <> 'R')
BEGIN
	SELECT @V_ERRMSG = '수주 확정 건만 자동 제출 할 수 있습니다.'
	GOTO ERROR
END

IF EXISTS (SELECT 1 
		   FROM SA_GIRL
		   WHERE CD_COMPANY = @P_CD_COMPANY
		   AND NO_SO = @P_NO_SO)
BEGIN
	SELECT @V_ERRMSG = '물류업무협조전 미작성 건만 자동 제출 할 수 있습니다.'
	GOTO ERROR
END

IF EXISTS (SELECT 1 
		   FROM CZ_SA_STOCK_BOOK SB
		   WHERE SB.CD_COMPANY = @P_CD_COMPANY
		   AND SB.NO_FILE = @P_NO_SO
		   AND ISNULL(SB.QT_STOCK, 0) <> ISNULL(SB.QT_BOOK, 0))
BEGIN
	SELECT @V_ERRMSG = '재고 사용건은 전량 재고 예약 되어야 자동 제출 할 수 있습니다.'
	GOTO ERROR
END

IF NOT EXISTS (SELECT SL.CD_COMPANY, SL.NO_SO, 
			   		  SL.QT_SO,
			   		  ISNULL(SB.QT_STOCK, 0) AS QT_STOCK
			   FROM SA_SOL SL
			   LEFT JOIN CZ_SA_STOCK_BOOK SB ON SB.CD_COMPANY = SL.CD_COMPANY AND SB.NO_FILE = SL.NO_SO AND SB.NO_LINE = SL.SEQ_SO
			   WHERE SL.CD_COMPANY = @P_CD_COMPANY
			   AND SL.NO_SO = @P_NO_SO
			   AND SL.QT_SO <> ISNULL(SB.QT_STOCK, 0))
BEGIN
	SELECT @V_ERRMSG = '전량 재고 사용건은 자동 제출 할 수 없습니다.'
	GOTO ERROR
END

IF NOT EXISTS (SELECT SH.CD_COMPANY, SH.NO_SO, PL.NO_PO, PL.NO_LINE, 
			   		  ISNULL(PL.QT_PO, 0) AS QT_PO, 
			   		  ISNULL(IL.QT_IO, 0) AS QT_IN
			   FROM SA_SOH SH
			   LEFT JOIN PU_POL PL ON PL.CD_COMPANY = SH.CD_COMPANY AND PL.NO_SO = SH.NO_SO
			   LEFT JOIN (SELECT CD_COMPANY, NO_PSO_MGMT, NO_PSOLINE_MGMT, 
								 SUM(QT_IO) AS QT_IO 
			   			  FROM MM_QTIO
			   			  GROUP BY CD_COMPANY, NO_PSO_MGMT, NO_PSOLINE_MGMT) IL 
			   ON IL.CD_COMPANY = PL.CD_COMPANY AND IL.NO_PSO_MGMT = PL.NO_PO AND IL.NO_PSOLINE_MGMT = PL.NO_LINE
			   WHERE SH.CD_COMPANY = @P_CD_COMPANY
			   AND SH.NO_SO = @P_NO_SO 
			   AND (ISNULL(PL.QT_PO, 0) = 0 OR ISNULL(PL.QT_PO, 0) <> ISNULL(IL.QT_IO, 0)))
BEGIN
	SELECT @V_ERRMSG = '전량 입고 건은 자동 제출 할 수 없습니다.'
	GOTO ERROR
END

BEGIN TRY

EXEC SP_CZ_SA_GIRH_SUB_S 
@P_CD_COMPANY,
NULL,
NULL,
NULL,
NULL,
@P_CD_PARTNER,
NULL,
NULL,
@P_NO_SO,
@P_NO_IMO,
NULL,
NULL,
NULL,
'N'

EXEC SP_CZ_SA_GIRL_SUB_S
@P_CD_COMPANY,
@P_NO_SO,
NULL,  
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
'N',
'001'

END TRY
BEGIN CATCH
	SELECT @V_ERRMSG = ERROR_MESSAGE()
	GOTO ERROR
END CATCH

RETURN

ERROR: 
RAISERROR(@V_ERRMSG, 16, 1)

GO

