USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_CRM_CHART_K02_S]    Script Date: 2017-07-13 오후 3:13:12 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER PROCEDURE [NEOE].[SP_CZ_SA_CRM_CHART_K02_S]
(
	@P_CD_COMPANY		NVARCHAR(7),
	@P_DT_FROM			NVARCHAR(8),
	@P_DT_TO			NVARCHAR(8),
	@P_CD_PARTNER		NVARCHAR(1000),
	@P_NO_IMO			NVARCHAR(10),
	@P_NO_EMP			NVARCHAR(10),
	@P_CD_ITEMGRP		NVARCHAR(20),
	@P_CD_SALEORG		NVARCHAR(7),
	@P_CD_SALEGRP		NVARCHAR(1000),
	@P_LENGTH			NUMERIC(1)
) 
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT QH.NO_FILE, QH.DT_INQ, QL.NM_ITEM_PARTNER,
	   MAX(QH.CD_PARTNER) AS CD_PARTNER,
	   MAX(MP.LN_PARTNER) AS LN_PARTNER,
	   MAX(MH.NM_VESSEL) AS NM_VESSEL,
	   MAX(CASE WHEN PL.CD_SUPPLIER IS NULL AND SB.QT_STOCK > 0 THEN 'STOCK' ELSE PL.CD_SUPPLIER END) AS CD_SUPPLIER,
	   MAX(CASE WHEN PL.NM_SUPPLIER IS NULL AND SB.QT_STOCK > 0 THEN 'STOCK' ELSE PL.NM_SUPPLIER END) AS NM_SUPPLIER,
	   MAX(REPLACE(REPLACE(REPLACE(REPLACE(QL.NM_ITEM_PARTNER, ' ', ''), CHAR(9), ''), CHAR(10), ''), CHAR(13), '')) AS NM_KEY,
	   MAX(QL.CD_ITEM) AS CD_ITEM,
	   MAX(MI.NM_ITEM) AS NM_ITEM,
	   MAX(QL.UM_KR_S) AS UM_QTN,
	   MAX(SL.UM_KR_S) AS UM_SO,
	   MAX(SB.UM_KR) AS UM_STOCK,
	   MAX(PL.UM_PO) AS UM_PO
FROM CZ_SA_QTNH QH
LEFT JOIN MA_SALEGRP SG ON SG.CD_COMPANY = QH.CD_COMPANY AND SG.CD_SALEGRP = QH.CD_SALEGRP
LEFT JOIN MA_PARTNER MP ON MP.CD_COMPANY = QH.CD_COMPANY AND MP.CD_PARTNER = QH.CD_PARTNER
LEFT JOIN CZ_MA_HULL MH ON MH.NO_IMO = QH.NO_IMO
LEFT JOIN CZ_SA_QTNL QL ON QL.CD_COMPANY = QH.CD_COMPANY AND QL.NO_FILE = QH.NO_FILE
LEFT JOIN SA_SOL SL ON SL.CD_COMPANY = QL.CD_COMPANY AND SL.NO_SO = QL.NO_FILE AND SL.SEQ_SO = QL.NO_LINE
LEFT JOIN CZ_SA_STOCK_BOOK SB ON SB.CD_COMPANY = QL.CD_COMPANY AND SB.NO_FILE = QL.NO_FILE AND SB.NO_LINE = QL.NO_LINE
LEFT JOIN (SELECT PL.CD_COMPANY, PL.NO_SO, PL.NO_SOLINE,
				  MAX(PH.CD_PARTNER) AS CD_SUPPLIER,
				  MAX(MP.LN_PARTNER) AS NM_SUPPLIER,
				  MAX(PL.UM) AS UM_PO 
		   FROM PU_POL PL
		   LEFT JOIN PU_POH PH ON PH.CD_COMPANY = PL.CD_COMPANY AND PH.NO_PO = PL.NO_PO
		   LEFT JOIN MA_PARTNER MP ON MP.CD_COMPANY = PH.CD_COMPANY AND MP.CD_PARTNER = PH.CD_PARTNER
		   GROUP BY PL.CD_COMPANY, PL.NO_SO, PL.NO_SOLINE) PL
ON PL.CD_COMPANY = SL.CD_COMPANY AND PL.NO_SO = SL.NO_SO AND PL.NO_SOLINE = SL.SEQ_SO
LEFT JOIN MA_PITEM MI ON MI.CD_COMPANY = QL.CD_COMPANY AND MI.CD_ITEM = QL.CD_ITEM
WHERE QH.CD_COMPANY = @P_CD_COMPANY
AND QH.DT_INQ BETWEEN @P_DT_FROM AND @P_DT_TO
AND ISNULL(QL.NM_ITEM_PARTNER, '') <> ''
AND (ISNULL(@P_CD_PARTNER, '') = '' OR QH.CD_PARTNER IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_PARTNER)))
AND (ISNULL(@P_NO_IMO, '') = '' OR QH.NO_IMO = @P_NO_IMO)
AND (ISNULL(@P_NO_EMP, '') = '' OR QH.NO_EMP = @P_NO_EMP)
AND (ISNULL(@P_CD_SALEORG, '') = '' OR SG.CD_SALEORG = @P_CD_SALEORG)
AND (ISNULL(@P_CD_SALEGRP, '') = '' OR QH.CD_SALEGRP IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SALEGRP)))
GROUP BY QH.NO_FILE, QH.DT_INQ, QL.NM_ITEM_PARTNER

GO