USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_CRM_CHART_P09_S]    Script Date: 2017-07-13 오후 3:13:12 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER PROCEDURE [NEOE].[SP_CZ_SA_CRM_CHART_P09_S]
(
	@P_CD_COMPANY		NVARCHAR(7),
	@P_DT_FROM			NVARCHAR(8),
	@P_DT_TO			NVARCHAR(8),
	@P_CD_PARTNER		NVARCHAR(1000),
	@P_NO_IMO			NVARCHAR(10),
	@P_NO_EMP			NVARCHAR(10),
	@P_CD_ITEMGRP		NVARCHAR(20),
	@P_CD_SALEORG		NVARCHAR(7),
	@P_CD_SALEGRP		NVARCHAR(1000),
	@P_LENGTH			NUMERIC(1)
) 
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

IF @P_CD_COMPANY = 'S100'
BEGIN
	WITH A AS
	(
		SELECT CD_COMPANY, 
			   NO_FILE,
			   CD_PARTNER 
		FROM CZ_PU_QTNH
		WHERE CD_COMPANY = 'S100'
		AND CD_PARTNER <> '10493'
		UNION ALL
		SELECT QH.CD_COMPANY,
			   QH.NO_FILE,
			   QH1.CD_PARTNER 
		FROM CZ_SA_QTNH QH
		JOIN CZ_PU_QTNH QH1 ON QH1.CD_COMPANY = QH.CD_COMPANY AND QH1.NO_FILE = QH.NO_FILE
		WHERE QH.CD_COMPANY = 'K100'
		AND EXISTS (SELECT 1 
				    FROM CZ_SA_QTNH
				    WHERE CD_COMPANY = 'S100' 
					AND (NO_FILE = QH.NO_FILE OR NO_FILE = QH.NO_REF))
		GROUP BY QH.CD_COMPANY, QH.NO_FILE, QH1.CD_PARTNER
	),
	B AS
	(
		SELECT QH.CD_COMPANY, QH.NO_FILE, QH.CD_PARTNER,
		  	   SUM(QL.AM_KR) AS AM_INQ,
			   NULL AS QT_QTN,
			   NULL AS AM_QTN,
		  	   NULL AS QT_PO,
		  	   NULL AS AM_PO,
		  	   NULL AS QT_SO,
			   NULL AS AM_SO,
		  	   NULL AS QT_STOCK,
		  	   NULL AS AM_STOCK,
		  	   NULL AS LT
		  FROM A QH
		  JOIN CZ_PU_QTNL QL ON QL.CD_COMPANY = QH.CD_COMPANY AND QL.NO_FILE = QH.NO_FILE AND QL.CD_PARTNER = QH.CD_PARTNER
		  WHERE (QL.YN_CHOICE IS NULL OR QL.YN_CHOICE = 'N')
		  AND ISNULL(QL.CD_ITEM, '') NOT LIKE 'SD%'
		  AND (ISNULL(@P_CD_ITEMGRP, '') = '' OR EXISTS (SELECT 1 
														 FROM CZ_SA_QTNL QL1
														 WHERE QL1.CD_COMPANY = QL.CD_COMPANY
														 AND QL1.NO_FILE = QL.NO_FILE
														 AND QL1.NO_LINE = QL.NO_LINE 
														 AND QL1.GRP_ITEM = @P_CD_ITEMGRP))
		  AND EXISTS (SELECT 1 
					  FROM CZ_SA_QTNH QH1
					  LEFT JOIN MA_SALEGRP SG ON SG.CD_COMPANY = QH1.CD_COMPANY AND SG.CD_SALEGRP = QH1.CD_SALEGRP
					  WHERE QH1.CD_COMPANY = QH.CD_COMPANY
					  AND QH1.NO_FILE = QH.NO_FILE
					  AND QH1.DT_INQ BETWEEN @P_DT_FROM AND @P_DT_TO
					  AND (ISNULL(@P_CD_PARTNER, '') = '' OR QH1.CD_PARTNER IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_PARTNER)))
			          AND (ISNULL(@P_NO_IMO, '') = '' OR QH1.NO_IMO = @P_NO_IMO)
			          AND (ISNULL(@P_NO_EMP, '') = '' OR QH1.NO_EMP = @P_NO_EMP)
			          AND (ISNULL(@P_CD_SALEORG, '') = '' OR SG.CD_SALEORG = @P_CD_SALEORG)
			          AND (ISNULL(@P_CD_SALEGRP, '') = '' OR QH1.CD_SALEGRP IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SALEGRP))))
		  GROUP BY QH.CD_COMPANY, QH.NO_FILE, QH.CD_PARTNER
		  UNION ALL
		  SELECT QH.CD_COMPANY, QH.NO_FILE, QH.CD_PARTNER,
		  	     SUM(QL.AM_KR) AS AM_INQ,
				 SUM(CASE WHEN QL1.NO_FILE IS NULL THEN 0 ELSE 1 END) AS QT_QTN,
				 SUM(QL1.AM_KR_S) AS AM_QTN,
		  	     SUM(CASE WHEN PL.NO_SO IS NULL THEN 0 ELSE 1 END) AS QT_PO,
		  	     SUM(PL.AM_PO) AS AM_PO,
		  	     SUM(CASE WHEN SL.NO_SO IS NULL THEN 0 ELSE 1 END) AS QT_SO,
				 SUM(SL.AM_KR_S) AS AM_SO,
		  	     SUM(CASE WHEN SB.NO_FILE IS NULL THEN 0 ELSE 1 END) AS QT_STOCK,
		  	     SUM(ISNULL(SB.QT_STOCK, 0) * ISNULL(SB.UM_KR, 0)) AS AM_STOCK,
		  	     MAX(PL.LT) AS LT
		  FROM A QH
		  JOIN CZ_PU_QTNL QL ON QL.CD_COMPANY = QH.CD_COMPANY AND QL.NO_FILE = QH.NO_FILE AND QL.CD_PARTNER = QH.CD_PARTNER
		  LEFT JOIN CZ_SA_QTNL QL1 ON QL1.CD_COMPANY = QL.CD_COMPANY AND QL1.NO_FILE = QL.NO_FILE AND QL1.NO_LINE = QL.NO_LINE
		  LEFT JOIN SA_SOL SL ON SL.CD_COMPANY = QL.CD_COMPANY AND SL.NO_SO = QL.NO_FILE AND SL.SEQ_SO = QL.NO_LINE
		  LEFT JOIN CZ_SA_STOCK_BOOK SB ON SB.CD_COMPANY = SL.CD_COMPANY AND SB.NO_FILE = SL.NO_SO AND SB.NO_LINE = SL.SEQ_SO
		  LEFT JOIN (SELECT PH.CD_COMPANY, PL.NO_SO, PL.NO_LINE,
		  		     	    SUM(PL.AM) AS AM_PO,
		  		     	    MAX(DATEDIFF(DAY, PH.DT_PO, IL.DT_IO)) AS LT
		  		     FROM PU_POH PH
		  		     JOIN PU_POL PL ON PL.CD_COMPANY = PH.CD_COMPANY AND PL.NO_PO = PH.NO_PO
		  		     LEFT JOIN (SELECT IL.CD_COMPANY, IL.NO_PSO_MGMT, IL.NO_PSOLINE_MGMT,
		  		     			       MAX(IH.DT_IO) AS DT_IO
		  		     		    FROM MM_QTIOH IH
		  		     		    LEFT JOIN MM_QTIO IL ON IL.CD_COMPANY = IH.CD_COMPANY AND IL.NO_IO = IH.NO_IO
		  		     		    GROUP BY IL.CD_COMPANY, IL.NO_PSO_MGMT, IL.NO_PSOLINE_MGMT) IL
		  		     ON IL.CD_COMPANY = PL.CD_COMPANY AND IL.NO_PSO_MGMT = PL.NO_PO AND IL.NO_PSOLINE_MGMT = PL.NO_LINE
		  		     GROUP BY PH.CD_COMPANY, PL.NO_SO, PL.NO_LINE) PL
		  ON PL.CD_COMPANY = QL.CD_COMPANY AND PL.NO_SO = QL.NO_FILE AND PL.NO_LINE = QL.NO_LINE
		  WHERE QL.YN_CHOICE = 'Y'
		  AND ISNULL(QL.CD_ITEM, '') NOT LIKE 'SD%'
		  AND (ISNULL(@P_CD_ITEMGRP, '') = '' OR EXISTS (SELECT 1 
														 FROM CZ_SA_QTNL QL1
														 WHERE QL1.CD_COMPANY = QL.CD_COMPANY
														 AND QL1.NO_FILE = QL.NO_FILE
														 AND QL1.NO_LINE = QL.NO_LINE 
														 AND QL1.GRP_ITEM = @P_CD_ITEMGRP))
		   AND EXISTS (SELECT 1 
					   FROM CZ_SA_QTNH QH1
					   LEFT JOIN MA_SALEGRP SG ON SG.CD_COMPANY = QH1.CD_COMPANY AND SG.CD_SALEGRP = QH1.CD_SALEGRP
					   WHERE QH1.CD_COMPANY = QH.CD_COMPANY
					   AND QH1.NO_FILE = QH.NO_FILE
					   AND QH1.DT_INQ BETWEEN @P_DT_FROM AND @P_DT_TO
					   AND (ISNULL(@P_CD_PARTNER, '') = '' OR QH1.CD_PARTNER IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_PARTNER)))
			           AND (ISNULL(@P_NO_IMO, '') = '' OR QH1.NO_IMO = @P_NO_IMO)
			           AND (ISNULL(@P_NO_EMP, '') = '' OR QH1.NO_EMP = @P_NO_EMP)
			           AND (ISNULL(@P_CD_SALEORG, '') = '' OR SG.CD_SALEORG = @P_CD_SALEORG)
			           AND (ISNULL(@P_CD_SALEGRP, '') = '' OR QH1.CD_SALEGRP IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SALEGRP))))
		  GROUP BY QH.CD_COMPANY, QH.NO_FILE, QH.CD_PARTNER
	),
	C AS
	(
		SELECT B.CD_COMPANY, B.NO_FILE, B.CD_PARTNER,
			   SUM(B.AM_INQ) AS AM_INQ,
			   SUM(CASE WHEN B.QT_QTN > 0 THEN 0 ELSE 1 END) AS QT_QTN,
			   SUM(B.AM_QTN) AS AM_QTN,
			   SUM(CASE WHEN B.QT_PO > 0 THEN 1 ELSE 0 END) AS QT_PO,
			   SUM(B.AM_PO) AS AM_PO,
			   SUM(CASE WHEN B.QT_STOCK > 0 THEN 1 ELSE 0 END) AS QT_STOCK,
			   SUM(B.AM_STOCK) AS AM_STOCK,
			   SUM(CASE WHEN B.QT_SO > 0 THEN 0 ELSE 1 END) AS QT_SO,
			   SUM(B.AM_SO) AS AM_SO,
			   MAX(B.LT) AS LT
		FROM B
		GROUP BY B.CD_COMPANY, B.NO_FILE, B.CD_PARTNER
	),
	D AS
	(
		SELECT C.CD_COMPANY, C.CD_PARTNER,
			   COUNT(C.NO_FILE) AS QT_INQ,
			   SUM(C.QT_QTN) AS QT_QTN,
			   SUM(C.QT_PO) AS QT_PO,
			   SUM(C.QT_STOCK) AS QT_STOCK,
			   SUM(C.QT_SO) AS QT_SO,
			   ISNULL(SUM(C.AM_INQ), 0) AS AM_INQ,
			   ISNULL(SUM(C.AM_QTN), 0) AS AM_QTN,
			   ISNULL(SUM(C.AM_PO), 0) AS AM_PO,
			   ISNULL(SUM(C.AM_STOCK), 0) AS AM_STOCK,
			   ISNULL(SUM(C.AM_SO), 0) AS AM_SO,
			   ISNULL(MAX(C.LT), 0) AS LT_MAX,
			   ISNULL(MIN(C.LT), 0) AS LT_MIN,
			   ISNULL(ROUND(AVG(C.LT), 2), 0) AS LT_AVG,
			   ISNULL(ROUND(STDEV(C.LT), 2), 0) AS LT_STDEV 
		FROM C
		GROUP BY C.CD_COMPANY, C.CD_PARTNER	
	)
	SELECT D.CD_PARTNER, 
		   MP.LN_PARTNER,
		   D.QT_INQ,
		   D.QT_QTN,
		   D.QT_PO,
		   D.QT_STOCK,
		   D.QT_SO,
		   D.AM_INQ,
		   D.AM_QTN,
		   D.AM_PO,
		   D.AM_STOCK,
		   D.AM_SO,
		   (D.AM_SO - (D.AM_PO + D.AM_STOCK)) AS AM_PROFIT,
		   (CASE WHEN D.QT_INQ = 0 THEN 0
								   ELSE ROUND(((D.QT_PO + D.QT_STOCK) / CONVERT(FLOAT, D.QT_INQ)) * 100, 2) END) AS RT_PO,
		   (CASE WHEN D.AM_SO = 0 THEN 0
								  ELSE ROUND(((D.AM_SO - (D.AM_PO + D.AM_STOCK)) / D.AM_SO) * 100, 2) END) AS RT_PROFIT,
		   D.LT_MAX,
		   D.LT_MIN,
		   D.LT_AVG,
		   D.LT_STDEV 
	FROM D
	JOIN MA_PARTNER MP ON MP.CD_COMPANY = D.CD_COMPANY AND MP.CD_PARTNER = D.CD_PARTNER
	ORDER BY D.AM_PO + D.AM_STOCK DESC
END
ELSE
BEGIN
	WITH A AS
	(
		SELECT QH.CD_COMPANY, QH.NO_FILE, QH.CD_PARTNER,
		  	   SUM(QL.AM_KR) AS AM_INQ,
			   NULL AS QT_QTN,
			   NULL AS AM_QTN,
		  	   NULL AS QT_PO,
		  	   NULL AS AM_PO,
			   NULL AS QT_SO,
		  	   NULL AS AM_SO,
		  	   NULL AS QT_STOCK,
		  	   NULL AS AM_STOCK,
		  	   NULL AS LT
		  FROM CZ_PU_QTNH QH
		  JOIN CZ_PU_QTNL QL ON QL.CD_COMPANY = QH.CD_COMPANY AND QL.NO_FILE = QH.NO_FILE AND QL.CD_PARTNER = QH.CD_PARTNER
		  WHERE QH.CD_COMPANY = @P_CD_COMPANY
		  AND (QL.YN_CHOICE IS NULL OR QL.YN_CHOICE = 'N')
		  AND ISNULL(QL.CD_ITEM, '') NOT LIKE 'SD%'
		  AND (ISNULL(@P_CD_ITEMGRP, '') = '' OR EXISTS (SELECT 1 
														 FROM CZ_SA_QTNL QL1
														 WHERE QL1.CD_COMPANY = QL.CD_COMPANY
														 AND QL1.NO_FILE = QL.NO_FILE
														 AND QL1.NO_LINE = QL.NO_LINE 
														 AND QL1.GRP_ITEM = @P_CD_ITEMGRP))
		  AND EXISTS (SELECT 1 
					  FROM CZ_SA_QTNH QH1
					  LEFT JOIN MA_SALEGRP SG ON SG.CD_COMPANY = QH1.CD_COMPANY AND SG.CD_SALEGRP = QH1.CD_SALEGRP
					  WHERE QH1.CD_COMPANY = QH.CD_COMPANY
					  AND QH1.NO_FILE = QH.NO_FILE
					  AND QH1.DT_INQ BETWEEN @P_DT_FROM AND @P_DT_TO
					  AND (ISNULL(@P_CD_PARTNER, '') = '' OR 
						   QH1.CD_PARTNER IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_PARTNER)) OR 
						   (QH1.CD_COMPANY = 'K100' AND QH1.CD_PARTNER = '10286' AND EXISTS (SELECT 1 
																				             FROM CZ_SA_QTNH
																				             WHERE CD_COMPANY = 'S100'
																				             AND (NO_FILE = QH1.NO_FILE OR NO_FILE = QH1.NO_REF)
																				             AND CD_PARTNER IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_PARTNER)))))
			          AND (ISNULL(@P_NO_IMO, '') = '' OR QH1.NO_IMO = @P_NO_IMO)
			          AND (ISNULL(@P_NO_EMP, '') = '' OR QH1.NO_EMP = @P_NO_EMP)
			          AND (ISNULL(@P_CD_SALEORG, '') = '' OR SG.CD_SALEORG = @P_CD_SALEORG)
			          AND (ISNULL(@P_CD_SALEGRP, '') = '' OR QH1.CD_SALEGRP IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SALEGRP))))
		  GROUP BY QH.CD_COMPANY, QH.NO_FILE, QH.CD_PARTNER
		  UNION ALL
		  SELECT QH.CD_COMPANY, QH.NO_FILE, QH.CD_PARTNER,
		  	     SUM(QL.AM_KR) AS AM_INQ,
		  	     SUM(CASE WHEN QL1.NO_FILE IS NULL THEN 0 ELSE 1 END) AS QT_QTN,
				 SUM(QL1.AM_KR_S) AS AM_QTN,
				 SUM(CASE WHEN PL.NO_SO IS NULL THEN 0 ELSE 1 END) AS QT_PO,
		  	     SUM(PL.AM_PO) AS AM_PO,
				 SUM(CASE WHEN SL.NO_SO IS NULL THEN 0 ELSE 1 END) AS QT_SO,
		  	     SUM(SL.AM_KR_S) AS AM_SO,
		  	     SUM(CASE WHEN SB.NO_FILE IS NULL THEN 0 ELSE 1 END) AS QT_STOCK,
		  	     SUM(ISNULL(SB.QT_STOCK, 0) * ISNULL(SB.UM_KR, 0)) AS AM_STOCK,
		  	     MAX(PL.LT) AS LT
		  FROM CZ_PU_QTNH QH
		  JOIN CZ_PU_QTNL QL ON QL.CD_COMPANY = QH.CD_COMPANY AND QL.NO_FILE = QH.NO_FILE AND QL.CD_PARTNER = QH.CD_PARTNER
		  LEFT JOIN CZ_SA_QTNL QL1 ON QL1.CD_COMPANY = QL.CD_COMPANY AND QL1.NO_FILE = QL.NO_FILE AND QL1.NO_LINE = QL.NO_LINE
		  LEFT JOIN SA_SOL SL ON SL.CD_COMPANY = QL.CD_COMPANY AND SL.NO_SO = QL.NO_FILE AND SL.SEQ_SO = QL.NO_LINE
		  LEFT JOIN CZ_SA_STOCK_BOOK SB ON SB.CD_COMPANY = SL.CD_COMPANY AND SB.NO_FILE = SL.NO_SO AND SB.NO_LINE = SL.SEQ_SO
		  LEFT JOIN (SELECT PH.CD_COMPANY, PL.NO_SO, PL.NO_LINE,
		  		     	    SUM(PL.AM) AS AM_PO,
		  		     	    MAX(DATEDIFF(DAY, PH.DT_PO, IL.DT_IO)) AS LT
		  		     FROM PU_POH PH
		  		     JOIN PU_POL PL ON PL.CD_COMPANY = PH.CD_COMPANY AND PL.NO_PO = PH.NO_PO
		  		     LEFT JOIN (SELECT IL.CD_COMPANY, IL.NO_PSO_MGMT, IL.NO_PSOLINE_MGMT,
		  		     			       MAX(IH.DT_IO) AS DT_IO
		  		     		    FROM MM_QTIOH IH
		  		     		    LEFT JOIN MM_QTIO IL ON IL.CD_COMPANY = IH.CD_COMPANY AND IL.NO_IO = IH.NO_IO
		  		     		    GROUP BY IL.CD_COMPANY, IL.NO_PSO_MGMT, IL.NO_PSOLINE_MGMT) IL
		  		     ON IL.CD_COMPANY = PL.CD_COMPANY AND IL.NO_PSO_MGMT = PL.NO_PO AND IL.NO_PSOLINE_MGMT = PL.NO_LINE
		  		     GROUP BY PH.CD_COMPANY, PL.NO_SO, PL.NO_LINE) PL
		  ON PL.CD_COMPANY = QL.CD_COMPANY AND PL.NO_SO = QL.NO_FILE AND PL.NO_LINE = QL.NO_LINE
		  WHERE QH.CD_COMPANY = @P_CD_COMPANY
		  AND QL.YN_CHOICE = 'Y'
		  AND ISNULL(QL.CD_ITEM, '') NOT LIKE 'SD%'
		  AND (ISNULL(@P_CD_ITEMGRP, '') = '' OR EXISTS (SELECT 1 
														 FROM CZ_SA_QTNL QL1
														 WHERE QL1.CD_COMPANY = QL.CD_COMPANY
														 AND QL1.NO_FILE = QL.NO_FILE
														 AND QL1.NO_LINE = QL.NO_LINE 
														 AND QL1.GRP_ITEM = @P_CD_ITEMGRP))
		   AND EXISTS (SELECT 1 
					   FROM CZ_SA_QTNH QH1
					   LEFT JOIN MA_SALEGRP SG ON SG.CD_COMPANY = QH1.CD_COMPANY AND SG.CD_SALEGRP = QH1.CD_SALEGRP
					   WHERE QH1.CD_COMPANY = QH.CD_COMPANY
					   AND QH1.NO_FILE = QH.NO_FILE
					   AND QH1.DT_INQ BETWEEN @P_DT_FROM AND @P_DT_TO
					   AND (ISNULL(@P_CD_PARTNER, '') = '' OR 
						    QH1.CD_PARTNER IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_PARTNER)) OR 
						    (QH1.CD_COMPANY = 'K100' AND QH1.CD_PARTNER = '10286' AND EXISTS (SELECT 1 
						 														              FROM CZ_SA_QTNH
						 														              WHERE CD_COMPANY = 'S100'
						 														              AND (NO_FILE = QH1.NO_FILE OR NO_FILE = QH1.NO_REF)
						 														              AND CD_PARTNER IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_PARTNER)))))
			           AND (ISNULL(@P_NO_IMO, '') = '' OR QH1.NO_IMO = @P_NO_IMO)
			           AND (ISNULL(@P_NO_EMP, '') = '' OR QH1.NO_EMP = @P_NO_EMP)
			           AND (ISNULL(@P_CD_SALEORG, '') = '' OR SG.CD_SALEORG = @P_CD_SALEORG)
			           AND (ISNULL(@P_CD_SALEGRP, '') = '' OR QH1.CD_SALEGRP IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SALEGRP))))
		  GROUP BY QH.CD_COMPANY, QH.NO_FILE, QH.CD_PARTNER
	),
	B AS
	(
		SELECT A.CD_COMPANY, A.NO_FILE, A.CD_PARTNER,
			   SUM(A.AM_INQ) AS AM_INQ,
			   SUM(CASE WHEN A.QT_QTN > 0 THEN 1 ELSE 0 END) AS QT_QTN,
			   SUM(A.AM_QTN) AS AM_QTN,
			   SUM(CASE WHEN A.QT_PO > 0 THEN 1 ELSE 0 END) AS QT_PO,
			   SUM(A.AM_PO) AS AM_PO,
			   SUM(CASE WHEN A.QT_STOCK > 0 THEN 1 ELSE 0 END) AS QT_STOCK,
			   SUM(A.AM_STOCK) AS AM_STOCK,
			   SUM(CASE WHEN A.QT_SO > 0 THEN 1 ELSE 0 END) AS QT_SO,
			   SUM(A.AM_SO) AS AM_SO,
			   MAX(A.LT) AS LT
		FROM A
		GROUP BY A.CD_COMPANY, A.NO_FILE, A.CD_PARTNER
	),
	C AS
	(
		SELECT B.CD_COMPANY, B.CD_PARTNER,
			   COUNT(B.NO_FILE) AS QT_INQ,
			   SUM(B.QT_QTN) AS QT_QTN,
			   SUM(B.QT_PO) AS QT_PO,
			   SUM(B.QT_STOCK) AS QT_STOCK,
			   SUM(B.QT_SO) AS QT_SO,
			   ISNULL(SUM(B.AM_INQ), 0) AS AM_INQ,
			   ISNULL(SUM(B.AM_QTN), 0) AS AM_QTN,
			   ISNULL(SUM(B.AM_PO), 0) AS AM_PO,
			   ISNULL(SUM(B.AM_STOCK), 0) AS AM_STOCK,
			   ISNULL(SUM(B.AM_SO), 0) AS AM_SO,
			   ISNULL(MAX(B.LT), 0) AS LT_MAX,
			   ISNULL(MIN(B.LT), 0) AS LT_MIN,
			   ISNULL(ROUND(AVG(B.LT), 2), 0) AS LT_AVG,
			   ISNULL(ROUND(STDEV(B.LT), 2), 0) AS LT_STDEV 
		FROM B
		GROUP BY B.CD_COMPANY, B.CD_PARTNER	
	)
	SELECT C.CD_PARTNER, 
		   MP.LN_PARTNER,
		   C.QT_INQ,
		   C.QT_QTN,
		   C.QT_PO,
		   C.QT_STOCK,
		   C.QT_SO,
		   C.AM_INQ,
		   C.AM_QTN,
		   C.AM_PO,
		   C.AM_STOCK,
		   C.AM_SO,
		   (C.AM_SO - (C.AM_PO + C.AM_STOCK)) AS AM_PROFIT,
		   (CASE WHEN C.QT_INQ = 0 THEN 0
								   ELSE ROUND(((C.QT_PO + C.QT_STOCK) / CONVERT(FLOAT, C.QT_INQ)) * 100, 2) END) AS RT_PO,
		   (CASE WHEN C.AM_SO = 0 THEN 0
								  ELSE ROUND(((C.AM_SO - (C.AM_PO + C.AM_STOCK)) / C.AM_SO) * 100, 2) END) AS RT_PROFIT,
		   C.LT_MAX,
		   C.LT_MIN,
		   C.LT_AVG,
		   C.LT_STDEV 
	FROM C
	JOIN MA_PARTNER MP ON MP.CD_COMPANY = C.CD_COMPANY AND MP.CD_PARTNER = C.CD_PARTNER
	ORDER BY C.AM_PO + C.AM_STOCK DESC
END

GO