USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_CRM_CHART_P03_S]    Script Date: 2017-07-13 오후 3:13:12 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER PROCEDURE [NEOE].[SP_CZ_SA_CRM_CHART_P03_S]
(
	@P_CD_COMPANY		NVARCHAR(7),
	@P_DT_FROM			NVARCHAR(8),
	@P_DT_TO			NVARCHAR(8),
	@P_CD_PARTNER		NVARCHAR(1000),
	@P_NO_IMO			NVARCHAR(10),
	@P_NO_EMP			NVARCHAR(10),
	@P_CD_ITEMGRP		NVARCHAR(20),
	@P_CD_SALEORG		NVARCHAR(7),
	@P_CD_SALEGRP		NVARCHAR(1000),
	@P_LENGTH			NUMERIC(1)
) 
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

WITH QH AS 
(
	SELECT CONVERT(NUMERIC(17, 0), ROUND(CASE WHEN ISNULL(QL.AM_SO, 0) = 0 THEN 0
											  WHEN ISNULL(QL.AM_PROFIT, 0) < 0 THEN -100 
																	       ELSE (ISNULL(QL.AM_PROFIT, 0) / ISNULL(QL.AM_SO, 0)) * 100 END, 0)) AS RT_PROFIT,
		   1.0 AS QT_QTN,
		   (CASE WHEN SH.CD_COMPANY IS NULL THEN 0 ELSE 1.0 END) AS QT_SO
	FROM CZ_SA_QTNH QH
	JOIN (SELECT QL.CD_COMPANY, QL.NO_FILE,
				 SUM(QL.AM_KR_S) AS AM_SO,
				 SUM(ISNULL(QL.AM_KR_S, 0) - ISNULL(QL.AM_KR_P, 0)) AS AM_PROFIT
	      FROM CZ_SA_QTNL QL
		  WHERE (ISNULL(@P_CD_ITEMGRP, '') = '' OR QL.GRP_ITEM = @P_CD_ITEMGRP)
		  GROUP BY QL.CD_COMPANY, QL.NO_FILE) QL
	ON QL.CD_COMPANY = QH.CD_COMPANY AND QL.NO_FILE = QH.NO_FILE
	LEFT JOIN MA_SALEGRP SG ON SG.CD_COMPANY = QH.CD_COMPANY AND SG.CD_SALEGRP = QH.CD_SALEGRP
	LEFT JOIN SA_SOH SH ON SH.CD_COMPANY = QH.CD_COMPANY AND SH.NO_SO = QH.NO_FILE
	WHERE QH.CD_COMPANY = @P_CD_COMPANY
	AND QH.DT_QTN BETWEEN @P_DT_FROM AND @P_DT_TO
	AND (ISNULL(@P_CD_PARTNER, '') = '' OR QH.CD_PARTNER IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_PARTNER)))
    AND (ISNULL(@P_NO_IMO, '') = '' OR QH.NO_IMO = @P_NO_IMO)
    AND (ISNULL(@P_NO_EMP, '') = '' OR QH.NO_EMP = @P_NO_EMP)
    AND (ISNULL(@P_CD_SALEORG, '') = '' OR SG.CD_SALEORG = @P_CD_SALEORG)
    AND (ISNULL(@P_CD_SALEGRP, '') = '' OR QH.CD_SALEGRP IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SALEGRP)))
)
SELECT CONVERT(NVARCHAR, QH.RT_PROFIT) AS RT_PROFIT,
	   ROUND((ISNULL(QH.QT_QTN, 0) / ISNULL(QH1.QT_QTN, 0)) * 100, 2) AS RT_QT_QTN,
	   ROUND((ISNULL(QH.QT_SO, 0) / ISNULL(QH1.QT_SO, 0)) * 100, 2) AS RT_QT_SO,
	   ISNULL(QH.QT_QTN, 0) AS QT_QTN,
	   ISNULL(QH.QT_SO, 0) AS QT_SO,
	   ISNULL(QH.RT_SO, 0) AS RT_SO,
	   ISNULL(QH1.RT_SO, 0) AS RT_SO_ALL
FROM (SELECT RT_PROFIT,
      	     SUM(QT_QTN) AS QT_QTN,
      	     SUM(QT_SO) AS QT_SO,
			 ROUND(CASE WHEN SUM(QH.QT_QTN) = 0 OR SUM(QH.QT_SO) = 0 THEN 0 
																	 ELSE (SUM(QH.QT_SO) / SUM(QH.QT_QTN)) * 100 END, 2) AS RT_SO 
      FROM QH
      GROUP BY RT_PROFIT) QH
JOIN (SELECT SUM(QT_QTN) AS QT_QTN,
      	     SUM(QT_SO) AS QT_SO,
			 CONVERT(NUMERIC(17, 2), ROUND(CASE WHEN SUM(QH.QT_QTN) = 0 OR SUM(QH.QT_SO) = 0 THEN 0 
																							 ELSE (SUM(QH.QT_SO) / SUM(QH.QT_QTN)) * 100 END, 2)) AS RT_SO
	  FROM QH) AS QH1
ON 1=1
WHERE QH.QT_SO > 0
ORDER BY QH.RT_PROFIT

GO