USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_CRM_CHART_S01_S]    Script Date: 2017-07-13 오후 3:13:12 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER PROCEDURE [NEOE].[SP_CZ_SA_CRM_CHART_S01_S]
(
	@P_CD_COMPANY		NVARCHAR(7),
	@P_DT_FROM			NVARCHAR(8),
	@P_DT_TO			NVARCHAR(8),
	@P_CD_PARTNER		NVARCHAR(1000),
	@P_NO_IMO			NVARCHAR(10),
	@P_NO_EMP			NVARCHAR(10),
	@P_CD_ITEMGRP		NVARCHAR(20),
	@P_CD_SALEORG		NVARCHAR(7),
	@P_CD_SALEGRP		NVARCHAR(1000),
	@P_LENGTH			NUMERIC(1)
) 
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT LEFT(PH.DT_PO, @P_LENGTH) AS DT_PO,
	   ISNULL(SUM(PL.AM_AE), 0) AS AM_AE,
	   ISNULL(SUM(PL.AM_BD), 0) AS AM_BD,
	   ISNULL(SUM(PL.AM_EQ), 0) AS AM_EQ,
	   ISNULL(SUM(PL.AM_ET), 0) AS AM_ET,
	   ISNULL(SUM(PL.AM_GS), 0) AS AM_GS,
	   ISNULL(SUM(PL.AM_HE), 0) AS AM_HE,
	   ISNULL(SUM(PL.AM_ME), 0) AS AM_ME,
	   ISNULL(SUM(PL.AM_PP), 0) AS AM_PP,
	   ISNULL(SUM(PL.AM_PV), 0) AS AM_PV,
	   ISNULL(SUM(PL.AM_SG), 0) AS AM_SG,
	   ISNULL(SUM(PL.AM_TC), 0) AS AM_TC,
	   ISNULL(SUM(PL.AM_TS), 0) AS AM_TS
FROM PU_POH PH
LEFT JOIN SA_SOH SH ON SH.CD_COMPANY = PH.CD_COMPANY AND SH.NO_SO = PH.CD_PJT
LEFT JOIN MA_SALEGRP SG ON SG.CD_COMPANY = SH.CD_COMPANY AND SG.CD_SALEGRP = SH.CD_SALEGRP
LEFT JOIN (SELECT PL.CD_COMPANY, PL.NO_PO,
				  SUM(CASE WHEN MI.GRP_ITEM = 'AE' THEN PL.AM ELSE 0 END) AS AM_AE,
				  SUM(CASE WHEN MI.GRP_ITEM = 'BD' THEN PL.AM ELSE 0 END) AS AM_BD,
				  SUM(CASE WHEN MI.GRP_ITEM = 'EQ' THEN PL.AM ELSE 0 END) AS AM_EQ,
				  SUM(CASE WHEN MI.GRP_ITEM = 'ET' THEN PL.AM ELSE 0 END) AS AM_ET,
				  SUM(CASE WHEN MI.GRP_ITEM = 'GS' THEN PL.AM ELSE 0 END) AS AM_GS,
				  SUM(CASE WHEN MI.GRP_ITEM = 'HE' THEN PL.AM ELSE 0 END) AS AM_HE,
				  SUM(CASE WHEN MI.GRP_ITEM = 'ME' THEN PL.AM ELSE 0 END) AS AM_ME,
				  SUM(CASE WHEN MI.GRP_ITEM = 'PP' THEN PL.AM ELSE 0 END) AS AM_PP,
				  SUM(CASE WHEN MI.GRP_ITEM = 'PV' THEN PL.AM ELSE 0 END) AS AM_PV,
				  SUM(CASE WHEN MI.GRP_ITEM = 'SG' THEN PL.AM ELSE 0 END) AS AM_SG,
				  SUM(CASE WHEN MI.GRP_ITEM = 'TC' THEN PL.AM ELSE 0 END) AS AM_TC,
				  SUM(CASE WHEN MI.GRP_ITEM = 'TS' THEN PL.AM ELSE 0 END) AS AM_TS
		   FROM PU_POL PL
		   LEFT JOIN MA_PITEM MI ON MI.CD_COMPANY = PL.CD_COMPANY AND MI.CD_PLANT = PL.CD_PLANT AND MI.CD_ITEM = PL.CD_ITEM
		   WHERE (ISNULL(@P_CD_ITEMGRP, '') = '' OR MI.GRP_ITEM = @P_CD_ITEMGRP)
		   GROUP BY PL.CD_COMPANY, PL.NO_PO) PL
ON PL.CD_COMPANY = PH.CD_COMPANY AND PL.NO_PO = PH.NO_PO
WHERE PH.CD_COMPANY = @P_CD_COMPANY
AND PH.DT_PO BETWEEN @P_DT_FROM AND @P_DT_TO
AND (ISNULL(@P_CD_PARTNER, '') = '' OR PH.CD_PARTNER IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_PARTNER)))
AND (ISNULL(@P_NO_EMP, '') = '' OR PH.NO_EMP = @P_NO_EMP)
AND (ISNULL(@P_CD_SALEORG, '') = '' OR SG.CD_SALEORG = @P_CD_SALEORG)
AND (ISNULL(@P_CD_SALEGRP, '') = '' OR SH.CD_SALEGRP IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SALEGRP)))
GROUP BY LEFT(PH.DT_PO, @P_LENGTH)
ORDER BY LEFT(PH.DT_PO, @P_LENGTH)

GO