USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_CRM_CHART_S04_S]    Script Date: 2017-07-13 오후 3:13:12 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER PROCEDURE [NEOE].[SP_CZ_SA_CRM_CHART_S04_S]
(
	@P_CD_COMPANY		NVARCHAR(7),
	@P_DT_FROM			NVARCHAR(8),
	@P_DT_TO			NVARCHAR(8),
	@P_CD_PARTNER		NVARCHAR(1000),
	@P_NO_IMO			NVARCHAR(10),
	@P_NO_EMP			NVARCHAR(10),
	@P_CD_ITEMGRP		NVARCHAR(20),
	@P_CD_SALEORG		NVARCHAR(7),
	@P_CD_SALEGRP		NVARCHAR(1000),
	@P_LENGTH			NUMERIC(1)
) 
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT IH.DT_IV,
	   SUM(IH1.AM_CLS) AS AM_CLS,
	   SUM(FD.AM_BAN) AS AM_BAN,
	   SUM(FD.AM_BAN_ADPAY) AS AM_BAN_ADPAY,
	   SUM(ISNULL(IH1.AM_CLS, 0) - (ISNULL(FD.AM_BAN, 0) + ISNULL(FD.AM_BAN_ADPAY, 0))) AS AM_REMAIN,
	   (CASE WHEN SUM(IH1.AM_CLS) = 0 THEN 0
									  ELSE ROUND(SUM(ISNULL(IH1.AM_CLS, 0) - (ISNULL(FD.AM_BAN, 0) + ISNULL(FD.AM_BAN_ADPAY, 0))) / SUM(IH1.AM_CLS) * 100, 2) END) AS RT_REMAIN
FROM (SELECT IH.CD_COMPANY,
	  		 LEFT(IH.DT_PROCESS, @P_LENGTH) AS DT_IV
	  FROM PU_IVH IH
	  JOIN PU_IVL IL ON IL.CD_COMPANY = IH.CD_COMPANY AND IL.NO_IV = IH.NO_IV
	  WHERE IH.CD_COMPANY = @P_CD_COMPANY
	  AND IH.DT_PROCESS BETWEEN @P_DT_FROM AND @P_DT_TO
	  AND (ISNULL(@P_CD_PARTNER, '') = '' OR IH.CD_PARTNER IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_PARTNER)))
	  GROUP BY IH.CD_COMPANY, LEFT(IH.DT_PROCESS, @P_LENGTH)) IH
LEFT JOIN (SELECT IH.CD_COMPANY, 
				  LEFT(IH.DT_PROCESS, @P_LENGTH) AS DT_IV,
				  FD.NO_DOCU,  
				  SUM(CASE WHEN IL.YN_RETURN = 'Y' THEN -(IL.AM_CLS + IL.VAT) 
				  								   ELSE (IL.AM_CLS + IL.VAT) END) AS AM_CLS
			   FROM PU_IVH IH
			   JOIN PU_IVL IL ON IL.CD_COMPANY = IH.CD_COMPANY AND IL.NO_IV = IH.NO_IV
			   LEFT JOIN (SELECT CD_COMPANY, NO_MDOCU, NO_DOCU 
						  FROM FI_DOCU
						  GROUP BY CD_COMPANY, NO_MDOCU, NO_DOCU) FD
			   ON FD.CD_COMPANY = IH.CD_COMPANY AND FD.NO_MDOCU = IH.NO_IV
			   WHERE (ISNULL(@P_CD_PARTNER, '') = '' OR IH.CD_PARTNER IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_PARTNER)))
			   GROUP BY IH.CD_COMPANY, LEFT(IH.DT_PROCESS, @P_LENGTH), FD.NO_DOCU) IH1
ON IH1.CD_COMPANY = IH.CD_COMPANY AND IH1.DT_IV <= IH.DT_IV
LEFT JOIN (SELECT FD.CD_COMPANY, 
				  MAX(FD.DT_ACCT) AS DT_ACCT,
				  FD.NO_BDOCU,
				  SUM(CASE WHEN AB.NO_BILLS IS NULL THEN (FD.AM_CR + FD.AM_DR) ELSE 0 END) AS AM_BAN,
				  SUM(CASE WHEN AB.NO_BILLS IS NOT NULL THEN (FD.AM_CR + FD.AM_DR) ELSE 0 END) AS AM_BAN_ADPAY
		   FROM FI_DOCU FD
		   LEFT JOIN CZ_PU_ADPAYMENT_BILL_H AB ON AB.CD_COMPANY = FD.CD_COMPANY AND AB.NO_BILLS = FD.NO_MDOCU
		   GROUP BY FD.CD_COMPANY, FD.NO_BDOCU) FD
ON FD.CD_COMPANY = IH1.CD_COMPANY AND FD.NO_BDOCU = IH1.NO_DOCU AND LEFT(FD.DT_ACCT, @P_LENGTH) <= IH.DT_IV
GROUP BY IH.DT_IV
ORDER BY IH.DT_IV

GO