USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_CRM_CHART_K03_S]    Script Date: 2017-07-13 오후 3:13:12 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER PROCEDURE [NEOE].[SP_CZ_SA_CRM_CHART_K03_S]
(
	@P_CD_COMPANY		NVARCHAR(7),
	@P_DT_FROM			NVARCHAR(8),
	@P_DT_TO			NVARCHAR(8),
	@P_CD_PARTNER		NVARCHAR(1000),
	@P_NO_IMO			NVARCHAR(10),
	@P_NO_EMP			NVARCHAR(10),
	@P_CD_ITEMGRP		NVARCHAR(20),
	@P_CD_SALEORG		NVARCHAR(7),
	@P_CD_SALEGRP		NVARCHAR(1000),
	@P_LENGTH			NUMERIC(1)
) 
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT QL.CD_ITEM, MI.NM_ITEM, MI.STAND_PRC,
	   ISNULL(SUM(QL.QT_QTN), 0) AS QT_QTN,
	   ISNULL(SUM(SL.QT_SO), 0) AS QT_SO,
	   ISNULL(SUM(SB.QT_STOCK), 0) AS QT_STOCK,
	   ISNULL(SUM(SB.QT_BOOK), 0) AS QT_BOOK
FROM CZ_SA_QTNH QH
LEFT JOIN MA_SALEGRP SG ON SG.CD_COMPANY = QH.CD_COMPANY AND SG.CD_SALEGRP = QH.CD_SALEGRP
LEFT JOIN CZ_SA_QTNL QL ON QL.CD_COMPANY = QH.CD_COMPANY AND QL.NO_FILE = QH.NO_FILE
LEFT JOIN SA_SOL SL ON SL.CD_COMPANY = QL.CD_COMPANY AND SL.NO_SO = QL.NO_FILE AND SL.SEQ_SO = QL.NO_LINE
LEFT JOIN CZ_SA_STOCK_BOOK SB ON SB.CD_COMPANY = QL.CD_COMPANY AND SB.NO_FILE = QL.NO_FILE AND SB.NO_LINE = QL.NO_LINE
LEFT JOIN MA_PITEM MI ON MI.CD_COMPANY = QL.CD_COMPANY AND MI.CD_ITEM = QL.CD_ITEM
WHERE QH.CD_COMPANY = @P_CD_COMPANY
AND QH.DT_INQ BETWEEN @P_DT_FROM AND @P_DT_TO
AND MI.CLS_ITEM = '009'
AND (ISNULL(@P_CD_PARTNER, '') = '' OR QH.CD_PARTNER IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_PARTNER)))
AND (ISNULL(@P_NO_IMO, '') = '' OR QH.NO_IMO = @P_NO_IMO)
AND (ISNULL(@P_NO_EMP, '') = '' OR QH.NO_EMP = @P_NO_EMP)
AND (ISNULL(@P_CD_SALEORG, '') = '' OR SG.CD_SALEORG = @P_CD_SALEORG)
AND (ISNULL(@P_CD_SALEGRP, '') = '' OR QH.CD_SALEGRP IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_SALEGRP)))
GROUP BY QL.CD_ITEM, MI.NM_ITEM, MI.STAND_PRC
ORDER BY SUM(QL.QT_QTN) DESC

GO