IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id(N'UP_TR_EXINV_SELECT') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
DROP PROCEDURE UP_TR_EXINV_SELECT
GO

/***********************************************************************    
**  System : 무역  
**  Sub System : 수출  
**  Page  : 송장등록  
**  Desc  : 송장등록 초기화 및 조회   
**  수정자 : 허성철    
************************************************************************/

CREATE PROCEDURE UP_TR_EXINV_SELECT 
	@P_CD_COMPANY   NVARCHAR(7),  
	@P_NO_INV   NVARCHAR(20)  
AS  
BEGIN
	SELECT NO_INV,  -- 송장번호  
	DT_BALLOT,		-- 발행일자  
	CD_BIZAREA,		-- 사업장  
	CD_SALEGRP,		-- 영업그룹  
	NO_EMP,			-- 담당자
	  
	FG_LC,			-- LC구분  
	CD_PARTNER,		-- 거래처  
	CD_EXCH,		-- 환종  
	AM_EX,			-- 외화금액  
	DT_LOADING,		-- 선적예정일 
	 
	CD_ORIGIN,		-- 원산지  
	CD_AGENT,		-- 대행자  
	CD_EXPORT,		-- 수출자  
	CD_PRODUCT,		-- 제조자  
	SHIP_CORP,		-- 선적회사  
	
	NM_VESSEL,		-- VESSEL명   
	COND_TRANS,		-- 인도조건  
	TP_TRANSPORT,	-- 운송형태  
	TP_TRANS,		-- 운송방법  
	TP_PACKING,		-- 포장형태  
	
	CD_WEIGHT,		-- 중량단위  
	GROSS_WEIGHT,	-- 총중량  
	NET_WEIGHT,		-- 순중량  
	PORT_LOADING,	-- 선적지  
	PORT_ARRIVER,	-- 도착지  
	
	DESTINATION,	-- 목적지  
	NO_SCT,			-- 시작C/T번호  
	NO_ECT,			-- 종료C/T번호  
	CD_CUST_IN AS CD_NOTIFY,		-- 착하통지서  
	DT_TO,			-- 통관예정일  
	
	NO_LC,			-- 관련LC번호  
	NO_SO,			-- 관련수주번호
	REMARK1,  
	REMARK2,  
	REMARK3,   
	
	REMARK4,  
	REMARK5,
	DTS_INSERT,		--등록일
	ID_INSERT,		--등록자
	DTS_UPDATE,		--수정자
	
	ID_UPDATE,		--수정일
	--NO_TO,			--통관번호
	--NO_BL,			--선적번호
	NM_NOTIFY,		--착하통지처
	ADDR1_NOTIFY,	--통지처주소1
	
	ADDR2_NOTIFY,	--통지처주소2
	CD_CONSIGNEE,	--수하인
	NM_CONSIGNEE,	--수하인명
	ADDR1_CONSIGNEE,--수하인주소1
	ADDR2_CONSIGNEE,--수하인주소2
	REMARK,
	
	NM_PARTNER,
	ADDR1_PARTNER,
	ADDR2_PARTNER,
	NM_EXPORT,
	ADDR1_EXPORT,
	ADDR2_EXPORT,
	COND_PRICE,
	
	--(SELECT LN_PARTNER FROM MA_PARTNER WHERE CD_COMPANY = A.CD_COMPANY AND CD_PARTNER = A.CD_PARTNER) NM_PARTNER,    
	(SELECT NM_KOR FROM MA_EMP WHERE CD_COMPANY = A.CD_COMPANY AND NO_EMP = A.NO_EMP) NM_KOR,    
	(SELECT NM_SALEGRP FROM MA_SALEGRP WHERE CD_COMPANY = A.CD_COMPANY AND CD_SALEGRP = A.CD_SALEGRP) NM_SALEGRP,    
	(SELECT NM_BIZAREA FROM MA_BIZAREA WHERE CD_COMPANY = A.CD_COMPANY AND CD_BIZAREA = A.CD_BIZAREA) NM_BIZAREA,    
	(SELECT LN_PARTNER FROM MA_PARTNER WHERE CD_COMPANY = A.CD_COMPANY AND CD_PARTNER = A.SHIP_CORP) NM_SHIP_CORP,    
	--(SELECT LN_PARTNER FROM MA_PARTNER WHERE CD_COMPANY = A.CD_COMPANY AND CD_PARTNER = A.CD_CUST_IN) NM_CUST_IN,    
	--(SELECT LN_PARTNER FROM MA_PARTNER WHERE CD_COMPANY = A.CD_COMPANY AND CD_PARTNER = A.CD_EXPORT) NM_EXPORT,    
	(SELECT LN_PARTNER FROM MA_PARTNER WHERE CD_COMPANY = A.CD_COMPANY AND CD_PARTNER = A.CD_AGENT) NM_AGENT,  
	(SELECT LN_PARTNER FROM MA_PARTNER WHERE CD_COMPANY = A.CD_COMPANY AND CD_PARTNER = A.CD_PRODUCT) NM_PRODUCT  
	FROM TR_INVH A  
	WHERE NO_INV = @P_NO_INV    
	AND  CD_COMPANY = @P_CD_COMPANY   
END
GO
  

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id(N'UP_TR_EXINV_DELETE') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
DROP PROCEDURE UP_TR_EXINV_DELETE
GO

/***********************************************************************    
**  System : 무역  
**  Sub System : 수출  
**  Page  : 송장작성  
**  Desc  : 송장작성 삭제   
**  수정자 : 허성철    
************************************************************************/
   
CREATE PROCEDURE UP_TR_EXINV_DELETE
	@P_CD_COMPANY	NVARCHAR(7),     
	@P_NO_INV		NVARCHAR(20)     
AS
BEGIN
  
	IF EXISTS ( SELECT * FROM TR_COSTEXH WHERE CD_COMPANY = @P_CD_COMPANY AND NO_INVOICE = @P_NO_INV AND FG_PRODUCT = '002')  
	BEGIN  
		RAISERROR -5000 '판매 경비가 등록되어 있어 삭제할 수 없습니다'  
		RETURN
	END  
  
	SET NOCOUNT ON
	DECLARE @V_NO_LINE NUMERIC(3)  
  
	DECLARE CUR CURSOR FOR  
	SELECT NO_LINE FROM TR_INVL WHERE CD_COMPANY = @P_CD_COMPANY AND NO_INV = @P_NO_INV
	  
	OPEN CUR  
	FETCH NEXT FROM CUR INTO @V_NO_LINE  
	WHILE @@FETCH_STATUS = 0  
	BEGIN  
		DELETE  
		FROM TR_INVL  
		WHERE CD_COMPANY = @P_CD_COMPANY  
		AND  NO_INV  = @P_NO_INV  
		AND  NO_LINE  = @V_NO_LINE  

		FETCH NEXT FROM CUR INTO @V_NO_LINE  
	END

	CLOSE CUR  
	DEALLOCATE CUR  
  
	DELETE   
	FROM TR_PACKING    
	WHERE CD_COMPANY = @P_CD_COMPANY  
	AND  NO_INV = @P_NO_INV      
  
	DELETE   
	FROM TR_INVH    
	WHERE CD_COMPANY = @P_CD_COMPANY    
	AND  NO_INV = @P_NO_INV   
END
GO
  
  
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id(N'UP_TR_EXINV_INSERT') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
DROP PROCEDURE UP_TR_EXINV_INSERT
GO

/***********************************************************************    
**  System : 무역  
**  Sub System : 수출  
**  Page  : 송장작성  
**  Desc  : 송장작성 저장   
**  수정자 : 허성철    
************************************************************************/

CREATE PROCEDURE UP_TR_EXINV_INSERT    
	@P_NO_INV			NVARCHAR(20),    
	@P_CD_COMPANY		NVARCHAR(7),    
	@P_DT_BALLOT		NCHAR(8),    
	@P_CD_BIZAREA		NVARCHAR(7),    
	@P_CD_SALEGRP		NVARCHAR(7),    
	@P_NO_EMP			NVARCHAR(10),    
	
	@P_FG_LC			NCHAR(3),    
	@P_CD_PARTNER		NVARCHAR(7),    
	@P_CD_EXCH			NVARCHAR(3),    
	@P_AM_EX			NUMERIC(17,4),    
	@P_DT_LOADING		NCHAR(8),    
	
	@P_CD_ORIGIN		NVARCHAR(3),    
	@P_CD_AGENT			NVARCHAR(7),    
	@P_CD_EXPORT		NVARCHAR(7),    
	@P_CD_PRODUCT		NVARCHAR(7),    
	@P_SHIP_CORP		NVARCHAR(7),    
	
	@P_NM_VESSEL		NVARCHAR(50),    
	@P_COND_TRANS		NVARCHAR(50),    
	@P_TP_TRANSPORT		NVARCHAR(3),    
	@P_TP_TRANS			NVARCHAR(3),    
	@P_TP_PACKING		NVARCHAR(3),    
	
	@P_CD_WEIGHT		NVARCHAR(3),    
	@P_GROSS_WEIGHT		NUMERIC(17,4),    
	@P_NET_WEIGHT		NUMERIC(17,4),    
	@P_PORT_LOADING		NVARCHAR(50),    
	@P_PORT_ARRIVER		NVARCHAR(50),    
	
	@P_DESTINATION		NVARCHAR(50),    
	@P_NO_SCT			NUMERIC(10,0),    
	@P_NO_ECT			NUMERIC(10,0),    
	@P_CD_NOTIFY		NVARCHAR(7),    
	@P_DT_TO			NCHAR(8),    
	
	@P_NO_LC			NVARCHAR(20),    
	@P_NO_SO			NVARCHAR(20),    
	@P_REMARK1			NVARCHAR(100),    
	@P_REMARK2			NVARCHAR(100),    
	@P_REMARK3			NVARCHAR(100),    
	
	@P_REMARK4			NVARCHAR(100),    
	@P_REMARK5			NVARCHAR(100),    
	@P_DTS_INSERT		NVARCHAR(14),--등록일
	@P_ID_INSERT		NVARCHAR(15),--등록자
	@P_DTS_UPDATE		NVARCHAR(14),--수정자
	
	@P_ID_UPDATE		NVARCHAR(15),--수정일
	--@P_NO_TO			NVARCHAR(15),--통관번호
	--@P_NO_BL			NVARCHAR(15),--선적번호
	@P_NM_NOTIFY		NVARCHAR(100),--착하통지처
	@P_ADDR1_NOTIFY		NVARCHAR(100),--통지처주소1
	
	@P_ADDR2_NOTIFY		NVARCHAR(50),--통지처주소2
	@P_CD_CONSIGNEE		NVARCHAR(7),--수하인
	@P_NM_CONSIGNEE		NVARCHAR(50),--수하인명
	@P_ADDR1_CONSIGNEE	NVARCHAR(100),--수하인주소1
	@P_ADDR2_CONSIGNEE	NVARCHAR(100),--수하인주소2 
	@P_REMARK			TEXT,
	
	@P_NM_PARTNER		NVARCHAR(50),
	@P_ADDR1_PARTNER	NVARCHAR(100),
	@P_ADDR2_PARTNER	NVARCHAR(100),
	@P_NM_EXPORT		NVARCHAR(50),
	@P_ADDR1_EXPORT		NVARCHAR(100),
	@P_ADDR2_EXPORT		NVARCHAR(100),
	@P_COND_PRICE		NVARCHAR(3)
AS    
BEGIN
	--DECLARE @P_DTS_INSERT VARCHAR(14)    
	--SET @P_DTS_INSERT = REPLACE(REPLACE(REPLACE(CONVERT(VARCHAR(20), GETDATE(), 120), '-',''), ' ', ''),':','')    
    
	INSERT INTO TR_INVH(NO_INV,			CD_COMPANY,		DT_BALLOT,		CD_BIZAREA,		CD_SALEGRP,		NO_EMP,     
					    FG_LC,			CD_PARTNER,		CD_EXCH,		AM_EX,			DT_LOADING,		CD_ORIGIN,     
					    CD_AGENT,		CD_EXPORT,		CD_PRODUCT,		SHIP_CORP,		NM_VESSEL,		COND_TRANS,     
					    TP_TRANSPORT,	TP_TRANS,		TP_PACKING,		CD_WEIGHT,		GROSS_WEIGHT,	NET_WEIGHT,     
					    PORT_LOADING,	PORT_ARRIVER,	DESTINATION,	NO_SCT,			NO_ECT,			CD_CUST_IN,     
					    DT_TO,			NO_LC,			NO_SO,			REMARK1,		REMARK2,		REMARK3,     
					    REMARK4,		REMARK5,		DTS_INSERT,		ID_INSERT,		NM_NOTIFY,		ADDR1_NOTIFY,
					    ADDR2_NOTIFY,	CD_CONSIGNEE,	NM_CONSIGNEE,	ADDR1_CONSIGNEE,ADDR2_CONSIGNEE,REMARK,
					    NM_PARTNER,		ADDR1_PARTNER,	ADDR2_PARTNER,	NM_EXPORT,		ADDR1_EXPORT,	ADDR2_EXPORT,
						COND_PRICE)    
	VALUES(@P_NO_INV,		@P_CD_COMPANY,		@P_DT_BALLOT,		@P_CD_BIZAREA,  @P_CD_SALEGRP,		@P_NO_EMP,     
		   @P_FG_LC,		@P_CD_PARTNER,		@P_CD_EXCH,			@P_AM_EX,		@P_DT_LOADING,		@P_CD_ORIGIN,     
		   @P_CD_AGENT,		@P_CD_EXPORT,		@P_CD_PRODUCT,		@P_SHIP_CORP,	@P_NM_VESSEL,		@P_COND_TRANS,     
		   @P_TP_TRANSPORT, @P_TP_TRANS,		@P_TP_PACKING,		@P_CD_WEIGHT,	@P_GROSS_WEIGHT,	@P_NET_WEIGHT,     
		   @P_PORT_LOADING, @P_PORT_ARRIVER,	@P_DESTINATION,		@P_NO_SCT,		@P_NO_ECT,			@P_CD_NOTIFY,     
		   @P_DT_TO,		@P_NO_LC,			@P_NO_SO,			@P_REMARK1,		@P_REMARK2,			@P_REMARK3,     
		   @P_REMARK4,		@P_REMARK5,			@P_DTS_INSERT,		@P_ID_INSERT,	@P_NM_NOTIFY,		@P_ADDR1_NOTIFY,
		   @P_ADDR2_NOTIFY,	@P_CD_CONSIGNEE,	@P_NM_CONSIGNEE,	@P_ADDR1_CONSIGNEE,@P_ADDR2_CONSIGNEE,@P_REMARK,
		   @P_NM_PARTNER,	@P_ADDR1_PARTNER,	@P_ADDR2_PARTNER,	@P_NM_EXPORT,	@P_ADDR1_EXPORT,	@P_ADDR2_EXPORT,
		   @P_COND_PRICE)    
END
GO    


IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id(N'UP_TR_EXINV_UPDATE') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
DROP PROCEDURE UP_TR_EXINV_UPDATE
GO

/***********************************************************************    
**  System : 무역  
**  Sub System : 수출  
**  Page  : 송장작성  
**  Desc  : 송장작성 수정  
**  수정자 : 허성철    
************************************************************************/
 
CREATE PROCEDURE UP_TR_EXINV_UPDATE    
	@P_NO_INV			NVARCHAR(20),    
	@P_CD_COMPANY		NVARCHAR(7),    
	@P_DT_BALLOT		NCHAR(8),    
	@P_CD_BIZAREA		NVARCHAR(7),    
	@P_CD_SALEGRP		NVARCHAR(7),    
	@P_NO_EMP			NVARCHAR(10),    
	
	@P_FG_LC			NCHAR(3),    
	@P_CD_PARTNER		NVARCHAR(7),    
	@P_CD_EXCH			NVARCHAR(3),    
	@P_AM_EX			NUMERIC(17,4),    
	@P_DT_LOADING		NCHAR(8),    
	
	@P_CD_ORIGIN		NVARCHAR(3),    
	@P_CD_AGENT			NVARCHAR(7),    
	@P_CD_EXPORT		NVARCHAR(7),    
	@P_CD_PRODUCT		NVARCHAR(7),    
	@P_SHIP_CORP		NVARCHAR(7),    
	
	@P_NM_VESSEL		NVARCHAR(50),    
	@P_COND_TRANS		NVARCHAR(50),    
	@P_TP_TRANSPORT		NVARCHAR(3),    
	@P_TP_TRANS			NVARCHAR(3),    
	@P_TP_PACKING		NVARCHAR(3),    
	
	@P_CD_WEIGHT		NVARCHAR(3),    
	@P_GROSS_WEIGHT		NUMERIC(17,4),    
	@P_NET_WEIGHT		NUMERIC(17,4),    
	@P_PORT_LOADING		NVARCHAR(50),    
	@P_PORT_ARRIVER		NVARCHAR(50),    
	
	@P_DESTINATION		NVARCHAR(50),    
	@P_NO_SCT			NUMERIC(10,0),    
	@P_NO_ECT			NUMERIC(10,0),    
	@P_CD_NOTIFY		NVARCHAR(7),    
	@P_DT_TO			NCHAR(8),    
	
	@P_NO_LC			NVARCHAR(20),    
	@P_NO_SO			NVARCHAR(20),    
	@P_REMARK1			NVARCHAR(100),    
	@P_REMARK2			NVARCHAR(100),    
	@P_REMARK3			NVARCHAR(100),    
	
	@P_REMARK4			NVARCHAR(100),    
	@P_REMARK5			NVARCHAR(100),    
	@P_DTS_INSERT		NVARCHAR(14),--등록일
	@P_ID_INSERT		NVARCHAR(15),--등록자
	@P_DTS_UPDATE		NVARCHAR(14),--수정자
	
	@P_ID_UPDATE		NVARCHAR(15),--수정일
	--@P_NO_TO			NVARCHAR(15),--통관번호
	--@P_NO_BL			NVARCHAR(15),--선적번호
	@P_NM_NOTIFY		NVARCHAR(100),--착하통지처
	@P_ADDR1_NOTIFY		NVARCHAR(100),--통지처주소1
	
	@P_ADDR2_NOTIFY		NVARCHAR(50),--통지처주소2
	@P_CD_CONSIGNEE		NVARCHAR(7),--수하인
	@P_NM_CONSIGNEE		NVARCHAR(50),--수하인명
	@P_ADDR1_CONSIGNEE	NVARCHAR(100),--수하인주소1
	@P_ADDR2_CONSIGNEE	NVARCHAR(100),--수하인주소2
	@P_REMARK		    TEXT,
	
	@P_NM_PARTNER		NVARCHAR(50),
	@P_ADDR1_PARTNER	NVARCHAR(100),
	@P_ADDR2_PARTNER	NVARCHAR(100),
	@P_NM_EXPORT		NVARCHAR(50),
	@P_ADDR1_EXPORT		NVARCHAR(100),
	@P_ADDR2_EXPORT		NVARCHAR(100),
	@P_COND_PRICE		NVARCHAR(3)   
AS    
BEGIN
	--DECLARE @P_DTS_UPDATE VARCHAR(14)    
	--SET @P_DTS_UPDATE = REPLACE(REPLACE(REPLACE(CONVERT(VARCHAR(20), GETDATE(), 120), '-',''), ' ', ''),':','')    

	UPDATE TR_INVH 
	SET     
		DT_BALLOT		= @P_DT_BALLOT,  
		CD_BIZAREA		= @P_CD_BIZAREA,  
		CD_SALEGRP		= @P_CD_SALEGRP,     
		NO_EMP			= @P_NO_EMP,  
		FG_LC			= @P_FG_LC,  
		CD_PARTNER		= @P_CD_PARTNER,     
		CD_EXCH			= @P_CD_EXCH,  
		AM_EX			= @P_AM_EX,  
		DT_LOADING		= @P_DT_LOADING,     
		CD_ORIGIN		= @P_CD_ORIGIN,  
		CD_AGENT		= @P_CD_AGENT,  
		CD_EXPORT		= @P_CD_EXPORT,     
		CD_PRODUCT		= @P_CD_PRODUCT,  
		SHIP_CORP		= @P_SHIP_CORP,  
		NM_VESSEL		= @P_NM_VESSEL,     
		COND_TRANS		= @P_COND_TRANS,  
		TP_TRANSPORT    = @P_TP_TRANSPORT,  
		TP_TRANS		= @P_TP_TRANS,     
		TP_PACKING		= @P_TP_PACKING,  
		CD_WEIGHT		= @P_CD_WEIGHT,  
		GROSS_WEIGHT    = @P_GROSS_WEIGHT,     
		NET_WEIGHT		= @P_NET_WEIGHT,  
		PORT_LOADING    = @P_PORT_LOADING,  
		PORT_ARRIVER    = @P_PORT_ARRIVER,     
		DESTINATION		= @P_DESTINATION,  
		NO_SCT			= @P_NO_SCT,  
		NO_ECT			= @P_NO_ECT,     
		CD_CUST_IN		= @P_CD_NOTIFY,  
		DT_TO			= @P_DT_TO,  
		NO_LC			= @P_NO_LC,     
		NO_SO			= @P_NO_SO,  
		REMARK1			= @P_REMARK1,  
		REMARK2			= @P_REMARK2,     
		REMARK3			= @P_REMARK3,  
		REMARK4			= @P_REMARK4,  
		REMARK5			= @P_REMARK5,     
		DTS_UPDATE		= @P_DTS_UPDATE,  
		ID_UPDATE		= @P_ID_UPDATE,
		NM_NOTIFY		= @P_NM_NOTIFY,			--착하통지처
		ADDR1_NOTIFY	= @P_ADDR1_NOTIFY,		--통지처주소1
		ADDR2_NOTIFY	= @P_ADDR2_NOTIFY,		--통지처주소2
		CD_CONSIGNEE	= @P_CD_CONSIGNEE,		--수하인
		NM_CONSIGNEE	= @P_NM_CONSIGNEE,		--수하인명
		ADDR1_CONSIGNEE	= @P_ADDR1_CONSIGNEE,	--수하인주소1
		ADDR2_CONSIGNEE	= @P_ADDR2_CONSIGNEE,	--수하인주소2
		REMARK			= @P_REMARK,
		NM_PARTNER		= @P_NM_PARTNER,
		ADDR1_PARTNER	= @P_ADDR1_PARTNER,
		ADDR2_PARTNER	= @P_ADDR2_PARTNER,
		NM_EXPORT		= @P_NM_EXPORT,
		ADDR1_EXPORT	= @P_ADDR1_EXPORT,	
		ADDR2_EXPORT	= @P_ADDR2_EXPORT,
		COND_PRICE		= @P_COND_PRICE	
	WHERE NO_INV = @P_NO_INV    
	AND CD_COMPANY = @P_CD_COMPANY        
END
GO 


IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id(N'UP_TR_EXINV_COSTBF_SELECT'))
DROP PROCEDURE UP_TR_EXINV_COSTBF_SELECT
GO 

/**********************************************************************************************************  
 * 프로시저명: UP_TR_EXINV_COSTBF_SELECT
 * 관련페이지: 
 * 설      명: 판매비용등록 버튼 클릭시 넘길 인자값을 가져온다.
 * 작  성  자: 
 * EXEC UP_TR_EXINV_COSTBF_SELECT '1130','INV20080304-1000'
 *********************************************************************************************************/
 
CREATE PROCEDURE UP_TR_EXINV_COSTBF_SELECT  
	@P_CD_COMPANY	NVARCHAR(7),  
	@P_NO_INV		NVARCHAR(20)  
AS      
BEGIN
	SELECT INVH.DT_BALLOT, 
		INVH.CD_BIZAREA,
		(SELECT NM_BIZAREA FROM MA_BIZAREA WHERE INVH.CD_COMPANY = CD_COMPANY AND INVH.CD_BIZAREA = CD_BIZAREA) AS NM_BIZAREA,
		INVH.NO_EMP,
		EMP.NM_KOR AS NM_EMP,
		EMP.CD_DEPT,
		(SELECT NM_DEPT FROM MA_DEPT WHERE INVH.CD_COMPANY = CD_COMPANY AND EMP.CD_DEPT = CD_DEPT) AS NM_DEPT,
		SAL.CD_CC,
		(SELECT NM_CC FROM MA_CC WHERE INVH.CD_COMPANY = CD_COMPANY AND SAL.CD_CC = CD_CC) AS NM_CC
	FROM TR_INVH INVH
	LEFT OUTER JOIN MA_EMP EMP ON INVH.CD_COMPANY = EMP.CD_COMPANY AND INVH.NO_EMP = EMP.NO_EMP
	LEFT OUTER JOIN MA_SALEGRP SAL ON INVH.CD_COMPANY = SAL.CD_COMPANY AND INVH.CD_SALEGRP = SAL.CD_SALEGRP
	WHERE INVH.CD_COMPANY = @P_CD_COMPANY
	AND INVH.NO_INV = @P_NO_INV
END
GO