USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_CLAIMH_S]    Script Date: 2015-04-14 오전 8:31:11 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER PROCEDURE [NEOE].[SP_CZ_SA_CLAIMH_S]
(
	@P_CD_COMPANY		NVARCHAR(7),
	@P_NO_CLAIM			NVARCHAR(8),
	@P_NO_SO			NVARCHAR(20),
	@P_DT_CLAIM_FROM	NVARCHAR(8),
	@P_DT_CLAIM_TO		NVARCHAR(8),
	@P_CD_PARTNER		NVARCHAR(20),
	@P_CD_SUPPLIER		NVARCHAR(20),
	@P_NO_IMO			NVARCHAR(10),
	@P_TP_CAUSE			NVARCHAR(1),
	@P_CD_STATUS		NVARCHAR(1),
	@P_NO_EMP			NVARCHAR(10),
	@P_CD_SALEGRP		NVARCHAR(7),
	@P_TP_ITEM			NVARCHAR(3)
) 
AS
 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT CH.NO_CLAIM, 
       CH.NO_SO, 
	   SH.NO_CONTRACT,
	   CH.NO_IMO,
	   MH.NO_HULL,
	   MH.NM_VESSEL,
       CH.CD_PARTNER,
	   MP.LN_PARTNER, 
       CH.NO_SALES_EMP,
	   ME.NM_KOR AS NM_SALES_EMP, 
	   SH.DT_SO,
	   CH.CD_STATUS,
	   MC1.NM_SYSDEF AS NM_STATUS,
	   GW.ST_STAT AS CD_GW_STATUS,
	   MC2.NM_SYSDEF AS NM_GW_STATUS,
	   GW1.ST_STAT AS CD_GW_STATUS1,
	   MC6.NM_SYSDEF AS NM_GW_STATUS1,
       CH.TP_CLAIM,
	   MC3.NM_SYSDEF AS NM_CLAIM,
       CH.TP_CAUSE, 
	   MC4.NM_SYSDEF AS NM_CAUSE,
       CH.TP_ITEM, 
	   MC5.NM_SYSDEF AS NM_ITEM,
       CH.AM_ITEM_RCV, 
       CH.AM_ADD_RCV, 
       (CH.AM_ITEM_RCV + CH.AM_ADD_RCV) AS AM_TOTAL_RCV,
	   CH.AM_ITEM_PRO, 
       CH.AM_ADD_PRO, 
       (CH.AM_ITEM_PRO + CH.AM_ADD_PRO) AS AM_TOTAL_PRO, 
	   CH.AM_ITEM_CLS,
	   CH.AM_ADD_CLS,
	   (CH.AM_ITEM_CLS + CH.AM_ADD_CLS) AS AM_TOTAL_CLS,
       CH.NO_EMP,
	   ME1.NM_KOR AS NM_EMP,
       CH.DC_PROGRESS, 
       CH.DC_RESULT, 
       CH.DC_PREVENTION, 
       CH.DC_CLOSING, 
       CH.DT_INPUT,
	   CH.DT_EXPECTED_CLOSING_PRO,
	   CH.DT_EXPECTED_CLOSING,
	   CH.DT_CLOSING,
	   CH.CD_SUPPLIER_REWARD,
	   MC.NM_SYSDEF AS NM_SUPPLIER_REWARD,
	   CH.DC_SUPPLIER_REWARD,
	   CH.DC_CREDIT_NOTE,
	   CH.CD_CREDIT_EXCH,
	   CH.AM_CREDIT,
	   CH.TP_REASON,
	   MC7.NM_SYSDEF AS NM_REASON,
	   CH.TP_RETURN,
	   MC8.NM_SYSDEF AS NM_RETURN,
	   CH.TP_REQUEST,
	   MC9.NM_SYSDEF AS NM_REQUEST,
	   CH.DC_RECEIVE,
	   CH.IMAGE1,
	   CH.IMAGE2,
	   CH.IMAGE3,
	   CH.IMAGE4,
	   CH.IMAGE5,
	   CH.IMAGE6,
	   CH.DC_IMAGE1,
	   CH.DC_IMAGE2,
	   CH.DC_IMAGE3,
	   CH.DC_IMAGE4,
	   CH.DC_IMAGE5,
	   CH.DC_IMAGE6,
	   SH.CD_SALEGRP,
	   SG.NM_SALEGRP,
	   CL.CD_SUPPLIER,
	   MP1.LN_PARTNER AS NM_SUPPLIER,
	   GW.APP_DOC_ID,
	   GW1.APP_DOC_ID AS APP_DOC_ID1,
	   CH.DC_PACK_SIZE,
	   CH.QT_PACK_WEIGHT
FROM CZ_SA_CLAIMH CH
LEFT JOIN (SELECT CL.CD_COMPANY, CL.NO_CLAIM, 
		   		  MAX(CL.CD_SUPPLIER) AS CD_SUPPLIER 
		   FROM CZ_SA_CLAIML CL
		   GROUP BY CL.CD_COMPANY, CL.NO_CLAIM) CL
ON CL.CD_COMPANY = CH.CD_COMPANY AND CL.NO_CLAIM = CH.NO_CLAIM 
LEFT JOIN SA_SOH SH ON SH.CD_COMPANY = CH.CD_COMPANY AND SH.NO_SO = CH.NO_SO
LEFT JOIN CZ_MA_HULL MH ON MH.NO_IMO = CH.NO_IMO
LEFT JOIN MA_PARTNER MP ON MP.CD_COMPANY = CH.CD_COMPANY AND MP.CD_PARTNER = CH.CD_PARTNER
LEFT JOIN MA_PARTNER MP1 ON MP1.CD_COMPANY = CL.CD_COMPANY AND MP1.CD_PARTNER = CL.CD_SUPPLIER
LEFT JOIN MA_EMP ME ON ME.CD_COMPANY = CH.CD_COMPANY AND ME.NO_EMP = CH.NO_SALES_EMP
LEFT JOIN MA_EMP ME1 ON ME1.CD_COMPANY = CH.CD_COMPANY AND ME1.NO_EMP = CH.NO_EMP
LEFT JOIN (SELECT CD_COMPANY, NO_EMP,
				  MAX(CD_SALEGRP) AS CD_SALEGRP 
		   FROM MA_USER
		   GROUP BY CD_COMPANY, NO_EMP) MU 
ON MU.CD_COMPANY = ME.CD_COMPANY AND MU.NO_EMP = ME.NO_EMP
LEFT JOIN MA_SALEGRP SG ON SG.CD_COMPANY = MU.CD_COMPANY AND SG.CD_SALEGRP = MU.CD_SALEGRP
LEFT JOIN FI_GWDOCU GW ON GW.CD_COMPANY = 'K100' AND GW.CD_PC = '010000' AND GW.NO_DOCU = CH.CD_COMPANY + '-' + CH.NO_CLAIM + '-' + CH.CD_STATUS
LEFT JOIN FI_GWDOCU GW1 ON GW1.CD_COMPANY = 'K100' AND GW1.CD_PC = '010000' AND GW1.NO_DOCU = CH.CD_COMPANY + '-' + CH.NO_CLAIM + '-CDT'
LEFT JOIN MA_CODEDTL MC ON MC.CD_COMPANY = CH.CD_COMPANY AND MC.CD_FIELD = 'CZ_SA00036' AND MC.CD_SYSDEF = CH.CD_SUPPLIER_REWARD
LEFT JOIN MA_CODEDTL MC1 ON MC1.CD_COMPANY = CH.CD_COMPANY AND MC1.CD_FIELD = 'CZ_SA00004' AND MC1.CD_SYSDEF = CH.CD_STATUS
LEFT JOIN MA_CODEDTL MC2 ON MC2.CD_COMPANY = GW.CD_COMPANY AND MC2.CD_FIELD = 'PU_C000065' AND MC2.CD_SYSDEF = GW.ST_STAT
LEFT JOIN MA_CODEDTL MC3 ON MC3.CD_COMPANY = CH.CD_COMPANY AND MC3.CD_FIELD = 'CZ_SA00001' AND MC3.CD_SYSDEF = CH.TP_CLAIM
LEFT JOIN MA_CODEDTL MC4 ON MC4.CD_COMPANY = CH.CD_COMPANY AND MC4.CD_FIELD = 'CZ_SA00002' AND MC4.CD_SYSDEF = CH.TP_CAUSE
LEFT JOIN MA_CODEDTL MC5 ON MC5.CD_COMPANY = CH.CD_COMPANY AND MC5.CD_FIELD = 'CZ_SA00003' AND MC5.CD_SYSDEF = CH.TP_ITEM
LEFT JOIN MA_CODEDTL MC6 ON MC6.CD_COMPANY = GW1.CD_COMPANY AND MC6.CD_FIELD = 'PU_C000065' AND MC6.CD_SYSDEF = GW1.ST_STAT
LEFT JOIN MA_CODEDTL MC7 ON MC7.CD_COMPANY = CH.CD_COMPANY AND MC7.CD_FIELD = 'CZ_SA00048' AND MC7.CD_SYSDEF = CH.TP_REASON
LEFT JOIN MA_CODEDTL MC8 ON MC8.CD_COMPANY = CH.CD_COMPANY AND MC8.CD_FIELD = 'CZ_SA00050' AND MC8.CD_SYSDEF = CH.TP_RETURN
LEFT JOIN MA_CODEDTL MC9 ON MC9.CD_COMPANY = CH.CD_COMPANY AND MC9.CD_FIELD = 'CZ_SA00049' AND MC9.CD_SYSDEF = CH.TP_REQUEST
WHERE CH.CD_COMPANY = @P_CD_COMPANY 
AND ((ISNULL(@P_NO_CLAIM, '') = '' AND CH.DT_INPUT BETWEEN @P_DT_CLAIM_FROM AND @P_DT_CLAIM_TO) OR CH.NO_CLAIM = @P_NO_CLAIM)
AND (ISNULL(@P_NO_SO, '') = '' OR CH.NO_SO LIKE @P_NO_SO + '%')
AND (ISNULL(@P_CD_PARTNER, '') = '' OR CH.CD_PARTNER = @P_CD_PARTNER)
AND (ISNULL(@P_CD_SUPPLIER, '') = '' OR EXISTS (SELECT 1 FROM CZ_SA_CLAIML 
												WHERE CD_COMPANY = CH.CD_COMPANY 
												AND NO_CLAIM = CH.NO_CLAIM 
												AND CD_SUPPLIER = @P_CD_SUPPLIER))
AND (ISNULL(@P_NO_IMO, '') = '' OR CH.NO_IMO = @P_NO_IMO)
AND (ISNULL(@P_TP_CAUSE, '') = '' OR CH.TP_CAUSE = @P_TP_CAUSE)
AND (ISNULL(@P_CD_STATUS, '') = '' OR CH.CD_STATUS = @P_CD_STATUS)
AND (ISNULL(@P_NO_EMP, '') = '' OR CH.NO_EMP = @P_NO_EMP)
AND (ISNULL(@P_CD_SALEGRP, '') = '' OR SG.CD_SALEGRP = @P_CD_SALEGRP)
AND (ISNULL(@P_TP_ITEM, '') = '' OR CH.TP_ITEM = @P_TP_ITEM)

GO