USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_CLAIMH_S]    Script Date: 2015-04-14 오전 8:31:11 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER PROCEDURE [NEOE].[SP_CZ_SA_CLAIMH_D]
(
	@P_CD_COMPANY			NVARCHAR(7),
	@P_NO_CLAIM				NVARCHAR(8)
) 
AS
	DELETE FROM CZ_SA_CLAIMH
	WHERE CD_COMPANY = @P_CD_COMPANY
	AND NO_CLAIM = @P_NO_CLAIM

	DELETE FROM CZ_SA_CLAIML
	WHERE CD_COMPANY = @P_CD_COMPANY
	AND NO_CLAIM = @P_NO_CLAIM

	DELETE FROM FI_GWDOCU
	WHERE CD_COMPANY = 'K100'
	AND CD_PC = '010000'
	AND NO_DOCU LIKE @P_CD_COMPANY + '-' + @P_NO_CLAIM + '%'
GO