USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_PR_WO_MNG_AUTO_INSP_D]    Script Date: 2017-01-05 오후 5:48:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_PR_WO_MNG_AUTO_INSP_D]          
(
	@P_CD_COMPANY	NVARCHAR(7),
	@P_NO_WO		NVARCHAR(20),
	@P_NO_LINE		NUMERIC(5, 0),
	@P_SEQ_WO_FROM	NUMERIC(5, 0),
	@P_SEQ_WO_TO	NUMERIC(5, 0)
)  
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

DELETE WI
FROM CZ_PR_WO_INSP WI
WHERE WI.CD_COMPANY = @P_CD_COMPANY
AND WI.NO_WO = @P_NO_WO
AND WI.NO_LINE = @P_NO_LINE
AND WI.SEQ_WO >= @P_SEQ_WO_FROM 
AND WI.SEQ_WO <= @P_SEQ_WO_TO

GO