USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_PR_WO_MNGDH_S]    Script Date: 2021-03-02 오전 10:51:36 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER PROCEDURE [NEOE].[SP_CZ_PR_WO_MNGDH_S]
(
	@P_CD_COMPANY		NVARCHAR(7),
	@P_NO_WO			NVARCHAR(20)
) 
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT WD.NO_WO,
	   WD.SEQ_WO,
	   WD.DT_NO_ID,
	   WD.NO_SEQ,
	   WD.NO_ID,
	   WD.NO_ID_OLD,
	   WD.NO_HEAT,
	   (CASE WHEN EXISTS (SELECT 1 
						  FROM CZ_PR_WO_INSP WI
						  WHERE WI.CD_COMPANY = WD.CD_COMPANY
						  AND WI.NO_WO = WD.NO_WO
						  AND WI.SEQ_WO = WD.SEQ_WO
						  AND WI.NO_INSP = -1) THEN 'Y' ELSE 'N' END) AS YN_BAD
FROM CZ_PR_WO_REQ_D WD
WHERE WD.CD_COMPANY = @P_CD_COMPANY
AND WD.NO_WO = @P_NO_WO
ORDER BY WD.SEQ_WO

GO