USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_PR_WO_MNG_I]    Script Date: 2017-01-05 오후 5:48:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_PR_WO_MNG_I]          
(
	@P_CD_COMPANY	NVARCHAR(7),
	@P_NO_WO		NVARCHAR(20),
	@P_FG_SERNO		NVARCHAR(4),
	@P_ID_INSERT	NVARCHAR(15)
)  
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

DECLARE @V_ERRMSG NVARCHAR(255)   -- ERROR 메시지

BEGIN TRAN SP_CZ_PR_WO_MNG_I
BEGIN TRY

IF EXISTS (SELECT 1 
		   FROM PR_WO WO
		   WHERE WO.CD_COMPANY = @P_CD_COMPANY
		   AND WO.NO_WO = @P_NO_WO
		   AND WO.QT_ITEM > 9999)
BEGIN
	SET @V_ERRMSG = '수량 10,000개 이상 생산투입 할 수 없습니다.'
    GOTO ERROR
END

DECLARE @V_NO_YEAR NVARCHAR(1),
		@V_NO_MONTH NVARCHAR(1)

SET @V_NO_YEAR = CHAR(((YEAR(GETDATE()) - 2012) % 26) + 65)
SET @V_NO_MONTH = CHAR(MONTH(GETDATE()) - 1 + 65)

IF @P_FG_SERNO = '999'
BEGIN
	;WITH A AS
	(
		SELECT WO.CD_COMPANY,
			   WO.NO_WO,
			   WO.CD_ITEM,
			   WO.QT_ITEM AS QT_TOTAL,
			   1 AS SEQ_WO,
			   (ISNULL((SELECT MAX(NO_SEQ) 
				        FROM CZ_PR_WO_REQ_D
				        WHERE CD_COMPANY = @P_CD_COMPANY
				        AND NO_YEAR = @V_NO_YEAR
				        AND NO_MONTH = @V_NO_MONTH), 0) + 1) AS NO_SEQ
		FROM PR_WO WO
		WHERE WO.CD_COMPANY = @P_CD_COMPANY
		AND WO.NO_WO = @P_NO_WO
	    UNION ALL
		SELECT A.CD_COMPANY,
			   A.NO_WO,
			   A.CD_ITEM,		   
			   A.QT_TOTAL,
			   A.SEQ_WO + 1 AS SEQ_WO,
			   CONVERT(NUMERIC, A.NO_SEQ) + 1 AS NO_SEQ
		FROM A
		WHERE A.CD_COMPANY = @P_CD_COMPANY
		AND A.NO_WO = @P_NO_WO
		AND A.SEQ_WO < A.QT_TOTAL
	)
	INSERT INTO CZ_PR_WO_REQ_D
	(
		CD_COMPANY,
		NO_WO,
		SEQ_WO,
		CD_ITEM,
		DT_NO_ID,
		NO_YEAR,
		NO_MONTH,
		NO_PREFIX,
		NO_SEQ,
		NO_ID,
		CD_QR,
		ID_INSERT,
		DTS_INSERT
	)
	SELECT A.CD_COMPANY,
		   A.NO_WO,
		   A.SEQ_WO,
		   A.CD_ITEM,
		   CONVERT(CHAR(6), GETDATE(), 112) AS DT_NO_ID,
		   @V_NO_YEAR AS NO_YEAR,
		   @V_NO_MONTH AS NO_MONTH,
		   CHAR(A.NO_SEQ / 10000 + 65) AS NO_PREFIX,
		   A.NO_SEQ,
		   (@V_NO_YEAR + @V_NO_MONTH + CHAR(A.NO_SEQ / 10000 + 65) + FORMAT(A.NO_SEQ % 10000, '0000')) AS NO_ID,
		   (@V_NO_YEAR + @V_NO_MONTH + CHAR(A.NO_SEQ / 10000 + 65) + FORMAT(A.NO_SEQ % 10000, '0000')) AS CD_QR,
		   @P_ID_INSERT AS ID_INSERT,
		   NEOE.SF_SYSDATE(GETDATE()) AS DTS_INSERT
	FROM A
	OPTION(MAXRECURSION 0)
END

COMMIT TRAN SP_CZ_PR_WO_MNG_I

END TRY
BEGIN CATCH
	ROLLBACK TRAN SP_CZ_PR_WO_MNG_I
	SELECT @V_ERRMSG = ERROR_MESSAGE()
	GOTO ERROR
END CATCH

RETURN
ERROR: RAISERROR(@V_ERRMSG, 16, 1)

GO