USE [NEOE]
GO
/****** Object:  StoredProcedure [NEOE].[SP_CZ_PR_WO_MNG_U1]    Script Date: 2021-07-12 오후 1:46:06 ******/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_PR_WO_MNG_U1]
(
	@P_CD_COMPANY	NVARCHAR(7),
	@P_CD_PLANT		NVARCHAR(7),
	@P_NO_WO		NVARCHAR(20),
	@P_DC_RMK		NVARCHAR(500),
	@P_ID_UPDATE	NVARCHAR(15),
	@P_CD_USERDEF1	NVARCHAR(20),
	@P_CD_USERDEF2	NVARCHAR(4),
	@P_CD_USERDEF3	NVARCHAR(4),
	@P_CD_USERDEF4	NVARCHAR(4),
	@P_CD_USERDEF5	NVARCHAR(4),
	@P_NO_LOT		NVARCHAR(100),
	@P_DT_LIMIT		NVARCHAR(8),
	@P_NUM_USERDEF1 NUMERIC(17, 4),
	@P_NUM_USERDEF2 NUMERIC(17, 4),
	@P_DT_CLOSE		NVARCHAR(8),
	@P_DC_RMK2		NVARCHAR(500),
	@P_NO_HEAT		NVARCHAR(200)
)
AS

DECLARE @ERRMSG NVARCHAR(255)

DECLARE @V_DTS_UPDATE	NVARCHAR(16)
SELECT	@V_DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE())

UPDATE PR_WO
SET DC_RMK = @P_DC_RMK,
	CD_USERDEF1 = @P_CD_USERDEF1,
	CD_USERDEF2 = @P_CD_USERDEF2,
	CD_USERDEF3 = @P_CD_USERDEF3,
	CD_USERDEF4 = @P_CD_USERDEF4,
	CD_USERDEF5 = @P_CD_USERDEF5,
	NO_LOT = @P_NO_LOT,
	DT_LIMIT = @P_DT_LIMIT,
	NUM_USERDEF1 = @P_NUM_USERDEF1,
	NUM_USERDEF2 = @P_NUM_USERDEF2,
	DT_CLOSE = @P_DT_CLOSE,
	DC_RMK2 = @P_DC_RMK2,
	TXT_USERDEF1 = @P_NO_HEAT,
	ID_UPDATE = @P_ID_UPDATE,
	DTS_UPDATE = @V_DTS_UPDATE
WHERE CD_COMPANY = @P_CD_COMPANY
AND	CD_PLANT = @P_CD_PLANT
AND	NO_WO = @P_NO_WO
            
IF (@@ERROR <> 0 ) BEGIN SELECT @ERRMSG = '[UP_PR_WO_MNG_U]PR_WO TABLE UPDATE ERROR.' GOTO ERROR END            

RETURN
ERROR: RAISERROR (@ERRMSG, 18 , 1)
RETURN