USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_PR_WO_MNG_INSP_XML]    Script Date: 2017-01-05 오후 5:48:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_PR_WO_MNG_INSP_XML]          
(
	@P_XML			XML, 
	@P_ID_USER		NVARCHAR(10), 
    @DOC			INT = NULL
)  
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

EXEC SP_XML_PREPAREDOCUMENT @DOC OUTPUT, @P_XML 

-- ================================================== DELETE
DELETE A 
FROM CZ_PR_WO_INSP A 
JOIN OPENXML (@DOC, '/XML/D', 2) 
        WITH (CD_COMPANY NVARCHAR(7),
			  NO_WO		 NVARCHAR(20),
			  NO_LINE	 NUMERIC(5, 0),
			  SEQ_WO	 NUMERIC(5, 0),
			  NO_INSP	 NUMERIC(4, 0)) B 
ON A.CD_COMPANY = B.CD_COMPANY
AND A.NO_WO = B.NO_WO
AND A.NO_LINE = B.NO_LINE
AND A.SEQ_WO = B.SEQ_WO
AND A.NO_INSP = B.NO_INSP

-- ================================================== UPDATE
UPDATE A 
SET A.NO_DATA1 = B.NO_DATA1, 
    A.NO_DATA2 = B.NO_DATA2, 
    A.NO_DATA3 = B.NO_DATA3, 
    A.NO_DATA4 = B.NO_DATA4, 
    A.NO_DATA5 = B.NO_DATA5,
    A.NO_HEAT = B.NO_HEAT,
	A.YN_MARKING = B.YN_MARKING,
    A.ID_UPDATE = @P_ID_USER, 
    A.DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE())
FROM CZ_PR_WO_INSP A 
JOIN OPENXML (@DOC, '/XML/U', 2) 
        WITH (CD_COMPANY NVARCHAR(7),
		      NO_WO	     NVARCHAR(20),
		      NO_LINE	 NUMERIC(5, 0),
		      SEQ_WO	 NUMERIC(5, 0),
		      NO_INSP	 NUMERIC(4, 0),
			  NO_DATA1   NUMERIC(18, 4),
			  NO_DATA2   NUMERIC(18, 4),
			  NO_DATA3   NUMERIC(18, 4),
			  NO_DATA4   NUMERIC(18, 4),
			  NO_DATA5   NUMERIC(18, 4),
			  NO_HEAT	 NVARCHAR(20),
			  YN_MARKING NVARCHAR(1)) B 
ON A.CD_COMPANY = B.CD_COMPANY
AND A.NO_WO = B.NO_WO
AND A.NO_LINE = B.NO_LINE
AND A.SEQ_WO = B.SEQ_WO
AND A.NO_INSP = B.NO_INSP

INSERT INTO CZ_PR_WO_INSP
(
	CD_COMPANY,
	NO_WO,
	NO_LINE,
	SEQ_WO,
	NO_INSP,
	DT_INSP,
	NO_EMP,
	NO_DATA1,
	NO_DATA2,
	NO_DATA3,
	NO_DATA4,
	NO_DATA5,
	NO_HEAT,
	YN_MARKING,
	DTS_INSERT,
	ID_INSERT
)
SELECT A.CD_COMPANY,
	   A.NO_WO,
	   A.NO_LINE,
	   A.SEQ_WO,
	   A.NO_INSP,
	   CONVERT(CHAR(8), GETDATE(), 112) AS DT_INSP,
	   @P_ID_USER AS NO_EMP,
	   A.NO_DATA1,
	   A.NO_DATA2,
	   A.NO_DATA3,
	   A.NO_DATA4,
	   A.NO_DATA5,
	   A.NO_HEAT,
	   A.YN_MARKING,
	   NEOE.SF_SYSDATE(GETDATE()) AS DTS_INSERT,
	   @P_ID_USER AS ID_INSERT
FROM OPENXML (@DOC, '/XML/U', 2) 
        WITH (CD_COMPANY NVARCHAR(7),
		      NO_WO	     NVARCHAR(20),
		      NO_LINE	 NUMERIC(5, 0),
		      SEQ_WO	 NUMERIC(5, 0),
		      NO_INSP	 NUMERIC(4, 0),
			  NO_DATA1   NUMERIC(18, 4),
			  NO_DATA2   NUMERIC(18, 4),
			  NO_DATA3   NUMERIC(18, 4),
			  NO_DATA4   NUMERIC(18, 4),
			  NO_DATA5   NUMERIC(18, 4),
			  NO_HEAT	 NVARCHAR(20),
			  YN_MARKING NVARCHAR(1)) A
WHERE NOT EXISTS (SELECT 1 
				  FROM CZ_PR_WO_INSP WI
				  WHERE WI.CD_COMPANY = A.CD_COMPANY
				  AND WI.NO_WO = A.NO_WO
				  AND WI.NO_LINE = A.NO_LINE
				  AND WI.SEQ_WO = A.SEQ_WO
				  AND WI.NO_INSP = A.NO_INSP)

GO