USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_PR_WO_MNG_D]    Script Date: 2017-01-05 오후 5:48:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_PR_WO_MNG_D]          
(
	@P_CD_COMPANY	NVARCHAR(7),
	@P_NO_WO		NVARCHAR(20)
)  
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

DECLARE @V_ERRMSG	   VARCHAR(255) -- ERROR 메시지

BEGIN TRAN SP_CZ_PR_WO_MNG_D
BEGIN TRY

IF EXISTS (SELECT 1 
		   FROM PR_WO_ROUT WR
		   WHERE WR.CD_COMPANY = @P_CD_COMPANY
		   AND WR.NO_WO = @P_NO_WO
		   AND WR.QT_WORK > 0)
BEGIN
	SELECT @V_ERRMSG = '진행중인 건은 생산투입 취소 할 수 없습니다.'                     
	GOTO ERROR	
END

IF EXISTS (SELECT 1 
		   FROM CZ_PR_WO_INSP
		   WHERE CD_COMPANY = @P_CD_COMPANY
		   AND NO_WO = @P_NO_WO
		   AND NO_INSP IN (994, 995))
BEGIN
	SELECT @V_ERRMSG = '외주 발주 등록된 건은 생산투입 취소 할 수 없습니다.'                     
	GOTO ERROR	
END

IF EXISTS (SELECT 1 
		   FROM PR_WO WO
		   LEFT JOIN CZ_PR_WO_REQ_D WD ON WD.CD_COMPANY = WO.CD_COMPANY AND WD.NO_WO = WO.NO_WO
		   WHERE WO.CD_COMPANY = @P_CD_COMPANY
		   AND WO.NO_WO = @P_NO_WO
		   AND EXISTS (SELECT 1 
					   FROM CZ_PR_MATCHING_DATA MD
					   WHERE MD.CD_COMPANY = WD.CD_COMPANY
					   AND (MD.NO_ID = WD.NO_ID OR MD.NO_ID_C = WD.NO_ID)))
BEGIN
	SELECT @V_ERRMSG = '현합 진행 중인 건은 생산투입 취소 할 수 없습니다.'                     
	GOTO ERROR	
END

IF EXISTS (SELECT 1 
		   FROM PR_WO WO
		   LEFT JOIN CZ_PR_WO_REQ_D WD ON WD.CD_COMPANY = WO.CD_COMPANY AND WD.NO_WO = WO.NO_WO
		   WHERE WO.CD_COMPANY = @P_CD_COMPANY
		   AND WO.NO_WO = @P_NO_WO
		   AND EXISTS (SELECT 1 
					   FROM CZ_PR_ASSEMBLING_DATA AD
					   WHERE AD.CD_COMPANY = WD.CD_COMPANY
					   AND AD.CD_PLANT = WO.CD_PLANT
					   AND (AD.NO_ID = WD.NO_ID OR AD.NO_ID_C = WD.NO_ID)))
BEGIN
	SELECT @V_ERRMSG = '조립 진행 중인 건은 생산투입 취소 할 수 없습니다.'                     
	GOTO ERROR	
END

DELETE 
FROM CZ_PR_WO_REQ_D
WHERE CD_COMPANY = @P_CD_COMPANY
AND NO_WO = @P_NO_WO

DELETE 
FROM CZ_PR_WO_INSP
WHERE CD_COMPANY = @P_CD_COMPANY
AND NO_WO = @P_NO_WO	

COMMIT TRAN SP_CZ_PR_WO_MNG_D

END TRY
BEGIN CATCH
	ROLLBACK TRAN SP_CZ_PR_WO_MNG_D
	SELECT @V_ERRMSG = ERROR_MESSAGE()
	GOTO ERROR
END CATCH

RETURN
ERROR: 
RAISERROR(@V_ERRMSG, 16, 1)
ROLLBACK TRAN SP_CZ_PR_WO_MNG_D

GO