USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_IV_RPTL_S]    Script Date: 2015-11-12 오후 7:35:29 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




ALTER PROCEDURE [NEOE].[SP_CZ_SA_IV_RPTL_S]  
(
    @P_CD_COMPANY			NVARCHAR(7),
	@P_NO_IV				NVARCHAR(20),
	@P_CD_CC				NVARCHAR(12),
	@P_YN_CONFIRM			NVARCHAR(1) = 'N',
	@P_YN_CHARGE			NVARCHAR(1) = 'N',
	@P_YN_SALE_ACCT			NVARCHAR(1) = 'N'
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT IL.NO_IV,
	   IL.CD_CC,
	   IL.NO_LINE,
	   IL.NO_DSP,
	   IL.CD_ITEM_PARTNER,
	   IL.NM_ITEM_PARTNER,
	   IL.CD_ITEM,
	   MI.NM_ITEM,
	   (CASE WHEN IL.YN_RETURN = 'Y' THEN -ISNULL(IL.QT_IV, 0) ELSE ISNULL(IL.QT_IV, 0) END) AS QT_IV,
	   (CASE WHEN IL.YN_RETURN = 'Y' THEN -ISNULL(IL.UM_SO, 0) ELSE ISNULL(IL.UM_SO, 0) END) AS UM_SO,
	   (CASE WHEN IL.YN_RETURN = 'Y' THEN -ISNULL(IL.UM_IV, 0) ELSE ISNULL(IL.UM_IV, 0) END) AS UM_IV,
	   (CASE WHEN IL.YN_RETURN = 'Y' THEN -(ISNULL(IL.UM_SO, 0) * ISNULL(IL.QT_IV, 0)) ELSE (ISNULL(IL.UM_SO, 0) * ISNULL(IL.QT_IV, 0)) END) AS AM_SO,
	   (CASE WHEN IL.YN_RETURN = 'Y' THEN -(ISNULL(IL.UM_IV, 0) * ISNULL(IL.QT_IV, 0)) ELSE (ISNULL(IL.UM_IV, 0) * ISNULL(IL.QT_IV, 0)) END) AS AM_IV,
	   IL.NO_SO,
	   IL.NO_SOLINE,
	   IL.CD_PJT
FROM SA_IVH IH
JOIN (SELECT IL.CD_COMPANY, IL.CD_PLANT, IL.YN_RETURN, IL.CD_CC, IL.NO_IV, IL.NO_LINE, IL.CD_ITEM, 
	  		 (CASE WHEN IL.CD_ITEM LIKE 'SD%' THEN NULL ELSE QL.NO_DSP END) AS NO_DSP,
	  		 (CASE WHEN IL.CD_ITEM LIKE 'SD%' THEN NULL ELSE QL.CD_ITEM_PARTNER END) AS CD_ITEM_PARTNER,
	  		 (CASE WHEN IL.CD_ITEM LIKE 'SD%' THEN NULL ELSE QL.NM_ITEM_PARTNER END) AS NM_ITEM_PARTNER,
	  		 (CASE WHEN IL.CD_ITEM LIKE 'SD%' AND ISNULL(IL.QT_CLS, 0) = 0 THEN 1 ELSE IL.QT_CLS END) AS QT_IV,
	  		 (CASE WHEN IL.CD_ITEM LIKE 'SD%' THEN IL.UM_ITEM_CLS 
	  		 								  ELSE (CASE WHEN QL.NO_FILE IS NULL THEN ROUND(ISNULL(SL.UM_SO, 0) * ISNULL(SH.RT_EXCH, 0), 2) 
	  		 																	 ELSE SL.UM_KR_S END) END) AS UM_SO,
	  		 IL.UM_ITEM_CLS AS UM_IV,
	  		 IL.NO_SO,
	  		 IL.NO_SOLINE,
	  		 IL.CD_PJT
	  FROM SA_IVL IL
	  LEFT JOIN SA_SOL SL ON SL.CD_COMPANY = IL.CD_COMPANY AND SL.NO_SO = IL.NO_SO AND SL.SEQ_SO = IL.NO_SOLINE
	  LEFT JOIN SA_SOH SH ON SH.CD_COMPANY = SL.CD_COMPANY AND SH.NO_SO = SL.NO_SO
	  LEFT JOIN CZ_SA_QTNL QL ON QL.CD_COMPANY = IL.CD_COMPANY AND QL.NO_FILE = IL.NO_SO AND QL.NO_LINE = IL.NO_SOLINE
	  WHERE (@P_YN_CHARGE = 'Y' OR (IL.CD_ITEM NOT LIKE 'SD%' OR ISNULL(IL.QT_CLS, 0) <> 0))) IL
ON IL.CD_COMPANY = IH.CD_COMPANY AND IL.NO_IV = IH.NO_IV
LEFT JOIN (SELECT FD.CD_COMPANY, FD.NO_MDOCU,
		   		  MAX(FD.NO_DOCU) AS NO_DOCU,
		   		  MAX(FD.ST_DOCU) AS ST_DOCU 
		   FROM FI_DOCU FD
		   LEFT JOIN FI_ACCTCODE FA ON FA.CD_COMPANY = FD.CD_COMPANY AND FA.CD_ACCT = FD.CD_ACCT
		   WHERE (@P_YN_SALE_ACCT = 'N' OR (FA.CD_ACGRP = '510' AND FA.YN_FILL = 'Y'))
		   GROUP BY FD.CD_COMPANY, FD.NO_MDOCU) FD 
ON FD.CD_COMPANY = IH.CD_COMPANY AND FD.NO_MDOCU = IH.NO_IV
LEFT JOIN MA_PITEM MI ON MI.CD_COMPANY = IL.CD_COMPANY AND MI.CD_PLANT = IL.CD_PLANT AND MI.CD_ITEM = IL.CD_ITEM
WHERE IH.CD_COMPANY = @P_CD_COMPANY
AND IH.NO_IV = @P_NO_IV
AND IL.CD_CC = @P_CD_CC
AND (@P_YN_CONFIRM = 'N' OR FD.ST_DOCU = '2')
AND (@P_YN_SALE_ACCT = 'N' OR FD.NO_DOCU IS NOT NULL)
ORDER BY IH.CD_COMPANY, IH.NO_IV, IL.CD_CC, IL.NO_LINE

GO