USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_IV_RPTR_S]    Script Date: 2015-11-12 오후 7:35:39 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




ALTER PROCEDURE [NEOE].[SP_CZ_SA_IV_RPTR_S]  
(
    @P_CD_COMPANY			NVARCHAR(7),
	@P_NO_IV				NVARCHAR(20),
	@P_CD_CC				NVARCHAR(12),
	@P_YN_CONFIRM			NVARCHAR(1) = 'N',
	@P_YN_CHARGE			NVARCHAR(1) = 'N'
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

DECLARE @P_AM_FSIZE		NUMERIC(3, 0)   -- 소수점    

IF @P_CD_COMPANY = 'S100'
	SET @P_AM_FSIZE = 2
ELSE
	SET @P_AM_FSIZE = 0

SELECT IH.CD_COMPANY,
	   IH.NO_IV,
	   IL.NO_LINE,
	   IL.CD_CC,
	   IL.NO_DSP,
	   IL.CD_ITEM_PARTNER,
	   IL.NM_ITEM_PARTNER,
	   IL.CD_ITEM,
	   MI.NM_ITEM,
	   ISNULL(IL.QT_IV, 0) AS QT_IV,
	   ISNULL(IL.UM_PO, 0) AS UM_PO,
	   ISNULL(IL.UM_IV, 0) AS UM_IV,
	   (ISNULL(IL.QT_IV, 0) * ISNULL(IL.UM_PO, 0)) AS AM_PO,
	   (ISNULL(IL.QT_IV, 0) * ISNULL(IL.UM_IV, 0)) AS AM_IV,
	   (ISNULL(IL.QT_IV, 0) * ISNULL(IL.UM_CHARGE, 0)) AS AM_CHARGE,
	   IL.NO_PO,
	   IL.NO_POLINE
FROM SA_IVH IH
LEFT JOIN (SELECT IL.CD_COMPANY, IL.CD_PLANT, IL.NO_IV, IL.NO_LINE, IL.CD_ITEM, IL.CD_CC, 
		   		  QL.NO_DSP, QL.CD_ITEM_PARTNER, QL.NM_ITEM_PARTNER,
		   		  ((CASE WHEN IL.YN_RETURN = 'Y' THEN -1 ELSE 1 END) * (CASE WHEN (ISNULL(SL.QT_SO, 0) - ISNULL(SB.QT_STOCK, 0)) = 0 THEN ISNULL(GL.QT_GIR, 0)
		   																															 ELSE ISNULL(GL.QT_GIR, 0) * (ISNULL(PL.QT_PO, 0) / (ISNULL(SL.QT_SO, 0) - ISNULL(SB.QT_STOCK, 0))) END)) AS QT_IV,
		   		  PL.NO_PO,
		   		  PL.NO_LINE AS NO_POLINE,

		   		  ISNULL(PL.UM, 0) AS UM_PO,
		   		  ISNULL(PV.UM_IV, 0) AS UM_IV,
				  ISNULL(PV1.UM_CHARGE, 0) AS UM_CHARGE
		   FROM SA_IVL IL
		   LEFT JOIN (SELECT QO.CD_COMPANY, QO.NO_IO, QO.NO_IOLINE,
		   					 (ISNULL(GL.QT_GIR, 0) - ISNULL(GL.QT_GIR_STOCK, 0)) AS QT_GIR  
		   			  FROM MM_QTIO QO
		   			  LEFT JOIN SA_GIRL GL ON GL.CD_COMPANY = QO.CD_COMPANY AND GL.NO_GIR = QO.NO_ISURCV AND GL.SEQ_GIR = QO.NO_ISURCVLINE) GL
		   ON GL.CD_COMPANY = IL.CD_COMPANY AND GL.NO_IO = IL.NO_IO AND GL.NO_IOLINE = IL.NO_IOLINE
		   LEFT JOIN SA_SOL SL ON SL.CD_COMPANY = IL.CD_COMPANY AND SL.NO_SO = IL.NO_SO AND SL.SEQ_SO = IL.NO_SOLINE
		   LEFT JOIN CZ_SA_STOCK_BOOK SB ON SB.CD_COMPANY = SL.CD_COMPANY AND SB.NO_FILE = SL.NO_SO AND SB.NO_LINE = SL.SEQ_SO
		   LEFT JOIN PU_POL PL ON PL.CD_COMPANY = SL.CD_COMPANY AND PL.NO_SO = SL.NO_SO AND PL.NO_SOLINE = SL.SEQ_SO
		   LEFT JOIN CZ_SA_QTNL QL ON QL.CD_COMPANY = PL.CD_COMPANY AND QL.NO_FILE = PL.NO_SO AND QL.NO_LINE = PL.NO_LINE
		   LEFT JOIN (SELECT CD_COMPANY, NO_PO, NO_POLINE, MAX(UM_ITEM_CLS) AS UM_IV 
		   			  FROM PU_IVL
					  WHERE CD_ITEM NOT LIKE 'SD%'
		   			  GROUP BY CD_COMPANY, NO_PO, NO_POLINE) PV 
		   ON PV.CD_COMPANY = PL.CD_COMPANY AND PV.NO_PO = PL.NO_PO AND PV.NO_POLINE = PL.NO_LINE
		   LEFT JOIN (SELECT IL.CD_COMPANY, IL.CD_PJT, 
					  		 ROUND(SUM(ISNULL(IL.AM_CLS, 0)) / MAX(ISNULL(SL.QT_PO, 0)), @P_AM_FSIZE) AS UM_CHARGE 
					  FROM PU_IVL IL
					  JOIN (SELECT CD_COMPANY, NO_SO, SUM(QT_PO) AS QT_PO 
					  	    FROM SA_SOL
					  	    GROUP BY CD_COMPANY, NO_SO) SL
					  ON SL.CD_COMPANY = IL.CD_COMPANY AND SL.NO_SO = IL.CD_PJT
					  WHERE IL.CD_ITEM LIKE 'SD%'
					  GROUP BY IL.CD_COMPANY, IL.CD_PJT) PV1
		   ON PV1.CD_COMPANY = IL.CD_COMPANY AND PV1.CD_PJT = IL.NO_SO
		   WHERE IL.CD_ITEM NOT LIKE 'SD%'
		   AND ISNULL(GL.QT_GIR, 0) > 0
		   UNION
		   SELECT IL.CD_COMPANY, IL.CD_PLANT, IL.NO_IV, IL.NO_LINE, IL.CD_ITEM, IL.CD_CC, 
		   		  QL.NO_DSP, QL.CD_ITEM_PARTNER, QL.NM_ITEM_PARTNER,
		   		  ISNULL(GL.QT_GIR, 0) AS QT_IV,
		   		  NULL,
		   		  NULL,
		   		  ISNULL(SB.UM_KR, 0) AS UM_PO,
		   		  ISNULL(SB.UM_KR, 0) AS UM_IV,
				  NULL
		   FROM SA_IVL IL
		   LEFT JOIN (SELECT QO.CD_COMPANY, QO.NO_IO, QO.NO_IOLINE,
		   				     ISNULL(GL.QT_GIR_STOCK, 0) AS QT_GIR
		   			  FROM MM_QTIO QO
		   			  LEFT JOIN SA_GIRL GL ON GL.CD_COMPANY = QO.CD_COMPANY AND GL.NO_GIR = QO.NO_ISURCV AND GL.SEQ_GIR = QO.NO_ISURCVLINE) GL
		   ON GL.CD_COMPANY = IL.CD_COMPANY AND GL.NO_IO = IL.NO_IO AND GL.NO_IOLINE = IL.NO_IOLINE
		   LEFT JOIN SA_SOL SL ON SL.CD_COMPANY = IL.CD_COMPANY AND SL.NO_SO = IL.NO_SO AND SL.SEQ_SO = IL.NO_SOLINE
		   LEFT JOIN CZ_SA_QTNL QL ON QL.CD_COMPANY = SL.CD_COMPANY AND QL.NO_FILE = SL.NO_SO AND QL.NO_LINE = SL.SEQ_SO
		   LEFT JOIN CZ_SA_STOCK_BOOK SB ON SB.CD_COMPANY = SL.CD_COMPANY AND SB.NO_FILE = SL.NO_SO AND SB.NO_LINE = SL.SEQ_SO
		   WHERE IL.CD_ITEM NOT LIKE 'SD%'
		   AND ISNULL(GL.QT_GIR, 0) > 0) IL 
ON IL.CD_COMPANY = IH.CD_COMPANY AND IL.NO_IV = IH.NO_IV
LEFT JOIN MA_PITEM MI ON MI.CD_COMPANY = IL.CD_COMPANY AND MI.CD_PLANT = IL.CD_PLANT AND MI.CD_ITEM = IL.CD_ITEM
WHERE IH.CD_COMPANY = @P_CD_COMPANY
AND IH.NO_IV = @P_NO_IV
AND IL.CD_CC = @P_CD_CC
AND ABS(IL.QT_IV) > 0
ORDER BY IH.CD_COMPANY, IH.NO_IV, IL.CD_CC, IL.NO_LINE, IL.NO_PO, IL.NO_POLINE

GO