USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_DEFERRED_DELIVERY_EXCEL]    Script Date: 2016-06-28 오후 1:28:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_SA_DEFERRED_DELIVERY_EXCEL] 
(
	@P_XML			XML, 
	@P_ID_USER		NVARCHAR(10)
) 
AS 

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

DECLARE @V_DOC INT

EXEC SP_XML_PREPAREDOCUMENT @V_DOC OUTPUT, @P_XML 

SELECT * INTO #XML
FROM OPENXML (@V_DOC, '/XML/ROW', 2) WITH 
(
	NO_ORDER	NVARCHAR(200),
	NO_LINE		INT,
	DT_EXPECT	NVARCHAR(8)
)

EXEC SP_XML_REMOVEDOCUMENT @V_DOC 

UPDATE PL
SET PL.DT_EXPECT = XL.DT_EXPECT
FROM PU_POH PH
JOIN PU_POL PL ON PL.CD_COMPANY = PH.CD_COMPANY AND PL.NO_PO = PH.NO_PO
JOIN #XML XL ON XL.NO_ORDER = PH.NO_ORDER AND XL.NO_LINE = PL.NO_LINE
WHERE PH.CD_COMPANY = 'K100'
AND PH.NO_PO LIKE '%ST%'
AND ISNULL(XL.DT_EXPECT, '') <> ''

DROP TABLE #XML

GO

