USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_DEFERRED_DELIVERY_U]    Script Date: 2016-05-23 오후 4:20:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO





ALTER PROCEDURE [NEOE].[SP_CZ_SA_DEFERRED_DELIVERYH_U]  
(  
    @P_CD_COMPANY		NVARCHAR(7),
	@P_TP_TYPE			NVARCHAR(1),
	@P_NO_SO			NVARCHAR(20),
	@P_NO_KEY			NVARCHAR(20),
	@P_DT_LIMIT			NVARCHAR(8),
	@P_DT_EXPECT		NVARCHAR(8),
	@P_DT_REPLY			NVARCHAR(8),
	@P_DC_RMK_TEXT2		NVARCHAR(4000),
	@P_DC_RMK			NVARCHAR(MAX),
	@P_CD_DELAY			NVARCHAR(4),
	@P_TP_SEND			NVARCHAR(10),
	@P_DTS_SEND			NVARCHAR(15),
	@P_ID_UPDATE		NVARCHAR(15)
)
AS

UPDATE SA_SOH
SET DC_RMK_TEXT2 = @P_DC_RMK_TEXT2
WHERE CD_COMPANY = @P_CD_COMPANY
AND NO_SO = @P_NO_SO

IF NOT EXISTS (SELECT 1 
			   FROM CZ_SA_DEFERRED_DELIVERY 
			   WHERE CD_COMPANY = @P_CD_COMPANY 
			   AND TP_TYPE = @P_TP_TYPE
			   AND NO_SO = @P_NO_SO
			   AND NO_KEY = @P_NO_KEY 
			   AND DT_LIMIT = @P_DT_LIMIT)
INSERT INTO CZ_SA_DEFERRED_DELIVERY
(
	CD_COMPANY,
	TP_TYPE,
	NO_SO,
	NO_KEY,
	DT_LIMIT,
	DT_EXPECT,
	DT_REPLY,
	DC_RMK,
	CD_DELAY,
	TP_SEND,
	DTS_SEND,
	ID_INSERT,
	DTS_INSERT
)
VALUES
(
	@P_CD_COMPANY,
	@P_TP_TYPE,
	@P_NO_SO,
	@P_NO_KEY,
	@P_DT_LIMIT,
	@P_DT_EXPECT,
	@P_DT_REPLY,
	@P_DC_RMK,
	@P_CD_DELAY,
	@P_TP_SEND,
	@P_DTS_SEND,
	@P_ID_UPDATE,
	NEOE.SF_SYSDATE(GETDATE())
)
ELSE
UPDATE CZ_SA_DEFERRED_DELIVERY
SET DT_EXPECT = @P_DT_EXPECT,
	DT_REPLY = @P_DT_REPLY,
    DC_RMK = @P_DC_RMK,
	CD_DELAY = @P_CD_DELAY,
	TP_SEND = @P_TP_SEND,
	DTS_SEND = @P_DTS_SEND,
	ID_UPDATE = @P_ID_UPDATE,
	DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE())
WHERE CD_COMPANY = @P_CD_COMPANY 
AND TP_TYPE = @P_TP_TYPE
AND NO_SO = @P_NO_SO
AND NO_KEY = @P_NO_KEY
AND DT_LIMIT = @P_DT_LIMIT

GO

