USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_CLAIML_SUB_S]    Script Date: 2015-04-14 오전 8:32:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER PROCEDURE [NEOE].[SP_CZ_SA_CLAIML_SUB_S]
(
	@P_CD_COMPANY	NVARCHAR(7),
	@P_LANGUAGE		NVARCHAR(5) = 'KR',
	@P_NO_SO		NVARCHAR(20)
) 
AS 

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

DECLARE @P_AM_FSIZE NUMERIC(3, 0)   -- 소수점    

IF @P_CD_COMPANY = 'S100'
	SET @P_AM_FSIZE = 2
ELSE
	SET @P_AM_FSIZE = 0

SELECT 'Y' AS S,
	   SL.NO_SO,
	   SL.SEQ_SO,
	   QL.NO_DSP,
	   QL.NM_SUBJECT,
	   SL.CD_ITEM,
	   MI.NM_ITEM,
	   QL.CD_ITEM_PARTNER,
	   QL.NM_ITEM_PARTNER,
	   SL.QT_SO,
	   SL.UNIT_SO,
	   MI.CLS_ITEM,
	   (SELECT (CASE @P_LANGUAGE WHEN 'KR' THEN NM_SYSDEF
								 WHEN 'US' THEN NM_SYSDEF_E
								 WHEN 'JP' THEN NM_SYSDEF_JP
								 WHEN 'CH' THEN NM_SYSDEF_CH END)
		FROM MA_CODEDTL
		WHERE CD_COMPANY = MI.CD_COMPANY
		AND CD_FIELD = 'MA_B000010'
		AND CD_SYSDEF = MI.CLS_ITEM) AS NM_CLS_ITEM,
	   ISNULL(PL.CD_PARTNER, SB.CD_PARTNER) AS CD_PARTNER,
	   ISNULL(MP.LN_PARTNER, SB.CD_PARTNER) AS LN_PARTNER,
	   ISNULL(PL.UM_PO, 0) AS UM_PO,
	   ISNULL(PL.AM_PO, 0) AS AM_PO,
	   ISNULL(SB.UM_KR, 0) AS UM_STOCK,
	   ISNULL(SB.AM_KR, 0) AS AM_STOCK,
	   SL.UM_SO,
	   SL.AM_SO,
	   ISNULL(CONVERT(NVARCHAR, PL.LT), SB.LT) AS LT,
	   '' AS NO_CLAIM,
	   0 AS QT_CLAIM,
	   IL.DT_IO AS DT_OUT
FROM (SELECT SL.CD_COMPANY, SL.NO_SO, SL.SEQ_SO,
			 SL.CD_ITEM,
			 SL.UNIT_SO,
			 SL.QT_SO,
			 ISNULL(SL.UM_KR_S, ROUND(SL.UM_SO * SH.RT_EXCH, @P_AM_FSIZE)) AS UM_SO,
			 ISNULL(SL.AM_KR_S, SL.AM_WONAMT) AS AM_SO 
	  FROM SA_SOL SL
	  LEFT JOIN SA_SOH SH ON SH.CD_COMPANY = SL.CD_COMPANY AND SH.NO_SO = SL.NO_SO) SL
LEFT JOIN CZ_SA_QTNL QL ON QL.CD_COMPANY = SL.CD_COMPANY AND QL.NO_FILE = SL.NO_SO AND QL.NO_LINE = SL.SEQ_SO
LEFT JOIN (SELECT PL.CD_COMPANY, PL.NO_SO, PL.NO_SOLINE, 
				  MAX(PH.CD_PARTNER) AS CD_PARTNER, 
				  SUM(PL.UM) AS UM_PO, 
				  SUM(PL.AM) AS AM_PO, 
				  MAX(PL.LT) AS LT 
		   FROM PU_POL PL
		   LEFT JOIN PU_POH PH ON PH.CD_COMPANY = PL.CD_COMPANY AND PH.NO_PO = PL.NO_PO
		   GROUP BY PL.CD_COMPANY, PL.NO_SO, PL.NO_SOLINE) PL
ON PL.CD_COMPANY = SL.CD_COMPANY AND PL.NO_SO = SL.NO_SO AND PL.NO_SOLINE = SL.SEQ_SO
LEFT JOIN (SELECT CD_COMPANY, NO_FILE, NO_LINE,
				  'STOCK' AS CD_PARTNER,
				  UM_KR,
				  AM_KR,
				  'STOCK' AS LT 
		   FROM CZ_SA_STOCK_BOOK) SB 
ON SB.CD_COMPANY = SL.CD_COMPANY AND SB.NO_FILE = SL.NO_SO AND SB.NO_LINE = SL.SEQ_SO
LEFT JOIN (SELECT OL.CD_COMPANY, OL.NO_PSO_MGMT, OL.NO_PSOLINE_MGMT,
				  MAX(OH.DT_IO) AS DT_IO 
		   FROM MM_QTIO OL
		   LEFT JOIN MM_QTIOH OH ON OH.CD_COMPANY = OL.CD_COMPANY AND OH.NO_IO = OL.NO_IO
		   WHERE OL.FG_PS = '2'
		   GROUP BY OL.CD_COMPANY, OL.NO_PSO_MGMT, OL.NO_PSOLINE_MGMT) IL
ON IL.CD_COMPANY = SL.CD_COMPANY AND IL.NO_PSO_MGMT = SL.NO_SO AND IL.NO_PSOLINE_MGMT = SL.SEQ_SO
LEFT JOIN MA_PITEM MI ON MI.CD_COMPANY = SL.CD_COMPANY AND MI.CD_ITEM = SL.CD_ITEM
LEFT JOIN MA_PARTNER MP ON MP.CD_COMPANY = PL.CD_COMPANY AND MP.CD_PARTNER = PL.CD_PARTNER
WHERE SL.CD_COMPANY = @P_CD_COMPANY
AND SL.NO_SO = @P_NO_SO 

GO

