USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_PR_MATCHING_DEACTIVATE_S]    Script Date: 2017-01-05 오후 5:48:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_PR_MATCHING_DEACTIVATE_S]          
(
	@P_CD_COMPANY		NVARCHAR(7),
	@P_CD_PLANT			NVARCHAR(7),
	@P_STA_DEACTIVATE   NVARCHAR(4),
	@P_CD_ITEM			NVARCHAR(20)
)  
AS
   
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT 'N' AS S,
	   MD.CD_COMPANY,
	   MD.CD_PLANT,
	   MD.NO_ID,
	   MD.STA_DEACTIVATE,
	   MD.NO_WO,
	   MD.CD_ITEM,
	   MD.CD_PITEM,
	   MI.NM_ITEM,
	   MI.STND_ITEM,
	   MI.NO_DESIGN,
	   MD.NUM_P1_OUT,
	   MD.NUM_P2_OUT,
	   MD.NUM_P3_OUT,
	   MD.NUM_P1_IN,
	   MD.NUM_P2_IN,
	   MD.NUM_P3_IN,
	   MD.DC_RMK,
	   MU.NM_USER AS NM_INSERT,
	   MD.DTS_INSERT,
	   MU1.NM_USER AS NM_UPDATE,
	   MD.DTS_UPDATE
FROM CZ_PR_MATCHING_DEACTIVATE MD
LEFT JOIN MA_PITEM MI ON MI.CD_COMPANY = MD.CD_COMPANY AND MI.CD_PLANT = MD.CD_PLANT AND MI.CD_ITEM = MD.CD_PITEM
LEFT JOIN MA_USER MU ON MU.CD_COMPANY = MD.CD_COMPANY AND MU.ID_USER = MD.ID_INSERT
LEFT JOIN MA_USER MU1 ON MU1.CD_COMPANY = MD.CD_COMPANY AND MU1.ID_USER = MD.ID_UPDATE
WHERE MD.CD_COMPANY = @P_CD_COMPANY
AND MD.CD_PLANT = @P_CD_PLANT
AND (ISNULL(@P_STA_DEACTIVATE, '') = '' OR MD.STA_DEACTIVATE = @P_STA_DEACTIVATE)
AND (ISNULL(@P_CD_ITEM, '') = '' OR MD.CD_PITEM = @P_CD_ITEM)

GO

