USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_MM_MONTHLY_STOCK_RPT_PIVOT_S]    Script Date: 2017-01-05 오후 5:48:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_PR_MATCHING_ITEM_S]          
(
	@P_CD_COMPANY	NVARCHAR(7),
	@P_CD_PLANT		NVARCHAR(7),
	@P_CD_ITEM		NVARCHAR(20),
	@P_CD_PITEM 	NVARCHAR(20)
)  
AS
   
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT MC.CD_COMPANY,
	   MC.CD_PLANT,
	   MC.CD_ITEM,
	   MI.NM_ITEM,
	   MC.CD_PITEM,
	   MI1.NM_ITEM AS NM_PITEM,
	   MC.TP_POS
FROM CZ_PR_MATCHING_ITEM MC
LEFT JOIN MA_PITEM MI ON MI.CD_COMPANY = MC.CD_COMPANY AND MI.CD_PLANT = MC.CD_PLANT AND MI.CD_ITEM = MC.CD_ITEM
LEFT JOIN MA_PITEM MI1 ON MI1.CD_COMPANY = MC.CD_COMPANY AND MI1.CD_PLANT = MC.CD_PLANT AND MI1.CD_ITEM = MC.CD_PITEM
WHERE MC.CD_COMPANY = @P_CD_COMPANY
AND MC.CD_PLANT = @P_CD_PLANT
AND (ISNULL(@P_CD_ITEM, '') = '' OR MC.CD_ITEM = @P_CD_ITEM)
AND (ISNULL(@P_CD_PITEM, '') = '' OR MC.CD_PITEM = @P_CD_PITEM)

GO

