USE [NEOE]
GO
/****** Object:  StoredProcedure [NEOE].[CZ_MAILBAGLIST_SL]    Script Date: 2023-05-03 오후 4:46:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[CZ_MAILBAGLIST_SL]
		@P_DAYS_RECORD		NVARCHAR(10),
		@P_SEND_COMPANY		NVARCHAR(8)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET NOCOUNT ON

SELECT
	A.SEND_COMPANY,
	A.DAYS_RECORD,
	A.SEND_NUM,
	A.SEND_CONTENTS,
	A.SEND_QT,
	A.SEND_ID,
	MP1.NM_KOR AS NM_SEND,
	A.RECEIVE_ID,
	MP2.NM_KOR AS NM_RECEIVE,
	A.INSPECT_ID,
	MP3.NM_KOR AS NM_INSPECT,
	A.DC_RMK,
	A.DTS_UPDATE,
	A.ID_UPDATE,
	A.DTS_INSERT,
	A.ID_INSERT,
	B.SEND_COMPANYNAME
FROM CZ_MAILBAGLIST_L AS A
LEFT JOIN CZ_MAILBAGLIST_H AS C ON A.SEND_COMPANY = C.SEND_COMPANY AND A.DAYS_RECORD = C.DAYS_RECORD
LEFT JOIN MA_EMP MP1 ON A.SEND_ID = MP1.NO_EMP AND C.CD_COMPANY = MP1.CD_COMPANY
LEFT JOIN MA_EMP MP2 ON A.RECEIVE_ID = MP2.NO_EMP AND C.CD_COMPANY = MP2.CD_COMPANY
LEFT JOIN MA_EMP MP3 ON A.INSPECT_ID = MP3.NO_EMP AND C.CD_COMPANY = MP3.CD_COMPANY
LEFT JOIN CZ_MAILBAGLIST_COMPANY B ON A.SEND_COMPANY = B.SEND_COMPANY
WHERE A.DAYS_RECORD = @P_DAYS_RECORD
AND A.SEND_COMPANY = @P_SEND_COMPANY
ORDER BY A.SEND_NUM ASC
--ASC 오름차순 DESC 내림차순