USE [NEOE]
GO
/****** Object:  StoredProcedure [NEOE].[CZ_MAILBAGLIST_DL]    Script Date: 2023-05-03 오후 4:45:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--작성삭제용
ALTER PROCEDURE [NEOE].[CZ_MAILBAGLIST_DL]
(
	@P_SEND_COMPANY		NVARCHAR(2),
	@P_DAYS_RECORD		NVARCHAR(14),
	@P_SEND_NUM			NUMERIC(3,0)
)  
AS
   
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

DELETE CZ_MAILBAGLIST_L
WHERE SEND_COMPANY = @P_SEND_COMPANY
AND DAYS_RECORD	= @P_DAYS_RECORD
AND SEND_NUM = @P_SEND_NUM