USE [NEOE]
GO
/****** Object:  StoredProcedure [NEOE].[CZ_MAILBAGLIST_MSG_SEND]    Script Date: 2023-05-03 오후 4:45:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[CZ_MAILBAGLIST_MSG_SEND]
		@P_NO_EMP			NVARCHAR(10)
AS

DECLARE	@V_CONTENTS		NVARCHAR(MAX)
DECLARE	@V_CONTENTS1	NVARCHAR(MAX)

 SET @V_CONTENTS1 = Convert(varchar(10),Getdate(),111)+' 본사에서 양산창고로 발송'+char(10)+char(10)+
 (SELECT DISTINCT  
        STUFF((SELECT distinct concat(char(10),
		'발송자 : '+ISNULL(MP1.NM_KOR,'')+
		' / 수신자 : '+ISNULL(MP2.NM_KOR,'')+
		' // 내용 : '+ISNULL(A.SEND_CONTENTS,'없음')+
		' / 수량 : '+ISNULL(CONVERT(NVARCHAR(3),A.SEND_QT),'없음')+	
		' / 비고 : '+ISNULL(A.DC_RMK,''))
	FROM CZ_MAILBAGLIST_L AS A
	LEFT JOIN CZ_MAILBAGLIST_H AS C ON A.SEND_COMPANY = C.SEND_COMPANY AND A.DAYS_RECORD = C.DAYS_RECORD
	LEFT JOIN MA_EMP MP1 ON A.SEND_ID = MP1.NO_EMP AND C.CD_COMPANY = MP1.CD_COMPANY
	LEFT JOIN MA_EMP MP2 ON A.RECEIVE_ID = MP2.NO_EMP AND C.CD_COMPANY = MP2.CD_COMPANY
	LEFT JOIN MA_EMP MP3 ON A.INSPECT_ID = MP3.NO_EMP AND C.CD_COMPANY = MP3.CD_COMPANY
	LEFT JOIN CZ_MAILBAGLIST_COMPANY B ON A.SEND_COMPANY = B.SEND_COMPANY
	WHERE A.DAYS_RECORD = FORMAT(CAST(GETDATE() AS DATE), 'yyyyMMdd')
	AND A.SEND_COMPANY = '01'
	FOR XML PATH('')),1,1,'')  
FROM CZ_MAILBAGLIST_L AS A)

SET @V_CONTENTS = ISNULL(@V_CONTENTS1,'금일 본사에서 양산로 발송할 물건이 없습니다')

EXEC PX_CZ_RPA_MSG_SEND @P_NO_EMP,@V_CONTENTS
