USE [NEOE]
GO
/****** Object:  StoredProcedure [NEOE].[CZ_MAILBAGLIST_IL]    Script Date: 2023-05-03 ¿ÀÈÄ 4:45:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[CZ_MAILBAGLIST_IL]
(
	@P_SEND_COMPANY		NVARCHAR(2),
	@P_DAYS_RECORD		NVARCHAR(14),
	@P_SEND_NUM			NUMERIC(3,0),
	@P_SEND_CONTENTS	NVARCHAR(MAX),
	@P_SEND_QT			NUMERIC(3,0),
	@P_SEND_ID			NVARCHAR(15),
	@P_RECEIVE_ID		NVARCHAR(15),
	@P_INSPECT_ID		NVARCHAR(15),
	@P_DC_RMK			NVARCHAR(MAX),
	@P_DTS_INSERT		NVARCHAR(14),
	@P_ID_INSERT		NVARCHAR(15)
)  
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

INSERT CZ_MAILBAGLIST_L
(
	SEND_COMPANY,
	DAYS_RECORD,
	SEND_NUM,
	SEND_CONTENTS,
	SEND_QT,
	SEND_ID,
	RECEIVE_ID,
	INSPECT_ID,
	DC_RMK,
	DTS_INSERT,
	ID_INSERT
)
VALUES
(
	@P_SEND_COMPANY,
	@P_DAYS_RECORD,
	@P_SEND_NUM,
	@P_SEND_CONTENTS,
	@P_SEND_QT,
	@P_SEND_ID,
	@P_RECEIVE_ID,
	@P_INSPECT_ID,
	@P_DC_RMK,
	@P_DTS_INSERT,
	@P_ID_INSERT
)
