USE [NEOE]
GO

/****** Object:  Table [NEOE].[CZ_PR_ROUT_EQUIP]    Script Date: 2023-06-27 오후 4:27:23 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [NEOE].[CZ_PR_ROUT_EQUIP](
	[CD_COMPANY] [nvarchar](7) NOT NULL,
	[CD_PLANT] [nvarchar](7) NOT NULL,
	[CD_ITEM] [nvarchar](20) NOT NULL,
	[NO_OPPATH] [nvarchar](3) NOT NULL,
	[CD_OP] [nvarchar](4) NOT NULL,
	[CD_WC] [nvarchar](7) NOT NULL,
	[CD_WCOP] [nvarchar](4) NOT NULL,
	[CD_EQUIP] [nvarchar](30) NOT NULL,
	[QT_LABOR_PLAN] [numeric](17, 4) NULL,
	[ID_INSERT] [nvarchar](15) NULL,
	[DTS_INSERT] [nvarchar](14) NULL,
	[ID_UPDATE] [nvarchar](15) NULL,
	[DTS_UPDATE] [nvarchar](14) NULL,
 CONSTRAINT [PK_CZ_PR_WO_ROUT_EQUIP] PRIMARY KEY CLUSTERED 
(
	[CD_COMPANY] ASC,
	[CD_PLANT] ASC,
	[CD_ITEM] ASC,
	[NO_OPPATH] ASC,
	[CD_OP] ASC,
	[CD_EQUIP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


