USE [NEOE]
GO
/****** Object:  StoredProcedure [NEOE].[SP_CZ_PU_PR_D]    Script Date: 2021-03-18 오전 9:19:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_PU_PR_D]      
(
    @P_CD_COMPANY		NVARCHAR(7),
    @P_CD_PLANT         NVARCHAR(7),
    @P_NO_PR			NVARCHAR(20),
    @P_NO_PRLINE		NUMERIC(5)
)      
AS

DELETE PU_PRL  
WHERE CD_COMPANY = @P_CD_COMPANY
AND CD_PLANT = @P_CD_PLANT
AND NO_PR = @P_NO_PR
AND NO_PRLINE = @P_NO_PRLINE

DELETE CZ_PR_SA_SOL_PU_PRL_MAPPING
WHERE CD_COMPANY = @P_CD_COMPANY
AND CD_PLANT = @P_CD_PLANT
AND NO_PR = @P_NO_PR
AND NO_PRLINE = @P_NO_PRLINE

IF NOT EXISTS(SELECT 1 
              FROM PU_PRL 
              WHERE CD_COMPANY = @P_CD_COMPANY
              AND CD_PLANT = @P_CD_PLANT
              AND NO_PR = @P_NO_PR)
BEGIN
    DELETE PU_PRH
    WHERE CD_COMPANY = @P_CD_COMPANY
    AND CD_PLANT = @P_CD_PLANT
    AND NO_PR = @P_NO_PR
END

GO