USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_PR_WO_SIMULATION_D]    Script Date: 2020-06-30 오후 7:14:12 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_PR_WO_SIMULATION_D]
(
	@P_CD_COMPANY		NVARCHAR(7)
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

DELETE WS
FROM CZ_PR_SA_SOL_PR_WO_MAPPING WS
WHERE NOT EXISTS (SELECT 1 
		          FROM PR_WO WO 
			      WHERE WO.CD_COMPANY = WS.CD_COMPANY
				  AND WO.NO_WO = WS.NO_WO)

DELETE PL 
FROM CZ_PR_SA_SOL_PU_PRL_MAPPING PL
WHERE NOT EXISTS (SELECT 1 
			      FROM PU_PRL PL1 
				  WHERE PL1.CD_COMPANY = PL.CD_COMPANY 
				  AND PL1.NO_PR = PL.NO_PR 
				  AND PL1.NO_PRLINE = PL.NO_PRLINE)

DELETE SR
FROM CZ_PR_SA_SOL_SU_PRL_MAPPING SR
WHERE NOT EXISTS (SELECT 1 
				  FROM SU_PRL SR1 
				  WHERE SR1.CD_COMPANY = SR.CD_COMPANY 
				  AND SR1.NO_PR = SR.NO_PR 
				  AND SR1.NO_LINE = SR.NO_LINE)

GO