USE [NEOE]
GO
/****** Object:  StoredProcedure [NEOE].[SP_CZ_PR_OPOUT_PR_REG_ID_S]    Script Date: 2022-10-19 오후 5:49:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO



ALTER PROCEDURE [NEOE].[SP_CZ_PR_OPOUT_PR_REG_ID_S]
(
	@P_CD_COMPANY		NVARCHAR(7),
	@P_NO_PR			NVARCHAR(20),
	@P_NO_LINE			NUMERIC(5, 0),
	@P_NO_WO			NVARCHAR(20),
	@P_NO_WO_LINE		NUMERIC(5, 0)
) 
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET NOCOUNT ON
DECLARE @CD_COMPANY		NVARCHAR(7)
DECLARE @NO_PR			NVARCHAR(20)
DECLARE	@NO_LINE		NUMERIC(5, 0)
DECLARE @NO_WO			NVARCHAR(20)
DECLARE @NO_WO_LINE		NUMERIC(5, 0)
SET @CD_COMPANY	= @P_CD_COMPANY
SET @NO_PR		= @P_NO_PR
SET	@NO_LINE	= @P_NO_LINE
SET @NO_WO		= @P_NO_WO
SET @NO_WO_LINE	= @P_NO_WO_LINE

BEGIN

SELECT 'Y' S,
	   WD.CD_COMPANY,
	   WD.NO_WO,
	   WD.SEQ_WO,
	   WD.DT_NO_ID,
	   WD.NO_SEQ,
	   WD.NO_ID,
	   WD.NO_ID_OLD,
	   WD.NO_HEAT,
	   WR.NO_LINE AS NO_WO_LINE,
	   WI.NO_OPOUT_PR,
	   WI.NO_PR_LINE,
	   WI.NO_OPOUT_PO,
	   WI.NO_OPOUT_WORK
FROM CZ_PR_WO_REQ_D WD
LEFT JOIN PR_WO_ROUT WR ON WR.CD_COMPANY = WD.CD_COMPANY AND WR.NO_WO = WD.NO_WO
LEFT JOIN CZ_PR_WO_INSP WI ON WI.CD_COMPANY = WD.CD_COMPANY AND WI.NO_WO = WD.NO_WO AND WI.SEQ_WO = WD.SEQ_WO AND WI.NO_LINE = WR.NO_LINE
WHERE WD.CD_COMPANY = @CD_COMPANY
AND WI.NO_OPOUT_PR = @NO_PR
AND WI.NO_PR_LINE = @NO_LINE
AND WD.NO_WO = @NO_WO
AND WR.NO_LINE = @NO_WO_LINE 
AND EXISTS (SELECT 1
			FROM CZ_PR_WO_INSP WI
			WHERE WI.CD_COMPANY = WD.CD_COMPANY
			AND WI.NO_WO = WD.NO_WO
			AND WI.SEQ_WO = WD.SEQ_WO
			AND WI.NO_LINE = WR.NO_LINE
			AND (WI.NO_INSP = 994 OR WI.NO_INSP = 995))
AND (ISNULL(WR.CD_OP_BEFORE, '') = '' OR EXISTS (SELECT 1 
											     FROM CZ_PR_WO_INSP WI
											     JOIN PR_WO_ROUT WR1 ON WR1.CD_COMPANY = WI.CD_COMPANY AND WR1.NO_WO = WI.NO_WO AND WR1.NO_LINE = WI.NO_LINE
											     WHERE WI.CD_COMPANY = WD.CD_COMPANY
											     AND WI.NO_WO = WD.NO_WO
											     AND WR1.CD_OP = WR.CD_OP_BEFORE
											     AND WR1.CD_WC = WR.CD_WC_BEFORE
											     AND WR1.CD_WCOP = WR.CD_WCOP_BEFORE
											     AND WI.SEQ_WO = WD.SEQ_WO))

UNION ALL

SELECT 'N' S,
	   WD.CD_COMPANY,
	   WD.NO_WO,
	   WD.SEQ_WO,
	   WD.DT_NO_ID,
	   WD.NO_SEQ,
	   WD.NO_ID,
	   WD.NO_ID_OLD,
	   WD.NO_HEAT,
	   WR.NO_LINE AS NO_WO_LINE,
	   WI.NO_OPOUT_PR,
	   @NO_LINE AS NO_PR_LINE,
	   WI.NO_OPOUT_PO,
	   WI.NO_OPOUT_WORK
FROM CZ_PR_WO_REQ_D WD
LEFT JOIN PR_WO_ROUT WR ON WR.CD_COMPANY = WD.CD_COMPANY AND WR.NO_WO = WD.NO_WO
LEFT JOIN CZ_PR_WO_INSP WI ON WI.CD_COMPANY = WD.CD_COMPANY AND WI.NO_WO = WD.NO_WO AND WI.SEQ_WO = WD.SEQ_WO AND WI.NO_LINE = WR.NO_LINE
WHERE WD.CD_COMPANY = @CD_COMPANY
AND WD.NO_WO = @NO_WO
AND WR.NO_LINE = @NO_WO_LINE 
AND NOT EXISTS (SELECT 1 
				FROM CZ_PR_WO_INSP WI
				WHERE WI.CD_COMPANY = WD.CD_COMPANY
				AND WI.NO_WO = WD.NO_WO
				AND WI.SEQ_WO = WD.SEQ_WO
				AND WI.NO_INSP = -1)
AND NOT EXISTS (SELECT 1
				FROM CZ_PR_WO_INSP WI
				WHERE WI.CD_COMPANY = WD.CD_COMPANY
				AND WI.NO_WO = WD.NO_WO
				AND WI.SEQ_WO = WD.SEQ_WO
				AND WI.NO_LINE = WR.NO_LINE)
AND NOT EXISTS (SELECT 1
				FROM CZ_PR_WO_INSP WI
				WHERE WI.NO_WO = WD.NO_WO
				AND WI.SEQ_WO = WD.SEQ_WO
				AND WI.NO_INSP = 994)
AND (ISNULL(WR.CD_OP_BEFORE, '') = '' OR EXISTS (SELECT 1 
											     FROM CZ_PR_WO_INSP WI
											     JOIN PR_WO_ROUT WR1 ON WR1.CD_COMPANY = WI.CD_COMPANY AND WR1.NO_WO = WI.NO_WO AND WR1.NO_LINE = WI.NO_LINE
											     WHERE WI.CD_COMPANY = WD.CD_COMPANY
											     AND WI.NO_WO = WD.NO_WO
											     AND WR1.CD_OP = WR.CD_OP_BEFORE
											     AND WR1.CD_WC = WR.CD_WC_BEFORE
											     AND WR1.CD_WCOP = WR.CD_WCOP_BEFORE
											     AND WI.SEQ_WO = WD.SEQ_WO))
ORDER BY WD.SEQ_WO

END