USE [NEOE]
GO
/****** Object:  StoredProcedure [NEOE].[UP_CZ_PR_OPOUT_PR_DELETE]    Script Date: 2022-10-19 오후 5:42:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROC [NEOE].[UP_CZ_PR_OPOUT_PR_DELETE]
(
    @P_CD_COMPANY   NVARCHAR(7),
    @P_CD_PLANT     NVARCHAR(7),
    @P_NO_PR        NVARCHAR(20),
    @P_NO_LINE      NUMERIC(5,0)
)
AS

DECLARE @ERRMSG     NVARCHAR(255)

DELETE FROM CZ_PR_OPOUT_PR
WHERE CD_COMPANY = @P_CD_COMPANY
    AND CD_PLANT = @P_CD_PLANT
    AND NO_PR = @P_NO_PR
    AND NO_LINE = @P_NO_LINE

DELETE FROM CZ_PR_WO_INSP
WHERE CD_COMPANY = @P_CD_COMPANY
AND NO_OPOUT_PR = @P_NO_PR
AND NO_PR_LINE = @P_NO_LINE

IF (@@ERROR <> 0 ) BEGIN SELECT @ERRMSG = '[UP_CZ_PR_OPOUT_PRL_DELETE]작업을정상적으로처리하지못했습니다.' GOTO ERROR END

RETURN
ERROR: RAISERROR (@ERRMSG, 18, 1)
RETURN
