USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[UP_CZ_PR_INV_L_SCH_SELECT]    Script Date: 2022-03-29 오후 4:57:34 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO





ALTER PROC [NEOE].[UP_CZ_PR_INV_L_SCH_SELECT]
(
@P_CD_COMPANY		NVARCHAR(12), 
@P_CD_PLANT			NVARCHAR(12), 
@P_DT_START			NVARCHAR(10), 
@P_DT_END			NVARCHAR(10), 
@P_ITEM				NVARCHAR(50)
)
AS

SELECT 
	A.CD_COMPANY
,	A.CD_PLANT
,	A.CD_ITEM
,	A.CD_OP
,	A.NM_OP
,	A.CD_WCOP
,	A.CD_WC
,	A.NM_WC
,	SUM(A.QT_WIP) AS QT_WIP
,	A.DC_RMK
FROM (SELECT  A.CD_COMPANY
		  ,	  A.CD_PLANT
		  ,	  A.NO_WO
		  ,	  B.CD_WCOP
		  ,   B.CD_WC
		  ,   B.CD_OP
		  ,   A.CD_ITEM
		  ,   SUM(B.QT_WIP) QT_WIP
		  ,	  D.NM_OP
		  ,   E.NM_WC
		  ,	  F.TXT_USERDEF5 DC_RMK
		   FROM PR_WO A
		   INNER JOIN PR_WO_ROUT B ON B.CD_COMPANY = @P_CD_COMPANY AND B.NO_WO = A.NO_WO
		   INNER JOIN DZSN_MA_PITEM C ON C.CD_COMPANY = @P_CD_COMPANY AND C.CD_PLANT = @P_CD_PLANT AND C.CD_ITEM = A.CD_ITEM
		   LEFT OUTER JOIN DZSN_PR_WCOP D ON D.CD_COMPANY = @P_CD_COMPANY AND D.CD_PLANT = @P_CD_PLANT AND D.CD_WC = B.CD_WC AND D.CD_WCOP = B.CD_WCOP
		   LEFT OUTER JOIN DZSN_MA_WC E ON E.CD_COMPANY = @P_CD_COMPANY AND E.CD_PLANT = @P_CD_PLANT AND E.CD_WC = B.CD_WC
		   LEFT OUTER JOIN PR_ROUT_L F ON F.CD_COMPANY = @P_CD_COMPANY AND F.CD_ITEM = @P_ITEM AND F.CD_OP = B.CD_OP
		   WHERE A.CD_COMPANY = @P_CD_COMPANY
		   AND A.CD_PLANT = @P_CD_PLANT
		   AND A.DT_REL >= @P_DT_START
		   AND A.DT_DUE <= @P_DT_END
		   AND A.CD_ITEM = @P_ITEM
		   AND A.ST_WO IN ('R','S')
		   AND QT_WIP > 0
		   GROUP BY A.CD_COMPANY, A.CD_PLANT,A.NO_WO, B.CD_WCOP, B.CD_WC, B.CD_OP, A.CD_ITEM, D.NM_OP, E.NM_WC, F.TXT_USERDEF5) A
GROUP BY A.CD_COMPANY, A.CD_PLANT, A.CD_ITEM, A.CD_OP, A.NM_OP, A.CD_WCOP, A.CD_WC, A.NM_WC, A.DC_RMK


