USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_AUTO_MAIL_SA_S]    Script Date: 2016-01-13 오후 9:02:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
 
ALTER PROCEDURE [NEOE].[SP_CZ_SA_AUTO_MAIL_SA_S]    
(            
	@P_CD_COMPANY		NVARCHAR(7),
	@P_CD_PARTNER		NVARCHAR(20),
	@P_NO_SO			NVARCHAR(20)
)            
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT AM.CD_PARTNER,
	   MP.LN_PARTNER,
	   AM.TP_PARTNER,
	   AM.TP_PERIOD,
       AM.YN_MON,
	   AM.YN_TUE,
	   AM.YN_WED,
	   AM.YN_THU,
	   AM.YN_FRI,
	   AM.YN_READY_INFO,
	   AM.YN_ORDER_STAT,
	   AM.QT_WEEK,
	   AM.TP_DOW_RI,
	   AM.YN_MON_WO,
	   AM.YN_TUE_WO,
	   AM.YN_WED_WO,
	   AM.YN_THU_WO,
	   AM.YN_FRI_WO,
	   SH.CD_PARTNER_GRP,
	   SH.YN_ORDER_STATUS,
	   SH.YN_REMARK,
	   SH.CD_FLAG3 AS NM_LOG,
	   MC2.NM_SYSDEF AS NM_PARTNER_GRP
FROM CZ_SA_AUTO_MAIL_PARTNER AM
LEFT JOIN MA_PARTNER MP ON MP.CD_COMPANY = AM.CD_COMPANY AND MP.CD_PARTNER = AM.CD_PARTNER
LEFT JOIN (SELECT SH.CD_COMPANY, SH.CD_PARTNER, SH.CD_PARTNER_GRP, VE.CD_FLAG3,
		   	      ROW_NUMBER() OVER (PARTITION BY SH.CD_COMPANY, SH.CD_PARTNER ORDER BY COUNT(1) DESC) AS IDX,
		   	      MAX(CASE WHEN SL.QT_SO > ISNULL(SL.QT_GI, 0) THEN 'Y' ELSE 'N' END) AS YN_ORDER_STATUS,
		   	      MAX(CASE WHEN SL.QT_SO > ISNULL(SL.QT_GI, 0) AND DATEDIFF(DAY, SL.DT_DUEDATE, GETDATE()) >= 21 AND ISNULL(DD.DC_RMK1, '') = '' THEN 'Y' ELSE 'N' END) AS YN_REMARK
		   FROM SA_SOH SH
		   JOIN (SELECT SL.CD_COMPANY, SL.NO_SO,
		                MAX(CASE WHEN SL.QT_SO > ISNULL(SL.QT_GI, 0) THEN SL.DT_DUEDATE 
		                                                             ELSE NULL END) AS DT_DUEDATE,
		   		        SUM(SL.QT_SO) AS QT_SO,
		   		        SUM(SL.QT_GI) AS QT_GI
		         FROM SA_SOL SL
		   	     WHERE SL.CD_ITEM NOT LIKE 'SD%'
		   	     GROUP BY SL.CD_COMPANY, SL.NO_SO) SL 
		   ON SL.CD_COMPANY = SH.CD_COMPANY AND SL.NO_SO = SH.NO_SO
		   LEFT JOIN V_CZ_SA_QTN_LOG_EMP VE ON VE.CD_COMPANY = SH.CD_COMPANY AND VE.NO_FILE = SH.NO_SO
		   LEFT JOIN CZ_SA_DEFERRED_DELIVERY DD ON DD.CD_COMPANY = SH.CD_COMPANY AND DD.TP_TYPE = '0' AND DD.NO_SO = SH.NO_SO AND DD.NO_KEY = SH.NO_SO AND DD.DT_LIMIT = SL.DT_DUEDATE
		   WHERE ISNULL(SH.YN_CLOSE, 'N') <> 'Y'
		   AND (ISNULL(@P_NO_SO, '') = '' OR SH.NO_SO = @P_NO_SO)
		   GROUP BY SH.CD_COMPANY, SH.CD_PARTNER, SH.CD_PARTNER_GRP, VE.CD_FLAG3) SH
ON SH.CD_COMPANY = AM.CD_COMPANY AND SH.CD_PARTNER = AM.CD_PARTNER AND SH.IDX = 1
LEFT JOIN MA_CODEDTL MC2 ON MC2.CD_COMPANY = MP.CD_COMPANY AND MC2.CD_FIELD = 'MA_B000065' AND MC2.CD_SYSDEF = MP.CD_PARTNER_GRP
WHERE AM.CD_COMPANY = @P_CD_COMPANY
AND AM.TP_PARTNER = '002'
AND (ISNULL(@P_CD_PARTNER, '') = '' OR AM.CD_PARTNER = @P_CD_PARTNER)

GO