USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_AUTO_MAIL_NOT_GR]    Script Date: 2016-01-13 오후 9:02:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
 
ALTER PROCEDURE [NEOE].[SP_CZ_SA_AUTO_MAIL_NOT_GR]    
(            
	@P_CD_COMPANY		NVARCHAR(7),
	@P_CD_PARTNER		NVARCHAR(20),
    @P_QT_LT_OVERDUE    INT,
    @P_NO_PO            NVARCHAR(20),
    @P_NO_EMP           NVARCHAR(20)
)            
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT PH.CD_PARTNER,
       PH.NO_PO,
       PH.NO_ORDER,
       PL.DT_LIMIT,
       PH.DT_PO,
       DATEDIFF(DAY, PH.DT_PO, GETDATE()) AS QT_PO_OVERDUE,
       DATEDIFF(DAY, PL.DT_LIMIT, GETDATE()) AS QT_LT_OVERDUE,
       SH.DC_RMK_TEXT2,
       DD.YN_EXCLUDE,
       DD.YN_URGENT,
       DD.DT_EXPECT,
       DD.TP_SEND,
       DD.DTS_SEND,
       DD.DC_RMK,
       DD.DC_RMK1,
       PH.CD_PJT,
       MH.NM_VESSEL,
       MH.NO_HULL,
       ME.NM_KOR,
       (CASE WHEN DATEDIFF(DAY, PH.DT_PO, GETDATE()) >= 5
                  AND ISNULL(DD.YN_EXCLUDE, 'N') <> 'Y'
                  AND (ISNULL(DD.DT_EXPECT, '') = '' OR DATEDIFF(DAY, DD.DT_EXPECT, GETDATE()) >= 2)
                  AND (ISNULL(DD.DTS_SEND, '') = '' OR DATEDIFF(DAY, LEFT(DD.DTS_SEND, 8), GETDATE()) >= 1) THEN 'Y' ELSE 'N' END) AS YN_SEND
FROM PU_POH PH
JOIN (SELECT PL.CD_COMPANY, PL.NO_PO,
             MAX(PL.DT_LIMIT) AS DT_LIMIT
      FROM PU_POL PL
      WHERE 1=1
      AND PL.QT_PO > ISNULL(PL.QT_RCV, 0)
      AND PL.CD_ITEM NOT LIKE 'SD%'
      AND EXISTS (SELECT 1 
                  FROM SA_SOL SL
                  WHERE SL.CD_COMPANY = PL.CD_COMPANY
                  AND SL.NO_SO = PL.NO_SO
                  AND SL.SEQ_SO = PL.NO_SOLINE
                  AND ISNULL(SL.QT_SO, 0) > ISNULL(SL.QT_GIR, 0)) -- 협조전작성건 제외
      GROUP BY PL.CD_COMPANY, PL.NO_PO) PL 
ON PL.CD_COMPANY = PH.CD_COMPANY AND PL.NO_PO = PH.NO_PO
LEFT JOIN SA_SOH SH ON SH.CD_COMPANY = PH.CD_COMPANY AND SH.NO_SO = PH.CD_PJT
LEFT JOIN CZ_SA_DEFERRED_DELIVERY DD ON DD.CD_COMPANY = PH.CD_COMPANY AND DD.TP_TYPE = '2' AND DD.NO_SO = PH.CD_PJT AND DD.NO_KEY = PH.NO_PO AND DD.DT_LIMIT = PL.DT_LIMIT
LEFT JOIN CZ_MA_HULL MH ON MH.NO_IMO = SH.NO_IMO
LEFT JOIN V_CZ_SA_QTN_LOG_EMP VE ON VE.CD_COMPANY = SH.CD_COMPANY AND VE.NO_FILE = SH.NO_SO
LEFT JOIN MA_EMP ME ON ME.CD_COMPANY = VE.CD_COMPANY AND ME.NO_EMP = VE.CD_FLAG1
WHERE PH.CD_COMPANY = @P_CD_COMPANY
AND PH.CD_PARTNER = @P_CD_PARTNER
AND DATEDIFF(DAY, PL.DT_LIMIT, GETDATE()) >= ISNULL(@P_QT_LT_OVERDUE, 0)
AND SH.DT_SO BETWEEN DATEADD(YEAR, -3, GETDATE()) AND CONVERT(CHAR(8), GETDATE(), 112) -- 3년치 수주
AND ISNULL(SH.YN_CLOSE, 'N') <> 'Y' -- 수주마감제외
AND LEFT(PH.NO_PO, 2) NOT IN ('SB', 'NS', 'BE', 'TE', 'HB') -- SB, NB, BE, TE, HB 제외
AND (ISNULL(@P_NO_PO, '') = '' OR PH.NO_PO LIKE @P_NO_PO + '%')
AND (ISNULL(@P_NO_EMP, '') = '' OR VE.CD_FLAG1 = @P_NO_EMP)
ORDER BY DATEDIFF(DAY, PL.DT_LIMIT, GETDATE()) DESC

GO