USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_FI_TAX_MNG_U]    Script Date: 2015-08-18 오후 5:59:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER PROCEDURE [NEOE].[SP_CZ_FI_TAX_MNG_U] 
(
	@P_CD_COMPANY		NVARCHAR(7),
	@P_NO_IV			NVARCHAR(20),
	@P_NO_IO			NVARCHAR(20),
	@P_NO_SO			NVARCHAR(20),
	@P_AM_TAX_EX		NUMERIC(19, 4),
	@P_AM_TAX		    NUMERIC(19, 4),
	@P_DT_LOADING		NVARCHAR(8),
	@P_DT_VAT			NVARCHAR(8),
	@P_TP_EXPORT		NVARCHAR(3),
	@P_DC_RMK			NVARCHAR(550),
	@P_ID_UPDATE		NVARCHAR(15)
) 
AS

IF EXISTS (SELECT 1 FROM CZ_FI_TAX WHERE CD_COMPANY = @P_CD_COMPANY AND NO_IV = @P_NO_IV AND NO_IO = @P_NO_IO AND NO_SO = @P_NO_SO)
BEGIN
	UPDATE CZ_FI_TAX
	SET DT_LOADING = @P_DT_LOADING,
		DT_VAT = @P_DT_VAT,
		TP_EXPORT = @P_TP_EXPORT,
		AM_TAX_EX = @P_AM_TAX_EX,
		AM_TAX = @P_AM_TAX,
		DC_RMK = @P_DC_RMK,
		ID_UPDATE = @P_ID_UPDATE,
		DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE())
	WHERE CD_COMPANY = @P_CD_COMPANY
	AND NO_IV = @P_NO_IV
	AND NO_IO = @P_NO_IO
	AND NO_SO = @P_NO_SO
END
ELSE
BEGIN
	INSERT INTO CZ_FI_TAX
	(
		CD_COMPANY,
		NO_IV,
		NO_IO,
		NO_SO,
		DT_LOADING,
		DT_VAT,
		TP_EXPORT,
		AM_TAX_EX,
		AM_TAX,
		DC_RMK,
		ID_INSERT,
		DTS_INSERT
	)
	VALUES
	(
		@P_CD_COMPANY,
		@P_NO_IV,
		@P_NO_IO,
		@P_NO_SO,
		@P_DT_LOADING,
		@P_DT_VAT,
		@P_TP_EXPORT,
		@P_AM_TAX_EX,
		@P_AM_TAX,
		@P_DC_RMK,
		@P_ID_UPDATE,
		NEOE.SF_SYSDATE(GETDATE())
	)
END

GO