USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_PU_IV_AUTO_MNGL2_S]    Script Date: 2016-11-17 오후 5:00:32 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
    
ALTER PROCEDURE [NEOE].[SP_CZ_PU_IV_AUTO_MNGL2_S]        
(             
	@P_CD_COMPANY           NVARCHAR(7),
	@P_CD_PARTNER			NVARCHAR(20),
	@P_DT_MONTH				NVARCHAR(6),
	@P_IDX					INT,
	@P_NO_FILE				NVARCHAR(20)
)        
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT EL.CD_PARTNER,
	   EL.DT_MONTH,
	   EL.IDX,
	   EL.SEQ,
	   EL.NO_FILE,
	   EL.AM,
	   EL.VAT,
	   EL.DC_RMK
FROM CZ_PU_ETAX_DETAILL EL
WHERE EL.CD_COMPANY = @P_CD_COMPANY
AND EL.CD_PARTNER = @P_CD_PARTNER
AND EL.DT_MONTH = @P_DT_MONTH
AND EL.IDX = @P_IDX
AND (ISNULL(@P_NO_FILE, '') = '' OR EL.NO_FILE = @P_NO_FILE)
ORDER BY SEQ

GO