USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_PU_IV_AUTO_MNGH_S]    Script Date: 2016-11-17 오후 5:00:32 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_PU_IV_AUTO_MNGH_S]        
(             
	@P_CD_COMPANY           NVARCHAR(7),
	@P_DT_START				NVARCHAR(8),
	@P_DT_END				NVARCHAR(8),
	@P_CD_PARTNER			NVARCHAR(20),
	@P_NO_ETAX				NVARCHAR(30),
	@P_TP_READ				NVARCHAR(3),
	@P_CLS_PARTNER			NVARCHAR(4)
)        
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT 'N' AS S,
       EH.NO_ETAX,
	   EH.NO_COMPANY,
	   MC.NM_SYSDEF AS NM_CLS_PARTNER,
	   MP.CD_PARTNER,
	   MP.LN_PARTNER,
	   EH.DT_SEND,
	   EH.AM,
	   EH.VAT,
	   ISNULL(MC2.NM_SYSDEF, EH.DC_REASON) AS DC_REASON,
	   EH.DC_RMK1,
	   EH.DC_RMK2,
	   EH.PLATFORM,
	   EH.NO_FILE,
	   EH.NO_IO,
	   IH.NO_IV,
	   FD.NO_DOCU,
	   (CASE WHEN EH.YN_READ = 'C' OR (IH.NO_IV IS NOT NULL AND FD.NO_DOCU IS NOT NULL) THEN EH.YN_READ 
																						ELSE NULL END) AS YN_READ,
	   (CASE WHEN EH.YN_READ = 'C' THEN '임의처리'
	         WHEN EH.YN_READ = 'A' AND IH.NO_IV IS NOT NULL AND FD.NO_DOCU IS NOT NULL THEN '자동매입'
			 WHEN EH.YN_READ = 'M' AND IH.NO_IV IS NOT NULL AND FD.NO_DOCU IS NOT NULL THEN '수동매입'
		     ELSE NULL END) AS TP_READ,
	   (CASE WHEN MC1.NM_SYSDEF IS NULL THEN 'N' ELSE 'Y' END) AS YN_MONTHLY,
	   EH.DC_LOG,
	   EH.NO_FILE_SEND,
	   EH.DTS_INSERT,
	   EH.DTS_UPDATE,
	   IC.NO_EMP,
	   IC.NO_PO,
	   IC.DC_RMK,
	   IC.DC_RMK_WF,
	   (CASE WHEN EXISTS (SELECT 1 
				          FROM MA_FILEINFO MF
				          WHERE MF.CD_COMPANY = EH.CD_COMPANY 
				          AND MF.CD_MODULE = 'CZ' 
				          AND MF.ID_MENU = 'P_CZ_PU_IV_AUTO_MNG' 
				          AND MF.CD_FILE = EH.NO_ETAX) THEN 'Y' ELSE 'N' END) AS YN_FILE
FROM CZ_PU_ETAXH EH
LEFT JOIN MA_PARTNER MP ON MP.CD_COMPANY = EH.CD_COMPANY AND MP.NO_COMPANY = EH.NO_COMPANY
LEFT JOIN PU_IVH IH ON IH.CD_COMPANY = EH.CD_COMPANY AND IH.NO_IV = EH.NO_IV
LEFT JOIN (SELECT CD_COMPANY, NO_DOCU 
		   FROM FI_DOCU
		   GROUP BY CD_COMPANY, NO_DOCU) FD 
ON FD.CD_COMPANY = EH.CD_COMPANY AND FD.NO_DOCU = EH.NO_DOCU
LEFT JOIN MA_CODEDTL MC ON MC.CD_COMPANY = MP.CD_COMPANY AND MC.CD_FIELD = 'MA_B000003' AND MC.CD_SYSDEF = MP.CLS_PARTNER
LEFT JOIN CZ_MA_CODEDTL MC1 ON MC1.CD_COMPANY = MP.CD_COMPANY AND MC1.CD_FIELD = 'CZ_PU00009' AND MC1.CD_SYSDEF = MP.CD_PARTNER
LEFT JOIN CZ_PU_IV_CONFIRM IC ON IC.CD_COMPANY = EH.CD_COMPANY AND IC.TP_CONFIRM = '002' AND IC.NO_ETAX = EH.NO_ETAX
LEFT JOIN MA_CODEDTL MC2 ON MC2.CD_COMPANY = EH.CD_COMPANY AND MC2.CD_FIELD = 'FI_T000029' AND MC2.CD_SYSDEF = EH.DC_REASON
WHERE EH.CD_COMPANY = @P_CD_COMPANY
AND EH.DT_SEND BETWEEN @P_DT_START AND @P_DT_END
AND (ISNULL(@P_CD_PARTNER, '') = '' OR MP.CD_PARTNER = @P_CD_PARTNER)
AND	(ISNULL(@P_CLS_PARTNER, '') = '' OR MP.CLS_PARTNER = @P_CLS_PARTNER)
AND (ISNULL(@P_NO_ETAX, '') = '' OR EH.NO_ETAX = @P_NO_ETAX)
AND (ISNULL(@P_TP_READ, '') = '' OR 
	 (@P_TP_READ = '001' AND (EH.YN_READ = 'C' OR (EH.YN_READ IN ('A', 'M') AND IH.NO_IV IS NOT NULL AND FD.NO_DOCU IS NOT NULL))) OR 
	 (@P_TP_READ = '002' AND (ISNULL(EH.YN_READ, 'N') = 'N' OR (EH.YN_READ IN ('A', 'M') AND (IH.NO_IV IS NULL OR FD.NO_DOCU IS NULL)))))

GO