USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_PU_IV_AUTOH_D]    Script Date: 2016-03-30 오후 1:48:31 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
           
ALTER PROCEDURE [NEOE].[SP_CZ_PU_IV_AUTOH_D]                
(
	@P_CD_COMPANY           NVARCHAR(7),
	@P_CD_PARTNER			NVARCHAR(20),
	@P_DT_MONTH				NVARCHAR(6),
	@P_IDX					INT
)                
AS                

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

DELETE FROM CZ_PU_ETAX_DETAILL
WHERE CD_COMPANY = @P_CD_COMPANY
AND CD_PARTNER = @P_CD_PARTNER
AND DT_MONTH = @P_DT_MONTH
AND IDX = @P_IDX

DELETE FROM CZ_PU_ETAX_DETAILH
WHERE CD_COMPANY = @P_CD_COMPANY
AND CD_PARTNER = @P_CD_PARTNER
AND DT_MONTH = @P_DT_MONTH
AND IDX = @P_IDX

GO