USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_CUST_REL_MNG_MEETING_MEMO_S]    Script Date: 2017-05-31 오후 4:11:05 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER PROCEDURE [NEOE].[SP_CZ_SA_CRM_PARTNER_MEETING_MEMO_S]
(
	@P_CD_COMPANY		NVARCHAR(7),
	@P_CD_PARTNER		NVARCHAR(20)
) 
AS
 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT MT.CD_COMPANY,
	   MT.NO_MEETING,
	   MT.DT_MEETING,
	   MT.DC_TIME,
	   MT.DC_LOCATION,
	   MT.DC_SUBJECT,
	   MT.DC_PURPOSE,
	   MT.DC_MEETING,
	   GW.NO_DOCU,
	   BT.NO_DOCU AS NO_DOCU1,
	   GW.ST_STAT,
	   MC.NM_SYSDEF AS NM_GW_STAT,
	   BT.ST_STAT AS ST_STAT1,
	   MC1.NM_SYSDEF AS NM_GW_STAT1,
	   MF.QT_FILE,
	   GW.ID_WRITE,
	   BT.ID_WRITE AS ID_WRITE1,
	   STUFF((SELECT DISTINCT ',' + AT.NM_ATTENDEE
			  FROM CZ_SA_MEETING_ATTENDEE AT
			  WHERE AT.CD_COMPANY = MT.CD_COMPANY
			  AND AT.CD_PARTNER = MT.CD_PARTNER
			  AND AT.NO_MEETING = MT.NO_MEETING
			  AND AT.TP_INOUT = 'OUT'
			  FOR XML PATH('')),1,1,'') AS NM_OUT_ATTENDEE,
	  STUFF((SELECT DISTINCT ',' + AT.NM_ATTENDEE
			  FROM CZ_SA_MEETING_ATTENDEE AT
			  WHERE AT.CD_COMPANY = MT.CD_COMPANY
			  AND AT.NO_MEETING = MT.NO_MEETING
			  AND AT.TP_INOUT = 'IN'
			  FOR XML PATH('')),1,1,'') AS NM_IN_ATTENDEE
FROM CZ_SA_MEETING_MEMO MT
LEFT JOIN FI_GWDOCU GW ON GW.CD_COMPANY = 'K100' AND GW.CD_PC = '010000' AND GW.NO_DOCU = MT.CD_COMPANY + '-' + MT.NO_GW_DOCU
LEFT JOIN MA_CODEDTL MC ON MC.CD_COMPANY = GW.CD_COMPANY AND MC.CD_FIELD = 'PU_C000065' AND MC.CD_SYSDEF = GW.ST_STAT
LEFT JOIN (SELECT CD_COMPANY, CD_MODULE, ID_MENU, CD_FILE,
				  COUNT(1) AS QT_FILE
		   FROM MA_FILEINFO
		   GROUP BY CD_COMPANY, CD_MODULE, ID_MENU, CD_FILE) MF 
ON MF.CD_COMPANY = MT.CD_COMPANY AND MF.CD_MODULE = 'SA' AND MF.ID_MENU = 'P_CZ_SA_MEETING_MEMO_MNG' AND MF.CD_FILE = MT.NO_MEETING
LEFT JOIN (SELECT BT.CD_COMPANY,
		   	      BT.NO_MEETING,
		   	      BT.ST_STAT, 
		   	      BT.NO_DOCU, 
		   	      BT.ID_WRITE 
		   FROM (SELECT BT.CD_COMPANY,
		   	  	        BT.NO_MEETING,
		   	  	        GW.ST_STAT, 
		   	  	        GW.NO_DOCU, 
		   	  	        GW.ID_WRITE,
		   	  	        ROW_NUMBER() OVER (PARTITION BY BT.CD_COMPANY, BT.NO_MEETING ORDER BY BT.DTS_INSERT DESC) AS IDX
		   	     FROM CZ_SA_BUSINESS_TRIP_MEETING BT
		   	     LEFT JOIN FI_GWDOCU GW ON GW.CD_COMPANY = 'K100' AND GW.CD_PC = '010000' AND GW.NO_DOCU = BT.CD_COMPANY + '-' + BT.NO_BIZ_TRIP) BT
		   WHERE BT.IDX = 1) BT
ON BT.CD_COMPANY = MT.CD_COMPANY AND BT.NO_MEETING = MT.NO_MEETING
LEFT JOIN MA_CODEDTL MC1 ON MC1.CD_COMPANY = BT.CD_COMPANY AND MC1.CD_FIELD = 'PU_C000065' AND MC1.CD_SYSDEF = BT.ST_STAT
WHERE MT.CD_COMPANY = @P_CD_COMPANY
AND MT.CD_PARTNER = @P_CD_PARTNER

GO