USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_CRM_PARTNER_SUPPLIERL_S]    Script Date: 2018-06-01 오후 6:15:23 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




ALTER PROCEDURE [NEOE].[SP_CZ_SA_CRM_PARTNER_SUPPLIERD_S]
(
	@P_CD_COMPANY		NVARCHAR(7),
	@P_CD_PARTNER		NVARCHAR(20),
	@P_CD_SUPPLIER		NVARCHAR(20),
	@P_CD_ITEM			NVARCHAR(20),
	@P_DT_START			NVARCHAR(8),
	@P_DT_END			NVARCHAR(8)
) 
AS
 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT QL1.CD_PARTNER AS CD_SUPPLIER,
	   ISNULL(QL.CD_ITEM, '') AS CD_ITEM,
	   QL.NO_FILE,
	   QL3.DT_QTN,
	   QL3.LN_PARTNER,
	   QL3.NM_VESSEL,
	   QL.NO_LINE,
	   QL3.NO_DSP,
	   QL3.NM_SUBJECT,
	   QL3.CD_ITEM_PARTNER,
	   QL3.NM_ITEM_PARTNER,
	   QL.QT,
	   (ISNULL(QL.UM_KR, 0) - ISNULL(QL1.UM_KR, 0)) AS UM_MINUS,
	   (ISNULL(QL.LT, 0) - ISNULL(QL1.LT, 0)) AS LT_MINUS,
	   QL.YN_CHOICE,
	   QL.NM_EXCH,
	   QL.RT_EXCH,
	   QL.UM_EX,
	   QL.UM_KR,
	   QL.LT,
	   QL.DC_RMK_QTN,
	   QL1.YN_CHOICE AS YN_CHOICE1,
	   QL1.NM_EXCH AS NM_EXCH1,
	   QL1.RT_EXCH AS RT_EXCH1,
	   QL1.UM_EX AS UM_EX1,
	   QL1.UM_KR AS UM_KR1,
	   QL1.LT AS LT1,
	   QL1.DC_RMK_QTN AS DC_RMK_QTN1,
	   QL2.LN_PARTNER AS NM_SUPPLIER_CHOICE,
	   QL2.NM_EXCH AS NM_EXCH2,
	   QL2.RT_EXCH AS RT_EXCH2,
	   QL2.UM_EX AS UM_EX2,
	   QL2.UM_KR AS UM_KR2,
	   QL2.LT AS LT2,
	   QL2.DC_RMK_QTN AS DC_RMK_QTN2 
FROM (SELECT QH.CD_COMPANY, QH.CD_PARTNER, QH.NO_FILE, QL.NO_LINE,
			 (CASE WHEN MI.CLS_ITEM = '009' THEN QL.CD_ITEM ELSE NULL END) AS CD_ITEM,
			 QL.QT,
			 QL.YN_CHOICE,
			 MC.NM_SYSDEF AS NM_EXCH,
			 QH.RT_EXCH,
			 QL.UM_EX,
			 QL.UM_KR,
			 QL.LT,
			 QH.DC_RMK_QTN 
	  FROM CZ_PU_QTNH QH
	  LEFT JOIN MA_CODEDTL MC ON MC.CD_COMPANY = QH.CD_COMPANY AND MC.CD_FIELD = 'MA_B000005' AND MC.CD_SYSDEF = QH.CD_EXCH
	  JOIN CZ_PU_QTNL QL ON QL.CD_COMPANY = QH.CD_COMPANY AND QL.CD_PARTNER = QH.CD_PARTNER AND QL.NO_FILE = QH.NO_FILE
	  LEFT JOIN MA_PITEM MI ON MI.CD_COMPANY = QL.CD_COMPANY AND MI.CD_ITEM = QL.CD_ITEM
	  WHERE QH.CD_COMPANY = @P_CD_COMPANY
      AND QH.DT_QTN BETWEEN @P_DT_START AND @P_DT_END
      AND QH.CD_PARTNER = @P_CD_PARTNER
	  AND ISNULL(QL.CD_ITEM, '') NOT LIKE 'SD%'
	  AND ISNULL(QL.AM_KR, 0) <> 0) QL
JOIN (SELECT QH.CD_COMPANY, QH.CD_PARTNER, QH.NO_FILE, QL.NO_LINE,
			 QL.YN_CHOICE,
			 MC.NM_SYSDEF AS NM_EXCH,
			 QH.RT_EXCH,
			 QL.UM_EX,
			 QL.UM_KR,
			 QL.LT,
			 QH.DC_RMK_QTN 
	  FROM CZ_PU_QTNH QH
	  LEFT JOIN MA_CODEDTL MC ON MC.CD_COMPANY = QH.CD_COMPANY AND MC.CD_FIELD = 'MA_B000005' AND MC.CD_SYSDEF = QH.CD_EXCH
	  JOIN CZ_PU_QTNL QL ON QL.CD_COMPANY = QH.CD_COMPANY AND QL.CD_PARTNER = QH.CD_PARTNER AND QL.NO_FILE = QH.NO_FILE
	  WHERE QH.CD_PARTNER = @P_CD_SUPPLIER
	  AND ISNULL(QL.AM_KR, 0) <> 0) QL1 
ON QL1.CD_COMPANY = QL.CD_COMPANY AND QL1.NO_FILE = QL.NO_FILE AND QL1.NO_LINE = QL.NO_LINE
LEFT JOIN (SELECT QH.CD_COMPANY, QH.CD_PARTNER, QH.NO_FILE, QL.NO_LINE,
		   	      MP.LN_PARTNER, 
		   	      MC.NM_SYSDEF AS NM_EXCH,
		   	      QH.RT_EXCH,
		   	      QL.UM_EX,
		   	      QL.UM_KR,
		   	      QL.LT,
		   	      QH.DC_RMK_QTN 
		   FROM CZ_PU_QTNH QH
		   LEFT JOIN MA_CODEDTL MC ON MC.CD_COMPANY = QH.CD_COMPANY AND MC.CD_FIELD = 'MA_B000005' AND MC.CD_SYSDEF = QH.CD_EXCH
		   LEFT JOIN MA_PARTNER MP ON MP.CD_COMPANY = QH.CD_COMPANY AND MP.CD_PARTNER = QH.CD_PARTNER
		   JOIN CZ_PU_QTNL QL ON QL.CD_COMPANY = QH.CD_COMPANY AND QL.CD_PARTNER = QH.CD_PARTNER AND QL.NO_FILE = QH.NO_FILE
		   WHERE ISNULL(QL.YN_CHOICE, 'N') = 'Y'
		   AND ISNULL(QL.AM_KR, 0) <> 0) QL2
ON QL2.CD_COMPANY = QL.CD_COMPANY AND QL2.NO_FILE = QL.NO_FILE AND QL2.NO_LINE = QL.NO_LINE
JOIN (SELECT QH.CD_COMPANY, QH.NO_FILE, QL.NO_LINE,
			 QH.DT_QTN,
			 MP.LN_PARTNER,
			 MH.NM_VESSEL, 
			 QL.NO_DSP,
			 QL.NM_SUBJECT,
			 QL.CD_ITEM_PARTNER,
			 QL.NM_ITEM_PARTNER
	  FROM CZ_SA_QTNH QH
	  LEFT JOIN MA_PARTNER MP ON MP.CD_COMPANY = QH.CD_COMPANY AND MP.CD_PARTNER = QH.CD_PARTNER
	  LEFT JOIN CZ_MA_HULL MH ON MH.NO_IMO = QH.NO_IMO
	  JOIN CZ_SA_QTNL QL ON QL.CD_COMPANY = QH.CD_COMPANY AND QL.NO_FILE = QH.NO_FILE) QL3 
ON QL3.CD_COMPANY = QL.CD_COMPANY AND QL3.NO_FILE = QL.NO_FILE AND QL3.NO_LINE = QL.NO_LINE
WHERE ISNULL(QL.CD_ITEM, '') = @P_CD_ITEM

GO

