USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_CUST_REL_MNG_PIC_COMMENT_S]    Script Date: 2017-06-08 오후 7:52:31 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




ALTER PROCEDURE [NEOE].[SP_CZ_SA_CRM_PARTNER_TODO_I]
(
	@P_CD_COMPANY	NVARCHAR(7),
	@P_CD_PARTNER	NVARCHAR(20),
	@P_NO_INDEX		NUMERIC(18, 0),
	@P_NO_EMP		NVARCHAR(10),
	@P_NO_TODO		INT,
	@P_ID_USER		NVARCHAR(15)
) 
AS
 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

INSERT INTO CZ_CRM_PARTNER_TODO
(
	CD_COMPANY,
	CD_PARTNER,
	NO_INDEX,
	NO_EMP,
	NO_TODO,
	ID_INSERT,
	DTS_INSERT
)
VALUES
(
	@P_CD_COMPANY,
	@P_CD_PARTNER,
	@P_NO_INDEX,
	@P_NO_EMP,
	@P_NO_TODO,
	@P_ID_USER,
	NEOE.SF_SYSDATE(GETDATE())
)

GO