USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_CRM_PARTNER_STOCKL_S]    Script Date: 2018-05-14 오후 2:05:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER PROCEDURE [NEOE].[SP_CZ_SA_CRM_PARTNER_STOCKL_S]
(
	@P_CD_COMPANY		NVARCHAR(7),
	@P_CD_PARTNER		NVARCHAR(20),
	@P_CD_ITEM			NVARCHAR(20),
	@P_DT_START			NVARCHAR(8),
	@P_DT_END			NVARCHAR(8)
) 
AS
 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT QH.CD_ITEM,
       QH.NO_IMO,
	   MH.NM_VESSEL,
	   QH.DT_QTN,
	   QH.DT_SO,
	   QH.QT_QTN_FILE,
	   QH.QT_STOCK_FILE,
	   QH.QT_QTN,
	   QH.QT_STOCK,
	   ROUND(CASE WHEN ISNULL(QH.QT_QTN_FILE, 0) = 0 THEN 0 
													 ELSE (ISNULL(QH.QT_STOCK_FILE, 0) / ISNULL(QH.QT_QTN_FILE, 0)) * 100 END, 2) AS RT_SO_FILE,
	   ROUND(CASE WHEN ISNULL(QH.QT_QTN, 0) = 0 THEN 0 
											    ELSE (ISNULL(QH.QT_STOCK, 0) / ISNULL(QH.QT_QTN, 0)) * 100 END, 2) AS RT_SO
FROM (SELECT QH.CD_COMPANY, QH.CD_PARTNER, QL.CD_ITEM, QH.NO_IMO,
	  	     MAX(QH.DT_QTN) AS DT_QTN,
	  	     MAX(SH.DT_SO) AS DT_SO,
			 SUM(1.0) AS QT_QTN_FILE,
			 SUM(CASE WHEN SH.CD_COMPANY IS NULL THEN 0 ELSE 1.0 END) AS QT_STOCK_FILE,
	  	     SUM(QL.QT_QTN) AS QT_QTN,
	  	     SUM(QL.QT_STOCK) AS QT_STOCK
	  FROM CZ_SA_QTNH QH
	  LEFT JOIN SA_SOH SH ON SH.CD_COMPANY = QH.CD_COMPANY AND SH.NO_SO = QH.NO_FILE
	  JOIN (SELECT QL.CD_COMPANY, QL.NO_FILE, QL.CD_ITEM,
	  			   SUM(QL.QT_QTN) AS QT_QTN,
	  			   SUM(SB.QT_STOCK) AS QT_STOCK 
	  		FROM CZ_SA_QTNL QL
	  		LEFT JOIN CZ_SA_STOCK_BOOK SB ON SB.CD_COMPANY = QL.CD_COMPANY AND SB.NO_FILE = QL.NO_FILE AND SB.NO_LINE = QL.NO_LINE
			WHERE QL.CD_ITEM = @P_CD_ITEM
	  		GROUP BY QL.CD_COMPANY, QL.NO_FILE, QL.CD_ITEM) QL
	  ON QL.CD_COMPANY = QH.CD_COMPANY AND QL.NO_FILE = QH.NO_FILE
	  WHERE QH.CD_COMPANY = @P_CD_COMPANY
      AND QH.CD_PARTNER = @P_CD_PARTNER
	  AND QH.DT_QTN BETWEEN @P_DT_START AND @P_DT_END
	  GROUP BY QH.CD_COMPANY, QH.CD_PARTNER, QL.CD_ITEM, QH.NO_IMO) QH
LEFT JOIN CZ_MA_HULL MH ON MH.NO_IMO = QH.NO_IMO
ORDER BY QH.QT_QTN DESC

GO

