USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_CRM_PARTNER_VESSEL_SUPPLIER_S]    Script Date: 2017-05-25 오전 10:04:17 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER PROCEDURE [NEOE].[SP_CZ_SA_CRM_PARTNER_VESSEL_SUPPLIER_S]
(
	@P_CD_COMPANY		NVARCHAR(7),
	@P_CD_PARTNER		NVARCHAR(20),
	@P_DT_START			NVARCHAR(8),
	@P_DT_END			NVARCHAR(8)
) 
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT QH.NO_FILE,
       LEFT(QH.NO_FILE, 2) AS NO_PREFIX,
       QH.NO_IMO,
       MH.NM_VESSEL,
       MH.DT_SHIP_DLV,
       (CASE WHEN ISNULL(MH.DC_SHIPBUILDER, '') = '' THEN MC.NM_SYSDEF ELSE MH.DC_SHIPBUILDER END) AS DC_SHIPBUILDER,
       QL.CD_SUPPLIER,
       MP.LN_PARTNER,
       1 AS QT_FILE,
       QL.QT_ITEM,
       QL.QT_QTN,
       QL.AM_QTN,
       (CASE WHEN QL.QT_SO > 0 THEN 1 ELSE 0 END) AS QT_SO_FILE,
       QL.QT_SO,
       QL.AM_SO
FROM CZ_SA_QTNH QH
JOIN (SELECT QL.CD_COMPANY, QL.NO_FILE, QL.CD_SUPPLIER,
             COUNT(1) AS QT_ITEM,
             SUM(QL.QT) AS QT_QTN,
             SUM(QL.AM_KR_S) AS AM_QTN,
             SUM(SL.QT_SO) AS QT_SO,
             SUM(SL.AM_KR_S) AS AM_SO
      FROM CZ_SA_QTNL QL
      LEFT JOIN SA_SOL SL ON SL.CD_COMPANY = QL.CD_COMPANY AND SL.NO_SO = QL.NO_FILE AND SL.SEQ_SO = QL.NO_LINE
      WHERE QL.CD_ITEM NOT LIKE 'SD%'
      GROUP BY QL.CD_COMPANY, QL.NO_FILE, QL.CD_SUPPLIER) QL
ON QL.CD_COMPANY = QH.CD_COMPANY AND QL.NO_FILE = QH.NO_FILE
LEFT JOIN CZ_MA_HULL MH ON MH.NO_IMO = QH.NO_IMO
LEFT JOIN MA_PARTNER MP ON MP.CD_COMPANY = QL.CD_COMPANY AND MP.CD_PARTNER = QL.CD_SUPPLIER
LEFT JOIN MA_CODEDTL MC ON MC.CD_COMPANY = QH.CD_COMPANY AND MC.CD_FIELD = 'CZ_MA00001' AND MC.CD_SYSDEF = MH.TP_SHIP_YARD
WHERE QH.CD_COMPANY = @P_CD_COMPANY
AND QH.CD_PARTNER = @P_CD_PARTNER
AND ISNULL(QH.DT_QTN, '') BETWEEN @P_DT_START AND @P_DT_END

GO

