USE [NEOE]
GO
/****** Object:  StoredProcedure [NEOE].[SP_CZ_PR_OPOUT_PR_SCH_SUB_S1]    Script Date: 2022-10-19 오후 5:46:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO




ALTER PROCEDURE [NEOE].[SP_CZ_PR_OPOUT_PR_SCH_SUB_S1]  
(  
    @P_CD_COMPANY   NVARCHAR(7),   
	@P_CD_PLANT     NVARCHAR(7),   
	@P_NO_PR		NVARCHAR(20)
)  
AS  

SELECT 
	A.CD_COMPANY
,	A.CD_PLANT
,	A.NO_PR
,	A.NO_LINE
,	A.NO_WO
,	C.NM_TP_WO
,	A.CD_OP
,	A.CD_WC
,	D.NM_WC
,	A.CD_WCOP
,	E.NM_OP
,	A.CD_ITEM
,	F.NM_ITEM
,	F.STND_ITEM
,	F.NO_DESIGN
,	F.UNIT_IM
,	A.QT_PR
,	A.CD_PARTNER
,	ISNULL(G.LN_PARTNER,'') AS LN_PARTNER
FROM CZ_PR_OPOUT_PR A
JOIN PR_WO B ON B.CD_COMPANY = A.CD_COMPANY AND B.CD_PLANT = A.CD_PLANT  AND B.NO_WO = A.NO_WO
LEFT JOIN PR_TPWO C ON C.CD_COMPANY = B.CD_COMPANY AND C.TP_WO = B.TP_ROUT
LEFT JOIN MA_WC D ON D.CD_COMPANY = A.CD_COMPANY AND D.CD_PLANT = A.CD_PLANT AND D.CD_WC = A.CD_WC
LEFT JOIN PR_WCOP E ON E.CD_COMPANY = A.CD_COMPANY AND E.CD_PLANT = A.CD_PLANT AND E.CD_WC = A.CD_WC AND E.CD_WCOP = A.CD_WCOP
LEFT JOIN MA_PITEM F ON F.CD_COMPANY = A.CD_COMPANY AND F.CD_PLANT = A.CD_PLANT AND F.CD_ITEM = A.CD_ITEM
LEFT JOIN MA_PARTNER G ON G.CD_COMPANY = A.CD_COMPANY AND G.CD_PARTNER = A.CD_PARTNER
WHERE A.CD_COMPANY = @P_CD_COMPANY
AND A.CD_PLANT = @P_CD_PLANT
AND A.NO_PR = @P_NO_PR

