USE [NEOE]
GO

/****** Object:  Table [NEOE].[CZ_SA_EWS_CONDITION_BACKUP]    Script Date: 2020-02-04 오전 9:59:36 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [NEOE].[CZ_SA_EWS_CONDITION_BACKUP](
	[CD_COMPANY] [nvarchar](7) NOT NULL,
	[DT_BACKUP] [nvarchar](8) NOT NULL,
	[YN_SIMULATION] [nvarchar](1) NOT NULL,
	[TP_GUBUN] [nvarchar](1) NOT NULL,
	[CD_EWS] [nvarchar](10) NOT NULL,
	[DC_EWS] [nvarchar](200) NULL,
	[DC_EWS1] [nvarchar](200) NULL,
	[DC_EWS2] [nvarchar](50) NULL,
	[DC_EWS3] [nvarchar](50) NULL,
	[YN_USE] [nvarchar](1) NULL,
	[ID_INSERT] [nvarchar](15) NULL,
	[DTS_INSERT] [nvarchar](14) NULL,
	[ID_UPDATE] [nvarchar](15) NULL,
	[DTS_UPDATE] [nvarchar](14) NULL,
 CONSTRAINT [PK_CZ_SA_EWS_CONDITION_BACKUP] PRIMARY KEY CLUSTERED 
(
	[CD_COMPANY] ASC,
	[DT_BACKUP] ASC,
	[YN_SIMULATION] ASC,
	[TP_GUBUN] ASC,
	[CD_EWS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


