USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_VSSL_ETRYNDH]    Script Date: 2018-11-21 오후 4:25:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER PROCEDURE [NEOE].[SP_CZ_SA_VSSL_ETRYNDH]
(
    @P_CD_PRTAG					NVARCHAR(3), 
	@P_NM_PRTAG					NVARCHAR(10), 
	@P_DT_ETRYPT_YEAR			NVARCHAR(4), 
	@P_CNT_ETRYPT				NVARCHAR(3), 
	@P_CLSGN					NVARCHAR(10), 
	@P_NM_VSSL					NVARCHAR(20), 
	@P_CD_VSSL_NLTY				NVARCHAR(2), 
	@P_NM_VSSL_NLTY				NVARCHAR(10), 
	@P_NM_VSSL_KND				NVARCHAR(10), 
	@P_CD_ETRYPT_PURPS			NVARCHAR(2), 
	@P_NM_ETRYPT_PURPS			NVARCHAR(3), 
    @P_CD_FRST_DPMPRT_NAT_PRT	NVARCHAR(5), 
	@P_NM_FRST_DPMPRT_PRT		NVARCHAR(10), 
	@P_CD_PRVS_DPMPRT_NAT_PRT	NVARCHAR(5), 
	@P_NM_PRVS_DPMPRT_PRT		NVARCHAR(10), 
	@P_CD_NX_INPT_NAT_PRT		NVARCHAR(5), 
	@P_NM_NX_INPT_PRT			NVARCHAR(10), 
	@P_CD_DSTN_NAT_PRT			NVARCHAR(5),
	@P_NM_DSTN_PRT			    NVARCHAR(10)
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

IF EXISTS (SELECT 1 
		   FROM CZ_SA_VSSL_ETRYNDH
		   WHERE CD_PRTAG = @P_CD_PRTAG
		   AND DT_ETRYPT_YEAR = @P_DT_ETRYPT_YEAR
		   AND CNT_ETRYPT = @P_CNT_ETRYPT
		   AND CLSGN = @P_CLSGN
		   AND NM_VSSL = @P_NM_VSSL)
BEGIN
	IF EXISTS (SELECT 1 
		       FROM CZ_SA_VSSL_ETRYNDH
		       WHERE CD_PRTAG = @P_CD_PRTAG
		       AND DT_ETRYPT_YEAR = @P_DT_ETRYPT_YEAR
		       AND CNT_ETRYPT = @P_CNT_ETRYPT
		       AND CLSGN = @P_CLSGN
		       AND NM_VSSL = @P_NM_VSSL
			   AND (CD_VSSL_NLTY <> @P_CD_VSSL_NLTY 
				 OR NM_VSSL_NLTY <> @P_NM_VSSL_NLTY 
			     OR NM_VSSL_KND <> @P_NM_VSSL_KND 
			     OR CD_ETRYPT_PURPS <> @P_CD_ETRYPT_PURPS 
			     OR NM_ETRYPT_PURPS <> @P_NM_ETRYPT_PURPS 
			     OR CD_FRST_DPMPRT_NAT_PRT <> @P_CD_FRST_DPMPRT_NAT_PRT 
			     OR NM_FRST_DPMPRT_PRT <> @P_NM_FRST_DPMPRT_PRT 
			     OR CD_PRVS_DPMPRT_NAT_PRT <> @P_CD_PRVS_DPMPRT_NAT_PRT 
			     OR NM_PRVS_DPMPRT_PRT <> @P_NM_PRVS_DPMPRT_PRT 
			     OR CD_NX_INPT_NAT_PRT <> @P_CD_NX_INPT_NAT_PRT
			     OR NM_NX_INPT_PRT <> @P_NM_NX_INPT_PRT 
			     OR CD_DSTN_NAT_PRT <> @P_CD_DSTN_NAT_PRT 
			     OR NM_DSTN_PRT <> @P_NM_DSTN_PRT))
    BEGIN
		UPDATE CZ_SA_VSSL_ETRYNDH
		SET CD_VSSL_NLTY = @P_CD_VSSL_NLTY, 
			NM_VSSL_NLTY = @P_NM_VSSL_NLTY, 
			NM_VSSL_KND = @P_NM_VSSL_KND, 
			CD_ETRYPT_PURPS = @P_CD_ETRYPT_PURPS, 
			NM_ETRYPT_PURPS = @P_NM_ETRYPT_PURPS, 
		    CD_FRST_DPMPRT_NAT_PRT = @P_CD_FRST_DPMPRT_NAT_PRT, 
			NM_FRST_DPMPRT_PRT = @P_NM_FRST_DPMPRT_PRT, 
			CD_PRVS_DPMPRT_NAT_PRT = @P_CD_PRVS_DPMPRT_NAT_PRT, 
			NM_PRVS_DPMPRT_PRT = @P_NM_PRVS_DPMPRT_PRT, 
			CD_NX_INPT_NAT_PRT = @P_CD_NX_INPT_NAT_PRT, 
			NM_NX_INPT_PRT = @P_NM_NX_INPT_PRT, 
			CD_DSTN_NAT_PRT = @P_CD_DSTN_NAT_PRT, 
		    NM_DSTN_PRT = @P_NM_DSTN_PRT,
			DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE())
		WHERE CD_PRTAG = @P_CD_PRTAG
		AND DT_ETRYPT_YEAR = @P_DT_ETRYPT_YEAR
		AND CNT_ETRYPT = @P_CNT_ETRYPT
		AND CLSGN = @P_CLSGN
		AND NM_VSSL = @P_NM_VSSL
	END 
END
ELSE
BEGIN
	INSERT INTO CZ_SA_VSSL_ETRYNDH
	(
		CD_PRTAG, 
		NM_PRTAG, 
		DT_ETRYPT_YEAR, 
		CNT_ETRYPT, 
		CLSGN, 
		NM_VSSL, 
		CD_VSSL_NLTY, 
		NM_VSSL_NLTY, 
		NM_VSSL_KND, 
		CD_ETRYPT_PURPS, 
		NM_ETRYPT_PURPS, 
        CD_FRST_DPMPRT_NAT_PRT, 
		NM_FRST_DPMPRT_PRT, 
		CD_PRVS_DPMPRT_NAT_PRT, 
		NM_PRVS_DPMPRT_PRT, 
		CD_NX_INPT_NAT_PRT, 
		NM_NX_INPT_PRT, 
		CD_DSTN_NAT_PRT, 
        NM_DSTN_PRT, 
		DTS_INSERT,
		CALL_SIGN
	)
	VALUES
	(
		@P_CD_PRTAG, 
		@P_NM_PRTAG, 
		@P_DT_ETRYPT_YEAR, 
		@P_CNT_ETRYPT, 
		@P_CLSGN, 
		@P_NM_VSSL, 
		@P_CD_VSSL_NLTY, 
		@P_NM_VSSL_NLTY, 
		@P_NM_VSSL_KND, 
		@P_CD_ETRYPT_PURPS, 
		@P_NM_ETRYPT_PURPS, 
        @P_CD_FRST_DPMPRT_NAT_PRT, 
		@P_NM_FRST_DPMPRT_PRT, 
		@P_CD_PRVS_DPMPRT_NAT_PRT, 
		@P_NM_PRVS_DPMPRT_PRT, 
		@P_CD_NX_INPT_NAT_PRT, 
		@P_NM_NX_INPT_PRT, 
		@P_CD_DSTN_NAT_PRT, 
        @P_NM_DSTN_PRT, 
		NEOE.SF_SYSDATE(GETDATE()),
		REPLACE(@P_CLSGN, '/', '')
	)
END

IF EXISTS (SELECT 1 
		   FROM CZ_MA_HULL
		   WHERE CALL_SIGN = REPLACE(@P_CLSGN, '/', '')
		   AND (YN_DOM IS NULL OR YN_DOM = 'N'))
BEGIN
	UPDATE CZ_MA_HULL
	SET YN_DOM = 'Y',
	    ID_UPDATE = 'SYSTEM',
		DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE())
	WHERE CALL_SIGN = REPLACE(@P_CLSGN, '/', '')
END

GO

