USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_H_CZ_HR_PEVALU_OBJECT_SUB]    Script Date: 2015-10-12 오후 4:55:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER PROCEDURE [NEOE].[SP_H_CZ_HR_PEVALU_OBJECT_SUB]
(
	@P_CD_COMPANY      NVARCHAR(7),
	@P_LANGUAGE		   NVARCHAR(5) = 'KR',
	@P_CD_FLAG1		   NVARCHAR(3),
	@P_CD_FLAG2		   NVARCHAR(3),
	@P_SEARCH		   NVARCHAR(MAX)
) 
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
 
BEGIN 
    SELECT MC1.CD_SYSDEF AS CODE1,
		   (CASE @P_LANGUAGE WHEN 'KR' THEN MC1.NM_SYSDEF
						     WHEN 'US' THEN MC1.NM_SYSDEF_E
						     WHEN 'JP' THEN MC1.NM_SYSDEF_JP
						     WHEN 'CH' THEN MC1.NM_SYSDEF_CH END) AS NAME1,
		   MC2.CD_SYSDEF AS CODE2,
		   (CASE @P_LANGUAGE WHEN 'KR' THEN MC2.NM_SYSDEF
						     WHEN 'US' THEN MC2.NM_SYSDEF_E
						     WHEN 'JP' THEN MC2.NM_SYSDEF_JP
						     WHEN 'CH' THEN MC2.NM_SYSDEF_CH END) AS NAME2,
		   MC3.CD_SYSDEF AS CODE3,
		   (CASE @P_LANGUAGE WHEN 'KR' THEN MC3.NM_SYSDEF
							 WHEN 'US' THEN MC3.NM_SYSDEF_E
							 WHEN 'JP' THEN MC3.NM_SYSDEF_JP
							 WHEN 'CH' THEN MC3.NM_SYSDEF_CH END) AS NAME3
  FROM MA_CODEDTL MC1
  LEFT JOIN MA_CODEDTL MC2 ON MC2.CD_COMPANY = MC1.CD_COMPANY AND MC2.CD_FIELD = 'CZ_HR00001' AND MC2.CD_SYSDEF = MC1.CD_FLAG1
  LEFT JOIN MA_CODEDTL MC3 ON MC3.CD_COMPANY = MC1.CD_COMPANY AND MC3.CD_FIELD = 'CZ_HR00003' AND MC3.CD_SYSDEF = MC1.CD_FLAG2
  WHERE MC1.CD_COMPANY = @P_CD_COMPANY
  AND MC1.CD_FIELD = 'CZ_HR00002'
  AND (ISNULL(@P_CD_FLAG1, '') = '' OR MC1.CD_FLAG1 = @P_CD_FLAG1)
  AND (ISNULL(@P_CD_FLAG2, '') = '' OR MC1.CD_FLAG2 = @P_CD_FLAG2)
  AND (ISNULL(@P_SEARCH, '') = '' OR MC1.NM_SYSDEF LIKE '%' + @P_SEARCH + '%' OR MC1.CD_SYSDEF LIKE '%' + @P_SEARCH + '%')
END

GO