USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_H_CZ_MA_HULL_SUB]    Script Date: 2015-07-01 오후 6:41:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER PROCEDURE [NEOE].[SP_H_CZ_MA_HULL_SUB]
(
	@P_CD_COMPANY      NVARCHAR(7),
	@P_CD_PARTNER	   NVARCHAR(20),
	@P_SEARCH		   NVARCHAR(MAX)
) 
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
 
SELECT MH.NO_IMO, 
       MH.NO_HULL, 
       MH.NM_VESSEL,
	   MP.CD_PARTNER,
	   MP.LN_PARTNER,
	   MP.CD_PARTNER_GRP,
	   MH.INVOICE_COMPANY,
	   MP.USE_YN,
	   MH.DT_SHIP_DLV,
	   MH.YN_NEWSHIP
FROM CZ_MA_HULL MH
LEFT JOIN MA_PARTNER MP ON MP.CD_COMPANY = @P_CD_COMPANY AND MP.CD_PARTNER = MH.CD_PARTNER
WHERE (ISNULL(@P_CD_PARTNER, '') = '' OR MH.CD_PARTNER = @P_CD_PARTNER)
AND (ISNULL(@P_SEARCH, '') = '' OR MH.NO_IMO LIKE '%' + @P_SEARCH + '%' OR MH.NO_HULL LIKE '%' + @P_SEARCH + '%' OR MH.NM_VESSEL LIKE '%' + @P_SEARCH + '%')

GO