USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_H_CZ_MA_CODE_SUB]    Script Date: 2015-10-28 오후 3:37:14 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER PROCEDURE [NEOE].[SP_H_CZ_MA_CODE_SUB]
(
	@P_CD_COMPANY      NVARCHAR(7),
	@P_CD_FIELD		   NVARCHAR(10),
	@P_LANGUAGE		   NVARCHAR(5) = 'KR',
	@P_HELP_ID		   NVARCHAR(30),
	@P_P61_CODE1	   NVARCHAR(50),
	@P_SEARCH		   NVARCHAR(MAX)
) 
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

IF @P_HELP_ID = 'P_CZ_MA_HULL'
BEGIN
	SELECT CD_SYSDEF AS CODE,
		   (CASE @P_LANGUAGE WHEN 'KR' THEN NM_SYSDEF
		   		             WHEN 'US' THEN NM_SYSDEF_E
		   		             WHEN 'JP' THEN NM_SYSDEF_JP  
		   	                 WHEN 'CH' THEN NM_SYSDEF_CH END) AS NAME,
		   CD_FLAG2
	FROM MA_CODEDTL
	WHERE CD_COMPANY = @P_CD_COMPANY
	AND USE_YN = 'Y'
	AND CD_FIELD = @P_CD_FIELD
	AND CD_FLAG1 = @P_P61_CODE1
	AND (ISNULL(@P_SEARCH, '') = '' OR (CASE @P_LANGUAGE WHEN 'KR' THEN NM_SYSDEF
		   									             WHEN 'US' THEN NM_SYSDEF_E
		   									             WHEN 'JP' THEN NM_SYSDEF_JP  
		   									             WHEN 'CH' THEN NM_SYSDEF_CH END) LIKE '%' + @P_SEARCH + '%')
END
ELSE
BEGIN
	SELECT CD_SYSDEF AS CODE,
		   (CASE @P_LANGUAGE WHEN 'KR' THEN NM_SYSDEF
		   		             WHEN 'US' THEN NM_SYSDEF_E
		   		             WHEN 'JP' THEN NM_SYSDEF_JP  
		   	                 WHEN 'CH' THEN NM_SYSDEF_CH END) AS NAME
	FROM MA_CODEDTL
	WHERE CD_COMPANY = @P_CD_COMPANY
	AND USE_YN = 'Y'
	AND CD_FIELD = @P_CD_FIELD
	AND (ISNULL(@P_SEARCH, '') = '' OR (CASE @P_LANGUAGE WHEN 'KR' THEN NM_SYSDEF
		   									             WHEN 'US' THEN NM_SYSDEF_E
		   									             WHEN 'JP' THEN NM_SYSDEF_JP  
		   									             WHEN 'CH' THEN NM_SYSDEF_CH END) LIKE '%' + @P_SEARCH + '%')
END

GO