USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_H_CZ_SA_USER_SUB]    Script Date: 2015-07-01 오후 5:55:53 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER PROCEDURE [NEOE].[SP_H_CZ_SA_USER_SUB]
(
	@P_CD_COMPANY       NVARCHAR(MAX),
	@P_LANGUAGE			NVARCHAR(5) = 'KR',
	@P_TP_BIZ			NVARCHAR(2),
	@P_CD_INCOM			NVARCHAR(3),
	@P_SEARCH           NVARCHAR(MAX)
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT SU.CD_COMPANY,
	   (CASE WHEN @P_LANGUAGE = 'KR' THEN MC.NM_COMPANY ELSE MC.EN_COMPANY END) NM_COMPANY,
	   SU.TP_BIZ,
	   (SELECT (CASE @P_LANGUAGE WHEN 'KR' THEN NM_SYSDEF
								 WHEN 'US' THEN NM_SYSDEF_E
								 WHEN 'JP' THEN NM_SYSDEF_JP
								 WHEN 'CH' THEN NM_SYSDEF_CH END)
		FROM MA_CODEDTL
		WHERE CD_COMPANY = SU.CD_COMPANY
		AND CD_FIELD = 'CZ_SA00024'
		AND CD_SYSDEF = SU.TP_BIZ) AS NM_TP_BIZ,
	   SU.ID_USER,
	   (CASE WHEN @P_LANGUAGE = 'KR' THEN ME.NM_KOR
			 WHEN @P_LANGUAGE = 'US' THEN ME.NM_ENG
			 WHEN @P_LANGUAGE = 'JP' THEN ME.NM_KOR  
			 WHEN @P_LANGUAGE = 'CH' THEN ME.NM_CHIN END) NM_USER 
FROM CZ_SA_USER SU
LEFT JOIN MA_USER MU ON MU.CD_COMPANY = SU.CD_COMPANY AND MU.ID_USER = SU.ID_USER
LEFT JOIN MA_EMP ME ON ME.CD_COMPANY = MU.CD_COMPANY AND ME.NO_EMP = MU.NO_EMP
LEFT JOIN MA_COMPANY MC ON MC.CD_COMPANY = SU.CD_COMPANY
WHERE 1=1 
AND (ISNULL(@P_CD_COMPANY, '') = '' OR ISNULL(@P_CD_COMPANY, '|') = '|' OR SU.CD_COMPANY IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_COMPANY)))
AND (ISNULL(@P_TP_BIZ, '') = '' OR SU.TP_BIZ = @P_TP_BIZ)
AND (ISNULL(@P_SEARCH, '') = '' OR SU.ID_USER LIKE '%' + @P_SEARCH + '%' OR MU.NM_USER LIKE '%' + @P_SEARCH + '%')
AND (ISNULL(@P_CD_INCOM, '') = '' OR ME.CD_INCOM = @P_CD_INCOM)
GO