USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_ATTENDANCE_SUB_S]    Script Date: 2017-06-12 오후 5:30:22 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_H_CZ_FI_PARTNERPTR_SUB]
(
	@P_CD_COMPANY      NVARCHAR(7),
	@P_CD_PARTNER	   NVARCHAR(20),
	@P_SEARCH		   NVARCHAR(MAX)
) 
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT FP.CD_PARTNER,
	   MP.LN_PARTNER,
	   FP.SEQ,
	   FP.NM_PTR,
	   FP.EN_PTR,
	   FP.NM_DEPT,
	   FP.NM_DUTY_RESP,
	   FP.EN_DUTY_RESP,
	   FP.NO_HP,
	   FP.NM_EMAIL,
	   FP.NO_FAX,
	   FP.NO_TEL,
	   FP.CLIENT_NOTE
FROM FI_PARTNERPTR FP
JOIN MA_PARTNER MP ON MP.CD_COMPANY = FP.CD_COMPANY AND MP.CD_PARTNER = FP.CD_PARTNER
WHERE FP.CD_COMPANY = @P_CD_COMPANY
AND (ISNULL(@P_CD_PARTNER, '') = '' OR FP.CD_PARTNER = @P_CD_PARTNER)
AND (ISNULL(@P_SEARCH, '') = '' OR FP.NM_PTR LIKE @P_SEARCH + '%')

GO

