USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_RCPBILL_S]    Script Date: 2016-04-28 오후 3:20:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/*******************************************
**  System	: 영업관리
**  Sub System	: 선수금정리
**  Page	: 
**  Desc	: 
**
**  Return Values
**
**  수 정 내 용	: 
*********************************************
** Change History
*********************************************
*********************************************/

ALTER PROCEDURE [NEOE].[SP_CZ_SA_RCPBILL_S]
(
    @CD_COMPANY                 NVARCHAR(7),
    @NO_BILLS                   NVARCHAR(20)
)
AS
BEGIN

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

/* 페이지:선수금정리
   기 능:조회
   작성자:이승훈
   외화선수금정리기능및환차손처리컬럼추가20080813
*/

SELECT /*A.CD_COMPANY,*/
	   A.NO_BILLS AS NO_BILLS, --NO_RCPBILL, 
	   A.DT_BILLS AS DT_BILLS, --DT_RCPBILL,
	   A.CD_BILLTGRP AS CD_BILLTGRP, --CD_SALEGRP,
	   E.NM_SALEGRP,
	   A.CD_PARTNER,
	   B.LN_PARTNER AS NM_PARTNER,
       A.BILL_PARTNER,
	   C.LN_PARTNER AS NM_BILL_PARTNER,
	   A.NO_EMP,
	   D.NM_KOR,
	   A.TP_BUSI,
	   A.AM_BILLS AS AM_BILLS, --AM_RCPBILL,
	   A.AM_IV,
	   A.DC_RMK,
	   ISNULL(A.ST_BILL, 'N') AS ST_BILL,
	   ISNULL(A.CD_TP, '')    AS CD_TP,
	   A.TP_BILLS,
       A.CD_DOCU,
	-- DTS_INSERT,
    -- ID_INSERT,
    -- DTS_UPDATE,
    -- ID_UPDATE,
	   ISNULL((SELECT TOP 1 FD.NO_DOCU   
			   FROM FI_DOCU FD WITH(READUNCOMMITTED)
			   WHERE FD.CD_COMPANY = A.CD_COMPANY                     
			   AND FD.NO_MDOCU = A.NO_BILLS), '') NO_DOCU, -- 2011-04-20, 이승훈 추가함.                          
	   CC.CD_PC AS CD_PC                
FROM SA_BILLSH A 
LEFT JOIN MA_PARTNER B ON B.CD_COMPANY = A.CD_COMPANY AND B.CD_PARTNER = A.CD_PARTNER
LEFT JOIN MA_PARTNER C ON C.CD_COMPANY = A.CD_COMPANY AND C.CD_PARTNER = A.BILL_PARTNER
LEFT JOIN MA_EMP D ON D.CD_COMPANY = A.CD_COMPANY AND D.NO_EMP = A.NO_EMP
LEFT JOIN MA_SALEGRP E ON E.CD_COMPANY = A.CD_COMPANY AND E.CD_SALEGRP = A.CD_BILLTGRP
LEFT JOIN MA_CC CC ON E.CD_COMPANY = CC.CD_COMPANY AND E.CD_CC = CC.CD_CC	
WHERE A.CD_COMPANY = @CD_COMPANY
AND A.NO_BILLS = @NO_BILLS

SELECT /*A.CD_COMPANY,*/
	   A.NO_BILLS,
	   A.NO_LINE,
	   A.NO_RCP,
	   B.DT_RCP,
	   A.AM_BILLS AS AM_BILLS, --AM_RCPS,
	   A.AM_TARGET,
	   ( A.AM_TARGET - A.AM_BILLS ) AS AM_REMAIN,
	   A.CD_EXCH,
	   ( SELECT NM_SYSDEF FROM MA_CODEDTL WHERE CD_FIELD = 'MA_B000005' AND CD_COMPANY = A.CD_COMPANY AND CD_SYSDEF = A.CD_EXCH ) CD_EXCH_NAME, --환종명
	   A.RT_EXCH,
	   A.AM_TARGET_EX,  
	   A.AM_BILLS_EX,
	   NO_MGMT,
	   B.FG_MAP,
	   A.CD_PJT,
	   A.NO_DOCU,
	   A.NO_DOLINE
FROM SA_BILLSL A 
JOIN SA_RCPH B ON B.CD_COMPANY = A.CD_COMPANY AND B.NO_RCP = A.NO_RCP
WHERE A.CD_COMPANY = @CD_COMPANY
AND A.NO_BILLS   = @NO_BILLS

SELECT /*A.CD_COMPANY,*/
       A.NO_BILLS,
       A.NO_IV,
       A.DT_IV,
       (ISNULL(B.AM_K, 0) + ISNULL(C.AM_K, 0)) AS AM_IV,
       (ISNULL(B.VAT_TAX, 0) + ISNULL(C.VAT, 0)) AS AM_VAT,
       A.AM_TARGET,
	   ( A.AM_TARGET - A.AM_RCPS ) AS AM_REMAIN,
       A.AM_RCPS AS AM_RCPS, --AM_BAN,
       A.GUBUN,
	   --A.CD_EXCH_IV,
	   ( SELECT NM_SYSDEF FROM MA_CODEDTL WHERE CD_FIELD = 'MA_B000005' AND CD_COMPANY = A.CD_COMPANY AND CD_SYSDEF = A.CD_EXCH_IV ) CD_EXCH_IV, --환종명
	   A.RT_EXCH_IV,
	   A.AM_TARGET_EX,
	   A.AM_RCPS_EX,
	   A.AM_PL,
	   CASE WHEN SIGN(A.AM_PL) = 1   THEN 0 - (A.AM_PL) ELSE 0 END AS AM_PL_LOSS,
	   CASE WHEN SIGN(A.AM_PL) = -1  THEN 0 - (A.AM_PL) ELSE 0 END AS AM_PL_PROFIT,
	   A.NO_RCP,
	   A.NO_DOCU_RCP,
	   A.NO_DOLINE_RCP,
	   A.NO_DOCU_IV,
	   A.NO_DOLINE_IV,
	   A.TP_SO
FROM SA_BILLSD A
LEFT JOIN SA_IVH B ON A.CD_COMPANY = B.CD_COMPANY AND A.NO_IV = B.NO_IV
LEFT JOIN EC_IVH C ON A.CD_COMPANY = C.CD_COMPANY AND A.NO_IV = C.NO_IV
WHERE A.CD_COMPANY = @CD_COMPANY
AND A.NO_BILLS = @NO_BILLS
AND A.GUBUN = '0'

/* 기초선수금반제는논리오류가있다. (보류처리함)
UNION ALL
SELECT A.CD_COMPANY,
       A.NO_BILLS,
       A.NO_IV,
       A.DT_IV,
      

 B.AM_IV AS AM_IV,
       0 AS AM_VAT,
       A.AM_TARGET,
	   ( A.AM_TARGET - A.AM_RCPS ) AS AM_REMAIN,
       A.AM_RCPS AS AM_BAN,
       A.GUBUN
FROM SA_BILLSD A INNER JOIN SA_BILLSH C
  ON C.CD_COMPANY = A.CD_COMPANY
 AND C.NO_BILLS   = A.NO_BILLS
   

              INNER JOIN SA_AR B
  ON B.CD_COMPANY = C.CD_COMPANY
 AND B.CD_PARTNER = C.CD_PARTNER
 AND B.YYMM = A.NO_IV
WHERE A.CD_COMPANY = @CD_COMPANY
  AND A.NO_BILLS   = @NO_BILLS
  AND A.GUBUN = '1'
*/

END

GO