USE [NEOE]
GO
/****** Object:  StoredProcedure [NEOE].[UP_CZ_PR_OPOUT_WORK_MNG_L_SELECT]    Script Date: 2022-12-09 오후 4:06:14 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO




ALTER PROC [NEOE].[UP_CZ_PR_OPOUT_WORK_MNG_L_SELECT]
(
	@P_CD_COMPANY       NVARCHAR(7), 
	@P_CD_PLANT         NVARCHAR(7), 
	@P_NO_PO            NVARCHAR(20), 
	@P_NO_POLINE        NUMERIC(5, 0), 
    @P_NO_EMP			NVARCHAR(20)	= NULL,
    @P_NO_WO			NVARCHAR(20)	= NULL,
    @P_FG_LANG			NVARCHAR(4) = NULL	--언어
)
AS
-- MultiLang Call
EXEC UP_MA_LOCAL_LANGUAGE @P_FG_LANG


DECLARE @YN_MFG_AUTH	NCHAR(1)
SELECT	@YN_MFG_AUTH  = ISNULL((SELECT	YN_MFG_AUTH
								FROM	MA_ENV
								WHERE	CD_COMPANY = @P_CD_COMPANY ), 'N')

BEGIN
	SELECT	WR.CD_PLANT, WR.DT_WORK, WR.NO_WORK, L.QT_PO, W.QT_ITEM QT_WO, WR.QT_WORK, WR.QT_REJECT, 
			WR.QT_REWORK, WR.QT_MOVE, WR.UM_EX, WR.AM_EX, WR.UM_WORK, WR.AM_WORK, WR.AM_VAT_WORK, WR.AM_HAP_WORK, 
			WR.NO_WO, WR.CD_OP, WR.CD_WC, WR.CD_WCOP, 
			L.NO_PO, L.NO_LINE, 
			A.NM_WC, B.NM_OP,
			P.UNIT_IM,
			L.UNIT_CH,
			L.QT_CHCOEF,
			L.OLD_QT_PO,
			WR.QT_WORK_CHCOEF,
			WR.QT_WORK_BAD_CHCOEF,
			L.UM_EX AS UM_EX_PO, L.UM, L.AM_EX AS AM_EX_PO, L.AM, L.AM_VAT, (L.AM + L.AM_VAT) AS AM_TOTAL,
			WR.DT_LIMIT,
			I.NO_LOT,
			I.CD_MNG1, I.CD_MNG2, I.CD_MNG3, I.CD_MNG4, I.CD_MNG5,
			I.CD_MNG6, I.CD_MNG7, I.CD_MNG8, I.CD_MNG9, I.CD_MNG10,
			I.CD_MNG11, I.CD_MNG12, I.CD_MNG13, I.CD_MNG14, I.CD_MNG15,
			I.CD_MNG16, I.CD_MNG17, I.CD_MNG18, I.CD_MNG19, I.CD_MNG20,
			W.DC_RMK AS DC_RMK_WO,
			WR.DC_RMK1, WR.DC_RMK2, WR.DC_RMK3,
			W.TXT_USERDEF1 AS TXT_USERDEF1_WO,
			R.NO_LINE AS NO_WO_LINE
	FROM PR_OPOUT_POH H
	INNER JOIN PR_OPOUT_POL L ON L.CD_COMPANY = H.CD_COMPANY AND L.CD_PLANT = H.CD_PLANT AND L.NO_PO = H.NO_PO 
	INNER JOIN PR_WO W ON W.CD_COMPANY = L.CD_COMPANY AND W.CD_PLANT = L.CD_PLANT AND W.NO_WO = L.NO_WO
	INNER JOIN PR_WO_ROUT R ON R.CD_COMPANY = L.CD_COMPANY AND R.CD_PLANT = L.CD_PLANT AND R.NO_WO = L.NO_WO AND R.CD_OP = L.CD_OP
	INNER JOIN PR_WORK WR ON WR.CD_COMPANY = L.CD_COMPANY AND WR.CD_PLANT = L.CD_PLANT AND WR.NO_OPOUT_PO = L.NO_PO AND WR.NO_OPOUT_PO_LINE = L.NO_LINE
	LEFT  JOIN CZ_PR_OPOUT_PR O ON L.CD_COMPANY = O.CD_COMPANY AND L.NO_WO = O.NO_WO AND L.CD_OP = O.CD_OP AND O.NO_PR = L.NO_PR
	LEFT  JOIN DZSN_MA_PITEM P ON P.CD_COMPANY = L.CD_COMPANY AND P.CD_PLANT = L.CD_PLANT AND P.CD_ITEM = L.CD_ITEM
	LEFT  JOIN DZSN_MA_WC A ON A.CD_COMPANY = L.CD_COMPANY AND A.CD_PLANT = L.CD_PLANT AND A.CD_WC = L.CD_WC
	LEFT  JOIN DZSN_PR_WCOP B ON B.CD_COMPANY = L.CD_COMPANY AND B.CD_PLANT = L.CD_PLANT AND B.CD_WC = L.CD_WC AND B.CD_WCOP = L.CD_WCOP
	LEFT  JOIN PR_QTIOLOT I ON I.CD_COMPANY = WR.CD_COMPANY AND I.CD_PLANT = WR.CD_PLANT AND I.NO_WO = WR.NO_WO AND I.NO_SRC = WR.NO_WORK
						   AND I.CD_WC  = WR.CD_WC			AND I.CD_WCOP  = WR.CD_WCOP  AND I.CD_OP = WR.CD_OP AND I.NO_LINE_IO = 1
						   AND I.NO_LOT = WR.NO_LOT			AND I.FG_SLIP  = '203'
						   
	WHERE	H.CD_COMPANY = @P_CD_COMPANY
	AND		H.CD_PLANT = @P_CD_PLANT
	AND		H.NO_PO = @P_NO_PO
	AND		L.NO_LINE = @P_NO_POLINE 
	AND		(R.YN_SUBCON = 'Y' OR O.QT_PR > 0)
	AND		(L.NO_WO = @P_NO_WO OR @P_NO_WO = '' OR @P_NO_WO IS NULL)
	AND  (  (@YN_MFG_AUTH <> 'Y' OR  ISNULL(@P_NO_EMP,'') =  '')
		 OR	(@YN_MFG_AUTH =  'Y' AND ISNULL(@P_NO_EMP,'') <> '' AND EXISTS (SELECT	1
																			FROM	MA_MFG_AUTH AUTH
																			WHERE	AUTH.CD_COMPANY = W.CD_COMPANY
																			AND		AUTH.CD_AUTH	= W.TP_ROUT
																			AND		AUTH.FG_AUTH	= 'PR_TPWO'
																			AND		AUTH.NO_EMP		= @P_NO_EMP))	)
	AND  (  (@YN_MFG_AUTH <> 'Y' OR  ISNULL(@P_NO_EMP,'') =  '')
		 OR	(@YN_MFG_AUTH =  'Y' AND ISNULL(@P_NO_EMP,'') <> '' AND EXISTS (SELECT	1
																			FROM	MA_MFG_AUTH AUTH
																			WHERE	AUTH.CD_COMPANY = L.CD_COMPANY
																			AND		AUTH.CD_AUTH	= L.CD_WC
																			AND		AUTH.FG_AUTH	= 'MA_WC'
																			AND		AUTH.NO_EMP		= @P_NO_EMP))	)
END
