USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_PR_DEPT_EQUIP_MNG_S1]    Script Date: 2019-03-26 오전 11:26:39 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_PR_DEPT_EQUIP_MNG_S1]
(
    @P_CD_COMPANY   NVARCHAR(7),
	@P_CD_CC		NVARCHAR(20),
	@P_NO_WO		NVARCHAR(20),
	@P_YN_EQUIP		NVARCHAR(1),
	@P_CD_EQUIP		NVARCHAR(30)
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT WO.NO_WO,
	   WO.DT_REL,
	   WO.CD_ITEM,
	   MI.NM_ITEM,
	   MI.NO_DESIGN,
	   MI.STND_ITEM,
	   WO.QT_ITEM,
	   WR1.NM_OP AS NM_OP_CURR,
	   OP.NM_OP AS NM_OP,
	   WR.CD_EQUIP,
	   EQ.NM_EQUIP,
	   WR.NO_LINE,
	   WR.CD_USERDEF1,
	   ROW_NUMBER() OVER (PARTITION BY WR.CD_EQUIP ORDER BY ISNULL(NULLIF(WR.CD_USERDEF1, ''), '9999') ASC, WO.DT_REL) AS IDX_WORK
FROM PR_WO WO
LEFT JOIN MA_PITEM MI ON MI.CD_COMPANY = WO.CD_COMPANY AND MI.CD_PLANT = WO.CD_PLANT AND MI.CD_ITEM = WO.CD_ITEM
JOIN PR_WO_ROUT WR ON WR.CD_COMPANY = WO.CD_COMPANY AND WR.NO_WO = WO.NO_WO
JOIN PR_WCOP OP ON OP.CD_COMPANY = WR.CD_COMPANY AND OP.CD_PLANT = WR.CD_PLANT AND OP.CD_WC = WR.CD_WC AND OP.CD_WCOP = WR.CD_WCOP
LEFT JOIN PR_EQUIP EQ ON EQ.CD_COMPANY = WR.CD_COMPANY AND EQ.CD_PLANT = WR.CD_PLANT AND EQ.CD_EQUIP = WR.CD_EQUIP
JOIN (SELECT WR.CD_COMPANY,
		     WR.NO_WO,
			 OP.NM_OP,
			 ROW_NUMBER() OVER (PARTITION BY WR.CD_COMPANY, WR.NO_WO ORDER BY WR.CD_OP DESC) AS IDX
	  FROM PR_WO_ROUT WR
	  LEFT JOIN PR_WCOP OP ON OP.CD_COMPANY = WR.CD_COMPANY AND OP.CD_PLANT = WR.CD_PLANT AND OP.CD_WC = WR.CD_WC AND OP.CD_WCOP = WR.CD_WCOP
	  WHERE WR.QT_WIP > 0) WR1 
ON WR1.CD_COMPANY = WO.CD_COMPANY AND WR1.NO_WO = WO.NO_WO AND WR1.IDX = 1
WHERE WO.CD_COMPANY = @P_CD_COMPANY
AND (ISNULL(@P_NO_WO, '') = '' OR WO.NO_WO = @P_NO_WO)
AND OP.CD_CC = @P_CD_CC
AND WR.QT_START > WR.QT_WORK
AND (@P_YN_EQUIP = 'N' OR ISNULL(EQ.CD_EQUIP, '') = '')
AND (ISNULL(@P_CD_EQUIP, '') = '' OR EQ.CD_EQUIP = @P_CD_EQUIP)
ORDER BY WR.CD_EQUIP, ROW_NUMBER() OVER (PARTITION BY WR.CD_EQUIP ORDER BY ISNULL(NULLIF(WR.CD_USERDEF1, ''), '9999') ASC, WO.DT_REL)

GO

