USE [NEOE]
GO

/****** Object:  Table [NEOE].[CZ_PU_POL_HSD]    Script Date: 2022-04-08 ¿ÀÈÄ 4:13:36 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [NEOE].[CZ_PU_POL_HSD](
	[CD_COMPANY] [nvarchar](7) NOT NULL,
	[NO_PO] [nvarchar](20) NOT NULL,
	[NO_LINE] [numeric](5, 0) NOT NULL,
	[DC1] [nvarchar](200) NOT NULL,
	[NO_ORDER] [nvarchar](200) NULL,
	[CD_ITEM] [nvarchar](20) NULL,
	[QT_PO] [numeric](17, 4) NULL,
	[DTS_INSERT] [nvarchar](15) NULL,
 CONSTRAINT [PK_CZ_PU_POL_HSD] PRIMARY KEY CLUSTERED 
(
	[CD_COMPANY] ASC,
	[NO_PO] ASC,
	[NO_LINE] ASC,
	[DC1] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


