USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_MA_PARTNER_D_BEFORE]    Script Date: 2016-07-04 오후 4:19:11 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_MA_PARTNER_D_BEFORE]
(
	@P_CD_COMPANY	NVARCHAR(7),
	@P_CD_PARTNER	NVARCHAR(20),
	@P_NO_COMPANY	NVARCHAR(20),
	@P_MSGID		VARCHAR(10) OUTPUT
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET @P_MSGID = ''

-- ① 영업모듈에 거래처정보가 있는지 검사
IF EXISTS (SELECT  NO_SO FROM SA_SOH WHERE CD_COMPANY = @P_CD_COMPANY AND CD_PARTNER = @P_CD_PARTNER)
BEGIN
	SET @P_MSGID = 'HR_M500093'
	RETURN
END

IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID = OBJECT_ID(N'[NEOE].[PU_POH]') AND OBJECTPROPERTY(ID, N'ISUSERTABLE') = 1)
BEGIN
	-- ② 구매모듈에 거래처정보가 있는지 검사
	IF EXISTS (SELECT NO_PO FROM PU_POH WHERE CD_COMPANY = @P_CD_COMPANY AND CD_PARTNER = @P_CD_PARTNER)
	BEGIN
		SET @P_MSGID = 'HR_M500093'
		RETURN
	END
END

IF EXISTS (SELECT NO_DOCU FROM FI_DOCU WHERE CD_COMPANY = @P_CD_COMPANY AND CD_PARTNER = @P_CD_PARTNER )
BEGIN
	SET @P_MSGID = 'HR_M500093' -- ③ 회계모듈(전표)에 거래처정보가 있는지 검사
	RETURN
END

IF EXISTS (SELECT NO_TAX FROM FI_TAX WHERE CD_COMPANY = @P_CD_COMPANY AND CD_PARTNER = @P_CD_PARTNER )
BEGIN
	SET @P_MSGID = 'HR_M500093' -- ④ 회계모듈(부가세)에 거래처정보가 있는지 검사
	RETURN
END
GO

