USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_MA_PARTNER_D]    Script Date: 2016-07-04 오후 4:13:12 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_MA_PARTNER_D]
(
	@P_CD_COMPANY	NVARCHAR(7),
	@P_CD_PARTNER	NVARCHAR(20),
	@P_ID_UPDATE    NVARCHAR(15)
)
AS

SET NOCOUNT ON

-- 2011.10.12 거래처 로그데이터 삭제시 만들어 줘야 하는 문제로 추가함(SQL만 있음)
INSERT INTO MA_PARTNER_LOG
(
	DTS_INSERT,
	DTS_JOBDATE,		
	ID_USER,
	CD_JOB,
	CD_PARTNER,
	CD_COMPANY,
	LN_PARTNER,
	USE_YN,
	EN_PARTNER,
	FG_PARTNER,
	NM_CEO,
	NO_COMPANY,
	NO_RES,
	TP_JOB,
	CLS_JOB,
	E_MAIL,
	NO_TEL,
	NO_FAX,
	DC_ADS1_H,
	DC_ADS1_D,
	NO_DEPOSIT,
	CD_BANK,
	CD_EMP_PARTNER,
    NO_HPEMP_PARTNER,
	NM_DEPOSIT,
	CD_EMP_SALE,
	DC_ADS2_H,
	DC_ADS2_D,
	NO_TEL2,
	NO_FAX2,
	TP_DEFER
)
SELECT CONVERT(CHAR(8), GETDATE(), 112),
	   NEOE.SF_SYSDATE(GETDATE()),
	   ISNULL(@P_ID_UPDATE,'SYSTEM'),		
	   'D',
	   CD_PARTNER,
	   CD_COMPANY,
	   LN_PARTNER,
	   USE_YN,
	   EN_PARTNER,
	   FG_PARTNER,
	   NM_CEO,
	   NO_COMPANY,
	   NO_RES,
	   TP_JOB,
	   CLS_JOB,
	   E_MAIL,
	   NO_TEL,
	   NO_FAX,
	   DC_ADS1_H,
	   DC_ADS1_D,
	   NO_DEPOSIT,
	   CD_BANK,
	   CD_EMP_PARTNER,
	   NO_HPEMP_PARTNER,
	   NM_DEPOSIT,
	   CD_EMP_SALE,
	   DC_ADS2_H,
	   DC_ADS2_D,
	   NO_TEL2,
	   NO_FAX2,
	   TP_DEFER
FROM MA_PARTNER
WHERE CD_COMPANY = @P_CD_COMPANY
AND	CD_PARTNER = @P_CD_PARTNER

-- 삭제
DELETE FROM MA_PARTNER
WHERE CD_COMPANY = @P_CD_COMPANY 
AND CD_PARTNER = @P_CD_PARTNER

DELETE FROM CZ_MA_PARTNER
WHERE CD_COMPANY = @P_CD_COMPANY 
AND CD_PARTNER = @P_CD_PARTNER

DELETE FROM CZ_SRM_PARTNER
WHERE CD_COMPANY = @P_CD_COMPANY 
AND CD_PARTNER = @P_CD_PARTNER

DELETE FROM MA_PARTNER_DEPOSIT
WHERE CD_COMPANY = @P_CD_COMPANY 
AND CD_PARTNER = @P_CD_PARTNER

DELETE FROM CZ_MA_PARTNER_DEPOSIT
WHERE CD_COMPANY = @P_CD_COMPANY 
AND CD_PARTNER = @P_CD_PARTNER

DELETE FROM FI_PARTNERPTR
WHERE CD_COMPANY = @P_CD_COMPANY 
AND CD_PARTNER = @P_CD_PARTNER

--DELETE FROM MA_PARTNER_HTYD
--WHERE CD_COMPANY = @P_CD_COMPANY 
--AND CD_PARTNER = @P_CD_PARTNER

SET NOCOUNT OFF
GO

