USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_SO_MONTHLY_REPORT_S]    Script Date: 2015-06-01 오전 10:19:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_SA_SO_MONTHLY_REPORT_S]
(
	@P_CD_COMPANY	    NVARCHAR(7)
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

DECLARE @T_MONTH NVARCHAR(2) = RIGHT(CONVERT(NVARCHAR(6), GETDATE(), 112), 2);

WITH PC
AS
(
	SELECT CD_COMPANY,
		   TP_PLAN,
		   CD_KEY,
		   (CASE WHEN @T_MONTH = '01' THEN AM_TOT_JAN 
		         WHEN @T_MONTH = '02' THEN AM_TOT_FEB
		         WHEN @T_MONTH = '03' THEN AM_TOT_MAR
		         WHEN @T_MONTH = '04' THEN AM_TOT_APR
		         WHEN @T_MONTH = '05' THEN AM_TOT_MAY
		         WHEN @T_MONTH = '06' THEN AM_TOT_JUN
		         WHEN @T_MONTH = '07' THEN AM_TOT_JUL
		         WHEN @T_MONTH = '08' THEN AM_TOT_AUG
		         WHEN @T_MONTH = '09' THEN AM_TOT_SEP
		         WHEN @T_MONTH = '10' THEN AM_TOT_OCT
		         WHEN @T_MONTH = '11' THEN AM_TOT_NOV
		         WHEN @T_MONTH = '12' THEN AM_TOT_DEC END) AS AM_MONTHWON
	FROM CZ_SA_PTR_PLAN
	WHERE CD_COMPANY = @P_CD_COMPANY
	AND YY_PLAN = CONVERT(NVARCHAR(4), GETDATE(), 112)
	AND TP_PLAN = '0'
),
A AS
(
	SELECT MC.CD_CC,
	       MC.NM_CC,
		   SH.AM_SO,
		   SH.AM_SO_OVER,
		   CONVERT(FLOAT, PC.AM_MONTHWON) AS AM_MONTHWON
	FROM MA_CC MC
	LEFT JOIN (SELECT SH.CD_COMPANY,
					  MS.CD_CC,
					  SUM(CASE WHEN LEFT(SH.DT_CONTRACT, 6) = CONVERT(NVARCHAR(6), GETDATE(), 112) THEN (CASE WHEN ST.RET = 'Y' THEN -SL.AM_SO ELSE SL.AM_SO END) ELSE 0.0 END) AS AM_SO,
			          SUM(CASE WHEN LEFT(SH.DT_CONTRACT, 6) > CONVERT(NVARCHAR(6), GETDATE(), 112) THEN (CASE WHEN ST.RET = 'Y' THEN -SL.AM_SO ELSE SL.AM_SO END) ELSE 0.0 END) AS AM_SO_OVER
			   FROM SA_SOH SH
			   LEFT JOIN SA_TPSO ST ON ST.CD_COMPANY = SH.CD_COMPANY AND ST.TP_SO = SH.TP_SO
			   LEFT JOIN MA_SALEGRP MS ON MS.CD_COMPANY = SH.CD_COMPANY AND MS.CD_SALEGRP = SH.CD_SALEGRP
			   JOIN (SELECT SL.CD_COMPANY, SL.NO_SO,
					 	    SUM(CASE WHEN (ISNULL(EJ.YN_AM, 'N') = 'Y' OR SL.TP_GI IN ('250', '251')) THEN SL.AM_WONAMT ELSE 0 END) AS AM_SO
					 FROM SA_SOL SL
					 LEFT JOIN MA_PITEM MI ON MI.CD_COMPANY = SL.CD_COMPANY AND MI.CD_PLANT = SL.CD_PLANT AND MI.CD_ITEM = SL.CD_ITEM
					 LEFT JOIN MM_EJTP EJ ON EJ.CD_COMPANY = SL.CD_COMPANY AND EJ.CD_QTIOTP = SL.TP_GI
					 WHERE ISNULL(MI.CLS_ITEM, '') <> '010'
					 GROUP BY SL.CD_COMPANY, SL.NO_SO) SL
			   ON SL.CD_COMPANY = SH.CD_COMPANY AND SL.NO_SO = SH.NO_SO
			   WHERE SH.CD_COMPANY = @P_CD_COMPANY
			   AND LEFT(SH.DT_CONTRACT, 6) >= CONVERT(NVARCHAR(6), GETDATE(), 112) 
			   AND (LEFT(SH.NO_SO, 3) = 'ENG' OR EXISTS (SELECT 1 
														 FROM MA_CODEDTL MD1 
														 WHERE MD1.CD_COMPANY = SH.CD_COMPANY 
														 AND MD1.CD_FIELD = 'CZ_SA00023' 
														 AND MD1.CD_SYSDEF NOT IN ('00', 'ZZ', 'T-', 'CL', 'CN', 'CS') 
														 AND MD1.CD_SYSDEF = LEFT(SH.NO_SO, 2)))
			   GROUP BY SH.CD_COMPANY, MS.CD_CC) SH
	ON SH.CD_COMPANY = MC.CD_COMPANY AND SH.CD_CC = MC.CD_CC
	JOIN PC ON PC.CD_COMPANY = MC.CD_COMPANY AND PC.TP_PLAN = '0' AND PC.CD_KEY = MC.CD_CC
	WHERE MC.CD_COMPANY = @P_CD_COMPANY
),
B AS
(
	SELECT '000' AS TP_COLOR,
		   A.CD_CC,
		   A.NM_CC,
		   A.AM_SO,
		   A.AM_MONTHWON,
		   ROUND((A.AM_SO / A.AM_MONTHWON) * 100, 2) AS RT_MONTH,
		   A.AM_SO_OVER
	FROM A
	UNION ALL
	SELECT '001' AS TP_COLOR,
		   '999999' AS CD_CC,
		   '총계' AS NM_CC,
		   SUM(A.AM_SO) AS AM_SO,
		   SUM(A.AM_MONTHWON) AS AM_MONTHWON,
		   ROUND((SUM(A.AM_SO) / SUM(A.AM_MONTHWON)) * 100, 2)AS RT_MONTH,
		   SUM(A.AM_SO_OVER) AS AM_SO_OVER
	FROM A
)
SELECT B.TP_COLOR,
       B.NM_CC,
	   B.AM_SO,
	   B.AM_MONTHWON,
	   B.RT_MONTH,
	   B.AM_SO_OVER
FROM B
ORDER BY B.CD_CC

GO