USE [NEOE]
GO

/****** Object:  Table [NEOE].[CZ_LN_CURR_FORECAST]    Script Date: 2019-06-25 오후 5:47:17 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [NEOE].[CZ_LN_CURR_FORECAST](
	[TP_GUBUN] [nvarchar](100) NOT NULL,
	[DT_QUARTER] [nvarchar](10) NOT NULL,
	[DT_MONTH] [nvarchar](10) NOT NULL,
	[RT_USD] [nvarchar](50) NULL,
	[DTS_INSERT] [nvarchar](14) NULL,
	[DTS_UPDATE] [nvarchar](14) NULL,
 CONSTRAINT [PK_CZ_LN_CURR_FORECAST] PRIMARY KEY CLUSTERED 
(
	[TP_GUBUN] ASC,
	[DT_QUARTER] ASC,
	[DT_MONTH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


