USE [NEOE]
GO

/****** Object:  Table [NEOE].[CZ_LN_CURR_YEAR]    Script Date: 2019-06-07 오후 4:41:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [NEOE].[CZ_LN_CURR_YEAR](
	[YEAR] [nvarchar](4) NOT NULL,
	[GDP_K] [nvarchar](50) NULL,
	[GDP_US] [nvarchar](50) NULL,
	[DTS_INSERT] [nvarchar](14) NULL,
	[DTS_UPDATE] [nvarchar](14) NULL,
 CONSTRAINT [PK_CZ_LN_CURR_YEAR] PRIMARY KEY CLUSTERED 
(
	[YEAR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

