USE [NEOE]
GO

/****** Object:  Table [NEOE].[CZ_LN_CURR_QUARTER]    Script Date: 2019-06-07 오후 4:41:14 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [NEOE].[CZ_LN_CURR_QUARTER](
	[QUARTER] [nvarchar](5) NOT NULL,
	[EC_R_K] [nvarchar](50) NULL,
	[EC_R_US] [nvarchar](50) NULL,
	[DTS_INSERT] [nvarchar](14) NULL,
	[DTS_UPDATE] [nvarchar](14) NULL,
 CONSTRAINT [PK_CZ_LN_CURR_QUARTER] PRIMARY KEY CLUSTERED 
(
	[QUARTER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

