USE [NEOE]
GO

/****** Object:  Table [NEOE].[CZ_HR_WBARCODE]    Script Date: 2020-12-31 오전 9:30:32 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [NEOE].[CZ_HR_WBARCODE](
	[CD_COMPANY] [nvarchar](7) NOT NULL,
	[NO_CARD] [nvarchar](40) NOT NULL,
	[DT_WORK] [nvarchar](8) NOT NULL,
	[TM_CARD] [nvarchar](6) NOT NULL,
	[CD_WCODE] [nvarchar](3) NULL,
	[DTS_INSERT] [nvarchar](14) NULL,
	[ID_INSERT] [nvarchar](15) NULL,
	[DTS_UPDATE] [nvarchar](14) NULL,
	[ID_UPDATE] [nvarchar](15) NULL,
	[CD_USERDEF1] [nvarchar](100) NULL,
	[CD_TM] [nvarchar](3) NULL,
 CONSTRAINT [PK_CZ_HR_WBARCODE] PRIMARY KEY CLUSTERED 
(
	[CD_COMPANY] ASC,
	[NO_CARD] ASC,
	[DT_WORK] ASC,
	[TM_CARD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

