USE [NEOE]
GO
/****** Object:  StoredProcedure [NEOE].[SP_CZ_PR_ASSEMBLING_MNGD_S]    Script Date: 2023-04-25 오후 2:28:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_PR_ASSEMBLING_MNGD_S]          
(
	@P_CD_COMPANY		NVARCHAR(7),
	@P_NO_WO			NVARCHAR(20),
	@P_NO_LINE          NVARCHAR(5),
	@P_YN_ASSEMBLE      NVARCHAR(1)
)  
AS
   
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

DECLARE @V_COLUMN_PV NVARCHAR(MAX)
DECLARE @V_COLUMN NVARCHAR(MAX)
DECLARE @V_QUERY NVARCHAR(MAX)

;WITH tblA (CD_PITEM, QT_ITEM) AS
(
	SELECT AI.CD_PITEM, AI.QT_ITEM
	FROM PR_WO WO
	LEFT JOIN CZ_PR_ASSEMBLING_ITEM AI ON AI.CD_COMPANY = WO.CD_COMPANY AND AI.CD_PLANT = WO.CD_PLANT AND AI.CD_ITEM = WO.CD_ITEM
	WHERE WO.CD_COMPANY = @P_CD_COMPANY
	AND WO.NO_WO = @P_NO_WO
)
, tblB (CD_PITEM, QT_ITEM, SEQ) AS
(
	SELECT 
		A.CD_PITEM
	,	A.QT_ITEM
	,	1
	FROM tblA A
	UNION ALL
	SELECT
		A.CD_PITEM
	,	A.QT_ITEM
	,	A.SEQ + 1
	FROM tblB A
	WHERE A.SEQ + 1 <= A.QT_ITEM
)
, A AS
(
SELECT
	A.CD_PITEM + '_' + CONVERT(NVARCHAR, A.SEQ) AS CD_PITEM
,	A.SEQ
FROM tblB A
)
SELECT @V_COLUMN_PV = 'PV.[' + STRING_AGG(A.CD_PITEM, '],PV.[') + ']',
	   @V_COLUMN = '[' + STRING_AGG(A.CD_PITEM, '],[') + ']'
FROM A

SET @V_QUERY = ';WITH A AS
(
	SELECT WO.CD_COMPANY,
		   WO.CD_PLANT,
		   WO.NO_WO,
		   WD.SEQ_WO,
		   WD.NO_ID,
		   WO.CD_ITEM,
		   AI.CD_PITEM +' + '''_''' + '+ CONVERT(NVARCHAR, AD.SEQ_ITEM) AS CD_PITEM,
		   AD.NO_ID_C
	FROM PR_WO WO
	JOIN CZ_PR_WO_REQ_D WD ON WD.CD_COMPANY = WO.CD_COMPANY AND WD.NO_WO = WO.NO_WO
	LEFT JOIN CZ_PR_ASSEMBLING_ITEM AI ON AI.CD_COMPANY = WO.CD_COMPANY AND AI.CD_PLANT = WO.CD_PLANT AND AI.CD_ITEM = WO.CD_ITEM
	LEFT JOIN CZ_PR_ASSEMBLING_DATA AD ON AD.CD_COMPANY = WO.CD_COMPANY AND AD.CD_PLANT = WO.CD_PLANT AND AD.NO_ID = WD.NO_ID AND AD.CD_PITEM = AI.CD_PITEM
	WHERE WO.CD_COMPANY = ''' + @P_CD_COMPANY + '''
	AND WO.NO_WO = ''' + @P_NO_WO + '''
)
SELECT ''N'' AS S,
	   PV.NO_WO,
	   PV.CD_PLANT,'
     + @P_NO_LINE + ' AS NO_LINE,
	   PV.SEQ_WO,
	   PV.NO_ID,
	   PV.CD_ITEM,
	   WI.NO_SO,
	   WI.DC_RMK,
	   WI.TXT_OPENING,
	   WI.TXT_VENTING,
	   WI.TXT_SHIM,
	   AD.DT_ASSEMBLE,'
	   + @V_COLUMN_PV +
'FROM A
 PIVOT(MAX(A.NO_ID_C) FOR A.CD_PITEM IN (' + @V_COLUMN + ')) AS PV
 LEFT JOIN CZ_PR_WO_INSP WI ON WI.CD_COMPANY = PV.CD_COMPANY AND WI.NO_WO = PV.NO_WO AND WI.SEQ_WO = PV.SEQ_WO AND WI.NO_INSP = 996
 LEFT JOIN (SELECT AI.CD_COMPANY, AI.CD_ITEM,
                   COUNT(1) AS QT_ITEM       
            FROM CZ_PR_ASSEMBLING_ITEM AI
            GROUP BY AI.CD_COMPANY, AI.CD_ITEM) AI
 ON AI.CD_COMPANY = PV.CD_COMPANY AND AI.CD_ITEM = PV.CD_ITEM
 LEFT JOIN (SELECT AD.CD_COMPANY, AD.CD_PLANT, AD.NO_WO, AD.NO_LINE, AD.SEQ_WO,
                   COUNT(1) AS QT_DATA,
				   MAX(AD.DT_ASSEMBLE) AS DT_ASSEMBLE
            FROM CZ_PR_ASSEMBLING_DATA AD
            GROUP BY AD.CD_COMPANY, AD.CD_PLANT, AD.NO_WO, AD.NO_LINE, AD.SEQ_WO) AD
 ON AD.CD_COMPANY = WI.CD_COMPANY AND AD.CD_PLANT = PV.CD_PLANT AND AD.NO_WO = WI.NO_WO AND AD.NO_LINE = WI.NO_LINE AND AD.SEQ_WO = WI.SEQ_WO
 WHERE (''' + @P_YN_ASSEMBLE + ''' = ''N'' OR ISNULL(AI.QT_ITEM, 0) > ISNULL(AD.QT_DATA, 0))
 ORDER BY PV.SEQ_WO ASC'

PRINT @V_QUERY

EXEC SP_EXECUTESQL @V_QUERY

