USE [NEOE]
GO
/****** Object:  StoredProcedure [NEOE].[SP_CZ_PR_ASSEMBLING_MNG_JSON]    Script Date: 2023-04-25 ¿ÀÈÄ 4:06:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_PR_ASSEMBLING_MNG_JSON]          
(
	@P_JSON			NVARCHAR(MAX),
	@P_ID_USER		NVARCHAR(10)	
)  
AS
   
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

DELETE AD
FROM CZ_PR_ASSEMBLING_DATA AD
WHERE EXISTS (SELECT 1 
			  FROM OPENJSON(@P_JSON)
			  WITH
			  (
					CD_COMPANY      NVARCHAR(7),
					CD_PLANT        NVARCHAR(7),
					NO_WO			NVARCHAR(20),
					NO_LINE			NUMERIC(5, 0),
					SEQ_WO			NUMERIC(5, 0),
					CD_PITEM        NVARCHAR(20),
					SEQ_ITEM		NUMERIC(5, 0),
					JSON_FLAG		NVARCHAR(1)
			  ) JS
			  WHERE JS.JSON_FLAG = 'D'
			  AND JS.CD_COMPANY = AD.CD_COMPANY
			  AND JS.CD_PLANT = AD.CD_PLANT
			  AND JS.NO_WO = AD.NO_WO
			  AND JS.NO_LINE = AD.NO_LINE
			  AND JS.SEQ_WO = AD.SEQ_WO
			  AND JS.CD_PITEM = AD.CD_PITEM
			  AND JS.SEQ_ITEM = AD.SEQ_ITEM)

INSERT INTO CZ_PR_ASSEMBLING_DATA
(
	CD_COMPANY,
	CD_PLANT,
	NO_WO,
	NO_LINE,
	SEQ_WO,
	CD_PITEM,
	SEQ_ITEM,
	NO_ID,
	NO_ID_C,
	NO_HEAT,
	NO_LOT,
	DT_ASSEMBLE,
	ID_INSERT,
	DTS_INSERT
)
SELECT CD_COMPANY,
	   CD_PLANT,
	   NO_WO,
	   NO_LINE,
	   SEQ_WO,
	   CD_PITEM,
	   SEQ_ITEM,
	   NO_ID,
	   NO_ID_C,
	   NO_HEAT,
	   NO_LOT,
	   NULL AS DT_ASSEMBLE,
	   @P_ID_USER,
	   NEOE.SF_SYSDATE(GETDATE())
FROM OPENJSON(@P_JSON)
WITH
(
	CD_COMPANY			NVARCHAR(7),
	CD_PLANT			NVARCHAR(7),
	NO_WO				NVARCHAR(20),
	NO_LINE				NUMERIC(5, 0),
	SEQ_WO				NUMERIC(5, 0),
	CD_PITEM			NVARCHAR(20),
	SEQ_ITEM			NUMERIC(5, 0),
	NO_ID				NVARCHAR(20),
	NO_ID_C				NVARCHAR(20),
	NO_HEAT				NVARCHAR(200),
	NO_LOT				NVARCHAR(20),
	JSON_FLAG			NVARCHAR(1)
) JS
WHERE JS.JSON_FLAG = 'I'

UPDATE AD
SET AD.NO_ID_C = JS.NO_ID_C,
	AD.NO_HEAT = JS.NO_HEAT,
	AD.NO_LOT = JS.NO_LOT,
	AD.ID_UPDATE = @P_ID_USERSP_CZ_PR_ASSEMBLING_MNGD_S
	AD.DTS_UPDATE = NEOE.SF_SYSDATE(GETDATE())
FROM CZ_PR_ASSEMBLING_DATA AD
JOIN OPENJSON(@P_JSON)
WITH
(
	CD_COMPANY			NVARCHAR(7),
	CD_PLANT			NVARCHAR(7),
	NO_WO				NVARCHAR(20),
	NO_LINE				NUMERIC(5, 0),
	SEQ_WO				NUMERIC(5, 0),
	CD_PITEM			NVARCHAR(20),
	SEQ_ITEM			NUMERIC(5, 0),
	NO_ID_C				NVARCHAR(20),
	NO_HEAT				NVARCHAR(200),
	NO_LOT				NVARCHAR(20),
	JSON_FLAG			NVARCHAR(1)
) JS
ON JS.CD_COMPANY = AD.CD_COMPANY AND JS.CD_PLANT = AD.CD_PLANT AND JS.NO_WO = AD.NO_WO AND JS.NO_LINE = AD.NO_LINE AND JS.SEQ_WO = AD.SEQ_WO AND JS.CD_PITEM = AD.CD_PITEM AND JS.SEQ_ITEM = AD.SEQ_ITEM
WHERE JS.JSON_FLAG = 'U'

