USE [NEOE]
GO
/****** Object:  StoredProcedure [NEOE].[SP_CZ_PR_ASSEMBLING_MNG_S]    Script Date: 2023-05-08 오전 10:59:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [NEOE].[SP_CZ_PR_ASSEMBLING_MNG_S]          
(
	@P_CD_COMPANY		NVARCHAR(7),
	@P_CD_PLANT			NVARCHAR(7),
	@P_CD_ITEM			NVARCHAR(20),
	@P_NO_WO			NVARCHAR(20),
	@P_NO_SO			NVARCHAR(20),
	@P_YN_END			NVARCHAR(1)
)  
AS
   
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT 'N' AS S,
	   WO.NO_WO,
	   WR.NO_LINE,
	   WR.CD_OP,
	   OP.NM_OP,
	   WO.CD_ITEM,
	   MI.NM_ITEM,
	   WO.QT_ITEM,
	   WR.QT_WIP,
	   WI.QT_ASSEMBLING,
	   WR.QT_WORK
FROM PR_WO WO
JOIN PR_WO_ROUT WR ON WR.CD_COMPANY = WO.CD_COMPANY AND WR.NO_WO = WO.NO_WO
LEFT JOIN PR_WCOP OP ON OP.CD_COMPANY = WR.CD_COMPANY AND OP.CD_WC = WR.CD_WC AND OP.CD_WCOP = WR.CD_WCOP
LEFT JOIN MA_PITEM MI ON MI.CD_COMPANY = WO.CD_COMPANY AND MI.CD_PLANT = WO.CD_PLANT AND MI.CD_ITEM = WO.CD_ITEM
LEFT JOIN (SELECT WI.CD_COMPANY, WI.NO_WO, WI.NO_LINE,
		   	      SUM(CASE WHEN AI.QT_ITEM = AD.QT_DATA THEN 1 ELSE 0 END) AS QT_ASSEMBLING 
		   FROM PR_WO WO
		   JOIN CZ_PR_WO_INSP WI ON WI.CD_COMPANY = WO.CD_COMPANY AND WI.NO_WO = WO.NO_WO
		   LEFT JOIN (SELECT AI.CD_COMPANY, AI.CD_PLANT, AI.CD_ITEM,
                             SUM(AI.QT_ITEM) AS QT_ITEM       
                      FROM CZ_PR_ASSEMBLING_ITEM AI
                      GROUP BY AI.CD_COMPANY, AI.CD_PLANT, AI.CD_ITEM) AI
           ON AI.CD_COMPANY = WO.CD_COMPANY AND AI.CD_PLANT = WO.CD_PLANT AND AI.CD_ITEM = WO.CD_ITEM
           LEFT JOIN (SELECT AD.CD_COMPANY, AD.CD_PLANT, AD.NO_WO, AD.NO_LINE, AD.SEQ_WO,
                             COUNT(1) AS QT_DATA
                      FROM CZ_PR_ASSEMBLING_DATA AD
                      GROUP BY AD.CD_COMPANY, AD.CD_PLANT, AD.NO_WO, AD.NO_LINE, AD.SEQ_WO) AD
           ON AD.CD_COMPANY = WI.CD_COMPANY AND AD.CD_PLANT = WO.CD_PLANT AND AD.NO_WO = WI.NO_WO AND AD.NO_LINE = WI.NO_LINE AND AD.SEQ_WO = WI.SEQ_WO
		   WHERE WI.NO_INSP = 996
		   GROUP BY WI.CD_COMPANY, WI.NO_WO, WI.NO_LINE) WI
ON WI.CD_COMPANY = WO.CD_COMPANY AND WI.NO_WO = WO.NO_WO AND WI.NO_LINE = WR.NO_LINE
WHERE WO.CD_COMPANY = @P_CD_COMPANY
AND WO.CD_PLANT = @P_CD_PLANT
AND OP.NM_OP LIKE '%조립%'
AND (WR.QT_WIP > 0 OR @P_YN_END = 'N')
AND (ISNULL(@P_CD_ITEM, '') = '' OR WO.CD_ITEM = @P_CD_ITEM)
AND (ISNULL(@P_NO_WO, '') = '' OR WO.NO_WO = @P_NO_WO)
AND (ISNULL(@P_NO_SO, '') = '' OR EXISTS (SELECT 1 
										  FROM CZ_PR_SA_SOL_PR_WO_MAPPING SW
										  WHERE SW.CD_COMPANY = WO.CD_COMPANY
										  AND SW.CD_PLANT = WO.CD_PLANT
										  AND SW.NO_WO = WO.NO_WO
										  AND SW.NO_SO = @P_NO_SO))
AND EXISTS (SELECT 1 
            FROM CZ_PR_WO_REQ_D WD
            WHERE WD.CD_COMPANY = WO.CD_COMPANY
            AND WD.NO_WO = WO.NO_WO)

