USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_OUTSTANDING_INVOICE_RPT_S]    Script Date: 2017-12-06 오후 3:18:17 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER PROCEDURE [NEOE].[SP_CZ_SA_OUTSTANDING_INV_RPT_S]          
(  
	@P_CD_COMPANY		NVARCHAR(7),
	@P_DT_MONTH			NVARCHAR(6),
	@P_CD_PARTNER		NVARCHAR(20)
)  
AS
   
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT OI.CD_PARTNER,
	   MP.LN_PARTNER,
	   OI.AM_IV,
	   OI.AM_RCP,
	   OI1.AM_REMAIN AS AM_REMAIN_BEFORE,
	   OI.AM_REMAIN,
	   (ISNULL(OI.AM_REMAIN, 0) - ISNULL(OI1.AM_REMAIN, 0)) AS AM_REMAIN_DIFF,
	   OI.QT_REMAIN,
	   OI.AM_IV_MONTH,
	   OI.QT_IV_MONTH,
	   OI.AM_RCP_MONTH,
	   OI.QT_RCP_MONTH,
	   OI.DT_RETURN,
	   OI.DT_REMAIN,
	   ISNULL(ROUND(CASE WHEN (ISNULL(OI1.AM_REMAIN, 0) + ISNULL(OI.AM_IV_MONTH, 0)) = 0 THEN 0 
																						 ELSE ((ISNULL(OI.AM_RCP_MONTH, 0) / (ISNULL(OI1.AM_REMAIN, 0) + ISNULL(OI.AM_IV_MONTH, 0))) * 100) END, 2), 0) AS RT_RETURN
FROM CZ_SA_OUTSTANDING_INV OI
LEFT JOIN MA_PARTNER MP ON MP.CD_COMPANY = OI.CD_COMPANY AND MP.CD_PARTNER = OI.CD_PARTNER
LEFT JOIN (SELECT CD_COMPANY,
				  CD_PARTNER,
				  AM_REMAIN,
				  QT_REMAIN 
		   FROM CZ_SA_OUTSTANDING_INV
		   WHERE DT_MONTH = LEFT(CONVERT(NVARCHAR(8), DATEADD(MM, -1, @P_DT_MONTH + '01'), 112), 6)) OI1
ON OI1.CD_COMPANY = OI.CD_COMPANY AND OI1.CD_PARTNER = OI.CD_PARTNER
WHERE OI.CD_COMPANY = @P_CD_COMPANY
AND OI.DT_MONTH = @P_DT_MONTH
AND (ISNULL(@P_CD_PARTNER, '') = '' OR OI.CD_PARTNER = @P_CD_PARTNER)

GO

