USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_OUTSTANDING_INVOICE_RPT_IV_S]    Script Date: 2017-12-06 오후 5:51:04 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




ALTER PROCEDURE [NEOE].[SP_CZ_SA_OUTSTANDING_INV_RPT_IV_S]          
(  
	@P_CD_COMPANY		NVARCHAR(7),
	@P_CD_PARTNER		NVARCHAR(20),
	@P_DT_MONTH			NVARCHAR(6)
)  
AS
   
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT IH.CD_PARTNER,
	   IH.NO_IV,
	   IH.DT_PROCESS,
	   RH.DT_RCP,
	   (ISNULL(IH.AM_K, 0) + ISNULL(IH.VAT_TAX, 0)) AS AM_IV,
	   (ISNULL(RH.AM_RCP, 0)) AS AM_RCP,
	   ((ISNULL(IH.AM_K, 0) + ISNULL(IH.VAT_TAX, 0)) - ISNULL(RH.AM_RCP, 0)) AS AM_REMAIN,
	   (CASE WHEN ((ISNULL(IH.AM_K, 0) + ISNULL(IH.VAT_TAX, 0)) - ISNULL(RH.AM_RCP, 0)) = 0 THEN DATEDIFF(DAY, IH.DT_PROCESS, RH.DT_RCP) ELSE 0 END) AS DT_RETURN,
	   (CASE WHEN ((ISNULL(IH.AM_K, 0) + ISNULL(IH.VAT_TAX, 0)) - ISNULL(RH.AM_RCP, 0)) > 0 THEN DATEDIFF(DAY, IH.DT_PROCESS, GETDATE()) ELSE 0 END) AS DT_REMAIN 
FROM SA_IVH IH
LEFT JOIN (SELECT RH.CD_COMPANY,
		          RD.NO_IV,
		          MAX(RH.DT_RCP) AS DT_RCP,
		          SUM(RD.AM_RCP) AS AM_RCP
		   FROM SA_RCPH RH
		   LEFT JOIN (SELECT RD.CD_COMPANY, RD.NO_RCP, RD.NO_TX AS NO_IV,
  		     		    (ISNULL(RD.AM_RCP_TX, 0) + ISNULL(RD.AM_PL, 0)) AS AM_RCP
		   			  FROM SA_RCPD RD 
		   			  UNION ALL
		   			  SELECT BD.CD_COMPANY, BD.NO_RCP, BD.NO_IV,
  		     			 (ISNULL(BD.AM_RCPS, 0) + ISNULL(BD.AM_PL, 0)) AS AM_RCP
		   			  FROM SA_BILLSD BD) RD
		   ON RD.CD_COMPANY = RH.CD_COMPANY AND RD.NO_RCP = RH.NO_RCP
		   WHERE RD.NO_IV IS NOT NULL
		   AND LEFT(RH.DT_RCP, 6) <= @P_DT_MONTH
		   GROUP BY RH.CD_COMPANY, RD.NO_IV) RH
ON RH.CD_COMPANY = IH.CD_COMPANY AND RH.NO_IV = IH.NO_IV
WHERE IH.CD_COMPANY = @P_CD_COMPANY
AND IH.CD_PARTNER = @P_CD_PARTNER
AND LEFT(IH.DT_PROCESS, 6) <= @P_DT_MONTH
ORDER BY IH.DT_PROCESS DESC


GO

