USE [NEOE]
GO

/****** Object:  Table [NEOE].[CZ_QU_INSP_SCHEDULE]    Script Date: 2021-05-06 오전 9:03:04 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [NEOE].[CZ_QU_INSP_SCHEDULE](
	[CD_COMPANY] [nvarchar](7) NOT NULL,
	[NO_SO] [nvarchar](20) NOT NULL,
	[TP_COMPANY] [nvarchar](4) NOT NULL,
	[DT_INSP] [nvarchar](8) NOT NULL,
	[TP_INSP] [nvarchar](4) NULL,
	[TP_CONTENTS] [nvarchar](4) NULL,
	[TP_RESULT] [nvarchar](4) NULL,
	[NO_CERT] [nvarchar](200) NULL,
	[DC_RMK] [nvarchar](500) NULL,
	[ID_INSERT] [nvarchar](15) NULL,
	[DTS_INSERT] [nvarchar](14) NULL,
	[ID_UPDATE] [nvarchar](15) NULL,
	[DTS_UPDATE] [nvarchar](14) NULL,
 CONSTRAINT [PK_CZ_QU_INSP_SCHEDULE] PRIMARY KEY CLUSTERED 
(
	[CD_COMPANY] ASC,
	[NO_SO] ASC,
	[TP_COMPANY] ASC,
	[DT_INSP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


