USE [NEOE]
GO

/****** Object:  Table [NEOE].[CZ_MA_HULL_HGS_EQ_COUNT]    Script Date: 2020-12-28 오후 4:10:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [NEOE].[CZ_MA_HULL_HGS_EQ_COUNT](
	[NO_IMO] [nvarchar](7) NOT NULL,
	[SERVICEEQ] [nvarchar](50) NOT NULL,
	[HULLNO] [nvarchar](50) NOT NULL,
	[SANCTION] [nvarchar](50) NULL,
	[SHIPNAME] [nvarchar](100) NULL,
	[CATEGORY] [nvarchar](50) NULL,
	[TYPE] [nvarchar](50) NULL,
	[POWERPRJ] [nvarchar](50) NULL,
	[PLANT] [nvarchar](50) NULL,
	[COUNT] [int] NULL,
	[YN_URGENT] [nvarchar](1) NULL,
 CONSTRAINT [PK_CZ_MA_HULL_HGS_EQ_COUNT] PRIMARY KEY CLUSTERED 
(
	[NO_IMO] ASC,
	[SERVICEEQ] ASC,
	[HULLNO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


