USE [NEOE]
GO

/****** Object:  Table [NEOE].[CZ_MA_HULL_ENGINE_LOG]    Script Date: 2020-09-02 오후 6:38:54 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [NEOE].[CZ_MA_HULL_ENGINE_LOG](
	[NO_IMO] [nvarchar](10) NOT NULL,
	[NO_ENGINE] [int] NOT NULL,
	[CD_ENGINE] [nvarchar](3) NOT NULL,
	[NM_MODEL] [nvarchar](100) NULL,
	[CD_MAKER] [nvarchar](4) NULL,
	[DTS_DELETE] [nvarchar](14) NULL,
 CONSTRAINT [PK_CZ_MA_HULL_ENGINE_LOG] PRIMARY KEY CLUSTERED 
(
	[NO_IMO] ASC,
	[NO_ENGINE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

