USE [NEOE]
GO

/****** Object:  Table [NEOE].[CZ_MA_HULL_HGS_CUSTOMER]    Script Date: 2020-12-28 오후 4:09:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [NEOE].[CZ_MA_HULL_HGS_CUSTOMER](
	[NO_IMO] [nvarchar](7) NOT NULL,
	[HULL_NO] [nvarchar](50) NOT NULL,
	[SERVICEEQ] [nvarchar](50) NOT NULL,
	[CD_CUSTOMER] [nvarchar](10) NOT NULL,
 CONSTRAINT [PK_CZ_MA_HULL_HGS_CUSTOMER] PRIMARY KEY CLUSTERED 
(
	[NO_IMO] ASC,
	[HULL_NO] ASC,
	[SERVICEEQ] ASC,
	[CD_CUSTOMER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


