USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_GI_STOCK_SUB_S]    Script Date: 2015-12-09 오후 4:59:40 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER PROCEDURE [NEOE].[SP_CZ_SA_GI_STOCK_S]
(
	@P_CD_COMPANY		 NVARCHAR(MAX),
	@P_DT_GIR_FROM       NVARCHAR(8),
	@P_DT_GIR_TO         NVARCHAR(8),
	@P_YN_GI_STOCK		 NVARCHAR(1) = 'N',
	@P_YN_PACK_ORDER	 NVARCHAR(1) = 'N',
	@P_NO_GIR			 NVARCHAR(20) = '',
	@P_NO_SO			 NVARCHAR(20) = '',
	@P_STA_GIR			 NVARCHAR(1),
	@P_TP_GIR			 NVARCHAR(3)
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

WITH A AS
(
	SELECT GL.CD_COMPANY,
		   GH.CD_PARTNER,
		   MH.NO_IMO,
	 	   MH.NO_HULL,
		   MH.NM_VESSEL,
		   GH.DT_GIR,
		   GL.NO_GIR,
		   GL.SEQ_GIR,
		   GL.NO_SO,
		   GL.SEQ_SO,
		   GL.CD_ITEM,
		   MI.NM_ITEM,
		   MI.STND_ITEM,
		   MI.CD_ZONE,
		   GL.QT_GIR,
		   GL.QT_GIR_STOCK,
		   (CASE GL.YN_GI_STOCK WHEN 'Y' THEN '완료'
							    WHEN 'P' THEN '이동'
								ELSE '미처리' END) AS TP_GI_STOCK,
		   NEOE.FN_CZ_GET_STOCK_QTY (GL.CD_COMPANY, CONVERT(CHAR(8), GETDATE(), 112), GH.CD_PLANT, GL.CD_ITEM) AS QT_INV,
		   ISNULL(PB.QT_PACK_BEFORE, 0) AS QT_PACK_BEFORE,
		   ISNULL(PB.QT_GIR_BEFORE, 0) AS QT_GIR_BEFORE,
		   (CASE WHEN (ISNULL(PB.QT_PACK_BEFORE, 0) - ISNULL(PB.QT_GIR_BEFORE, 0)) <= 0 THEN ISNULL(GL.QT_GIR_STOCK, 0)
																						ELSE (ISNULL(GL.QT_GIR_STOCK, 0) - (ISNULL(PB.QT_PACK_BEFORE, 0) - ISNULL(PB.QT_GIR_BEFORE, 0))) END) AS QT_WORK,
		   ISNULL(PL.QT_GIR, 0) AS QT_GIR_PACK,
		   ISNULL(PL.QT_GIR_STOCK, 0) AS QT_GIR_STOCK_PACK,
		   ISNULL(PL.QT_PACK, 0) AS QT_PACK,
		   ISNULL(PL.QT_PACK_STOCK, 0) AS QT_PACK_STOCK,
		   GL.ID_GI_STOCK,
		   GL.DTS_GI_STOCK,
		   '001' AS TP_GIR,
		   GD.CD_DELIVERY_TO,
		   MP.LN_PARTNER AS NM_DELIVERY_TO,
		   GD.CD_MAIN_CATEGORY,
		   MD.NM_SYSDEF AS NM_MAIN_CATEGORY,
		   GD.CD_SUB_CATEGORY,
		   MD1.NM_SYSDEF AS NM_SUB_CATEGORY,
		   GD.DT_START,
		   GH.STA_GIR
	FROM SA_GIRL GL
	JOIN SA_GIRH GH ON GH.CD_COMPANY = GL.CD_COMPANY AND GH.NO_GIR = GL.NO_GIR
	JOIN MA_PITEM MI ON MI.CD_COMPANY = GL.CD_COMPANY AND MI.CD_PLANT = GH.CD_PLANT AND MI.CD_ITEM = GL.CD_ITEM AND MI.CLS_ITEM = '009'
	LEFT JOIN CZ_SA_GIRH_WORK_DETAIL GD ON GD.CD_COMPANY = GL.CD_COMPANY AND GD.NO_GIR = GL.NO_GIR
	LEFT JOIN CZ_MA_HULL MH ON MH.NO_IMO = GD.NO_IMO
	LEFT JOIN CZ_MA_DELIVERY MP ON MP.CD_COMPANY = GD.CD_COMPANY AND MP.CD_PARTNER = GD.CD_DELIVERY_TO
	LEFT JOIN MA_CODEDTL MD ON MD.CD_COMPANY = GD.CD_COMPANY AND MD.CD_FIELD = 'CZ_SA00006' AND MD.CD_SYSDEF = GD.CD_MAIN_CATEGORY
	LEFT JOIN MA_CODEDTL MD1 ON MD1.CD_COMPANY = GD.CD_COMPANY AND MD1.CD_FIELD = MD.CD_FLAG1 AND MD1.CD_SYSDEF = GD.CD_SUB_CATEGORY
	LEFT JOIN (SELECT PL.CD_COMPANY, PL.NO_SO, PL.SEQ_SO,
					  SUM(PL.QT_GIR) AS QT_GIR,
					  SUM(ISNULL(PL.QT_GIR_STOCK, 0)) AS QT_GIR_STOCK,
					  SUM(CASE WHEN ISNULL(PH.STA_GIR, '') = 'C' THEN PL.QT_GIR ELSE 0 END) AS QT_PACK,
					  SUM(CASE WHEN ISNULL(PH.STA_GIR, '') = 'C' THEN ISNULL(PL.QT_GIR_STOCK, 0) ELSE 0 END) AS QT_PACK_STOCK
			   FROM CZ_SA_GIRH_PACK PH
			   LEFT JOIN CZ_SA_GIRH_PACK_DETAIL PD ON PD.CD_COMPANY = PH.CD_COMPANY AND PD.NO_GIR = PH.NO_GIR
			   LEFT JOIN CZ_SA_GIRL_PACK PL ON PL.CD_COMPANY = PH.CD_COMPANY AND PL.NO_GIR = PH.NO_GIR
			   WHERE PD.CD_PACK_CATEGORY = '001'
			   GROUP BY PL.CD_COMPANY, PL.NO_SO, PL.SEQ_SO) PL
	ON PL.CD_COMPANY = GL.CD_COMPANY AND PL.NO_SO = GL.NO_SO AND PL.SEQ_SO = GL.SEQ_SO
	LEFT JOIN (SELECT SL.CD_COMPANY, SL.NO_SO, SL.SEQ_SO, GL.NO_GIR, GL.SEQ_GIR,
					  (SELECT SUM(PL.QT_GIR_STOCK) AS QT_GIR_STOCK 
					   FROM CZ_SA_GIRL_PACK PL
					   JOIN CZ_SA_GIRH_PACK PH ON PH.CD_COMPANY = PL.CD_COMPANY AND PH.NO_GIR = PL.NO_GIR
					   LEFT JOIN CZ_SA_GIRH_PACK_DETAIL PD ON PD.CD_COMPANY = PH.CD_COMPANY AND PD.NO_GIR = PH.NO_GIR
					   WHERE PL.CD_COMPANY = SL.CD_COMPANY
					   AND PL.NO_SO = SL.NO_SO
					   AND PL.SEQ_SO = SL.SEQ_SO
					   AND PD.CD_PACK_CATEGORY = '001'
					   AND PH.DTS_INSERT < MAX(GH1.DTS_INSERT)) AS QT_PACK_BEFORE,
					  (SELECT SUM(GL.QT_GIR_STOCK) AS QT_GIR_STOCK 
					   FROM SA_GIRL GL
					   JOIN SA_GIRH GH ON GH.CD_COMPANY = GL.CD_COMPANY AND GH.NO_GIR = GL.NO_GIR
					   WHERE GL.CD_COMPANY = SL.CD_COMPANY
					   AND GL.NO_SO = SL.NO_SO
					   AND GL.SEQ_SO = SL.SEQ_SO
					   AND GH.DTS_INSERT < MAX(GH1.DTS_INSERT)) AS QT_GIR_BEFORE 
		   FROM SA_SOL SL
		   LEFT JOIN SA_GIRL GL ON GL.CD_COMPANY = SL.CD_COMPANY AND GL.NO_SO = SL.NO_SO AND GL.SEQ_SO = SL.SEQ_SO
		   LEFT JOIN SA_GIRH GH1 ON GH1.CD_COMPANY = GL.CD_COMPANY AND GH1.NO_GIR = GL.NO_GIR
		   GROUP BY SL.CD_COMPANY, SL.NO_SO, SL.SEQ_SO, GL.NO_GIR, GL.SEQ_GIR) PB
	ON PB.CD_COMPANY = GL.CD_COMPANY AND PB.NO_SO = GL.NO_SO AND PB.SEQ_SO = GL.SEQ_SO AND PB.NO_GIR = GL.NO_GIR AND PB.SEQ_GIR = GL.SEQ_GIR
	WHERE (ISNULL(@P_CD_COMPANY, '') = '' OR GH.CD_COMPANY IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_COMPANY))) 
	AND GH.DT_GIR BETWEEN @P_DT_GIR_FROM AND @P_DT_GIR_TO
	AND ISNULL(GH.STA_GIR, '') IN ('R', 'C')
	AND (ISNULL(@P_STA_GIR, '') = '' OR GH.STA_GIR = @P_STA_GIR)
	AND GL.QT_GIR_STOCK > 0
	AND (@P_YN_GI_STOCK = 'N' OR (@P_YN_GI_STOCK = 'Y' AND ISNULL(GL.YN_GI_STOCK, 'N') <> 'Y' AND ISNULL(GL.YN_GI_STOCK, 'N') <> 'P'))
	AND (@P_NO_GIR = '' OR GL.NO_GIR = @P_NO_GIR)
	AND (@P_NO_SO = '' OR GL.NO_SO = @P_NO_SO)
	UNION
	SELECT GL.CD_COMPANY,
		   GH.CD_PARTNER,
		   MH.NO_IMO,
	 	   MH.NO_HULL,
		   MH.NM_VESSEL,
		   GH.DT_GIR,
		   GL.NO_GIR,
		   GL.SEQ_GIR,
		   GL.NO_SO,
		   GL.SEQ_SO,
		   GL.CD_ITEM,
		   MI.NM_ITEM,
		   MI.STND_ITEM,
		   MI.CD_ZONE,
		   GL.QT_GIR,
		   GL.QT_GIR_STOCK,
		   (CASE GL.YN_GI_STOCK WHEN 'Y' THEN '완료'
							    WHEN 'P' THEN '이동'
								ELSE '미처리' END) AS TP_GI_STOCK,
		   NEOE.FN_CZ_GET_STOCK_QTY (GL.CD_COMPANY, CONVERT(CHAR(8), GETDATE(), 112), GH.CD_PLANT, GL.CD_ITEM) AS QT_INV,
		   0 AS QT_PACK_BEFORE,
		   0 AS QT_GIR_BEFORE,
		   ISNULL(GL.QT_GIR_STOCK, 0) AS QT_WORK,
		   GL.QT_GIR AS QT_GIR_PACK,
		   ISNULL(GL.QT_GIR_STOCK, 0) AS QT_GIR_STOCK_PACK,
		   (CASE WHEN ISNULL(GH.STA_GIR, '') = 'C' THEN GL.QT_GIR ELSE 0 END) AS QT_PACK,
		   (CASE WHEN ISNULL(GH.STA_GIR, '') = 'C' THEN ISNULL(GL.QT_GIR_STOCK, 0) ELSE 0 END) AS QT_PACK_STOCK,
		   GL.ID_GI_STOCK,
		   GL.DTS_GI_STOCK,
		   '002' AS TP_GIR,
		   GD.CD_COLLECT_FROM AS CD_DELIVERY_TO,
		   MP.LN_PARTNER AS NM_DELIVERY_TO,
		   GD.CD_PACK_CATEGORY AS CD_MAIN_CATEGORY,
		   MD.NM_SYSDEF AS NM_MAIN_CATEGORY,
		   GD.CD_SUB_CATEGORY,
		   MD1.NM_SYSDEF AS NM_SUB_CATEGORY,
		   GD.DT_START,
		   GH.STA_GIR
	FROM CZ_SA_GIRL_PACK GL
	JOIN CZ_SA_GIRH_PACK GH ON GH.CD_COMPANY = GL.CD_COMPANY AND GH.NO_GIR = GL.NO_GIR
	JOIN MA_PITEM MI ON MI.CD_COMPANY = GL.CD_COMPANY AND MI.CD_PLANT = GH.CD_PLANT AND MI.CD_ITEM = GL.CD_ITEM AND MI.CLS_ITEM = '009'
	LEFT JOIN CZ_SA_GIRH_PACK_DETAIL GD ON GD.CD_COMPANY = GL.CD_COMPANY AND GD.NO_GIR = GL.NO_GIR
	LEFT JOIN CZ_MA_HULL MH ON MH.NO_IMO = GD.NO_IMO
	LEFT JOIN CZ_MA_DELIVERY MP ON MP.CD_COMPANY = GD.CD_COMPANY AND MP.CD_PARTNER = GD.CD_COLLECT_FROM
	LEFT JOIN MA_CODEDTL MD ON MD.CD_COMPANY = GD.CD_COMPANY AND MD.CD_FIELD = 'CZ_SA00020' AND MD.CD_SYSDEF = GD.CD_PACK_CATEGORY
	LEFT JOIN MA_CODEDTL MD1 ON MD1.CD_COMPANY = GD.CD_COMPANY AND MD1.CD_FIELD = MD.CD_FLAG1 AND MD1.CD_SYSDEF = GD.CD_SUB_CATEGORY
	WHERE (ISNULL(@P_CD_COMPANY, '') = '' OR GH.CD_COMPANY IN (SELECT CD_STR FROM GETTABLEFROMSPLIT(@P_CD_COMPANY)))  
	AND GH.DT_GIR BETWEEN @P_DT_GIR_FROM AND @P_DT_GIR_TO
	AND ISNULL(GH.STA_GIR, '') IN ('R', 'C')
	AND GD.CD_PACK_CATEGORY = '001'
    AND (ISNULL(@P_STA_GIR, '') = '' OR GH.STA_GIR = @P_STA_GIR)
	AND GL.QT_GIR_STOCK > 0
	AND (@P_YN_GI_STOCK = 'N' OR (@P_YN_GI_STOCK = 'Y' AND ISNULL(GL.YN_GI_STOCK, 'N') <> 'Y' AND ISNULL(GL.YN_GI_STOCK, 'N') <> 'P'))
	AND (@P_NO_GIR = '' OR GL.NO_GIR = @P_NO_GIR)
	AND (@P_NO_SO = '' OR GL.NO_SO = @P_NO_SO)
)

SELECT 'N' AS S,
	   A.CD_COMPANY,
	   MC.NM_COMPANY,
	   A.NO_SO,
	   A.SEQ_SO,
       A.NO_GIR,
	   A.SEQ_GIR,
	   A.DT_GIR,
	   A.NO_IMO,
	   A.NO_HULL,
	   A.NM_VESSEL,
	   A.CD_PARTNER,
	   MP.LN_PARTNER,
	   QL.NO_DSP,
	   A.CD_ITEM,
	   A.NM_ITEM,
	   A.STND_ITEM,
	   QL.NM_SUBJECT,
	   QL.CD_ITEM_PARTNER,
	   QL.NM_ITEM_PARTNER,
	   A.CD_ZONE,
	   ISNULL(SL.QT_SO, 0) AS QT_SO,
	   ISNULL(A.QT_GIR, 0) AS QT_GIR,
	   ISNULL(A.QT_GIR_STOCK, 0) AS QT_GIR_STOCK,
	   ISNULL(A.QT_INV, 0) AS QT_INV,
	   (ISNULL(A.QT_INV, 0) - ISNULL(A.QT_GIR_STOCK, 0)) AS QT_MINUS,
	   A.QT_PACK_BEFORE,
	   A.QT_GIR_BEFORE,
	   A.QT_WORK,
	   A.QT_GIR_PACK,
	   A.QT_GIR_STOCK_PACK,
	   A.QT_PACK,
	   A.QT_PACK_STOCK,
	   A.TP_GI_STOCK,
	   A.ID_GI_STOCK,
	   MU.NM_USER AS NM_GI_STOCK,
	   A.DTS_GI_STOCK,
	   A.TP_GIR,
	   A.CD_DELIVERY_TO,
	   A.NM_DELIVERY_TO,
	   A.CD_MAIN_CATEGORY,
	   A.NM_MAIN_CATEGORY,
	   A.CD_SUB_CATEGORY,
	   A.NM_SUB_CATEGORY,
	   A.DT_START,
	   A.STA_GIR
FROM A
LEFT JOIN SA_SOL SL ON SL.CD_COMPANY = A.CD_COMPANY AND SL.NO_SO = A.NO_SO AND SL.SEQ_SO = A.SEQ_SO
LEFT JOIN CZ_SA_QTNL QL ON QL.CD_COMPANY = A.CD_COMPANY AND QL.NO_FILE = A.NO_SO AND QL.NO_LINE = A.SEQ_SO
LEFT JOIN MA_PARTNER MP ON MP.CD_COMPANY = A.CD_COMPANY AND MP.CD_PARTNER = A.CD_PARTNER
LEFT JOIN MA_COMPANY MC ON MC.CD_COMPANY = A.CD_COMPANY
LEFT JOIN MA_USER MU ON MU.CD_COMPANY = A.CD_COMPANY AND MU.ID_USER = A.ID_GI_STOCK
WHERE (ISNULL(@P_TP_GIR, '') = '' OR A.TP_GIR = @P_TP_GIR)
AND (@P_YN_PACK_ORDER = 'N' OR (@P_YN_PACK_ORDER = 'Y' AND A.QT_WORK > 0))
ORDER BY A.CD_COMPANY, A.NO_SO, A.SEQ_SO, A.DT_GIR

GO