USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_SA_FORWARDER_RPT_S]    Script Date: 2016-01-27 오후 3:31:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

 
ALTER PROCEDURE [NEOE].[SP_CZ_SA_FORWARDER_RPT_S]
(
    @P_CD_COMPANY    NVARCHAR(7),
	@P_LANGUAGE		 NVARCHAR(5) = 'KR',
    @P_DT_GIR_FROM   NVARCHAR(8),
	@P_DT_GIR_TO     NVARCHAR(8),
	@P_NO_EMP		 NVARCHAR(10),
	@P_NO_GIR		 NVARCHAR(20)
)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT GH.DT_GIR,
       GH.NO_GIR,
	   STUFF((SELECT DISTINCT ',' + GL.NO_SO
			  FROM SA_GIRL GL
			  WHERE GL.CD_COMPANY = GH.CD_COMPANY
			  AND GL.NO_GIR = GH.NO_GIR
			  FOR XML PATH('')),1,1,'') AS NO_SO,
	   GH.NO_EMP,
	   ME.NM_KOR,
	   (CASE WHEN ISNULL(MC.NM_SYSDEF_E, '') = ''  THEN ISNULL(TH.PORT_ARRIVER, '')
			 WHEN ISNULL(TH.PORT_ARRIVER, '') = '' THEN MC.NM_SYSDEF_E
												   ELSE (ISNULL(TH.PORT_ARRIVER, '') + ' ' + MC.NM_SYSDEF_E) END) AS PORT_ARRIVER,
	   TH.PORT_ARRIVER,
	   GD.CD_SUB_CATEGORY,
	   (SELECT (CASE @P_LANGUAGE WHEN 'KR' THEN NM_SYSDEF
								 WHEN 'US' THEN NM_SYSDEF_E
								 WHEN 'JP' THEN NM_SYSDEF_JP
								 WHEN 'CH' THEN NM_SYSDEF_CH END)
		FROM MA_CODEDTL
		WHERE CD_COMPANY = GH.CD_COMPANY
		AND CD_FIELD = 'CZ_SA00011'
		AND CD_SYSDEF = GD.CD_SUB_CATEGORY) AS NM_SUB_CATEGORY,
	   GD.WEIGHT,
	   ISNULL(GF1.AM_PRICE, 0) AS AM_PRICE_001,
	   ISNULL(GF2.AM_PRICE, 0) AS AM_PRICE_002,
	   ISNULL(GF3.AM_PRICE, 0) AS AM_PRICE_004,
	   GD.CD_FORWARDER,
	   GF.NM_FORWARDER,
	   GF.AM_PRICE,
	   GD.FG_REASON,
	   (SELECT (CASE @P_LANGUAGE WHEN 'KR' THEN NM_SYSDEF
								 WHEN 'US' THEN NM_SYSDEF_E
								 WHEN 'JP' THEN NM_SYSDEF_JP
								 WHEN 'CH' THEN NM_SYSDEF_CH END)
		FROM MA_CODEDTL
		WHERE CD_COMPANY = GH.CD_COMPANY
		AND CD_FIELD = 'CZ_SA00031'
		AND CD_SYSDEF = GD.FG_REASON) AS NM_FG_REASON
FROM SA_GIRH GH
LEFT JOIN CZ_SA_GIRH_WORK_DETAIL GD ON GD.CD_COMPANY = GH.CD_COMPANY AND GD.NO_GIR = GH.NO_GIR 
LEFT JOIN CZ_SA_GIRH_FORWARDER GF ON GF.CD_COMPANY = GH.CD_COMPANY AND GF.NO_GIR = GH.NO_GIR AND GF.CD_FORWARDER = GD.CD_FORWARDER
LEFT JOIN CZ_SA_GIRH_FORWARDER GF1 ON GF1.CD_COMPANY = GH.CD_COMPANY AND GF1.NO_GIR = GH.NO_GIR AND GF1.CD_FORWARDER = '001'
LEFT JOIN CZ_SA_GIRH_FORWARDER GF2 ON GF2.CD_COMPANY = GH.CD_COMPANY AND GF2.NO_GIR = GH.NO_GIR AND GF2.CD_FORWARDER = '002'
LEFT JOIN CZ_SA_GIRH_FORWARDER GF3 ON GF3.CD_COMPANY = GH.CD_COMPANY AND GF3.NO_GIR = GH.NO_GIR AND GF3.CD_FORWARDER = '004'
LEFT JOIN MA_EMP ME ON ME.CD_COMPANY = GH.CD_COMPANY AND ME.NO_EMP = GH.NO_EMP
LEFT JOIN (SELECT CD_COMPANY, NO_GIR, MAX(NO_INV) AS NO_INV 
		   FROM SA_GIRL 
		   GROUP BY CD_COMPANY, NO_GIR) GL
ON GL.CD_COMPANY = GH.CD_COMPANY AND GL.NO_GIR = GH.NO_GIR
LEFT JOIN CZ_TR_INVH TH ON TH.CD_COMPANY = GL.CD_COMPANY AND TH.NO_INV = GL.NO_INV
LEFT JOIN MA_CODEDTL MC ON MC.CD_COMPANY = TH.CD_COMPANY AND MC.CD_FIELD = 'MA_B000020' AND MC.CD_SYSDEF = TH.ARRIVER_COUNTRY
WHERE GH.CD_COMPANY = @P_CD_COMPANY
AND GH.DT_GIR BETWEEN @P_DT_GIR_FROM AND @P_DT_GIR_TO
AND GD.CD_MAIN_CATEGORY = '003'
AND (GD.CD_SUB_CATEGORY = '001' OR GD.CD_SUB_CATEGORY = '002')
AND (ISNULL(@P_NO_EMP, '') = '' OR GH.NO_EMP = @P_NO_EMP)
AND (ISNULL(@P_NO_GIR, '') = '' OR GH.NO_GIR = @P_NO_GIR)

GO