USE [NEOE]
GO

/****** Object:  StoredProcedure [NEOE].[SP_CZ_FI_BANK_SEND_RPTL_U]    Script Date: 2017-01-26 오후 6:56:41 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER PROCEDURE [NEOE].[SP_CZ_FI_BANK_SEND_RPTL_U]
(  
	@P_C_CODE			NVARCHAR(10),
	@P_TRANS_DATE		NVARCHAR(8),
	@P_TRANS_SEQ		NVARCHAR(16),
	@P_SEQ				NVARCHAR(16),
	@P_TRANS_ACCT_NO	NVARCHAR(40),
	@P_CLIENT_NOTE		NVARCHAR(100),
	@P_TRANS_NOTE		NVARCHAR(100),
	@P_TP_CHARGE		NVARCHAR(4),
	@P_TP_SEND_BY		NVARCHAR(4),
	@P_DC_RELATION		NVARCHAR(50)
)  
AS  

UPDATE BANK_SENDH
SET TRANS_ACCT_NO = @P_TRANS_ACCT_NO,
	CLIENT_NOTE = @P_CLIENT_NOTE,
	TRANS_NOTE = @P_TRANS_NOTE
WHERE C_CODE = @P_C_CODE
AND TRANS_DATE = @P_TRANS_DATE
AND TRANS_SEQ = @P_TRANS_SEQ
AND SEQ = @P_SEQ

UPDATE BANK_SENDD
SET TRANS_ACCT_NO = @P_TRANS_ACCT_NO,
	CLIENT_NOTE = @P_CLIENT_NOTE,
	TP_CHARGE = @P_TP_CHARGE,
	TP_SEND_BY = @P_TP_SEND_BY,
	DC_RELATION	= @P_DC_RELATION
WHERE C_CODE = @P_C_CODE
AND TRANS_DATE = @P_TRANS_DATE
AND TRANS_SEQ = @P_TRANS_SEQ
AND SEQ = @P_SEQ

GO

