USE [NEOE]
GO

/****** Object:  UserDefinedFunction [NEOE].[FN_CZ_GET_SIGNATURE_PATH]    Script Date: 2015-12-03 오후 1:34:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER OFF
GO


ALTER FUNCTION [NEOE].[FN_CZ_GET_SIGNATURE_PATH]
(
	@P_SERVER_KEY	NVARCHAR(50),
	@P_CD_COMPANY	NVARCHAR(7),
	@P_NO_EMP		NVARCHAR(10)
)

RETURNS VARCHAR(MAX)
AS
BEGIN
	DECLARE	@V_SERVER_PATH NVARCHAR(MAX)
	DECLARE	@V_FILE_NAME NVARCHAR(MAX)
	DECLARE	@V_SIGN_PATH NVARCHAR(MAX)

	SELECT @V_SERVER_PATH = ASSEMBLY_HOST_SERVER
	FROM CM_SERVER_CONFIG WITH(NOLOCK) 
	WHERE SERVER_KEY = @P_SERVER_KEY

	SELECT @V_FILE_NAME = DC_SIGN
	FROM HR_PHOTO WITH(NOLOCK)
	WHERE CD_COMPANY = @P_CD_COMPANY
	AND NO_EMP = @P_NO_EMP
	
	IF ISNULL(@V_FILE_NAME, '') = ''
		SET @V_SIGN_PATH = ''
	ELSE
		SET @V_SIGN_PATH = ISNULL(@V_SERVER_PATH, '') + '/shared/image/human/sign/' + ISNULL(@P_CD_COMPANY, '') + '/' + ISNULL(@V_FILE_NAME, '')

	RETURN @V_SIGN_PATH
END

GO

